### ISSUE TITLE
Combination of for_each and group_by

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1002]
Right now `for_each` cannot be used with `group_by`. More specifically,

* `for_each` repeat input files
* `group_by` repeat input files

The following scenario will fail:

```
[10]
input: for_each={'a': range(5)}, group_by='2'
```
because it applies `group_by` to an empty input file list. It would make sense to apply `group_by` to the substeps defined by `for_each`.

**Comment by BoPeng** [comment]
Note that

```
[10]
input: 'input1.txt', 'input2.txt', for_each=[{'a': range(5)}], group_by='1'
print(f'{_input} {a}')
```
works as
```
input1.txt 0
input2.txt 0
input1.txt 1
input2.txt 1
input1.txt 2
input2.txt 2
input1.txt 3
input2.txt 3
input1.txt 4
input2.txt 4
```
so basically `for_each` is applied to the groups defined by `group_by`.

**Comment by gaow** [comment]
I think it makes more sense to first group by then apply for each, regardless of how they appear in the SoS `input` statement. Same deal for `paired_with`?

**Comment by BoPeng** [comment]
This is what we do now, but I was surprised by the error caused by 

```
[10]
input: for_each={'a': range(5)}, group_by='2'
```
and this does look like a legitimate use case.

**Comment by gaow** [comment]
> and this does look like a legitimate use case.

I'm not sure about that. `group_by` works with file input. there can be other ways to group parameters considering they can be provided with more flexibility? For example

```
[10]
a = [(i, i+1) for i in range(0,10,2)]
input: for_each = 'a'
```
?

**Comment by BoPeng** [comment]
What is so special about this example? `for_each` is legitimate here.

**Comment by BoPeng** [comment]
We use `group_by` generally for more than one input files. In which case it is ok to apply `for_each` after `group_by` because we are repeating for each "group".

When there is no input file or a single input file, `group_by` is meaningless and is currently not used. However, with `for_each`, we can create a large number of substeps defined by `for_each` variable, and using `group_by` to process them by group makes sense to me.

**Comment by gaow** [comment]
The point for this example is for empty `input` one would not need `group_by` to group parameters.

**Comment by BoPeng** [comment]
Yes, but them it makes sense to `group_by` the substeps created by `for_each`, say, using `for_each=3` to define groups for `i = 0, 2, 4`, and `i=6, 8, 10` etc.

**Comment by BoPeng** [comment]
Sorry, I think what I said does not make sense because we are sending a single `_a` to the substep, not a list.

**Comment by gaow** [comment]
Well unlike for `input` files, there is always a chance for us to preprocess parameters into tuples that essentially is a type of `group_by`. This is what I do in practice anyways. tuples seem to have well defined behavior that I can trust on.
