### ISSUE TITLE
Purge for current project broken

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1011]
I still see some files under `~/.sos/task` with extension `*.task`. I suppose those were not deleted because I interrupted the sos job submission with `ctrl-c`? How can we ensure under all circumstances those tempory `task` files will be removed at the end of an SoS run, if not earlier?

**Comment by BoPeng** [comment]
Tasks older than 1 month will be automatically removed. Or you can remove them manually with sos purge by age status etc.

**Comment by gaow** [comment]
Okay ... is there any harm removing `completed` and `failed` tasks constantly? I'm thinking of setting up a `cronstab` to do it every day for my cluster queue. Otherwise it is very easy to go over the file count limit on my end.

**Comment by gaow** [comment]
On the documentation page:

```
> sos purge -q cluster

removes all tasks related to current project from a remote cluster,
```

here, project means wherever the local `.sos` folder is located (and in my `cronstab` i'll have to first `cd` to the folder) and the command will not impact other ongoing SoS processes, right?

**Comment by BoPeng** [comment]
Yes. It will find all tasks related to the current directory ( under .sos) and remove them from remote host. —all will remove all tasks.  I am not quite sure if getting task under current directory works after all recent changes though.

**Comment by gaow** [comment]
>  I am not quite sure if getting task under current directory works after all recent changes though.

I do not think it works. I created a very simple setting:

```
[GW] tree -a
.
├── test1
│   ├── .sos
│   │   ├── transcript.txt
│   │   └── workflow_signatures.db
│   └── test.sos
└── test2
    ├── .sos
    │   ├── transcript.txt
    │   └── workflow_signatures.db
    └── test.sos
```

where `test.sos` is just:

```
[GW] cat test1/test.sos
[1]
task:
bash:
  echo test1
```

and is `echo test2` for `test2` folder. I run sos under both folders. Then under `./test1` I run `sos purge -s completed`. It ends up removing both tasks. Should i open a separate issue or it is an easy fix?

**Comment by BoPeng** [comment]
Yes, I will create a test and fix it. sos used to get tasks from `.sig` files and they are gone now.

**Comment by gaow** [comment]
I'm not sure if it works as expected now. I run `sos purge -s completed` in my current directory. It cleaned out about 300 out of my 600 tasks in `~/.sos/task`. When I run it again I get `INFO: No matching tasks`.  But some of the remaining tasks files in `~/.sos/task` do have status `completed`. I'm sure I only have worked with one directory today. 

However if I run `sos purge -s completed --all`, all tasks are removed, including some with status not "completed" (eg one of the tasks was labelled status `new` but was removed from the command above). 

It might be hard to come up with MWE for this. But I'll keep observing, if there is nothing obviously problematic on your end.

**Comment by gaow** [comment]
I see. Yes I think the current behavior makes sense. I guess I should use the updated SoS to first generate tasks and purge, and report back if there is still an issue.

Initially I want to come up with some default `sos purge` command that I can put in `crontab`. But now I think it might actually help to run `sos purge -s completed` immediately  (manually) after execution of a workflow. Because that way `sos status` will only show me the problematic ones for me to look at deeper. The completed tasks for the current project will no longer be of interest. Does this make sense? If so, what is the point to keep completed tasks?

**Comment by BoPeng** [comment]
Yeah, `sos purge --all -s` was mishandled. I am adding a test.

**Comment by BoPeng** [comment]
Purge without —all removes tasks related to workflows executed under the current directory. I have been debating if I should do the same to sos status.

**Comment by gaow** [comment]
Yes I understand. But my current directory is the only project directory I have on the cluster since after removing `~/.sos`. And all tasks are completed. So I expect `sos purge -s completed` to remove everything. 

> I have been debating if I should do the same to sos status.

To only show current project? Absolutely. Otherwise it takes forever to check status. I never run `sos status` without job ID because it is not very informative to show everything.

**Comment by BoPeng** [comment]
To check tasks related to current directory ([this function](https://github.com/vatlab/SoS/blob/master/src/sos/signatures.py#L243)), just open a python shell and run

```
from sos.signatures import workflow_signatures
workflow_signatures.tasks()
```
if you do not see the submitted tasks here, it is either that you have accidentally removed .sos (so have incomplete record), or sos has failed to register the task under some circumstances.
