### ISSUE TITLE
Jobs in `showq` exceeds maximum running jobs

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1014]
I set `max_running_jobs` to `50` but in my `showq`:

```
$ showq | wc -l
104
```

But if I only show running jobs:

```
$ showq | grep R | wc -l
56
```
which is more or less correct. Is it also counting those submitted jobs? These jobs are in `PD` status and shows `submitted`, not `running`, in `sos status` command:

```
          JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
          48291581   broadwl M2_3aa86     gaow PD       0:00      1 (Priority)
          48291582   broadwl M2_62275     gaow PD       0:00      1 (Priority)
          48291583   broadwl M2_0c859     gaow PD       0:00      1 (Priority)
```

I wonder if they are not considered when checking with `max_running_jobs`. Because it might not make sense to keep submitting when some existing jobs are in the queue. In an extreme case when no job ever runs then SoS will just keep submitting?

**Comment by BoPeng** [comment]
`max_running_jobs` controls number of running jobs and submitted jobs, so this does not look right to me.

**Comment by BoPeng** [comment]
When this happens, please run

```
sos status 
```
and count the actual number of running and submitted jobs. SoS status might be inconsistent with what PBS shows but that is another problem.

**Comment by gaow** [comment]
Seems to have been fixed now.
