### ISSUE TITLE
Rerun one task with updated specifications

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1015]
Out of my thousands of jobs, there is only one failed job due to running over maximum walltime. I was able to identify the job with `aborted` status and get its job tag. But I still need to rerun it just need to increase the `walltime`. I'm not sure how to do it. In order to rerun this one job I need to rerun the entire script, which is a lot of work on signature check. Do we have a way to only submit one task, eg: `sos execute M5_db0d470cd00a4d77`, with different setting of `cores`, `walltime`, `mem`, `trunk_size`, `tags` etc?

**Comment by BoPeng** [comment]
Good question. What I used to do is to rerun the entire step with different `walltime` etc. Completed jobs are ignored but in your case it can take a while to check signatures of all these tasks. I would find the failed job, gather its input etc, and use something like the following to rerun the job

```
input: ....

skip_if( sample_name != 'failed_sample')

task:
```

**Comment by BoPeng** [comment]
You an also get on the cluster and see if the corresponding `.sh` file is still there. These files were not cleaned so I was able to change the `.sh` file manually and submit manually. The file might still be there if the job fails in a way before tasks file absorb them.

**Comment by BoPeng** [comment]
Actually, upon reflection, I think no signature would be checked and sos would simply ignore completed tasks. However, I am not completely sure if this is the case now because of all the changes in task file and signatures. This should be something we decide, document, and tested.

**Comment by gaow** [comment]
In fact it might have to be 

```
sos execute task_id --cores ... -- walltime ... --mem .... --job_id ...
```

with `--job_id` because only 1 job out of the 5 jobs in that task has failed. I was able to get this from the `err` file:

```
slurmstepd-midway2-0031: error: *** JOB 48289843 ON midway2-0031 CANCELLED AT 2018-08-10T09:55:27 DUE TO TIME LIMIT ***
```

So from the file name I can figure out which task it is, and from the error message I know which job it is to rerun. All seems to be missing from user's prospective is a command like above.

**Comment by BoPeng** [comment]
At least that was the reason I kept all task files until a project is completed. Although tasks are always inside steps, steps do not have to have signatures. An obvious example is for steps that do not specify output. In this case, the tasks will be run and re-run the steps will always trigger rerun of tasks. In the current implementation, tasks will be rerun in this case but signatures inside tasks might left them quit directly (though they will also be queued in PBS etc).

I do not know an all-around good solution, but at least we are at a point when we should decide on a reasonable solution.

**Comment by gaow** [comment]
I see. Sounds reasonable. But:

> In the current implementation, tasks will be rerun in this case but signatures inside tasks might left them quit directly (though they will also be queued in PBS etc).

Does this go directly into `task_signature.db`? 

> At least that was the reason I kept all task files until a project is completed.

For my case I've got to clean it up very often because each run will generate lots of task files.

> In this case, the tasks will be run and re-run the steps will always trigger rerun of tasks.

I think this is a reasonable behavior from user's prospective. Without using `task` such steps will have to rerun anyways right? Then it is conceptually cleaner if remote behavior is consistent with local behavior.

**Comment by BoPeng** [comment]
> Does this go directly into task_signature.db?

There is no `task_signature.db`, task signatures are now embedded into task files so no signature will be left behind after the completion of tasks.

> For my case I've got to clean it up very often because each run will generate lots of task files.

Then if you do have signatures for each step, the task will not be rerun because it will never be reached. Changing your script with higher `walltime` and rerun should be suffice and I am working on a branch on concurrent signature checking.

> I think this is a reasonable behavior from user's prospective.

Yes but admins would hate you when you submit 1000 48 hr jobs and 999 of them quit in seconds.

**Comment by gaow** [comment]
> Then if you do have signatures for each step, the task will not be rerun because it will never be reached. 

Sure. This is what's happening now.

> Changing your script with higher walltime and rerun should be suffice and I am working on a branch on concurrent signature checking.

Yes that will be very helpful! If signature check is fast, then users will only need to run repeatedly `sos run` with adjusted `task` options until all is completed. 

Still it might worth including the actual script ran into the `*.task` file for sanity check? Because unlike return code 1 case when scripts in question will be copied to local `.sos`, nothing is left behind for these failed PBS jobs. Having them in `*.task` is ugly but is a place good fall-back to when there is really a need.

**Comment by BoPeng** [comment]
The sh file is embedded in task. I am on the road and cannot check if sos status -v4 shows it.

**Comment by gaow** [comment]
> The sh file is embedded in task. 

Great!

> cannot check if sos status -v4 shows it.

Unfortunately `-v4` does not show it
