### ISSUE TITLE
SoS submitter hang on cluster

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1018]
I've experienced various hanging behavior for the job submitter. "Hang" here means that job queue is empty but SoS refuses to move on. It looks like stuck on the current job submission, yet `ps -A | grep sos` shows nothing. With `ctrl-c` I can keyboard interrupt it.

There are now 2 types of hangs I can reliably reproduce. Hopefully by describing them you'll be able to make some MWE for your cluster:

1. When my job exceeds the `walltime`
2. When my specified directory for `err` and `out` files do not exist, eg:

```
      #SBATCH --output={cur_dir}/non_existing_dir/{job_name}.out
      #SBATCH --error={cur_dir}/non_existing_dir/{job_name}.err
```

I hope this is enough to reproduce it.

**Comment by BoPeng** [comment]
Hang instead of error out? Specifying err is not a good idea because sos only keeps the ones under sos tasks.

**Comment by BoPeng** [comment]
Your template need to specify sos locations.

**Comment by BoPeng** [comment]
The second problem seem to have nothing to do with sos. When you specify 

```
#SBATCH --output={cur_dir}/non_existing_dir/{job_name}.out
#SBATCH --error={cur_dir}/non_existing_dir/{job_name}.err
```
with non-existence dir, it is up to SLURM to decide what to do with this setting. sos can only make sure `~/.sos/tasks` exists.

**Comment by BoPeng** [comment]
For the first problem, sos sets the template according to `walltime`, but sos does not enforce walltime. (It has a queue option `max_walltime` but that has a different usage). The problem here is that cluster has different strategies in handling walltime (grace period) and it can be confusing if sos kills the job before PBS.

sos should detect the case when the job is terminated by PBS, because then the pulse thread will also be killed and sos should detect the case and mark it as canceled. I will see if this is still the case.

**Comment by gaow** [comment]
> it is up to SLURM to decide what to do with this setting. sos can only make sure ~/.sos/tasks exists.

I understand this. But how does this work on your system? On my system SLURM just die silently. Perhaps SoS hangs because SLURM did not give any feedback to it? Then this might be some behavior we need to evaluate and change?

**Comment by BoPeng** [comment]
Because SLURM reads the setting before executing it, it is likely that the `sos execute` command at the latter part of the script is not executed at all. Since sos knows that the job has been submitted, and the jobs has not been started (no pulse etc), it will assume that it is still queued by PBS.

**Comment by gaow** [comment]
>  it is likely that the sos execute command at the latter part of the script is not executed at all. 

I think you are right about it. Because the following does not work:

```
#SBATCH --output={cur_dir}/non_existing_dir/{job_name}.out
mkdir -p non_existing_dir
```

which indicates the `sos execute` part is not executed ...

**Comment by BoPeng** [comment]
SoS knows the job id returned from SLURM. A more robust method would be checking SLURM status periodically to detect this case. SoS currently does not do it because it lacks a way to translate SLURM status output to SoS status.

**Comment by BoPeng** [comment]
What is the output of `squeue --job ID` for jobs failed like this?

**Comment by BoPeng** [comment]
Shows nothing means something... this can be done but technical difficulties remain. I mean, `sos status` is currently fast but it would be very slow if sos has to query status of jobs from BPS for each `sos status` run, even if `pending` is the only status that needs further querying PBS.

**Comment by gaow** [comment]
Related to my stdout/stderr problem: are you suggesting that I should do something like:

```
            #PBS -o {home_dir}/.sos/tasks/{task}.out
            #PBS -e {home_dir}/.sos/tasks/{task}.err
```

then my stderr and stdout will get absorbed to the `task` file; and I should not save them to an arbitrary directory?

**Comment by BoPeng** [comment]
Yes, that is my suggestion, perhaps `$HOME` to allow shell expansion of `HOME` is better because SoS would expand `{home_dir}` to host-specific full directory with user name, which is arguable better be replaced with a generic `$HOME`.

**Comment by gaow** [comment]
I'll use other tickets to discuss this (long standing) issue.
