### ISSUE TITLE
`jnbinder` error with `_lock` file

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1020]
I cannot make an easy MWE for this one, so I hope the line of error below can already suggest where the bug is. I am running with the current master version for `jnbinder` to build one of my project website. I get this error with `-v4`:

```
DEBUG: Master received an exception
TRACE: Set step_name to default_3 of type <class 'str'>
  File "/opt/miniconda3/lib/python3.6/site-packages/sos/__main__.py", line 372, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.6/site-packages/sos/__main__.py", line 372, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
  File "/opt/miniconda3/lib/python3.6/site-packages/sos/workflow_executor.py", line 1404, in run
    raise exec_error
sos.workflow_executor.ExecuteError: [0f724187-7d83-4e99-8ea7-8e5b9e865fab]: [update-hp]: 'RuntimeInfo' object has no attribute '_lock'
[update-hp + update-nb + update-wf + upda]: 3 pending steps: update-nb, update-search, remove-obsolete
[default]: 1 pending step: default_4
ERROR: [0f724187-7d83-4e99-8ea7-8e5b9e865fab]: [update-hp]: 'RuntimeInfo' object has no attribute '_lock'
```
the `update-hp` step [looks like this](https://github.com/vatlab/jnbinder/blob/52c169412fed479d34d1034b4f30d03364a4e418/release#L156). Hopefully it is easy to spot the problem from the error message.

**Comment by BoPeng** [comment]
This is related to the signature rewrite. I am reducing it to a warning for this case and will investigate the problem later.

**Comment by gaow** [comment]
Okay now I get these:

```
WARNING: Releasing an non-existent or released lock for ce9f13fb1e7d6dcc.
WARNING: Releasing an non-existent or released lock for 685aad445e6a00e7.
WARNING: Releasing an non-existent or released lock for 93612ca62e1ee5a9.
```

I can see the case when `self._lock` is `None` (double release), but why some `RuntimeInfo` instances did not `_lock` attribute to start with -- how come they did not make the `.lock()` call? Anyways, please let me know what I can do to help debugging this better.

**Comment by BoPeng** [comment]
I know, but I have not got a chance to really look. The message means the lock is released without being locked so the use of lock is not paired correctly, or disrupted, or something. The patch just let you continue to use sos.

**Comment by gaow** [comment]
Okay I'm getting this in other projects, too. Rerunning some local jobs triggers it. Additionally, I have this line of warning:

```
WARNING: 1bbe894b5c63f27d: Releasing 15 slots from 1 available ones. Please report this bug to SoS developers.
```

**Comment by BoPeng** [comment]
For the lock releasing bug, there should be lines like

```
Lock acquired for output files ...
Lock released for output files...
```

It would be helpful if you could run in `-v4` and send me the complete logs.

**Comment by gaow** [comment]
Will try to reproduce when I get home in 1hr. But it is not always readily reproducible. Will try.

**Comment by BoPeng** [comment]
The recent patches will significantly reduce `workflow_signatures` traffic, but I guess cannot eliminate them.

**Comment by gaow** [comment]
I'm sorry I was still not able to reproduce the lines:

```
Lock acquired for output files ...
Lock released for output files...
```

I did use `-v4` earlier, could not reproduce the bug. I was just doing some analysis, reproduced the bug, and `ctrl-C` immediately, added `-v4` switch, still was able to reproduce. But did not see those lines above. Only the `non-existing or released lock` warning. This means something right? Sorry the file that has `-v4` piped in is gone due to a fresh run that overwrote it. Will try to collect it next time.

**Comment by gaow** [comment]
I get it again. Here is a log file from `-v4`:

[release.bug.txt](https://github.com/vatlab/SoS/files/2288717/release.bug.txt)

**Comment by BoPeng** [comment]
Thanks. There are 14 
```
Releasing an non-existent
```
lines before 14 correctly paired

```
Lock acquired for output files
Lock released for output files
```
so these must happened before the steps are executed. Checking.

**Comment by BoPeng** [comment]
I find the culprit. There is something like

```
try:
   if sig.validate():
       return
   sig.lock()
finally:
   sig.release()
```
so `sig.release` is called when `sig` passes validation.

Please rerun and let me know if you still see the warning.

**Comment by gaow** [comment]
I do not think I can reproduce the error now. But the error is not always reproducible anyways. Should we close the issue for now if you are very sure about the fix?

**Comment by BoPeng** [comment]
Yes, I am pretty sure. The bug happens at rerun so it is not always triggered.
