### ISSUE TITLE
Slowness preparing jobs

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1024]
Now I can provide a MWE on this! Here is the SoS script to reproduce:

```
[1]
input: glob.glob('*.txt'), group_by = 1, concurrent = True
output: dynamic(glob.glob("*.out"))
bash: expand = True
  touch {_input:n}.out
```

To see the problem, first go to an empty folder, type `touch {1..50000}.txt` in bash to create 50K test input files. Then run `sos run test.sos`. It takes forever to even get SoS started real processes, at least on my mechanical hard drive. This is a big problem now because previously I can analyze input of up to 50K scale and now I'm just trying to rerun my earlier analysis. Hopefully the bottleneck can be identified. It must be certainly signature related because I've not seen this before.

**Comment by BoPeng** [comment]
You see, even bash complains. :smile:

``` 
$ touch {1..50000}.txt
-bash: /usr/bin/touch: Argument list too long
```

**Comment by gaow** [comment]
Ha, not my bash though. Interesting ...

**Comment by BoPeng** [comment]
One of the biggest problems here is that after the execution of each substep, sos needs to `glob` all `.out` files, which increases linearly with increasing `_index`. So while my test here with `5000` files completes reasonably fast, `50000` can be hundreds of times slower.

Note that sos handles `*.out` and `*.txt` automatically so no `glob.glob` is needed.

**Comment by gaow** [comment]
Okay but why this was not a problem before? I've been using the same pipeline since some time ago. I believe the issue was recent.

> Note that sos handles *.out and *.txt automatically so no glob.glob is needed.

i did not try but my actual pattern was more complicated, eg `*/something/*`. That was why I thought I needed `glob`. i can try to see if SoS handles that pattern.

**Comment by BoPeng** [comment]
I mean, your script would be a lot faster with

```
input: '*.txt', group_by = 1, concurrent = True
output: _input.with_suffix('.out')
bash: expand = True
  touch {_output}
```
```
$ time sos run test
INFO: output:   1.out, 10.out, ... (5000 items)
INFO: Workflow default (ID=b959cc02ac21a43d) is executed successfully with 1 completed step and 5000 completed substeps.

real	1m21.507s
user	1m53.212s
sys	2m29.002s
```

**Comment by gaow** [comment]
Sure but in reality the input and output do not have one to one match. That was why I had to use glob ...

**Comment by BoPeng** [comment]
The reason was that file signatures were saved individually so each time only a new file needs to be checksumed. The current version put file signatures inside step signature so files needs to be checksumed again and again.

The reason is that sos do not expect overlapping output files from substeps, and it will actually error out if you do `output: 'same.out'` for steps with substeps. Your case is allowed only because it is dynamic so sos cannot prevent it. If output from substeps are distinct, keeping file signatures in step signature is a reasonable choice as it reduces repetition and reduces most transactions to a separate target database.

**Comment by BoPeng** [comment]
In reality, if `1.out` is removed, all substeps need to be rerun so it does not sound like a good arrangement anyway.

**Comment by gaow** [comment]
> The current version put file signatures inside step signature so files needs to be checksumed again and again.

I'm not sure if I get all the details, but this does not sound good. 

Also suppose I have dynamic input and output with index like : 

```
input: dynamic(some_files)
output: other_files[_index]
```

then SoS will know to check one file at a time rather than all of them over and over again? I can certainly make lots of my applications this style as you previously suggested. But I do have cases when dynamic is needed in both input and output.

**Comment by BoPeng** [comment]
Your best bet could be `-s ignore`

```
$ time sos run test -s ignore
INFO: output:   1.txt.out, 10.txt.out, ... (5000 items)
INFO: Workflow default (ID=47e6d11a062fe683) is executed successfully with 1 completed step and 5000 completed substeps.

real	1m13.566s
user	0m23.077s
sys	0m50.068s
```

**Comment by gaow** [comment]
I see. Okay that can get my analysis going now :) But is there a way out here -- combine the reasonable parts of the old and new implementations while still keeping the traffic low?

**Comment by BoPeng** [comment]
> I'm not sure if I get all the details, but this does not sound good.

The tech details is that we used to keep a separate signature for each input/output file, and we check these files when we create step signatures. md5 were not calculated if the signature already exists. When we switch to database, the target signature database become the busiest one with highest chance of collision and so I removed it in favor of keeping signatures in step signature. These means output files belonging to multiple substeps will be checksumed repeatedly, but "output belonging to multiple substeps" is dangerous and generally forbidden in sos. Just think this case

```
input: for_each={'n': range(100)}
output: [f'test_{x}.txt' for x in range(n)]
for file in _output:
    with open(file, 'a') as f:
        f.write(_index)
```
where the next substep will change the output of the previous substeps, so signatures will never work.

> will know to check one file at a time rather than all of them over and over again?

Yes, because there is only one output for each substep.

**Comment by BoPeng** [comment]
yes, each process can cache the md5 of processed files, in a database or in RAM, although this is only a optimization for a case that we try to avoid.

**Comment by gaow** [comment]
I see ... seems like a corner case bug. Still would be good to fix to avoid repeatedly checking step signatures unnecessarily.

**Comment by gaow** [comment]
An additional observation, perhaps related to this comment, is that rebuiding signatures can be very slow depending on network drive conditions. I've got a completed local workflow on a system with slow disk. I removed signature database and run again with `-s build`. It takes forever just for SoS to check and recover signatures -- for a simple step involving <5000 files it is now running 4min before moving on, and still counting! The same task completed quickly on SSD. So perhaps having some in-memory database is not generally a bad idea after all, not just for corner cases?

**Comment by BoPeng** [comment]
I agree...

**Comment by gaow** [comment]
Not sure if this is related to this issue or #1018 , but I'm using an interactive node on my cluster (first time running SoS on interactive node). I've got a step of my job done, involving `dynamic` output the same as above, but there are 70K of them. I'm now stuck at this:

![2018-08-22-14-56-40_scrot](https://user-images.githubusercontent.com/917985/44487306-980b3800-a61b-11e8-8c7c-c284147c4e0b.png)


And here are a few diagnostics:

```
[MW] date
Wed Aug 22 14:52:30 CDT 2018
[MW] ll .sos
total 1.5M
-rw-r--r-- 1 gaow pi-mstephens 180K Aug 22 14:30 step_signatures.db
-rw-rw-r-- 1 gaow pi-mstephens 155K Aug 22 14:31 transcript.txt
-rw-r--r-- 1 gaow pi-mstephens 1.2M Aug 22 14:43 workflow_signatures.db
[MW] ll ~/.sos
total 9.2M
drwxrwxr-x 2 gaow gaow 4.0K Aug 10 18:09 bin
-rw-r--r-- 1 gaow gaow 9.1M Aug 12 16:58 target_signatures.db
-rw-r--r-- 1 gaow gaow  64K Aug 22 14:30 step_signatures.db
-rw-rw-r-- 1 gaow gaow  973 Aug 22 14:31 3dae29f04e9643cf.status
drwxrwxr-x 3 gaow gaow  32K Aug 22 14:43 tasks
[MW] ps -A | grep sos
47132 pts/2    00:00:09 sos
47154 pts/2    00:00:08 sos
```

You see no database has been written to for about 10 minutes now. That is I'm looking at the hanging screen for 10min. However unlike #1018 I can still see `sos` processes. Is that still disk issues?

**Comment by BoPeng** [comment]
Just make sure. The tasks are running locally, not waiting for pbs, right. Note that even for local queue there is s max running limit so sos might be waiting for the queue to clear a bit before running more.

**Comment by gaow** [comment]
Oh sure yes those are local tasks. They are supposed to be done (I see 22 completed for my 22 chroms) and i got lots of dynamic output (~80K). The interactive compute node i'm on current only has those `sos` instances running, not Python processes for those tasks.

ps: still hanging as we speak.

**Comment by BoPeng** [comment]
What is the number of running and pending jobs if you run sos status?

**Comment by gaow** [comment]
```bash
[MW] git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
[MW] sos status
9cc490b4384923b3        3dae29f04e9643cf preprocess_2   Ran for 1 min   completed
b660debf995ab997        3dae29f04e9643cf preprocess_2   Ran for 2 min   completed
e61b3467c27dbabe        3dae29f04e9643cf preprocess_2   Ran for 2 min   completed
0d780fb2ac03d70d        3dae29f04e9643cf preprocess_2   Ran for 5 min   completed
aa34afae1c898712        3dae29f04e9643cf preprocess_2   Ran for 5 min   completed
b13b91bfaf364435        3dae29f04e9643cf preprocess_2   Ran for 5 min   completed
6dc89f06426127f4        3dae29f04e9643cf preprocess_2   Ran for 5 min   completed
5f9b9ebe9d2afbb3        3dae29f04e9643cf preprocess_2   Ran for 5 min   completed
6481886f5399cfa5        3dae29f04e9643cf preprocess_2   Ran for 5 min   completed
3f0e6becfa18647a        3dae29f04e9643cf preprocess_2   Ran for 5 min   completed
3ee34e16de3b41f9        3dae29f04e9643cf preprocess_2   Ran for 5 min   completed
a7b97b7657f420a8        3dae29f04e9643cf preprocess_2   Ran for 6 min   completed
bcb5889c9cd4d077        3dae29f04e9643cf preprocess_2   Ran for 6 min   completed
0871188a3ea7b103        3dae29f04e9643cf preprocess_2   Ran for 6 min   completed
e5df66c53209f8e7        3dae29f04e9643cf preprocess_2   Ran for 6 min   completed
904334909d5896dd        3dae29f04e9643cf preprocess_2   Ran for 8 min   completed
d463c0eb5dfde437        3dae29f04e9643cf preprocess_2   Ran for 8 min   completed
e7b04956cbf664f5        3dae29f04e9643cf preprocess_2   Ran for 8 min   completed
4e6a7460fed13775        3dae29f04e9643cf preprocess_2   Ran for 8 min   completed
d42de8ae2f8dfd23        3dae29f04e9643cf preprocess_2   Ran for 8 min   completed
eebfbac3127107d0        3dae29f04e9643cf preprocess_2   Ran for 9 min   completed
fbf664ba49e5c9b5        3dae29f04e9643cf preprocess_2   Ran for 11 min  completed
[MW]
```

**Comment by gaow** [comment]
but my next step in the workflow has not started.

**Comment by BoPeng** [comment]
These are all the tasks for this step? Wondering what sos is doing.

**Comment by BoPeng** [comment]
With -v4 in this case there would be some scrolling text such as xx running which would show some problem if the number is inconsistent with what we see outside.

**Comment by gaow** [comment]
Yes these are all tasks for one step. SoS is apparently running 2 threads, one for 14min one 24min:


```
[MW] ps -A | grep sos
47132 pts/2    00:00:14 sos
47154 pts/2    00:00:24 sos
```

I suspect it is working on the database, but the time stamp suggests otherwise because modification timestamp did not change.

Maybe i'll wait a bit and try again with `-v4`.

**Comment by BoPeng** [comment]
Flight taking off. Later.

**Comment by gaow** [comment]
Still no rush, but is there a plan to tackle this ticket, and the related `concurrent` issues? I've got to rerun a pipeline with updated methods that relies on concurrence in the presence of shared output. I can revert to an earlier version of SoS if we need more thoughts to fix these ones.

**Comment by BoPeng** [comment]
The problem here is that I cannot reproduce the problem, so I am working on something more reproducible (#1028).

**Comment by gaow** [comment]
Of course, thank you! yes it should be easier if #1028 is fixed first then at least we have one less factor to worry about when we try to come up with MWE for this one. I've being trying yesterday (though not hard enough) but still cannot get something small to upload here that can possibly reproduce it. But I'll try it again.

**Comment by gaow** [comment]
With the current `master` my example in the first post is reasonably fast -- under a minute before it can start running. I'm closing this ticket for now. Will see if down the road there is a need to make it even faster for larger scale problems (if we run into it).
