### ISSUE TITLE
Concurrent task with shared output

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1030]
Related to #1028 to bypass it, I re-implemented my workflow as:

```
[1: shared = {'unit_dataset': 'step_output'}]
max_dist = 999
cwd="/tmp"
y_data= path('/tmp/1.txt.gz')
chroms = [f'chr{x+1}' for x in range(22)]
input: for_each = 'chroms', concurrent = True
output: f'{cwd}/{y_data:bnn}_{int(max_dist/1000)}Kb/{_chroms}/MANIFEST'
bash: workdir = cwd, expand = "${ }"
     stress --cpu 1
```

Basically instead of using dynamic output I record output files to a text file and save them; I share them with the next step to create input file by:

```
input: paths([get_output(f'cat {x}').strip().split('\n') for x in unit_dataset]), group_by = 1, concurrent = True
```

I thought it would work. Unfortunately, it still runs on single process. Of course if `shared` is removed, it goes back to multiprocessing.

Since this is code in production and due to https://github.com/vatlab/SoS/issues/1024#issuecomment-415159345 the hang I cannot use `task` either, i'm a bit stuck here. But I can move on to other tasks -- guess these tickets share a lot in common and needs some thoughts on your end to address jointly :)

**Comment by gaow** [comment]
Sorry posted the wrong ticket earlier: so now a step involving `shared` for `step_output` seems to work with concurrent in the current `master`.

**Comment by BoPeng** [comment]
Look at the [`shared` option of tasks](https://vatlab.github.io/sos-docs/doc/documentation/Remote_Execution.html#Option-shared-1312), we allow tasks to return variables. The variables exist as individual variables, and we somehow make them a dictionary from multiple substeps. 

So logically speaking, tasks belong to substeps, and the variables shared by tasks will appear as themselves in the namespace after `task` (although no statement is allowed there). For the same reason, variables from substeps (without task) should be shared in the same fashion to be consistent. 

That is to say, if we are to implement `shared` in a consistent way, we will have to follow the model here and return `a = {0: 1}` from the following step:

```
[10: shared='a']
a=1
```
except for `step_input` and `step_output` which are designed to be step level variables. 

If we really want to return `a=1` for the above example, we will have to maintain two sets of variables. A possible implementation is that:

1. We define a step namespace with variables such as `step_output` etc. It will also contain substep variables, which should be the variable for the last substep.
2. We define a special variables that consists of namespaces for each substep, something like `_vars`. At the end of step, this `_vars` will contain namespaces from substeps, such as `_vars={'0': {'a': 1}}`. 
3. It is up to the user how to share variables. In most cases users would simply share step level variables and

```
[10: shared='seed']
input: for_each={'i': range(10)}
import random
seed=random.randint(0, 10000)
```
will only return one of the `seed`. If he wants all the seeds, he can use

```
[10: shared={'seed': 'x["seed"] for x in _vars.values()'}]
input: for_each={'i': range(10)}
import random
seed=random.randint(0, 10000)
```
to get them from the `_vars` namespace. Of course `_vars` could provide some convenient function such as `_vars.get('seed')`.

**Comment by BoPeng** [comment]
The `_vars` method is easy to explain because logically speaking the substeps can be considered to be executed by a for loop in the step namespace, so variables in the next substep naturally overwrite values from the previous substep (and this is exactly what has been done before `concurrent=True` and `task` were introduced). To this end we can even disable sharing variables from substeps for now  and provide `_vars` in a future release.

**Comment by BoPeng** [comment]
To hide `_vars`, we can define a whole new option `shared_all` (good name needed), so  that

```
[10: shared='seed']
input: for_each={'i': range(10)}
import random
seed=random.randint(0, 10000)
```
returns one of the seeds, and

```
[10: shared_all='seed']
input: for_each={'i': range(10)}
import random
seed=random.randint(0, 10000)
```
returns a list of `seed` for all substeps.

**Comment by BoPeng** [comment]
Implemented as

```
[10: shared='step_seed']
input: for_each={'i': range(10)}
import random
seed=random.randint(0, 10000)

[20]
print(step_seed)
```

```
$ sos run test
INFO: Running default_10:
INFO: Running default_20:
[9621, 9994, 8000, 7336, 3599, 7175, 8034, 3211, 4177, 9078]
```
