### ISSUE TITLE
Check docker container status for possible updates

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1031]
One of my long running pipeline failed, due to an error running an obsolete Docker image on my computer. 

This might be something to think about when we revisit the container option: currently it only checks if the image exists on the machine but whether or not it needs an update.

**Comment by BoPeng** [comment]
But you can specify exact tag of the image, right?

**Comment by BoPeng** [comment]
Do you want to check if the local latest is actually the latest on the cloud? What command could be used?

**Comment by BoPeng** [comment]
`latest` tag is something can go wrong ... https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375

**Comment by gaow** [comment]
> Do you want to check if the local latest is actually the latest on the cloud? What command could be used?

Yes that's what I want, and that's simply a `docker pull`.

> latest tag is something can go wrong ...

Interesting ... actually many of my docker containers are not versioned so by default I pull the "latest" like `gaow/debian-texlive` to avoid installing that suite on a computer. So `docker pull` will work as expected.

**Comment by BoPeng** [comment]
In meeting and cannot test.  In reality how fast is it to run docker pull if the image already exists?

**Comment by gaow** [comment]
I guess it depends on the number of layers?

1. 

```
[GW] time docker pull mdabioinfo/sos-notebook
Using default tag: latest
latest: Pulling from mdabioinfo/sos-notebook
Digest: sha256:ceab353df1574aaa73a5acd94219ed9ed72e5a0e6f1e4868a7c4cc296c175853
Status: Image is up to date for mdabioinfo/sos-notebook:latest

real	0m0.545s
user	0m0.012s
sys	0m0.000s
```

2. 


```
[GW] time docker pull gaow/debian-texlive
Using default tag: latest
latest: Pulling from gaow/debian-texlive
Digest: sha256:973f7467d5ef7b523e59d438809f415d039fd2fb9d466296ecb5f282f305d345
Status: Image is up to date for gaow/debian-texlive:latest

real	0m0.592s
user	0m0.012s
sys	0m0.000s
```

**Comment by BoPeng** [comment]
So pulling each time is acceptable? There can be a problem with network access for example running docker jobs with already pulled image on computing nodes without network access.

**Comment by gaow** [comment]
I did not sugguest `docker pull` in my first ticket precisely for that reason. There can be local images that people never push to remote. I wanted to test that behavior but have not got to it yet

**Comment by BoPeng** [comment]
```
[bpeng1@rrcs-24-103-236-65:~]$ docker pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
124c757242f8: Pull complete
2ebc019eb4e2: Pull complete
dac0825f7ffb: Pull complete
82b0bb65d1bf: Pull complete
ef3b655c7f88: Pull complete
Digest: sha256:72f832c6184b55569be1cd9043e4a80055d55873417ea792d989441f207dd2c7
Status: Downloaded newer image for ubuntu:latest
[bpeng1@rrcs-24-103-236-65:~]$ docker pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
Digest: sha256:72f832c6184b55569be1cd9043e4a80055d55873417ea792d989441f207dd2c7
Status: Image is up to date for ubuntu:latest
[bpeng1@rrcs-24-103-236-65:~]$ docker pull ubuntu
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: Service Unavailable
```
So docker quit very quickly. That means a potential solution is to pull everytime but ignore failed pull if image already exists?

**Comment by BoPeng** [comment]
The change is simple enough. Please test it, and fix the patch if something goes wrong.

**Comment by gaow** [comment]
It seems to be working:

```
HINT: Pulling docker image inutano/sra-toolkit
```

Read the patch. Yes pulling it anyways and properly quit on failure should be good enough.

**Comment by gaow** [comment]
It works, but I'm re-opening it because it seems to pull at every substep, eg:

```
INFO: Running default_1: BWA mapping & samtools postprocessing
HINT: Pulling docker image gaow/debian-ngs
HINT: Pulling docker image gaow/debian-ngs
```

It should pull just once.

**Comment by BoPeng** [comment]
Let me know if this is good enough.

![image](https://user-images.githubusercontent.com/9889312/45003679-9d1c9f80-afaa-11e8-9503-8a771ab8faeb.png)

**Comment by gaow** [comment]
So it is still just a delayed message? It certainly hides something. But I am more worried doing an analysis with 50K substeps (many of my analysis are) and trying to pull it 50K times. Do you think that is an issue?

**Comment by BoPeng** [comment]
Yes. That will be an issue and is why `docker run` does not pull by default. What I can do is to have a cache for pulled image, and adds item with docker pull and remove item with docker build etc...

**Comment by BoPeng** [comment]
I used a cache. The only question is that if I run local `docker build` without `docker pull`, would `docker pull` overwrite it?  I am talking about local and remote latest...

**Comment by BoPeng** [comment]
The answer is [yes](https://github.com/moby/moby/issues/10291). So image someone tries to do

```
[10]
docker_build: tag='myimage'
   xxx
sh: container='myimage'
    xxx
```
he might be surprised to find that his newly built image is not used if there is happens to be a `myimage` on dockerhub.

**Comment by gaow** [comment]
I see, so the current solution is to still pull and show messages for all substeps but use cache. It really gets ugly for 5K substeps. 

Does it make sense to just pull once for `concurrent = True`?

**Comment by BoPeng** [comment]
No. SoS caches the names of the pulled images so there will be no `docker pull` after the first time.

**Comment by gaow** [comment]
Okay but it does not look like the case, if you run the example in #1038 . I still see HINT message for all substeps in my workflow.

**Comment by BoPeng** [comment]
The problem is that this `cache` is per-process so a new worker will have an empty cache to start with. So either a file based cache needs to be used or wait for the zmq controller for such kind of thing...

**Comment by gaow** [comment]
> or wait for the zmq controller for such kind of thing.

Okay if that will be dealt with using zmq controller I think it is fair enough to not worry about it now.

**Comment by BoPeng** [comment]
Yes, the idea is that the controller will handling all things that should have been done by one process, including database writing, docker pull, and slot management. The loose coupling between the processes, and the messaging system will allow the implementation of a monitor console later on (if someone can tackle it).
