### ISSUE TITLE
A CONFIG bug

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1032]
Here is MWE for my SoS script:

```
[1]
samples = list(CONFIG.keys())
input: for_each = 'samples'
bash: expand = True
	echo {CONFIG[_samples]['name']}
```

and the CONFIG file:

```
sample:
        name: 'N666'
```

and the command & error message:

```
$ sos run test.sos -c config.yml 
INFO: Running default_1: 
N666
ERROR: [default_1]: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
script_8686010746599247775 in <module>
      bash(fr"""echo {CONFIG[_samples]['name']}
----> """)

TypeError: string indices must be integers
```

You see the name has been properly printed but there is an error genrated at the end.

**Comment by BoPeng** [comment]
My `CONFIG` contains a lot of host definitions so using all keys from `CONFIG` is not safe.

I changed the code to

```
[1]
samples = list(CONFIG['samples'].keys())
input: for_each = 'samples'
bash: expand = True
	echo {CONFIG['samples'][_samples]['name']}
```

with `test.yml` 

```
samples:
    s1:
        name: 'N666'
    s2:
        name: 'N667'
```
and I do not see a problem with command

```
sos run test.sos -c test.yml
```

**Comment by gaow** [comment]
I see, the problem is keys in `CONFIG`. It has more stuff unrelated to local project. I keep forgetting this ... 

I think I should better use `yaml.load` for project specific configuration? It is not as convenient but since we do not have the concept of local configurations it might be safer that way. 

I'm okay to close this issue if you think there is little to improve on this.

**Comment by BoPeng** [comment]
Another option is to use subkeys like what my example uses.

**Comment by gaow** [comment]
> Another option is to use subkeys like what my example uses.

Sure, but after re-realizing CONFIG is global I become hesitated doing that (what if my subkey happens to be, say, `hosts` ...)

**Comment by BoPeng** [comment]
The design allows users to specify `hosts` in local configurations, which is at least useful for sos tests where configurations for docker based hosts are defined in separate configuration files for tests.
