### ISSUE TITLE
Option shared of steps with substeps

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1033]
Option shared returns step variables to the master process but it is entirely sure what happens to steps with substeps. 

Basically, option `shared` evaluates and returns variables after the completion of a step. However,

1. SoS only makes sure `step_output` exists and contains the collection of substep output (`_output`).
2. For other variables, 
  2.a: if `concurrent=True`, the substeps are executed in separate processes and currently does not return any variable.
  2.b: if `concurrent=False`, the substeps are executed sequentially so the variable is the "end result" after all substeps. That is to say, if each substeps returns a different value, only the last value is caught.

So in theory the `shared` variable will have to be substep-specific, that is to say, 

```
[1: shared='a']
input:  for_each={'b': range(2)}
a = b
```
should return `a=[0, 1]` for value `b=0` and `b=1` for different substeps, and
```
[1: shared='a']
a = 1
```
should in theory returns `a=[1]` (or `[{'a': 1}]`) to reflect the fact that there is one substep, but this is not how this option works now.

**Comment by gaow** [comment]
> but it is entirely sure what happens to steps with substeps.

sure or not sure?

> SoS only makes sure step_output exists and contains the collection of substep output (_output).

Well, most of the time (if not at all times) I only care for sharing output files. It would surely be good to make the behavior consistent with what users would expect. As you've labelled, it is indeed buggy otherwise. But if the fix comes at a high cost of performance we might want to rethink whether or not we want to make special cases within the `shared` mechanism ...

**Comment by BoPeng** [comment]
I was not sure. The ticket says there are two types of step variables, step level and substep level and I am not sure how to share substep variables since include all user defined variables.

**Comment by BoPeng** [comment]
The key here is to pass the result of a step back to the workflow as variables, sometimes as a side effect (e.g. return number of mapped reads after alignment). We did not pay attention to substeps because they were executed in the same namespace sequentially so the variables are naturally overwritten if there are more, but with `concurrent=True` we need to decide how to pass variable back from workers and how to aggregate multiple variables from substeps.

Right now I do not see a good balance of performance (not saving all local variables to signatures), consistency and usability for this feature.

**Comment by gaow** [comment]
Okay, then sounds like we have to make some special cases here: if the `shared` is step output (or anything definite, no need to dive into substeps) we allow for concurrent safely. Otherwise we simply disable concurrent? I think this is understandable behavior but maybe a warning message can be printed to screen when concurrent is disabled due to such ambiguities.

**Comment by BoPeng** [comment]
But the case for sequential execution and overwriting the shared variable is also problematic. For example,

```
[10: shared='_index']
input: for_each={'i': range(10)}
```
would pass `_index=9` to the workflow, which might not be what users' need.

How are you using `shared`? I am thinking that perhaps we should disable this feature until we have a better solution.

**Comment by gaow** [comment]
> How are you using shared?

I only use it to share step output. That should be fine right? It might be fair to allow only sharing what we are sure about?

I do use it for our Process Oriented SoS demo:

https://vatlab.github.io/sos-docs/doc/examples/Process_Oriented.html

**Comment by BoPeng** [comment]
`step_output` is well defined and should be ok. I have workflow steps that for example align the reads and return number of reads which is a bit more difficult to convert...

Let me think harder on this.

**Comment by BoPeng** [comment]
`shared` means the variables are shared to others so that others can see it. The meaning of this option is more like a "return value", or "export". `shared_all` does not show the meaning of sharing individual variables from substeps, perhaps `substep_shared` is more accurate?

**Comment by BoPeng** [comment]
It is intuitive to have the following work as users would expected

```
[1: shared='a']
a = 1
```
but it might be a good idea to use `_a` because this is the convention we have been using for loop variables.

**Comment by gaow** [comment]
Yes I also thought about using `_` but it was a bit weird you used `step_output` for step output `_output`. That case we'll have to make exceptions for `step_output` and perhaps `step_index` ... perhaps it is not too bad, but it is not very clear either.

**Comment by BoPeng** [comment]
In simupop when I faced the same naming issue I chose _sp for subpop specific variable. I suppose a_ss (for substep) is ok although users can define a variable named a_ss.

**Comment by BoPeng** [comment]
Or a for step level and _vars[“a”] or _vars.a for substep level (array).

**Comment by gaow** [comment]
Well, that case I'd rather go for `_a` for substep variable, but make it special case that `step_output` and `step_index` are for step level -- it is just too many conventions otherwise.

**Comment by BoPeng** [comment]
`step_a` is actually acceptable. It is a bit confusing but it says something like "all (sub)step"...

**Comment by BoPeng** [comment]
Document is updated with the use of `step_XX` variables: 

https://vatlab.github.io/sos-docs/doc/documentation/SoS_Step.html#Option_shared
