### ISSUE TITLE
database locking on samba mount causing mac OS to freeze

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1034]
I am experiencing something very bad with sos tasks. I am working on a mac machine with a samba mount of a linux file system. When a workflow runs and multiple tasks have been completed, and supposedly writing to the database, the whole system freeze and I have to hard reboot the machine. This might be caused by samba file system but I did not expect the consequence as bad as this.

**Comment by BoPeng** [comment]
It seems to be a [known issue](https://discussions.apple.com/thread/8197522).

**Comment by BoPeng** [comment]
Upgrade mac OSX to 10.13.6 fixes this issue.

**Comment by BoPeng** [comment]
The problem strikes again...

**Comment by gaow** [comment]
> And this time my mac did not die, just froze for a long time 

and never wakes up? This sounds like my hang on the cluster. Does `ps -A | grep sos` show anything when it froze?

**Comment by BoPeng** [comment]
I submitted the job at home and I could not even log in to the workstation and run the `ps` command, until like 30 minutes later. It was a surprise though because I would have hard rebooted the machine if I were in office.

**Comment by BoPeng** [comment]
It looks like the only safe way to handle sqlite etc without locking is to use a single process/thread to write it. To this end we will have to create a client/server kind of structure so that the main process starts a socket that listens to requests from workers and respond. Let me first see if there is an existing implementation for this sort of thing.

**Comment by gaow** [comment]
Does it help if everything is in memory during the execution, and dumped to the disk only at the end (or try to save it at keyboard disruption signal)?

**Comment by gaow** [comment]
Also since we use sqlite for not just tasks but for steps / workflow signatures as well, this will impact both task and non-task applications ,right?

**Comment by BoPeng** [comment]
> Does it help if everything is in memory during the execution, and dumped to the disk only at the end (or try to save it at keyboard disruption signal)?

No, essentially speaking all data needs to be sent to a single process to write to disk to avoid database lock completely. 

> Also since we use sqlite for not just tasks but for steps / workflow signatures as well, this will impact both task and non-task applications ,right?

Yes.

I had the concept of messaging based inter-process communication for a long time but ended up using the old-style pipe. We can use existing pipes to pass signatures but this will make our code a step more complex and less maintainable. 

The new idea is to use sockets (or zeromq) to replace pipes between subprocesses. It is more or less like Jupyter when the frontend passes messages to backend for computation. The key difference here is that the client (worker) can send whatever message then continue (no wait), and the server (master sos process) can cache and choose to ignore the messages. It is much more flexible than the tightly coupled pipe-based multiprocessing architecture, and my only concerns is how fast starting the client server communication would be as message passing would be very fast.

**Comment by gaow** [comment]
Excited that `zmq` is now merged! Did it resolves the situation that workers reports to disk directly and cause your Sambda freeze (and some lock errors on my end  from time to time)?

**Comment by BoPeng** [comment]
Merged because sos-notebook can only test against sos in master, The tests still fail but can hopefully be resolved soon.

Yes, it should not cause samba freeze, database lock, slot error because all these operations are done in a single process and/or in memory. I will let you know when the master is ready for testing.
