### ISSUE TITLE
Check for required resource

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1036]
In our RNA-seq differential expression example the `STAR` alignment uses >32GB memory. It should be familiar to `STAR` users but could be frustrating for people who has not anticipate it. Shall we add something to `depends:` statement to check for computational resources beforehand? In particular, memory and available disk space?

**Comment by BoPeng** [comment]
Something like the following?

`depends: resource(mem='32G')`

**Comment by gaow** [comment]
Looks good. Otherwise I'm wondering if we can consolidate it with one of the existing target (maybe not ... )

**Comment by BoPeng** [comment]
Is 'mem='32G'` clear enough, I somehow think the case when some guy wants less than 32G of ram... :smile:

**Comment by gaow** [comment]
I think `mem=32G` is clear enough -- is this also our `task` option convention? 

How about disk space? `resource(mem='32G', disk='200G')`?

Some guy? That somehow sounds familiar ...

**Comment by BoPeng** [comment]
Target `system_resource` is added. Documented [here](https://vatlab.github.io/sos-docs/doc/documentation/Targets_and_Actions.html#Target-system_resource-148).
