### ISSUE TITLE
Check for software required for actions

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1037]
In a system without R, running for example the regression workflows under `examples` folder of SoS doc, there are error messages like:

```
 ERROR: Failed to execute script: [Errno 2] No such file or directory: 'Rscript': 'Rscript' ERROR: Failed to execute script: [Errno 2] No such file or directory: 'Rscript': 'Rscript' ERROR: [47acccab-1d33-49fe-bf12-9506d4c931b6]: No step to generate target R_library("MASS") requested by ridge_1 [default]: 1 pending step: default_2 
```

This is not very informative. Although it is trivial to add `executable('Rscript')` check for a workflow step, I wonder if we should automatically ensure availability of software for actions involved in the script. That is, `Rscript`, `python`, `python3`, etc.  and provide informative error messages when the dependencies are not satisfied.

**Comment by gaow** [comment]
Similiarly for docker actions:

```
- RuntimeError Traceback (most recent call last) script_2541748460723416072 in <module>
run(fr"""fastq-dump -I --split-files {os.path.basename(data)}
----> """, docker_image = 'gaow/debian-ngs', workdir = cwd)
RuntimeError: Cannot connect to the Docker daemon. Is the docker daemon running on this host? [star (/home/tester/GIT/LargeFiles/RNAseqDE/]: --------------------------------------------------------------------------- RuntimeError Traceback (most recent call last) script_8334085995044279767 in <module>
--runThreadN {ncpu} {'--genomeSAsparseD 2' if sparse_star else ''}
----> """, workdir = '/tmp', docker_image = 'gaow/debian-ngs', volumes = [f'{resource_dir}:{resource_dir}'])
RuntimeError: Cannot connect to the Docker daemon. Is the docker daemon running on this host? [align]: 2 pending steps: align_1, align_2 “””
```

is what happens when docker is not installed. Maybe we want to check for `docker` command ahead of time?

**Comment by BoPeng** [comment]
For regular commands, there are two possible complications, that is to say an action can have multiple interpreter (e.g. `python27`, `python2`), or if the action can have no interpreter (e.g. `run` with `#!`). I agree that we can test the existence of interpreter for cases we can decide though.

For the second problem, the existence of `docker` does not mean the `docker` daemon is running. Again, it is good to test if `docker` exists in the first place though.

**Comment by BoPeng** [comment]
Ohmm, SoS already [checks the existence of interpreter before running action](https://github.com/vatlab/SoS/blob/master/src/sos/actions.py#L292), not sure what is going on with the `Rscript` case.

**Comment by BoPeng** [comment]
For the second case, SoS already [checks the existence of docker command](https://github.com/vatlab/SoS/blob/master/src/sos/docker/client.py#L236). Checking if the docker daemon is running is a much harder problem.

**Comment by BoPeng** [comment]
The problem was caused by the checking of `R_Library`, not by `R` action. I have tried to produce a better message.

**Comment by gaow** [comment]
Okay ... that looks reasonable. Let me close it for now and I'll report back when I create a fresh ubuntu VM to test various example workflows.
