### ISSUE TITLE
boolean parameter input

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1038]
In this notebook https://github.com/vatlab/sos-campaign/issues/64:

https://github.com/vatlab/sos-docs/blob/master/src/examples/WGS_Call.ipynb

I have, by default `zap=True`. However it does not seem to work, that is, under the output `bam` folder nothing got zapped. Looks like a bug to me.

If I set `zap=False` by default, then from command line I add `--zap`, it works as expected.

**Comment by BoPeng** [comment]
Just to confirm with `zap=False` by default and `--zap` works.

**Comment by gaow** [comment]
> Just to confirm with zap=False by default and --zap works.

Yes.

> --no-zap also works.

not sure we can say that, because `zap=True` does not work.

**Comment by BoPeng** [comment]
This is a bug but I have tested this case explicitly and I do not understand why the test case did not catch it.
