### ISSUE TITLE
Parameter name conflicts with sos environment

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1041]
For [this SoS example](https://github.com/vatlab/sos-docs/blob/38136e843de016cda2d5d80a031033d26d7d0ed3/src/examples/Process_Oriented_Modular.sos#L24) I got this bash script generated:

```
Rscript <function script at 0x2ae090cb7620> seed=4 N="c(40,200)" b="c(3,1.5,0,0,2,0,0,0)" rstd=3 oftrain="'data_4.train.csv'" oftest="'data_4.test.csv'"
```

this is because `script`, my workflow parameter, conflicts with an imported SoS function. I think we should check and prevent it from happening.

**Comment by BoPeng** [comment]
There are some mechanism to prevent the use of sos keywords in places in parameters, but assignments are not monitored for performance reasons. This actually lead to a more serious question: should we allow sos keyword to be overwritten? At least in python you can easily overwrite system functions (e.g. `id=5` where `id` is a builtin function) and sos should perhaps follow suit.

**Comment by gaow** [comment]
> should we allow sos keyword to be overwritten? 

I guess so! and even more interesting in R:

```
> t = 5
> t(matrix(1))
     [,1]
[1,]    1
```

(but i think it is fair enough to not do that ^)

**Comment by BoPeng** [comment]
Allowing users to override sos keyword is the right thing to do. Think about this scenario:

1. Write a working workflow
2. Install a newer version of sos or another python module that introduces a  new action or target
3. Your workflow no longer works

**Comment by BoPeng** [comment]
The thing with R is different because `t(matrix)` is essentially `matrix.t` so changing `t=5` did not touch the member function of `matrix`.

**Comment by gaow** [comment]
Sure. My point is that interface-wise R can make this distinction but we do not have to do the same. Overriding is good enough

**Comment by BoPeng** [comment]
Your example should now work as expected.

**Comment by gaow** [comment]
@BoPeng sorry too soon I guess ... 

```
gaow@trico:~/tmp/05-Sep-2018$ cat test.sos 
[1]
parameter: input = 5
output = 10
python: expand=True
  print({input})
gaow@trico:~/tmp/05-Sep-2018$ sos run test.sos 
ERROR: File contains parsing errors: /home/gaow/tmp/05-Sep-2018/test.sos
	[line  4]: 
Invalid parameter name input: input is a SoS keyword
```

However it works if `parameter` is removed.

**Comment by BoPeng** [comment]
This is caused by [this line](https://github.com/vatlab/SoS/blob/master/src/sos/parser.py#L502) of code and I am not quite sure if we should life the gate here. As far as I can tell now, sos process `input:` etc in parsing time so they will not enter sos running namespace so it should not matter to have parameters named `input`, `task` etc.

**Comment by BoPeng** [comment]
Does your example work now?

**Comment by gaow** [comment]
It was broken due to a typo but I fixed it. Should be good now.

**Comment by BoPeng** [comment]
Thanks. I was editing directly on github.com (no access to desktop) and could not see the diff before I commit.
