### ISSUE TITLE
Option name for singularity

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1042]
nextflow uses [the following configurations for singularity]((https://www.nextflow.io/docs/latest/singularity.html)):

```
process.container = 'file:///path/to/singularity.img'
singularity.enabled = true
```

where `process.container` can be `file` (local file), `docker://` (pull from docker hub), and `shub` (pull from sigularity hub).

We currently have

```
container = 'image' (equivalent to 'docker://image')
container = 'docker://image'
```
that assumes the use of docker.
```
container = 'file://file'
container = 'shub://url'
```
can assume the use of singularity, but what if we want to use singularity to execute docker container? Should we have

```
container='image', singularity=True
```
or
```
container='docker://image', singularity=True
```
or
```
container='image', engine='singularity'
```
so that we can support other types of engines (e.g. shifter)?

**Comment by gaow** [comment]
> container='image', engine='singularity'

this looks good to me.

**Comment by BoPeng** [comment]
Thanks, used `engine='singularity'`.
