### ISSUE TITLE
`sos-cm-toc` template TOC display problem

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1054]
This is not exactly a MWE but is easy enough to reproduce. First, 

```
git clone https://github.com/gaow/ipynb-html-encrypted.git
cd ipynb-html-encrypted
```

it's a little script I wrote to generate password protected HTML files to post online for collaborators. Now run:

```
./encrypt.sos --notebook README.md
```

Under the hood it uses `sos-cm-toc` . You should see a file `README.original.html`. Open it in your browser and in TOC click on "Usage". You'll see the 3 subsections under "Usage" briefly flashes then folds back. This is the problem I would like to report.

Hopefully it is easy enough to reproduce and fix!

**Comment by BoPeng** [comment]
Private repo?

**Comment by BoPeng** [comment]
You can send me just the resulting HTML file.

**Comment by gaow** [comment]
Sorry, fixed the `git clone` link above. 

Yes I should just sent the file ... See attached.

[demo.html.txt](https://github.com/vatlab/SoS/files/2385319/demo.html.txt)

(please remove `.txt` extension)

**Comment by BoPeng** [comment]
I see, click the second time and things are ok. This is from third-party library (toc code) and I will have a look when I get some time (not likely for a while).

**Comment by BoPeng** [comment]
@gaow Please let me know if the problem still exists with the new tocbot based TOC.

**Comment by gaow** [comment]
Okay this time it simply does not show anything under `Usage` section in TOC when I click on it -- the default level of headers in the TOC has changed?? Here is the result:

[demo.html.txt](https://github.com/vatlab/SoS/files/2789535/demo.html.txt)

(please remove .txt extension)

**Comment by BoPeng** [comment]
What I observe is that:

1. if the window is short enough, it can scroll without problem and the TOC will expand, clicking will work.
2. if the window is high so that is no scrolling, the TOC will not move or expand because everything is in one page. Clicking toc will not work.

Do you have the same observation?

**Comment by BoPeng** [comment]
Do you ming if I send the example to the tocbot ticket tracker?

**Comment by gaow** [comment]
> Do you have the same observation?

Indeed.

> Do you ming if I send the example to the tocbot ticket tracker?

Not at all. Please go ahead.
