### ISSUE TITLE
atomic write feature

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1055]
Atomic write ensures that output files don't end up in their final paths before the whole task has completed, so that it can separate non-finished files from finished one, in case the workflow scripts breaks for any reason.

Without atomic writes, if a user wants to continue from a previous run, they have no way of knowing whether the existing files that the workflow depends on are properly finished or not. Thus, this is a serious limitation in reliable, reproducible research and in my opinion needs to be implemented in the software for it to be worth publication. In my view, anything else is preparing for potential catastrophe, with silently missed errors because of truncated data files.

Acceptable mechanisms could be to add a temporary file extension to their file names, or write them into a temporary folder, and moving temporary files into their final destinations when the task is finished.

**Comment by BoPeng** [comment]
We could not use temporary file or directories because sos allows loosely defined steps with no or incomplete input and/or output directives. SoS cannot do anything if it does not know the input or output of steps. Actually, evaluating steps in sandboxes (temporary directories) is error prone because the steps might not run correctly in sandboxes because the sandboxes might not have the correct dependencies etc.

I think SoS has largely solved this problem largely through the use of signatures. Basically, SoS creates a signature only after successful completion of a step, and ignores a step only if the signature exists and verifies successfully. However, there are two potential scenarios for errors:

1. If a step fails, a signature will not be saved, and need to be rerun. However, the previous run might have left some erroneous intermediate files and rerunning the step with such intermediate files might lead to erroneous results.

2. SoS checks the existence of dependent targets. If the target exists, it will go ahead and use that target. In the scenario when the target is the output of a failed auxiliary step, the target might exist but in an incomplete status, leading to erroneous results.

**Comment by BoPeng** [comment]
I think we can improve the situation by removing `_output` of failed steps. That is to say, if a step fails for any reason, sos can check its intended output and remove (or move away) them. 

1. This will solves problem 2 because auxiliary steps always have `_output` so removing failed `_output` will make sure that `_output` is valid.
2. This will partially solves problem 1 because sos allows steps without `_output` and the problem causing files might be intermediate. However, it is fair to say that it is users' responsibility to create a more robust workflow by specifying `_output` of a step.
3. Removing incomplete `_output` might interfere with the execution of programs. For example, a program that downloads a bunch of files might be able to continue from partially downloaded files; and some program might have an internal checkpoint to start from last crashed status, and removing partial output can break the checkpoint feature.

**Comment by BoPeng** [comment]
Test script
```
[sub: provides='{file}.csv']
sh: expand=True
   touch {_output}
   eco "something wrong"

[step]
depends: 'failed.csv'
path('result.csv').touch()
```
Previously, when `sub` failed, `failed.csv` is already generated so the workflow would succeed when it is run the second time.  With the patch, `failed.csv` would be removed when `sub` failed to execute.

**Comment by BoPeng** [comment]
> That said, we dont have a mechanism to save status of intermediate file and evaluate that along with the rest of the environment?

Could you elaborate?

**Comment by gaow** [comment]
Sure, for example, something like:

```
[default]
output: '1.txt'
R: expand = True, track = [f'{_input:n}.important.intermediate.file', '2.txt']
 ...
```

Then files specified by `track` will have their signature saved and checked to determine re-run, just like `_output` ; or maybe more similar to parameters whose status change will trigger rerun.

**Comment by BoPeng** [comment]
We already have `input`, `output` and `tracked` for actions https://vatlab.github.io/sos-docs/doc/documentation/Targets_and_Actions.html#tracked.

**Comment by gaow** [comment]
That explains why it felt super familiar when I typed the `track` keyword! So isnt that solution to the erroneous intermediate file problem? I guess this is what you meant by the user's responsibility to specify them.

**Comment by BoPeng** [comment]
Yes.
