### ISSUE TITLE
idle processes during execution

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1056]
sos generates a number of idle processes when steps are waiting for the completion of tasks or subworkflows. Basically, these processes are push aside (not counted towards `-j`) so that new processes could be created to process the nested workflow etc. It would be helpful to make use of these idle processes for the processing of new steps.

**Comment by BoPeng** [comment]
This is a bigger problem now with `zmq` because the new branch counts the exact number of processes so the idle processes will be counted towards `-j`, and fewer processes will be actually running if there are a number of pending steps and workflows etc. Need to find a way to reuse idle processes.

**Comment by BoPeng** [comment]
It looks like the easiest solution is to run steps with tasks and/or `sos_run` action in the master sos process. Because steps that involves `tasks` and `sos_run` are usually "controller" steps without much computation for themselves, it seems to make sense to do this. This also avoids the trouble of sending tasks and nested workflows to the master workflow, which simplifies the execution logic.

**Comment by BoPeng** [comment]
The proposed solution will not work.

1. The steps will wait so it cannot be executed in the master thread of the master process.
2. Because steps are executed in `env.sos_dict`, all threads in the master process will share it. So at most one thread with the master thread are allowed. Then the entire workflow will stall if two waiting processes are needed (e.g. a nested workflow and a step with task).

Right now I have implemented the zmq version of the original pipe solution. That is to say, idle processes will be present but not counted towards `-j` so `-j 4` might have more than 4 sos processes. It is possible for us to suspend and wake up idle processes but I am not sure if that is the right thing to do.

**Comment by gaow** [comment]
I think initially we had issues with this solution, that nested workflows triggers so many more processes than `-j`. That's why we ended up using `slotmanager` I think. Isnt there a problem now?

**Comment by gaow** [comment]
Is `-j` switch also broken? I tried to run a workflow with `-j 8`, but I got the following:

![2018-09-23-20-34-18_scrot](https://user-images.githubusercontent.com/917985/45935372-7978c380-bf70-11e8-861d-aa7ff655da28.png)

and kind of freezes my computer now ...

**Comment by BoPeng** [comment]
Needs an example to duplicate this...

**Comment by gaow** [comment]
Computer is frozen ... cannot kill it for the interest another long running
job. Will test more after.

**Comment by BoPeng** [comment]
Still working on tests. Windows is giving me lots of headache. Billiard failed (now I see why I gave it up before) and there are problems with passing sockets around. I will work on -j after all tests pass.

**Comment by BoPeng** [comment]
@gaow The problem you have seen was likely caused by zoombie processes caused by incomplete disposal of zmq resources. The current trunk has addressed this particular problem so perhaps you can try again and let me know if the problem persists. Note that the idle processes problem still exists so you should see more processes than `-j` if your workflow contains sub workflows.

**Comment by gaow** [comment]
Unfortunately I do not think it works. Here is a MWE:

```
[1]
n = [x for x in range(20)]
input: for_each = 'n', concurrent=True
bash:
  stress --cpu 1
```

and

```
[GW] sos run test.sos -j2
INFO: Running default_1: 
stress: info: [19469] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
stress: info: [19472] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
stress: info: [19481] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
stress: info: [19487] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
stress: info: [19493] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
stress: info: [19499] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
stress: info: [19505] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
stress: info: [19511] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
stress: info: [19520] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
stress: info: [19526] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
stress: info: [19535] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
stress: info: [19541] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
stress: info: [19547] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
stress: info: [19554] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
stress: info: [19560] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
stress: info: [19566] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
stress: info: [19572] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
stress: info: [19578] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
stress: info: [19584] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
stress: info: [19590] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
^CKeyboardInterrupt
```

I killed it before it got crazier.

**Comment by BoPeng** [comment]
I still could not figure out a good way to solve the idle process problem but the concurrent worker problem should have been solved. Basically, substeps are now sent to a controller where workers are created (and destroyed) to handle substeps from all steps. You should usually see `j+1` processes because the one extra process is the step that is waiting for the completion of substeps.

Also, all tests have passed so it is time for you to test the master of `sos` and `sos-notebook`. The conversion to zmq is not completed because many other things could be done in the zmq way (e.g resume of tasks) but these can be done slowly and should be relatively easy with a working zmq framework.

**Comment by BoPeng** [comment]
zmq makes the handling of idle process a bit easier because things are less tightly integrated but I still cannot find a good way to put idle processes to sleep or aside. The problem is with our global `sos_dict` which cannot be shared by threads in the same process. A real solution would have to make `sos_dict` local (to threads) but that is not an easy thing to do... so this ticket will remain open for a while.

From my point of view, it is ok to use master in production as long as all tests pass. Your jobs might fail due to incomplete tests (e.g. your `sos_variable` + `depends` + `concurrent` + not using variable in step) but at least these are new bugs that can be tested and fixed.

**Comment by BoPeng** [comment]
#1218 

Feels good to close this loooooong-standing ticket.
