### ISSUE TITLE
Inconsistent summary information between reruns

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1062]
I find the new `-v1` is super useful in summarizing execution status and revealing possible bugs. I'm taking our classic "hang test" (cannot pin to the exact ticket without searching but I do have that folder on my computer to run manual SoS tests), data attached again:

[hang_test.sos.txt](https://github.com/vatlab/SoS/files/2407449/hang_test.sos.txt)

See the screenshot below:

![2018-09-21-21-45-26_scrot](https://user-images.githubusercontent.com/917985/45912504-38ee3e00-bde8-11e8-97f1-22a063b5913f.png)

and notice several things.

1. The first `-v1` did not show up any prompts
2. The 2nd `-v1` still seem to be running some tasks, not completely skipping them all! 
3. Although it starts to converge from the 3rd run, instead of saying 18 steps it is now 10, and there are still green dots, indicating they are still executed. 

I suspect it's a problem with nested workflow and these are false alarms?

Just by looking at the output I'm confused here by 18 vs 10 steps, and maybe in general, by "steps". I wonder what happens when for some steps only partial substeps are completed -- a fractional number? I still feel it a lot less confusing to use sub-steps instead, and just call them "jobs", that is, simply counting number of dots users will get information consistent with number they see for "jobs", and associate this with the same concept as in `-J` and `-j`.  The colored dots makes it straightforward to appreciate what SoS has helped (though still somewhat confusing now).

**Comment by BoPeng** [comment]
Mime seems to be ok?

![image](https://user-images.githubusercontent.com/9889312/45913418-9473f800-bdf7-11e8-8f56-d338c0fbe5c3.png)

**Comment by BoPeng** [comment]
Note that you see some green because steps with `sos_run` does not have signature so that sos can trace into subworkflows to validate signature.

**Comment by gaow** [comment]
Well, did you `rm -rf .sos` then run it? Maybe that will make a difference?

```
[GW] rm -rf .sos/
[GW] sos run hang_test.sos.txt -v1 
[...] 20 steps completed
[GW] sos run hang_test.sos.txt -v1 
[...] 18 steps completed, 10 steps ignored
...
```

> because steps with sos_run does not have signature so that sos can trace into subworkflows to validate signature.

Fair enough. Should we use another color for the ones without signature, though?

**Comment by gaow** [comment]
And from what I observed, a step will be considered "completed" not "ignored" even when most of its sub-steps have previously been completed. It still feels more informative counting the blocks as "jobs" and report that.

**Comment by BoPeng** [comment]
That might explains the issue. You have partially completed steps that are counted in both "completed" and "ignored" category. The formal output is more careful about this and would report something like `15.6` ignored...

**Comment by gaow** [comment]
> The formal output is more careful about this and would report something like 15.6 ignored.

Yes, and I still feel it is confusing when I try to think from the position of other users. SoS steps and substeps are not immediately familiar concepts to people. I think I got the word "jobs" from snakemake -- it prints to the terminal by units of jobs, not by "rules" (analogous to SoS steps). I found that easy to follow.

**Comment by BoPeng** [comment]
So you want to report number of substeps (or jobs), not steps?

**Comment by gaow** [comment]
Yes, I think it is the most informative -- a measure of the actual amount of computation and has some relationship with number of file output.

**Comment by BoPeng** [comment]
```
$ sos run hang -v1 -s force
[▣▣▣▣...] 220 substeps from 20 steps are completed
$ sos run hang -v1
[▣▣▣▣...] 220 substeps from 20 steps are processed (20 completed, 200 ignored)
```

**Comment by BoPeng** [comment]
Not sure if it is good to completely change the term from `substep` to `job` because `job` and `task` are generally exchangeable. Saying something like that sos task is part of job can be very confusing. My understanding is that `substep` is more **structural** because it points to where the `substep` is defined (inside `step`) and `job` is more like outcome of `substeps`. It does not sound too bad to say `step A has 10 substeps that generates 10 jobs`.

**Comment by gaow** [comment]
I'll use the other ticket to discuss formatting. But back to the possible signature issue, now there are more information to debug it (if there is a bug):

```
[GW] rm -rf .sos
[GW] sos run hang_test.sos.txt -v1
[▣▣▣...▣▣](no words said after the blocks)
[GW] sos run hang_test.sos.txt -v1
[▣▣▣..▣▣] 220 substeps from 20 steps are processed (70 completed, 150 ignored)
[GW] sos run hang_test.sos.txt -v1
[▣▣...▣] 220 substeps from 20 steps are processed (20 completed, 200 ignored)
[GW] sos run hang_test.sos.txt -v1
[▣▣..▣] 220 substeps from 20 steps are processed (20 completed, 200 ignored)
```

The first and 2nd lines are still problematic. The main issue is the 2nd line -- not sure why it happens.

**Comment by BoPeng** [comment]
You meant no words after the blocks? The problem is that the progress bar is printed by the controller thread. The master thread send the "done" message to the controller thread and calls

```
controller.wait(1)
```
and kills it if it does not finish in 1 second. Waiting indefinitely is possible but I do not want the executor to hang (you already observed some) just because the controller does not quit. Let me increase wait time and see if the missing text is due to timing or some internal problem.

**Comment by BoPeng** [comment]
I do not know what is going on here. I at least always have 21 # in the progress bar.

**Comment by gaow** [comment]
Are you saying this problem cannot be reproduced on your computer (the wrong line breaking and inconsistent numbers), even when you `rm -rf .sos`?  (i guess the numbers on the "completed job" summary can at least be reproduced?)

**Comment by BoPeng** [comment]
No I cannot. The first and last one removes `.sos`. The last one also removes `*rds`.

<img width="813" alt="screenshot 2018-09-22 14 45 35" src="https://user-images.githubusercontent.com/9889312/45921176-40f4bf00-be76-11e8-810e-506dd77fadb1.png">

**Comment by gaow** [comment]
Our result looks drastically different! Why do I have cyan colors -- is that part of the code? Should I update other packages apart from SoS.

**Comment by BoPeng** [comment]
cyan colors are for "partly" completed, so some jobs were not completed.

**Comment by BoPeng** [comment]
Not really. The controller processes messages from multiple processes and not necessarily in the order it was sent. Basically, using a fair share mechanism, zmq reads one message from each source so if one process sends many, some messages might be handled after some latter messages sent  from another less busy processes. 

In your case, the controller receives a "done" message and finalizes the progress bar, and then it receives a "progress" message from another process. I will need to figure out some way to put things in order.

**Comment by BoPeng** [comment]
Try again on the machine that triggers the problem.

**Comment by gaow** [comment]
Great! No newline for `#` and no cyan color anymore on that example. So indeed both problems are `zmq` sync issues that has now being properly resolved.
