### ISSUE TITLE
Bash unable to %put new variables

### ISSUE THREAD

**Issue by razimantv** [vatlab/SoS#1067]
I cannot export newly created variables from bash in SoS 

Example (trying inside jupyterlab):

```
SoS: 
    var1=10

Bash:
    %get var1
    var2=$((var1+1))

Bash:
    %put var2
```

I receive the error
```
Variable not exist: var2
```

But if var2 is already defined there is no problem

```
SoS: 
    var1 = 10
    var2 = 1

Bash:
    %get var1
    %get var2
    var2=$((var1+1))

Bash:
    %put var2

SoS:
    var2
```

I get the output `'11'` as expected

Versions:
jupyter-lab 0.34.12
bash-kernel 0.7.1
sos-bash 0.9.12.2
sos 0.16.11 for python 3.6.6

**Comment by BoPeng** [comment]
Currently `sos-bash` uses `env` command to get values of all `%put` variables but obviously `var2=$((var1+1))` without `export` does not put `var2` in `env`. The problem can be temporarily fixed by using

```
export var2=$((var1+1))
```
instead of 
```
var2=$((var1+1))
```
in the bash kernel. I will work on a real fix soon.

**Comment by BoPeng** [comment]
Please upgrade to `sos-bash` 0.12.3 (`pip install sos-bash -U`) and let me know if the problem has been fixed. Thanks.

**Comment by razimantv** [comment]
Thank you, it seems to have been fixed.
