### ISSUE TITLE
Implicit share of output

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1068]
There are currently two ways to use step of one step in another.

In a forward-style, `step_output` is explicitly `shared`:
```
[step_A: shared={'a_output': 'step_output'}]

[step_B]
input: a_output
```
In a makefile style, `step_output` is provided to others:
```
[step_A: provides='a_output']

[step_B]
input: 'a_output'
```

Since `shared={'a_output': 'step_output'}` can be used quite often, it makes sense to provide an easier way to access it, something like:

```
[step_A]

[step_B]
input: step_A_output
```

**Comment by gaow** [comment]
maybe a `from` option to `input`, eg

```
[step_B]
input: from = "step_A"
```
?

**Comment by BoPeng** [comment]
yes, that looks good. Let me think more about it (in terms of implementation).

**Comment by BoPeng** [comment]
The more ugly version `step_A_output` has the advantage of allowing the variables to be used outside of `input` statement as

```
input: step_B_output, group_by=1
sh: expand=True
    {step_A_output} {_output}
```
but this is difficult to do because of the availability of these variables would impose order of execution, which adds another layer of complexity to the DAG.

```
input: from=['step_A', 'step_B']
```
is easier to implement because I can automatically add `depends: sos_step('step_A'), sos_step('step_B')` for the building of DAG. 

Named input is difficult because it is difficult to determine the behavior of `group_by`, `for_each` etc for subgroups. However, it is not unreasonable to say that `group_by` etc does not work for `from` with multiple input sources.

**Comment by gaow** [comment]
> However, it is not unreasonable to say that group_by etc does not work for from with multiple input sources.

Well, maybe named output will not work for from multiple input sources, but others should work because what we are doing here is essentially a shortcut to `shared`, so behavior of the following, 

```
[step_a: shared = {'a':'a','b':'b'}]
...
[step_b]
input: a,b, group_by = 1
```

should be the same as 

```
[step_b]
input: from=['a','b'], group_by =1
```

I'm cool not dealing with named input.

**Comment by gaow** [comment]
But with `shared` we can also do

```
[step_b]
input: '1.txt', a, b
```

How do we do it with `from`?

```
input: from = ['1.txt', 'a', 'b']
```

```
input: '1.txt', from = ['a', 'b']
```
both read awkward although the latter is certainly better if I have to choose one.

**Comment by BoPeng** [comment]
I think 

```
input: '1.txt', from = ['a', 'b']
```
makes sense.

Named input is not that difficult to implement if we introduce the concept of `source` to `sos_targets`.

I mean, we are the creator of `sos_targets` so we can attach a field `source` for each target. Then

```
[a]
output: 'a.txt'
[b]
output: 'b.txt'
[c]
input: 'c.txt', from = ['a', 'b']
```
would translate to an `step_input` with targets with
```
targets: ['a.txt', 'b.txt', 'c.txt']
source: ['a', 'b', 'c']
```
while we can keep our existing way to access targets (e.g. `_input`, `step_input`, `_input[0]`), we can add the following interface

1. `[src]`: a `sos_targets` with a subset of `targets` and `source` with matching `src` (`_input['a'] = 'a.txt'`)
2. `.source`: return the `source` of targets. `_input.source = ['a', 'b', 'c']`

So users can do

```
input: 'c.txt', from = ['a', 'b']

_input['a']
_input['b']
_input[step_name]
```
and
```
input: 'c.txt', from = ['a', 'b'], group_by=1

if _input.source == ['a']:
   do_A()
elif _input.source == 'b']:
  do_B()
```

**Comment by gaow** [comment]
Just a thought,

```
input: 'c.txt', from = ['a', 'b'], group_by='steps'
```

so that 3 groups will be generated `'c.txt'`, `a`, and `b`.

Currently we have group_by options single, pairs, pairwise, combinations. Perhaps we can remove `single` (use `group_by=1` but still keep the code under the hood for `single` because it is easier than `group_by=N`), and add something to generate groups by steps? If no `from` option is provided it by default does not do any grouping.

**Comment by BoPeng** [comment]
If you agree with the source extension of sos targets, then the option would be named group_by=‘source’.

**Comment by gaow** [comment]
> If you agree with the source extension of sos targets, then the option would be named group_by=‘source’.

I am still hesitated to that ... my worry is that it encourages bad practice. For your example above, it should in fact be separated to two steps: 

```
[ca]
input: 'c.txt', from = ['a'], group_by=1
do_A()
[cb]
input: 'c.txt', from = ['b'], group_by=1
do_B()
```

If `input` is too powerful users can potentially make a lot less steps than what the workflow logic in fact naturally fits best.

I'm trying to think if a more compelling user case to justify `source` attribute. Could you think of another example?

**Comment by gaow** [comment]
Ahh I think I see an obvious example now:

```
input: 'c.txt', from = ['a', 'b']
case = _input['a']
control = _input['b']
```

Does this justify it? I guess let's just make sure our examples in documentation do not encourage bad practices.

**Comment by BoPeng** [comment]
`from` cannot be used because it is a python keyword. `from_steps` or `source`?

**Comment by BoPeng** [comment]
Pending more testing but the option works roughly like this:

```
[A]
output: 'a.txt'
_output.touch()

[B]
output: 'b.txt'
_output.touch()


[10]
input: 'c.txt', from_steps=['A', 'B']

print(_input)
print(_input.source)
```
Output:
```
c.txt a.txt b.txt
['default_10', 'A', 'B']
```

**Comment by gaow** [comment]
Great! @BoPeng could you comment / propose how this step should best change to take advantage of this feature? 

https://github.com/vatlab/sos-docs/blob/141831a152f3b4d5e30bc9c645baf4a9d3ab249b/src/examples/Process_Oriented.sos#L73

Currently it is not very intuitive due to the use of `replicate` variable. i suspect it is cleaner to use something like `_input['source_step'][0]` etc but not sure how it can be done. `group_by` is tricky. 

To recap, the idea is

```
[step_1]
output: 'tain.dat', 'test.dat'

[step_2]
input: 'train.dat', 'test.data'
output: 'estimate.result', 'prediction.result'

[step_3]

evaluation_1('estimate.result', 'test.dat')
evaluation_2('prediction.result', 'test.dat')
```

That is, `step_3` takes input groups of two, and pair that with partial output from `step_1`. Notice that I'm only outlining a special case of one "replicate". In reality all these are just substeps.

**Comment by BoPeng** [comment]
Not saying I like it but it is possible to do:

```
[A]
output: 'a.txt'
_output.touch()

[B]
output: 'b.txt'
_output.touch()


[10]
input: 'c.txt', sos_step('A').output, sos_step('B').output

print(_input)
print(_input.source)
```

Then your case could be written as

```
[step_1]
output: 'tain.dat', 'test.dat'

[step_2]
input: 'train.dat', 'test.data'
output: 'estimate.result', 'prediction.result'

[step_3]
test_dat = sos_step('step_1').output[1]
input: 
evaluation_1('estimate.result', test_dat)
evaluation_2('prediction.result', test_dat)
```

**Comment by BoPeng** [comment]
Or, as in the case of simuPOP, allow a python function like:

```
[step_1]
output: 'tain.dat', 'test.dat'

[step_2]
input: 'train.dat', 'test.data'
output: 'estimate.result', 'prediction.result'

[step_3]
def group(input):
    return zip(input['step_1'], input['step_2'][1])

input:  from_steps=['step_1', 'step_2'], group_by=group
evaluation_1(_input[0], _input[1])
```
Of course a `lambda` function could be used for simple cases.

**Comment by gaow** [comment]
Okay, the latter solution is a lot cleaner than the proposed `sos_step` but still not so sure about using functions (because people who does not use Python will find it daunting). First, lets see if it solves the problem when substeps are introduced:

```
[step_1]
replicate = [x+1 for x in range(5)]
input: for_each = 'replicate'
output: f'data_{_replicate}.train', f'data_{_replicate}.test'

[step_2]
input: group_by = 2
output: f'{_input[0]:n}.estimate',  f'{_input[0]:n}.prediction'
```

At this point `input['step_1']` is a vector of length 10, but we only need 2,4,6,8,10th element for  `step_3`. `input['step_2']` also is a vector of length 10 but we need them all. We want to pair them as 

```
input['step_1'][1], input['step_2'][0], input['step_2'][1]
input['step_1'][3], input['step_2'][2], input['step_2'][3]
...
```

each as a concurrent group. Does `group_by` take some `yield` function to generate this? 

If doable, we then should ask the 2nd question: is there a simpler solution, particularly for people who are not familiar with Python?

**Comment by BoPeng** [comment]
We can certainly introduce more parameters to `group_by` but there will be simply too many such cases and a function looks like a more general solution. For this particular example, you can write

```
group_by = zip(input['step_1'][1::2], input['step_2][::2], input['step_2'][1::2])
```
and I cannot imagine any other builtin parameter can specify it in an easier way.

**Comment by BoPeng** [comment]
The closet non-function solution that I can think of would be something like

```
group_by={'step_1': 2, 'step_2': 2}
```
which would generate 
```
input['step_1'][0], input['step_1'][1], input['step_2'][0], input['step_2'][1]
```
and you can just ignore `_input[0]`.

**Comment by gaow** [comment]
Oh wow I was about to propose something like that. This is similar to the more advanced use of `for_each`:

https://vatlab.github.io/sos-docs/doc/documentation/SoS_Step.html#Option_for_each

> If you would like define your own loop variable, or if the default loop variable does not work (e.g. loop through obj.sequence where _obj.sequence is not a valid variable name), you can use a dictionary syntax in the format of {'varname': sequence}.

Ignoring `_input[0]` is not a big deal.

**Comment by BoPeng** [comment]
`for_each` does not care about order, `group_by` should, although we can force the order of this particular dictionary.

**Comment by BoPeng** [comment]
Or we can introduce something more generally, 

1. `group_by=value`: regular `group_by`
2. `group_by=('name', value)`: `group_by` applied only to source `name`

Then your example can be written as

```
input: from_steps['step_1`, 'step_2'], group_by=('step_2`, 2)
val = step_input['step_1']
execute(_input, val[_index])
```

Or we can introduce also parallel `group_by`,

3. `group_by=[value1, value2]` which would zip two group_by results.

```
input: from_steps['step_1`, 'step_2'], group_by=[(`step_1`, 2), ('step_2`, 2)]
execute(_input[1], _input[2], _input[3])
```

**Comment by gaow** [comment]
Option 3 is essentially the dictionary syntax with order, which reads good. Option 2 seems confusing. I guess it is not unfair to assume for unspecified groups to not group any of them, eg, 

```
group_by = ('step_1', 2)
```

is equivalent to 

```
group_by [(`step_1`, 2), ('step_2`, 'all')]
```

(or `None`). If users want some different ordering they will need to explicitly specify them.

**Comment by BoPeng** [comment]
These are just too complicated, how about sequential group by?

```
group_by=(v1, v2)
```
the option will group by `v1`, and then `v2` to each group of `v1` and combine the subgroups together.

That is to say,

```
group_by=('source', 2)
```
will generate

```
s1: 0 1 2 3 4 ...
s2: 0 0 2 3 4...
```
then
```
s1: [0,1][2,3],[4,5]...
s2: [0,1][2,3],[4,5]...
```
with output
```
[s1[0], s1[1], s2[0], s2[1]]
[s1[2], s1[3], s2[2], s2[3]]
```
This is conceptually more difficult to get around but at least shorter.

**Comment by BoPeng** [comment]
Since we already have basic grouping and general grouping, I do not think it is a good idea to introduce a spectra of advanced `group_by` features. I would rather introduce something like `pair2`, which is similar to `pair` (divide input in half and match) but take 2 each time. This can be easily extended to `pairN` programatically.

If dividing by half is not enough (e.g. if you have three input sources), perhaps we can introduce `pairsource` and `pairsourceN`, which would pair input from all sources together and take 1 or more from each input.

**Comment by gaow** [comment]
I still think it is more confusing to introduce `paired`. I think we should not worry about sequential `group_by` because it sounds like a poor workflow design when people has to use that feature -- can you think of a compelling example in practice one has to use sequential `group_by`? On the contrary arbitrary pair-wise grouping (not just 2) is quite  common -- imaging in a workflow step in addition to the one main output one focuses on, there are also additional files for diagnostics eg plots or log files, of arbitrary number, that might be relevant to some of the downstream steps. Then the `group_by=[(`step_1`, 2), ('step_2`, 5)]` sounds very natural to me and I can imaging actually starting to track some of my important diagnostics files that way by making them actual output of steps.

**Comment by BoPeng** [comment]
All the options are too complicated to use. `group_by=[('step_1', 2), ('step_2', 5)]` is ok but it is long and make the step a bit more difficult to maintain because of explicit references to step names.

In the above patch I introduced:

1. `pairsN` in addition to `pairs`, which will divide input by half and take `N` pieces from each half to form `_input`.
2. `pairsource` and `pairsourceN`, which will pair input from all sources, take `N` (`1` by default) and form `_input`. Currently it requires all sources have the same number of input files.

For your particular case both `pairs2` and `pairsource2` would work.

**Comment by BoPeng** [comment]
Documented [here](https://vatlab.github.io/sos-docs/doc/documentation/SoS_Step.html#Option_group_by).

**Comment by gaow** [comment]
The [example here](https://github.com/vatlab/sos-docs/blob/1f8797d6f42ec92c4531c79c616613a5bf4c1aae/src/examples/Process_Oriented.sos#L73) is a bit more complicated. I could have used `pairesource` but the problem is that the step is shared by two workflows. I possibly can use something like 

```
from_source = [step_name.split('_')[0] + '_1', step_name.split('_')[0] + '_2']
```

but is there anything more elegant I can do here?

**Comment by gaow** [comment]
Okay even that did not work ...

```
from_steps = [step_name.split('_')[0] + '_1', step_name.split('_')[0] + '_2']: name 'step_name' is not defined
```

**Comment by BoPeng** [comment]
The `step_name` issue is fixed. I do not see any better method here,

```
from_steps=[f'{step_name[:-2]}_1', f'{step_name[:-2]}_2'] 
```
will be shorter, but that is about the best we can do unless we introduce further conventions or variables.

**Comment by gaow** [comment]
Well, it works, but `pairsource` did not work for that example:

```
ERROR ... : Input sources do not have equal size: {'ridge_2': 20, 'ridge_1': 10}
```

That is why I initially thought `pair` is a bit to restricted. To recap, here I need to pair:

```
# index, input 1, input 2
0, ridge_1[0], ridge_2[0]
1, ridge_1[1], ridge_2[2]
2, ridge_1[2], ridge_2[4]
```

Can i do it easily under the current framework?

**Comment by BoPeng** [comment]
Damn it. That was almost the only case that was left out and you have it.

**Comment by gaow** [comment]
And that warrants formally introducing lambda functions?

**Comment by BoPeng** [comment]
We are essentially doing a zip with unequal length. Instead of giving an error, we could devise a "most reasonable" way to handle it. Something like:

```
1. group longest source by specified `N`, say, with end result `m` groups
2. for source of size `Nm`, divide to `m` groups and zip
3. for source of size `m`, do not divide by. zip directly.
4. for source of size `1`, zip directly (e.g. repeat)
```

**Comment by BoPeng** [comment]
`pairsource2` should work for you now.

**Comment by BoPeng** [comment]
The rules have been simplified to

1. Determine number of groups `m` from longest source / `N`
2. All source either group (not necessarily by size `N`) or repeat to create `m` groups
3. zip subgroups from sources

For example,

````
A = a
B = b1 b2 b3 b4
C = c1 c2 c3 c4 c5 c6 c7 c8
``` 
`pairsouce4` would yield `8/4=2` groups
```
A: [a] [ a]
B: [b1 b2] [b3 b4]
C: [c1 c2 c3 c4] [c5 c6 c7 c8]
```
so
```
[a b1 b2 c1 c2 c3 c4]
[a b3 b4 c5 c6 c7 c8]
```
