### ISSUE TITLE
automatic expand wildcard characters of paths('*.txt')

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1071]
With a recent patch, `sos_targets` automatically expands `*.txt` so that `sos_targets('*.txt')` would be a list of files matching `*.txt`. I am wondering if we should do the same to `paths('*.txt')`. The counter arguments are that `paths` is a collection of `path` and `*.txt` is a valid `path` (albeit not expanded), and we have been using `paths()` to generate space limited output of names using special formatting of `paths`.

**Comment by gaow** [comment]
What's the user case of `sos_targets`? Statements such as `input: "*.txt"` works anyways. I never have used `sos_targets()` explicitly. So without the proposed implementation, we will support wildcard in `input`, `output` and `depends`, right? The only usage of `paths('*.txt')` is in `parameter`? Then for the following scenarios:

1. `input: "*.txt"`
2. `input: paths("*.txt")`
3. `parameter: a = "*.txt"`
4. `parameter: a = paths("*.txt")`

Should we expect the same behavior for all of them?

**Comment by BoPeng** [comment]
`sos_targets` is the data type for `step_input`, `_input`, `step_output`, `_output` etc. Before the patch, 

```
input: '*.txt'
```
has to be processed before passing to `sos_targets`. Right now `sos_targets` can handle `*.txt` directly.

However, 
```
input: paths('*.txt')
```
is currently not working and I believe it did not before because `paths('*.txt')` is treated as a valid `path` and not expanded. I can either keep `paths('*.txt')` as it is and expand `*.txt` when it is converted to `sos_target` (used in `input`), or always expand `paths('*.txt')`. So for your examples,

1. Works before and now but `*.txt` is expanded by `sos_targets`.
2. Does not work in both cases, therefore the ticket.
3. `a` is a string. Will be expanded in cases such as `input: a`
4. Right now `a` is a `paths` object with a single `path` (`*.txt`). The consequence will depend on how `a` is used. If we allow `paths` to expand, it will be expanded to multiple (or no) `path`.

**Comment by gaow** [comment]
Exactly -- consistency on user's end is what I am concerning. Without the proposed change, behavior of 1 and 2 are inconsistent, but 3 & 4 are mostly consistent. With the change 1 & 2 will be consistent but 3 & 4 will not. But `parameter` assumes "default" types unless we explicitly specify otherwise. So making things more consistent is an argument in favor of the change.

But how about the following:

```
parameter: a = "*.txt"
input: a
```

and how about:

```
parameter: a = [1, '*', 2]
print(paths(a))
```

I'm not particularly worry about your counter arguments because both seem some corner cases that we may rarely hit, if at all, and are both easy to implement otherwise without `paths`.

**Comment by BoPeng** [comment]
The goal is to make things a bit easier for users with less surprise. Intuitively, `paths('*.txt')` should expand `*.txt`... Either way is fine but I am just trying to iron out the inconsistencies and document the features.

For your examples,

```
parameter: a = "*.txt"
input: a
```
is ok because `input: a` is equivalent to `input: 'a.txt'` which will be expanded.
```
parameter: a = [1, '*', 2]
print(paths(a))
```
will be different because `*` will be expanded as all files under the current working directory. These are cases that I worried about but I suppose `*` is all files if users want to use it in `paths`.

**Comment by gaow** [comment]
>  I suppose * is all files if users want to use it in paths.

Indeed. 

I think expanding `paths('*.ext')` is expected than otherwise.
