### ISSUE TITLE
Faster step-level signature check

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1072]
Currently SoS checks step signature via checking signature for each substep. In order to bypass computation of a step, all substeps have to be checked. It becomes slightly inconvenient (though still acceptable) when a step involves, say, ~10K substeps. 

I have a workflow that works perfectly until the last step. But every step before the last has ~10K substeps. I was too lazy to use a small example to debug my last step, so I kept modifying it, rerunning, waiting for SoS to bypass other steps checking one substep at a time, then finally goes into my last step throwing a new error that I did not fix completely. Then the whole process happens again.

I'm wondering if there are better ways to check steps when SoS is 100% sure that nothing in the step was changed, thus safely bypassing substep checks?

**Comment by BoPeng** [comment]
Something like a step signature with Step input and output?

**Comment by gaow** [comment]
and parameters, action scripts, etc, everything. I think it is good enough if a step is skipped because **absolutely** nothing in it was changed. Otherwise we proceed into the existing substep signature checking procedure for a finer examination.

**Comment by BoPeng** [comment]
Yes we need to make sure that paramaters are the same in cases of
```
[10]
parameter: a = int
...
```

**Comment by BoPeng** [comment]
Step level signature check would only help if the step level input and output files is less the sum of substep input and output files. In the "normal" case of separated `_output`, I doubt step level signature would help. Overlapping `_output` only happens for dynamic output, which is a special case that we have largely decided to leave alone.

**Comment by BoPeng** [comment]
Also, now that signature checks are parallelized, having a single step level signature with all output files can be slower than checking substep signatures separately. Also, if this is no clear relationship between step and substep signatures, signature mismatch at the step level means that sos would have to validate substep signature again to find the mismatch substeps.
