### ISSUE TITLE
Step specific "build" mode?

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1073]
Similar context as #1072 -- am really doing some sloppy work today by working directly on the final step of a production pipeline. I've made some cosmetic changes to the code of that final step which has previously caused failure in some corner case substeps , but I would like to avoid computing for all its substeps. So naturally I used `-s build`. It then ended up building signatures for all substeps from previous steps, for about 2hrs now. 

I was initially thinking of some "sloppy build", meaning that we just skip computation if output file exists, without rebuilding signature (is that what `ignore` model do??). but I think that's not a safe thing to do. Ideally it would be a lot better if I can specify which step to "build". But the interface might be challenging?

**Comment by BoPeng** [comment]
I used commit for every database transaction but it should not be needed with proper handling of terminations of zmq. With the newest master, the data is not written until the program quits so the database performance can be a lot faster and no data should be lost unless the process is killed by `kill -9`.

**Comment by gaow** [comment]
@BoPeng are you referring to this patch? 46e6f94d287d01e708a40f6a57b2327f8e2e5eda Should I try removing my `~/.sos` and build again just to see what happens?

**Comment by BoPeng** [comment]
You can time your workflow with and without the patch. My understanding is that for large amount of inserts the beginner in performance of less commit should be noticeable.

**Comment by gaow** [comment]
Okay I just tried. I didnt time it but I think it is faster from what I read on the screen, though not a lot faster (meaning visible on the screen flashing status), over without the commit. It's now like 10 substeps reconstructed per second from what I can roughly tell with `-v2`. (perhaps that logging process itself takes time). So reconstructing 10K files will take 1000 secs, for 3 steps, though it is 3000 secs < 1hr, which is better than the non-zmq version.

**Comment by BoPeng** [comment]
Yes, could you confirm if the building of signatures are done in parallel? (Will `-j` makes a difference?)

**Comment by gaow** [comment]
Is it designed to build signature in parallel? I've used -j 8 by default but from the screen output I don't think it is done in parallel. Every line updates one substep at a time.

**Comment by gaow** [comment]
Oh yes indeed, these jobs submitted to cluster are all `task`s. Should be good to lift the limitation, but a potential issue is that by default `-j` is half of the CPU which is not ideal for cluster headnodes. But I guess users can always specify `-j` explicitly if there is a concern.

**Comment by BoPeng** [comment]
The latest patch sends tasks to substep workers, but I am not sure if there can be delays with a large number of tasks. More specifically, sos

1. Sends all substeps to a worker queue, which dispatch substeps to workers.
2. Starts waiting for results. If tasks are returned, send task to task queues.

That is to say, step 2 will not start until all substeps are sent to the queue (not necessarily processed). From my test sos can send 20k substeps to the worker queue in seconds but there is a possibility that the queue can be backed up and delay step 2 (the submission of tasks). Let me know how sos behaves on your end.

**Comment by gaow** [comment]
@BoPeng I did not time it but there is now a visible performance improvement building signatures for my workflow with multiple steps having >10K substeps with `-s build` from screen output.

**Comment by BoPeng** [comment]
Glad to hear that. Signatures are now built in substep workers in parallel and should be faster.

**Comment by gaow** [comment]
Yes and what seems to be limiting it is the use of `-v2` now. I'm happy now running `-v1` with `-s build` in parallel. I think we can close the ticket until we have further problems.
