### ISSUE TITLE
Py_Module does not have an option for "version"

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1074]
Related to #1069 , `R_library` currently [accepts a version specification](https://vatlab.github.io/sos-docs/doc/documentation/Targets_and_Actions.html#Target-R_library-1103), but `Py_Module` seems not ...

**Comment by gaow** [comment]
Well, I'm using a somewhat different convention in `R_library`:

https://github.com/vatlab/SoS/blob/master/src/sos/targets_r.py#L42

It is not what PIP does. So we might want to change the code here too, to unify them. I've no problem to adopt to PIP conventions.

**Comment by BoPeng** [comment]
There is an entire pep440 for this kind of thing. Hopefully distutils ( setup.py), pkg_resource,pep440 even conda somehow agree with each other.

**Comment by BoPeng** [comment]
There is another problem with `Py_Module: mismatch of module and package names. One of our examples have

```
Py_Module('scikit-learn')
```
which was `True` because sos could not import `scikit-learn` but could install `scikit-learn`. It is `False` now because it could not import scikit-learn and `autoinstall` is set to False

**Comment by BoPeng** [comment]
Please try to use

```
Py_Module('sklean', autoinstall='sciket-learn')
```
or
```
Py_Module('sklean')
```

**Comment by gaow** [comment]
Ahh ... but great solution. In fact previously I did use `sklearn` which will trigger install without a problem. But `sklearn` will not trigger its dependency installation properly. It will then complain about `numpy` and `scipy` not found. `scikit-learn` can trigger dependency installations. 

The solution seems to do the trick except when version number is factored in (very soon):

```
[GW] pip install sklearn
Collecting sklearn
Requirement already satisfied: scikit-learn in /opt/miniconda3/lib/python3.6/site-packages (from sklearn) (0.19.2)
Installing collected packages: sklearn
Successfully installed sklearn-0.0
```

the last line above is worrisome. ..

**Comment by gaow** [comment]
The examples still does not work:

```
depends: Py_Module("sklearn", version = '0.18.1')
```

gives,
```
ERROR: Version 0.0 of installed sklearn does not match specified version 0.18.1
```

Because `sklearn` is always Version 0.0. I also tried  with `autoinstall = 'scikit-learn'` but still not working.

BTW, can we have `version = 0.18.1` for strict equality and `0.18.1+` for `>=`? I noticed from the code that the default is `>=`. It was done differently in R_library, see:

https://github.com/vatlab/SoS/blob/master/src/sos/targets_r.py#L42

**Comment by gaow** [comment]
Bump on this one. I think this is the only obstacle for our deadline in 2 days.

**Comment by BoPeng** [comment]
This is for this particular package, `pkg_resource` 
```
$ ls /Users/bpeng1/anaconda3/envs/sos/lib/python3.6/site-packages/sklearn
sklearn/               sklearn-0.0.dist-info/
```
always find version `0.0`. `sklearn.__init__` does show the correct version number so I will have to use that one first.

**Comment by gaow** [comment]
Yes i understand. Sorry I'd have to propose an interface change:

```
Py_Module("sklearn", autoinstall='False', pkgname='scikit-learn')
```

Because module name is not always package name for Python modules

**Comment by BoPeng** [comment]
Should be fixed. What was wrong with

```
Py_Module("sklearn", autoinstall='False', pkgname='scikit-learn')
```
The package name is not important if the module is not installed, so it made sense to me to say 
1. `autoinstall=True` , yes, auto install `skearn` if `sklearn` is not available.
2. `autoinstall='scikit-learn'` , yes, auto install `scikit-learn` if `sklearn` is not available.
3. `autoinstall=False`, do not install if `sklearn` is not available.

**Comment by BoPeng** [comment]
I can make another release if you can confirm all examples are running correctly now.

**Comment by gaow** [comment]
As long as version string can be fixed there is no problem with the current interface.

The example now works. But again when I specify for example `0.18.1` it assumes versions greater than `0.18.1` will work. What if I need it fixed at an earlier version? Could we use the same syntax / logic as in:

https://github.com/vatlab/SoS/blob/master/src/sos/targets_r.py#L42

**Comment by BoPeng** [comment]
Ok, let us follow the convention from setuptools http://peak.telecommunity.com/DevCenter/setuptools#declaring-dependencies

**Comment by BoPeng** [comment]
The module and package name discrepancy is not easy to resolve.

setuptools is based on packages. If we are to use setuptools convention, we should forget about module name and use package name, and replace `Py_Module` with something like

```
Py_Requirements('scikit-learn>=0.18')
```
even
```
Py_Requirements('''
scikit-learn>0.18
whatever
''')
because we are essentially dealing with an `requirements.txt` file.

If we are to check the existence of `module`, then we have to do something like

```
Py_Module('sklearn')
```
to check the availability of the module (not the package). Then should we have
```
Py_Module('sklearn', version='>=0.18', autoinstall='scikit-learn>=0.18')
```
or
```
Py_Module('sklearn>=0.18', autoinstall='scikit-learn>=0.18')
```
or something of this sort? You can see that I dislike duplicate specification.

**Comment by BoPeng** [comment]
So, if 
```
Py_Module('sklearn')
```
works for our examples. I think we should just use it, forget about version comparison and raise an error is the module is not available, and leave the more troublesome `Py_Requirements` for later.

**Comment by gaow** [comment]
Yes unfortunately the `sklearn` example I picked is a trouble maker. Currently it seems to work. Let me just edit it to the same interface as  `R_library` for now and call it a day.

**Comment by gaow** [comment]
Oh okay i see it is not changed to `setuptools` convention. Sorry i misunderstood. Then let's leave it as is for now.

**Comment by BoPeng** [comment]
Please also do not use the `version` parameter of `Py_Module` because it could become

```
Py_Module('sklean>=0.18')
```
to be consistent with future
```
Py_Package('scikit-learn>=0.18')
```

**Comment by BoPeng** [comment]
OK, since it is almost trivial to implement, I have added

```
Py_Module('sklern', version='>=0.18.0')
Py_Module('sklearn>=0.18.0')
```
where `>=` can also be `>`, `<`, `==`, `!=`, `<=`. The only operator that is not supported is `,`. I personally like the second shortcut syntax but let us keep `version` for compatibility reasons.

**Comment by BoPeng** [comment]
Just a reminder that we should make the syntax consistent with `R_Library`.

**Comment by gaow** [comment]
> Just a reminder that we should make the syntax consistent with R_Library.

Done.

**Comment by BoPeng** [comment]
There is one question, I treated 

```
Py_Module('sklean', version='0.18.0')
```
as
```
Py_Module('sklean>=0.18.0')
```
and you treated in `R_Library`
```
R_Library('something', version='0.18.0')
```
as
```
R_Library('sklean==0.18.0')
```
and we need to be consistent.

**Comment by gaow** [comment]
I think `==` is more reasonable ...

**Comment by BoPeng** [comment]
ok. I changed to ==, now this ticket can really be considered closed.
