### ISSUE TITLE
Stop step name aliasing.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1075]
Currently we assume that 

```
[10]
[20]
```
is the same as
```
[default_10]
[default_20]
```
and allow the use of
```
sos run script default
```

We also allows
```
[A]
[A_20]
```
and assumes 
```
[A]
```
is equivalent to
```
[A_0]
```

These all make sense but has caused ambiguity in the specification of `sos_step` and `from_steps`.

For example, we need to make sure that both

```
sos_step('default_10')
```
and
```
sos_step('10')
```
work, and perhaps also
```
sos_step('default')
```
and things get complicated with the new `from_steps` input option because

```
[10]
[20]
[30]
input: from_steps=['default_10']
```
would be confusing but it is difficult to support 
```
[10]
[20]
[30]
input: from_steps=['10']
```
because of internal use of `default_10`. (It is not very difficult but troublesome and confusing anyway).

I would suggest that we get rid of step name aliasing and use whatever user specifies as the step name. The side effect is that we can no longer do

```
sos run script default
```
because the workflow does not have a name, but the numeric numbered steps are the default ones so `default` in the command is not needed anyway.

**Comment by gaow** [comment]
I agree. I have had this problem with `sos_step` before. With the new "share" the default behavior can indeed be more confusing than before. But if a script only has one step will that be recognized and used as default? When there are multiple steps, will the ones with `default_` be recognized to be the default step with `sos run`? I am talking about backwards compatibility.

**Comment by BoPeng** [comment]
Yes, workflow `A`

```
[A]
```
or
```
[A_1]
[A_2]
```
will be called by
```
sos run script
```
since `A` is the only workflow in the script.
