### ISSUE TITLE
Failed jobs make SoS hang on cluster

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1078]
It seems a new problem with the `zmq` queue but I cannot (yet) come up with a good MWE for it. In short I have some tasks submitted to cluster and failed due to errors in the script not related to SoS. But instead of quitting properly (commit to signature DB and quit) it hangs. I have to `ctrl-c`, try to figure out what is wrong, and rerun them. When I rerun I noticed some previously successful substeps are not ignored, possibly due to https://github.com/vatlab/SoS/commit/46e6f94d287d01e708a40f6a57b2327f8e2e5eda. I've been wrestling with it the whole day trying to fix issues on my end, but I might have to eventually give it up and revert to pre-zmq version to get my work done ... 

@BoPeng I do not have a MWE, but with modification to our favorite `hang_test.sos` example here:

[hang_test_cluster.tar.gz](https://github.com/vatlab/SoS/files/2454626/hang_test_cluster.tar.gz)

I was able to reproduce it reliably. 

## The hang-test example

It contains a `sos` file and `yml` file. 

- The `sos` file has on line 36 a variable that has not been defined `not_exist_foo`. It should create a failure
- The `yml` file defines my cluster configuration. The key is that I submitted the job from the headnode. 

To run the example:

```
sos run hang_test.sos.txt -c hang_test.localhost.yml
```

## The output files

![2018-10-07-22-08-24_scrot](https://user-images.githubusercontent.com/917985/46591040-8a036080-ca7d-11e8-9c70-969bf4886e64.png)

you can see the time stamps: 21:52 is when the last output `rds` file was generated, which is >10min ago.

## The hang screen

![2018-10-07-22-09-52_scrot](https://user-images.githubusercontent.com/917985/46591074-ba4aff00-ca7d-11e8-8869-d518c831fbd5.png)

It is hanging for quite a while. My task queue is currently empty. 

## Other comments

I recall that previously the problem was that SoS reports failures and quits workflow but the jobs in question was in fact successful. We decided to look into that with `zmq` but now the hang behavior is worse ...

**Comment by gaow** [comment]
Updates: 

1. if it helps, I ran another workflow which succeeded in every single substep. SoS quits nicely in this case without reporting false alarms that some steps failed (which was the case before).
2. Another way to reproduce the hang issue, which is simpler, is to mess up the `yml` configuration's job template, eg, make it a single line or remove the `#` whatever messes it up. Then interestingly at least on my end all jobs will report `submitted` and hang there. But for my example in the thread above the `sos status` check was indeed `failed`. So it is perhaps better to test that example first.

**Comment by BoPeng** [comment]
Still trying to reproduce the issue with my VM, please be patient.

**Comment by gaow** [comment]
Sure, great! Yes we should do it one at a time -- try to reproduce and fix "failed" hang first (with my example running as is); then I'll test the patch on my end that "submitted" hang i mentioned in the 2nd thread and see if it still exists, then worry about reproducing and fixing that.

**Comment by BoPeng** [comment]
I can reproduce some problems but solutions are hard. Generally speaking, we have focused on errors in scripts and tasks, but no errors of job submission etc. Whereas such errors will error out sos easily before, current the zmq implementation require all processes to shutdown properly, so the error has to be handled at a global level...

**Comment by gaow** [comment]
I see. Indeed another type of hang is also very easy to reproduce but am reporting it here anways: when the run time exceeds required resource the job will be aborted and cause a hang.

**Comment by BoPeng** [comment]
Previously, we 

1. step send tasks to master
2. master submit and collect results
3. if all pass, master sends results to step and allow it to complete
4. if some tasks fail, the master would quit. The step workers would die silently.

With zmq, the master cannot shutdown completely with worker still running.

**Comment by BoPeng** [comment]
Should be better now, but not sure if it solves the job submission problem.

**Comment by gaow** [comment]
The hang test example script now quits properly! That's an error from the script right? It would be nice to display the task ID for the failed tasks though so that people can use `sos status` to track them. Currently it only says:

```
ERROR: Workflow failed due to error
```

I'm not sure what you meant by "I can reproduce some problems" and "Should be better now". I just messed up my job template to create syntax error for my `sbatch` command. Again I got a hanging screen. Messing up that template is straightforward: just remove all line break and make the job template a one liner, then you should see the hang problem.

**Comment by BoPeng** [comment]
This patch handles error from job submission command better.

**Comment by gaow** [comment]
Okay the behavior of failed job is a lot better. It currently points to the exact sub-step that went wrong, the problematic script, and the task ID of it. Also instead of quitting altogether it continues to run other steps independent of the failed step and reports the failure at the very end. This is very good. I believe it is the case for non-task anyways. Good to have them consistent.

However I do not think the problem is fixed for messed up template. It still hangs. Can you reproduce it? How about trying to change the folder for `stdout` and `stderr` to some non-existing directory? On my system this is also a good way to reproduce a type of hang. eg, my `showq` is empty but 

```
 sos status M5_fe671fedde2a7928 
M5_fe671fedde2a7928     3646e05e00ca3c5a normal Ran for 1 day   submitted
```

and the hang:

```
INFO: M5_32d2ad5b00fab26e submitted to midway2_head with job id 50877470


INFO: M5_fe671fedde2a7928 submitted to midway2_head with job id 50877471
INFO: M5_be2d1662fc65d995 submitted to midway2_head with job id 50877473
INFO: M5_0401a7b7a8477c59 submitted to midway2_head with job id 50877474
INFO: M5_16efb430ecc21c8d submitted to midway2_head with job id 50877475
INFO: M5_3f1b18244d1729ea submitted to midway2_head with job id 50877476



```

This is because I changed the `stdout` and `stderr` path to some crazy directory.

**Comment by BoPeng** [comment]
OK. Messed-up template is still not fixed because I only fixed case then the submission command fails to generate a job ID... I am working on a binder example on.

**Comment by BoPeng** [comment]
This does not look like fixable. The shell scripts generated by the template are executed by the scheduler and `sos` would not be executed if the shell script itself is problematic, and there is no chance for sos to do anything.

**Comment by gaow** [comment]
Oh that explained it! I always thought SoS relies on `qstat` so I am always a bit confused when I notice inconsistencies between `qstat` and what SoS determines. Then seems SoS works reasonably well independently without info from qstat, until this issue comes up! Maybe as you suggest, we can make status command a "secondary" (hard to define) mechanism to help determine SoS status.
