### ISSUE TITLE
Rerun completed workflow triggers a DAG bug

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1079]
Still need to come up with a MWE but I can mostly reliably trigger [this line](https://github.com/vatlab/SoS/blob/8fe695d50f4114e6c70910d13ad5d191255be906/src/sos/dag.py#L249). The error message is:

```
INFO: Running summarize_ld: 
INFO: Target unavailable: sos_step("liter_data")
ERROR: Completed target sos_step("liter_data") is being re-executed. Please report this bug to SoS developers.
```

The error is triggered by:

1. Successfully run the step in question 
2. Run with `-s build` to rebuild signature (not sure if this is needed to reproduce it. i do it to test recent SoS patches)
2. In another run, rerun the workflow without `-s build`. But for the step in question all signatures are matched and ignored.
3. The error message shows up and quits.
4. running exactly the same command again, the error message disappears and 

I can try to come up with MWE (or based on the hang test) later. Just documenting it here in case there are immediate thoughts.

**Comment by BoPeng** [comment]
Let me know if the patch works.

**Comment by BoPeng** [comment]
Assume it is fixed.
