### ISSUE TITLE
`clean_output()` calls

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1081]
when I ctrl-c my code, I got an error : 

```
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/site-packages/sos/substep_executor.py", line 155, in _execute_substep
    clear_output()
TypeError: clear_output() missing 1 required positional argument: 'e'
```

It refers to  [this line](https://github.com/vatlab/SoS/blob/975b9dbd4f2d77f7f23b325a0881962f14c7dfd7/src/sos/substep_executor.py#L155). then I noticed there are multiple places in the code where `clean_output` are used wrong .. .

**Comment by BoPeng** [comment]
Sorry. These were debugging code that I failed to clean.
