### ISSUE TITLE
A bug with zap

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1087]
Im in a rush now, but without a MWE this is what I've done:

1. have a `default_2` step that included at the end of it `_input.zap()`; successfully executed.
2. edited `default_2` and rerun it.

I got:

![2018-11-05-19-12-55_scrot](https://user-images.githubusercontent.com/917985/48038091-c2f22c00-e134-11e8-8865-49c6ee145f64.png)

I expect that case `default_1` should be reran to generate the file again?

**Comment by BoPeng** [comment]
Let me try to reproduce the problem.

**Comment by BoPeng** [comment]
Isn't this expected?

1. input file is zapped, leaving a `.zapped` file
2. change step and rerun
3. sos found that the step needs to rerun, and try to find the real input
4. sos failed to find the original input file and produce an error

The point here is that zapped file can be ignored only if the step does not need to be rerun.

**Comment by gaow** [comment]
Well, i thought if SoS failed to find the original input it is going to rerun the previous step. The point of zapped file is to be able to help skipping execution if nothing has been changed. But when things do change it should ditch that zapped file and start over. Otherwise how can i start over? Manually removing zapped file first? `-s force` will trigger rerun for everything thus not idea behavior.

**Comment by BoPeng** [comment]
The patch fixes the test case I generated but might not fix your problem. Please try again.

**Comment by gaow** [comment]
Great thank you! I will do it first thing tmr to ensure our next release incorporates the patch.

**Comment by gaow** [comment]
I think the problem is with substeps. The workflow below will exactly reproduce what I was complaining about:

```
[step_10]
chrom = [1,2,3]
input: for_each = 'chrom'
output: f'{_chrom}.txt'
sh: expand = True
  echo "hellp" > {_output}

[step_20]
input: group_by = 1
output: _input.with_suffix('.bak')
sh: expand=True
   cp {_input} {_output}

_input.zap()
```

The error:

```
INFO: Running step_10: 
INFO: step_10 (index=0) is ignored due to saved signature
INFO: step_10 (index=1) is ignored due to saved signature
INFO: step_10 (index=2) is ignored due to saved signature
INFO: output:   1.txt 2.txt... (3 items)
INFO: Running step_20: 
WARNING: Removing 1.bak generated by failed step step_20.
ERROR: [step]: No step to generate target 1.txt requested by step_10

```

**Comment by BoPeng** [comment]
OK, the problem here is that

1. Step 1 is ignored because of the existence of zapped file.
2. Step 2 needs to be rerun because of step change
3. Step 2 look for `1.txt` but failed, it looks for auxiliary steps that generates it, still failed.

So the problem is that sos treats
```
[step_10]
output: 'a.txt'
sh:
  echo "hellp" > a.txt
```
as an automatic-auxiliary step because output is clear. It does not treat 
```
[step_10]
chrom = [1,2,3]
input: for_each = 'chrom'
output: f'{_chrom}.txt'
sh: expand = True
  echo "hellp" > {_output}
```
as auxiliary step because the output is undetermined at parsing time.

Solution?
1. Be more clever about auxiliary step, or
2. Check processed signatures for this particular case (e.g. signature pass with zapped file).

**Comment by BoPeng** [comment]
It turns out that the mechanism is already there but not working due to an error in the order of parameter passing.
