### ISSUE TITLE
Kernel dies when trying to create SoS notebook (on debian stable)

### ISSUE THREAD

**Issue by N7DR** [vatlab/SoS#1089]
Running debian stable (64 bit).

I installed jupyter notebook and the py3 and py2 kernels from the official debian repositories, and those seem to be working correctly.

To install SoS support, I followed the instructions at https://vatlab.github.io/sos-docs/, slightly modified to ensure that python3 was being used (since python2 is the default on this system):

[HN:~] pip3 install sos
[HN:~] pip3 install sos-notebook
[HN:~] python3 -m sos_notebook.install

These commands appeared to run without error.

I then start jupyter, and attempt to create a SoS notebook:

[HN:~] jupyter-notebook                                                               
[I 14:27:25.357 NotebookApp] Serving notebooks from local directory: /home/n7dr
[I 14:27:25.357 NotebookApp] 0 active kernels 
[I 14:27:25.357 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/                                                                                                   
[I 14:27:25.357 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 14:27:37.552 NotebookApp] Creating new notebook in                                            
[I 14:27:39.647 NotebookApp] Kernel started: f288e746-92bb-492f-adf6-34bb8ec649d2
Traceback (most recent call last):                                  
  File "/usr/lib/python3.5/runpy.py", line 183, in _run_module_as_main                                                                                                          
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 153, in _get_module_details
    code = loader.get_code(mod_name)                                        
  File "<frozen importlib._bootstrap_external>", line 775, in get_code        
  File "<frozen importlib._bootstrap_external>", line 735, in source_to_code                     
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed  
  File "/home/n7dr/.local/lib/python3.5/site-packages/sos_notebook/kernel.py", line 50
    f'<div class="sos_hint">{hint_line}</div>').data}
                                             ^
SyntaxError: invalid syntax
[W 14:27:39.904 NotebookApp] 404 GET /static/components/codemirror/mode/sas/sas.js?v=20181107142725 (::1) 10.32ms referer=http://localhost:8888/notebooks/Untitled19.ipynb?kernel_name=sos

The kernel restarter tried to restart the kernel a few times, always with the same result.

**Comment by gaow** [comment]
@N7DR SoS requires Python 3.6. You must be on 3.6 when you install otherwise it will fail at installation. I noticed your kernal calls Python 3.5 though. Can you configure it to run on Python 3.6?

**Comment by N7DR** [comment]
I just came to the same conclusion after digging for a bit... the specific problem is that f-strings aren't defined in 3.5 :-(

The latest python supported by debian stable is 3.5.

So I guess I am stuck. Pity. I was looking forward to using jupyter notebook. The limitation to a single kernel per notebook is too restrictive for it to be useful for me, so I was delighted to discover SoS. But it seems that SoS is incompatible with the current release of debian stable, and it's expected to be quite a while before the debian 10 becomes the official stable release :-(

**Comment by BoPeng** [comment]
SoS relies on the format string feature of Python 3.6 so does not work with Python 3.5. We use SoS on Delian with anaconda python (python 3.7) without problem.

**Comment by gaow** [comment]
@N7DR yes I should add that it is perhaps always good idea to avoid `apt-get` for scientific computing stuff. We find `conda` (shipped with anaconda or miniconda) a good alternative. My Linux desktop is in fact Debian 8.x. `miniconda` is easy to setup, if you want to give it a go. It is lighter-weight than `anaconda` so it would be a good start if you are not yet into using `conda`. Installation takes <1min. But before that you may want to remove existing SoS installation `pip uninstall sos sos-notebook ...`

**Comment by gaow** [comment]
Also I bet your computer must have Python 3.6 installed somewhere; otherwise SoS installation would not pass. It's just a matter of relinking the kernel. Which I'm not sure how to do. So it is cleaner to start with miniconda

**Comment by BoPeng** [comment]
No, `python setup.py` will check python version but `pip install sos` does not seem to do that... I am trying to find a way to let pip know the minimum python version now.

**Comment by BoPeng** [comment]
This 

```
python_requires='>=3.6',
```
feature is pretty recent. With the patches `pip` version 9 and higher should disallow the installation of sos to python 3.5 and lower.
