### ISSUE TITLE
New zmq version hang on start 

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1090]
Again using our favorite hang test example:

[hang_test.sos.txt](https://github.com/vatlab/SoS/files/2567558/hang_test.sos.txt)

`sos run hang_test.sos.txt`

This time you'll notice it takes quite a while to even start running, which used to take a second in non-zmq era. 

@BoPeng Can you reproduce on your end?

**Comment by BoPeng** [comment]
It take a while to start (I can check what is going on), but no hang.

On a machine with totally messed up R

![image](https://user-images.githubusercontent.com/9889312/48289793-4a41e700-e436-11e8-8b4a-95baf0c426af.png)

This is because my R is messed up though.

**Comment by gaow** [comment]
Sorry I meant to say it takes a while to start but did not hang. it is just easier to use our existing `hang_test.sos` example as the more complicated MWE to report problems -- remember this example has helped us making various improvements and bug fixes in the past. It is called hang test for historical reasons :) 

Yes what bothers is the slowness to start. I have in practice examples that starts a lot slower. It would be nice to figure out what is going on here.

**Comment by BoPeng** [comment]
Try again.

**Comment by gaow** [comment]
Starts instantly now. But all it is needed is to reduce the delay time? Is that going to create problems? I guess you must have a reason to set it to 100 earlier?

**Comment by BoPeng** [comment]
The delay has the unit of ms. I just copied some code that uses 100ms and thought that 0.1 is not too bad. But if you have 100 sos_step requests like this example, it will just wait 10s.

The code is supposed to handle all "existing" messages so waiting even 0s should be ok.

**Comment by gaow** [comment]
Ha do you want to change other places that you've copied the code? I'm cool to close this ticket now.

**Comment by BoPeng** [comment]
I think these are the only places of calling `poll` on sockets.
