### ISSUE TITLE
Database connection caused signature fail

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1091]
Sorry for the lack of MWE (hard to reproduce), but there is a warning message in a job execution:

```
WARNING: Failed to push signature ['step', 'sampling', {'input': {}, 'output': ...: 'NoneType' object has no attribute 'executemany'
```

which looks like it can be attributed to [this line](https://github.com/vatlab/SoS/blob/7156fbda4e74d91be894701f3618a6b15001f493/src/sos/signatures.py#L30). Is it possible to confirm that the logic is problematic here, thus triggering the warning?

**Comment by BoPeng** [comment]
That line looks ok because self._conn is created at line 25. Line 38 is problematic though. Could you change

```
self._conn.ex
```
to 
```
self.conn.ex
```
and try again?

**Comment by BoPeng** [comment]
Just pushed a fix.

**Comment by gaow** [comment]
Oh of course its that write line. I coped the wrong line when I looked it on github for the link. Anyways, yes the patch looks like the proper fix. Thank you! I'll close it for now.
