### ISSUE TITLE
Circular dependency of SoS packages

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1096]
@BoPeng this problem below prevents @jdblischak from an attempt to create conda package for SoS (#896 which we once visited). Specifically as reported in an offline message:  

- sos depends on sos-pbs, sos-rq, and sos-bioinfo https://github.com/vatlab/SoS/blob/master/setup.py#L110
- sos-rq depends on sos https://github.com/vatlab/SoS-rq/blob/master/setup.py#L41
- sos-pbs depends on sos https://github.com/vatlab/SoS-pbs/blob/master/setup.py#L41
- sos-bioinfo depends on sos https://github.com/vatlab/SoS-bioinfo/blob/master/setup.py#L41

In this case it is not possible to create a conda package for anyone of them without already having a conda package for at least one other. 

I'm looping in @jdblischak for this one and possible other discussions RE SoS on conda cloud.

**Comment by BoPeng** [comment]
SoS dependencies on other sos components was introduced to make it easier to install the complete package. The bioconda folks thought that circular dependencies are valid and submitted a patch for it although the bioconda recipe for sos (created by another user) has been sitting there for a while. We can remove the dependencies if needed.

**Comment by gaow** [comment]
I think it is reasonable to remove these dependencies. Particularly if that's what helps SoS on `conda-forge`

**Comment by jdblischak** [comment]
I see. It makes sense to submit SoS to the bioconda channel (instead of conda-forge) since sos-bioinfo depends on pysam.

>  The bioconda folks thought that circular dependencies are valid and submitted a patch for it although the bioconda recipe for sos (created by another user) has been sitting there for a while. We can remove the dependencies if needed.

Looking at the recipes in https://github.com/bioconda/bioconda-recipes/pull/9457, it appears that they just removed sos as a dependency for the sos subpackages. If sos-rq, sos-pbs, and sos-bioinfo will install successfully using this strategy, then I agree that should work without having to change the packages themselves.

**Comment by gaow** [comment]
`sos-bioinfo` should be dependency for `sos-notebook` not `sos`. I'm thinking it makes it better to have `sos` on `conda-forge`. Should we remove that dependency for this purpose? How about `sos-notebook` then?

**Comment by BoPeng** [comment]
I think we have gone a little too far to make `sos` easy to install. Technically speaking, `sos` is the core package that should not depend on any other sos component. `sos-pbs` and `sos-rq` should depend on `sos` and be installed only for `pbs` and `rq` systems, and `sos-bioinfo` should be installed when the handling of bioinformatic file types is expected. The same hold for `sos-notebook`, which should not depend on any language module.

@gaow , I have removed the dependencies and released sos 0.17.6. Feel free to create a recipe for sos without any other components for `conda-forge` and we can start from there.

**Comment by gaow** [comment]
Great! For `conda-forge` does it make sense to create an `sos-essentials` meta-package that installs them `sos sos-rq sos-pbs` and possibly more? I think we've been there before but in the context of `pip` and got rid of it. In the context of `conda` maybe it makes sense to revisit the notion of a meta-package because this is a platform that will make SoS truly easy to install (without a compiler)?

**Comment by BoPeng** [comment]
That was why I said “let us start from here”. SoS first.

**Comment by gaow** [comment]
Oh okay sure, I think @jdblischak is already ahead of us. @jdblischak would you be willing to kindly make this happen on `conda-forge` when you get a chance? Maybe start from the core `sos` and add others, or maybe you've already have some meta-package idea in mind in addition to each module? we can use a separate ticket for this.

**Comment by jdblischak** [comment]
@gaow I'll submit a recipe for sos to conda-forge. I'll add you both as recipe maintainers (this will make it easier for you to update in the future) and ping you in the Pull Request.

I think an `sos-essentials` metapackage is a good idea. However, I think it should be super convenient and install the notebook and kernel support as well. This way new sos users can get started experimenting with sos immediately, while still allowing more advanced users to selectively install only the packages they want.

(sorry for the delayed response. I typed this yesterday, but apparently I forgot to post it)
