### ISSUE TITLE
SoS save to HTML: send_frontend_msg() got an unexpected keyword argument 'title'

### ISSUE THREAD

**Issue by mathieuboudreau** [vatlab/SoS#1100]
I've been using the SoS functionality of saving to HTML from within a Jupyter Notebook quite heavily (thank you!!), however, today all my notebooks have been giving me errors when trying to do so:

```
Failed to save workflow: send_frontend_msg() got an unexpected keyword argument 'title'
```

Screenshot:

<img width="560" alt="capture d ecran 2018-12-05 a 18 10 07" src="https://user-images.githubusercontent.com/1421029/49545831-5300ce00-f8b9-11e8-9aad-a64f755a072d.png">

The last day that I successfully generated an HTML with SoS was on November 27 2018, from my records on GitHub.

My notebooks are set up in a [GitHub repo](https://github.com/qMRLab/t1_notebooks/tree/blog_vfa) with a [Dockerfile](https://github.com/qMRLab/t1_notebooks/blob/blog_vfa/Dockerfile), so you can test for yourself using the same environment that I'm using with [MyBinder](https://mybinder.org/v2/gh/qMRLab/t1_notebooks/blog_vfa) (e.g. go in blog_vfa/VariableFlipAngle.ipynb and try to create an HTML without running the notebook, which takes 30-40 minutes).

My Dockerfile installs the most up to date versions of all packages (I tried freezing it, however another package complained about SoS not being up to date when I did so, so I stopped). The output of `pip freeze `today is:

<details>

```

alembic==0.9.9
appdirs==1.4.3
asn1crypto==0.24.0
async-generator==1.10
attrs==18.1.0
Automat==0.0.0
backcall==0.1.0
bleach==2.1.4
certifi==2018.8.13
cffi==1.11.5
chardet==3.0.4
Click==7.0
conda==4.5.8
constantly==15.1.0
cryptography==2.2.1
cycler==0.10.0
dash==0.31.1
dash-core-components==0.40.2
dash-dangerously-set-inner-html==0.0.1
dash-html-components==0.13.2
dash-renderer==0.15.1
decorator==4.3.0
entrypoints==0.2.3
fasteners==0.14.1
feather-format==0.4.0
Flask==1.0.2
Flask-Compress==1.4.0
html5lib==1.0.1
hyperlink==17.3.1
idna==2.7
incremental==17.5.0
ipykernel==4.8.2
ipython==6.5.0
ipython-genutils==0.2.0
itsdangerous==1.1.0
jedi==0.12.1
Jinja2==2.10
jsonschema==2.6.0
jupyter-client==5.2.3
jupyter-core==4.4.0
jupyterhub==0.9.2
jupyterlab==0.34.0
jupyterlab-launcher==0.13.1
kiwisolver==1.0.1
Mako==1.0.7
Markdown==3.0.1
MarkupSafe==1.0
matplotlib==3.0.2
metakernel==0.20.14
mistune==0.8.3
monotonic==1.5
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.2
notebook==5.6.0
numpy==1.15.4
octave-kernel==0.28.4
pamela==0.3.0
pandas==0.23.4
pandocfilters==1.4.2
parso==0.3.1
pexpect==4.6.0
pickleshare==0.7.4
plotly==3.4.2
prometheus-client==0.3.0
prompt-toolkit==1.0.15
psutil==5.4.8
ptyprocess==0.6.0
pyarrow==0.11.1
pyasn1==0.4.4
pyasn1-modules==0.2.1
pycosat==0.6.3
pycparser==2.18
pycurl==7.43.0.2
pydot==1.4.0
pydotplus==2.0.2
Pygments==2.2.0
pyOpenSSL==18.0.0
pyparsing==2.3.0
PySocks==1.6.8
python-dateutil==2.7.3
python-editor==1.0.3
python-oauth2==1.0.1
pytz==2018.7
PyYAML==3.13
pyzmq==17.1.2
requests==2.19.1
retrying==1.3.3
ruamel-yaml==0.15.44
sas7bdat==2.2.1
saspy==2.4.0
scipy==1.1.0
Send2Trash==1.5.0
service-identity==17.0.0
simplegeneric==0.8.1
six==1.11.0
sos==0.17.7
sos-bash==0.12.3
sos-javascript==0.9.12.2
sos-julia==0.9.12.1
sos-matlab==0.9.12.1
sos-notebook==0.17.3
sos-python==0.9.12.1
sos-r==0.9.12.3
sos-ruby==0.9.15.0
sos-sas==0.9.12.3
SQLAlchemy==1.2.11
tabulate==0.8.2
terminado==0.8.1
testpath==0.3.1
tornado==5.1
tqdm==4.28.1
traitlets==4.3.2
Twisted==18.7.0
urllib3==1.23
Wand==0.4.5
wcwidth==0.1.7
webencodings==0.5
Werkzeug==0.14.1
xxhash==1.3.0
zope.interface==4.5.0

```

</details>

**Comment by mathieuboudreau** [comment]
Maybe [this commit](https://github.com/vatlab/sos-notebook/commit/7f4314cefcffbe0665b4bdcc81d6c4f8848e45ed) in `sos-notebook` is to blame?

**Comment by BoPeng** [comment]
Yes, all the mess due to vatlab/sos-notebook#150, which is almost done though.

**Comment by mathieuboudreau** [comment]
Ok thanks! I'll try setting `sos-notebook < 0.17.3` as a temporary fix, glad to know you were aware!

**Comment by BoPeng** [comment]
@jdblischak The sos notebook trunk is ready for test. vatlab/sos-notebook#150 changes the side panel to an interface that resembles the console window of JupyterLab, which will make the two platform more consistent. The `%sossave` magic can now be executed with the save icon.
