### ISSUE TITLE
Support for named input

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1106]
http://bionics.it/posts/workflows-dataflow-not-task-deps

```
# Run the same task on the two splits
t1 = Task1()
t2 = Task1()
t3 = Task2(
        in1 = t1.outspec('out1')
        in2 = t1.outspec('out2')
        in3 = t2.outspec('out1')
        in4 = t2.outspec('out2'))
```

So `t3` gets input `in1`, `in2`, `in3`, `in4` as step `t1`'s `out1`, `out2`, `out1`, `out2` respectivelyl.

What we have is

```
[t1]

[t2]

[t3]
input: from_steps=['t1', 't2']
```
and we cannot differentiate individual outputs from steps `t1` and `t2`.

**Comment by BoPeng** [comment]
We do have

```
[t3]
input: {
    'name1': filelist1
    'name2': filelist2
}
```
but `name1` and `name2` cannot be used directly and have to be used through `_input['name1']` etc.

**Comment by BoPeng** [comment]
Our implementation of `input` uses positional arguments for file list, but this can be relaxed as

```
[t3]
input: name1=filelist1, name2=filelist2
```
as long as `name1` etc do not conflict with our existing options such as `group_by`.

Also, we could define `name1` and `name2` **in addition** to `_input` (but still allows `_input['name1']` etc because our `group_by` etc will depend on `_input`.

**Comment by gaow** [comment]
> but name1 and name2 cannot be used directly and have to be used through _input['name1'] etc.

What is the problem with this approach? I think we have named input in place by that definition already, and we only worry about named output? 

Also we already have, 

```
[t3]
name1=filelist1
name2=filelist2
input: name1, name2
```

right? Now when `group_by` is used, these names are not directly usable in a meaningful way in a workflow step. But there are many cases without `group_by` that our existing approaches can already handle for the input part. I doubt we need new syntax to use these variables in a step.

**Comment by BoPeng** [comment]
You are right about

```
[t3]
name1=filelist1
name2=filelist2
input: name1, name2
```

The proposed syntax
```
[t3]
input: name1=filelist1, name2=filelist2
```
will allow `_input['name1']` but I am not sure if we should expose `name1` directly in this case. [snakemake](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html) seems to be using `_input.name1` which is more succinct.

**Comment by gaow** [comment]
> _input.name1, _input.name2, ...

Okay I'm cool with that (in fact neutral), as long as we still have `_input` in there which makes the syntax very clear. I do not think `_input['name1']` is too bad.

> extend from_steps

Conceptually it makes it hard (at least for me) to think about `group_by` behavior based on source -- how do we deal about it then? We also have `group_by` in `output`. It feels like `group_by` behavior has to be changed too.

**Comment by gaow** [comment]
Oh okay seems our messages are crossing but thoughts are converging ... I think `group_fastq_by='1'` you said above is more like some `for_each` extension. In light of that, maybe along the lines of `group_by = ('fastq', 1)`?

**Comment by BoPeng** [comment]
Yes, we have kept the `group_by` option to a single parameter, and it seems ok to allow `group_by=('fastq', 1)`. I wrote `group_fastq_by` because it reads better and writes better, and we are the creator and can make it happen.

Things can get complicated. For example in our code example you might want to group the first named source by 2 and second named source by 1, so something like

```
input: out1=output_from('step1'), out2=output_from('step2'),
   group_out1_by=2, group_out1_by=1
```
which is actually not too bad...

**Comment by gaow** [comment]
sure, I agree it reads good by itself. But do we want to be somewhat consistent with other options? eg `for_each` is an option that takes a string, a list and dictionary `{(n,p): [_n < _p for _n in n for _p in p]}`. The last one is certainly flexible but does not read better. But they are all `for_each`. Maybe it is easier for users to learn, if we can take this opportunities to somewhat unify flavors of `for_each` and `group_by` rather than making them more different. We can also remove some of the paring based on source syntax.

**Comment by gaow** [comment]
so maybe we keep to having only `for_each` and `group_by`, but make these two very similar in flavor for various extensions. Also think of some really simple but common users cases (eg like from that blog) and make sure our mechanism does not make simple cases more complicated? 

> I felt that the use of for_each='i', which generates _i is a bit magically and should be deprecated.

but I think conceptually we have one `for_each` which takes string, list or a dictionary. This is intuitive to remember. `for_each_sample` constructs the LHS of a statement which indeed simplified the RHS, but is not that intuitive on tthe LHS because I expect programmers usually would like to focus on the RHS however ugly they are ...

**Comment by gaow** [comment]
Also when typed in full, the existing:

```
i = range(5)
for_each = 'i'
```

and the proposed:

```
for_each_i=range(5)
```

the proposed made the parameter `i` less explicit -- are you cool with that?

**Comment by BoPeng** [comment]
I know both arguments. I have written 

```
input: for_each={'i': range(5)}
```
for so many times for testing and I had hopefully we could make it easier. We can introduce the following
```
input: for_each_i=range(5)
```
as a syntax sugar for these kinds of thing but I know we pythonist should not crave for it.

**Comment by BoPeng** [comment]
```
i = range(5)
for_each = 'i'
```
is not good because

1. It does not show what the loop variable is (`_i` is out convention).
2. the use of `i` to refer to a variable name `i` is not quite natural because as I have said programmers are familiar with for_each over a loop, not a name.

**Comment by gaow** [comment]
> is not good because

I should have written:

```
parameter: i = range(5)
for_each = 'i'
```

with the potential to change `i` from command input. Of course interally we can still have `for_each = {'i': i}`.

>  as a syntax sugar for these kinds of thing but I know we pythonist should not crave for it.

Since SoS positions itself Python-based thus the low learning curve, maybe we want to be consistent about that?

**Comment by BoPeng** [comment]
Perhaps something like:

```
_i = for_each(i)
sample = for_each(samples)
```
and we tell user that `for_each` is some sort of generator and `_i` and `sample` would take one value each time?

**Comment by BoPeng** [comment]
We can also have something in effective of

```
fastq=group_by(step_input.fastq, 2)
```

**Comment by BoPeng** [comment]
So in the end we have a bunch of `input`-only functions (I would not make it available outside of `input`) that creates `names` that can be used in the content of the step.

**Comment by gaow** [comment]
> So in the end we have a bunch of input-only functions

But to me you are proposing `for_each()` to give a new data type, a generator, that we know conceptually will be used for input and naturally extends to output, implicitly. For example:

```
parameter: samples = list()
sample = for_each(samples)
bash: 
  echo {sample}
```

will run the bash script `len(samples)` times since `sample` is a generator? It is way too subtle to grasp.

**Comment by BoPeng** [comment]
Updated your example.

So we I said, the keyword arguments would generate names that can be used in the content, with the meaning of names determined by the RHS.

For example

```
input: fastq=output_from('step_2')
```
would allow the use of `_input.fastq` (even `fastq` if we decide so) in the script.
```
input: _i = for_each(range(5))
```
would allow the use of `_i` in the script.
```
input: fastq=group_by(output_from('step2'), 1)
```
would allow the use of `fastq` as one of the output of `step2` one by one.

Right now I do not see anything particularly difficult to digest, and we can keep our `group_by` options for a while.

**Comment by gaow** [comment]
so `output_from` and `group_by` will return file targets, but `for_each` will return parameters? The LHS does not reflect these differences. It still feels subtle to me.  What would this be like in the new syntax, for example?

```
parameter: filename = str # or path()
parameter: a = list
parameter: b = list
input: filename, for_each = ['a', 'b'], group_by = 1
```

From current syntax it is at least clear that group_by happens after for_each parameter and all accompanying `filename`.

**Comment by BoPeng** [comment]
Something like
```
parameter: filename = str # or path()
parameter: a = list
parameter: b = list
input: 
        _a=for_each(a),
        _b=for_each(b),
        _input=group_by(filename, 1)
```
if we use pure new syntax?

**Comment by gaow** [comment]
well, I guess this is what I meant earlier by trying to not make simple case more complicated. The new syntax seems to complicate things, and it is not very clear that `group_by` will loop over each `a` and `b` for input file `filename`.

**Comment by gaow** [comment]
> And the explicitly helps in more complex cases such as

Certainly ... but in this example the LHS of `=` are all input files. Mixing in `i = for_each()` is still awkward. Should one expect to access `i` via `_input.i`?

Also does it help to also outline the plan for named output and see if the theme match?

**Comment by BoPeng** [comment]
In terms of output, we can do something like:

```
input: fastq=group_by('*.fastq', 1)
output: bam=fastq.with_suffix('.bam')
```
Here `fastq` is similar to `_input`, and we allow the assignment of `_output` to `bam`.

I think we can keep the use of `_input` and `_output` for "default" input and output but use these syntax for named input and output, although it is currently unclear how to mix them together. For example, 

```
output_from('step').bam
```
would be named output, and 
```
output_from(step)
```
would be `_output`, but what is `_output` with the presence of `bam`?

If we keep our current `_input` (and `_output`) + `sources` implementation, 

```
output_from('step')
```
would be the complete `_output` (actually `step_output`), and 
```
output_from('step').bam
```
would be `step_output.bam`. and `step_output` still represents multiple outputs if there are multiple named outputs. The same goes to `_input`.

**Comment by BoPeng** [comment]
`_input.i` is actually not a bad idea but it allows us to pass all information belong to an input group together. In this case,

```
sample_names=['sample1', 'sample2']
input: 'ref.fa', fastq=group_by(['f1.fastq', 'f2.fastq'], 1), a = for_each(sample_names)
```
we can have an `_input` with components

```
step_input = 'ref.fa', 'f1.fastq', 'f2.fastq'
step_input.fastq = 'f1.fastq', 'f2.fastq' .
_input.fastq = 'f1.fastq'   # the same as _input['fastq']
_input[''] = 'ref.fa` # if really needed
_input.a = 'sample1'
```

**Comment by BoPeng** [comment]
In generally what we did for `from_steps` and `_input['source']` had named input and output almost there because `from_steps='a'` refers to output of a step, not just a step, there will be a lot of work for the new syntax though.

**Comment by BoPeng** [comment]
The `for_each` stuff handles parameters, which can be completely separated from the named input/output issues, so the only thing we need to worry about is `group_by`.

Whereas

```
input: unnamed, name1=whatever, name2=whatever2, group_by=('name1', 2)
```
would work, 

```
input: unnamed, name1=group_by(whatever, 2), name2=whatever2
```
seems to make more sense, although implementation-wise this syntax makes it difficult to determine `step_input` since this syntax technically specifies `_input.name1` directly.

**Comment by gaow** [comment]
> The for_each stuff handles variables, which can be completely separated from the named input/output issues, so the only thing we need to worry about is group_by.

agreed. Also agreed that the 2nd syntax is more intuitive. And we replace `from_steps = ` to `output_from()`? How would you translate the example

```
[lasso_3, ridge_3]
input: from_steps = [1, 2], group_by = 'pairsource2', concurrent = True
output: f"{_input[2]:nn}.mse.csv"
```

to the new interface? (not simply pairing, but by groups of 2 here)

**Comment by gaow** [comment]
good, this is what I thought too, but with `s1 = group_by(output_from(1), 2)`. So we are on the same page here at least for the input. Now that with `group_by = ` and `from_steps = ` eliminated I dont feel too bad about leaving `for_each` taking its own convention (and leave it current convention).

Any thoughts on eliminating `paired_with` and `group_with`? Now that we have `group_by` as a function we can add parameters ...

**Comment by gaow** [comment]
Also I assume:

```
input: group_by(1)
```
will still work?

**Comment by BoPeng** [comment]
Maybe, have not thought of how to implement the new syntax. At least `group_by=1` would be kept for a while, perhaps forever.

**Comment by gaow** [comment]
> At least group_by=1 would be kept for a while, perhaps forever.

I guess all current mechanism can be kept forever for backwards compatibility but we do not document it? (thinking of lots of my pipelines already distributed to colleagues or out there for published work).

It will be a bit easier if we use keyword arguments,  `group_by(variable, size = ..., with = ..., )`, eg, the following are allowed

```
input: variable # set variable to _input
input: group_by(variable, size = 1) # same as _input = group_by(variable, size = 1)
input: group_by(size = 1) # same as _input = group_by(output_from(previous_step), size = 1)
```

**Comment by BoPeng** [comment]
A member function `group_by` is added to `sos_targets` that allows:

```
input: sos_targets('a.txt', 'b.txt').group_by(1)
```
and will support
```
input: output_of('step_2').group_by(1)
```
later.

The problem is how we should implement classical unnamed `group_by`. The new way

```
input: sos_targets('a.txt', 'b.txt').group_by(1)
```
is a bit long and needs explicit use of `sos_targets`.

Keep using
```
input: 'a.txt', 'b.txt', group_by=1
```
is possible but we are deprecating `group_by=1`.

There is another option for applying `group_by(1)` to nothing (namely the default `step_input`),
```
input: 'a.txt', 'b.txt', group_by(1)
```
but I am not sure if this is logically clear because we are adding an "action" as one of the input elements.

**Comment by gaow** [comment]
Previously I was suggesting:

```
input: variable # set variable to _input
input: group_by(variable, size = 1) # same as _input = group_by(variable, size = 1)
input: group_by(size = 1) # same as _input = group_by(output_from(previous_step), size = 1)
```

I think making it a class member function `.group_by` is even more confusing because we do not have other such class member functions.

**Comment by BoPeng** [comment]
OK, I was not particularly fond of 

```
group_by(size=1)
```
because we have to use keyword argument here (I guess not a big deal?). The syntax also has the problem of

```
input: 'a.txt', 'b.txt', group_by(size=1)
```
because it is unclear if `group_by` should group `a.txt`, `b.txt` or `output_from(previous_step)`. The latter case can be confusing but easier to implement, the former is difficult to implement because we are evaluating parameters referring to previous ones.

**Comment by BoPeng** [comment]
Also, I would prefer

```
group(by='pair')
```
over
```
group_by(size='pair')
```

**Comment by gaow** [comment]
Well, I was suggesting not using 

```
input: 'a.txt', 'b.txt', group_by(size=1)
```

at all, but stick to 

```
input: group_by('a.txt', 'b.txt', size=1)
```

where positional arguments are the input. I also agree `by` is better than `size`. And we can possibly simply use `group()` because we have required keyword argument `by` anyways? Also we can think of possibly more keyword arguments to account for `paired_with` and `group_with`

**Comment by gaow** [comment]
or, `sos_group` to be consistent with `sos_target`

**Comment by BoPeng** [comment]
But again, if we allow both

```
input: 'a.txt', 'b.txt'
```
and
```
input: group(by=1)
```
we should expect
```
input: 'a.txt', 'b.txt', group(by=1)
```

**Comment by gaow** [comment]
Not if we do 

```
input: 'a.txt', 'b.txt'
```

and 

```
input: sos_group(by = 1)
...
input: sos_group('a.txt', 'b.txt', by = 1)
```

because users would view it as an enhanced `sos_target` specification.

**Comment by BoPeng** [comment]
[This](https://vatlab.github.io/sos-docs/doc/documentation/SoS_Step.html#Step-Input--13) is what I have till now, let me know if you are ok with the syntax.

Note that I have not tested this on any of the real examples.

**Comment by gaow** [comment]
> The former is a little easier to type but can only be used for groups with proper names. For example, only step_input["1"] can be used to access the group 1 of step_input because step_input.1 is not allows.

I was thinking we should get rid of the dot syntax `input.grp1` altogether, for several reasons:

1. The exceptions / caveats you have listed above
2. pythonist argument that there should be only one obvious way to do it
3. From other OOP languages, accessing what appears to be a class member data directly is not a good thing (use should member functions).
4. Potential convention conflicts, eg what if a input group name is `sources`?

**Comment by BoPeng** [comment]
ok.

**Comment by BoPeng** [comment]
To conclude our named input feature, the SoS equivalence of 
```
# Run the same task on the two splits
t1 = Task1()
t2 = Task1()
t3 = Task2(
        in1 = t1.outspec('out1')
        in2 = t1.outspec('out2')
        in3 = t2.outspec('out1')
        in4 = t2.outspec('out2'))
```
is
```
[t1]
output:  out1='t1_out1', out2='t1_out2'
[t2]
output:  out1='t2_out1', out2='t2_out2'
[t3]
input: 
        in1 = output_from('t1')['out1'],
        in2 = output_from('t1')['out2'],
        in3 = output_from('t2')['out1'],
        in4 = output_from('t2')['out2']

```

**Comment by gaow** [comment]
Do we allow for `output_from` to count backwards, eg `output_from(-N)` `N = 1, 2, 3, ....` ?

**Comment by BoPeng** [comment]
No. I had a look and found that it is difficult to implement it because the step does not know the existence of previous steps. Also, `-1` is not particularly clear in the case of 

```
[step_10]

[step_20]
```

since `output_from(-1)` can be `step_19` or `step_10`.

**Comment by BoPeng** [comment]
I have not been able to attend to #1108, but can you just use the step number or name? If you want `from_output(-1)` be our default input from previous step, it is a smaller task and could possibly be done.

**Comment by gaow** [comment]
> but can you just use the step number or name? 

I certainly can, but it makes it harder to insert steps in between just like your example with `step_10` and `step_20` which might later change to `step_19` and `step_20`. 

> If you want from_output(-1) be our default input from previous step, it is a smaller task and could possibly be done.

I would love to see it happen -- and is perhaps good for most cases with process oriented workflow where the next steps only cares about the previous one. Unless you can suggest a better way out for #1108 (using new or old syntax) which I see is a nice test for our design here.

**Comment by gaow** [comment]
Also, do you think `from_output` is a better name than `output_from` (assuming we can `perl` replace the code and documentation relatively easily)?

**Comment by BoPeng** [comment]
I thought of `output_of` since it is shorter. I think `output_from` is better because it emphasizes on `output`, which is the type of returned stuff, and reads like 'output from step_10`. `from_output` does not read as smooth.

**Comment by gaow** [comment]
Okay I was maybe too much under the influence of `from_steps`... but how do you feel about `sos_output`?  :)

**Comment by gaow** [comment]
Actually i'm cool with `output_from`. I agree it is the best name by itself unless we consider some common "themes" in naming our features. But I dont see it necesssary.

**Comment by BoPeng** [comment]
Not sure about sos_output since it is too general. sos_groups can be problematic because it feels like a sos type but it is actually a function that returns a sos_targets object with extra grouping information.

**Comment by gaow** [comment]
`sos_groups` effectively makes targets so it is not too much of a confusion, and it is not true that all sos types are `sos_xyz` eg `path` , `executable` etc. I think `sos_groups` and `output_from` are good enough.

**Comment by gaow** [comment]
@BoPeng how much does the name `sos_groups` bother you ? Compared to other possiblities such as `groups()`? Maybe `groups` is both easier to type and less confusing conceptually if you are strict about the use of `sos_` prefix.

Also I just want to verify:

```
input: group_by = 1
```
 is now

```
input: sos_groups(by = 1)
```
when the default is from the previous step? We do not have that example in the documentation but I think it is a reasonable default.

Also just a reminder of `output_from(-1)` whose usage is justified in #1108 .

**Comment by gaow** [comment]
Another thing to double check on: do we allow for multiple positional arguments in `sos_groups`:

```
input: sos_groups(output_from(1), output_from(2), by = 'paired2')
```

so that it gives me 

```
out1.A out1.B out2.A out2.B
out1.C out1.D out2.C out2.D
...
```

etc?

**Comment by BoPeng** [comment]
I just had a meeting with Chris Wakefield and he had a very good point in that data flow is not the same as named inputs/outputs. Actually,

```
input: ref=output_from('step_a')['ref']
```
is not that different from
```
input: from_steps('step_a')
```
because we still need to refer to a step, which was something the reviewer disliked, and is not data flow driven workflow.

What data flow actually means can be something we already have

```
[A]
output: 'something'

[B]
input: 'something'
```
That is to say, we only need to specify **data**, and SoS connects steps. SoS has done this for a long time under the feature of `auto-provides`. Basically, for steps with pre-determinable output (not calculated from `_input` etc), it translates

```
[A]
output: 'whatever'
```
to
```
[A: autoprovides='whatever']
output: 'whatever'
```
so that the steps can be used as an auxiliary step in case `whatever` is needed.

Putting the technical details aside, I agree that 
```
[A]
output: 'something'

[B]
input: 'something'
```
feels more like data flow and we should present it in our response.

Now, giving that our `autoprovides` stuff only support pre-determinable output, it is possible for us to do something like

```
[A]
output: something=f'{_input}_derived'

[B]
input:  data('something')
```
so that we can define `something` as a token for the data, and refer to the data, which is arguably a lot more flexible than `output_from(step)['something']`.

**Comment by gaow** [comment]
> is not that different from

I agree. My view is as follows:

```
In our view the only limitation of this mechanism is the lack of named output -- in other words, `from_steps` assumes the default, unnamed output from other tasks, which is implicit and appears task focused rather than data flow oriented.
```

"this mechanism" refers to `from_step`.

> data flow is not the same as named inputs/outputs. 

Sure, but named inputs and outputs emphasize data flow more than using task dependencies. 

I have to run now but will add more thoughts later ... maybe on the go

**Comment by gaow** [comment]
> That is to say, we only need to specify data, and SoS connects steps. 

This is what i meant to say with these:

```
This is true regardless of whether or not named input / output is used, but herein we provide another example using named input and output
```

so yes we have it all along.

> so that we can define something as a token for the data, and refer to the data, which is arguably a lot more flexible than output_from(step)['something'].

I thought about proposing something like that in the beginning, but there will potentially ambiguity that multiple steps has `something`. If we make it an SoS variable  then there is no need to do antying special about it. That's why I think we should just make a good case that data flow regardless of named input and output is what we have. But named input and output does help understanding, sepcifing and using data flow between tasks.

I think we are on the same page. It is just a matter of how to word these and give examples in the right places.

**Comment by BoPeng** [comment]
`sos_variable` is a variable, which is possible type of `BaseTarget` (`output`). I think the key here is to define `data`, probably independent of steps.

```
files = ['a.txt', 'b.txt']

[10]
input: files
```
has a flavor of this, so does
```
files = ['a.txt', 'b.txt']

[10]
output: files
```
but `files` is statically defined and is not quite useful. In contrast

```
[10]
output: files='whatever'

[20]
input: data('files')
```
makes input of `step_20` be the `files` of whatever step. It is more useful and can be a lot easier to use than

```
[20]
input: output_from(10)['files']
```

I understand the ambiguity part because it is easy to do

```
[A]
output: out='a.txt'

[B]
output: out='b.txt'
```
and users have the confusing choices between

```
[C]
input: 'a.txt'
```
and
```
[C]
input: data('out`)
```
but it should be sufficient to yield an error for such cases, the same when we are trying to find `a.txt` through other cases (pattern matching, exact match etc).

The implementation is also easy because we already have the `autoprovide` stuff, and we only need to add something similar to `autoprovide`, with the provided stuff changed from targets to names of targets.

The actual problem is that SoS has gone a little bit too far since it allows many methods to add dependencies to a level that could be really confusing.

**Comment by BoPeng** [comment]
On the other hand, I think named data matching

```
[10]
output: out='something'

[20]
input: data('out')
```
is an natural extension to the ununamed data matching

```
[10]
output: 'something'

[20]
input: 'something'
```

**Comment by gaow** [comment]
> but it should be sufficient to yield an error for such cases

Agreed. 

So the proposed mechanism is completely independent of steps. But I think being explicit about steps also has its values -- because feels like data flow the way you proposed is at the borderline of Process Oriented. I still would like to see it as Process Oriented, but it is a bit implicit now without specifying step it comes from. Still it is explicit in the sense that the identifier `files` has no wildcard, unlike Make style which is completely implicit and the wildcard match can be quite hard to digest. So it looks like a powerful addition to `output_from`, not a replacement.

> The actual problem is that SoS has gone a little bit too far since it allows many methods to add dependencies to a level that could be really confusing.

I tend to think and view this by flow styles and levels of explicitness. I think multi-style flow is one thing that distinguishes SoS from others. Surely we will have to document it well. Unless these mechanism have complicated the code to the extend that we can no longer be confident about correctness of implementation -- that case yes we should be careful about new features like this.

**Comment by BoPeng** [comment]
So any suggestion on the name? I used

```
data('name')
```
but
```
named_output('name')
```
can be more explicit.

**Comment by BoPeng** [comment]
I think in our response we should first list

```
[A]
output: 'somefile'

[B]
input: 'somefile'
```
as something we already have for data flow, but point out is limitation. Then we say we add named output like

```
[A]
output: name='somefile'

[B]
input: named_data('name')
```
to overcome the limitation.

Then we say we also support the style cited in the blog 

```
input: output_from('step')['name']
```
in case there are multiple 'name's from different steps.

**Comment by BoPeng** [comment]
Yes. If we adopt the `set`/`get` stuff, there is no need for `paired_with` and the original parameter would continue to work (if we do not intentionally deprecate it).

**Comment by gaow** [comment]
> if we do not intentionally deprecate it

I'd suggest we do not do it for all of them if possible, including `group_by` ... As far as I know a substantial number of SoS workflows are already out there in production in various places. 

Okay, 

1. as discussed before since `sos_groups` generates `sos_target` the use of `sos_` prefix is justified? Otherwise `input_groups` and we have `input_` and `output_` prefix based function names. 
2. for `data()`,  how about `output_variable()` which seems to fall in line with `output_from`? The issue is when we allow for multiple variables we have a grammar problem ...

**Comment by BoPeng** [comment]
Used `named_output()` for now because it describes the name most appropriately. I know there can be better choices than `named_output` and `output_from` but let us leave this for later.

Now `for_each`.

**Comment by BoPeng** [comment]
OK, with the new `set/get` stuff, it is possible to associate variables with `sos_targets`. So

```
sos_targets('a.txt').for_each('i', range(5))
```
says:
1. create a group if there is no group.
2. repeat the group five times.
3. associate each group with a variable `i`, with values 0, 1, 2, 3, 4

Then we have `_input` as each group, and then `_input.get('i')` as the variable associated with `sos_targets`.

Of course `_input.get('i')` is a lot more difficult to use than `i` generated from `for_each={'i': range(5)}`....

**Comment by BoPeng** [comment]
Now, using the `group_by` convention, the syntax could be something like

```
for_each(sos_targets('a.txt'), i=range(5), j=samples)
```
which is only slightly better.

**Comment by BoPeng** [comment]
>  still have the parameter accessible via eg _input.get('var'), and _var is a shorthand of it inside the current step ...

Why do you need `_input.get('var')`?

**Comment by gaow** [comment]
> Why do you need _input.get('var')?

I think I did not think it through ... I actually want something like `_output.get('chunk')`. Here is an example of what I"m currently editing:

```
[1]
chunks = <a list of strings>
input: sos_groups(by = 1), for_each = 'chunks', concurrent = True
...

[2]
input: sos_groups(by = 1), concurrent = True
output: summary_stats = f"{_input:n}.summary_stats.txt", ld_matrix = f"{_input:n}.LD.txt"
python: ...
   chunk = {_input.get('_chunks')}
```

Basically in step `[1]` I got an attribute `for_each` that generated my different output groups. I want that information to be carried on. Maybe I'm missing something obvious (that I can in fact pass it on different way but easier way)?

**Comment by BoPeng** [comment]
I see. this makes sense. So we need to expand `for_each=...` to assign the variables to groups.

**Comment by BoPeng** [comment]
The concept that `BaseTarget` and `sos_targets` can carry dictionaries is very powerful, but I am limiting the dictionary to basic types (`bool`, `int`, `float`, `str`, and `list` and `tuple`, `dict` of these types) because other types will make the targets not portable (e.g. need `pickle` across processes and needs the destination environment to understand them).

**Comment by gaow** [comment]
>  but I am limiting the dictionary to basic types

Yes I do not see at least from my current experience that I need something to violate this design in order to get things work the way I want -- hopefully my experience speaks for a reasonable size of potential user groups.

**Comment by BoPeng** [comment]
You actually want the `for_each` variables in not only `_input`, but also `_output`, which is unfortunately not possible because `step_output` is an accumulation of ` _output` so even if I set variables to `_output`, they will not be kept intact in `step_output`.

It is possible to keep the groups information (and associated dictionaries) in `step_output` that that can cause some other issues since `output_from(step)` right now is "plain" `sos_targets` without groups.
