### ISSUE TITLE
rules for source of sos_targets

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1109]
We now have the following rules for sources of targets:

```
## step_input = sos_targets('filename', source = "step_name")
input: 'filename' 
```
keyword argument overrides default source step_name
```
## step_input = sos_targets('filename', sources = "a")
input: a = 'filename'
```
so that we can use `_input.a` to refer to `filename`.

Things get a bit complicated when `filename` is a `sos_targets` with its own sources. For example,

```
[step_1]
## step_output = sos_targets(file1, sources="step1")
output: 'file1'

[step_2]
## step_output = sos_targets(['file2', 'file3'], sources=["out", "out2"])
output: out='file2', out2='file3'   
```

now,
```
input: output_from('step_1')      ==>    step_input = sos_targets(file1, sources ="??")
input: output_from('step_2')      ==>    step_input = sos_targets(file2, file3, sources ="??")
input: output_from('step_2').out  ==>    step_input = sos_targets(file2, sources ="??")

input: a=output_from('step_1')     ==>   step_input = sos_targets(file1, sources ="??")
input: a=output_from('step_2')     ==>   step_input = sos_targets(file2, file3, sources ="??")
input: a=output_from('step_2').out ==>   step_input = sos_targets(file2, sources ="??")
```

1. we get the source from `step_1`, so `sources="step_1"`.
2. `sources="step_2"` or `out`. If we choose `out`, then `_input.out` and `_input.out2` can be used. However, the `_input.out` will have two targets in the case of `input: out="something", output_from("step_2")`.
3. `sources="step_2"` or `out`: the same answer as `2`?
4. `sources=a` or `step_1`: `a` makes sense. `step_1` is overridden.
5. `sources=a` or `step_1` or `out`: `a` makes sense but will wipe out original `sources`.
6. `sources=s1 or `step_1` or `out`: the same answer as `5`?

The choices will affect how `_input` will be used in the following cases
```
input: output_from('step_1'), output_from('step_2').out, output_from('step_3').out2
input: a=output_from('step_1'), b=output_from('step_2').out, c=output_from('step_3').out2
```

**Comment by BoPeng** [comment]
Things can be even more complicated with `group_by`

```
input: sos_groups(output_from('step_2'), by=1)  
```
we would have
```
_input.out
```
for the first group, and
```
_input.out2
```
for the second?

```
input: a=sos_groups(output_from('step_2'), by=1)  
```
is easier since we have
```
_input.a
```
for both.

So for this reason, perhaps it is easier to 

```
input: output_from('step_2')      ==>    step_input = sos_targets(file2, file3, sources ="step_2")
```

**Comment by gaow** [comment]
Thank you! Yes I agree, and I guess a nice starting point would be a paragraph to make it clear that named input/output is task independent. And that we only fall back to referring step names as sources when their names are not specified, which, in practice is what we envisage the most natural convention for simple Process Oriented workflow implementation anyways. But for more sophisticated Process Oriented workflows we can always change the behavior as needed.

**Comment by BoPeng** [comment]
I am not quite happy with 
```

[group]
input: sos_groups(output_from('step_10'), by=1),
       sos_groups(output_from('step_20'), by=2),
       my=('e1', 'e2')
```
because `_input.my` would be invalid in this case. I think it makes sense to add `sos_targets` directly to each group so that `_input.my` can be used.

**Comment by BoPeng** [comment]
OK, this is fixed and documented. But there is another question on whether or not we should allow more advanced group merge methods. Right now, we

1. merge groups of the same size (easy)
2. repeat groups of size 1 with groups of size N by repeating the singleton group.

Should we extend this by repeating smaller groups? My feeling is that we should leave this for later when we have a good use case for it.

**Comment by gaow** [comment]
> My feeling is that we should leave this for later when we have a good use case for it.

I agree. But what is the behavior for cases outside 1 and 2 above? Do we quit on error (which I think is appropriate behavior)?

**Comment by BoPeng** [comment]
Yes, [an error will be raised](https://github.com/vatlab/SoS/blob/named_input/src/sos/targets.py#L890)
