### ISSUE TITLE
Deprecate `paired_with` and `group_with`

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1110]
With implementation of `sos_groups`, I wonder if we want to make `paired_with` and `group_with` be `sos_groups()` parameter instead?

**Comment by BoPeng** [comment]
Without `sos_groups`, `paired_with` still works,
```
[10]
output: '1.txt'
_output.touch()

[20]
var = ['1', '2']
input: '2.txt', output_from(10), paired_with='var'

print(_input)
print(_var)
```
with output
```
2.txt 1.txt
['1', '2']
```

With `sos_groups`,
```
[10]
output: '1.txt'
_output.touch()

[20]
var = ['1', '2']
input: sos_groups('2.txt', out=output_from(10), by=1), paired_with='var'

print(_input)
print(_var)

```
still works with output
```
2.txt
['1']
1.txt
['2']
``` 
because `paired_with` is matched to all input files, including those from `output_from(10)`. 

Now, 

1. The simpler case without `sos_groups`, should we allow for `paired_with`? It is not a significant use case since there is no need to pair input with variables without substeps.

2. In the case with a single `sos_groups`, 

```
input: sos_groups('2.txt', out=output_from(10), by=1), paired_with='var'
```
can be written as

```
input: sos_groups('2.txt', out=output_from(10), by=1, paired_with='var')
```

3. In the more complex case with multiple `sos_groups`,

```
input: sos_groups(filelist1, paired_with='var'), sos_groups(filelist2, pariwd_with='var2')
```
makes more sense because `paired_with` would pair with the filelist before grouping.

**Comment by gaow** [comment]
> The simpler case without sos_groups, should we allow for paired_with? It is not a significant use case since there is no need to pair input with variables without substeps.

Am with you -- I do not see a need to use paired_with outside the context of `group_by` so I'm cool to disallow it and I'm sure it will not break any reasonably written existing SoS code.

> In the case with a single sos_groups, ... can be written as

Yes

> In the more complex case with multiple sos_groups, ... makes more sense because paired_with would pair with the filelist before grouping.

and yes!

**Comment by BoPeng** [comment]
But as I said I do not like the magic of _var for paired_with=‘var’. I would rather have something like

sample=paired_with(samples)

**Comment by gaow** [comment]
Okay, that brings back to our discussion with `for_each`. I left that out in this discussion because it is more clear that `for_each` stays outside `sos_groups`. Now all these 3 options are relevant to the "magic" of `_var`, which truthfully I had some doubts back in 2016 but I'm now very happy about the syntax.

**Comment by gaow** [comment]
I guess I dont see the current convention too confusing to accept, and my primary argument is that our implementation should make complicated situation simpler but not the other way around. If for simple, commonly used cases the syntax becomes too complicated then it is not good.

**Comment by BoPeng** [comment]
We chose `for_each='var'` because at that time the `input` statement only allows for unnamed input and the syntax was the easiest to bring in the feature. Now that `input` statement can be quite long and complex, uniformity and explicitness (clarity) seems to be more important.

Or we can just say we have another chance to make a design decision.

**Comment by gaow** [comment]
I find that conceptually, `paired_with` and `group_with` should happen inside `sos_group`; `for_each` should happen outside it. Do you agree with the assessment? If we are on the same page on this point, we can then think about re-design. I'm not anti other ideas. I just think it is important to not make simple case more complicated (thus losing the majority group of non-power users) .

**Comment by BoPeng** [comment]
I agree. But we should get the revision out first.

**Comment by BoPeng** [comment]
Merging `paired_with` with `sos_targets` is doable but difficult because of there are many operations for `sos_targets`. For example, if we have a `sos_targets` with paired vars, the operation can be complicated when this `sos_targets` is extended or merged with another `sos_targets` without the var.

It might be easier to add vars to `BaseTarget` to allow something like

```
a = file_target('a.txt')
a.sample_name = 'sample'
```
In this way at least we do not have to worry about adding `sample_name` to a `sos_step` instance when the input has different types of targets.

**Comment by BoPeng** [comment]
Basically we can define

```
BaseTarget.set(name, val)
BaseTarget.get(name, default)
sos_targets.set_each(name, list_of_vals) . # [target.set(name, val) for target, val in zip(targets, list_of_vals)]
```
so that we can add arbitrary attributes or properties to `BaseTarget`.

One advantage of this approach is that the attributes can be carried along across steps (say, with `ouput:`) because they are part of each `BaseTarget`.

**Comment by gaow** [comment]
> One advantage of this approach is that the attributes can be carried along across steps (say, with ouput:) because they are part of each BaseTarget.

This is very convincing ... but interface-wise:

```
sos_groups(a = '2.txt', b = output_from(-1), by=1, c =paired_with(samples))
```

this is confusing right? To my understanding unnamed keyword argument are reserved for renaming input and output. 

Alternatively the interface you had issues with, 

```
sos_groups(a = '2.txt', b = output_from(-1), by=1, paired_with = 'c')
```

can still carry `c` on as an attribute right?

**Comment by BoPeng** [comment]
The return value of `set_each` will be `self`, but not so for `for_each`, Right now `for_each` introduces another variable outside of `sos_step`, such as

```
input: for_each={'i': range(5)}
```

**Comment by gaow** [comment]
I see. So you are saying we should not let input and output carry `for_each` properties? What is the difference between those `for_each` properties and `paired_with` properties -- I view they are by nature the same so it feels a bit strange why one gets kept as an attribute but not another.

**Comment by BoPeng** [comment]
`paired_with` basically tags targets with variables and the number of variables and group does not change. `for_each` will create additional groups (which is ok) but also add for each group some variables, which complicates the `sos_targets` design.

I have not really though of `for_each` yet, let me deal with `set`/`get` first.

**Comment by gaow** [comment]
Great, looks like you have pushed? I'm drafting a new pipeline now; I can really make use of these new features. But I'll be drafting the entire thing before actually running it so I'm using the new syntax in my draft and will pull the branch and test it out in a couple of hours.

**Comment by BoPeng** [comment]
Set_each accepts a name and then a sequence. It works for very simple cases here but will likely fail in more complex cases. Let me work on data() and think more on for_each before finalizing the features with tests.

**Comment by gaow** [comment]
Hmm I do come across the case I find it would be nice to have `for_each` be an attribute! Now that I think of it I believe this is a commonly used feature. For the time being I embed this information in the output file name and parse from the file name in the next step to extract the info. This is what i typically do. Would be nice to have it otherwise taking advantage of our new design.

**Comment by BoPeng** [comment]
Now, since we now have both

```
samples = ['A', 'B']
input: 'a.txt', 'b.txt', paired_with='samples'
print(_input)
print(_samples)
```
and 
```
samples = ['A', 'B']
input: sos_targets('a.txt', 'b.txt').paired_with('sample', samples)
print(_input[0].get('sample'])
```

Do we want to 
1. Keep the usages separated, or
2. Extend `paired_with` so that in the first case `_input[0].get('_sample')` can be used
3. Some other idea to make them similar in usage?

**Comment by gaow** [comment]
I think it is fair enough to keep the usage separate (and make as deprecate in the documentation). Any reason to make them similar in usage at this point?

**Comment by BoPeng** [comment]
I do not think we should deprecate `paired_with` etc.

When we officially introduce `groups` to `sos_targets`, we does not expose `sos_targets._group()` but allowed `sos_targets(group_by)` and kept backward compatibility.

When we introduce `set/get` stuff, we do not have to introduce `sos_targets.paired_with`. We can introduce `paired_with` as a parameter to `sos_targets` (not done now), and we do not have to introduce anything new. `group_with` and `for_each` can be handled similarly.

The only problem is that we previous allow direct access to the `paired_with`, `for_each` variables, and it is difficult to implement `paired_with` etc purely as a parameter of `sos_target`....

The benefit is that we are not introducing anything new on the surface, and just allowed more flexible use of old parameters, e.g. allow `group_by` in `output_from` and allow the merge of multiple `sos_targets` with `group_by`.

**Comment by BoPeng** [comment]
So I have to make a decision whether or not to introduce `paired_with`, `group_with`, `for_each` to all `sos_targets` objects.

```
input: output_from(1, paired_with=...), output_from(2, for_each=...)
```
I previously though that `for_each` should be applied to `_input`, but this does not seem to be the case because if we can simply merge group dictionaries.

Then we can have `_input.get('a')` as the official way to access such vars but allow the access of `a` for backward compatibility and for convenience.

**Comment by BoPeng** [comment]
The "problem" I am trying to solve is "local" paired_with and alike. That is to say, when `output_from` etc carry their own dictionary, have their own groups, when we put them together, global `paired_with` etc no longer works. The solution has been implemented `output_from( ).paired_with()`, but perhaps `output_from( paired_with)` is more natural as it needs one less thing for users to remember.

Switching all to `sos_target.paired_with` is possible but we will need to deprecate `paired_with=`, and 

```
input: sos_targets('a.txt', 'b.txt').paired_with('name', value)
```
is a lot more troublesome to use than
```
input: 'a.txt', 'b.txt', paired_with=dict(name=value)
```

**Comment by gaow** [comment]
I was proposing keeping `for_each` and deprecate `paired_with` and `group_with` (keep backwards compatibility without documenting them) precisely because I find it confusing sometimes to digest when I think them as "globally applied" to all input groups the way `for_each` does. I have no trouble thinking `for_each` as global because it is very clear what it does. In practice I avoid using `paired_with` and `group_with` by working directly with `_index` to avoid confusion. Now that they become local the behavior is a lot better and I would be happy to get rid of the previous potentially confusing interface.

> we previous allow direct access to the paired_with, for_each variables

This is indeed a nice feature we might want to keep ... particularly to be compatible with `for_each`. I was a big fan of the convenient `_i` syntax as you can tell. 

> but perhaps output_from( paired_with) is more natural as it needs one less thing for users to remember.

I agree!

So can we move `for_each`, `paired_with` and `group_with` into inside of `sos_target`, `output_from` and `named_output`, and consider this:

```
input: 'a.txt', 'b.txt', paired_with=dict(name=value)
```
as a shorthand of the special case

```
input: sos_targets('a.txt', 'b.txt', paired_with = dict(name=value))
```

and when `paired_with = 'name'` we can still keep the `_name` convention?  In fact I used the word "shorthand" in my edits to issue 1115.

> Then we can have _input.get('a') as the official way to access such vars but allow the access of a for backward compatibility and for convenience.

that'd be very nice!
