### ISSUE TITLE
New style group_with

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1113]
`group_with` associate variables with each group, which is essentially a `sos_targets`, so `set()` and `get()` should work.

The problem is that we have the magic of treating an `sos_target` with single element as the element itself, so it is not clear what `_input.get('name')` is, because it can be the `name` of the `sos_target`, or the `name` of the first child `file_target`.

**Comment by BoPeng** [comment]
One the other hand, as long as

```
_input.get()
```
can be used, it does not matter if the `_input` is set at the `sos_targets` level or at the lower level. We can just try both....

**Comment by gaow** [comment]
After reading your latest thread on #1114 I finally understand this.
