### ISSUE TITLE
Remove limitation to allow for only basic properties in `set`

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1117]
I tried this:

```
chunks = [['chr9', 1, 15000], ['chr9', 15001, 25000]]
input: sos_groups(by=1), for_each = 'chunks'
output: sos_targets(f"{_input} ... <an _input based name>").set('chunks', chunks)
```

I get:

```
 Failed to process step output ..: Target properties can only be sequence of basic types: [['chr9', 1, 15000], ['chr9', 15001, 25000]] provided.
```

So I guess for `set` it is not bad idea to remove this limitation? Actually this is the only usage for `set` that I can be convinced useful.

**Comment by BoPeng** [comment]
What I need is an easy way to test data types that do not need pickle to transfer...

**Comment by gaow** [comment]
> What I need is an easy way to test data types that do not need pickle to transfer...

Do we not have that, because we keep `global` around and we do not check it there?

**Comment by gaow** [comment]
I know it is a hectic morning, but it would be nice if recursive basic types can be added to the supported basic types for now ... I am a bit stuck without being able to do it in my pipeline.  Basically for dict, list and tuple we want to call the check function recursively for each element of it, right?

**Comment by BoPeng** [comment]
Not tested. Make it work if it fails. The code is clear enough.

**Comment by gaow** [comment]
It worked, thanks a lot!! Maybe i'll close it for now and we 'll see if recursive basic types will cover our basis.
