### ISSUE TITLE
Should sos_targets["name"] slice groups as well?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1121]
Running

```
sos run test B
```

on workflow
```
[A]
input: for_each=dict(i=range(5))
output: a=f'a_{i}.txt', b=f'b_{i}.txt'
_output.touch()

[B]
input: named_output('a')
print(_input)
```
would yield

```
a_0.txt
a_1.txt
a_2.txt
a_3.txt
a_4.txt
```
because `named_output` slices not only the targets, but also groups of `output_from('A')` so that `named_output('A')` would also have groups.

The same output would be generated for
```
[A]
input: for_each=dict(i=range(5))
output: a=f'a_{i}.txt', b=f'b_{i}.txt'
_output.touch()

[B]
input: output_from('A')
print(_input['a'])
```

because `output_from('A')` has groups.

However, output from the following workflow using `output_from('A')['a']`

```
[A]
input: for_each=dict(i=range(5))
output: a=f'a_{i}.txt', b=f'b_{i}.txt'
_output.touch()

[B]
input: output_from('A')['a']
print(_input)
```
is
```
a_0.txt a_1.txt a_2.txt a_3.txt a_4.txt
```
because `['a`]` slices the targets and produce a `sos_target` without groups.

Should the slice operation always slices `groups`?

**Comment by gaow** [comment]
I think so! because `output_from('A')` will output groups by default, it is rather weird if the slices do not.

**Comment by BoPeng** [comment]
ok, now the last example shows the same result.

Note that if we would like to regroup, we will have to regroup from `output_from`, as in

```
[A]
input: for_each=dict(i=range(5))
output: a=f'a_{i}.txt', b=f'b_{i}.txt'
_output.touch()

[B]
input: output_from('A', group_by='all')['a']
print(_input)
```
