### ISSUE TITLE
Use attributes for set/get

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1123]
We decided to use `["source"]` for accessing subset of `sos_targets`. For `set()` and `get()` stuff, i think it makes sense to use `setattr` and `getattr` so that we can do

```
_input.sample_name
```
instead of
```
_input.get("sample_name")
```
because the extra `get(" ")` will greatly reduce the usability of this feature.

**Comment by BoPeng** [comment]
Another reason for this proposal is that whereas we could have `sources` of `1` etc (if the output comes from step `1`), `paired_with` etc will all have proper names so there is no confusing.

**Comment by gaow** [comment]
If we restrict the usage only to attributes it would be better. For named input and output this is still not allowed and we have to use `_input['name']` right? Then what are the other restrictions here -- some reserved attribute that will cause a confusion? eg `.sources`? I would like to see all possibility of name clash be ruled out before welcoming this feature.

**Comment by BoPeng** [comment]
So
```
a["name"]
a[1]
a[:2]
```
etc are slices that retrieve part of the `a`. There is no confusing here.

```
a.name
```
would be 
```
getattr(a, 'name')
```
which will try to get the object's own attribute `name` before returning our attribute (unless we override `__getattribute__` to allow users to override native attributes but that is rarely a good idea).

So the limitation is that 

```
a.touch
```
will not work because it will return a function `Path.touch`. We could prevent this from happening by disallowing `a.touch = x`.

**Comment by gaow** [comment]
> a.touch

it is the wrong syntax anyways right? because it should be `a.touch()`. So there is no problem here? Any other exceptions? What do we do about `sources` -- make it `sources()`?

> which will try to get the object's own attribute name before returning our attribute

I do not like this ... even though it makes sense.

**Comment by BoPeng** [comment]
Yes, that can happen when user does not know the existence of `Path.touch` and would like to save an attribute like that, but we can easily prevent this by testing `hasattr('touch')` before we assign.

**Comment by gaow** [comment]
Still, `Path.touch()` has `()` as a class method call, not class attribute right? I am saying we can use this convention for `sources()` or whatever, few, potential conflicts.

There are some other properties (not methods) on this page, but are for `PurePath`, so they should not create a conflict?

https://docs.python.org/3/library/pathlib.html

**Comment by BoPeng** [comment]
Yes, all such methods should be avoided because `getattr(a, 'touch')` is the first step for `a.touch`, regardless if it is a function or not.

**Comment by gaow** [comment]
Yes I understand that. But from the user's prospective (let's not discuss implementation difficulties on our end), when they do `a.touch` for `Path` it is most likely a user error (unless they want to do stuff like `my_touch = a.touch`) and the correct usage is always `a.touch()`. So from our prospective it is fair enough to say that `a.whatever` is referring to `.whatever` attributes for `sos_targets`. That makes it conceptually clear I think. Then I guess by `avoided` you are saying to override the behavior such that `a.touch` will trigger errors if `touch` is not a sos target attribute, even if `touch` is a ` Path` method? Same holds for named input, eg we will code it such that `_input.named_input` complains.

**Comment by BoPeng** [comment]
By avoid I meant not allowing any attribute like touch.

**Comment by BoPeng** [comment]
Or we could allow all names but for touch users can only use get(‘touch’) because a.touch will get the touch function.

**Comment by gaow** [comment]
Okay that sounds reasonable, if we compile such a keyword list and make appropriate suggestions to alternative use of `get`. I gather this might be easier than other approches. Can we still prevent accessing named input and output this way?

**Comment by BoPeng** [comment]
Yes. `input.name` will only get attributes, not subsets.

**Comment by BoPeng** [comment]
This what I did

1. Keep `.set()` since overriding `__setattr__` can be tricky, and we do not encourage explicit use of `.set` (`paired_with` etc should be easier to use).
2. Raise an error if `.set('touch')` etc is called.
3. Keep `.get(name, default=None)`, as a safe way to get `name` if `name` does not exist. 
4. Allow `a.name` but it will raise an `AttributeError` if `name` does not exist.

So in the end, users should use
1. `paired_with` and `group_with`, `for_each` to set attributes
2. Use `a.name` to get attributes
3. Use `.set()`, `.get()` for more advanced usages.

**Comment by BoPeng** [comment]
`Path` has a number of attributes (not functions) such as `name`, `suffix`, `drive`, `parent` so we are excluding a large number of common words. However, these attributes have clear meanings and it is not a good idea to use them outside of their original meaning...
