### ISSUE TITLE
Should `concurrent` status be passed on along with group_by? 

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1125]
Currently with the new behavior of `group_by` what I used to specify for a workflow,

```
[1]
input: group_by = 1, concurrent = True
...
[2]
input: group_by = 1, concurrent = True
```

now becomes 

```
[1]
input: group_by =1 , concurrent=True
...
[2]
input: concurrent=True
```

I wonder where information for `concurrent` is saved, and if it makes sense to make it group property that can also be passed on unless otherwise specified?

**Comment by BoPeng** [comment]
The only case when `concurrent` should be `False` is when the next substep depends upon the result of previous ones, and frankly I have not seen a single use case for this in the past few years. With the better control of number of processes now,  I suppose we can make `concurrent=True` the default.

**Comment by gaow** [comment]
@BoPeng just to double check this: now `concurrent=True` is default for non-task. It is also `True` for task, and has been like that for some time already, right?

**Comment by BoPeng** [comment]
Yes. I do not think there is such an option for `task` (and I will remove it if there is as I am going through the manual).
