### ISSUE TITLE
Switch between `task` and non-task modes

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1127]
I think I've raised this before but we did not discuss it in detail. I often switch between prototyping on a desktop computer and running many jobs on a compute cluster. Each time I have to comment and uncomment `task:` statements. Is there an easier way to make it happen? I'm thinking of leveraging the `-q` option, by maybe specifying some specific values to force running workflows as if `task:` does not exist?

**Comment by gaow** [comment]
Yes, that'd be great. But what if one accidentally typed in `None`? Hopefully that is not the `-q` default.

**Comment by BoPeng** [comment]
What about tasks with its own `queue` value? The global `-q` option is not supposed to override them.

**Comment by gaow** [comment]
Do we allow for `config.yml` to set step specific queues? That will remove the limitation because one can always override from there -- by providing different config files with queues configured for different computing environment, including not using task at all (`None`)

**Comment by BoPeng** [comment]
No, but nothing prevents from using

```
parameter: queue=''
task: queue=queue
```
or
```
task: queue=CONFIG['queue']
```

**Comment by BoPeng** [comment]
I have allowed

```
sos run -q None
```
and
```
sos run -q none
```
to disable `task` statement without its own `queue` option.

In addition,
```
task: queue=None, "None", or "none"
```
will invalidate the task statement. This allow users to use command line argument to customize step level queue selection.
