### ISSUE TITLE
Remote execution template interpolation `walltime`

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1129]
This is very much likely a user error, but some templates that worked for me a while ago on a cluster now does not work. The error messages I got was:

```
INFO: fbccb119c2eca59e restart from status pending
ERROR: Failed to generate job file for task fbccb119c2eca59e: Failed to interpolate #!/bin/bash
#{partition}
#{account}
#SBATCH --time={walltime}
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task={cores}
#SBATCH --mem-per-cpu={mem//10**9}G
#SBATCH --job-name={job_name}
#SBATCH --output={job_name}.out
#SBATCH --error={job_name}.err
cd {cur_dir}
module load R
sos execute {task} -v {verbosity} -s {sig_mode}
: name 'walltime' is not defined
ERROR: [default]: Workflow exited due to failed step default_2.
```

It says ": name 'walltime' is not defined". But I'm sure it is how I should use it. What am I missing here? 

The configuration file:

https://github.com/gaow/fine-mapping/blob/master/workflow/midway2.yml

The workflow:

https://github.com/gaow/fine-mapping/blob/master/workflow/summary_statistics_wrangler.ipynb

(search for word `task:`)

My command:

```
sos run .... -c workflow/midway2.yml -q midway2 -J 40 
```

**Comment by BoPeng** [comment]
Release or latest trunk?

**Comment by gaow** [comment]
The latest `trunk` version 0.17.8. I do not think we've release 0.18.0 on pypi yet.

**Comment by gaow** [comment]
Also it looks like the naming convention of task `fbccb119c2eca59e: ` is not right. In my `default_2` step, I do have `trunk_size = 80` so I expect the task name be something like `M80_...`?

**Comment by BoPeng** [comment]
I think I know what is going on. I moved the processing of `task` before `input` to handle `queue=None`, but your task options contains `_output`. 

Working on a fix now.

**Comment by BoPeng** [comment]
Not tested, please check if the patch works.

**Comment by BoPeng** [comment]
Fixed the patch.

**Comment by BoPeng** [comment]
For task name, maybe the output was reporting something for the individual task. I will need more output from you to determine that.

**Comment by gaow** [comment]
Hmm there is some progress:

```
INFO: Running get summary stats: 
WARNING: Invalid tag "default_2_ENSG00000181404.15.summary_stats ENSG00000181404.15.LD" is added as "default_2_ENSG00000181404.15.summary_statsENSG00000181404.15.LD"
INFO: M1_fbccb119c2eca59e submitted to midway2 with job id 55849130
ERROR: [default]: Workflow exited due to failed step default_2.
```

but there still is a failure.  I now see `M1` because my test run only has 1 job. When I increase it to more jobs there is another issue with recent changes in groups / attributes. I'll come up with a MWE to make sure, use another ticket to report it, then revisit this one. I'll do it now and get back very soon but really no pressure to get back tonight.

**Comment by gaow** [comment]
Also that warning message above:

```
WARNING: Invalid tag "default_2_ENSG00000181404.15.summary_stats ENSG00000181404.15.LD" is added as "default_2_ENSG00000181404.15.summary_statsENSG00000181404.15.LD"
```

My tag is `tags = f'{step_name}_{_output:bn}'` and because I used `group_by = 1` in my `default_2` workflow, I should be able to use `_output` here to refer to sub-steps?  So even though I may be able to fix the warning via using `_output[0]` it is conceptually not clear.

Again, no rush on getting it back to me tonight.

**Comment by BoPeng** [comment]
Your output has two files, so you need to use `{_output[0]}` or `{_output["summary_stats"]}` in `tags`, right?

```
output: summary_stats = f"{_input:n}/{_input:bn}.summary_stats.txt", ld_matrix = f"{_input:n}/{_input:bn}.LD.txt"
task: trunk_workers = 1, trunk_size = 80, walltime = '10m', mem = '5G', cores = 1, tags = f'{step_name}_{_output:bn}'
````

**Comment by gaow** [comment]
Ahh sure sorry that is my bad. But still, the confusion related to setting attribute `_chunks` remains. We can use #1130 to discuss it.
