### ISSUE TITLE
Input properties does not work in output interpolation

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1130]
Here is a MWE:

```
chunks = [(1,100,200),(2,300,400)]

[1]
input: '1.txt', group_by = 1, for_each = 'chunks'
output: f"{_chunks[-1] if len(_chunks) > 3 else '%s_%s_%s' % (_chunks[0], _chunks[1], _chunks[2])}.pkl", group_with = 'chunks'
_output.touch()
```

It does not work with/without "`1.txt`, group_by =1" specificaitons. The error message:

```
ERROR: Failed to process step output (f"{_chunks[-1] if len(_chunks) > 3 else '%s_%s_%s' % (_chunks[0], _chunks[1], _chunks[2])}.pkl", group_with = 'chunks'): Length of provided properties (2) does not match number of groups (1)
ERROR: [1]: Failed to process step output (f"{_chunks[-1] if len(_chunks) > 3 else '%s_%s_%s' % (_chunks[0], _chunks[1], _chunks[2])}.pkl", group_with = 'chunks'): Length of provided properties (2) does not match number of groups (1)
```

other syntax might work but I think we agreed `_chunks` is shorthand for using the dictionary specification?

**Comment by BoPeng** [comment]
Here is the thing:

when you write, 

```
ouput: f'whatever'
```
you are specifying `_output`, not `step_output`, so you need to pair it with a single element. In your case you have a list of tuples so you will have to use something like

```
group_with = dict(_chunks=[_chunks])
```
because `dict(_chunks=_chunks` will get a tuple of size 3, which does not match the size of output statement.

**Comment by BoPeng** [comment]
If you do
```
output: the_whole_thing, group_by=1,  group_with='chunks'
```
will be allowed because when you generate a `step_output` with groups, the `_index` group will be taken.

**Comment by BoPeng** [comment]
Whether or not we should make this kind of thing easier is another issue.

**Comment by gaow** [comment]
Hmm, this is related to my latest comment on #1129 the `tag` business ...

**Comment by gaow** [comment]
Nope, I changed it to : 

```
input: for_each = 'chunks'
output: f"{ss_data:n}/{_chunks[-1] if len(_chunks) > 3 else '%s_%s_%s' % (_chunks[0], _chunks[1], _chunks[2])}.pkl", group_by = 1, group_with = 'chunks'
```

still got:

```
ERROR: Failed to process step output (f"{ss_data:n}/{_chunks[-1] if len(_chunks) > 3 else '%s_%s_%s' % (_chunks[0], _chunks[1], _chunks[2])}.pkl", group_by = 1, group_with = 'chunks'): Length of provided properties (5) does not match number of groups (1)
ERROR: [default_1]: Failed to process step output (f"{ss_data:n}/{_chunks[-1] if len(_chunks) > 3 else '%s_%s_%s' % (_chunks[0], _chunks[1], _chunks[2])}.pkl", group_by = 1, group_with = 'chunks'): Length of provided properties (5) does not match number of groups (1)
[default]: 2 pending steps: default_2, default_3
```

In the past when I have `group_by = 1, for_each = 'var'` then in `output: f'{_input:n}_{_var}'` I always get grouped output by default. That is why it is a bit puzzling now.

**Comment by BoPeng** [comment]
You only define one element in output. Group by does not help.  You need to specify all.

**Comment by gaow** [comment]
Sorry not sure if I understand this. I changed it to:

```
[1]
input: for_each = 'chunks'
output: f"{_chunks[-1] if len(_chunks) > 3 else '%s_%s_%s' % (_chunks[0], _chunks[1], _chunks[2])}.pkl"
_output.touch()
```

not worrying about `group_with` for now. It works:

```
INFO: Running 1: 
INFO: output:   1_100_200.pkl 2_300_400.pkl in 2 groups
INFO: Workflow default (ID=06e763ca33005985) is executed successfully with 1 completed step and 2 completed substeps.
```

and said it is in 2 groups. But when I add in `group_with` to output:

```
ERROR: [1]: Failed to process step output (f"{_chunks[-1] if len(_chunks) > 3 else '%s_%s_%s' % (_chunks[0], _chunks[1], _chunks[2])}.pkl", group_with = 'chunks'): Length of provided properties (2) does not match number of groups (1)
```

the number of groups is now 1 ...?

**Comment by gaow** [comment]
@BoPeng Sorry this issue still remains in confusion and I cannot get my pipeline in production to work. From my thread above I believe conceptually I was not wrong and there are some inconsistency in SoS dealing with groups.

**Comment by BoPeng** [comment]
The `output` does not know how many groups there are. It needs to produce either a `sos_targets` without group or a `sos_targets` object with the same number of groups as input and then the `_index` group will be taken as `_output`.

In your case,

```
f"{_chunks[-1] if ...", group_with = 'chunks'
```
`_chunks` is one of the `chunks` and f" ...." is a single file name. It cannot be grouped with `chunks` because  there is no group for `output` (not `input`).

If you would like to use `group_with` with the original `chunks`, you will have to 

1. generate multiple output files
2. use `group_by` to generate the same number of groups as input

**Comment by gaow** [comment]
> The output does not know how many groups there are

Okay, but the output message from my above thread without `group_with` indeed said:

```
INFO: output:   1_100_200.pkl 2_300_400.pkl in 2 groups
```

this made me think it knows how many groups. How did it happen? 

> If you would like to use group_with with the original chunks, you will have to

How exactly can I do it? Here is a even smaller example:

```
chunks  = [1,2]
[1]
input: for_each = 'chunks'
output: f'{_chunks}.txt', group_by = 1, group_with = 'chunks'
_output.touch()
```

Still does not work.

> generate multiple output files

this,

```
chunks  = [1,2]
[1]
input: for_each = 'chunks'
output: [f'{_chunks}.txt' for _chunks in chunks], group_by = 1, group_with = 'chunks'
_output.touch()
```

indeed works but is a bit counter intuitive considering the behavior without `group_with` ...

**Comment by BoPeng** [comment]
The last example is what I meant. It is the same as `input`. That is to say,

1. In `input:`, you build `step_input`, `group_by` and get `_input`. `group_with` is applied to `step_input`.
2. In `output:`, we usually have `_output`, so `group_with` can only be a single element. `_output` accumulates to `step_output`.
3. Alternatively, in `output`, you can define `step_output`, apply `group_by`, then `group_with`, then you get ` _group` as the `_index` of `_step_output`. It is sort of wasteful because you build `step_output` and get `_output` each time using this method.

**Comment by BoPeng** [comment]
One way to get around of this problem is to let `output:` knows the number of groups in `_output`, and

```
output: 'something', group_by='trunk'
```
will define `_output` and group_with the `_index`-th element of `trunk`. This behavior should be well defined with the presence of `group_by` and not in `output`. Also there is `paired_with`, which is currently `paired_with` `_output` but you are seeing `group_with` pairing with `step_output` and then `paired_with` pairing with `_output`.

**Comment by gaow** [comment]
Indeed. I think the major confusion is that under the hood '_output accumulates to step_output.' but to the users, it is confusing to see 

```
output: f'{_chunks}.txt'
```

works, producing multiple groups, but

```
output: f'{_chunks}.txt', group_with = 'chunks'
```

does not work. 

I can live with it if it involves too much change. 

Just saw your new ticket. Will try understand that proposal now.

**Comment by gaow** [comment]
>  group_by='trunk'

I'm not sure ... we've got a table of `group_by` already with many reserved keyword rules. It would be very confusing to allow for these.

>  you are seeing group_with pairing with step_output and then paired_with pairing with _output.

Conceptually, if one sees the `_output` accumulates to `step_output`, then using `paired_with` seems justifiable? It should be either `group_with` or `paired_with` depending on how we (or SoS) view it, but using `group_by` like that does not seems good idea.

**Comment by BoPeng** [comment]
That was a typo, I meant `group_with`.

**Comment by BoPeng** [comment]
So basically we say `group_with` in output applies to `step_output`, so whatever provides with `group_with`, we take the `_index`-th element of it.

**Comment by gaow** [comment]
> So basically we say group_with in output applies to step_output, so whatever provides with group_with, we take the _index-th element of it.

Yes that's what I meant. This is exactly what happens to  `group_with` for `step_input` right? Then the behavior is consistent.

**Comment by BoPeng** [comment]
In my original design, I want to make it clear that we are **working on `_output` unless `group_by` or `for_each` is used**. Then the  single  `_output` accumulates to `step_output`.

The `group_by` case is actually reserved to one simple case like

```
infiles = a list of input files
outfiles = a list of matching output files
var1 = a list of matching properties
var2 = a list of matching group properties

input: infiles, group_by, paired_with='var1', group_with='var2'
ouput: outfiles, group_by, paired_with='var1', group_with='var2'
```
That is to say we handle input and output in the same way.

**Comment by gaow** [comment]
Difference between `group_with` and `paired_with` is that one happens before (or at the same time as) `group_by` and the other after. In that sense, `paired_with` is the right way to think about it, because the default `group_by` is already done. And `group_with` should be used when `group_by` is called again? So it should be:

```
output: f'{_chunks}.txt', paired_with = 'chunks'
``` 

and 

```
output: [f'{_chunks}.txt' for _chunks in chunks], group_by = 1, group_with = 'chunks'
```

?

**Comment by BoPeng** [comment]
No, `paired_with` applies to targets, `group_by` applies to `_output`. They are quite different.

**Comment by gaow** [comment]
> No, paired_with applies to targets, group_with applies to _output. They are quite different.

I understand they are different. But this explanation is not very intuitive so I tend to think of their difference as "Difference between group_with and paired_with is that one happens before (or at the same time as) group_by and the other after." -- is that the right non-technical understanding? 

I guess maybe my understanding above ignored some important techincal details that makes the `_output` case more complicated? 

When `group_by` is specified  in `_output` then we will be re-grouping and everything will be handled the same way as `input`. That is very intuitive and I have no issues with that.

**Comment by BoPeng** [comment]
So you mean,

1. if groups are defined by `group_by` or `for_each`, we are specifying `step_output` and we do things the `input` way.
2. if no groups are defined, we are specifying `_output`, `group_with` pairs the `_index` element of the variable.
3. In either case, `paired_with` pairs with all the specified stuff, which can be `_output` and `step_output`. This is what bothers me.

**Comment by BoPeng** [comment]
I meant,

```
A=[1, 2]
input: 'a1,txt', 'a2.txt', group_by=1, paired_with='A'
output: _input.with_suffix('.bak'), paired_with=??
```
In the present implementation,
```
paired_with=dict(_A=_input.A)
```
is needed, and makes sense because we are passing `_input` to `_output`. You might think

```
paired_with='A'
```
is easier but the output has only one element and cannot be paired with a list of 2. We cannot even resort to `_index` because the number of files for each `_output` can be different.

**Comment by BoPeng** [comment]
So what I meant that is that it can be clearer if we handle `paired_with` and `group_with` in a uniform way and

1. let them work with a groupless `sos_targets` if there is no group. That is to say, they have to specify single variables.
2. Let them work with a grouped `sos_targets` if there are groups defined by `group_by`. In this case they can specify a list that matches the number of groups.

This is basically what has been implemented.

**Comment by gaow** [comment]
> In either case, paired_with pairs with all the specified stuff, which can be _output or step_output. This is what bothers me.

It does not bother me when I accept the difference and limitations ... I guess also relevant is:

1. With your 1~3 above, do we now have more than one most elegant way to do something? 
2. Is there something we want to do to `output` but cannot do it elegantly even with 1~3?

If the answer is no to both I'll be cool with it, including using `paired_with=dict(_A=_input.A)`.  

All I wanted to do with 

```
output: f'{_chunks}.txt', group_with = 'chunks'
```

is to add an attribute to each `_index` of `step_output`. The alternative of creating the output list and regrouping them is not elegant. 

Also,

```
[1]
input: for_each = 'chunks'
output: f'{_chunks}.txt',

[2]
input: group_with = 'chunks'
```

currently works because there is an implicit `group_by`. I find it awkward to not be allowed to think of 

```
output: f'{_chunks}.txt', group_with = 'chunks'
```

as having the same, implicit group information (although I understand techinically speaking it does not!)

**Comment by BoPeng** [comment]
Would it be good enough to do something like

```
output: f'{_chunks}.txt', pass_group_var='_chunks'
```
Here we think of pairing `_input` and `_output` and pass variables in `_input` to corresponding `_output`, which might be conceptually easier to understand.

**Comment by gaow** [comment]
A new parameter might always work, but should be the last resort ... In this case I'd rather do:

```
chunks  = [1,2]
[1]
input: for_each = 'chunks'
output: f'{_chunks}.txt'
_output.set( _chunks = _chunks)
_output.touch()

[2]
print(_input._chunks)
```

(which in fact does not work ...!) My point is, maybe a workaround like this is conceptually simpler.

**Comment by BoPeng** [comment]
Regardless the ticket, your usage would better work although I know technically why it does not.

**Comment by gaow** [comment]
Okay, so to recap:

1. Let's not use an extra parameter
2. Let's keep behavior of `group_with` and `paired_with` as is, because we cannot seem to come up with a happy solution yet
3. I'll instead use either the workaround above if you deem it proper (and possibly make it work?); or I'll just use `group_with` in `input:` of step 2 to re-pair the `chunks` variable. I'm using that solution anyways for the time being.

**Comment by BoPeng** [comment]
OK, I have implemented the `_index-th` behavior.

The explanation is that

For output statement, we know the number of groups and `group_with` attaches variables to `step_output`. That is to say,

```
output: 'a.txt', group_with='whatever'
```
is not considered as

```
output: sos_targets('a.txt', group_with='whatever')
```
as the input statement. Instead, it is applied after the `step_output` is constructed. 

One complication is that

```
output: sos_targets('a.txt', group_with('whatever'))(
```
is allowed because `group_with` is a valid parameter for `sos_targets`, so in this case `group_with` has to work with a target with no group...

**Comment by gaow** [comment]
Oh okay, well this is one useful exception and at least is conceptually clear to me after all the discussions above. I think it makes sense when properly documented in a short tutorial on setting output attributes.

Explicit use of `sos_targets` is to specify `step_output`, so the behavior otherwise makes sense to me. Also it looks like it is still considered advanced feature to define complicated grouping behavior which are relevant only when all output are specified in full. So I dont see it can causes a confusion so easily.
