### ISSUE TITLE
The readonly-ness of _output

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1137]
#1132 mentions that the following can be used to replace the `paired_with` stuff.

```
[1]
output: 'a.txt'
_output.touch()
_output.set(a=1)

[2]
print(_input.a)
```
The reason why it did not is that we intentionally make `_output` readonly. That is to say, we use the original `_output` to create `step_output` so that any changes to `_output` would be discarded.

We can of course make `_output` modifiable, but then we are facing usages such as

```
[1]
_output = 'a.txt'
```

**Comment by gaow** [comment]
I see ... when we change it like  `_output = 'a.txt'` the `step_output` will not be updated right? Then indeed we should keep it read-only to avoid inconsistency. It would be even better to warn or quit on error for attempts to modify it.

**Comment by BoPeng** [comment]
We do not currently have a mechanism to give warnings for changing `_output` (or `_input`) because run time validation can be expensive. We actually had a mechanism like treating `ALLCAP` variables as read only but gave up for the exact reason,

**Comment by gaow** [comment]
I'm okay to keep `_output` readonly because it seems dangerous otherwise. But is there a way to only change the attributes?  If not, then for #1130 we still do not have an elegant solution.
