### ISSUE TITLE
Slowness deploying tasks

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1139]
Not sure if it is related to recent changes in `sos_targets` but the production code seems a lot slower now particularly for `task`. Here is a MWE:

```
loci = path('gtex_loci.txt')

[1]

chunks = [x.strip().split() for x in open(f'{loci:a}').readlines() if not x.strip().startswith('#')]

input: for_each = 'chunks'
output: f"{_chunks[-1] if len(_chunks) > 3 else '%s_%s_%s' % (_chunks[0], _chunks[1], _chunks[2])}.pkl", group_with = 'chunks'
task:
bash: expand = True
   touch {_output}
```

Running it with `-q none` I can see at least it moves along, though from the output it does not feel like well paralleled. Without `-q none` it appears stuck.

The analyze involves 30K groups in `gtex_loci.txt` attached here:

[gtex_loci.txt](https://github.com/vatlab/SoS/files/2716954/gtex_loci.txt)

**Comment by gaow** [comment]
Sure, that'd be great. I certainly hope the performance loss can eventually be compensated for by some optimization because most of my code in production are of this scale of computation. It is not urgent in the sense that I can always revert to an earlier version (0.17.7) and modify my code to not use any of the 0.18.0 features.

**Comment by BoPeng** [comment]
It could be something very simple to fix, or very hard if we are unlucky. I will try to fix it tomorrow if we are on the lucky side.

**Comment by BoPeng** [comment]
I am not sure if you used `concurrent=True` before but the problem right now is caused by the fact that

1. the master process sends the substeps to substep workers because we have `concurrent=True` as default now.
2. the worker does not do anything but sent the task back to the master
3. the master seems to be busy with patching things to substep worker and does not have time to attend to these tasks

So the tasks are queued in the master process and will not be started perhaps until so the trunks are sent to the substep worker. As you can see, the worker is not very useful in this case and this is why I allowed the workers to handle tasks not long ago when you requested to check signatures of tasks in parallel.

Adding `concurrent=False` will improve the situation but I am not sure if it will restore previous performance.

**Comment by BoPeng** [comment]
Since the step worker in this case just forward the tasks from substep workers to the master process, it makes sense to let the substep worker send the tasks directly to the master process, which should be idle at this point.

```
master --> step worker --> substep worker
 submit  <-   pass along   <-  task

**Comment by gaow** [comment]
In fact I tried both `concurrent=True` and `concurrent=False`. For the non-task version I did not notice a difference -- both are slow. For `task` I thought we always had `concurrent=True` by default. Did not try another approach.

So you are suggesting this is not related to the recent changes in `sos_targets` ? It indeed has been a while since I last submitted jobs at this scale. I'm not sure when it became like this. But sounds like bypassing the substep worker is promising?

**Comment by BoPeng** [comment]
I do not have any reference benchmark so I do not know what should be expected. Perhaps you can create a new conda env with a previous version of sos and test.

**Comment by BoPeng** [comment]
Should improve but not sure if it is still slower than before.

**Comment by gaow** [comment]
Thank you. I'm not sure either. It is certainly better than yesterday -- after a few minutes job submission I  get something like:

```
INFO: Running get genotype: Get genotype matrix
INFO: M80_13ddd8bb8c914690 submitted to midway2 with job id 55875372
INFO: M80_fcf3a298ebed7d67 submitted to midway2 with job id 55875393
INFO: M80_c8fee1b9dc9715cb submitted to midway2 with job id 55875409
INFO: M80_23ca952398dcdaed submitted to midway2 with job id 55875417
```

Here I group 34K jobs by 80 per job, so there should be 425 submissions. I currently see 4 as I was writing this post.  I was hoping to see a lot more of it submitted at the same time.

**Comment by gaow** [comment]
For the MWE in this ticket: using the latest `master` with `task:` (default chunk size is 1) I get **113 tasks done in 120 seconds**.

To run the old version of SoS we have to remove `group_with` in output. Then running with `task:` I get 545 tasks done in under one minute. So it is still about 10 times slower.

**Comment by gaow** [comment]
One other thing I noticed, as pointed out in my last post from yesterday, is that when I submit with `M80` it takes quite a while to submit each batch -- so I suspect it is still related to too much overhead on `sos_targets` not the way task requests are handled?

**Comment by BoPeng** [comment]
OK. I am still working on 1140, which is tricky because anything related to the signatures is tricky. I will have a look at this one afterwards.

**Comment by gaow** [comment]
@BoPeng No problem there is no rush on my end at all (I can use older implementation or what I find that saves time, see below). I'm just posting some observations for you to follow up when you attend to it. 

1. Here is the new MWE:

```
loci = path('gtex_loci.txt')

[1]

chunks = [x.strip().split() for x in open(f'{loci:a}').readlines() if not x.strip().startswith('#')]

input: for_each = 'chunks'
output: f"{_chunks[-1] if len(_chunks) > 3 else '%s_%s_%s' % (_chunks[0], _chunks[1], _chunks[2])}.pkl", group_with = 'chunks'
task:
bash: expand = True
   touch {_output}
fail_if(_index >= 300)
```

Noticed I added `fail_if` to limit it to under 300 tasks so that we can `time` it better. I had to keep the 34K lines of `gtex_loci.txt` file because if I only use the first few hundred lines it is fast -- perhaps it is something else to be worried about, that each step has to verify on that information (of a list of 34K tuples) unnecessarily?

For this script I get:

```
real	5m40.516s
user	11m39.060s
sys	0m34.852s
```

that is 300 tasks for 5min.

2. I kept `group_with` above.  Now if I remove `group_with` but still using current `master` I get:

```
real	0m37.307s
user	5m15.628s
sys	0m26.092s
```

Not bad!

3. Reverting to version 0.17.7(without `group_with`) I get:

```
real	0m36.366s
user	4m51.172s
sys	0m23.392s
```

roughly the same as above. So it is #1130 again, after all?

**Comment by gaow** [comment]
Great. With `group_with`, it is now:

```
real	0m37.805s
user	5m34.256s
sys	0m27.512s
```

> It is amazing how quick you caught my laziness.

It is amazing you are ever lazy :) 

I was reading that patch, is that general enough to cover all possible usage in output `sos_targets`?

**Comment by BoPeng** [comment]
Yes, it handles all cases of input `group_with`. I implemented the original version because I did not want to copy the code...

**Comment by gaow** [comment]
So to recap, the new bulkier `sos_targets` might have made it slower but not so much. And simplifying `step worker` + `substep worker`  in handling tasks should help either way, right?

Now previously i complained that `gtex_loci.txt`, having 34k lines, is a large file and will slow things down. Now if I use only the first 300 lines , my runtime benchmark is:

```
real	0m38.539s
user	4m36.152s
sys	0m24.728s
```

not very different. I think my previous observation is because of the inefficient handling of group_with

**Comment by BoPeng** [comment]
Yes. The new sos targets interface should not slow down things too much. The signatures will be larger but I have not noticed anything significant. We will see.
