### ISSUE TITLE
Random grouping of tasks.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1143]
```
input: ....
task:  trunk_size
```
will group subtasks randomly because the substeps are executed in parallel, which causes the tasks to be submitted to the task manager in parallel, and the master tasks will be created and submitted at the order in which tasks are received.

We should either accept this phenomena or try to group tasks by `_index`.

**Comment by gaow** [comment]
It might be nice to group by `_index`? at least that is what one would expect and would like to check, for example, the first few jobs (they think they have) submitted. Also does non-random grouping help with things such as signature tracking?

**Comment by BoPeng** [comment]
The code would be a lot more difficult to implement since for example in theory _index 0 can take a lot longer to pass by. Anyway, happy new year and I will have a look tomorrow (today).

**Comment by gaow** [comment]
If there is a lot overhead involved we might want to reconsider. I'm just trying to list the possible benefits to keep the job ordering. 

:) my last reply was our first post 2019. Happy New Year and have good night!

**Comment by BoPeng** [comment]
The easiest solution would be disable concurrency with trunk_size.

**Comment by BoPeng** [comment]
The tasks are generated before substep signatures are checked. In theory, if some tasks failed, only the failed tasks will be rerun...

So I think we will need to accept this phenomena and use `concurrent=False` manually if ordering is of concern.

**Comment by gaow** [comment]
> if some tasks failed, only the failed tasks will be rerun...

This is the desired behavior -- is it the case now? I've noticed yesterday for some of my examples repeated submission of jobs did not seem to skip some completed tasks. But I cannot say for sure without further tests which I cannot do now since my task queue on the cluster is saturated. 

 >  use concurrent=False manually if ordering is of concern.

That means tasks will be submitted batch by batch and the next batch is only submitted when the previous batch is completed? That is not very good use of resource. But I guess we can accept the random grouping behavior. At least I have not find it a bothering problem.

**Comment by BoPeng** [comment]
> This is the desired behavior -- is it the case now? 

It should be but I have noticed some weirdness when I played with the `trunk_size` option... and I am checking it.

**Comment by gaow** [comment]
Indeed there was some weirdness in my `trunk_size = 5` test jobs yesterday but I ended up deleting them all and submitted the actual 34K job. Would be nice if it can be confirmed that completed tasks are skipped. That is the most relevant for rescuing failed tasks.

**Comment by BoPeng** [comment]
OK. Not sure if related but there was a subtle task status bug. That is to say, when a task is completed and the pulse file has not been removed, and the task is started immediately with status pending, the task might be considered as already running... This tend to happen in my tests when I rerun simple workflows repeatedly.

**Comment by BoPeng** [comment]
Now I see the real problem with random order of subtasks

1. signatures of subtasks are stored in the master task.
2. when you regroup, the original signature that is saved with another master task is lost
3. so the subtask will be re-executed.

So random task ordering should not be allowed....

**Comment by BoPeng** [comment]
OK, tasks  have consistent grouping now, and can handle individual task failure better.

**Comment by gaow** [comment]
Wonderful! So this should fix the issue of repeated submission re-executes completed tasks? Is there much of an overhead involved? I'll test #1142  to see if it fixes it too (hopefully soon or find another account to do it).

**Comment by BoPeng** [comment]
Yes, it should. The overhead is minimal because right now sos passes index information with the tasks and submit the whole "slot" when all subtasks in a slot are filled. That is to say, the next batch will be submitted even if the previous batch is still pending a task. 

#1142 seems to be unrelated, but I will wait for your tests.

**Comment by BoPeng** [comment]
If you can reliably reproduce the error, you can add a bunch of `env.logger.error` to trace into the code, which is pretty easy to understand.
