### ISSUE TITLE
Leading and trailing spaces in path

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1144]
I noticed this issue today: though it is not directly related to what I had trouble with in one of the pipeline. : 

```
a = path('/path   ')
print(f'{a:a}')
print(len(f'{a:a}'))
```

You see the trailing white space is reflected,

```
INFO: Running default: 
/path   
8
INFO: Workflow default (ID=8ed0b3ebdf38953e) is executed successfully with 1 completed step.
```

should this be removed? Again it did not create an issue for me i just noticed the problem (unlike many other complaints were based on real issues)

**Comment by BoPeng** [comment]
Spaces in paths are significant, right?

**Comment by gaow** [comment]
But for leading and trailing spaces it is very likely user error. I wonder if we should have format options to remove them. Just mentioning it. Not a big deal I agree.

**Comment by BoPeng** [comment]
I was bitten by this before but I still think we should not be overly clever about this.
