### ISSUE TITLE
Workflow suspected false alarm and cannot be tracked

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1147]
I have submitted a workflow of 1 task containing 35 jobs (due to large `trunk_size` setting). I got the `ERROR` complaining that something is wrong. 
```
INFO: M35_d1ef9c2ae50eaa76 submitted to midway2 with job id 55932732
ERROR: [susie_bhat]: Workflow exited due to failed step susie_bhat_1.
```

But using `sos status` there is little information for me to check: 
```

[MW] sos status M35_d1ef9c2ae50eaa76 -v4
M35_d1ef9c2ae50eaa76	aborted

Created 7 min ago
Started 7 min ago
Ran for 1 min
TASK:
=====

TAGS:
=====
0071a8458fdc429e susie_bhat_1 susie_bhat_1_ENSG00000025772.7.uniform.SuSiE_B.L_5.prior_0p1.res_var_false susie_bhat_1_ENSG00

ENVIRONMENT:
============
_depends              Unspecified
_index                0
_input                Unspecified
_output               Unspecified
_runtime              {'cores': 2,
 'cur_dir': '/scratch/midway2/gaow/GIT/github/fine-mapping',
 'home_dir': '/home/gaow',
 'max_cores': 40,
 'max_mem': 64000000000,
 'max_walltime': '36:00:00',
 'mem': 5100000000,
 'run_mode': 'run',
 'sig_mode': 'default',
 'verbosity': 2,
 'walltime': '05:40:00'}
step_depends          Unspecified
step_input            Unspecified
step_name             'susie_bhat_1'
step_output           Unspecified

EXECUTION STATS:
```

and more importantly, all the 35 jobs are in fact successfully executed because they all generated desired output. 

I think it is sort of a long standing problem. I often just run it twice using `-s build`. But would be nice if we can figure out what is going on.

**Comment by gaow** [comment]
In fact looking at the `err` file, 

```
[MW] cat M35_d1ef9c2ae50eaa76.err
Note that the current default version of R is 3.5.1.
INFO: M35_d1ef9c2ae50eaa76 started
ERROR: cannot convert dictionary update sequence element #0 to a sequence
```

Looks like an SoS bug.

**Comment by gaow** [comment]
The issue also seems to be related to using `trunk_size` because when I set `trunk_size = 1` it works without an issue.

**Comment by BoPeng** [comment]
```
cannot convert dictionary update sequence element #0 to a sequence
```
is an python error message, perhaps from pandas. I saw it [here](https://stackoverflow.com/questions/27573687/python-typeerror-cannot-convert-dictionary-update-sequence-element-1-to-a-sequ) but cannot locate where the error happens.

I will try to reproduce it but perhaps you can get the line number with `-v3`.

**Comment by gaow** [comment]
I will reproduce and verify fix in another ticket, after my current jobs are done -- which should be done a while ago but for some reason it is still running and i'll report the "reason" in a separate ticket.
