### ISSUE TITLE
Trunk size not consistent for ignored substeps

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1153]
When I run with `-s build`, some of the previously runs are skipped, and for my `trunk_size = 80` jobs I get eg the following: 

```
...
-rw-rw-r-- 1 gaow gaow 7.6K Jan  3 15:50 M13_b57a6c3719a3a2c9.err
-rw-rw-r-- 1 gaow gaow    0 Jan  3 15:50 M2_16c0b7e17d0e47f0.out
-rw-rw-r-- 1 gaow gaow 1.3K Jan  3 15:50 M2_16c0b7e17d0e47f0.err
-rw-rw-r-- 1 gaow gaow    0 Jan  3 15:50 M5_276c9ac1df9b86cb.out
-rw-rw-r-- 1 gaow gaow 3.1K Jan  3 15:51 M5_276c9ac1df9b86cb.err
-rw-rw-r-- 1 gaow gaow    0 Jan  3 15:51 M11_d5df1f40f9e6a55e.out
-rw-rw-r-- 1 gaow gaow 6.5K Jan  3 15:51 M11_d5df1f40f9e6a55e.err
-rw-rw-r-- 1 gaow gaow    0 Jan  3 15:51 M3_22a77a31c6b8197c.out
-rw-rw-r-- 1 gaow gaow 1.9K Jan  3 15:51 M3_22a77a31c6b8197c.err
```

You see the actual trunk size ranges from 2 to 13. I assume because from 67 up to 78 jobs were skipped in their original trunk size of 80. If not too much trouble to achieve, I think it would be nice to re-assign failed jobs consolidating them so that I still get `M80`.

**Comment by BoPeng** [comment]
Fixed:

Running
```
[10]

input: for_each=dict(i=range(30))
output: f'{i}.txt'

task: trunk_size=10

if i in (10, 22, 1):
    0/0
_output.touch()
```
the first time gets 3 batches of 10 tasks, running the second time will get a batch of 3 tasks.
