### ISSUE TITLE
set default value of stop_if(keep_output) to True.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1161]
The default value of `keep_output` of action `stop_if` is currently set to `False`. 

Suppose users do not know this option at all and `keep_output=True` by default, the output file will be kept if it is already generated before the `stop_if` call, and will not be available if it is not generated. There is no surprise.

If the default is set to `False`, the output will not exist in both cases, which can be a surprise to users. So, from a less surprise point of view, this option should better be set it to `False` by default.

**Comment by gaow** [comment]
Sure. But if the output is not generated then SoS will know it and not complain at the end of the step?

**Comment by BoPeng** [comment]
Yes but the point is that removing a file is an aggressive action that should not be done by default.

**Comment by BoPeng** [comment]
But then the parameter name should be changed from a negative to a positive one, something like
```
stop_if(cond, remove_output=True)
```
instead of
```
stop_if(cond, keep_output=False)
```
because the consequence of the option is to remove `_output` from `step_output`, and the files if they exist.

**Comment by BoPeng** [comment]
```
stop_if(cond, discard_output=True)
```
sounds more appropriate.

**Comment by BoPeng** [comment]
```
stop_if(cond, no_output=True)
```
is used because `discard` or `remove` implies that the output already exists, and `no_output` is more neutral (and shorter) in this regard. Hopefully you have not used this new parameter somewhere.
