### ISSUE TITLE
SoS kernel with dark themes

### ISSUE THREAD

**Issue by aabor** [vatlab/SoS#1162]
When using SoS notebook with themes provided by dunovank/jupyter-themes current line highlighting hides text like in the picture provided:

![image](https://user-images.githubusercontent.com/29178038/50779283-f7a76e80-12b0-11e9-9fbd-c90f387fc087.png)

Please, do something about it. Many users prefer dark themes because it is better for eyes.

P.S. dunovank/jupyter-themes work well with other kernel types.

**Comment by BoPeng** [comment]
ok, I have disabled `styleActiveLine` which was added by SoS and thus not supported by jupyter-themes. The change should be available in the next few days with the next release of sos/sos-notebook.
