### ISSUE TITLE
Using labels instead of sources for targets in sos_targets

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1163]
We are using the term `source` to refer to the source of targets and for named input and outputs. It makes sense initially for

```
input: 'a.txt', output_from('a')
```
where the source of `a.txt` is step name etc, but a bit awkward for named inputs and outputs

```
input: a='a.txt'
```
since `a` is not a `source`. 

Unfortunately we do not have a proper name for `a` because 

* `name` of `sos_targets` is more like filename
* `group` is usually the right word but we have group of inputs for substeps already

Should we use a more neutral word `label`?

**Comment by gaow** [comment]
I'm actually cool with `name`. Otherwise `tag` is another word? Or, `ID` but the capital letter is awkward?

**Comment by BoPeng** [comment]
I was thinking of `label` because it is pretty natural to say `a.txt` is by default labelled with its step name but you can assign another label to it with keyword argument. Replacing label with source and you know why I created this ticket.

**Comment by gaow** [comment]
Oh okay then keyword conflict & similarity is not good ... Looking into difference between `label` and `tag` : 

https://www.italki.com/question/385197

> A tag is usually attached to the item or person in a manner that it will hang off. Example: A price tag hangs off the sweater sleeve. 
A label will go over the item and it is usually completely attached. Think of a food label, the words are stuck on the item. They are not hanging off.

so it indeed looks like `label` is the right word.

**Comment by BoPeng** [comment]
Terminology change is troublesome... but necessary for clarity as I felt awkward to write `sources` in the named inputs/outputs tutorials.

I also think we should not advertise the `sources` attribute (or `labels` later) because it should be enough to say how to use named input and output as in
```
sos_targets[label]
```

**Comment by gaow** [comment]
I have never used `source` in practice. Those dot methods and attributes should be considered advanced stuff -- can you find a compiling case for its usage to show in one of the tutorials? Otherwise it better stays in reference manual anyways.

**Comment by BoPeng** [comment]
The applications of `sources` are quite advanced, something like checking the available sources or looping through all sources. I did mention it in the tutorial because it shows the corresponding sources of input files. They can certainly be removed.
