### ISSUE TITLE
Progressbar for still running processes

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1169]
In `-v1` mode, sometimes a process takes very long time and the progress bar appears "stuck" -- no progress, and in my case the cursor even stopped blinking. One has to use `top` to ensure that SoS is still running. Here is  MWE:

```
[1]
input: for_each = {'i': range(25)}
bash: expand = True
    sleep {1 if i < 20 else 100}
```

Not a big deal not to have it, but would be nice if it is possible to have a blinking dot at the end of the progress bar while waiting for a substep.

**Comment by gaow** [comment]
> It is possible to add a gray (?) dot after each 5 seconds

And all the gray dots will disappear when there is some actual progress? That would be good. This reminds me of the `sinteractive` command in the slurm system of our HPC that it prints a dot every few seconds to indicate the job is still being requested.

> but sos should already quit if it crashes 

Let's say we hope this is the case. Still for users who has no idea what is going on under the hood, not seeing anything on screen is worrisome. Even I some times have to verify something is indeed running via `top`  when I do not see any progress. It can be trickier to track with `top` when the jobs are not computationally intensive. So some other indications of progress will be nice.

**Comment by BoPeng** [comment]
This can be done but I am not sure if it worth the trouble, because every real progress will reset a pulse progress bar...

**Comment by gaow** [comment]
Sure, I guess I can live with the "hanging"-like behavior. We can wait until others complain. However I do have noticed earlier to day with current version of SoS it does not quit when some steps crash (that's why i said previously "we hope it is the case"). I've yet to come up some MWE for it. Cannot easily create one for now. .. Will report that later in separate tickets.

**Comment by BoPeng** [comment]
ok, done, it is good to consolidate the progress bar into a single class anyway. Let me know if you notice any problem.

**Comment by gaow** [comment]
Thank you! Actually sorry yes there seems some issues: I'm currently trying to use a more complicated example to reproduce the failure to stop on error, the ["hang test"](https://github.com/vatlab/SoS/files/2753981/hang_test.sos.txt) example we've used before, I got:

```
$ sos run hang_test.sos.txt -v1
#################]21 steps processed (221 jobs completed)
.```

Issues are:

1. the leading `[` got absorbed
2. the ending `]` and text `21 steps` should have a space
3. there is a remaining gray (in my case, white) dot `.`  at a new line after messages are shown.

Sorry for the troubles ..

**Comment by gaow** [comment]
Hmm issues above can be reproduced with even that MWE:

```
[1]
input: for_each = {'i': range(25)}
bash: expand = True
    sleep {1 if i < 20 else 10}
```

```
$ sos run test.sos -v1
#]1 step processed (25 jobs completed)
.
```

In a more complicated example I have (no MWE) I actually see this:

![2019-01-13-21-53-42_scrot](https://user-images.githubusercontent.com/917985/51095903-bbc34c00-177d-11e9-92c6-3dde47044f49.png)

You see some of the green dot never got absorbed, and some of those white dots where there was a long running process did not get absorbed completely (there used to be many more white dots but somehow these 3 do not get absorbed)

**Comment by BoPeng** [comment]
Try again.

**Comment by gaow** [comment]
Hmm thank you, almost good now, see below:

![2019-01-13-22-00-48_scrot](https://user-images.githubusercontent.com/917985/51096023-b4e90900-177e-11e9-84a0-5dbf894268c0.png)

notice there are a couple of green dots and three white dots in between .... not sure if there is obvious fix without having to come up with a MWE for this.

**Comment by BoPeng** [comment]
Cannot reproduce but please try again.

**Comment by gaow** [comment]
Unfortunately it did not quite fix it so not sure if we want to revert the patch or do it later ... I'll try to come up with an MWE for it and report back.

**Comment by BoPeng** [comment]
Well, as usual, zmq should be used if there are potential timing issues between threads. Try again.

**Comment by gaow** [comment]
Ahh nice! I was just about to post this MWE that can somewhat reproduce the issue. But now that I check the current `master` it works flawlessly -- we can close this ticket now I think! 

[Still let me post this script here in case I want to base a future MWE on for other purposes. 
[hang_test_sleep.sos.txt](https://github.com/vatlab/SoS/files/2754051/hang_test_sleep.sos.txt)]

**Comment by BoPeng** [comment]
Yes, the problem was that the progress bar has not finished updating when another update is posted through the thread. zmq makes sure that these updates are passed sequentially.
