### ISSUE TITLE
Current SoS does not quit on error in nested steps

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1170]
Here using our "hang test" example, we got another case where it hangs:

[hang_test_fail_to_quit.sos.txt](https://github.com/vatlab/SoS/files/2753987/hang_test_fail_to_quit.sos.txt)

In this example I introduced an error to the script changing an R function `mean` to `meano` an undefined function. And I run:

```
sos run hang_test_fail_to_quit.sos.txt -v1
```

You'll see how it hangs without quitting.

**Comment by BoPeng** [comment]
Yes, somehow SoS will be terminated if one error comes from one subworkflow, but not so if two errors come from two separate subworkflows.... Still checking.

**Comment by BoPeng** [comment]
This is actually related to the `fail_if` behavior. Previously we treat the failed step normally and wait for other steps to complete, and now we terminate SoS when any one step failed, and zmq does not like abrupt termination.

**Comment by gaow** [comment]
> Previously we treat the failed step normally and wait for other steps to complete,

I'm not sure -- maybe it was meant to be the case but in fact at least in my cluster job runs if the first step fails the rest steps will never get to execute. 

I thought this is how it works:

1. if there is a failure in some substeps, the other substeps will still finish, but the step will be terminated. 
2. with `fail_if` we are explicitly detecting (or introducing) failures so if there is a failure we do want to stop and investigate before running more, right? Otherwise a `raise` will be enough to distrupt the substep in question while still keeping other substep running.

The situation in this ticket belongs to the 1st case and I was expecting the described behavior.

**Comment by BoPeng** [comment]
The problem is identified as follows:

1. If a step fails, right now it kills all workers.
2. One of the worker is running another subworkflow so the master has been waiting for its response.
3. The master zmq context is then incomplete, and destroying the zmq context will hang.

I have submitted a patch to stop destroying zmq context in this case... tests are still running though.

**Comment by gaow** [comment]
For the example above I now get this result:

![2019-01-14-14-37-52_scrot](https://user-images.githubusercontent.com/917985/51139659-1c986600-180a-11e9-9e50-1b5065069def.png)

not very clean, but it stopped at least.

**Comment by BoPeng** [comment]
Fixed.

**Comment by gaow** [comment]
Hmm now I get:

```
ERROR: Command 'Rscript .sos/mse_18_08307c20.R' returned non-zero exit status 1.
ERROR: Command 'Rscript .sos/mse_19_2eb93691.R' returned non-zero exit status 1.
ERROR: Nested worker is not supposed to receive the exception...
WARNING: Removing t_1_mean_1_mse_1.rds generated by failed step c_mse.
WARNING: Removing t_3_mean_2_mse_2.rds generated by failed step c_mse.
ERROR: [8fcec3c7-1e8b-4360-8cf8-dd3c2acfb151]: [mse]: 
Failed to execute Rscript .sos/mse_0_69dc6eac.R
exitcode=1, workdir=/home/gaow/Documents/TempDir/14-Jan-2019
---------------------------------------------------------------------------
[default]: 1 pending step: default
```

where it says:

```
ERROR: Nested worker is not supposed to receive the exception...
```

is a bit confusing.

**Comment by BoPeng** [comment]
Sorry. That was a debug code to help me understand the passing of exceptions ... I will revert soon.
