### ISSUE TITLE
Need improved error message for empty sos_group

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1171]
Took me a while to trace the cause of failure in a workflow, which boils down to:

```
[1]
output: ['1.txt', '2.txt', '3.txt', '4.txt']
for a in ['1.txt', '2.txt', '3.txt', '4.txt']:
 a = path(a)
 a.touch()

[2]
input: output_from(-1).slice(lambda x: x.stat().st_size>0), group_by = 2
print(_input)
```

You see all output from first step are empty, which makes the 2nd step empty. The error hint is not informative:

```
[GW] sos run test.sos 
INFO: Running 1: 
INFO: output:   1.txt 2.txt... (4 items)
INFO: Running 2: 
ERROR: [2]: Failed to process input statement output_from(-1).slice(lambda x: x.stat().st_size>0), group_by = 2
: Either labels or indexes should be specified
```

Would be nice to tell this case and improve?

**Comment by BoPeng** [comment]
I agree that the error message is not helping, let me see where it comes from.

But `slice` is unofficial and we have not determined a name for it. I think `select` is better.

**Comment by gaow** [comment]
Yes `slice` is more or less a programming jargon; `select` is indeed better.

**Comment by BoPeng** [comment]
Another word is `filter`, but with `select`, it is natural to have

```
a.select([1,2,3])
a.select(lambda x: True)
```
and `filter` only works with 

```
a.filter(lambda x:True)
```

However I chose `slice` because the operation actually slices through groups like a knife.

**Comment by gaow** [comment]
`select` is good for the general audience I guess. `slice` sounds perfectly fine to me though but I just worry it is too domain specific.

**Comment by BoPeng** [comment]
OK, just renamed. Will document as one of the features of `sos_targets`.

**Comment by BoPeng** [comment]
But still the question is whether or not we would like to support

```
input: output_from(-1), select=lambda x: x.stat().st_size>0, group_by = 2
```

**Comment by gaow** [comment]
I guess the same holds for `set` which you'd like to keep it restrictive? I agree explicit `select` would make more sense here. For this case we'd just have used `[x for x in ... if ]` if not for keeping the attributes of variables.
