### ISSUE TITLE
A global `workdir`

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1180]
Currently we cannot run multiple `sos` in the same directory due to potential racing conditions (and possibly will never support it?). But it makes sense to run the same pipeline for two different parameter settings at the same time, for example. It might be helpful to save separate `.sos` folders for these runs, or, to have a global configuration option to change to a work directory. In the simplest form it is just `cd /to/somewhere && sos run /path/to/script`. Is that doable or we have some mechanisms already?

**Comment by BoPeng** [comment]
Assuming that there is no conflict of file locking etc, conflict could arise from database locks. The most recent work on this problem has resolved this issue but we have not tested it yet. I would therefore encourage you to run multiple instances of sos and see if you can observe any database lock issue, then we can see if we should introduce something like what you proposed.

**Comment by gaow** [comment]
Sure, actually at least from a few runs I have on my computer it seems the database lock conflict has been resolved -- I'm able to run multiple instances under the same folder. 

But the racing condition I was referring to, and that we might never be able to support, is when indeed two workflows running in the same directory producing the same file. Is that the file lock condition you are talking about? A feedback I get from someone is that instead of having to write `A-B-(C,D)` and run it just once, they'd like to run `A-B-C` and `A-B-D` from the same SoS script under the same directory, but able to do it as if they first `cd` to some directory and run the pipelines eg `cd to_C && run A-B-C` and `cd to_G && run A-B-D` . Currently one can imaging copying the script to separate folders and run them. 

I guess with the database lock behavior hopefuly resolved, one can always do 
```
[global]
parameter: cwd = path()

[A]
task: workdir = cwd

[B]
task: workdir = cwd
```

? The only downside is to specificy these. But maybe it is not too bad?

**Comment by BoPeng** [comment]
In the software building community there is a widely adopted pattern of

mkdir debug
cd debug
cmake ../cmakefile

Perhaps we can accept this idiom?

**Comment by BoPeng** [comment]
Also, make has this [`-C` option](https://www.gnu.org/software/make/manual/html_node/Options-Summary.html)

> Change to directory dir before reading the makefiles. If multiple ‘-C’ options are specified, each is interpreted relative to the previous one: ‘-C / -C etc’ is equivalent to ‘-C /etc’. This is typically used with recursive invocations of make (see Recursive Use of make).

**Comment by gaow** [comment]
Yes I was thinking along the lines of `-C` (and the `.sos` folder will be under that folder as well right?), which is essentially a shorthand for `mkdir && cd && sos`. But overcoming the database lock issue is already a big step forward, so this feature would be a nice thing to add yet not necessary.

**Comment by BoPeng** [comment]
The `-C` option is for [recursive use of Make](http://www2.ipp.mpg.de/~dpc/gmake/make_49.html#SEC48), meaning that there is a `makefile` in the destination directory and make will go there and read it as in a current directory). This is different from what you want to do, which look more like the `cd; sos run ../workflow` idiom.

**Comment by gaow** [comment]
I'd not insist having that global workdir feature, now that at least database lock does not seem an issue.

**Comment by BoPeng** [comment]
But executing in another directory is conceptually useful when thinking of running workflows separately with different parameters or input files. The cd and run ../script idiom works so perhaps there is no need for a separate  option.
