### ISSUE TITLE
Removing variables `step_depends` and `_depends`

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1182]
With more flexible `_input`, I do not see the value of variables `step_depends` and `_depends`.

**Comment by gaow** [comment]
Well we did use it here: 

https://github.com/vatlab/sos-docs/blob/master/src/examples/Mixed_Style.sos#L72

remember after a long discussion we decide it is the best implementation? Of course alternatively, we had

https://github.com/vatlab/sos-docs/blob/master/src/examples/Mixed_Style_Data_Flow.sos

**Comment by BoPeng** [comment]
OK, but then there is no such thing as `step_depends`, right? In theory we can have `step_depends` as accumulated version of `_depends` and `shared` it in another name ....

**Comment by gaow** [comment]
I'm not sure I have used `step_depends` before but if we have `_output` and `step_output` would people assume there is `step_depends` for `_depends`?

**Comment by BoPeng** [comment]
It is pretty slow to create `step_depends` with its `groups` being `_depends`, unless we create `step_depends` only when it is `shared`. 

Right now there is no groups and `step_depends` is an accumulated version of `_depends`. I think for completeness we should treat it the same way as `step_output`.

**Comment by gaow** [comment]
> I  think for completeness we should treat it the same way as step_output.

sure, I think this is a good approach.

**Comment by BoPeng** [comment]
OK, `step_depends` now have groups.
