### ISSUE TITLE
numpy not found

### ISSUE THREAD

**Issue by Zepeng-Mu** [vatlab/SoS#1188]
I am using `sos run` to run a `ipynb` script that needs error but got the error `ImportError: No module named numpy`. I have python3 installed and have no problem with `import numpy` in the Python console. How could I solve this problem?
Thanks

**Comment by BoPeng** [comment]
It sounds like that you are mixing two different things. `sos run notebook.ipynb` executes the embedded sos workflow inside the notebook. It is not the same as "Run All" from within Jupyter. https://vatlab.github.io/sos-docs/doc/user_guide/sos_in_notebook.html has some details on how to run sos.

**Comment by Zepeng-Mu** [comment]
I think I kind of figured out how to do it. I can use `%sosrun%` in Jupyter notebook, and still trying to figure out how to do it in the command line.

**Comment by BoPeng** [comment]
`%sosrun` calls `sos run notebook.ipynb` so there is no reason why you can run the workflow from `%sosrun` but not from command line. If you are not sure, you can get the embedded workflow using

```
sos convert notebook.ipynb my.sos
```
to check what the workflow looks like before you run

```
sos run my.sos
```

**Comment by Zepeng-Mu** [comment]
Turned out that my default python version is python2, I need to change `python: expand = ...` in my script to `python3: expand = ...`.

**Comment by BoPeng** [comment]
Glad that you figured it out.
