### ISSUE TITLE
A confusing error message (and possibly confusing behavior?)

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1190]
I got a complain from someone on this message:

https://github.com/vatlab/SoS/blob/f481be7d0665192143cd25bbf280532c03b4d411/src/sos/task_executor.py#L169

It was not clear what it means by reading it. Basically they used `-s build` and this message popped up. 

```
INFO: 1f514b15c8adcb3b started
INFO: Task 1f514b15c8adcb3b for substep mash_2 (index=0) is executed with failed signature constructed
INFO: 1f514b15c8adcb3b completed
```

I'm not sure what it means. The word "failed" is scary.

**Comment by gaow** [comment]
Also, here is an issue reported by the same user. It is a user/cluster issue, but our message does not help too much:

```
INFO: Running vhat_mle: V estimate: "mle" method
INFO: 64c2a6fb7718d179 submitted to midway2 with job id 56698641
WARNING: Task 64c2a6fb7718d179 considered as aborted due to inactivity for more than 80 seconds.
ERROR: [vhat_mle (vhat_mle)]: 'ret_code'
[mash]: 2 pending steps: mash_1, mash_2
```

(actually i wonder what it is, that WARNING then the ERROR ...)

**Comment by BoPeng** [comment]
Note sure, it was an abandoned job, the `ret_code` key error is alarming though.

**Comment by BoPeng** [comment]
Yes, it is something like that the task has been aborted so rerunning the job can fix it. It is difficult to emulate the abortion of a task so it can be difficult to check what happened and implement a better message, but I will try after #1189 .

**Comment by BoPeng** [comment]
The message basically says that the signature is not built because some file is missing, so the task will be re-executed. I have removed the message.

**Comment by BoPeng** [comment]
The missing `ret_code` was caused for missing result from aborted task.
