### ISSUE TITLE
Previous steps have not generated target R_library

### ISSUE THREAD

**Issue by Zepeng-Mu** [vatlab/SoS#1192]
I am running a workflow that depends on rhdf5, I have that installed and can load it from my R console, but when I run the workflow, I got "Previous steps have not generated target R_library('rhdf5')".
Thanks

**Comment by BoPeng** [comment]
Is `R` in your `PATH`? I installed `rhdf5` and 

```
depends: R_library('rhdf5')
print('ok')
```
works correctly
```
$ sos run test
INFO: Running default:
ok
INFO: Workflow default (ID=16f4d1ba2a53a182) is executed successfully with 1 completed step.
```

**Comment by BoPeng** [comment]
@gaow I notice that bioconductor has changed their [installation process](http://bioconductor.org/packages/release/bioc/html/rhdf5.html), should we update our [installation script for bioconductor](https://github.com/vatlab/SoS/blob/master/src/sos/targets_r.py#L119)? This just proved that we should try not to be too helpful in the first place.

**Comment by gaow** [comment]
@BoPeng Well, the old installation method still works. The new method, however, does not work for R < 3.5.X. So I guess we should not bother at this point? Currently the default behavior is to not try auto_install anyways.

**Comment by Zepeng-Mu** [comment]
Curiously, both 
```
depends: R_library('rhdf5')
print('ok')
```
and
```
depends: R_library('rhdf5')
R:
   print(packageVersion('rhdf5'))
```
works fine on my login node. I am using rhdf5 version `2.26.2`.

My path for R and Rscript should be the same:`/software/R-3.5.1-el7-x86_64/bin/R`, `/software/R-3.5.1-el7-x86_64/bin/Rscript`. I am trying to run with `autoinstall=True` to see what happens.
Thanks

**Comment by gaow** [comment]
@Zepeng-Mu Just a reminder that `autoinstall=True` will not work on a compute node if the compute node does not have internet access. I still suggest that you try `which Rscript` on the compute node where you perform the computations, just in case they do not match the setup in your login node.

**Comment by Zepeng-Mu** [comment]
I am trying this, but I do not know if this is the right way:
```
JOB_OPTION="-q none -j 8"
sos run test $JOB_OPTION
```
and my test file is 
```
depends: R_library('rhdf5')
task: trunk_workers = 1, walltime = '36h', trunk_size = 1, mem = '2G', cores = 1, tags = f'{_output:bn}'
R:
    print(packageVersion('rhdf5'))
bash:
    which R
    which Rscript
```
So I think I am running on the login node since my dataset is not super large. The output looks like:
```
INFO: Running default: 
[1] ‘2.26.2’
/software/R-3.5.1-el7-x86_64/bin/R
/software/R-3.5.1-el7-x86_64/bin/Rscript
INFO: Workflow default (ID=07697fa98ed27d5f) is executed successfully with 1 completed step.
```

**Comment by gaow** [comment]
@Zepeng-Mu So you are saying the minimal example worked, but not in the context of your actual pipeline? This should not happen ... but just in case, could you update to the latest `sos` release and try again? You should be at version 0.8.14 after you update (via command `pip install sos -U`).

**Comment by Zepeng-Mu** [comment]
`0.8.14` is working, thanks!

**Comment by BoPeng** [comment]
This does not seem to be related to #1194 but I am glad that it is working.

**Comment by chj1ar** [comment]
@gaow I've just tested your minimal working example, which fails to run on UChicago RCC Midway, but works at my local end.
The content of the test SoS Notebook is as follows, and I simply ran it with the command `sos run test_Multi_tissues.ipynb`.
```
[global]
depends: R_library("biomaRt"), R_library("data.table")
R:
    print(packageVersion("data.table"))

bash:
    which R
    which Rscript
```
When running at my local end, the output was:
```
INFO: Running default: 
[1] ‘1.12.2’
/usr/local/bin/R
/usr/local/bin/Rscript
INFO: default is completed.
INFO: Workflow default (ID=95b62b0d24a2c20a) is executed successfully with 1 completed step.
```
So everything makes sense. However, when running at UChicago RCC Midway, the output was:
```
WARNING: R library biomaRt is not available.
WARNING: R library data.table is not available.
ERROR: No step to generate target R_library("data.table") requested by default
```
But actually, there seems to be no problem at all on sos and R on UChicago RCC Midway, since
```
(base) [chj1ar@midway2-login1 ~]$ sos --version
sos 0.20.1 for Python 3.7.4
(base) [chj1ar@midway2-login1 ~]$ which R && which Rscript
/scratch/midway2/chj1ar/R-3.6.1/bin/R
/scratch/midway2/chj1ar/R-3.6.1/bin/Rscript
```
So I was confused. Thank you very much.

Jiarun Chen

**Comment by gaow** [comment]
@chj1ar you have to install the R packages in question (data.table and biomart to your cluster system. Some systems (such as yours) doesnt have outside internet connection on the compute nodes so you have to do that on the login node.

**Comment by chj1ar** [comment]
@gaow I've tried and solved the problem. Thank you very much!

**Comment by BoPeng** [comment]
@gaow Can the error message be clearer?

**Comment by gaow** [comment]
@BoPeng I think the confusion is this generic statement:

```
ERROR: No step to generate target R_library("data.table") requested by default
```

because the warning messages:

```
WARNING: R library biomaRt is not available.
WARNING: R library data.table is not available.
```
is pretty clear. So I think if you make that WARNING and ERROR that should block the other unclear error message from showing up. Do you think that will help?

**Comment by BoPeng** [comment]
With `sos run` on the following workflow,

```
depends: R_library('unknwon_library')
R:
  paste("something"
```

I get

```
$ sos run test
WARNING: R library unknwon_library is not available.
ERROR: No step to generate target R_library("unknwon_library") requested by default
```

I think the point of the second message is to point out which step has stopped, although we should boost the first message from `WARNING` to `ERROR` because the workflow will not run without the library. (`WARNING` generally means the workflow would run, although unreliably).

**Comment by BoPeng** [comment]
The error message is now:

```
ERROR: R library unknwon_library is not available.
ERROR: No rule to generate target 'R_library("unknwon_library")', needed by 'default'. Stop.
```
