### ISSUE TITLE
Travis tests do not quit cleanly under linux.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1196]
I have spent long hours trying to figure out why travis tests do not quit cleanly under travis. It seems to boils down to `test_execute.py` and [removing one test seemed to work](https://github.com/vatlab/SoS/commit/d831d9962282142e396f331d88cba88ef429a8ae) but there is nothing suspicious about this test.

I suspected zombie processes and wraps the tests under [check_zombie.py](https://github.com/vatlab/SoS/blob/master/test/check_zombie.py) but this does not seems to be a problem either. Perhaps we will have to log in to travis or get a test docker image to figure out the reason.

**Comment by gaow** [comment]
Indeed, what's special about [this workflow in question](https://github.com/vatlab/SoS/blob/master/test/sample_workflow.ipynb)? Is there another simpler test for executing `ipynb` files? Can it be some dependency issues parsing ipynb files?

Also current build still seems to fail even though all tests pass?  Is that the warning messages causing it? For the warning message, 

```
    from collections import Sequence, Mapping, Set
```

should now be

```
    from collections.abc import Sequence, Mapping, Set
```

**Comment by BoPeng** [comment]
I created a branch and add remove tests. Removing that test fixed the hanging issue but removing some other tests could also stop hanging. The warnings you mentioned appear also in successful test runs so are unlikely to be the culprit. 

The only sensible way to debug is to login to Travis, which we will have to contact Travis support ...

**Comment by BoPeng** [comment]
Per https://docs.travis-ci.com/user/running-build-in-debug-mode/, I just emailed travis tech support.

**Comment by BoPeng** [comment]
[testSetVariablesTo_Output](https://github.com/vatlab/SoS/blob/master/test/test_execute.py#L1983) is confirmed to single-handedly trigger the hang, but the test hangs after removing this test, so there are more.

**Comment by BoPeng** [comment]
This test does not fail under windows using native python 3.6, but fails under anaconda python 3.7.

**Comment by BoPeng** [comment]
OK, it is confirmed. The test comes from the python module `pytest-cov`, which is a module for pytest that check the coverage of source code. The minimal test case is

```python
import unittest

from sos.parser import SoS_Script
from sos.workflow_executor import Base_Executor

class TestExecute(unittest.TestCase):
    def testSetVariablesTo_Output(self):
        '''Test assigning variables to _output'''
        # if there are substeps
        script = SoS_Script('''\
[10]
input: for_each=dict(i=range(2))
output: f'a_{i}.txt'
_output.touch()
''')
        wf = script.workflow()
        Base_Executor(wf).run()

if __name__ == '__main__':
    unittest.main()
```

Because this test uses `multiprocessing`, it seems that the `pytest-cov` adds some hooks to multiprocesses and makes sos hang.

**Comment by BoPeng** [comment]
Maybe this is related to https://pytest-cov.readthedocs.io/en/latest/mp.html.

**Comment by BoPeng** [comment]
Good, after installing `pytest-cov` locally, I can reproduce the hang....

**Comment by BoPeng** [comment]
Will fix after the upstream fix (https://github.com/pytest-dev/pytest-cov/pull/262).
