### ISSUE TITLE
`skip_if` should delete the corresponding output of substep from `step_output` (and other minor issues)

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1198]
Here is a MWE:

```
[default_1]
output: '1.txt', '2.txt', '3.txt'
bash: expand=True
  touch {_output} 

[default_2]
input: group_by = 1
output: f'{_input:n}.out'
_output.touch()
skip_if(str(_input) == '2.txt')

bash: expand = True
  touch {_output}

[*_3]
python: expand = True
  fn = {_input:r}
```

I get the following:

```
INFO: Running default_1: 
INFO: default_1 (index=0) is ignored due to saved signature
INFO: output:   1.txt 2.txt... (3 items)
INFO: Running default_2: 
WARNING: Removing 2.out generated by failed step default_2.
INFO: output:   1.out 3.out in 3 groups
INFO: Running *_3: 
  File "/tmp/tmpro747_7t.py", line 1
    fn = 
        ^
SyntaxError: invalid syntax
ERROR: Command 'python .sos/*_3_1_ee30c5b7.py' returned non-zero exit status 1.
ERROR: [*_3]: 
Failed to execute python .sos/*_3_1_ee30c5b7.py
exitcode=1, workdir=/home/gaow/tmp/29-Jan-2019

```

There are three problems:

1. `skip_if` in this case triggered a warning message claiming a "failed" substep, which is disturbingly confusing.
2. the 2nd step actually has output `1.out` and `3.out` not `2.out`. But the 3rd step does not know it. It fails at `_index == 2` because the input is empty. Since we removed the output anyways, it makes sense to also remove it from `step_output`
3. The `*_3` resulted in a file `*_3_1_84dd9228.py` saved. Not sure if it is possible to replace it with the actual step name? The `INFO: Running *_3: ` might also be improved to use the actual step name?

**Comment by BoPeng** [comment]
1. The behavior is intended but the warning message is indeed wrong. Actually, since users know this is a skipped substep, perhaps this line is not needed at all (unless a message is provided).

2. Not sure what to do here.

3. Yes, should be fixed.

**Comment by gaow** [comment]
> Actually, since users know this is a skipped substep, perhaps this line is not needed at all (unless a message is provided).

Agreed

> Not sure what to do here.

Can we remove the corresponding `_output` from `step_output`? Currently for my pipeline to work I have to do this:

```
input: [x for x in output_from(-1) if x], group_by = 1
```

But if `_output` is removed from `step_output` i can omit this line.

**Comment by BoPeng** [comment]
The problem with removing empty `_output` is that I do not know the importance of information such as number of groups and which substep is ignored. Right now at least you have the option to remove them, but you will not be able to restore the information if you remove them.

One possibility is to treat the case as

```
output_from(-1, remove_empty=True)
```
and users can explicitly call
```
output_from(-1, remove_empty=False)
```
if they would like to keep the empty groups.

**Comment by gaow** [comment]
Your proposed solution sounds reasonable! We'll see in practice whether or not uses would care down the line which indices are removed after we have this feature. At least for now, removing empty `_output` by default should not be a bad/unexpected behavior.

**Comment by BoPeng** [comment]
Submitted but as usual there can be better names, at least `keep_empty_groups` is more informative.

**Comment by gaow** [comment]
I think it is good enough for now. I confirm it worked for my pipeline. The option should not be used that often I believe. Please feel free to close the ticket after 3 is fixed :)
