### ISSUE TITLE
Adding new language module

### ISSUE THREAD

**Issue by ktaletsk** [vatlab/SoS#1202]
I am trying to create a new language module to support C++ using [xeus-cling Jupyter kernel](https://github.com/QuantStack/xeus-cling). I am following instructions from docs [here](https://vatlab.github.io/sos-docs/doc/documentation/Language_Module.html), but for now it's just a template which should do nothing, but recognize installed kernel and print debug message when magics like `%get` are called. I use the sos-r as a reference for my code.

This is an excerpt from `sos-xeus-cling/src/sos_xeus_cling/kernel.py`:

```
class sos_xeus_cling:
    background_color = '#9400D3'
    supported_kernels = {'C++11': ['xeus-cling-cpp11'], 'C++14' : ['xeus-cling-cpp14'], 'C++17' : ['xeus-cling-cpp17']}
    options = {}
    cd_command = '#include <unistd.h>\nchdir("{dir}");'

    def __init__(self, sos_kernel, kernel_name='xeus-cling-cpp14'):
        self.sos_kernel = sos_kernel
        self.kernel_name = kernel_name
        self.init_statements = ''

    def get_vars(self, names):
        for name in names:
            if name.startswith('_'):
                self.sos_kernel.warn(
                    f'Variable {name} is passed from SoS to kernel {self.kernel_name} as {"." + name[1:]}')
                newname = '.' + name[1:]
            else:
                newname = name
            xeus_repr = _xeus_declare_variable(env.sos_dict[name], newname)
            if self.sos_kernel._debug_mode:
                self.sos_kernel.warn(xeus_repr)
            self.sos_kernel.run_cell(f'{xeus_repr}', True, False,
                                     on_error=f'Failed to get variable {name} to xeus-cling')

```

Here is my installation sequence. First, I install xeus-cling
```
RUN conda install xeus-cling xwidgets notebook -c conda-forge/label/gcc7
```
Then I install my language module (sos-xeus-cling), using `python setup.py build && python setup.py install --single-version-externally-managed --root=/ `.
Finally I install all related SoS packages:
```
RUN conda install -y feather-format -c conda-forge
RUN pip install nbformat --upgrade
RUN pip install sos-notebook sos-r sos-bash sos-matlab sos-scala sos-python --upgrade
RUN python -m sos_notebook.install
RUN jupyter labextension install jupyterlab-sos
```

As a result, I have a perfectly functioning SoS setup with all kernels visible and working. Variable passing with `%get` and `%put` works for all kernels except for my new c++ kernels ( xeus-cling-cpp11, xeus-cling-cpp14, xeus-cling-cpp17). You can see that SoS correctly picked up the kernels names and cell colors, but not the functions.

[![Screen-Shot-2019-01-31-at-11-26-05-AM.png](https://i.postimg.cc/QdQyNGvH/Screen-Shot-2019-01-31-at-11-26-05-AM.png)](https://postimg.cc/PCq4KcXj)

`%get` gives an error at line https://github.com/vatlab/sos-notebook/blob/f8eb7f16e9f11c62a6f4b294fef0730b0fc1ea52/src/sos_notebook/kernel.py#L663
`%put` gives an error at line https://github.com/vatlab/sos-notebook/blob/f8eb7f16e9f11c62a6f4b294fef0730b0fc1ea52/src/sos_notebook/kernel.py#L718

Looks like my c++ kernels are not in `self.supported_languages`. How do I fix that? Maybe there is a preferred method to install new modules?

**Comment by BoPeng** [comment]
Do you have a repo that I can look at? In terms of "template", the currently frame-only [sos-scala](https://github.com/vatlab/sos-scala) is perhaps easier to copy. Anyway, as a first step, could you let me know if you have registered the language module with SoS, as in [this line of code](https://github.com/vatlab/sos-scala/blob/master/setup.py#L46)?

**Comment by BoPeng** [comment]
The second step is to check is if the language module can be imported. You can test this by running your version of

```
python -c 'from sos_scala.kernel import sos_scala'
```
Then you can check if the displayed name appears because SoS displays kernel name when a language module cannot be loaded, and language name otherwise.

**Comment by ktaletsk** [comment]
@BoPeng here's the repo: https://github.com/ktaletsk/sos-xeus-cling
I registered the module similarly to how it's done in Scala: https://github.com/ktaletsk/sos-xeus-cling/blob/0ca95593ae056f08bc36751016440bbfe2e20621/setup.py#L46
```
Cpp = sos_xeus_cling.kernel:sos_xeus_cling
```

Curiously, none of my installed kernels return anything (no error, no kernel name, just nothing) when I run any of the following commands:

```
python -c 'from sos_xeus_cling.kernel import sos_xeus_cling'
python -c 'from sos_scala.kernel import sos_scala'
python -c 'from sos_r.kernel import sos_R'
python -c 'from sos_matlab.kernel import sos_MATLAB'
python -c 'from sos_bash.kernel import sos_Bash'
```

All those kernels are installed. If I run `jupyter kernelspec list`, I get
```
  bash                /home/jovyan/.local/share/jupyter/kernels/bash
  octave              /home/jovyan/.local/share/jupyter/kernels/octave
  scala               /home/jovyan/.local/share/jupyter/kernels/scala
  sos                 /home/jovyan/.local/share/jupyter/kernels/sos
  ir                  /opt/conda/share/jupyter/kernels/ir
  python3             /opt/conda/share/jupyter/kernels/python3
  xeus-cling-cpp11    /opt/conda/share/jupyter/kernels/xeus-cling-cpp11
  xeus-cling-cpp14    /opt/conda/share/jupyter/kernels/xeus-cling-cpp14
  xeus-cling-cpp17    /opt/conda/share/jupyter/kernels/xeus-cling-cpp17
```

**Comment by BoPeng** [comment]
Oh, this is because you did not register languages `C++11` etc in `setup.py`. In your case, you should do
```
[sos_languages]
C++11 = sos_xeus_cling.kernel:sos_xeus_cling
C++14 = sos_xeus_cling.kernel:sos_xeus_cling
C++17 = sos_xeus_cling.kernel:sos_xeus_cling
```
You might also need to define different colors for different languages for the `background` definition.

**Comment by BoPeng** [comment]
When you define `put_vars` and `get_vars`, it is helpful to do

```
self.sos_kernel.warn(msg)
```
or
```
env.log_to_file(msg)
```
and the latter send `msg` to `~/sos_debug.log`.

You can also run
```
%debug on
```
which will send more details (e.g. when you call `self.sos_kernel.get_response`) to that file as well.

**Comment by ktaletsk** [comment]
> Oh, this is because you did not register languages `C++11` etc in `setup.py`.

That fixed the problem! https://github.com/ktaletsk/sos-xeus-cling/commit/f4846790c2f6438dfd305a73f48a11a36c6abd22

Maybe should update documentation for someone trying to extend the language. Is there a way to contribute to docs? I would be happy to help

**Comment by BoPeng** [comment]
That would be great. The documentation is currently at [here](https://github.com/vatlab/sos-docs/blob/master/src/documentation/Language_Module.ipynb) and we run a [SoS script](https://github.com/vatlab/sos-docs/blob/master/development/update-website) to convert it to HTML. It would be great if you could update the notebook with your experience and submit a PR (changes to `.ipynb` is good enough).

BTW, the color of your language does not appear here (perhaps works for you) because the latest version of sos-notebook uses css to display color, and `lan_C++11` is not a valid css name. A fix is possible on our end (e.g. translate `C++` to some valid name) but at least for testing you can use names `Cpp11` etc.
