### ISSUE TITLE
`trunk_size` messed up with grouping of input

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1203]
## Problem

It took me a while to pin on this bug and came up with the MWE:

```
l=[x for x in range(1,11)] 

[2]
input: for_each = 'l'
output: out1 = f'{l[_index]}.out1',  
	out2 = f'{l[_index]}.out2'

task: trunk_size = 2
_output[0].touch()
_output[1].touch()

[3]
output: _input['out1'].with_suffix('.out3')
task: trunk_size = 2
_output.touch()
```

To run it:

```
sos run test.sos -s force
```

the output:

```
INFO: Running 2: 
INFO: M2_82e99d8c2dd922de re-execute completed
INFO: M2_428e5735476ff33a re-execute completed
INFO: M2_d014bed94fc74396 re-execute completed
INFO: M2_d7939e2e58096dbf re-execute completed
INFO: M2_d94deb96d1d9bbb0 re-execute completed
INFO: M2_82e99d8c2dd922de started
INFO: M2_428e5735476ff33a started
INFO: M2_d014bed94fc74396 started
INFO: M2_d7939e2e58096dbf started
INFO: M2_d94deb96d1d9bbb0 started
INFO: All 2 tasks in M2_82e99d8c2dd922de completed
INFO: All 2 tasks in M2_d014bed94fc74396 completed
INFO: All 2 tasks in M2_428e5735476ff33a completed
INFO: All 2 tasks in M2_d7939e2e58096dbf completed
INFO: All 2 tasks in M2_d94deb96d1d9bbb0 completed
INFO: output:   1.out1 1.out2... (20 items in 10 groups)
INFO: Running 3: 
ERROR: [3]: Failed to process step output (_input['out1'].with_suffix('.out3')): sos_targets object has no attribute with_suffix
```

but without `trunk_size` (using `-q none`):

```
sos run test.sos -s force -q none
```

it works.

It is not obvious from this MWE but in practice what happened to my pipeline is that the grouping for step `[3]` appears messed up by `trunk_size`. In practice it has very bad impact as it created long path on my computer. See picture below:

![screenshot](https://user-images.githubusercontent.com/917985/52102089-2eb52b00-25a4-11e9-8b48-6ac712b7915c.png)

I suspect it can be fixed if the MWE is fixed.

## Additional notes

Two interesting observations:

1. For the MWE, it works without `-s force` when I rerun it.
2. For the messed up path in the screen shot above: it does not happen for all groups of jobs, but only some of them are problematic. This is quite curious!

**Comment by BoPeng** [comment]
The root of the problem seems to be `trunk_size` altered the output groups.... let me check.

**Comment by gaow** [comment]
Update: the issue shown in that figure above still persists after i use `-q none`. I do hope it is a user error on my end, though I've been spending quite some time already on it to no vail ... Might use another ticket for it if I can verify and reproduce with MWE.

**Comment by bioworkflows** [comment]
From time to time this copying reference thing would bite us... Let me know if the patch works.

**Comment by gaow** [comment]
It appears to have solved all problems described. Thanks!
