### ISSUE TITLE
SoS file parsing issue

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1211]
I have this SoS file:

[test.sos.txt](https://github.com/vatlab/SoS/files/2858990/test.sos.txt)

When I run it `sos run test.sos.txt` you'll see there is a parsing error. 

However, if I remove the line

```
  ld_file = ${_input[0].with_suffix('.ld_file.ld'):r}
```

and run it again the error is gone. If I remove all text after that line, but keep that line as is, that is, if I remove all text below and including 

```
class dotdict(dict):
```
it also works (no parsing error). I wonder what's going on here ...

**Comment by BoPeng** [comment]
The problem is that the SoS created statement has

```
f" ld_file = {_input[0].with_suffix(\'.ld_file.ld\'):r} "
```
and python does not allow `\` in format string expressions. Let me try to fix it tomorrow.

**Comment by gaow** [comment]
Sure, take your time. It is interesting that it seems to depend on other contents of the script ...

**Comment by BoPeng** [comment]
Test case:

```
python3: expand = "${ }"

  ld = ${'a'}
  a =  """doc"""
```

Reason, with the presence of `"""`, sos first concerts the string to a regular string 
```
"\nld = ${\'a\'}\na =  \"\"\"doc\"\"\"\n\n"
```
then replace `sigil` and add `f` to
```
f"\nld = {\'a\'}\na =  \"\"\"doc\"\"\"\n\n"
```
However, in python f-string, backslash is not allowed.

**Comment by BoPeng** [comment]
The tricky part here is that we cannot add backslash to quotes inside python expression in f-string, so if we have a string with expressions that use all potential quotation methods, we cannot include them in a valid Python f-string with any outside quote.

```
{'a' } {"a"} {'''a'''}{"""a"""}
```
because
```
f"{'a' } {"a"} {'''a'''}{"""a"""}"
```
etc would be invalid. I guess it is fair enough to say that this string cannot be presented as python f-string although they are perfectly ok in SoS' script format.

**Comment by BoPeng** [comment]
OK, it is a lot of code to handle the complicated cases but hopefully I have considered and tested all possibilities. Basically, I use shortcuts for simple cases and have to parse `f-string` manually and analyze the expressions piece by piece in complex cases, and in the worst case, 

```
{'a'}{"a"}{'''a'''}{"""a"""}
```
is converted to
```
'{0}{1}{2}{3}'.format('a', "a", '''a''', """a""")
```
Please close the ticket after you confirm the patch works for you.

**Comment by gaow** [comment]
I'm sorry for the troubles, "check_till" sounds tedious ... but unfortunately it still does not work ... for the script below:

[test2.sos.txt](https://github.com/vatlab/SoS/files/2866980/test2.sos.txt)

**Comment by BoPeng** [comment]
Well, as long as you can a test case, it is easy to spot the problem.

```
[default]
report: expand = "${ }"  
  ld_file = ${_input['']:r}
  """ '''
  {}, ${_output:r},
  ```
Fix is on the way.

**Comment by BoPeng** [comment]
Fixed. I noticed that you have no empty lines between code, and you can actually have them and they do not have to have the same indentation.

**Comment by gaow** [comment]
Thank you. it works now!

> I noticed that you have no empty lines between code, and you can actually have them and they do not have to have the same indentation.

Thanks for he pointer. Sure, that was an artifact when I copied it from a HTML file exported by jnbinder where white spaces are removed. I do not recall why I did that back then :P
