### ISSUE TITLE
Too many open files with MANY subworkflows.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1223]
With the following workflow
```
[nested]
parameter: idx=int
print(f'I am nested workflow {idx}')

[0]
parameter: rep=15
input: for_each=dict(rep=range(rep))
sos_run('nested', idx=_index)
```

If I run it with large `rep`, namely a large number of subworkflows,

```
sos run test --rep 300
```

 I will get an error saying "too many open files".

The problem here is that SoS workers might have many slots, each with an open socket, so the total number of sockets/open files can be large.

**Comment by gaow** [comment]
Is this related to #1208 where we had several rounds of discussions and have already eliminated lots of them? Does the improve `-j` control help, or not because we are talking about cumulatively opened sockets?

**Comment by BoPeng** [comment]
I can reproduce the `too many open files` problem with 

```
sos run test.sos --rep 300 -j4
```

but using the open file checker script in #1208 , I see
```
5 processes
79966 has 2 open files and 36 open connections
79993 has 1 open files and 13 open connections
79994 has 2 open files and 30 open connections
79995 has 2 open files and 30 open connections
79996 has 2 open files and 25 open connections
Overall 2 open files and 90 open connections
```

So there are not many open connections at all.

**Comment by BoPeng** [comment]
[check_open_files.txt](https://github.com/vatlab/SoS/files/2913029/check_open_files.txt)

[test_sos.txt](https://github.com/vatlab/SoS/files/2913030/test_sos.txt)
[test_sh.txt](https://github.com/vatlab/SoS/files/2913034/test_sh.txt)

**Comment by BoPeng** [comment]
zon a Linux system, I get the error when I use `--rep 3000`, and the process stops at 530 open files.

**Comment by BoPeng** [comment]
The patch makes sure all steps are processed before workflows so that workflows will not be submitted early and wait for their steps to be completed (while occupying a socket). With this change the maximum number of open connections is kept below 50 all the time.
