### ISSUE TITLE
Current submitter only submits one job at a time

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1224]
For jobs with many substeps the previous behavior was to submit all of them up to `max_jobs` (or `-J`) on cluster. However with version 0.19.0 it is not longer the case. The job submission seems sequential. For example on the cluster:

```
[MW] cd ~/tmp/18-Feb-2019/
[MW] sos run mnm.sos -c midway.localhost.yml -j 12

INFO: Running small_data in pipeline #1: 
INFO: Running oracle_generator in pipeline #1: 
INFO: Running module small_data: 
INFO: Running module oracle_generator: 
INFO: M1_4797eebaafbaf3b2 submitted to midway2_head with job id 58191696
INFO: output:   finemap_output/oracle_generator/oracle_generator_1.pkl
INFO: M50_3a8355440d64a5fb submitted to midway2_head with job id 58191700
...
```

Notice there is only one job submitted:

```
[MW] showq
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
          58191700   broadwl M50_3a83     gaow  R       0:59      1 midway2-0041

```

**Comment by BoPeng** [comment]
Right now substeps has the priority over step (then over subworkflows #1223) to execute, so it looks like substeps are being executed, sending tasks to step, but step does not get a chance to send the tasks to controller because it has low priority to execute.

The task should be sent directly to the controller, although right now they are sent to step first because step needs to keep track of them.

**Comment by BoPeng** [comment]
Low priority does not mean not executed though. In the following example, tasks are submitted before all substeps are processed

```
[1]
input: for_each=dict(i=range(1000))
print(i)
import time
time.sleep(0.1)

task:
sh: expand=True
echo Task {i}
```

**Comment by gaow** [comment]
Sorry I'm a bit confused. The observation is that only one job of trunk_size 50 is in the queue even though I expect a lot more than that. So the low priority in practice has caused delays in job submission, and this is not a desired behavior right?

**Comment by BoPeng** [comment]
Sorry, I was confused as well. So you have `trunk_size=50`, but got `M1`? I also saw a `M50` though.

**Comment by gaow** [comment]
So the workflow in question involves two steps. One step has just 1 substep, and it fits `M1` job. The other step has 150 substep and my trunk size is 50. I expect it to send in 3 `M50` jobs concurrently, which did not happen. In fact it should send that `M1` job and  three `M50` jobs all at the same time because the two steps are independent. This is what indeed happens in 0.18.7 but not now.

It can be reproduced by the same example on the cluster. We just have to force rerun that workflow `mnm.sos`.

**Comment by BoPeng** [comment]
So you meant the tasks are blocking? Let me check.

**Comment by gaow** [comment]
Yes It looks like blocking behavior
