### ISSUE TITLE
Yet another problematic lock 

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1227]
I noticed this issue via the `jnbinder` script. To reproduce it, first checkout a bunch of notebooks here:

```
git checkout https://github.com/stephenslab/ipynb-website
```

then 

```
cd ipynb-website
sos run release.sos
```

you should see a lock behavior. It is possible that `release.sos` logic is not good (too many things added to it after a first draft; it will need a redesign) but it is a good test case for the problem at least.

**Comment by BoPeng** [comment]
There are two processes, one is nested workflow waiting for the completion of a step, and one is waiting for the completion of a step, which is `update-nb`. Not sure why `update-nb` is stuck though.

**Comment by BoPeng** [comment]
This is caused by a complex interaction among multiple `sos_run`s. The new `SOS_DEBUG` syntax (#1060 )

```
export SOS_DEBUG=EXECUTOR,-; sos run ...
```
is helpful in narrowing down the problem.
