### ISSUE TITLE
Parameter pickling / passing bug

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1229]
Unfortunately here is another bug due to changes to the global section handling

```
[A]
parameter: param = str
print(param)

[B]
print(step_name)

[default]
sos_run('B+A')
```

command

```
 sos run test.sos A --param test
```

works, but not

```
$ sos run test.sos  --param test
INFO: Running default: 
INFO: Running B: 
B
INFO: Running A: 
ERROR: [2336ca46-9028-4396-8a8b-6e3bffea8dd2]: [A]: Argument param of type str is required
```

Notice there is a moment of "hang" at `Running A` before it failed with that error message.

**Comment by BoPeng** [comment]
Well, if it is not in our test suite, I would consider it as a feature request, not a bug report. 😄
