### ISSUE TITLE
Simplify the creation of a single output from multiple input files?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1231]
A user case is something like

```
input: 'a.txt', 'b.txt', group_by=1, concurrent=False

if _index == 0:
    sh('rm -f "all.txt"')
sh: expand=True
    echo {_input} >> "all.txt"
    cat {_input} >> "all.txt"
```
Basically this step tries to `cat` all input files to a single output file.

The problems are:
1. `ouptut:` statement cannot be used  if we use `group_by=1` because right now we require substeps to have different outputs.
2. We cannot use `group_by` if we are to set `output`, then users have to loop through `_input` by themselves
2.  it is ugly to clear output file before the first substep

So I am wondering if we can do something to this sort of change output case.

**Comment by gaow** [comment]
Interesting ... I never thought about changing SoS although apparently it is a common user case. For such multiple input and single output I always do `group_by = all` and do 2 (loop manually) and I find it conceptually clear. I can see the appeal of being about to do it at SoS level but not so much of an appeal.

**Comment by BoPeng** [comment]
I agree. Just wondering how popular this kind of "reduce" steps are. If we are to support `group_by`, we will have to tell `SoS` that all substeps share the same output and should be run sequentially.

Perhaps
```
input: multiple files
output: output file
for ifile in _input:
  ...
```
is not so bad.

**Comment by BoPeng** [comment]
Not worth special syntax.
