### ISSUE TITLE
Indented actions in script format

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1233]
We have insisted that function name in script format has to start from the first column. Consequently, we have to use regular function calls if the actions are used in conditions or loops.

```
if True:
    sh('''\
line1
line2
''')
```

I am therefore wondering how difficult (or confusing) it could be to allow

```
if True:
    sh:
        line1
        line2
```

**Comment by BoPeng** [comment]
The problem here is that it is a lot harder to determine the end of the script. Right now, we determine the end of script as "the next valid SoS directive", which means things like

```
[step]
R:
input:
```
after
```
sh:
line1
line2
```
and indentation make it easier to find the end of script because all SoS structure starts from column 1.

If we are to allow for spaces before action name, we will see

```
if True:
    sh:
line1
line2
    R:
line1
line2
else:
    something
```
which first indentation is much more important than before because ambiguity from
```
if True:
    python:
if whatever:
    do something
else:  # how to match this else?
    do something else
```
but then the ending condition will have to include "Python structure", namely
```
if True:
    python:
        if whatever:
            do something
    if whatever:  # getting out of script mode
        do something else
```

So in the end the added flexibility seems to add more confusion than convenience.

**Comment by BoPeng** [comment]
So the only sensible way to make it work would be enforcing indentation so that we have

```
if True:
    sh:
        line1
        line2
    R:
        line1
        line2
else:
    something

**Comment by gaow** [comment]
I think the scenario above would be less prevalent than scenarios where leading spaces are ignored. In other words in practice perhaps enforcing indentation is overall more limiting than to require use of regular function calls in scenario above.

**Comment by BoPeng** [comment]
We do not have to enforce indentation, just if we set some rule to detect end of script, proper indentation would be the best way to avoid ambiguity

**Comment by BoPeng** [comment]
I am actually more worried about wide adoption of this feature because I want users to use `group_by` and `stop_if` instead of `for...` and `if ...`. However, if really needed,

```
if True:
    sh:
        line1
        line2
    R:
        line1
        line2
else:
    something
```
is still a lot more readable than
```
if True:
    sh('''
line1
line2''')
    R('''
line1
line2''')
else:
    something
```

**Comment by BoPeng** [comment]
The patch does not fail any test and allows

```

if True:
    sh:
       echo 'A'
    python:
	 print('a')
```

**Comment by BoPeng** [comment]
[this test](https://github.com/vatlab/SoS/blob/script_format/test/test_parser.py#L1892) shows the supported formats. Basically,

```
[1]
if True:
    sh:
echo something
[2]
for i in range(2):
    sh:
echo something
```

```
[1]
if True:
    sh:
echo something
    python:
print(1)
```

```
[1]
if True:
    sh:
        echo something
[2]
for i in range(2):
    sh:
        echo something
```
```
[1]
if True:
    sh:
        echo something
    python:
        print(1)
```

```
[1]
if True:
    sh:
        echo something
else:
    python:
        print(1)
```

```
[1]
for i in range(2):
    if True:
        sh:
            echo something
    else:
        python:
            print(1)
```

are supported, and


```
[1]
if True:
    sh:
echo something
else:
    python:
print(1)
```
is not.

**Comment by BoPeng** [comment]
merged.

**Comment by BoPeng** [comment]
Documented [here](https://vatlab.github.io/sos-docs/doc/user_guide/scripts_in_sos.html#Indented-script-format) but has to re-open because of the need to add syntax highlighting for indented actions.

**Comment by BoPeng** [comment]
Regression:

```
report:
    name: whatever
```

fails because `name:` is recognized as an action.

**Comment by BoPeng** [comment]
fixed.
