### ISSUE TITLE
Changing internal mem unit from bytes to Mb or Gb?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1240]
Right now when user specified `mem='6G'`, SoS converts it to bytes `6000000` and users can do some calculation in the template file and say

```
#BSUB -M {mem // 10**9}G
```

It does not really matter but all the systems I am working on require memory in Gb, so it is more convenient if we provide `mem` in `Gb` or `Mb`.

**Comment by gaow** [comment]
I'm neutral to the change, considering the template is something one might not change once it is written. So users only have to think of bytes for just one time.

**Comment by BoPeng** [comment]
The problem here is inconsistency, as we provide walltime as `HH:MM:SS` (string) and `mem` as `int` (bytes). For walltime, one of the systems asks for `HH:MM` so I had to use `walltime.rsplit(':', 1)[0]`, and for `mem`, one system asks for `xxG` and one system asks only `xx` in `GB`.

Whereas the current situation is certainly tolerable, I am wondering if we should make `walltime` and `mem` some objects so that users can do something like

```
walltime.format('HH:MM')
```
and
```
mem.format('Gb')
```
and
```
queue = { 'long' if walltime > '12h' else 'medium' }
```
The problem here is that whereas the existing rules are rudimentary and inconsistent, they are easy to remember, and the new interface can be confusing as they add something else to remember.

**Comment by gaow** [comment]
Well, although I appreciate the problems and the appeal of solutions, I still think to users it should not be a big deal since these properties in job templates are not going to be changed once created. Same arguments holds for voting to create those objects you proposed which are flexible; and the additional learning curve is totally tolerable again because they'll not be changed.

**Comment by BoPeng** [comment]
ok, let us keep things as they are. If `STAR` accepts parameters such as `--whatever 30000000000` (I was counting zeros yesterday), perhaps it is not too bad to write `#BSUB -M {mem // 1000000000}G`.
