### ISSUE TITLE
Remove cur_dir task variable

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1244]
Currently we support a runtime variable `cur_dir`, which is the current project directory, and will be mapped to the remote host. We also support `workdir`, which is the specified `workdir` of `task`, default to current directory.

There is no reason to keep `cur_dir` because `workdir` has everything needed for `cur_dir`. Moreover, if `task_dir` is not current directory, the task will be executed at the `workdir` so there is no need to change directory to (remote) `cur_dir` before going to `workdir`.

`cur_dir` will be deprecated but stay for backward compatibility.

**Comment by BoPeng** [comment]
`home_dir` will also be deprecated because of the existence of  `~` , `os.environ['HOME']`, and `path(name='home').

**Comment by gaow** [comment]
I have never used `cur_dir` (an indication it is not a useful feature?). I do use `workdir` all the time. I have no problem removing `cur_dir`.

**Comment by BoPeng** [comment]
Thanks for the feedback. I am trying to make sure whatever I document this time is useful and intuitive, s othere could be a series of small changes to the remote task part of the code, hopefully nothing essential will be changed.
