### ISSUE TITLE
Py_Module autoinstall does not work if an older version exists

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1246]
To illustrate the problem:

```python
>>> from sos.targets_python import Py_Module
>>> Py_Module('rpy2>=3.0.1').target_exists()
ERROR: Version 2.9.4 of installed rpy2 does not match specified version >=3.0.1
False
>>> Py_Module('rpy2>=3.0.1', autoinstall=True).target_exists()
ERROR: Version 2.9.4 of installed rpy2 does not match specified version >=3.0.1
```

When `autoinstall=True` the 2nd line, I would expect the new version is installed to update the old one. 

To fix the issue we should add `-U` to the command below:

https://github.com/vatlab/SoS/blob/c0c338cde4d5be9e39b6a904b1ee820e5a5e26ab/src/sos/targets_python.py#L74

Is that right?

**Comment by BoPeng** [comment]
Yes

**Comment by gaow** [comment]
Okay the problem now is this line

https://github.com/vatlab/SoS/blob/c0c338cde4d5be9e39b6a904b1ee820e5a5e26ab/src/sos/targets_python.py#L78

because after version upgrade, the module will not be reloaded. So another round of `self._install` check will still fail. Apparently `importlib.reload` can check modules but the input cannot be a string, eg. `reload(rpy2)` is fine but not `reload('rpy2')`. I'm going to search for alternatives but please let me know if you have some immediate thoughts.

**Comment by BoPeng** [comment]
`-U` does not sounds right because it will always upgrade to the latest version, so 

```
Py_Module('rpy2==2.9.4')
```
will fail.

**Comment by BoPeng** [comment]
Fixed with test cases in 

https://github.com/vatlab/SoS/blob/d33e17f25aae2e1cd313694ea504c0d9502b0c30/test/test_python3_target.py#L80
