### ISSUE TITLE
max_running_jobs cannot prevent sos from submitting new jobs

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1248]
SoS currently submit new tasks if `submitting_tasks + running_tasks < max_running_job`,  here `submitting_tasks` are tasks that are collected from pending tasks but not yet submitted.

The problem is that `running_tasks` contains only `running` tasks when sos starts, so if there is a large amount of existing `submitted` or `pending` tasks, sos will still submit new jobs.

So it makes more sense to test all `pending`, `submitted` towards running jobs to avoid excessive submission of tasks.

**Comment by gaow** [comment]
Part of this [reverted patch](https://github.com/vatlab/SoS/commit/8f15807dd7cf472e23003427d64a2e23d7059c8e#diff-5481fe91f5039c19131add6e15af596cL229) is relevant to this ticket. But there is another part of the reverted patch seemingly to be meant for #1213 . Document it here as a reminder for further investigations.

**Comment by BoPeng** [comment]
Yes, the original implementation recognized that querying task status can be slow (e.g. you have more than 4000 tasks) so the task engine only checks the status of tasks that it submits, and make sure they are running ok. This can be problematic, for example, if a user submits tasks from different projects. Given that `sos status` is much faster than before (with cache), the patch tried to monitor all tasks, but somehow did not work.

**Comment by gaow** [comment]
I'm going through pending issues -- not sure if this was resolved (seems from your post above there are other complications) but from my recent experience SoS seems to honor `max_running_jobs` and controls size of my queue.

**Comment by BoPeng** [comment]
Yes, it should have been fixed.
