### ISSUE TITLE
Target unavailable false alarm

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1249]
I have this script MWE similar in structure to that in #1213 . But instead of having a large global variable I load those variables separately in each nested workflow. It should be equivalent but I get weird errors like

```
INFO: Target unavailable: sos_step("a_normal")
```

The MWE is here:

[target_mwe.tar.gz](https://github.com/vatlab/SoS/files/3069671/target_mwe.tar.gz)

to reproduce,

```
sos run test_load.sos
```

**Comment by gaow** [comment]
Okay, but there is still an exception going on, and the above example does not work. ... should I reopen the ticket?

**Comment by BoPeng** [comment]
What exception?

The exception is raised for `sos_step` missing because sos cannot parse 

```
depends: [sos_step('%s_%s' % (n2a(x[1]).lower(), x[0])) for x in data_io['depends']]
```

before the step started, and has to create the dependency dynamically. Then the exception is created and `workflow_executor` runs the steps ...

I did not try to complete the workflow.

**Comment by gaow** [comment]
> What exception?

The except is that INFO line complaining some target is not found. 

What I meant by a "false" alarm is because the complained missing target is in the script. But from your explanation it seems SoS does not know it exists because it is parsed dynamically? It makes sense, because my previous version:

```
depends: [sos_step('%s_%s' % (n2a(x[1]).lower(), x[0])) for x in IO_DB['depends']]
```

where `IO_DB` is a parameter in global section, actually works. Is that expected?

So here I merely try to use local variable `data_io` to elimiate the use of global variables. Now with the current `master` if you try this workflow, it simply hangs. This is not a good behavior either.

**Comment by BoPeng** [comment]
The `info` line was a debug message that I have just removed. The `sos_step` target is unknown, so it was passed to the executor and the executor executes the requested step. This part works ok but I need to check the hang behavior.

**Comment by gaow** [comment]
> because sos cannot parse ... before the step started,

If I explicitly use `sos_step()` it should be able to parse and create dependency beforehand? What if `data_io` is global variable? i‘m try to figure out the most efficient way to specify dependency -- by efficient I mean a method to make it easiest for SoS to create and execute the workflows.

**Comment by BoPeng** [comment]
SoS supports dynamic depends, which make the executor a lot more complex but we are almost there already so there is no reason to withdraw its support. I am trying to make `sos_step` static and see if the problem is caused by dynamic steps...

**Comment by BoPeng** [comment]
Another context switch bug...
