### ISSUE TITLE
Clear <defunct> workers

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1250]
Right now the master process sends a `None` signal to workers and let them kill themselves. However, this creates `<defunct>` processes because `p.join()` is not properly called, as described [here](https://stackoverflow.com/questions/45505981/multiprocessing-produces-defunct-process).

The problem here is that when **some** worker says I want work, and the master says I do not have any, please sucide, the master does not really know **which worker** is idle, and cannot `join()` it explicitly. Perhaps the `SIGCHILD` signal should be used.

**Comment by BoPeng** [comment]
@gaow The patch tries to join terminated processes (to free resource, avoid `defunct`) but I do not know if it will can avoid `defunct` process. Because there is a five second interval between sos pings workers, it ls likely that a terminated process can be defunct for 5 seconds before being released.

**Comment by gaow** [comment]
> , it ls likely that a terminated process can be defunct for 5 seconds before being released.

what I've observed is certainly longer than 5 secs so I believe it should have worked if I no longer observe long `defunct`. But currently cannot get through my workflows due to bugs reported in the other ticket ...
