### ISSUE TITLE
Use zstd instead of lzma for compression

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1257]
We currently use lzma to compress/decompress information in task files. However, when `params` gets large (a few megabytes), `lzma` becomes really slow. Since file size is less important than speed for task handling, we should switch to a faster algorithm. [zstd](https://github.com/facebook/zstd) is a more "fashionable" algorithm that claims to be faster. The only problem for its adoption is that it might not be available on some systems.

**Comment by gaow** [comment]
> The only problem for its adoption is that it might not be available on some systems.

We can always write customized class that uses whatever available via try catch, unless there is portability concerns?

**Comment by BoPeng** [comment]
Yes, that means for example, a zstd compressed task file cannot be executed on a sytem without zstd installed. Portability is important because task files are designed to be handled on different systems.

**Comment by gaow** [comment]
Does its Python binding ensures that the library itself is also installed? The performance benchmark looks promising.

**Comment by BoPeng** [comment]
We used `zlib` in v1, `lzma` now (v2 and v3), checking https://github.com/inikep/lzbench, we should really switch to `zstd` if possible. Not sure what `-1`, `-2` etc means though.

| Compressor name         | Compression| Decompress.| Compr. size | Ratio | 
| ---------------         | -----------| -----------| ----------- | ----- |
| lzma 16.04 -0           |    18 MB/s |    47 MB/s |    64013917 | 30.20 |
| lzma 16.04 -2           |    16 MB/s |    56 MB/s |    58867911 | 27.77 |
| lzma 16.04 -4           |  8.36 MB/s |    60 MB/s |    57201645 | 26.99 |
| lzma 16.04 -5           |  2.00 MB/s |    66 MB/s |    49720569 | 23.46 |
| lzma 16.04 -9           |  1.55 MB/s |    67 MB/s |    48742901 | 23.00 |
| lzmat 1.01              |    24 MB/s |   288 MB/s |    76485353 | 36.09 |
| zlib 1.2.11 -1          |    66 MB/s |   250 MB/s |    77259029 | 36.45 |
| zlib 1.2.11 -6          |    20 MB/s |   267 MB/s |    68228431 | 32.19 |
| zlib 1.2.11 -9          |  8.30 MB/s |   269 MB/s |    67644548 | 31.92 |
|**zstd 1.1.4 -1**         |  **242 MB/s** |   **636 MB/s** |    73654014 | 34.75 |
| zstd 1.1.4 -2           |   185 MB/s |   587 MB/s |    70164775 | 33.10 |
| zstd 1.1.4 -5           |    88 MB/s |   553 MB/s |    64998793 | 30.67 |
| zstd 1.1.4 -8           |    30 MB/s |   609 MB/s |    61021141 | 28.79 |
| zstd 1.1.4 -11          |    15 MB/s |   603 MB/s |    59518174 | 28.08 |
| zstd 1.1.4 -15          |  4.78 MB/s |   626 MB/s |    58005265 | 27.37 |
| zstd 1.1.4 -18          |  2.75 MB/s |   573 MB/s |    55288461 | 26.09 |
| zstd 1.1.4 -22          |  1.39 MB/s |   459 MB/s |    52718819 | 24.87 |

**Comment by gaow** [comment]
> we should really switch to zstd if possible

Apparently!!!

> Not sure what -1, -2 etc means though.

should be compression level? eg zlib's best is -9. What level did we use? A more fair comparison should look at the same compression ratio (the smaller the better) and compare speed. But if compression ratio 34% vs 24% really does not make a difference to our application then `zstd` is good to use.

**Comment by BoPeng** [comment]
I could use zstd under linux and mac, but windows is still the problem

```
(base) C:\>pip install zstd
Collecting zstd
  Downloading https://files.pythonhosted.org/packages/75/83/942faeb75d22eca94373dc93a816fdfa56f4018bef437894784c93662ff4/zstd-1.3.8.1.tar.gz (443kB)
    100% |████████████████████████████████| 450kB 2.8MB/s
Building wheels for collected packages: zstd
  Running setup.py bdist_wheel for zstd ... error
  Complete output from command C:\Users\bpeng1\AppData\Local\Continuum\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\bpeng1\\AppData\\Local\\Temp\\pip-install-cgewmeti\\zstd\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\bpeng1\AppData\Local\Temp\pip-wheel-xmv3e3z4 --python-tag cp37:
  running bdist_wheel
  running build
  running build_ext
  building 'zstd' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

  ----------------------------------------
  Failed building wheel for zstd
  Running setup.py clean for zstd
Failed to build zstd
Installing collected packages: zstd
  Running setup.py install for zstd ... error
    Complete output from command C:\Users\bpeng1\AppData\Local\Continuum\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\bpeng1\\AppData\\Local\\Temp\\pip-install-cgewmeti\\zstd\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\bpeng1\AppData\Local\Temp\pip-record-3u_m9bc9\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'zstd' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    ----------------------------------------
Command "C:\Users\bpeng1\AppData\Local\Continuum\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\bpeng1\\AppData\\Local\\Temp\\pip-install-cgewmeti\\zstd\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\bpeng1\AppData\Local\Temp\pip-record-3u_m9bc9\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\bpeng1\AppData\Local\Temp\pip-install-cgewmeti\zstd\
```

Because [conda zstd includes a windows binary](https://anaconda.org/conda-forge/zstd), it is likely that we could install it from conda though.

**Comment by gaow** [comment]
I think our case falls in the `small-data` mode: many small yet similar data-sets, that can help training the algorithm to compress better:

https://facebook.github.io/zstd/#small-data

It reads interesting!

**Comment by BoPeng** [comment]
I have implemented the zstd support in a zstd branch. However, initial runs of the issue_1 test does not show any performance gain in either time or file size. I suppose we need tasks with larger sizes to tell a difference.

```
(sos) [bpeng1@phn-w0073087372:~/.sos]$ ls -l tasks_lzma
total 120
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  4056 Apr 16 10:03 M1_06f822ac6764f8e0.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  4096 Apr 16 10:03 M1_3d15f437b16ab7fc.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  4064 Apr 16 10:03 M1_3dff9de3f6078f63.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  4076 Apr 16 10:03 M1_4e7f0c437479e3a0.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  4092 Apr 16 10:03 M1_6b2e769ba9347ee1.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  4072 Apr 16 10:03 M1_8a942f1c40e6f049.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  3864 Apr 16 10:03 M1_8be67b529c407518.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  3876 Apr 16 10:03 M1_944ffa5f4bae38ed.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  3824 Apr 16 10:03 M1_a0b39c940b9a7d34.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  3900 Apr 16 10:03 M1_ac2dae310d779ba3.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  3868 Apr 16 10:03 M1_b54e310f2dc216dc.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  3912 Apr 16 10:03 M1_b910b13cddfeb1ae.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  4084 Apr 16 10:03 M1_ef205377085fb312.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  4064 Apr 16 10:03 M1_f52057ce09cba924.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  3242 Apr 16 10:03 status_cache.pickle
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users     0 Apr 16 10:03 status_cache.pickle_

(sos) [bpeng1@phn-w0073087372:~/.sos]$ ls -l tasks_zstd
total 144
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  4071 Apr 16 10:01 M1_06f822ac6764f8e0.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  4102 Apr 16 10:01 M1_3d15f437b16ab7fc.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  4064 Apr 16 10:01 M1_3dff9de3f6078f63.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  4104 Apr 16 10:01 M1_4e7f0c437479e3a0.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  4112 Apr 16 10:01 M1_6b2e769ba9347ee1.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  4081 Apr 16 10:01 M1_8a942f1c40e6f049.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  3834 Apr 16 10:01 M1_8be67b529c407518.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  3882 Apr 16 10:01 M1_944ffa5f4bae38ed.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  3789 Apr 16 10:01 M1_a0b39c940b9a7d34.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  3902 Apr 16 10:01 M1_ac2dae310d779ba3.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  3872 Apr 16 10:01 M1_b54e310f2dc216dc.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  3903 Apr 16 10:01 M1_b910b13cddfeb1ae.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  4092 Apr 16 10:01 M1_ef205377085fb312.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  4062 Apr 16 10:01 M1_f52057ce09cba924.task
-rw-r--r--  1 bpeng1  MDANDERSON\Domain Users  3242 Apr 16 10:01 status_cache.pickle
```

**Comment by BoPeng** [comment]
Given your blog and the train mode API, it is possible to train the algorithm  to store a dictionary under `~/.sos/` but it does not seem to worth the trouble now.

**Comment by gaow** [comment]
> I suppose we need tasks with larger sizes

Can we easily modify some of the stress tests to have larger size, in particular the `issue_1216`? we can modify it to have a big global variable. But as you might have noticed already, that example is slow even when all runs are trivial. So I am not sure if it has anything to do with compression methods.

**Comment by BoPeng** [comment]
My understanding is that there is no benefit for a majority of cases of small task files, unless we can implement some training mode later. I think this belong to "stress-test" so we can fabricate a few large tasks when needed. I do not have time for this right now though.

**Comment by gaow** [comment]
> My understanding is that there is no benefit for a majority of cases of small task files, unless we can implement some training mode later. 

Agreed. We can table this. My main point is that I'm trying to understand behavior of `stress-test/issue_1216` trying to see what is the real blocker for it and whether or not compression algorithm is the key. The bigger picture problem is the fact that it takes > 8hrs to run trivial jobs. But this is discussion for another ticket.
