### ISSUE TITLE
Requested number of cores for master task

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1259]
Currently for a master task that requests `trunk_size=10`, `trunk_workers=2`, `ncores=4`, sos sets the required cores to `2 * 4 + 1` with `2 * 4` being the cores requested for two workers, and `1` being the task process that monitors the subtasks.

The problem here is that the the task manager requires some CPU/RAM, but perhaps not a core, and for the non-master tasks that requested `n` cores, we request `n` for the task, although the task manager is supposed to use some resource.

So this involves the question how clusters control `ncpus`. If it enforces to `ncpus` processes, `+1` might have to be added (and `ncpus` for regular tasks might need to be adjusted as well). If it basically means "suggested number of cores" for resource allocation purpose and the task can create many small-load processes, we should not add this 1 process.

**Comment by gaow** [comment]
Yes we should not `+1` because if all machines a cluster have are 8 cpu and users specify 8 cores, then we in fact put in 9 cores and none of the node will have the correct configuration. So it's good to see that patch. I'll test it to see if that solves some issues we have.

**Comment by BoPeng** [comment]
The problem was that with `trunk_workers > 1`, the sos process will be actively dispatching tasks to and collecting results from the workers. I do not think the cluster will actually count the number of processes, perhaps even not monitor `nCPU *100%` CPUs, so it should be safe to ignore the sos process.

**Comment by BoPeng** [comment]
A similar issue is that sos will take `n+1` processes for `-j n` because the master sos process will be taking one process, and will in many cases be the busiest one.

**Comment by gaow** [comment]
It's okay that `sos` command uses one more CPU core than it claims, same with `-j`. It's just putting this `n+1` in the template hard-coded can mess up the job scheduling, for reasons I previously argued about. I think it is therefore safer to put `n` not `n+1` in the template.

It seems to work well and fixed a bug i reported in DM!
