### ISSUE TITLE
Light-weight alternative to Celery

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#126]
https://github.com/nvie/rq

Seems very promising, at least the project has been under development for 5 years with a lot of developers. It does not seem to have complex task dependency etc, but we can have a model where SoS handles all dependencies, and dispatch tasks when dependencies are met.

**Comment by BoPeng** [comment]
Something between rq and celery (https://github.com/pricingassistant/mrq).

**Comment by gaow** [comment]
Dashboard of `mrq` is much nicer than `rq`! I think that gives us good enough reason to give it a shot if the code migration is as easy as the authors claim.

**Comment by BoPeng** [comment]
Support for MRQ (and other task systems) should be relatively easy, but we do need to have something set up to test.

I suppose these have to be developed when there is a real need for such systems (even from users). Otherwise our support would be incomplete and buggy.
