### ISSUE TITLE
Suppress output of tasks

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1261]
For a simple workflow

```
input: for_each=dict(i=range(5))

task:
print(i)

```

The result would be something like

```
$ sos run test
INFO: Running default: 
INFO: 22a671589ef54214 started
0
INFO: 22a671589ef54214 completed
INFO: 0e0838c5b2ddadc5 started
1
INFO: 0e0838c5b2ddadc5 completed
INFO: 1a977d87d4eaa33e started
2
INFO: 1a977d87d4eaa33e completed
INFO: 3ec5b60c90364ca4 started
4
INFO: 3ec5b60c90364ca4 completed
INFO: 3030e3480697e80d started
3
INFO: 3030e3480697e80d completed
INFO: Workflow default (ID=8de7ed36022e2c5c) is executed successfully with 1 completed step, 5 completed substeps and 5 completed tasks.
```

This is more or less ok because there are few tasks. However, if the outputs are long, the output of tasks will be mingled together and the task status will be washed away. The problem looks even worse in SoS notebook because the tasks tables will be separated and it would be difficult to get the overall status of the tasks.

Because one of the key motivations of having tasks is to run multiple tasks in parallel, and to encapsulate the executions, it makes sense to capture outputs in `task` files only and do not display them in terminal.

**Comment by gaow** [comment]
I'm not sure ... because when submitted to cluster there will be files to keep these stdout and stderr. It seems to me the only time at least I use this would be running on a desktop which dos not make sense to use `task` anyways. So maybe it is not an issue?

**Comment by BoPeng** [comment]
I also use remote execution (remote process queue), in which case the output is also returned.

Since you only use tasks with PBS, this will be a non-issue for you so I will make the change. The problem here is that we will need better ways to retrieve output from tasks. Currently `sos status task_id -v4` can show it with others, but something like

```
sos status task_id --stdout
```
might be better.

**Comment by gaow** [comment]
Sure ... I'm just saying there might be appeals not to hide it, eg, when people do `-v0`. If it can be a non-default option then I think it is more justifiable.
