### ISSUE TITLE
[BUG] Data exchange between Octave and Python3 

### ISSUE THREAD

**Issue by agahkarakuzu** [vatlab/SoS#1262]
Hi SoS team! 

**When I try to pass a 3D matrix (of any  type) from `Octave` to `Python3` subkernel, I run into the following problem:** 

![Screenshot from 2019-05-02 09-08-35](https://user-images.githubusercontent.com/9632322/57077390-f1069200-6cb9-11e9-8eea-91cbf2b2a157.png)

> I thought that a smaller 3D matrix would make it, but it still fails: 

![Screenshot from 2019-05-02 09-14-05](https://user-images.githubusercontent.com/9632322/57077708-b7825680-6cba-11e9-8b60-a7e4b0681cde.png)

> It works properly, when I reduce it to a 2D matrix by discarding one dimension:

![Screenshot from 2019-05-02 09-11-47](https://user-images.githubusercontent.com/9632322/57077575-670af900-6cba-11e9-86b9-5ecf6bf02f05.png)

>  Or when I collapse two dimensions into one:

![Screenshot from 2019-05-02 09-16-34](https://user-images.githubusercontent.com/9632322/57077879-1cd64780-6cbb-11e9-8696-3bab1af5f32f.png)

I would like to note once again that this problem occurs for any data type. 

***

* Hoping that passing the 3D matrix in vector form would do the trick, I did the following 

![Screenshot from 2019-05-02 09-21-56](https://user-images.githubusercontent.com/9632322/57078188-c4ec1080-6cbb-11e9-810d-bbe5c68e5e74.png)

However, it gets stuck for a long time and I had to restart the kernel on every attempt.

For now, I will shrink my 3D `Octave` matrices into 2D and reshape them back to their original form in `Python3` . I hope that this issue can help solve the problem. Please let me know if you need further details! 

## Environment 

* Ubuntu 18.04.2 running on Docker 
* Python 3.7.3 
* Octave 4.2.2
* jupyter 4.4.0
     * notebook 5.7.4
* sos 0.19.8
     * sos-bash 0.18.1
     * sos-javascript 0.18.0
     * sos-julia 0.18.2
     * sos-matlab 0.18.2
     * sos-notebook 0.19.6
     * sos-python 0.18.1
     * sos-r 0.19.1
     * sos-ruby 0.18.1
     * sos-sas 0.18.0

**Comment by BoPeng** [comment]
Many thanks for your detailed report. 3D matrix is not yet supported but let me see what it takes to support it.

**Comment by agahkarakuzu** [comment]
Thank you for the fast reply @BoPeng! Having support for 3D matrices would be really useful, let me know if I can be of help.

**Comment by BoPeng** [comment]
@agahkarakuzu 

What is the best way to convert python mixed list to Octave? Right now

```
a=[1.4, True, "asd"]
```
is converted as `cell` type

```
{
  [1,1] =  1.4000
  [2,1] = 1
  [3,1] = asd
}
```

which looks like 2d to me. Is there a 1d cell?

**Comment by mathieuboudreau** [comment]
I think 1D cell arrays will always display a singleton dimension (i.e. appear to be 2D).

Example from Octave:

```

octave:2> a=cell(2,1)
a =
{
  [1,1] = [](0x0)
  [2,1] = [](0x0)
}

octave:3> a=cell(1,2)
a =
{
  [1,1] = [](0x0)
  [1,2] = [](0x0)
}

```

See: [`cell` MATLAB documentation](https://www.mathworks.com/help/matlab/ref/cell.html)

**Comment by BoPeng** [comment]
Thanks, this is what confused me.

**Comment by BoPeng** [comment]
```
disp('ab\nd')

ab\nd
```
So `\n` is not newline?

**Comment by mathieuboudreau** [comment]
Not for the MATLAB-specific `disp()` function unfortunately. You can use that syntax for new lines with `fprintf()` or `sprintf()` though in MATLAB I believe.

**Comment by BoPeng** [comment]
I see.

![image](https://user-images.githubusercontent.com/9889312/57116829-3f994800-6d1d-11e9-8f33-43ebbc58ab37.png)


Is there a way to convert integer to integer string (`123` to `"123"`) and float to float string with high precision (`123.1` to `"123.100000"`)? Right now `sos-matlab` uses default `num2str`, which converts integer ok, but only get `.4` precision 
```
num2str(1.123456789)
ans = 1.1235
```
However, adding precision will display integer as float

```
num2str(1, '%.13f')
ans = 1.0000000000000
```

**Comment by mathieuboudreau** [comment]
You can specify the number of significant digits for floating point values of `num2str` by adding that number as a second argument.

e.g.

```

octave:4> a=1.2435678798654
a =  1.2436
octave:5> num2str(a,5)
ans = 1.2436
octave:6> num2str(a,1)
ans = 1
octave:7> num2str(a,3)
ans = 1.24

```

Documentation: https://www.mathworks.com/help/matlab/ref/num2str.html#btf97wk

**Comment by BoPeng** [comment]
Thanks! How to detect 3d array?

![image](https://user-images.githubusercontent.com/9889312/57117745-2051e900-6d24-11e9-9d7b-baee09a33db8.png)

**Comment by mathieuboudreau** [comment]
Using `size()`

e.g.

```

octave:9> a=zeros(2,3,4)
a =

ans(:,:,1) =

   0   0   0
   0   0   0

ans(:,:,2) =

   0   0   0
   0   0   0

ans(:,:,3) =

   0   0   0
   0   0   0

ans(:,:,4) =

   0   0   0
   0   0   0

octave:10> size(a)
ans =

   2   3   4



```

**Comment by BoPeng** [comment]
I have pushed a patch, please install the latest trunk with command

```
pip install git+https://github.com/vatlab/sos-matlab
```
and let me know if it works for you. You might need to remove local `sos-matlab` in case the new version does not override the old one.

**Comment by BoPeng** [comment]
@agahkarakuzu Thank you very much for your bug report and help. I rewrote the tests using a recently introduced test framework and was able to identify and fix a few problems (e.g. precision of passing double variables) with this module, and added support for `ndarray`. I have released `sos-matlab` 0.18.3 but of course feel free to let me know if you notice any problem.

BTW, I noticed a bug with the [`dataframe` package of octave](https://wiki.octave.org/Dataframe_package). Namely the package would ignore the first data line if the csv file contains all strings. I could not find how to contact the author but perhaps you can do it if you are an avid user of octave:

[csv.zip](https://github.com/vatlab/SoS/files/3142303/csv.zip)



![image](https://user-images.githubusercontent.com/9889312/57142806-14e1da80-6d83-11e9-9248-f33d5a078abf.png)

**Comment by agahkarakuzu** [comment]
@BoPeng you are amazing! Thank you so much for fixing the problem this quick, I will try asap and will let you know.

Sorry I was not responsive for the previous comments, big thanks to @mathieuboudreau for the inputs :rocket:

**Comment by mathieuboudreau** [comment]
@BoPeng FYI, the proper location to report bugs for Octave is here: https://savannah.gnu.org/bugs/?group=octave

**Comment by BoPeng** [comment]
It is a pain to submit to this system, but it is done now https://savannah.gnu.org/bugs/index.php?56263
