### ISSUE TITLE
Signature check performance issue & `skip` mode

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1263]
I think we've discussed it before and decided that we'd like to fail early and completely if there is an error in anywhere in the DAG. But someone is currently arguing against me about it, because it is very frustrating that for large workflows (benchmarking) for some errors occurring very late in the workflow, then rerun it, wait for an hour to get to that error to see if the fix works (because other steps takes very long time to verify the signature etc). 

The latter issue, performance of cluster job checks, is a separate one and is a long standing one, although big progress has been made in the past. But before revisiting that one, can we rethink of the "fail early" idea and possibly at least allow for other parts of the DAG to complete before fail?

**Comment by BoPeng** [comment]
I have been thinking about the signature performance problem and realized that as long as we keep "something" in database, either time stamp or signature, it will be some overhead to retrieve the information from database etc, and will be a bottleneck.

If the user knows that no existing files or parameters have been introduced and he just want to go back to the previously failed step, can we introduce some light-weight check, such as, passing as long as result file exists (not empty or newer than input as potential check)? Such checks do not involve the master process and can potentially be much faster.

**Comment by gaow** [comment]
> passing as long as result file exists

That'd be great feature to have! I suppose we can use a `-s ...`? Does it only check file existence or also time stamp? Or does not matter because it does not involve master and can be fast either way?

**Comment by BoPeng** [comment]
Yes, `-s ignore` just ignores signatures and run, I am not sure how to call this one.

The basic idea is not to compare with any stored signature and just check local files. Checking if output files are newer than input is probably reasonable but consider the case that changing a value or adding a case in a config file might cause everything to rerun.

**Comment by gaow** [comment]
> The basic idea is not to compare with any stored signature and just check local files. 

Yes i understand, great!

> consider the case that changing a value or adding a case in a config file might cause everything to rerun.

If the same is going to happen to make based workflow systems eg GNU Make or snakemake, then I do not think it is an issue at all, because it is expected for lightweight signatures.

How about `-s light`?

**Comment by BoPeng** [comment]
Perhaps

```
sos config --set signature md5
```
vs
```
sos config --set signature timestamp
```

**Comment by gaow** [comment]
So it can be global settings, and users can opt to have `make` equivalent? That'd be good idea.

**Comment by BoPeng** [comment]
Also touch mode of [GNU Make](https://www.gnu.org/software/make/manual/html_node/Instead-of-Execution.html)

> ‘--touch’
> “Touch”. Marks targets as up to date without actually changing them. In other words, make pretends to update the targets but does not really change their contents; instead only their modified times are updated.

We do not really want to touch the file if it is out to date though.

**Comment by BoPeng** [comment]
Timestamp has this [low resolution problem](https://www.gnu.org/software/make/manual/html_node/Special-Targets.html)

> .LOW_RESOLUTION_TIME
> The high resolution file time stamps of many modern file systems lessen the chance of make incorrectly concluding that a file is up to date. Unfortunately, some hosts do not provide a way to set a high resolution file time stamp, so commands like ‘cp -p’ that explicitly set a file’s time stamp must discard its sub-second part. If a file is created by such a command, you should list it as a prerequisite of .LOW_RESOLUTION_TIME so that make does not mistakenly conclude that the file is out of date.

**Comment by gaow** [comment]
I think this is our `-s build` because up to date in our definition is signatures up to date. We can possibly update the time stamp instead, if global mode is set to timestamp?

**Comment by gaow** [comment]
I think it is fair enough that we by default have the signature system, which in fact is a feature of SoS. But just to quickly rerun we can allow for using time stamps. 

Now thinking about it, conceptually they are still different ... I'd say `sos config` will not work. We want to skip existing files based on time stamp not signature. But for new files generated, we still should use signature system. And we always have it by default. So an option to `-s` is better I think. For a fresh run without any output files, users do `-s lite` they still get all the signatures generated. In other words we do not need a `make` replacement, but just a lite check is enough.

**Comment by BoPeng** [comment]
> update the time stamp instead, if global mode is set to timestamp?

Yes, I agree this is the equivalence of build with timestamp mode.

In my side of work when I develop workflows, many middle files come and go and the workflows change a lot so I tend to use md5 to make sure if the intermediate files are intact, and I do not mind if it is out of date. For example, an input file might have been re-generated, re-downloaded, and a step will not be rerun if it is content is not changed.

The scenario will be different if running a mature workflow where input and or workflow will not be changed. Signature will be needed for re-run the workflow but there is less a concern for corrupted files etc. I think timestamp is probably enough for such a case.

**Comment by gaow** [comment]
Sorry not sure if I understand it completely: so you agree that we should a) still keep one default mode, that is, based on signature, and use timestamp as a check; or b) to support a different, independent mode based on timestamp? I think b) is what you were suggesting with `sos config` but I do not think it is good idea and we can also solve our problem using a).

**Comment by BoPeng** [comment]
I was just listing the pros and cons of two systems. I agree that in most cases users can use md5 for correctness and only resort to timestame in case of rerun large workflows. Still not sure if `-s lite` is a good name though.

**Comment by gaow** [comment]
Then `-s timestamp` because it can also be viewed as a verb, and at least will change time stamps of the files involved.

**Comment by BoPeng** [comment]
How about
```
-s fast
```

`timestame` is a bit too long to type. My problem with `lite` is that it is not (I think) a proper word for `light`, more used in thing like `bud lite`.

**Comment by gaow** [comment]
Oh I thought you wanted to look for a verb not a adjective. Then `fast` is okay as long as we explain what it does. I was having in mind `sqlite` but not sure what `bud lite` is? You meant to say [`budlight`](https://www.budlight.com/)?

**Comment by BoPeng** [comment]
Ohmm, there is `Miller Lite` but `Bud Light`. Any, dictionary of `lite` all related to `low-fat`, `low-sugar` stuff, not the `light-weight` `fast` we want.

**Comment by BoPeng** [comment]
If you want a verb, the only thing I can think of is `-s rush`.

**Comment by BoPeng** [comment]
ok, the `fast` mode is in but I am still thinking of a better name. Test and let me know how it works for your large workflows.

**Comment by BoPeng** [comment]
How about `-s resume`? It means it should be used to re-run failed workflows. Just a suggestion.

**Comment by gaow** [comment]
Cool -- i'll try it on large workflows this evening. Fast is a verb but means different things : ) I cannot think of a good verb either. I think `fast` is good enough :)

**Comment by gaow** [comment]
For a workflow involving >40K files it took 163 secs to fast them over. This is quite nice. 
the message is a bit confusing though:

```
INFO: Ignore susie_scores (index 0) with existing output.
```

What does `(index 0)` mean? It only checked one index? Or actually it has checked it all but only showing one line? That case `(index 0)` should be removed.

**Comment by BoPeng** [comment]
It means substep index. Could remove if there is only one substep.

**Comment by BoPeng** [comment]
Message updated to 

```
INFO: Ignore step default (substep 0) with existing output.
```

How about change to 

```
-s skip
```
and
```
INFO: Skip step default (substep 0) with existing output.
```
`skip` here basically means `skip` signature check, or `skip` steps with existing output.

**Comment by gaow** [comment]
I see, that is right. So this is a nested workflow like 

```
[master]
sos_run('child')

[child]
parameter: replicate = [1,2,3,...]
```

What used to happen is that all substeps in child are checked for signature so the screen output is long and mostly dominated by indices with child. It seems now they are all ignored properly without having to show them. I then tried to remove just one file from a step in the nested workflow, I indeed get a number of prompts like: `Ignore ... (index ...) with existing files`.

> Could remove if there is only one substep.

That'd be great. It makes sense to remove `index=0` for steps with one substp.One additional comment is can we make it similar to what we have previously? 

```
INFO: ``some_step`` (index=...) is ``ignored`` due to saved signature
```

where `some_step` and `ignored` are in green. And here we should replace `due to saved signature` with `after timestamp check` or something like it?

**Comment by gaow** [comment]
Hmm our emails crossed. Yes `skip` would be fine! But the message is best to be consistent with the default. I think the old message for default mode was good. That is, `index` (shorter than `substep`). And with green colors explaining why they are ignored.

**Comment by BoPeng** [comment]
The last patch does not apply skip mode when there is `sos_run` in the step because otherwise the entire subworkflows could be ignored. There are two cases

```
[step]
sos_run('other')
```
is not effected because `skip` only applies if there is defined output, so the subworkflow will be executed.

```
[step]
output: 'whatever'
sos_run('other')
```
previously `skip` mode will only check `whatever` and skip `other`, but now `other` will be executed. The underlying assumption is that the nested workflow might call other workflows and `output` here might not reflect all the outputs.

**Comment by gaow** [comment]
Yes I see that makes sense. So we'll have the same (amount of) screen output as when `-s default` is used. But text will pop up much faster -- let me see if it is an issue.

**Comment by gaow** [comment]
They all skip quite well now. But I'm experiencing some interesting halt which i previously thought was because of having to write signature database (will detail it later). But now I think it is not entirely the case. The computation time doubled compared to the first patch with `fast`, because nested steps are looked into. And mostly on these halts. 

This also relates to in default mode when `-s default` checks signatures. I observe for some steps instead of submitting jobs right away it halts for even up to 20 minutes before it does anything. Not sure if that is usual. 

Maybe it is worth showing with stress test examples?

**Comment by BoPeng** [comment]
https://github.com/vatlab/stress-test/issues/5

**Comment by gaow** [comment]
I'll close this ticket for now and use another one to discuss what the ticket was initially created for, that is, discussion on finishing through the DAG in the presence of errors.

**Comment by gaow** [comment]
A couple of quick questions / comments:

1. When scripts are changed, would `-s skip` rerun the steps involving changed script?
2. Since we are still experiencing slowness in `-s default` I wonder if `-s skip` can be made more appealing by first check time stamps, and for cases time stamps mismatch, further check signature to decide whether or not to rerun, without involving workers?

**Comment by BoPeng** [comment]
`-s skip` does not check script change, which is the biggest problem and why it is only suitable for rerun failed script. The problem here is that the old script needs to be saved somewhere and `-s skip` only checks local files.

I would prefer removing `-s skip` after improving performance of `-s default` but right now it seems that both zmq and md5 can be slow. The former asks checking signatures in step worker and the latter asks checking signatures in substep worker. More benchmark is needed though.

**Comment by gaow** [comment]
I see. Then it makes sense to not do 2 that I proposed earlier, and try improve `-s default` down the road.

**Comment by BoPeng** [comment]
Note that right now sos builds signature with md5 (which can be slow but almost always done in parallel), but [check filesize and timestamp](https://github.com/vatlab/SoS/blob/master/src/sos/targets.py#L784) and only checks md5 if they are different, so in a majority of time file signature check should be fast. I am not sure if this is the case for our previous benchmark but I am reasonably confident that checking signatures sequentially in step worker should be good.

**Comment by gaow** [comment]
In other words, if file size and time stamps are the same then file signature check will be avoided, thus removing the need to use workers to check for potentially large output? So now we stick to the "master" process without zmq communications? It sounds reasonable, but how about tracking script change? Should I understand it as this: in current default mode the step worker checks sequentially file size + time stamp + script HASH and skip if they all agree. If time stamp do not agree then check file HASH, but will rerun anyways if file size or script HASH do not agree?

**Comment by BoPeng** [comment]
> In other words, if file size and time stamps are the same then file signature check will be avoided, thus removing the need to use workers to check for potentially large output? 

Yes. That is to say, almost all the time, the validation part does not involve md5.

> So now we stick to the "master" process without zmq communications? 

Yes, this is what I am doing, but I am adding a "distributed" mode that forces signature check to be done at substep workers (involves zmq), just for comparing performance between `skip`, `default` and `distributed` modes in real world examples.

> Should I understand it as this: in current default mode the step worker checks sequentially file size + time stamp + script HASH and skip if they all agree. If time stamp do not agree then check file HASH, but will rerun anyways if file size or script HASH do not agree?

Yes, you are right. So MD5 is used as a last resort because most changes to files will cause change of file size.

**Comment by BoPeng** [comment]
Note that currently the `build` mode is also done sequentially, which can be a problem because build will calculate md5. I do not want to add a `build_distributed` mode, so perhaps I will just force `build` to be done by substep workers.

**Comment by gaow** [comment]
It all sounds reasonable. I'm just thinking of 2 things:

1. If we make this new default the default what could be the pitfall? That is, how much more vulnerable it is compared to the old default, if it is indeed more vulnerable? Trying to brain storm corner cases.
2. Can worker level signature checks be done in parallel locally?

**Comment by BoPeng** [comment]
1. Not an issue as long as all tests pass, which is NOT the case now.
2. Yes, potentially these are network/filesystem intensive jobs and are ideal for multi-threading. That is to say, we could use multiple threads to submit substeps to substep workers. I do not have time for this now but we can create a ticket for trying this later.

**Comment by gaow** [comment]
Great. I'll remember to create a ticket for 2 once 1 is verified. "Not an issue as long as all tests pass" -- I'm proud of all you did for the unit test suite we have!
