### ISSUE TITLE
Missing pulse file warnings, and error after

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1264]
The following is still happening quite often:

```
WARNING: Task M100_ab7d16db90d084cd considered as aborted due to missing pulse file.
```

and it leads to errors that stops the entire workflow (also related to #1263). But in reality all those relevant steps are completed. It seems some communication issues, but it makes the entire workflow fail. Combined with #1263 for large workflows and the time it takes to reach the rerun point, this can be very frustrating to users.

**Comment by gaow** [comment]
Just ran into this again. The outcome looks like:

```
Failed to get results for tasks 5dbfa89b768a6aca, f71acc2e0ed207a4, 4a7f342b037098fc, 1ae6ea10a267390f, db936a54e4dfb610, d1d65a1e26c521d2, b9d8c75ba3c940c3, 5700f53dab31a406, edaf88c3f32bb8c5, add9095f014c6102, b73ca89f11a2dcfa, 6c5a33e926241e66, c9e549ee9df11199, c874e2d31d3c4468, 7a987959bb9e2bb7, aa27c939a714ed09, 7e2a0e0cc19bf935, 2eb185f235fb2100, 849ecbc030eb706a, d12c9ae941fce6da, 5837e6b7273cd832, 4badf63eb371bb17, cc3a67b71c1c0cdc, b1964edc86d35dee, d096fe0474150d46, 50cb458640cede62, dc0998b16aa31f3d, d2295dde334a91ab, d1cd1327c4d135b5, bdfa837ae845962c, 8519348bd50f01d5, 8baefa603096936b, f83a89d5a344f777, c7f97e93809e64f7, a61bb4561a4c1010, d0e8c20a60975e3a, 3a5f0ad1bc1ef7a1, b0aef44fd9da5337, e8265ee1a8d4a94a, aee625e7e48899b9, e3037d380c587e7a, 004f4c9ec02eb267, a424805330c9ce02, 4e0a514ea1cdfe08, db0c248513c09074, 52a3e8ca9e265354, 16a1452f014af81e, 7553cbdc37cfee3d, d911adbe49234296, 0eb140e3a64ab77b
```

and checking with `status`, 

```
sos status f71acc2e0ed207a4 -v4

f71acc2e0ed207a4    missing
```

but the result files are in place -- that is, computation seems complete. It is for some reason miscommunication with the PBS system. I wonder if trying it multiple times can help? The upside is now that we have `-s skip` rerunning is a lot faster.

**Comment by BoPeng** [comment]
The `Failed to get results for tasks 5dbfa89b768a6aca, f71acc2e0ed207a4, `, you are not supposed to see the tasks if they are subtasks of a master one.

I checked the relevant source code and the status of task is [changed to `completed` before the `.pulse` file is removed](https://github.com/vatlab/SoS/blob/master/src/sos/tasks.py#L675). However, the entire logic is inside a `with` block so it is likely that the status is not written to disk when the pulse file is removed. I have submitted [a patch](https://github.com/vatlab/SoS/commit/ffdeb0d7187275b445c8504cfc140fb4f9042bed) although I am not sure if this is the source of problem.

**Comment by gaow** [comment]
Thanks -- I've updated, and will see if it still happens.

> However, the entire logic is inside a with block so it is likely that the status is not written to disk when the pulse file is removed.

Sounds plausible ... but would be really weird on Python's end to have a somewhat random behavior over this case. Will see.

**Comment by BoPeng** [comment]
It is not python's fault. If what I thought was correct, Python closes the file at the end of the `with` block, so if another process get the status after the pulse file is removed and right before the `with` block exits, it will see the task as still `running`. This should rarely happen but on heavy load with thousands of tasks this will probably happen at high probability.

**Comment by BoPeng** [comment]
Please close the ticket if you no longer notice the issue.

**Comment by gaow** [comment]
A follow up on the problem -- the warning still shows up like

```
WARNING: Task M40_166b25d99d2a549f considered as aborted due to missing pulse file.
```

there is nothing funky about `sos statsus M40_166b25d99d2a549f`. But when i look into the standard error there is this line in it not shown in `sos status`:

```
WARNING: Task M40_166b25d99d2a549f aborted
/tmp/slurmd/job62519255/slurm_script: line 13: 23749 Killed                  sos execute M40_166b25d99d2a549f -v 2 -s build
```

So it looks like SoS indeed captured the slurm exception but put it inside `stderr` file. Later the warning shown on the screen is about missing pulse which reads confusing.

**Comment by BoPeng** [comment]
Ohmm, task aborted but the status is still shown as running, while the
pulse was removed. Something is not right here. Let me check.

**Comment by gaow** [comment]
@BoPeng thank you! Here is outcome of `sos status`:

```
[MW] sos status M40_166b25d99d2a549f
M40_166b25d99d2a549f	bea9d36b1b500b8c extract extract_ENSG00000258068.1.Multi_Tissues extract_ENSG00000258081.3.Multi_Tissues extract_ENSG000Ran for 0s    	aborted
```

but the aborted complaint should blame the line in slurm_script not about missing pulse.

**Comment by BoPeng** [comment]
The patch simply set the status to `aborted` but I still cannot figure out the event path that leads to a task file with `running` status and with missing `pulse` file. Looking back, our "self-monitored task execution" model is very complex compared to other "remote controlled task execution"  models, but at least this is how sos differs from them (e.g. dask).

**Comment by gaow** [comment]
> but I still cannot figure out the event path that leads to a task file with running status and with missing pulse file

`sos status` does show the status as `aborted` from my earlier thread:

```
M40_166b25d99d2a549f	
bea9d36b1b500b8c extract extract_ENSG00000258068.1.Multi_Tissues extract_ENSG00000258081.3.Multi_Tissues extract_ENSG000
Ran for 0s    	aborted
```

This is after I see warning for missing pulse the I look at the status of the file.  If you use `-v4` to see the status, everything looks good and only from the `stderr` file you can see it is killed by SLURM. I think the reason is that the job was aborted not because of the running script but because of SLURM kill externally?

**Comment by BoPeng** [comment]
The problem is that Slurm could kill the task process, but should not remove the `.pulse` file. The event chain should be 

1. slurm kills the shell script, thus the `sos execute` command, thus the monitoring thread, so everything halts.
2. The `sos status` process, when it queries the status of the task, detects that the `pulse` file has not been updated for more than 1 minute, and declare it dead by modifying task status and remove `pulse` file.

Perhaps slurm was more gentle and sent a `term` signal and allowed `sos` to respond and clean up, but I could not see how.

Perhaps I should have mimicked this process by submitting something and use `qdel` (or slurm equivalence) to kill the task.

**Comment by gaow** [comment]
> Perhaps slurm was more gentle and sent a term signal and allowed sos to respond and clean up, but I could not see how.

Do you think it will help if we can reproduce the behavior? I can try to create some test processes where the actual memory exceeds the requested and we see what happens after SLURM's kill signal ; maybe over the weekend.

**Comment by BoPeng** [comment]
OK, I have reverted the patch and will investigate more. I never was able to reproduce this so it would be helpful if you can reproduce it with SLURM.

**Comment by gaow** [comment]
I cannot reproduce it 100% but if I change the example under `~/tmp/test/test.sos` to use 8GB memory yet only request 2GB I see this in the stderr:

```
[MW] cat M5_c1f34c42f69c15d9.err
INFO: M5_c1f34c42f69c15d9 started
INFO: All 5 tasks in M5_c1f34c42f69c15d9 failed
slurmstepd-midway2-0312: error: Detected 622 oom-kill event(s) in step 62628004.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
```

and on the screen,

```
WARNING: Task M5_708c41b93b357e32 considered as aborted due to inactivity for more than 79 seconds.
WARNING: Task M5_0e2695d1e0ac20f4 considered as aborted due to inactivity for more than 80 seconds.
WARNING: Task M5_4989ffd2813f13c1 considered as aborted due to inactivity for more than 79 seconds.
WARNING: Task M5_e85e1ac3bd3edd57 considered as aborted due to inactivity for more than 85 seconds.
```

Not so much about missing pulse, but do you think this is also helpful? Notice that the error message this time is very specific (about memory) unlike in threads above it just got killed. However the message does not show in `sos status -v4` and the WARNING does not hint directly to the problem.

**Comment by gaow** [comment]
So the point here is that the `aborted` status is at least documented properly. I just cloned the current `master` where you've fixed messages and tested again. It is now:

```
WARNING: Task M5_416f99dd6d86191e inactive for more than 83 seconds, might have been killed.
WARNING: Task M5_f57b0d9d887b5867 inactive for more than 89 seconds, might have been killed.
```

alhtough the actual message is still in the `err` file not `sos status -v4`

**Comment by BoPeng** [comment]
You were reproducing the task killed behavior, not the missing pulse file behavior.

**Comment by gaow** [comment]
> You were reproducing the task killed behavior, not the missing pulse file behavior.

Last time task killed is what seems to have triggered missing pulse. But now I have difficulty triggering it.

**Comment by BoPeng** [comment]
I am analyzing 900+ samples and having trouble in identifying failed samples. At least the master task should summarize failed sub tasks.

**Comment by BoPeng** [comment]
Basically, previous we collect sub stdout to master stdout and substderr to master stderr, right now we collect sub stdout and stderr to master stdout if the subtask is completed, and both to master stderr if the task is failed.

**Comment by gaow** [comment]
Let me reuse this ticket and separate part of discussion in https://github.com/vatlab/sos/issues/1321#issuecomment-555558992 to keep tickets more focused:

> Overall I think it is more important to fix the task inactive for xx seconds issue but I cannot yet reproduce it reliably here to figure out why that happened. 

That's also a problem on my end. I dont get this every time. But getting it from time to time seems enough frustration for running large benchmark workflows. I understand it is hard to reproduce and fix, so I was thinking if changing the mechanism entirely can help.

A couple more of those lines popped up as we speak. After this run I"m going to see if running one of the stress test can reproduce it ... but while I'm on this run, what information or experiment do you need me to gather that might help?

**Comment by BoPeng** [comment]
Perhaps I can add more detailed debug message for the execution of tasks, such as when the task is started, and when it touches the `pulse` file etc, and we can filter the `sos_debug.log` file with ID of task showing the message. Note that this will add a lot of output if there are a large number of tasks, but it might be good if the extra output can make the problem more reproducible.

**Comment by gaow** [comment]
> Note that this will add a lot of output if there are a large number of tasks, but it might be good if the extra output can make the problem more reproducible.

that'd not be an issue as long as that goes to `sos_debug.log` not on the screen!

**Comment by gaow** [comment]
At least one cause I can see that's possibly related to the inactivity warning was walltime limit issue:

```
slurmstepd-midway2-0327: error: *** JOB 63843242 ON midway2-0327 CANCELLED AT 2019-11-20T00:30:54 DUE TO TIME LIMIT ***
```

However one can only see it in the `stderr` file as specified in job template. I wonder if it would be useful / easy to show it also in `sos status -v4`. Currently if I use `sos status -v4` for that task in question I still get the missing pulse prompt not this more useful line.

**Comment by BoPeng** [comment]
With `.err` set to `~/.sos/tasks/{task_id}.err`, `sos` should be able to catch and report cluster error. Is this ticket still valid?

**Comment by gaow** [comment]
Okay it seems we can close it for now.
