### ISSUE TITLE
Error handling on complicated workflow

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1265]
Separated from #1263 . I think we've discussed this before and decide we should fail early and stop the entire workflow when there is any error in the workflow. But the alternative, finishing up DAG as much as possible, is also appealing. In fact it is what snakemake does. Basically when there is an error we should perhaps only stop itself and the rest nodes in the DAG from running, but still try to finish up the rest of the DAG? Does it make more sense? I could not think of how we justified our previous behavior. 

Part of this request is motivated also by practical issues (#1263 that we solved, #1264 that still persists) and they are important factors. But other than practical considerations, is there a reason we should not try to finish up a DAG?

**Comment by BoPeng** [comment]
Cannot find the ticket but originally sos tried to complete the DAG in error but you talked me to the existing behavior. I think the arguments were something like the error could already affect the correctness of other steps, we are going to rerun anyway, and it is better to rerun earlier than later. My argument against it was mostly it is not nice to kill running steps.

**Comment by gaow** [comment]
>  but you talked me to the existing behavior

Yes I think I did that. But that was mostly for concurrent steps. So if one substep in a concurrent step failed, it makes sense to kill all other concurrent steps, even if it is not nice. I think I'm still in favor of that behavior.

Here I'm talking about step level DAG. Suppose there is a DAG `A->B, A->C` , then if `B` fails, one can argue that `A->C` should complete. However, one can also argue what if `B` failure was because of `A`, and all other steps depending on `A` will also fail? So yes I'm still not sure if it is reasonable to complete the DAG. At this point I guess possibly I'm more motivated by those practical considerations eg #1264 or any weird lost of connections of task manager with slurm, which unfortunatley is hard to reproduce.

**Comment by BoPeng** [comment]
Let us think more on this, perhaps check what gnu make does, but in theory sos bugs and performance should not be considered. 

I need to get up early tomorrow and have to stop now.

**Comment by gaow** [comment]
Sure, have good rest! I'm no longer very familiar with GNU Make syntax but I'm sure snakemake tries to complete the DAG. It still makes sense to me that concurrent substeps should be killed once any errors occurs. I was just not sure about my step level argument. 

I agree "in theory sos bugs and performance should not be considered." and if that is indeed the case I will perhaps still agree to stop early. But unfortunately currently practical considerations seems also important. Maybe we can leave the ticket here for now and see if later #1264 can be addressed, when you get a  chance to visit it.

**Comment by BoPeng** [comment]
https://www.gnu.org/software/make/manual/make.html#Errors has detailed description of what make does

> ‘--keep-going’
> Continue as much as possible after an error. While the target that failed, and those that depend on it, cannot be remade, the other prerequisites of these targets can be processed all the same.

It reads like make will usually exit immediately after an error, but will continue as much as possible after `--keep-going`.   The manual also describes the scenarios when `-k` is desired (compiling objects).

https://www.gnu.org/software/make/manual/make.html#Parallel
> If make terminates for any reason (including a signal) with child processes running, it waits for them to finish before actually exiting.

So make behaves as follows:

1. If an error happens, it waits for the parallel tasks to complete before existing.
2. If `-k` is specified, it will continue to run the DAG as much as possible.

So 
1. SoS' current behavior is the default of make and makes sense in most cases.
2. SoS kills running workers when error arises. This is not good as I have suspected, and should be changed.
3. Whether or not we should add an `-k` option is up to discussion.

**Comment by gaow** [comment]
> SoS kills running workers when error arises. This is not good as I have suspected, and should be changed.

Still not sure about this. In practice if we allow a step with thousands of substeps to complete, the error message for the failed substep will be buried somewhere deep, and users will be left puzzled that the step eventually failed with some error prompts they no longer see? At least this is what I remembered an inconvenient experience.

But I agree Make must have done it for good reasons. I think it would work in practice as long as we can make sure the error messages from the parallel tasks are easily available after `sos` quits.

**Comment by BoPeng** [comment]
The original behavior was the error message will be cached and displayed at the end (stored in a separate `execute_error` exception type), but this exception type is unused because the exceptions are no longer cached.

So it seems that the original behavior was consistent with make and we are turning back, and resolve your problem with probably a `-k` option.

**Comment by gaow** [comment]
Okay that sounds good -- would like to test it out when the original behavior is brought back. It would be good to have the additional `-k`-like option but I'm neutral to it at this point because with other SoS related issues / bugs resolved, this is more like an additional feature that should not be default anyways, rather than some desirable requirement to make things work.

**Comment by BoPeng** [comment]
Fixed and added option `-k`, with the following workflow


```
import time

[default]
sos_run('a')

[a_10]
time.sleep(5)

[a_11]
print('I am step 11')

[a_20]
input: None
time.sleep(2)
fail_if(True)
```

`a_10` and `a_20` starts at the same time, `a_10` runs longer than `a_20` and `a_20` will stop after 2 seconds, and `a_11` follows `a_10`.

1. `sos run test` will stop `a_20` after 2 seconds, but wait till `a_10` to finish to exit.
2. `sos run test -k` will stop a_20` after 2 seconds, but wait till `a_10` and `a_11` to finish to exit.

**Comment by gaow** [comment]
Oh good. I guess I should wait until unit tests pass? I am going to modify a small stress test to see its behavior in a non-trivial setting (will use a ticket in that repo)

**Comment by BoPeng** [comment]
Thanks. The test has passed. Note that the exception is handled at the step level so substep failure will terminate the entire step, just not other steps.

**Comment by BoPeng** [comment]
Substeps are not supported. There are two scenarios:

1. If a step has failed, should substeps of another step be stopped? This can be done but a bit inefficient because right now steps just send substep requests to the controller without waiting for a response. If we allow substeps to be denied, the step worker needs to wait for an response for each substep submitted.

2. If one substep failed, should all substeps to be stopped, how about the one that has been running?  It seems make sense to continue submitting substeps if `-k` is specified, otherwise stop submitting substeps but wait for the existing substeps to complete. Right now sos does not wait for the completion of submitted substeps.

**Comment by gaow** [comment]
I agree with 2. 

> otherwise stop submitting substeps but wait for the existing substeps to complete. 

Or, to fail as well, right?

> If a step has failed, should substeps of another step be stopped? 

what other step? The other step that depends on output in the failed step? I'm not sure if I understand the issue. In principle we want all dependency to fail, so if a step failed because of some substep, then the other steps should also fail?

**Comment by BoPeng** [comment]
For 1 I meant the following

```
import time

[10]
input: for_each=dict(i=range(10))

print(i)
time.sleep(1)

[20]
input: None

time.sleep(2)
fail_if(True, 'stop 20')
```

After step `20` fails, some of the substeps from step `10` are still running, but some are not yet submitted. Then we could either

1. wait for the entire step to complete (current behavior)
2. wait for the submitted substep to complete but stop submitting new substep. This means step 10 cannot finish and will also fail.

I think 1 is good enough.

**Comment by BoPeng** [comment]
For 2,

```
import time

[10]
input: for_each=dict(i=range(10))

print(i)

time.sleep(2)
fail_if(_index == 5, 'fail at 5')
```

if the substep worker stops index == 5, with `-k`, the step worker will submit the rest of the substeps as usual and report the error (substep 5 failed) at the end.

Without `-k` (default), we are supposed to kill the step but do not murder running substeps. So the behavior should perhaps be waiting for the current batch to complete but do not submit new.  A minor problem is that step worker submit jobs in advance so by the time substep 5 is errored, all other steps should have been submitted so the behavior will be the same regardless of `-k`. In contrast, the current behavior is that the step will be killed without waiting for the results of submitted substeps.

**Comment by BoPeng** [comment]
Test case (will add to tests)

```
import time

[10]
input: for_each=dict(i=range(10)), concurrent=False

print(i)

fail_if(_index == 5, 'fail at 5')
```

`sos run test` will terminate at step 5, `sos run test -k` will complete all ten steps. This is not concurrent so it is easy to stop.

**Comment by BoPeng** [comment]
Test cast

```
import time

[10]
input: for_each=dict(i=range(200))

print(i)

fail_if(_index == 5, 'fail at 5')
fail_if(_index == 50, 'fail at 50')
```

All substep will be executed with `-k`, without `-k`, the substeps will steps somewhere, but because of large number of substeps, most likely substeps beyond 100 will not be executed.

**Comment by gaow** [comment]
> I think 1 is good enough.

I agree that current behavior is good enough.

RE whether or not to wait for jobs submitted or to kill them: I think whichever easier and more robust would be our option for behavior without `-k`. It is understandable that in some cases`-k` and no `-k` does not make a difference.
