### ISSUE TITLE
Revisit the tracing subworkflow design

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1267]
Right now, our signature system traces into steps with subworkflows regardless of its signature and thinks that it is safer to check all steps because subworkflows can do many things that might not be captured in the `output` of the step. This works ok with

```
[default]
sos_run('blah')
```
because there is no signature for `default` anyway and sos will simply trace into `blah`.

This becomes a problem with 

```
[default]
output: long_output
sos_run('sub')
```

That is to say, if the signature of the step exist, we ignore the signature, execute the step, go into `sub`, but we **save signature after we scan the subworkflow** because we actually executed the step. This happens even with `-s skip` and when the step signature actually matches (we did not use it to validate), and can be slow if `output` has all output of the subworkflow.

So perhaps a more reasonable behavior is to remove this exception and

1. For 

```
[default]
sos_run('blah')
```
sos will trace into `blah` because no output is defined.

2. For 
```
[default]
output: long_output
sos_run('sub')
```
we check the signature and skip the step, thus the subworkflow if signature matches. That is to say, we trust that if users define `output` here, the subworkflow is supposed to generate these `output`.

If we do this, the signature validation will be much much faster for workflows with nested workflows.

**Comment by BoPeng** [comment]
One problem, and one of the motivations for this behavior is for `build` because without tracing into subworkflows sos cannot build signatures for subworkflows steps.

**Comment by gaow** [comment]
But what if there is a change in `sub` eg its input and scripts, will it rerun? `sub` can have input that is not very clear from `default` right?

**Comment by BoPeng** [comment]
Yes, that was a big problem and one of reasons it was designed this way. The problem here is that `sos_run` does not capture the content of the workflow to be executed, so to make this work, we have to get the content of workflow and make it part of the signature. Even then because nested workflow can essentially be nested and dynamically changed, so a reasonable assumption is to include the entire script, and the scripts of `sos_run(src=..)`.

**Comment by BoPeng** [comment]
With the experimental patch, `-s default` completes in `33s` and `-s skip` completes in `29s`.

**Comment by gaow** [comment]
Well, how about changes in input to those substeps? I'm not sure if I see how the `default` step can work safely without looking into the subworkflows.

**Comment by BoPeng** [comment]
Then the step with subworkflow will need to specify all the relevant input. If this is a burden, then just do not specify any input and output and let sos trace into the nested workflow.

**Comment by BoPeng** [comment]
The good news is that this is a bug, that is to say, signatures of steps with subworkflows are created, but not used, so they should not be created in the first place. With this fixed, the `-s default` time is reduced from `2m 40s` to `1m 40s`...

**Comment by gaow** [comment]
Sorry I want to clarify: so now we still always trace into subworkflows? Or we only stop tracing into subworkflows when no input and output are specified? I think it is safest to trace; and if we decide to do anything to stop it from tracing I think it should be : both input and output are known + no script has been changed. You seem to suggest that we will not trace unless neither input nor output is specified? I do not think it is reasonable behavior ...

**Comment by BoPeng** [comment]
I reverted the experimental patch and applied a patch to fix a bug for handling steps with subworkflows, so yes the newest behavior still drills into subworkflows. Basically, previously we ignore signatures for these steps but still writes them, and the patch stops writing them as well. Because the stress test has a large number of files, stop writing these signatures reduced time from 2:40s to 1:40s, which narrows the gap between `-s default` and `-s skip` to just a few seconds. (I previously thought that `-s skip` also writes signature but I was wrong).

Although bypassing subworkflows will reduce the time further to about `30s`, perhaps `1:30s` is good enough and there is no need to change the existing behavior.

**Comment by gaow** [comment]
Yes I agree, existing behavior is safest and it is great now that `-s default` is almost as good as `-s skip`!

**Comment by BoPeng** [comment]
This is just for one stress-test so it is worthwhile to keep `-s skip` and `-s distributed`, in case `-s default` appears to be slow for some workflows.

I will make a new release after the tests pass.
