### ISSUE TITLE
[autocompletion] at wrong place

### ISSUE THREAD

**Issue by tianyao1000** [vatlab/SoS#1268]
I am reporting two bugs regarding autocompletion function in Jupyter when I was using SOS.

The first one, when the hinterland function is disabled in nbextension.
As shown in the following image

![autocompletion1](https://user-images.githubusercontent.com/25381950/57822863-fee30980-77c7-11e9-9f9a-0d9cd6c7e085.png)

basically, when I tried to use the autocomplete, the first time it works fine (as shown in step 1 and 2). However, for the second time, the autocomplete inserted the code at the wrong place (as highlighted by the red rectangle)

The second is still related to autocompletion function, but this time, I turned on hinterland in nbextension. As shown in the following image, the autocomplete function adds an addition letter to the end of the code (instead of ggplot, the code becomes ggplotp)

![autocompletion2](https://user-images.githubusercontent.com/25381950/57822872-07d3db00-77c8-11e9-8298-f11355ba0695.png)

**Comment by BoPeng** [comment]
I notice that you have `python3` instead of `Python3` in the language dropdown box. This means the `sos-python` language module has not been installed. This does not mean this bug report is invalid but the bug might manifest in a different way if `sos-python` is installed.

Will look further into this later.

**Comment by BoPeng** [comment]
I have just pushed a patch. Please let me know if the bug has been fixed.

**Comment by tianyao1000** [comment]
Thanks for the patch. I tried it on my local machine, now the autocompletion works perfectly.
