### ISSUE TITLE
SoS Flow?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1271]
We now have `SoS Notebook` as the official name for the multi-language notebook, and `SoS` or `SoS Workflow System` for the workflow system. The problem is that `SoS` does not imply a workflow system and we often use `SoS` for the "SoS suite of tools" that includes both tools, and `SoS Workflow System` is a bit long. I am therefore wondering if we should have `SoS Flow` or `SoS Workflow` as the official name for the workflow system.

**Comment by gaow** [comment]
`SoS Flow` certainly has its appeals but `SoS Workflow` is clear about what it does, and the length of characters is the same as `SoS Notebook` which I can imaging be visually appealing on prints.

**Comment by BoPeng** [comment]
To be fair, a majority of the workflow systems listed [here](https://github.com/common-workflow-language/common-workflow-language/wiki/Existing-Workflow-systems) does not ends with `pipe` or `flow`, but to me listing `SoS` and `SoS Notebook` side by side is a bit awkward. Also, listing `Script of Scripts` in that page does not help branding since we need an official name.

**Comment by BoPeng** [comment]
We have used "Script of Scripts" in our paper, which seems to be the official name, but we do not use it in practice as much. Currently I want to have a consistent name to refer to the workflow system. Candidates include

| name | pros | cons |
| -- | -- | --|
| `Script of Scripts` | fullname | spaces in name, difficult to read | 
| `SoS`  | short, original name | confusing relationship with `SoS Notebook`|
| `SoS Workflow` | shows the nature of system | space in name | 
| `SoSWorkflow` | a single name | More or less a new name |
| `SoS Flow` | shows the nature of system | space in name, incompatible | 
| `SoSFlow` | a single name | incompatible |

**Comment by BoPeng** [comment]
I think I will

1. Use `SoS Notebook` to refer to the notebook.
2. Use `SoS Workflow` to refer to the workflow
3. Use hash tags `#sosnotebook` and `#sosworkflow` in twitter.
4. Use `SoS` to refer to the combo, the suite of tools.

**Comment by gaow** [comment]
Yes I also like `SoS Notebook` and `SoS Workflow`. Other proposals might look simpler but lacks consistency. 

Can we change twitter account name? I think we should use `bioworkflows` the company website name you bought. It's more generic and contains SoS project, but also will fit our needs down the road with future development.

**Comment by BoPeng** [comment]
Good idea! Just did that, even surprised that it is not taken. I also changed the name [here](https://github.com/common-workflow-language/common-workflow-language/wiki/Existing-Workflow-systems).

**Comment by BoPeng** [comment]
Also signed up bioworkflows@gmail.com

**Comment by BoPeng** [comment]
Thinking of renaming the repo from `SoS` to `sos-workflow` and release `sos` under the name of `sos-workflow` to make it consistent with `sos-notebook`, and future `sos-portal`.

**Comment by BoPeng** [comment]
But renaming is always troublesome, think of all the installation instructions, all the package installs. Perhaps it makes sense to keep the name `sos` as the `core` of the SoS suite of tools.

**Comment by gaow** [comment]
Yes I agree with keeping it as is. It is indeed the core after all. Other packages all depend on it

**Comment by BoPeng** [comment]
Ideally there should be a `sos` repo as the pivotal repo for other components...

Anyway, I just renamed `SoS` to `sos` and trying to see if there is any side effect. The reason being people generally do not expect capital letters in repo names.

**Comment by BoPeng** [comment]
`http://github.com/vatlab/SoS` still works, as well as `https://github.com/vatlab/SoS/issues`

**Comment by BoPeng** [comment]
The awkwardness comes from the fact that nowadays I tend to introduce sos notebook first because it is easier to introduce, earlier to be published, and the way presented on our website.

**Comment by gaow** [comment]
So you start from a non-tech, user oriented introduction to the notebook, as a polyglot notebook, that consolidates existing languages interactively; then introducing a new language called `sos` for workflows and the `sos` core that runs it. Then perhaps why we need workflow system in daily work? That does not sounds too awkward.
