### ISSUE TITLE
New batch job model implementations

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1276]
Moved from an offline discussion. @BoPeng wrote:

I have not thought through what the new execution model should look like. It can be one or both of the following:

1. The multi-machine version of sos master executor that executes the entire workflow. That is to say the master process is one of the working nodes and we distribute the existing workers to multiple processes and nodes.

2. A new task execution model that submit all tasks to multiple nodes. That is to say, we keep the existing execution model, the existing task submission model, but we expand `trunk_workers` to use multiple nodes. We submit a master task to the cluster and the task executor would have a master process coordinating the execution of many tasks on multiple nodes.

**Comment by gaow** [comment]
@BoPeng I think I can understand it for 1, but for 2, how does it help with vulnerability of communicating with job scheduling system? For 1 it is obvious because we claim via job scheduler enough resource all at once and let SoS decide what to do. For 2, how many "talks" have to happen between SoS and the scheduler? Also, for 1, it means we have to ask lots of resource in advance? This might lead to long waiting time in the queue. Maybe 2 is meant to be a more balanced solution between 1 and the current execution model?

**Comment by BoPeng** [comment]
For 2, only 1 master task will be submitted and the task will be executed on multiple nodes. We are doing this right now with `trunk_workers` > 1, but that is limited to one node.

**Comment by gaow** [comment]
I see. Thanks for the clarification. So method 2 will still involve some MPI approach, but avoid doing a very formal SoS cluster, the change is simpler, and is more scalable because one can balance between trunk_size and the nodes used in trunk_workers. Please correct if I am wrong.

Interface-wise, I worry this will easily confuse with `cores` ... But this should be solvable via improved documentation.

**Comment by BoPeng** [comment]
Both approaches have their uses. Whereas approach 2 is more SoS-like, users might be more familiar with the first approach when they are given a large workflow and would like to execute it on the cluster without anything local. Also,  in theory, although approach 1 should usually absorb tasks with `-q none`, it can submit tasks to more nodes.

**Comment by gaow** [comment]
> Both approaches have their uses.

I want to clarify one thing: is it true that approach 1 will only show in the queue as one job with one job ID, regardless of how complicated the workflow is? If so, this is what I meant by not scalable, because one has to ask for a huge amount of resource in advance, if they want a complex workflow to complete faster.

**Comment by BoPeng** [comment]
Yes. But that is the case for the execution of any workflow and it is user's responsibility to estimate the overall workload (memory usage etc) for not only sos, but all the external programs sos calls. The workflow report is very useful in summarizing the resources used after the completion of the (test) workflow though.

**Comment by BoPeng** [comment]
The new task executor would be less intrusive and easier to implement. Possible interface:

 ```
trunk_workers=(m, n)
```

More specifically,
1. `trunk_size=n` create master tasks with `n` tasks each. We could allow for value `0`, `-1`, or `None` for putting all tasks in one master task.
2. `trunk_workers=(m, n)` executes the tasks on `m` nodes with `n` processes  on each node. This is an extension to `trunk_workers=n` that we have now.

Then,
```
sos execute task_file
```
will check number of nodes specified in the `task_file`, and calls `mpiexec` if needed to create a `m`-node MPI job to process the tasks.

**Comment by BoPeng** [comment]
`task` statement already supports a parameter `nodes`, in addition to `cores`, `mem`, etc, which should be implemented to support multi-node execution. That is to say, without any interface change, 

1. The template should support `{nodes}`, which, if already added, should support the creation of multi-node jobs.
2. `sos execute` should be aware of `{nodes}` and run multiple sub tasks in multiple nodes.

**Comment by BoPeng** [comment]
We can use mpi interface to start sos, or manually following approaches of [`SCOOP`](https://github.com/soravux/scoop). In particular, [this function](https://github.com/soravux/scoop/blob/master/scoop/utils.py#L144) shows how to get node list. That is to say, when `sos execute` is submitted to multiple nodes, we can use this function to identify who is the master.
