### ISSUE TITLE
Dependency on PBS engine

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1282]
Here is a report from a colleague:

```
I’m really sorry ... but there seems no similar errors on Google. 
ERROR: Failed to locate task engine type pbs. Available engine types are process
ERROR: ‘LocalHost’ object has no attribute ‘_task_engine’
ERROR: ‘LocalHost’ object has no attribute ‘_task_engine’
ERROR: ‘LocalHost’ object has no attribute ‘_task_engine’
ERROR: ‘LocalHost’ object has no attribute ‘_task_engine’
ERROR: ‘LocalHost’ object has no attribute ‘_task_engine’
ERROR: ‘LocalHost’ object has no attribute ‘_task_engine’
ERROR: ‘LocalHost’ object has no attribute ‘_task_engine’
```

It turns out he installed `sos` and `sos-notebook` but not `sos-pbs`. Should we add some more peaceful check and prompt for `sos-pbs` installation when task engine type is parsed?

**Comment by BoPeng** [comment]
```
Failed to locate task engine type pbs
```
is already clear, right? The `no attribute` thing could be suppressed though.

**Comment by gaow** [comment]
> is already clear, right?

Yes. 

> The no attribute thing could be suppressed though. 

Right, that is what I meant by the more peaceful check: to wrap the message at least to not repeatedly show it and distract people from realizing what the problem is.

**Comment by BoPeng** [comment]
I do not see the `attribute` error here after I uninstall `sos-pbs`, let me check further.

```
(base) bpeng1@q1prphtch00:~$ sos run test -q htc
INFO: Running default: 
ERROR: Failed to locate task engine type pbs. Available engine types are process
ERROR: [default]: [28d6470c2906eeae]: Failed to locate task engine type pbs. Available engine types are process
```

**Comment by gaow** [comment]
If it helps, the example in #1281 was derived from the script he used that displays the error.

**Comment by BoPeng** [comment]
The second error message (from another worker) can be different

```
(base) bpeng1@q1prphtch00:~$ sos run test -q htc
INFO: Running 1: 
ERROR: Failed to locate task engine type pbs. Available engine types are process
ERROR: [1]: [1]: Failed to get results for tasks 7ef279e27d399ec5
```

So some basic safeguard of making sure `_task_engine` exists before referring to it could help.

**Comment by BoPeng** [comment]
How about this message?

```
                        f'{self._task_engine_type} task engine is not supported on this system. Did you install relevant module such as sos-{self._task_engine_type}?'

```

**Comment by gaow** [comment]
This is good enough. Will this also suppress the redundant error prompts?

**Comment by BoPeng** [comment]
```
$ sos run test -q htc
INFO: Running 1: 
ERROR: This system currently supports task engine process, not pbs as specified in the template. Did you install a relevant module such as sos-pbs?
ERROR: [1]: [1]: Failed to get results for tasks 7ef279e27d399ec5
```

I have tried to suppress other messages in the patch but I cannot test it as I could not reproduce it.
