### ISSUE TITLE
How to "retrofit" an existing python kernel to be used with SoS?

### ISSUE THREAD

**Issue by oerbilgin** [vatlab/sos#1289]
Hello, I am very excited about this SoS system you have built ... particularly the ability to use multiple kernels in one notebook! However, I'm confused on how to use my existing kernels within this notebook. I have a number of different Python (2 and 3) kernels, but none of them have the SoS magics supported ... is there a way I can "retrofit" an existing kernel to be compatible with SoS?

**Comment by BoPeng** [comment]
SoS already works with all jupyter kernels, in the sense that you can choose any kernel from the dropdown list, use magic `%expand` to prepare input,  `%capture` to capture output, and `%render` to render output. If you have language modules installed (e.g. `pip install sos-python sos-r`), you will see languages (`Python3`, `Python2` instead of `python3` etc) listed and you can use magics such as `%get` to pass variables. Please check out [sos notebook tutorials](https://vatlab.github.io/sos-docs/notebook.html#content) for details.

**Comment by oerbilgin** [comment]
Thanks for the quick reply @BoPeng! I can successfully use `%capture` and `%expand` with my pre-existing kernels, but when dealing with Pandas dataframes, it looks like the data exchange is always meant for rendering and not further data analysis (via a separate kernel, for example).

An error message I get when trying to use `%get` with a python kernel makes me think that adding these magics might be possible to my existing kernels:
```
Magic %get failed because the language module for python3 is not properly installed. Please install it according to language specific instructions on the Running SoS section of the SoS homepage and restart Jupyter server.
```

But perhaps another way to ask this question is ... given one of the `sos-python` kernels (e.g. `Python3`), is there a way I can install packages into that environment, with `pip` or `conda`?

It would be really sweet if I could pass various data structures between python kernels (which need to remain separate kernels due to dependency conflicts).

Thanks for your time!

**Comment by BoPeng** [comment]
Were you able to install `sos-python` using `pip install sos-python`? `sos-python` is not a kernel, it is a python module that provides a link between `sos` and `python3` kernels so that they can exchange data via `%get` and `%set` magics.

**Comment by BoPeng** [comment]
BTW, if you need multiple Python kernels, you can do

```
%use Py1 --langauge Python3
%use Py2 --langauge Python3
```

**Comment by oerbilgin** [comment]
Thanks again for the quick response and tips. Yes, I was able to install `sos-python`, and I saw a new (sub)kernel named Python3, which seems to work with `%get` magics (at least between Python3 and SoS subkernels). Your suggestion to specify the language for different python subkernels didn't seem to work for me though.

In Py1 code block:
```
[IN] 
%use Py1 --language Python3
[OUT] 
WARNING: Notebook uses language python for kernel Py1, but local system uses language Python3 instead.
```

So then I went into the `kernel.json` for Py1, changed the `language` attribute to Python3 and tried again, but got the same warning.

Despite the warning, if I try to `%get` a variable in a different subkernel, I still get this error:

```
Subkernel Py1 does not support magic %put.
```

I wonder what I'm doing wrong?

**Comment by BoPeng** [comment]
Could you try with a fresh notebook? language `python` remind me the possibility of an old notebook before `sos-python` was installed.

![image](https://user-images.githubusercontent.com/9889312/63610563-5cdd7500-c59f-11e9-9942-a76776336902.png)

**Comment by oerbilgin** [comment]
Hmm. maybe I am setting up the kernel incorrectly? This is how I've done it:

```bash
$ mkdir new_env; cd new_env
$ virtualenv --python=python3 .
$ source bin/activate
$ pip install sos-python
$ python -m ipykernel install --user --name Py1 --display-name "Python (Py1)"
```

And then, I restarted my jupyterlab (from a separate jupyterlab environment). I can see my new kernel, but get the same issue (the warning goes away if I manually change the `language` attribute to `Python3`, but I still get the same result)
![image](https://user-images.githubusercontent.com/16328959/63615921-4af9d300-c59b-11e9-926e-880e5c285ff0.png)

I get the same result if I create and launch a notebook server from a brand new notebook-specific env like this (just in case my jupyter lab environment was the problem):

```bash
$ mkdir other_env; cd other_env
$ virtualenv --python=python3 .
$ source bin/activate
$ pip install sos sos-notebook sos-python jupyter ipykernel
$ jupyter notebook
```

I feel like I'm doing just one or two things out of turn or something!

**Comment by BoPeng** [comment]
> `python -m ipykernel install --user --name Py1 --display-name "Python (Py1)"`

I have never done this before. SoS will not recognize this kernel if it has a different name, and you will likely have to do something like

```
%use py1 --kernel Py1 --language Python3
```
Although for a completely different issue, [this post](https://github.com/vatlab/sos-fsharp/issues/1#issuecomment-513821010) might help you understand the relationship between kernel, language module, and subkernel.

**Comment by BoPeng** [comment]
BTW, you usage looks like that you have a kernel (y1) and would like to link it to a language module, the SoS way is to do it is to create a new name using command
```
%use another_name --kernel py1 --language Python3
```
because `py1` is currently recognized by sos as a kernel without language (thus the warning message), and I am not quite sure if it allows
```
%use py1 --kernel py1 --language Python3
```
namely adding language information (`Python3`) to an existing displayed name (`py1`). Let me know if it works as expected though.

**Comment by oerbilgin** [comment]
> ```%use another_name --kernel py1 --language Python3```

This totally worked for me! thanks!

And thanks for the link to the other post; I'll take a read through that. 

This really is a beautiful tool. I'm very excited to use it. Great work!

**Comment by BoPeng** [comment]
But your usage is justifiable so I am trying to see if I can make it work.

**Comment by BoPeng** [comment]
The original behavior can be considered as a bug because it yielded a "warning" message (not an "error") but the language was not correctly assigned. The patch should have fixed it.

![image](https://user-images.githubusercontent.com/9889312/63619210-9c15c100-c5b3-11e9-9b24-11dbccd49de0.png)
