### ISSUE TITLE
Maximum number of jobs

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1291]
Discussions in #1149 is obsolete so I'm opening this new ticket. Somehow we still have this issue that submitted jobs in queue exceeds number of jobs allowed in our configuration, see this file below result of `showq` on my cluster

[showq.txt](https://github.com/vatlab/sos/files/3616776/running.txt)

Notice my maximum number of jobs is 150.

**Comment by gaow** [comment]
Here is what's going on with additional submissions that immediately reads problematic:
```
INFO: Waiting for the completion of 176 tasks before submitting 325 pending ones.
...
INFO: Waiting for the completion of 153 tasks before submitting 325 pending ones.
INFO: Waiting for the completion of 152 tasks before submitting 325 pending ones.
INFO: M40_5b4b0f54658ff383 submitted to midway2 with job id 62485138
INFO: M40_581006a0338f2628 submitted to midway2 with job id 62485139
...
INFO: Waiting for the completion of 299 tasks before submitting 175 pending ones.
INFO: Waiting for the completion of 295 tasks before submitting 175 pending ones.
...
```
My maximum job limit is 150. You see there are still 152 tasks to be completed in the queue; however at that point, the job master submitted another 150 tasks (the maximum allowed number) so my queue then have 300 tasks.

**Comment by BoPeng** [comment]
xxx in the `waiting for the completion of xxx tasks` is the sum of sumitting tasks plus running tasks, so the problem here is that there are too many submitting jobs, let me check why.

**Comment by BoPeng** [comment]
Please close the ticket if the problem has been fixed.

**Comment by gaow** [comment]
It seems so from my test a couple of nights ago. I'll reopen if it is not the case.
