### ISSUE TITLE
Replace `step_name` with "annotated" step name when available in INFO

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1292]
I'm referring to a modification I want to make here:

https://github.com/vatlab/sos/blob/baca625a0d3a16d6e7713348fd3bdb9680a641b8/src/sos/step_executor.py#L1000

currently it says `<step_name> is completed (pending nested workflow)`, but my workflow is like:

```
[step_name (some more informative annotation)]
```

so I want it appear as `some more informative annotation is completed (pending nested workflow)`. How should I change the code here?

**Comment by BoPeng** [comment]
sure.

**Comment by gaow** [comment]
Great thanks, done!
