### ISSUE TITLE
PBS overrides sos stdout and stderr files

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1293]
SoS uses `~/.sos/tasks/{id}.out` and `~/.sos/tasks/{id}.err` for stdout and stderr for tasks with id `{id}`, it also recommend setting these files in PBS wrapper scripts so that PBS could send job stdout and stderr to these files.

However, I have noticed that when something went wrong, the system `stderr` will override, instead of append to SoS stdout and stderr files.

**Comment by gaow** [comment]
You are referring to situation in #1264 where I found the SLURM kill message in system stderr, or there are still other situations you that behave like it?

**Comment by BoPeng** [comment]
For example, running the following script in localhost

```
input: for_each=dict(i=range(10))

task: trunk_size=None, trunk_workers=2, walltime='5m', mem='1G'
python: expand=True
  print({i})
  if {i} == 2:
     raise ValueError({i})
```

I would see messages such as

```
standout output:
================
68dcb886905882c6: completed
68dcb886905882c6: completed
output: 
fdb999510a870eb5: completed
fdb999510a870eb5: completed
```
in the output. However, running it on my cluster these messages are gone because the PBS system overrides `~/.sos/tasks/{id}.out` with the stdout it collects during the execution of the job.
