### ISSUE TITLE
Failed to start remote worker

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1300]
Without the `sos worker` part, sos currently uses a command similar to 
```
$ ssh q1prphtcb02 "bash --login -c 'set -e $(env)'"
bash: line 6: 60162: command not found
```
to log into another node of the cluster, and the `set -e $(env)` command sometimes fail.

This command is used to copy local environment to the remote hosts so that the effects of `module load` and `export PATH=...` could be propagated to remote hosts.

However, in one example, the `set` command fails when the out of of `env`

```
MANPATH=/usr/local/torque/share/man
XDG_SESSION_ID=2353
HOSTNAME=q1prphtch00
SHELL=/bin/bash
TERM=xterm-256color
HISTSIZE=1000
SSH_CLIENT=10.105.32.40 60162 22
CONDA_SHLVL=1
```
which triggers the `60162`  command not found error, because we are essentially running command

```
... SSH_CLIENT=10.105.32.40 60162...
```
from command line, `60162` is considered as a command

**Comment by gaow** [comment]
Separating from #1312 -- but `SSH_CLIENT="10.105.32.40 60162 22"` will work. So the question boils down to how to escape bash variables properly. How about adding quotes instead?

**Comment by BoPeng** [comment]
We could. I found that spaces and mostly large function definitions so used space to exclude them. A proper solution should be dumping the variables to a file and send it to remote host during ssh testing and source it in ssh
