### ISSUE TITLE
Number of workers and cpus per worker 

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1304]
https://github.com/vatlab/sos/issues/1290#issuecomment-536595178

Currently we have

```
task: trunk_workers=[4]*3, cores=4
```
which means

1. Each task will use `4` cores
2. Each trunk with have four workers on three nodes.
3. Therefore each node will require `4*4=16` cores.

Now, For SLURM (and other clusters)
1. we should always set `ncpus per task` to 1, and `njobs per node` to `cores`, which is 16.
2. sos accepts parameters `-j node1:ncpu node2:ncpu node3:ncpu` to `sos execute`
3. sos also knows `trunk_workers=[4]*3`, so it should start `4` workers on `node1`, `node2` and `node3` instead of 16.

Please verify if this is the case.

**Comment by gaow** [comment]
> we should always set ncpus per task to 1,, and njobs per node to cores, which is 16

I thought we should set number of tasks to 1 for each job, and ncpus per task to `cores` for that job? Basically we should bypass the `task` concept because in SoS we've got our way to handel tasks.

**Comment by BoPeng** [comment]
> I thought we should set number of tasks to 1 for each job, and ncpus per task to cores for that job? 

You are right, there is only 1 "job" which uses `n_workers * cores` cpus. It is the terminology between cluster job, cluster task, and sos task, sos workers that become confusing.

**Comment by gaow** [comment]
Currently #1290 seems to be fixed and we are on the same page that multiple tasks wound not be necessary. However in your first thread on this post: 

> we should always set ncpus per task to 1, and njobs per node to cores, which is 16.

while I was sugesting always set number of tasks to 1 and ncpus per task to `cores` then the actual `{cores}` will be `cores` times number of trunk workers on that node. Is that currently the case?

**Comment by BoPeng** [comment]
> while I was suggesting always set number of tasks to 1 and ncpus per task to cores then the actual {cores} will be cores times number of trunk workers on that node. Is that currently the case?

yes.

**Comment by BoPeng** [comment]
Just double checked that the implementation is correct regarding this issue.
