### ISSUE TITLE
Add a message for all tasks completed?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1307]
I see
```
INFO: Waiting for the completion of 10 tasks.
INFO: Waiting for the completion of 5 tasks.
INFO: Waiting for the completion of 2 tasks.
INFO: Waiting for the completion of 1 task.
INFO: Waiting for the completion of 1 task.
```
and a final `ALL tasks have been completed` should follow. Otherwise it appears that users should continue to wait.

The problem here is that the 'zero task' status is the most common case of the task engine, so it does not know if the status is a step down from having running or pending tasks, unless we are ok with generating a no task message every minute when there is no task.

**Comment by BoPeng** [comment]
The only way to implement this is to add a engine busy flag, and say, if the engine is busy and 1 minute has passed, we print a message and set the engine to idle. It is doable but I am not sure if it worth the trouble for such a small feature.

**Comment by gaow** [comment]
> and a final ALL tasks have been completed should follow.

For my case, since all tasks are complete, the output file summary INFO line will follow anyways. So I don't see it is an important feature to add.
