### ISSUE TITLE
Formally allow execution of SoS workflows in Python scripts?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1309]
SoS is not designed to be used as libraries but perhaps there could be applications that embed SoS workflows? For example, a python application that needs to execute multiple steps could do

```
from sos import SoS_Script, Base_Executor
script = SoS_Script(f'whatever {parameter}')
executor = Base_Executor(script, config)
executor.run()
```

Then it makes sense to document a stable API for the execution of SoS scripts.

**Comment by BoPeng** [comment]
To avoid changing existing implementation, we could implement a wrapper, something like

```
from sos import execute_workflow

execute_workflow(script, args, targets, config)
```

**Comment by gaow** [comment]
> `executor = Base_Executor(script, config)`

I dont think this is the case now, is it? There still has to be a script written to disk before one can execute it? It would be wonderful to have `execute_workflow` wrapper, if `script` is the content of the SoS script not just a file name. I use this feature a lot but currently I have to write small temporary scripts to disk.

**Comment by BoPeng** [comment]
No. If you check our tests, `Base_Executor(script)` has been used from the beginning. The problem is that it is three step process (define workflow, define executor, and run) which is a bit long and can be changed in the future, so I would like to condense it to a single function wrapper.

**Comment by gaow** [comment]
I see. Well I actually used `cmd_run` whose input `args.script` has to be a script name. The code inside `cmd_run` involves somewhat complicated logic to determine which executor to use. So maybe even after you condense them I'd still have to use `cmd_run` to avoid them all; unless you revamp `cmd_run` by, eg replacing most of it with `execute_workflow`.

**Comment by BoPeng** [comment]
Yes, `cmd_run` is most general, and `execute_workflow` is intended to be used grammatically when scripts and configurations are specified directly.

**Comment by gaow** [comment]
Okay I guess when `execute_workflow` is available I should be able to replace my `cmd_run` calls with it because I do have content of scripts (as a string) and configurations (as a dictionary) in place.

**Comment by BoPeng** [comment]
```
>>> from sos import execute_workflow
>>> help(execute_workflow)
Help on function execute_workflow in module sos:

execute_workflow(script:str, workflow=None, targets=None, args=[], config={})
    Execute a SoS workflow with the following parameters:
    
    script:
        A (multi-line) string that defines one or more workflows.
    
    workflow (optional):
        Name of workflow to execute. This option can be ignored if
        ignored if the script defines a default workflow (with no name
        or with name `default`) or defines only a single workflow, or
        if the workflow is triggered by option "targets".
    
    targets (string or list, or sos_targets, optional):
    
    args (list or dict, optional):
        Command line arguments (a list in the format of "[`--name', 'value']")
        for workflow parameters defined in "parameter" statements. A dictionary
        (e.g. {"name", "value"}) is also acceptable and is equivalent to setting
        `config["workflow_vars"]'.
    
    config (dict, optional):
        Dictionary with the following configuration options. Please
        refer to output of "sos run -h" for details about each option.
            config_file: configuration file ("-c")
            output_dag: option "-d"
            output_report: option "-p"
            default_queue: option "-q"
            worker_procs: option "-j"
            max_running_jobs: option "-J"
            sig_mode: option "-s"
            run_mode: "run" or "dryrun"
            verbosity: option "-v"
            trace_existing: option "-T"

```

**Comment by gaow** [comment]
@BoPeng is there a way to pass configuration file as a dictionary, or do I still have to write it to disk before using it?  It would be nice to be able to do that and `execute_workflow` can therefore work without any files.

**Comment by gaow** [comment]
Also there seems a bug here: `verbosity` argument cannot be honored. eg, 

```python
>>> from sos.utils import env
>>> env.verbosity = 2
>>> from sos import execute_workflow
>>> script = '[1]\nprint(1)'
>>> status = execute_workflow(script)
INFO: Running 1: 
1
INFO: 1 is completed.
INFO: Workflow default (ID=df0c406bbdabcd34) is executed successfully with 1 completed step.
```

This uses the default verbosity setting in `env`. However when I try to override it,

```
>>> settings = {'verbosity': 0 }
>>> status = execute_workflow(script, config=settings)
INFO: Running 1: 
1
INFO: 1 is completed.
INFO: Workflow default (ID=df0c406bbdabcd34) is executed successfully with 1 completed step.
```

you see it does not work. I have to instead:

```python
>>> env.verbosity=0
>>> status = execute_workflow(script, config=settings)
1
```

**Comment by BoPeng** [comment]
>  is there a way to pass configuration file as a dictionary, or do I still have to write it to disk before using it?

Currently no because `load_config_files` checks `env.config['config_file']` and loads it. It is possible to allow `env.config['config_file']` to be dictionary (and then `load_config_files` will simply merge it), but it does not look good to have `config_file` not pointing to a file.

**Comment by gaow** [comment]
I agree ... can we rename `config` to `options`, and allow for `config` as a dictionary that will be merged to configuration after config file is loaded?

```
execute_workflow(script:str, workflow=None, targets=None, args=[], options = {}, config={})
```

I'd use this to put in some `host` settings without having to write yml files for different hosts.
