### ISSUE TITLE
Failed to start workers on host error

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1312]
With this configuration file on cluster: 

[midway2.yml.txt](https://github.com/vatlab/sos/files/3688929/midway2.yml.txt)

I get these errors:

[failure.txt](https://github.com/vatlab/sos/files/3688931/failure.txt)

for my job submitted. There are two types of messages:

```
ERROR: Failed to start workers on host midway2-0010: No hosts definition for local host localhost
```

and 

```
ERROR: Failed to start workers on host midway2-0010: No localhost could be identified from hostname, ip address, or a localhost key in config file
```

But my coniguration looks pretty innocent. I'm not sure what's the issue here ...

**Comment by BoPeng** [comment]
Not sure what is going on. Did you actually use `-c midway2.yml`?

**Comment by gaow** [comment]
Yes I did use it:

```
sos run GTEx_V8_Association.ipynb mnm     --gene-id-file 1000_genes.txt     --prop-test 0.4     --output-dir /project2/compbio/GTEx_eQTL/cis_eqtl_mnm_v8     -c midway2.yml -q midway2
```

It is the first time I run a template wiht `based_on`. Can it be the issue?

**Comment by BoPeng** [comment]
Check with sos config -c midway2.yml and see if things are expanded correctly.

**Comment by gaow** [comment]
It looks correct to me ...

**Comment by BoPeng** [comment]
The configuration file by itself is correct:
```
[MW] cat test.sos
task: walltime='1h', mem='1G'
print(1)

[MW] sos run test -c midway2.yml.txt -q midway2
INFO: Running default: 
INFO: f152cccfd778561c restart from status pending
INFO: f152cccfd778561c submitted to midway2 with job id 62867177
INFO: Workflow default (ID=a70bf382614cb889) is executed successfully with 1 completed step and 1 completed task.
```

The error message says:
```
ERROR: Failed to start workers on host midway2-0010: No hosts definition for local host localhost
```
which is an indication that sos tries to start a remote worker on `midway2-0010` but failed. I double checked that `midway2-0010` exists, so the problem should be failure to pass `-c midway2.yml` to the worker instance.... Let me try to reproduce.

**Comment by BoPeng** [comment]
I can reproduce the problem with
```
[MW] cat test.sos
input: for_each=dict(i=range(10))

task: walltime='1h', mem='1G', trunk_size=0, trunk_workers=[1]*2
import time
print(20+i)
```

**Comment by gaow** [comment]
Thank you! I wonder why this is the first time we see it thought ...

**Comment by BoPeng** [comment]
The problem is that 
```
sos execute {task_id}
```
does not catch the customized configuration file. Changing the template to

```
      sos execute {task} -v {verbosity} -s {sig_mode} -c /scratch/midway2/gaow/TempDir/midway2.yml.txt
``` 
fixes the problem (another arised), but we currently does not pass `config_file}` to template.

The problem after passing config file is

```
2019-10-04 08:56:32,746 - ERROR - Failed to start workers on host midway2-0389: Failed to connect to midway2-0389: ssh connection to midway2-0389 was prompted for password. Please set up public key authentication to the remote host before continue.
```
which should not happen between computing nodes and needs further investigation. Note that sos tests remote connection and ready to answer `yes` so we are not seeing the "known host" issue here.

**Comment by gaow** [comment]
Thank you @BoPeng for the forensic work! But I've been using this for long time (over a year for sure). Even with the new MPI approach I've been using it for at last the past month. Why is it appear broken now?

**Comment by BoPeng** [comment]
* Previously all tasks runs locally so there is no need for any configuration. But if a task uses something defined in customized configuration file, things can get ugly. What is even worse is that if user defines something in `~/.sos/config.yml`, which is different or missing from remote host, thing can get uglier.

* Whether not `config_file` should be pass to remote host. I briefly considered passing `{config_file}` in templates before but my conclusion was that `-c config_file` is local and might not be applicable on remote host, and decided not to pass `config_file` for problems cited above.

* By design the new remote execution feature on cluster treats hostnames as server name, so **there should be no need for localhost definition**. There can be a bug here.

**Comment by gaow** [comment]
I see -- previously for some pipelines I believe I hard coded `queue = 'midway2'` as a task option. That might be the reason those worked? They still run remotely but they have the information in the task itself I believe.

**Comment by BoPeng** [comment]
@gaow  I do not know what is going on, but when I submit a two node job, log in to one of the computing nodes, and ssh to another login node

```
[MW] ssh midway2-0177
gaow@midway2-0177's password: 
```
I am asked for a password. 

This is unexpected because I assume that all computing nodes have public key access, which is the way all the cluster systems I have seen are set up.

**Comment by gaow** [comment]
I confirm the behavior ... am not sure either. I can ask around. 

But if we submit from the login node it should work without an issue, if the bug is fixed. Is that the case?

**Comment by BoPeng** [comment]
I suspect that you can fix it by yourself by setting up public key authentication on cluster. I hope that I do not have to use mpiexec .

**Comment by gaow** [comment]
Sorry I still dont understand why it matters because I dont know why communication between compute nodes are involved -- if I submit on login node, then only log in node and compute node communicate, and that will not require password. Also my earlier workflows work but I hard-coded `queue = 'midway2'` in the workflow. So I suspect the issue you see above is not relevant?

**Comment by BoPeng** [comment]
After a multinode Jo's is submitted, the cluster allocate resources and provide a list of nodes as environmental variables. It then runs the script on the first node, which is the sos run or sos execute command.  The sos command realises that it is on a cluster, it starts workers on remote host by running something like ssh host sos  start 4 workers , and this is when ssh to remote host is needed. 

In an moi application the program is usually started with a mpiexec command.  It also starts workers on other nodes, but it uses some system moi library, not ssh.

**Comment by gaow** [comment]
I see. After I revert to version 0.20.3 I no longer see the issue, but that is because there was a bug in that version which didnt actually submit multi-node jobs. Now that the issue was fixed, we are having a problem. Is that the case? But I'm sure there has been some versions where I both see multi-node parallel computing and experienced no issues. I wonder what is going on here now.

**Comment by gaow** [comment]
I've already asked the admin of the cluster why this is the case but it would look like this has been like this for some time. Do you think we can have an option to collect user's password on the fly without saving it to any files, then use that to aid in `ssh` from one node to another?

**Comment by BoPeng** [comment]
You might be able to set up things by yourself. For example, https://sites.google.com/a/case.edu/hpc-upgraded-cluster/cluster-faq/how-to-set-up-ssh-without-password says "Here is the detailed step-by-step process to establish the SSH between the nodes and the servers".

**Comment by gaow** [comment]
The post suggest adding login node `id_rsa.pub` to its own `authorized_keys`. The idea does cross my mind initially but I thought for something like that to work it will require gathering all compute nodes `id_rsa,pub` for any two compute node to access each other which is not feasible. But on a 2nd thought I realize the keys are also shared because the file system is shared, so that ought to work!

I implemented that simple solution without adding in the `~/.ssh/config` file (also suggested on that page) and submitted the job:

```
cd ~/tmp/test
sos run test.sos -c test.yml
```

I then find that I can ssh from one compute node to another! That is as expected and is the good news. See below I was able to login to 2 nodes and quit:

```
[MW] exit
logout
Connection to midway2-0396 closed.
[MW] exit
logout
Connection to midway2-0171 closed.
[MW] # back at login node
```

However I see in the *err files : 

```
bash: -c: line 0: syntax error near unexpected token `('
```
and some long lines after which seems to come from running `SLURM_CHECKPOINT_IMAGE_DIR` definition. Is that some SoS induced syntax error then?

**Comment by BoPeng** [comment]
Update and try again. The problem is likely caused by the fact that sos tries to pass environment variables to remote hosts, and the value of a variable contains `(`. Read the patch if you want to understand what is going on.

Perhaps `mpiexec` can duplicate environments more elegantly ...

**Comment by gaow** [comment]
Ahh i see that line now. Well maybe something more complicated is going on with my environment copying -- this is what I'm seeing now in my err file

```
bash: 5: command not found
bash: 45:*.spx=38: command not found
bash: 5: command not found
bash: 45:*.xspf=38: command not found
bash: 5: command not found
bash: 45:: command not found
```

Here is the previous err file that has this long complicated environment that it tries to copy over:

[erro_1312.txt](https://github.com/vatlab/sos/files/3695529/erro_1312.txt)

hope that helps; or there is a more elegant solution.

**Comment by BoPeng** [comment]
please try to exclude them following my patch. I have tried but could not find a better way to pass variables.

**Comment by BoPeng** [comment]
; should be excluded because it is meaningful in command line.

**Comment by gaow** [comment]
I'm not sure what to do -- see file attached below. It apparently tries to copy not just random white spaces and `:` as you see in some of the error prompts, but also random extensions that we might not be able to completely rule out. 

[all_errors_new.txt](https://github.com/vatlab/sos/files/3695534/all_errors_new.txt)

Should we use some patterns to help?

**Comment by BoPeng** [comment]
I submitted a patch to a new branch `env`.

The patch is easy to understand. Instead of passing environment variables from command line of ssh, I 

1. pickle `os.environ` to a file
2. start `ssh worker sos worker` with option `ssh worker sos worker --env file`
3. In `sos worker`, update os.environ with pickled content. Because we assume file systems are shared, the file is not copied in anyway. I cannot use `/tmp` because computing nodes can have different `/tmp` even if they share `/home` and most other file systems.

 Here I assume everything under `os.environ` is string, and updating `os.environ` of the remote `sos worker` process would set environment for all subprocesses that worker spawns. Please let me know if the patch works.

**Comment by gaow** [comment]
Nice touch in principle but under `~/tmp/test` I get:

```
ERROR: Failed to start workers on host midway2-0365: Can't pickle local object '_createenviron.<locals>.encode'
WARNING: Failed to handle master push message ['task', {'task_id': 'bc0fb69468c58b6e', 'params': 1 (index=83), 'runtime': {'_runtime': {'verbosity': 2, 'sig_mode': 'default', 'run_mode': 'run', 'walltime': '00:15:00', 'cores': 4, 'mem': 4000000000, 'workdir': path('/scratch/midway2/gaow/TempDir/test'), 'max_mem': 64000000000, 'max_cores': 40, 'max_walltime': '36:00:00'}, 'bc0fb69468c58b6e': {}}, 'sig_content': {'bc0fb69468c58b6e': {}}, 'config': defaultdict(<class 'str'>, {'config_file': None, 'output_dag': None, 'output_report': None, 'wait_for_task': None, 'default_queue': '', 'worker_procs': ['midway2-0364:4', 'midway2-0365:4'], 'max_running_jobs': None, 'sig_mode': 'default', 'run_mode': 'run', 'verbosity': 2, 'master_id': '', 'SOS_DEBUG': set(), 'sockets': {'master_push': 'tcp://10.50.222.108:36994', 'master_request': 'tcp://10.50.222.108:38874', 'worker_backend': 'tcp://10.50.222.108:36617', 'result_push_socket': 'tcp://10.50.222.108:46542'}, 'exec_mode': None}), 'quiet': True}]: Failed to start workers on host midway2-0365: Can't pickle local object '_createenviron.<locals>.encode'
WARNING: Failed to load environment variables: Ran out of input
```

**Comment by BoPeng** [comment]
So my first assumption that `os.environ` contains only strings is wrong. Could you try to change
```
pickle.dump(os.environ, envfile)
```
to something like
```
pickle.dump({x:y for x,y in os.environ,items() if isinstance(y, str), envfile)
```

**Comment by gaow** [comment]
Now it is working as expected on that test data:

```
[MW] cat *.err
INFO: M20_5434951a20ca9851 started
INFO: 4 workers started on 10.50.222.109
INFO: M20_63eda7d9c1414275 started
INFO: 4 workers started on 10.50.222.109
INFO: M20_90a72850f4af7e03 started
INFO: 4 workers started on 10.50.221.172
INFO: M20_e3465156877592c0 started
INFO: 4 workers started on 10.50.221.172
INFO: M20_ff17b7323af4dd40 started
INFO: 4 workers started on 10.50.222.109
```

I've pushed the change. I also confirm the multi-core job on a node work as expected when I check by ssh into the node. I think we can finally resolve this issue?

**Comment by BoPeng** [comment]
Great. I will merge the branch. I will also take note for https://github.com/vatlab/sos/issues/1312#issuecomment-538831864 and refer to it in the documentation when it says "all computers, even computing nodes would need public key access".
