### ISSUE TITLE
Python module resolve after auto-install

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1313]
Here is an MWE:

```
[1]
depends: Py_Module('jupyter-book', autoinstall=True)
```

and the output: 

```
[GW] sos run test.sos 
INFO: Installing python module jupyter-book with command pip install -U jupyter-book
Collecting jupyter-book
  Downloading https://files.pythonhosted.org/packages/2c/bf/c544069fc01c2484ed96687ce5d1b9758c85552b2776d264bd40d535c525/jupyter_book-0.6.3-py3-none-any.whl (2.4MB)
...
....
Successfully installed jupyter-book-0.6.3
ERROR: No rule to generate target 'Py_Module("jupyter-book")', needed by '1'. Stop.
```

Perhaps this is because the import in Python should be `jupyter_book` not `jupyter-book`?

**Comment by gaow** [comment]
Indeed if I change it to `Py_Module('jupyter_book', autoinstall=True)` it will work. So it solves my problem for now. The question is if we should just document this exception, or we should implement something in general when module name from pypi does not match `import`

**Comment by BoPeng** [comment]
We discussed this before, and I think the solution was `Py_Module('jupyter_book', autoinstall='jupyter-book')`.

**Comment by gaow** [comment]
Yes we did discuss ... But I don't find it in docs so I thought it is in my head. Will add it to docs when I am back in office
