### ISSUE TITLE
Behavior of temp scripts & stderr/stdout files

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1315]
The problem starts from receiving this error on the screen of a colleague and I cannot reproduce with an MWE:

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
script_517901066375932888 in <module>
      saveRDS(list(Yhat=out), {_output:r})
      
----> """)
      remove_log(_output)
      

FileNotFoundError: 2
```

It says "FileNotFoundError" but it does not tell me what file it was trying to find which makes it hard to debug. I then looked into `sos status` and find these below:

```
[                9901] [                 100] [            -5.50705]
[Wed 23 Oct 2019 10:51:15 AM CDT] Finished SGVB inference
Error in file(con, "rb") : cannot open the connection
Calls: saveRDS ... <Anonymous> -> load_script -> ifelse -> readChar -> file
In addition: Warning messages:
1: In normalizePath(sub(needle, "", path)) :
  path[1]="/tmp/tmpuazro21v.R": No such file or directory
2: In file(con, "rb") :
  cannot open file '/tmp/tmpuazro21v.R': No such file or directory
Execution halted
```

So it looks like the call to `saveRDS` fails, which to my understanding can only happen of some compute nodes do not see the path? But that'd result in the R script fail, still not answering the question what SoS means by `FileNotFound` -- which file is it referring to? Then I see in the R script it used some tmp files which was also missing. That makes me wonder how SoS deal with copying temp files over to `.sos` folder to keep track of failed scripts. It should try to copy then if it does not exist should just let it go rather than fail -- is that the case? It would be nice if there can be more information from that error prompt. eg, a typically FileNotFoundError looks like:

```
>>> open('asdf.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'asdf.txt'

```

Now I'm only guessing what's going on there, and my guess was that this is about copying over tmp files?

Another possibility is if it is `stderr` or `stdout` files? Because `saveRDS` failed it is plausible that some disk issues occurred then naturally stderr and stdout files will be problematic. Will that trigger an error?

**Comment by BoPeng** [comment]
Hard to say without reproducing the problem, but we could do a catch/try around that block of code.

**Comment by gaow** [comment]
> Hard to say without reproducing the problem

Rerunning on his computer again it works now. But we tried multiple reruns since yesterday they all dont work. I've been trying to reproduce since but cannot reproduce it.

So all I have is that I've observed that for some reason there can be FileNotFoundError after execution of a step using `task` on cluster (never see that running jobs locally). yes i'm trying to guess what code chunk might involve looking for files, and if not essential we should wrap it with a try/catch.

**Comment by BoPeng** [comment]
So you see the error from command line but the error actually happens from a task? I am trying to see if the exception is throw from the step executor or task executor.

**Comment by gaow** [comment]
> So you see the error from command line but the error actually happens from a task?

I see the error `FileNotFoundError` printed in red on screen. However, that message seems to be a result of the failed task above. And the message is also found in `sos status -v4`. If I run that workflow locally then there is no issue. It is weird anyways that `saveRDS` did not work when sending it out as a task. That's why I had to guess it is related to task. However tracking back to the error,

```
DEBUG: completed: 10 failed: 1 running: 1
INFO: Waiting for the completion of 1 task.
  File "/home/fmorgante/Software/miniconda/lib/python3.6/site-packages/sos/step_executor.py", line 1997, in run
    yreq = runner.send(yres)
Traceback (most recent call last):   
  File "/home/fmorgante/Software/miniconda/lib/python3.6/site-packages/sos/step_executor.py", line 1997, in run
    yreq = runner.send(yres)
  File "/home/fmorgante/Software/miniconda/lib/python3.6/site-packages/sos/step_executor.py", line 1853, in run
    self.check_results()
  File "/home/fmorgante/Software/miniconda/lib/python3.6/site-packages/sos/step_executor.py", line 1240, in check_results
    raise self.exec_error
```

it seems to be with `step_executor` and that `self.exec_error` is a collection of execution errors that could have happened anywhere in the process. I was trying to identify where exactly it is, but without being able to  reproduce it is not easy task ...

**Comment by BoPeng** [comment]
Ok, that helped, because the exception was generated by the task, and was sent to the master and re-raised there.

**Comment by gaow** [comment]
Okay now I think i'm quite sure that the error was because when SoS tries to copy tmp file scripts like `/tmp/tmpm_6g5g_n.R` to under `.sos` folder when an exception occurs, and for some reason that file is not there either. And that causes the error. The worse thing here is that the task indeed fail, but because copying the script in question also fails then it appears as if something is wrong with SoS not the user. 

Is there a more robust way to deliver the problematic script in question instead of copy that from `tmp`? I bet there is, because the `tmp` file was initially written out to disk from SoS anyways?

**Comment by BoPeng** [comment]
But sos does not copy temp script at all. It [writes the script to a file under `.sos`](https://github.com/vatlab/sos/blob/b02310637ffb9c9f3486b1d497980a50de3e8b2b/src/sos/actions.py#L524). The problem might be with https://github.com/vatlab/sos/blob/master/src/sos/actions.py#L544 but in theory the temporary file created [with `delete=False`](https://github.com/vatlab/sos/blob/master/src/sos/actions.py#L379) should be there when error happens.

**Comment by BoPeng** [comment]
You can try branch 1315 but perhaps I should push to trunk since you cannot reproduce the problem now.

**Comment by gaow** [comment]
Okay yes I think 1315 definitely should be merged. I'm almost sure that's the problem. I thought it is when you copy it but it is reassuring (and make sense!) that they were written to the script directly. The reason the error was triggered by the task is that the R code tries to access the script and load it for book-keeping, but cannot find it. That is, the "theory" that "the temporary file created with delete=False should be there when error happens." was violated. 

The reason I cannot reproduce is because it doesnt happen every time. So I'm going to merge that branch now.

**Comment by BoPeng** [comment]
ok. Go ahead and merge. It at least does not do any harm if it cannot fix the problem.
