### ISSUE TITLE
Template for variable for task or workflow id

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1325]
Right now we use `{task}` for task_id in `task_template`, and `{workflow_id}` for workflow ID for `workflow_template`. These IDs are usually used for job name.

However, although this works all right if the variables are used in different templates, it does not work for `submit_cmd`, as in the example for task spooler where the ID should be specified from command line.

```
        submit_cmd: ts -L {workflow_id} sh {job_file}
```

In this case an template-neutral ID should be used for `submit_cmd` because `submit_cmd`, as defined, cannot be used for task submission.

**Comment by gaow** [comment]
How about calling both `job_id` and let the context decide if it is `task_id` or `workflow_id`?

We might have backwards compatibility issue ... but it wouldn't bother me.

**Comment by BoPeng** [comment]
`job_id` is currently used for

```
        status_cmd: ts -s {job_id}
        kill_cmd: ts -r {job_id}
```
but these two commands are not used at all right now for `sos-pbs`.

**Comment by gaow** [comment]
Hmm is it true that a good solution here is to use one variable name to refer to both type of ID's? How about just `job` then?

**Comment by BoPeng** [comment]
Or job_name as it is used for such purpose anyway. It is also easy to keep backward compatibility (allow both job_name and task )

**Comment by BoPeng** [comment]
Use `job_name` now.
