### ISSUE TITLE
MPI again does not work for SLURM

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1326]
The MWE is on my cluster under `~/tmp/test`, and also here:

[test_mpi.tar.gz](https://github.com/vatlab/sos/files/3885201/test_mpi.tar.gz)

To reproduce on cluster:

```
$ sos run test_run.sos -c test.remote_config.yml 

INFO: M5_8a92d80e7e9ad9cc submitted to midway2 with job id 63994483
INFO: M5_97292d7ca56392cd submitted to midway2 with job id 63994484


INFO: Waiting for the completion of 2 tasks.
INFO: Waiting for the completion of 2 tasks.
INFO: Waiting for the completion of 2 tasks.
INFO: Waiting for the completion of 2 tasks.
WARNING: Task M5_8a92d80e7e9ad9cc inactive for more than 79 seconds, might have been killed.
WARNING: Task M5_97292d7ca56392cd inactive for more than 79 seconds, might have been killed.
ERROR: [d46bfe9c-2fb0-49a2-ac2b-3d6383af25e5]: [t]: [t]: Failed to get results for tasks 8a92d80e7e9ad9cc, 69e710ba8201e568, 8abf95d3ff9b6d74, 8f265e81d1291206, 1b8ff498fb82e065
[fc7915cd-32ef-4230-a9f9-3e3f8d2498b1]: [normal]: [normal]: Failed to get results for tasks 97292d7ca56392cd, 7a72d7510a6a2104, 9adeb8cbdc002809, 49d850e1f94aaf9f, eb8acfabd9f007c0
[default]: 13 pending steps: default, h_sq_err, g_abs_err, f_sq_err, e_abs_err, d_sq_err, c_abs_err, b_sq_err, a_abs_err, g_median, e_mean, c_median, a_mean


```

As you can see, all jobs now fail. However if I change all `trunk_workers` from `[4] * 10` to just `4`, that is, not using MPI, then everything works and the workflow completes very quickly.

**Comment by BoPeng** [comment]
The job ends with TIME LIMIT, so appears to be a communication problem between nodes.

```
WARNING: INFO: M5_97292d7ca56392cd started
INFO: 4 workers started on 10.50.222.214
slurmstepd-midway2-0469: error: *** JOB 64176758 ON midway2-0469 CANCELLED AT 2019-12-06T22:03:50 DUE TO TIME LIMIT ***
```

**Comment by gaow** [comment]
But it does not explain why using `trunk_works = 4` it works. Also the job should end instantly -- it should take a second to complete the workflow steps.

**Comment by BoPeng** [comment]
Initial guess is that the remote worker did not start, but in that case all jobs should be sent to local workers... Still checking.

**Comment by BoPeng** [comment]
It is an unfortunate bug that I introduced when I tested remote workers.... Too bad we do not have tests for true PBS systems.
