### ISSUE TITLE
Dealing with empty stdout and stderr files in `action`

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1327]
Currently, my step action setting looks like this:

```
R: expand = "${ }", stderr = f"{_output:n}.stderr", stdout = f"{_output:n}.stdout"
```

That is, there are companion `stderr` and `stdout`` file output for a substep that generate some results.

However for a benchmark workflow involving millions of output files these can be really painful to have. Especially with a cluster file system that has limits to number of files allowed (eg UChicago cluster!!). I wonder if we can change the behavior to this:

1. If `stderr` and/or `stdout` variables are empty then do not write the corresponding file.
2. If `stderr` and/or `stdout` variables are empty but the file already exists (from a previous run), then remove the corresponding file.

the 2nd behavior can help when a large number of substeps fail due to some errors in the code that later got fixed. It makes sense to then remove the files since the current run no longer produce any `stderr` anymore.

**Comment by gaow** [comment]
@BoPeng does the proposal above make sense to you? If so I can make the change if you point me to the code, before I run some large simulation experiments again, to avoid hitting cluster file count limit ...

**Comment by BoPeng** [comment]
Yes. The relevant code should be in actions.py
