### ISSUE TITLE
Stop exposing get_output and expand_pattern?`

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1337]
As shown in https://vatlab.github.io/sos-docs/doc/user_guide/sos_functions.html, both functions have simple enough python implementations and do not really deserve being in SoS API.

**Comment by BoPeng** [comment]
These could become 
```
from sos.utils import get_output
```

**Comment by BoPeng** [comment]
@gaow I would like to stop exposing `path` and `paths` to users as well, because these are very common names that would likely be overwritten by user scripts. I also would like to hide `path`, `paths`, `file_target`, `sos_targets` etc to make SoS a bit more flexible for future development (and place less burden on documenting these internal data types).

My only use of `paths` in any of my workflows is 

```
%run workflow --samples {paths(samples)}
```
so that `samples` would be expanded with `' '.join(var)`, and I do not really mind expanding it.

**Comment by gaow** [comment]
This will definitely break many workflows I have, including the ones for the SoS manuscript. I use them quite often except `expand_pattern`. I agree `paths` is not as often used but I believe I also use it to convert a list of string to `path` objects. 

How about a less intruding approach, that we allow for both exposing and explicit import for a while, as I try to catch it up changing at least those workflows I share with other people and for our manuscript then remove them?

**Comment by BoPeng** [comment]
OK, of the following, which ones have you used in your scripts?

* `path`
* `paths`
* `file_target`
* `sos_targets`
* `get_output`
* `expand_pattern`
* `logger`

**Comment by gaow** [comment]
Thanks -- the ones I use a lot are `path`, `paths`, and `get_output`.

**Comment by BoPeng** [comment]
A formal way to solve such problems is to make use of 

```
#fileformat=SOS1.0
```
and import the symbols for 1.0, but not for 1.1. However, even if you have it in your `.sos` file, it is not included in `.ipynb` workflows.

**Comment by BoPeng** [comment]
OK, these will become hidden features (not documented), and I will advertise the use of

```
from sos.targets import path, paths
from sos.utils import get_logger, get_output
from sos.pattern import expand_pattern
from sos.eval import interpolate
```
or something like
```
from sos.utils import path, paths
from sos.utils get_logger, get_output
from sos.utils import expand_pattern
from sos.utils import interpolate
```
if these are really needed.

**Comment by gaow** [comment]
Thanks! The latter would be much easier, and maybe as part of the API, `from sos import ...`? having to import them from different sos modules is a bit confusing from user standpoint.

**Comment by BoPeng** [comment]
Yes, `from sos import ...` would be easier, just like `from sos import execute_workflow`, although `execute_workflow` is for the execution of workflows from Python, and others are meant to be used inside sos scripts.

**Comment by BoPeng** [comment]
OK, I have removed `path`, `paths` from https://vatlab.github.io/sos-docs/doc/user_guide/sos_datatypes.html .
