### ISSUE TITLE
Confusion with output `group_with`

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1339]
We have gone back and forth with how to use `output: paired_with` and `output: group_with`.

For `paired_with`, it boils down to **variable applies to all targets in `output` statement, be they `_output` or `step_output` with `group_by`**. That is to say, a single value is required for `_output`, 

```
output: _input.with_suffix('.bak'), paired_with=dict(sample=_input.sample)
```

and an array is required for

```
output: out_files, group_by=1, paired_with=dict(sample=samples)
```
as described [here](https://vatlab.github.io/sos-docs/doc/user_guide/output_groups_vars.html).

And then we have a different set of rules for `group_with`. That is to say

1. If `group_with` a single variable (scalar), we use it directly
```
output: _input.with_suffix('.bak'), group_with={'var':  1}
```
2. If `group_with` an array, we require it to have the same number of elements as number of substeps,
```
output: _input.with_suffix('.bak'), group_with={'var':  [1, 2, 3]}
```
3. We do this regardless of `output: group_by`.

The problem with this approach is that it is inconsistent with `paired_with`, and it is not possible to associate arrays with the group.

I think it makes more sense to treat `group_with` the same as `paired_with`, in the sense that,

1. If `output` defines `_output`, `group_with` attaches whatever to `_output`.
2. If `output` defines `step_output` (with `group_by`), `group_with` works the same as `input` in that it split variable for each substep.

The problem with this change is that

```
output: _input.with_suffix('.bak'), group_with='sample'
```
will have to be changed to
```
output:  _input.with_suffix('.bak'),  group_with=dict(sample=sample[_index])
```

@gaow  How would this change affect your workflows?

**Comment by gaow** [comment]
@BoPeng I dont use `group_with` often. I mostly only use `group_by`. I'm quite comfortable with behavior of `paired_with` though, and a consistent behavior makes more sense.

**Comment by BoPeng** [comment]
Changed with new behavior documented  [here](https://vatlab.github.io/sos-docs/doc/user_guide/output_groups_vars.html).
