### ISSUE TITLE
Docker pull globally, instead of per substep in a step

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1343]
Currently for a step using docker containers it pulls the image for all substeps. Also, for the same workflow when multiple steps use the same docker image it got pulled at every step too. I think it would be much better if the pull happens only once per image per workflow.

**Comment by BoPeng** [comment]
I think we discussed this before and the conclusion was that `docker pull` is relatively fast and does not need to be optimized? It seem to be dangerous if we run `docker pull` from multiple substeps concurrently but perhaps it is ok since there is only one docker daemon?

**Comment by gaow** [comment]
> Also, for the same workflow when multiple steps use the same docker image it got pulled at every step too.

Sorry I was wrong about this. It does seem to only pull at the first step it is used. But it pulls it multiple times:

**Comment by gaow** [comment]
> that docker pull is relatively fast and does not need to be optimized? 

Well, when there is thousands of substeps this can be tricky ...

**Comment by BoPeng** [comment]
In theory we could have

```
input: for_each=dict(rev=('111', '222', '333'))

run: container=f'something:{rev}'
  script
```
so each substep needs to pull container anyway....

**Comment by gaow** [comment]
Hmm true. But if thousands of substeps share a few docker image as we can determine it, will it be easy to change the code and make it pull only the unique images it involves and do it sequentially?

**Comment by BoPeng** [comment]
OK, this can be done through a `docker_container(name)` target that `docker pull` would create automatically and send to controller, and each substep would ask the controller the existence of the target when it is trying to pull.... 

I assume this is not urgent though since I am trying my best to complete the documentation. https://vatlab.github.io/sos-docs/workflow.html#content . I have about 1/3 left.

**Comment by gaow** [comment]
Great! The proposal is reasonable although it sounds like an additional line of code users have to put in there. 

It is not urgent for the reason that we dont have many clients (at least not here in Chicago) running thousands of substeps via docker -- because our cluster does not allow it and I've yet to figure out singularity. For the scale of desktop based applications  pulling it multiple times seems fine. I'm about to share that workflow with someone from outside the university for them to run thousands of genes but i'm sure they wont work on it until after new year anyways :) Thanks for catching up with the documentation (they'll need to read that too)!!

**Comment by gaow** [comment]
Hmm got feed back from an external user on this who does not have the docker image on his computer so each substep was trying to pull independently a few GB of docker image. They dont conflict but he claims it is slow, and that `docker pull` directly beforehand is "much quick" to quote his words -- he indeed remove all cache and do fresh download each time so the comparison should be fair.

The command in question if you want to test it: first pull [this repo](https://github.com/percylinhai/rvnpl-notes) then run under the repo's root, 

```
sos run analysis/NPL_Simulation.ipynb simulate
```

**Comment by BoPeng** [comment]
Test script
```
input: for_each=dict(i=range(10))

sh: expand=True, container='ubuntu'
    echo {i}
```

behavior
```
$ sos run test
INFO: Running default: 
HINT: Pulling docker image ubuntu
HINT: Pulling docker image ubuntu
HINT: Pulling docker image ubuntu
HINT: Pulling docker image ubuntu
HINT: Pulling docker image ubuntu
HINT: Pulling docker image ubuntu
4
2
0
5
3
1
INFO: default (index=4) is completed.
INFO: default (index=2) is completed.
INFO: default (index=0) is completed.
INFO: default (index=5) is completed.
INFO: default (index=3) is completed.
INFO: default (index=1) is completed.
7
8
6
9
INFO: default (index=7) is completed.
INFO: default (index=8) is completed.
INFO: default (index=6) is completed.
INFO: default (index=9) is completed.
INFO: Workflow default (ID=ec0e525834e5cb89) is executed successfully with 1 completed step and 10 completed substeps.

```

**Comment by BoPeng** [comment]
Substeps can be submitted to remote hosts where they have separate docker daemon, so problem will arise if we only ask the master process to `pull` image, and the image would only be available to workers on the master node.

There is however a possibility that docker images are stored on shared storage so the downloaded image would be instantly available to docker daemon on other hosts, but this is just a hypothesis.

**Comment by BoPeng** [comment]
New behavior

```
$ sos run test
INFO: Running default: 
HINT: Pulling docker image ubuntu
0
5
INFO: default (index=0) is completed.
2
3
INFO: default (index=5) is completed.
4
1
INFO: default (index=2) is completed.
INFO: default (index=3) is completed.
INFO: default (index=4) is completed.
INFO: default (index=1) is completed.
6
INFO: default (index=6) is completed.
7
9
8
INFO: default (index=7) is completed.
INFO: default (index=9) is completed.
INFO: default (index=8) is completed.
INFO: Workflow default (ID=ec0e525834e5cb89) is executed successfully with 1 completed step and 10 completed substeps.
```

The patch is very simple, but might fail due to the reason I stated. Basically,

1. When a substep needs a docker image, it asks controller if the image is available.
2. The controller will
  * if it never heard of it, it marks it `pending` and replied `help yourself`
  * if the resource is registered, return its status, which could be `pending`, or `available`
3. If the substep hears
  * `help yourself`, it will go ahead and pull the image, and tell the controller the resource is `available` after it is done.
  * `pending`, then some other substep is downloading it, it will simply wait and ask again after 0.5s.
  * `available`, return

In this way the first substep will download the image and other substeps will be waiting until the first one completes and marks the image as available.

**Comment by BoPeng** [comment]
I believe this has been fixed in the new sos release. I have also completed updating documentation (except for a bug in singularity which renders it unusable, and some undecided features such as `map_vars`).
