### ISSUE TITLE
Deprecating a few task options

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1348]
https://vatlab.github.io/sos-docs/doc/user_guide/task_statement.html#Task-Options lists all the tasks options that are currently supported, but some of them do not seem to be useful.

* `concurrent`. I have never encountered a case that tasks should be execute sequentially. Even if this is true, `input: concurrent=False` should take care of it.

* `active`: we already have `skip_if` etc but we did keep `sh: active=`... so this is border line.

* `env`: this is not useful at all because we are not sure which `env` we are changing, local or remote. In addition, we do have host-specific `task_template`

* `prepand_path`, the same... this should be gone for the same reason.

* `map_vars`: this suppose to allow the translation of path for specified `host`, in addition to `workdir`, `_input` and `_output`, but I have never used it...

* `to_host`, `from_host`: files to be synchronized in addition to `_input`, and `_output`. Again, I have never used them.... 

The problem with `map_vars` and `to_host` and `from_host` is that if we are at a point that we should carefully consider mapping of variables and transfer of additional files, we should forget about "portability" and write tasks for a specific remote host.

@gaow Let me know which ones you have ever used...

**Comment by gaow** [comment]
Am traveling this week. In my daily pipelines I  use none of them. In
generated DSC benchmarks I use prepend_path. Not sure about env I thought
we have discussed in another ticket and decided to keep it. What is the
difference here?  That other discussion was for actions right?

On the go. Sorry for short text.

**Comment by BoPeng** [comment]
`prepend_path` is a simplified version of `env={'PATH': new_path : os.environ('PATH')}`. As I said, the problem is that we do not know if `PATH` is local or remote, and it should not exist as general task option... 

I am almost done with my rewrite of documentation... after this the documentation should be readable by others and I should perhaps find a student who does not know sos at all and see if it is understandable...

**Comment by gaow** [comment]
> prepend_path is a simplified version of env

In that case I'm cool to remove or at least hide `prepend_path`. I can adjust my script to use `env`.

> the problem is that we do not know if PATH is local or remote

True, but most cases for, for example conventional pipeline tool users (snakemake) the PATH is shared on all nodes under the same HPC environment. I am thinking of the notion of "not make simple task harder" ...

**Comment by BoPeng** [comment]
> . I am thinking of the notion of "not make simple task harder" ...

I think the general rule for all cluster systems is **not executing long-running jobs on headnodes**. That means executing a workflow on the headnode, submit tasks to a cluster system, and wait for the completion of the tasks are not recommended even not allowed.

So basically there are two recommended ways to work with cluster systems

1. Execute workflows on a desktop or laptop and submit large jobs to cluster system, in which case there will be local and remote paths, thus all the confusions.
2. Execute the entire workflow on the cluster system with option `-r`, then the workflow needs to be written specially for the cluster system. This problem is not important to you because you are running simulation codes, but important to me because I need to use all sorts of tools and paths...

**Comment by gaow** [comment]
In our system it is possible to submit an SoS command to a compute node which submits jobs from there. So we dont have to work with case 1 above. 

>  I need to use all sorts of tools and paths...

I though the solution we discussed earlier is to use config files to set values in `env`?

**Comment by BoPeng** [comment]
> I though the solution we discussed earlier is to use config files to set values in env, if we dont want to bother with specifically setting up task templates?

Yes, `task_template` is the ultimate solution but `env` and `prepend_path` are quick patches to make a task work for specific host.

I just realized that `prepend_path` is not a shortcut for `env={'PATH'...}` because `env` are evaluated locally so setting `env={'PATH': 'more/path':os.environ['PATH']}` will not work. Instead, `prepend_path` is done on the remote host before the task is executed, so it is actually prepending to `$PATH` on remote host.

Now, since both options have their value, and actually allows the execution of tasks with different `PATH` on the same `host`, it makes sense to keep them. (This is very similar to the argument of `env` for actions).

**Comment by BoPeng** [comment]
Finally decided to keep `to_host` and `from_host` but removed the dictionary options (which is the source of confusion), and deprecated `map_vars`.
