### ISSUE TITLE
Standard output with -v0

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1349]
Given the workflow

```
print(1)
sh:
  echo 2
```
we have

```
$ sos run test -v0
1
```

```
$ sos run test -v1
[1
2
#] 1 step processed (1 job completed)
```

```
$ sos run test -v2
INFO: Running default: 
1
2
INFO: default is completed.
INFO: Workflow default (ID=bfbe8a3fe680bd19) is executed successfully with 1 completed step.
```

Basically I think

1. The behavior of `-v0` is quite strange because it shows output of some statement (regular python statements), but not others (from action).

2. The behavior of `-v1` is also problematic because it outputs regular output, which messed up with the progress bar anyway.

So perhaps the following makes sense.

1. With `-v0`, we shutoff output from regular python statement as well, so basically there would be no output except for errors.
2. Then with `-v0` we can output a progress bar, which will not be disturbed by regular output.
3. With `-v1` we have outputs, but not sos messages.
4. With `-v2` we have both outputs and sos messages.
...

@gaow  The current behavior was proposed by you, any thought?

**Comment by gaow** [comment]
For actions, we have `stderr` and `stdout` options which controls the behavior of output on screen. I wonder if we should rely on these options and not let verbosity levels play a role there?  Then for python statements, `-v0` and `-v1` both silence them with `-v1` outputting progress bar (such that progress bar dont get disrupted), and `-v2` will show them all with default SoS messages. My problem with your proposal is `-v0` outputs progress bar. Also I think behavior of actions should be controlled case by case at user's discretion.

**Comment by BoPeng** [comment]
`-v2` is `INFO` so it is natural to show `Executing step 10`. It is fine to show both.

With your proposal, there is no level to show "user-generated output only", which is nice to have if we want to execute the workflow as a "script" without showing any workflow related messages. I think this should be `-v1`.

Then progress bar has to be with `-v0`.

**Comment by gaow** [comment]
I agree with the limitations with my proposal. Can we add a `-v -1` for absolutely no screen output at all ... ?

**Comment by BoPeng** [comment]
Perhaps we should separate progress bar from `-v`? Too bad `-p` is already taken (rePort) but it is natural to have `-v0` (silent), `-v1` (script output), `-v2` (sos info), `-v3` (debug). And something like `-P` for progress bar, although it only makes sense to use with `-v0`. We could let `-P` implies `-v0` though.

**Comment by gaow** [comment]
I was hesitate about adding a new option ... progress bar is not a very
often used feature. How does `-v 0.5` sound :P ?

On the go. Sorry for short text.

**Comment by BoPeng** [comment]
Why do you want an absolute silent -v0 then?

**Comment by BoPeng** [comment]
You could actually do -v0 2> /dev/null if you do not want the progress bar.

**Comment by gaow** [comment]
I thought by definition v0 should be silent for having zero extra
information. But compared to having another option for progress bar I am
okay with using v0 for it as you proposed.

On the go. Sorry for short text.
