### ISSUE TITLE
Support for singularity 3.3

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1352]
Running the following workflow,
```
run:  container='docker://ubuntu', engine='singularity'
  echo 'Echo'
```
SoS hangs at
```
$ sos run test
INFO: Running default: 
echo 'Echo'
Echo
[    1.417143] reboot: Power down
INFO: default is completed.
```

The workflow works ok if I remove the `engine` part so it does not look like a problem with the SoS executor. What is happening is that the step completes and send the controller a message, but the controller never received it....  Really curious what is going on here.

**Comment by BoPeng** [comment]
Fixed.

**Comment by gaow** [comment]
I'm testing `singularity` using docker image. The following works well.

```
[1]
R: container='docker://gaow/susie', engine='singularity'
  library(susieR)
  dat = read.table('test.txt')
  print(dat)
  saveRDS(dat,'test.rds')
```

It successfully reads `test.txt` and writes to `test.rds` no permission or mounting issues. The only "problem" is that the singularity images got converted to my `$HOME`. Is it the default path for `singularity` to look for images? I wonder if there is a way to customize it, and maybe by default set the path to `$HOME/.sos`?

**Comment by BoPeng** [comment]
Yes, I currently simply call `singularity pull image url` where `image` will be saved in current directory. I am not familiar with singularity well enough to know if there is any setting to control the destination, or is it worthwhile to save images by default to something like `~/.sos/singularity/library`.

**Comment by gaow** [comment]
According to [this page](https://singularity.lbl.gov/build-environment) the files should be under `~/.sigularity` which makes sense. But although I do see files under that folder, the image appears as a temporary file:

```
[MW] ll .singularity/cache/oci-tmp/1f3fd6204b3a41fbc7b34ddcf6e088c97699d8cec2c533051784daaa67b93d91/
total 461M
-rwxr-xr-x 1 gaow gaow 461M Dec 29 21:29 atac-gwas_latest.sif 
```

you see the file is 461M, same as the downloaded image under my `$HOME`

```
[MW] ll ~/gaow-atac-gwas.sif 
-rwxr-xr-x 1 gaow gaow 461M Dec 29 21:30 /home/gaow/gaow-atac-gwas.sif
```

so there are two copies of the same file now.

**Comment by BoPeng** [comment]
Technically speaking we should run 

```
singularity exec URL
```
and let singularity manages images and caches, instead of running
```
singularity pull IMAGE URL
singularity exec IMAGE
```
as we currently do. 

I do the latter because SoS will have control over the downloading of image (instead of letting each substep requesting the URL), and feel more comfortable in having a local `IMAGE` somewhere...

I think the central question is whether or not we want to keep permanent copies of the images. If not, we can let singularity download (and handles multiple pull request from substeps), or try to use its cache if we can figure out the naming rules (bad idea since these are unstable and can change from version to version).

**Comment by gaow** [comment]
> `singularity exec URL`

Yes I do see `singularity run docker://IMAGE_URL` command on itst documentation page.

> whether or not we want to keep permanent copies of the images.

I dont see why we should do it. At least for docker engine we don't.

>  If not, we can let singularity download (and handles multiple pull request from substeps)

Will it try to use cache by default? That seems a smart thing to do. I agree we should not try to mess with cache. `singularity run` (or `exec`) should have a way to handle it.

**Comment by BoPeng** [comment]
Could you try to run a few concurrent `singularity exec` and see if singularity can handle it ok?

**Comment by BoPeng** [comment]
BTW, my use case is that I run `singularity` locally and test workflow, and then copy the image to the cluster to run in production mode. SoS will use the image directly in this case, and will fail if it tried to access network (headnode does not have access to singularity hub dockerhub etc).

So the design was somehow tailored to my use case.

**Comment by gaow** [comment]
concurrent `singularity pull` does not report a race condition but i think they are doing the work twice (still not smart enough). So a global `pull` in this case makes sense (#1343). 

> will fail if it tried to access network (headnode does not have access to singularity hub dockerhub etc).

Good point. Then it does make sense to save a local copy somewhere `singularity` can find it. It is not clear from the documentation how to customize that path, though.

**Comment by BoPeng** [comment]
Are you sure singularity will use the cache even if we do

```
singularity pull IMAGE URL
singularity exec IMAGE
```

My understanding is that a cache is needed only for
```
singularity exec URL
```
because a hidden image is needed anyway.

**Comment by gaow** [comment]
> Are you sure singularity will use the cache even if we do

I'm sure it is the other way around as I just tested it.  

I agree on clusters it is more likely that a compute node does not have internet access and we have to provide `sif` file beforehand. So the current mechanism makes sense. It's just a matter of how to save those images to outside `$HOME`. On our HPC, `$HOME` folder only has 25GB space.

**Comment by BoPeng** [comment]
OK, assuming that it is unsafe to try to use the same cache as singularity, we have two choices:

1. Use `singularity exec URL` for
```
run: container='shub:...'
  script
```
add action `singularity_pull` and let users do  

```
singularity_pull(image.sif, URL)
run: container='image.sif'
```
if they want an image for cluster.

PROS: this reflects the true workflow
CONS: pull from substeps can be slow, and we need to make sure `singularity_pull` does nothing if `image.sif` exists to make the workflow runnable without internet access.

2. Instead of `singularity_pull` action, provide an option
```
run: container='shub:...', pull_as='image'
   script
```
to simplify option 1. Basically users can specify an image file, and SoS will not pull if the file already exists.

3. Keep the current behavior but allow the specification of image directory, something like  `$SOS_SINGULARITY_CACHE`.

Option 2 seems to make most sense.

**Comment by gaow** [comment]
For option 2, a concern is the interface compatibility with using docker containers. For now, what I do is:

```
[global]
parameter: container_engine = 'docker'
...
[...]
R: container='docker://gaow/susie', engine=container_engine
￼```

this way I can switch between running docker and singularity. For this reason, something along the lines of 3 would work best.

**Comment by BoPeng** [comment]
But are you concerned with having two copies of the image? I still think it is dumb for singularity to download files to its cache then copy to `IMAGE` for command

```
singularity pull IMAGE URL
```
if this is indeed what it is doing.

**Comment by gaow** [comment]
> But are you concerned with having two copies of the image?
Not so much now that I understand how it works; and how it suppose to work on most HPC (that direct `pull` will not work due to lack of internet). Because I'll now just keep `rm -r ~/.singularity` to free up my `$HOME` after I download successfully the `sif` file I need to elsewhere on the cluster, before they come up with something smarter.

**Comment by BoPeng** [comment]
You can try to make the following work and push:

```diff
diff --git a/src/sos/singularity/client.py b/src/sos/singularity/client.py
index 7a066124..1dcf0acb 100644
--- a/src/sos/singularity/client.py
+++ b/src/sos/singularity/client.py
@@ -214,7 +215,20 @@ class SoS_SingularityClient:
             if ctx == 'file':
                 return image
             else:
-                return cname.replace('/', '-').replace(':', '-') + '.sif'
+                lib_path = path(
+                    os.environ['SOS_SINGULARITY_LIBRARY']
+                ) if 'SOS_SINGULARITY_LIBRARY' in os.environ else path(
+                    '~/.sos/singularity/library')
+                if not os.path.isdir(lib_path):
+                    try:
+                        os.makedirs(lib_path, exists_ok=True)
+                    except:
+                        raise RuntimeError(
+                            f'Failed to create singularity library directory {lib_path}'
+                        )
+                return os.path.join(
+                    lib_path,
+                    cname.replace('/', '-').replace(':', '-') + '.sif')
```

**Comment by gaow** [comment]
Worked after fixing a typo `exists_ok` to `exist_ok`. I've moved those images I downloaded tonight to outside `$HOME` now :D

**Comment by BoPeng** [comment]
Thanks. You can document this in `https://vatlab.github.io/sos-docs/doc/user_guide/singularity.html` if you have time. Actually I could not finish this tutorial because `singularity build` does not work on mac now (`FATAL:   Only remote builds are supported on this platform`) and you may be able to get it working under linux.

**Comment by gaow** [comment]
i've added a section for `SOS_SINGULARITY_LIBRARY` (did not compile HTML) but the build does not work on my end either. 

```
[GW]  /usr/local/bin/singularity build lolcow.sif library://GodloveD/lolcow
INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: while getting image info: request did not succeed: Bad image reference provided collection ref is not valid: GodloveD (400 Bad Request)
```

**Comment by BoPeng** [comment]
Thanks. The error was because the example URL no longer exist. Perhaps you can try to use some other image from the doc, like one with `library:...`?

**Comment by BoPeng** [comment]
We have a bug here. When `SOS_SINGULARITY_LIBRARY` is defined and `image.sif` is used, SoS will try to locate it in the current directory and fail. Instead SoS should look into `SOS_SINGULARITY_LIBRARY`. On the other hand `file://image.sif` should check local `image.sif` only, because `file://` is supposed to point to a file location directly.

**Comment by BoPeng** [comment]
Fixed. Documentation is also updated using a Linux VM.
