### ISSUE TITLE
Support for positional argument

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1353]
Just a random thought that if we could support positional arguments so that users can do

```
sos-do something
```
when `sos-do` is a sos script with `#!/usr/bin/env sos-runner`.

Note that currently the command line only supports `-` options from `sos`, and `--` for parameters, and does not allow positional argument.

**Comment by gaow** [comment]
We currently have `sos run script.sos step` it is already 3 positional arguments ... I think it is too much for additional ones.

**Comment by BoPeng** [comment]
Yes, technically speaking this is not possible since `step` is optional so SoS would not be able to differentiate between

```
sos-do workflow
sos-do param
sos-do workflow param
```
