### ISSUE TITLE
Simplify the use of named path with special syntax

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1356]
Right now we have

```
path(name='home')
```
to get to host-dependent `home` directory. We also rely on path translation between local and remote host for translation.

I would propose that

1. We stop translating paths so that any path will be treated as it is, no confusion.
2. We extend the `path(name='home')` syntax to allow for

```
input: `#home/blah`
task: workdir='#home/blah'
...
```

In this way we are not confused with any path translation stuff and the code can be easily portable.

**Comment by BoPeng** [comment]
@gaow This will be a big change but should not affect you because you have been working on head node of cluster, right?

**Comment by gaow** [comment]
No it would not have an impact on my existing workflows.

**Comment by BoPeng** [comment]
Done.
