### ISSUE TITLE
sos status command failure

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1360]
I got this report from a user but I dont have access to and cannot test that particular cluster: 

```
ERROR: Failed to obtain params of task 777db0bbabe3a204:
WARNING: Check output of sos status  -v 3  --numeric-times    failed: Command 'sos status  -v 3  --numeric-times   ' returned non-zero exit status 1.
WARNING: Failed to query status of tasks on farnam:
```

I'm asking for more diagnostic information on their end and post to this ticket. @BoPeng if you have  suggestions please let me know and i'll ask them to get and report the information.

**Comment by BoPeng** [comment]
This particular error message means the task file is corrupted so `sos status` failed to read the header. It maybe a result of concurrent read/write, or abrupt interruption of something. The way to proceed is to `sos purge` the task and resubmit, or remove the `~/.sos/tasks/777*` files if `sos purge` fails.

I am not sure how to debug the root of the issue without steps to reproduce it though. On a related though, the test coverage of sos is currently only 68%,, and I will have to raise it to around 90% to claim it "production" grade, yet it cannot prevent errors like this.

**Comment by gaow** [comment]
@BoPeng thank you. The purge command worked. We'll resubmit and see the outcome.
