### ISSUE TITLE
`dryrun` does not work with `-q none` when we want it for debug purpose

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1365]
Asking this issue that @dianacornejo ran into:

```
(base) [dc2325@farnam2 ~]$sos dryrun pleiotropy_UKB/SAIGE_binary_UKB.ipynb step1 -q none
ERROR: KEY=VALUE pairs are required for definitions after queue name.
```

where `step1` has a `task` line that looks like:

```
task: trunk_workers = 1, trunk_size = job_size, walltime = '48h', mem = '60G', cores = numThreads, tags = f'{step_name}_{_output:bn}'
```

`sos run` with `-q none` however, will work, as we always do to switch between submitting HPC jobs or run them locally. Can we make it work for `dryrun` too so (new) users will be able to debug the workflow syntax?

**Comment by BoPeng** [comment]
Fixed. Note that `-q none` is deprecated because `sos run` now requires explicit queue name such as `-q localhost`. To test submission of task under dryrun mode, use `-q localhost`.
