### ISSUE TITLE
switch between conda environment

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1367]
@BoPeng before I complain on SoS repo, I just want to quickly check -- do we have an option to use some conda environment? we currently tried this:

```
bash: expand = "${ }", workdir = cwd, ... env={'PATH': f"/gpfs/ysm/project/dewan/dc2325/conda_envs/RSAIGE/bin
:{os.environ['PATH']}"}   
    Rscript ...
```

but that `Rscript` command complains about some library not found. So it is apparent that setting `$PATH` is not good enough for conda environments ... How do we properly load conda environments? Typically in `conda` it is just 

```
conda activate some_env
```

then run the commands in the same bash environment after it is activated. When we run `R` after that `conda activate` we can load the library we want without a problem. I'm not sure how to do that in SoS.

**Comment by BoPeng** [comment]
Implemented options `template` and `template_name`, of course tests are currently lacking.

See https://vatlab.github.io/sos-docs/doc/user_guide/sos_actions.html#Option-template-and-template_name for details.

**Comment by BoPeng** [comment]
Let me know if it works, and what other templates you would like to add as system default. I think `module load` should be one.

**Comment by gaow** [comment]
I'm looking at the interface: why do we have to use `cmd` and `script`? Should we stick to `script` because `cmd` is just part of bash script?

**Comment by BoPeng** [comment]
for 
```
sh: 
   echo 1
```
we have `script` as
```
echo 1
```
and `cmd` being
```
sh /tmp/whatever.sh
```

The template can choose to extend `{cmd}`, or do something directly with `{script}`.

**Comment by gaow** [comment]
@BoPeng thank you this makes sense. I've modified the pipeline on our end. I'll hear what they have to say about the result (I dont run the pipeline myself) and close the ticket if the feature works fine.

**Comment by BoPeng** [comment]
I have tried to limit myself to 1 open-source day (sos, variant tools stuff) per week so I will leave the tests to next week, but the implementation is straightforward and I do not expect any major bug. Please feel free to let "they" try and let me know if they encounter any problem or have any comments.

**Comment by gaow** [comment]
Our limited tests in practice confirms the feature works. I'll close the ticket for now until we have an issue.

**Comment by dianacornejo** [comment]
@BoPeng we are implementing the template option as stated below:
```
conda_tpl = '''
conda activate {saige_env}
{cmd}
'''
```
```
bash: expand = "${ }", workdir = cwd, ... template=conda_tpl
Rscript...
```

And we got this error after running the pipeline

```
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

```

To fix this issue we added the following lines to the `.bash_profile`. As indicated from this discussion [https://github.com/conda/conda/issues/7980)] on activating conda from a bash script

```
export -f conda
export -f __conda_activate
export -f __conda_reactivate
export -f __conda_hashr
```

So far the pipeline seems to be working fine with the `template` option.

**Comment by BoPeng** [comment]
Why do you have to implement your own version? The official way to do this is through `conda run` command, which is provided as a system template [here](https://github.com/vatlab/sos/blob/master/src/sos/actions.py#L355). You therefore only need to do

```
sh: template_name='conda', env_name='whatever'
```

**Comment by gaow** [comment]
Sorry my bad. I was not pointing to the right section of reference on the documentation. This approach works perfectly as well.

**Comment by BoPeng** [comment]
sos 0.21.6 is released with this new feature and a few other bug fixes.
