### ISSUE TITLE
Signatures are ignored for workflow actions after nested workflow

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1373]
Here is the MWE:

```
[to_be_nested]
parameter: input_file = str
parameter: output_file = str
input: input_file
output: output_file
bash: expand = True
  sleep 5
  echo done > {_output}


[default]
input: '1.txt'
output: f'{_input:n}.a', f'{_input:n}.b'

sos_run('to_be_nested', input_file = _input, output_file = _output[0])

bash: expand = True
  echo "I am being executed"
  sleep 5
  echo done > {_output[1]}
```

The problem is that when this workflow is executed twice in a row, supposedly all computation should be skipped the 2nd round, but it is not the case:

first run,

```
$ touch 1.txt
$ sos run test.sos 
INFO: Running default: 
INFO: Running to_be_nested: 
INFO: to_be_nested is completed.
INFO: to_be_nested output:   1.a
I am being executed
INFO: default is completed.
INFO: default output:   1.a 1.b
INFO: Workflow default (ID=66acb2efba52ab38) is executed successfully with 2 completed steps.
```

second run, part of the workflow is still executed:

```
$ sos run test.sos 
INFO: Running default: 
INFO: Running to_be_nested: 
INFO: to_be_nested (index=0) is ignored due to saved signature
INFO: to_be_nested output:   1.a
I am being executed
INFO: default is completed.
INFO: default output:   1.a 1.b
INFO: Workflow default (ID=66acb2efba52ab38) is executed successfully with 1 completed step and 1 ignored step.
```

**Comment by BoPeng** [comment]
This is also by design, because sos does not keep signatures for steps with subworkflows. This will give SoS a chance to visit the subworkflow and check if anything over there has been changed and needs rerun. An obvious example is that if the code for a subworkflow has been changed but the master step has not, the substep would not be executed.

**Comment by gaow** [comment]
Okay, then I guess the recommended alternative is to use two separate steps for it?

**Comment by BoPeng** [comment]
Yes, perhaps `depends: sos_step` would also work, but separate step is more straightforward for complex cases.

**Comment by gaow** [comment]
I was able to reimplement my pipeline and get it work. Ideally when truly nothing is changed the computation should be skipped regardless of implementation (nested workflow or not) but current design choice is not too limiting anyways. It's okay with me if we label it `wontfix` and close the ticket.

**Comment by BoPeng** [comment]
Yes, ideally sos should be able to track the content of the nested workflow, but in really this is very difficult as even name of workflows can be dynamic.. and nested workflows can call nested workflows. 

We could solve the problem partially by recording the content of the entire file, but then we have `sos_run(source='another_file')`.

I suppose I will keep the ticket open as reference for future discussions.
