### ISSUE TITLE
output_from does not complain when named key is wrong

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1378]
Here is MWE:

```
[default_1]
output: any_name='1.txt', correct_name = '2.txt'
bash: expand = True
  touch {_output}

[default_2]
input: output_from('default_1')['wrong_name'], output_from('default_1')['correct_name']
bash: expand = True
  echo {_input}
```

as you can see the first input of 2nd step has wrong name. But instead of complaining about it , SoS just ignored it, so only one input file is printed:

```
$ sos run test.sos -s force
INFO: Running default_1: 
INFO: default_1 is completed.
INFO: default_1 output:   1.txt 2.txt
INFO: Running default_2: 
2.txt
INFO: default_2 is completed.
INFO: Workflow default (ID=dbd95549e2814b54) is executed successfully with 2 completed steps.
```

I have not tested in general behavior of `_input['name']` . I am now only using it with `output_from` but I suspect this is a more general bug involving using keys to reference input.

**Comment by BoPeng** [comment]
`sos_target['name']` means getting all targets with label `name`, so if there is no such label nothing would be returned.

At some point I was doing something like picking files from two groups, but missing data was tolerated so the existing behavior worked well.

**Comment by BoPeng** [comment]
Note that

```
[1,2,4][5]
```
would raise an error, but
```
[1,2,4][5:]
```
will just return empty list.

```
>>> sos_targets(a=['1.txt', '2.txt'], b='3.txt')['a']
[file_target('1.txt'), file_target('2.txt')]
>>> sos_targets(a=['1.txt', '2.txt'], b='3.txt')['c']
Unspecified
```
was meant to be a "slice" operator to get multiple items and is similar to the latter.

**Comment by BoPeng** [comment]
It would make sense to let  `targets['name']` raise an error but allow some sort of `tagets.get('name', [])` to return empty even other stuff when `name` does not exist. Unfortunately `targets.get()` is now used for variables so we have to think of something like `targets.with_name()`.

**Comment by gaow** [comment]
Yes something along this line is better. I didn't know the behavior of slice (a bit surprising to me). But the `target['name']` syntax looks like dictionary keys so I would expect it raise errors. 

I cannot think of a good syntax for the other behavior at this point ... but will post when I have a suggestion.

**Comment by BoPeng** [comment]
A straightforward solution is to add a warning message. Note that we have

```
SOS_DEBUG=WORKER,CONTROLLER
```
etc to essentially control `-v3` (debug) and I plan to deprecate `-v4` , we could do something like

```
SOS_WARNING=SYNTAX
```
to enable/disable particular warning messages.

**Comment by BoPeng** [comment]
Give out a warning and prepare to enable `SOS_WARNING`.
