### ISSUE TITLE
Peak memory used for a task

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1389]
Currently, `sos status task_id -v4` dose not show the peak memory for a task. Do we monitor this, or there is an option to add for it? I seem to recall when we submit using SoS notebook interface there are some peak memory monitors? This would be useful to debug and adjust my failed tasks due to insufficient memory.

**Comment by BoPeng** [comment]
The information were in HTML output, but not in `-v4`. It could be added.

**Comment by gaow** [comment]
Thank you @BoPeng . We are working on a pipeline that this feature would be very useful. I wonder if it would be possible to code it for `-v4` so we can use it to monitor our pipeline memory usage and make adjustments.

**Comment by BoPeng** [comment]
ok, will have a look soon(ish). It might already be there. I mean the memory is recorded every 1 minute so no such information will be collected for short jobs.

**Comment by gaow** [comment]
> I mean the memory is recorded every 1 minute so no such information will be collected for short jobs.

I think that's good enough ... or we can use job template to control that? We are running association analysis on UK Biobank data; each job can take hours if not days. But I hope peak memory usages lasts for more than 1 minute so we can see it.

**Comment by BoPeng** [comment]
ok, the problem had something with the graphic output, which was broken but not fixed because we needed some JS library to display the figure but it was too much trouble to keep the dependency. The output was therefore changed but the command line did not catch up.

Please try the latest master.

**Comment by gaow** [comment]
Thank you @BoPeng I've asked my team to run and report back. I take that the problem is solved but I'm yet to hear from them. I'll confirm when I get the result.

**Comment by gaow** [comment]
We confirm it works as expected. It has been helpful for us to revisit resource usage for some of our pipeline steps.

**Comment by BoPeng** [comment]
It is not a priority task but I noticed that sos uses about 50M of RAM for simple sleep command, which could be optimized.
