### ISSUE TITLE
Hosting a public SOS Jupyter server.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#139]
We can host a public SoS jupyter server so that users can test sos directly from their browser. Of course we can set up some special mode (e.g. `sos_interactive_timeout`) to limit the time the commands execute, and provide a few example scripts/notebooks. Our variant tools server might be able to do this...

**Comment by BoPeng** [comment]
This is technically easy but the server that hosts variant tools cannot sustain any computation (it is a webserver).

**Comment by BoPeng** [comment]
It would be great if we could host a server that allows users to test sos with Python, R etc remotely, without installing anything. I am not sure but the server can be hosted at amazon cloud...

**Comment by BoPeng** [comment]
I suppose the easiest method is to connect to a docker machine with jupyter notebook on, but I am having trouble getting the IP address of the docker-image running `mdabioinfo/sos-full`.

**Comment by jma7** [comment]
I tried to change the last line of your sos_full Docker file to:

> ENV TINI_VERSION v0.6.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
RUN chmod +x /usr/bin/tini
ENTRYPOINT ["/usr/bin/tini", "--"]
EXPOSE 8888
CMD ["jupyter", "notebook", "--port=8888"]



Then in the Docerfile folder:
> docker build -t mdabioinfo/sos_full .
docker run -d -p 8888:8888 --name sos_full mdabioinfo/sos_full

After build and run, it seems the server is started in the docker machine. 
This is the output from docker logs sos_full:

> [I 16:56:51.477 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
[I 16:56:51.487 NotebookApp] Writing notebook server cookie secret to /home/mdabioinfo/.local/share/jupyter/runtime/notebook_cookie_secret
[I 16:56:52.155 NotebookApp] [nb_anacondacloud] enabled
[I 16:56:52.159 NotebookApp] [nb_conda] enabled
[I 16:56:52.230 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 16:56:52.230 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
[I 16:56:52.234 NotebookApp] Serving notebooks from local directory: /home/mdabioinfo
[I 16:56:52.234 NotebookApp] 0 active kernels 
[I 16:56:52.234 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 16:56:52.235 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 16:56:52.235 NotebookApp] No web browser found: could not locate runnable browser.

**Comment by BoPeng** [comment]
Great. Thanks. I just sent you an invitation to collaborate. Please accept and push the change. 

I also tried to add sos to `jupyter/datascience-notebook` to create `mdabioinfo/sos-notebook`, but I cannot get some bioconductor packages installed. Could you remove the bioconductor part (or make it work if you can) and make it runnable as well? I suppose the [datascience-notebook](https://github.com/jupyter/docker-stacks/tree/master/datascience-notebook) image already has the command to start jupyter server but I am not sure.

**Comment by BoPeng** [comment]
BTW, option `--no-browser` could be used to suppress the last warning.

**Comment by BoPeng** [comment]
tmpnb.org hosts public jupyter server

**Comment by jma7** [comment]
Essentially follow the steps from https://github.com/econchick/scapy-tmpnb with some modification:
##### 1. Make sure "EXPOSE 8888" is in the Dockerfile of docker-notebook.
##### 2. Create ubuntu 14.04 instance, with public IP and 20GB, expose port 8000 and 22. 
##### 3. Download the key from amazon ec2 and ssh into the instance. 
##### 4. Install Docker in the instance:
    sudo apt-get update -y
    wget -qO- https://get.docker.com/ | sh 
    sudo usermod -a -G docker ubuntu

    exit out of ssh, and ssh back in (for usermod to take effect)
    test that docker works with docker info

##### 5. Build sos-notebook.
    git clone https://github.com/BoPeng/SOS.git,  
    cd  ~/SOS/misc/docker-notebook
    docker build -t mdabioinfo/sos-notebook:latest .

##### 6. Run sos-notebook with tmpnb
    docker pull jupyter/tmpnb
    export TOKEN=$( head -c 30 /dev/urandom | xxd -p )
    docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN --name=proxy    jupyter/configurable-http-proxy --default-target http://127.0.0.1:9999
    docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN --name tmp_sos -v /var/run/docker.sock:/docker.sock jupyter/tmpnb python orchestrate.py --image='mdabioinfo/sos-notebook' --command="ipython notebook --NotebookApp.base_url={base_path} --ip=0.0.0.0 --port {port}"

Right now, the URL is http://54.89.117.159:8000/.

**Comment by BoPeng** [comment]
This is cool! Could you map a folder to the docker image so that it can have access to certain folder in the VM (e.g. `/home/someuser/examples`)? We will need to put a few examples there so that everyone can open and play with the notebooks.

It also makes sense to make the `examples` directory read-only, while allowing users to create notebooks in a writable folder in the docker so that visitors can change and save (temporarily) notebooks but cannot modify the examples.

**Comment by BoPeng** [comment]
One a second thought, it would be easier to add the examples to the docker image. In this way the users can change the examples and/or create new ones as much as they like, and everything will be restored once the session ends.

**Comment by BoPeng** [comment]
I just released a new version of sos. Please add `examples/example.ipynb` and `examples/NotebookTutorial.ipynb` to `mdabioinfo/sos-notebook` and restart the notebook server.

**Comment by BoPeng** [comment]
I cannot access the URL, is it because of IP address change or because it only allows one connection?

**Comment by jma7** [comment]
I cannot access neither. So I restart the instance, the examples are there. However, every time the instance restarts, the IP address changes. Now the IP address is
http://52.23.218.234:8000/
It now allows 10 connections. I think it could be set to allow more.

**Comment by BoPeng** [comment]
Can we get a more stable IP address or URL? We can request a domain name if needed. The server would be frequently restarted as we update sos and/or add more examples, and it is painful to update `README.md` to reflect different IP addresses.

**Comment by BoPeng** [comment]
I suppose we need an elastic IP address. We will be charged when the instance dies, which makes me a bit uncomfortable. Will we be notified if our EC2 instance dies?

**Comment by jma7** [comment]
The Elastic IP address is http://34.192.184.206:8000/. I am not sure if we will be notified since the account is not linked to my email.

**Comment by BoPeng** [comment]
I have updated `README.md` with URL `ec2-34-192-184-206.compute-1.amazonaws.com`. This is an elastic IP so will not change at least before we switch to another account.

**Comment by BoPeng** [comment]
It is currently a bit difficult to re-start the public server after sos is updated. It would be helpful to use the amazon aws cli tool to automatically update the server with each sos release. The steps should be inserted to `development/release.sos`.
