### ISSUE TITLE
step_output not defined at the end of remote task with from_host

### ISSUE THREAD

**Issue by lucasrla** [vatlab/sos#1395]
I have just stumbled on an error with `step_output` not being defined. I am not sure if it is a bug or if it's just me not understanding how `step_output` and `from_host` behave.

Here are the relevant files:

```sh
# ~/.sos/hosts.yml
localhost: mbp
hosts:
  mbp:
    paths:
      home: /Users/{USER_NAME}
  ec2:
    address: ec2-user@{IP_ADDRESS}
    pem_file: {PATH_TO_PEM_FILE}
    paths:
      home: /home/ec2-user/
```

```sh
# remote_test.sos
[new]
input: "new_input.txt"
output: "new_output.txt"
task: queue='ec2'
sh: expand=True
    ls; mv {step_input} {step_output}; ls

[to_from_test]
input: "new2_input.txt"
output: "new2_output.txt"
task: to_host="new2_other_file.txt", from_host="remote_file.txt", queue='ec2'
sh: expand=True
    ls; mv {step_input} {step_output}; ls

[bo_peng_test]
output: 'aws_output.txt'
task:
sh: expand=True
  echo I am on $HOSTNAME > {_output}
```

`new_input.txt`, `new2_input.txt`, and `new2_other_file.txt` are just dummy files on `mbp`. `remote_file.txt` is a dummy file on `ec2`.

I ran:

```sh
# the following line runs just fine
# as discussed in https://github.com/vatlab/sos/issues/1392
sos run remote_test.sos bo_peng_test -q ec2

# this one also works fine
sos run -v4 remote_test.sos new

# here is the command that causes the error
sos run -v4 remote_test.sos to_from_test
```

The verbose 4 output is as follows:

```sh
INFO: Running to_from_test:
DEBUG: _input: new2_input.txt
DEBUG: Signature mismatch: Missing target new2_output.txt
DEBUG: Signature mismatch: Missing target new2_output.txt
INFO: 737b5e385adb837b re-execute completed
INFO: 737b5e385adb837b sent new2_input.txt to ec2
INFO: 737b5e385adb837b sent 'new2_other_file.txt' to ec2
INFO: 737b5e385adb837b started
INFO: 737b5e385adb837b completed
DEBUG: Failed to create signature: input target /home/ec2-user/new2_input.txt does not exist
DEBUG: completed: 3
INFO: 737b5e385adb837b received 'new2_output.txt' from ec2
  File ".../lib/python3.8/site-packages/sos/__main__.py", line 642, in cmd_run
    executor.run(args.__targets__, mode=config['run_mode'])
Traceback (most recent call last):
  File ".../lib/python3.8/site-packages/sos/__main__.py", line 642, in cmd_run
    executor.run(args.__targets__, mode=config['run_mode'])
  File ".../lib/python3.8/site-packages/sos/workflow_executor.py", line 347, in run
    return self.run_as_master(targets=targets, mode=mode)
  File ".../lib/python3.8/site-packages/sos/workflow_executor.py", line 1651, in run_as_master
    raise exec_error
sos.executor_utils.ExecuteError: [to_from_test]: Failed to interpolate rsync -a --no-g -e 'ssh -o 'ControlMaster=auto' -o 'ControlPath=/Users/{USER_NAME}/.ssh/controlmasters/%r@%h:%p' -o 'ControlPersist=10m' -i '/Users/{USER_NAME}/.ssh/{PEM_FILE}.pem'  -p 22' ec2-user@{IP_ADDRESS}:/home/ec2-user/{step_output} "/Users/{USER_NAME}": name 'step_output' is not defined
ERROR: [to_from_test]: Failed to interpolate rsync -a --no-g -e 'ssh -o 'ControlMaster=auto' -o 'ControlPath=/Users/{USER_NAME}/.ssh/controlmasters/%r@%h:%p' -o 'ControlPersist=10m' -i '/Users/{USER_NAME}/.ssh/{PEM_FILE}.pem'  -p 22' ec2-user@{IP_ADDRESS}:/home/ec2-user/{step_output} "/Users/{USER_NAME}": name 'step_output' is not defined
```

Here is what I find puzzling:

1. How can it be that `step_output` works fine within `new` and `bo_peng_test` but is not defined at the end of `to_from_test`? (Is `from_host` being left out of the string expansion?)

2. Why is `rsync` trying to get `{step_output}` if, as per line `INFO: 737b5e385adb837b received 'new2_output.txt' from ec2`, the local machine has already received `new2_output.txt`, which is `step_output` itself?

Thank you in advance for your help and insights, @BoPeng.

**Comment by BoPeng** [comment]
First, `step_output` should not be used directly, because it is undetermined when multiple substeps run in parallel. `_output` is recommended as it is the variable for each substep. `step_input` is the same as `_input` when there is no substeps.

So your workflow `new` works, but should better be written as:
```
[new]
input: "new_input.txt"
output: "new_output.txt"
task: queue='ec2'
sh: expand=True
    ls; mv {_input} {_output}; ls
```

The `to_from_test` workflow works well if I do not use `PEM_FILE` variable, but failed to interpolate if I do. This is a consequence of https://github.com/vatlab/sos/issues/1394 . Let me see if there is a quick fix.

**Comment by BoPeng** [comment]
I submitted a patch to master to expand `pem_file`. However, it appears that


```
pem_file: {PATH_TO_PEM_FILE}
```
is interpreted as a dictionary by pyyaml, and you would need to do

```
pem_file: '{PATH_TO_PEM_FILE}'
```

**Comment by lucasrla** [comment]
The `to_from_test` workflow is working perfectly now.

As per your instructions, I:

1. upgraded my pip package to your latest commit
2. added `"` `"` to make sure my `pem_file` value from `hosts.yml` is interpreted as a string
3. used `_output` instead of `step_output`

I clearly misunderstood `_output` and `step_output`. I thought `step_output` was the "reliable" one, not `_output`. Maybe it was the `_` at the beginning that made `_output` seem less "reliable" to me (i.e., sometimes not set, depending on step/workflow specifics).

Thank you again!

**Comment by BoPeng** [comment]
`_output` was used because `output` is too common and its counterpart `input` is a Python function that should not be overridden. In general `step_output` is accumulated from `_output` as an product of the execution of a step (that can be used in another step).

In your case `{PEM_FILE}` was parsed as a dictionary `{'PEM_FILE', None}`) so I have added a warning if the value of `pem_file` (and other keys from the config file) is not string.
