### ISSUE TITLE
Docker does not automatically mount input and output file paths

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1398]
I'm surprised we didnt run into this problem before -- when we use docker to analyze files outside current work directory it turns out we have to explicitly mount the input and output paths. Otherwise it will not work:

```
 volumes = [f'{_input:d}:{_input:d}', f'{_output:d}:{_output:d}']
```

Should we always include these paths in the mount switch so users do not have to specify this (if they ever realize it is an issue at all because currently the error message just says some files are not found but they are actually there on the host computer)? Of course we can drop that if it is a duplicate with other default volume mounts.

**Comment by BoPeng** [comment]
Cannot quite remember the arguments but what if users need to map the directory to something else inside the image?

**Comment by gaow** [comment]
Sure, then they can override it with `volumes = [f'{_input:d}:something_else']`?

**Comment by BoPeng** [comment]
So we have to check if users specify `input` to avoid duplicated `-v`? I guess this is doable.

**Comment by gaow** [comment]
> So we have to check if users specify input to avoid duplicated -v?

Yes we should avoid duplicates in `-v` and also allow for `volumes` to override our default mounts

**Comment by BoPeng** [comment]
Please let me know if the patch works as expected. I am a little worried about overlapping paths such as

```
-v /path:/path -v /path/path1:/path/somethingelse
```

**Comment by gaow** [comment]
@BoPeng sorry for the delayed update. Yes it does seem to work as expected! 

I'm working with some docker + singularity based pipeline, and will try for the first time running singularity on our cluster. I might post some more issues the next couple of days hopefully we can fix them, then release a next version.

**Comment by gaow** [comment]
This particular issue is fixed but I'm having other problems that I've not finished debugging yet -- could be my problem or SoS. I'm closing this for now. Maybe we can hold on to the release for a couple more days?
