### ISSUE TITLE
Display progress or status of docker / singularity pull

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1399]
I got this message running a container using `singularity` engine:

```
RuntimeError                              Traceback (most recent call last)
script_1780078351431037236 in <module>
----> bash('gatk -h\n', container='docker://gaow/gatk4-annovar', container_engine='singularity')
      

RuntimeError: Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

The problem is apparently SoS tries to use `docker pull`. But for Singularity, it should be 

```
singularity pull docker://gaow/gatk4-annovar
```

I'm currently running this command separately to get a singularity image for SoS to use. But it would be nice to fix up the automatic pull with SoS along the lines of the command above.

**Comment by gaow** [comment]
Also, currently we have the prompt:

```
INFO: Pulling image ...
```

but without screen output to the progress. Then actually after the images are pulled and the actual workflow starts, we still see this line above as if the pull has not been completed (or hang), even though we are actually already running some analysis and way past the image pull. Perhaps it might be better to just allow for the original output printed to the screen?

**Comment by gaow** [comment]
Other than these 2 comments above, singularity based SoS workflow worked great for our project. I'm cool with a new release.

**Comment by BoPeng** [comment]
> 
> The problem is apparently SoS tries to use `docker pull`. But for Singularity, it should be

https://github.com/vatlab/sos/blob/master/src/sos/singularity/client.py#L281

We are using singularity pull. Maybe the action did not use singularity client.

**Comment by BoPeng** [comment]
> ----> bash('gatk -h\n', container='docker://gaow/gatk4-annovar', container_engine='singularity')

This should be `engine='singularity'`, not `container_engine`. See https://vatlab.github.io/sos-docs/doc/user_guide/singularity.html#Options-container-and-engine

**Comment by gaow** [comment]
Ahh sorry my bad. Okay i've changed the title of the ticket to focus on the `INFO` issue. If we don't show the full screen output, at least we should print an INFO line saying the pull has completed?

**Comment by BoPeng** [comment]
Changed, but I am not sure if it is a good idea to contaminate notebooks with progresses. You can try and let me know if you like this behavior. I am neutral.

**Comment by gaow** [comment]
Thanks @BoPeng . The behavior of pulling an existing image is acceptable I think:

```
INFO: Running 1: 
HINT: Pulling docker image debian:bullseye-slim
bullseye-slim: Pulling from library/debian
Digest: sha256:0d8ed7153c06b2ce26b0ae6c8832219d211869e6a88f4f3f11599cf34779c24d
Status: Image is up to date for debian:bullseye-slim
docker.io/library/debian:bullseye-slim
INFO: 1 is completed.
INFO: 1 output:   test_dir/test.txt
INFO: Workflow default (ID=7ff537b1265b7e0b) is executed successfully with 1 completed step.
```

But I can imaging having lots of unnecessary outputs for first time pull. Since you are neutral about it, I changed it back to the old behavior but adding a line of message underneath so users would not be wondering if it is the pull hangs, or the actual computing is taking place. 

Looking forward to a new release!

**Comment by BoPeng** [comment]
0.21.14 is released.
