### ISSUE TITLE
`pytest` for sos-pbs?

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1400]
I'm reporting an issue with PBS job submission but before the main issue let me point out this line that I see when I use `-v4`:

```
INFO: Running STEP_1: 
DEBUG: Failed to load workflow engine pbs: No module named 'pytest'
DEBUG: submit M2_571b7d27504106d1: qsub ~/.sos/tasks/M2_571b7d27504106d1.sh
INFO: M2_571b7d27504106d1 submitted to csg with job id 730353
```

nothing fails but it is just a nuisance -- pointing it out in case this can be fixed quickly

**Comment by BoPeng** [comment]
Fixed. Not sure how it landed there.
