### ISSUE TITLE
SGE issue with multiple jobs per node

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1401]
On our cluster system, with `trunk_size` larger than 1, we run into an error. Here is the script that triggers it:

```
[STEP_1]
A = [1,2,3,4,5,6]
input: for_each = "A"
task: trunk_workers = 1, trunk_size = 2, walltime = '4h',  mem = '1G', tags = f'{step_name}'
bash: expand = "$[ ]"
        echo $[_A]
```

and job template: https://github.com/cumc/bioworkflows/blob/master/GWAS/csg.yml, with command to run:

```
sos run test.sos -c GWAS/csg.yml -q csg -v4
```

Error message below shows the line in question:

```
INFO: M2_571b7d27504106d1 started
  File "/home/gw2411/miniconda3/lib/python3.8/site-packages/sos/__main__.py", line 2521, in main
    args.func(args, workflow_args)
Traceback (most recent call last):
  File "/home/gw2411/miniconda3/lib/python3.8/site-packages/sos/__main__.py", line 2521, in main
    args.func(args, workflow_args)
  File "/home/gw2411/miniconda3/lib/python3.8/site-packages/sos/__main__.py", line 1363, in cmd_execute
    exit_code.append(executor.execute(task))
  File "/home/gw2411/miniconda3/lib/python3.8/site-packages/sos/task_executor.py", line 89, in execute
    res = self.execute_master_task(task_id, params, runtime,
  File "/home/gw2411/miniconda3/lib/python3.8/site-packages/sos/task_executor.py", line 387, in execute_master_task
    n_nodes, n_procs = self._parse_num_workers(env.config['worker_procs'])
  File "/home/gw2411/miniconda3/lib/python3.8/site-packages/sos/task_executor.py", line 560, in _parse_num_workers
    n_workers = int(val.rsplit(':', 1)[-1])
ValueError: invalid literal for int() with base 10: 'UNDEFINED'
```

So I printed near line 560 the variable `num_workers`. It says:

```
['node42:1:all.q@node42:UNDEFINED']
```

@BoPeng I guess the number you would like to extract is the `1` right after the first `node42`. But unfortunately the convention here is different. Is there are more robust approach to this?

**Comment by BoPeng** [comment]
Is this standard PBS? Looks like this should be defined by the cluster environment variable and `UNDEFINED` should usually be a number?

**Comment by BoPeng** [comment]
Could you define `SOS_DEBUG=WORKER` and see the output of the following function?

 https://github.com/vatlab/sos/blob/master/src/sos/utils.py#L1860

I just want to understand what variables are defined by your cluster.

**Comment by gaow** [comment]
I added `export SOS_DEBUG=WORKER` to my `bashrc` then 

```
>>> from sos.utils import get_nodelist
>>> print(get_nodelist())
None
```

which returns nothing. `~/.sos/sos_debug.log` is also empty. Is this the right way to check it?

**Comment by BoPeng** [comment]
No. The code only triggers when the task is submitted and executed by the cluster, so you will have to add export stuff in the template. I can fix the bug from your description of it is difficult to do.

**Comment by gaow** [comment]
Thank you @BoPeng I did some digging into it. Turns out we are SGE and I added a line of `print` here:

```
    elif "PE_HOSTFILE" in os.environ:
        with open(os.environ["PE_HOSTFILE"], 'r') as hosts:
            args = [':'.join(host.split()) for host in hosts]
        env.log_to_file('WORKER', f'Using "-j {args}" on a SGE cluster.')
```

it says `('PE_HOSTS', ['node29:1:all.q@node29:UNDEFINED'])` .

**Comment by BoPeng** [comment]
So it is SGE, something I was not able to test. I will submit a patch this afternoon.

**Comment by gaow** [comment]
Oh that's great! Do you need more information from my end or additional test for it?

**Comment by BoPeng** [comment]
Could you try again? You can manually edit the file in place if it is difficult to compile the master branch of sos on cluster nodes.

**Comment by gaow** [comment]
@BoPeng it works!

**Comment by BoPeng** [comment]
sos 0.21.15 is released for this fix.
