### ISSUE TITLE
Direct specification of for_each context?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1403]
My real use case is a lot more complex but in essence with multiple for loops and exceptions we have to do the following in SoS:

```python
input: for_each=[ {'var1': range(5)}, {'var2': range(5)}]

skip_if(var1 == var2)
```

Then when processing the data in Python I have to do
```python
for var in range(5):
  for var1 in range(5):
    if var == var1:
      continue
```

For these cases the following method might be cleaner:

```python
contexts = []
for var in range(5):
  for var1 in range(5):
    if var == var1:
       continue
    contexts.appen(dict(var=var, var1=var1)

input: for_each=contexts
```

basically we construct contexts directly and free `sos` from doing this, and the code can be easier to understood for users.

@gaow What do you think? Of course interface is another issue.

**Comment by gaow** [comment]
I think i've done `contexts` approach for some of my applications -- doesn't it work with the current SoS implementation?

**Comment by BoPeng** [comment]
Hmm, at least the current list of duct syntax means something else.  Did you simply loop through contexts and refer to its content as dictionary key?

**Comment by gaow** [comment]
Ha okay my usage is in DSC. For example a DSC module like this

```
method: 
  n, p: (10, 20), (10, 5)
  @FILTER: n>p 
```

Will be translated to the following `for_each` code in SoS:

```
input: for_each = {'_n,_p,_DSC_REPLICATE':[(_n,_p,_DSC_REPLICATE) for _DSC_REPLICATE in DSC_REPLICATE for _p in p for _n in n if (_n > _p and _n == 10 and _p == 5) or (_n > _p and _n == 10 and _p == 20)]}
```

so yes technically I use the context notion but my approach is to create the exact SoS syntax automatically like this. ...

**Comment by BoPeng** [comment]
ok, currently `for_each` is designed to to cross-product of multiple variables, less so for irregular context, for which something like

```
input: for_each = [
  {'A': 1, 'B': 2},
  {'A': 5, 'B': 7'}
  ]
```

looks to be more readable to me than your style, 

```
input: for_each={'A,B': [(1, 2), (5, 7)]}
```

It could be too confusing to add another style to the already very complex syntax for `for_each` though.

**Comment by BoPeng** [comment]
Just for the record, for my application with a lot of directly specified "context", I am using

```python
def from_contexts(contexts):
    keys = contexts[0].keys()
    return {','.join(keys): [[x[key] for key in keys] for x in contexts]}

input: for_each=from_contexts(contexts)

```
to convert list of cases into SoS `for_each`. The contexts were created using the following code

```python
contexts = []
for risk_name in ['Lowrisk' , 'Highrisk']: 
    for quarantine_days in [0, 10, 14]:
        for test_frequency in ['', 'M', 'MF', 'MWF', 'MTWTF']:
            for test_name in ['NOTEST', 'PCR90', 'PCR95', 'AG85']:
                if test_frequency == '' and test_name != 'NOTEST':
                    continue
                if test_name == 'NOTEST' and test_frequency != '':
                    continue
                if test_name != 'AG85' and test_frequency == 'MTWTF':
                    continue
                for rep in range(10):
                    contexts.append(dict(
                        risk_name = risk_name,
                        quarantine_days = quarantine_days,
                        test_frequency = test_frequency,
                        test_name = test_name,
                        name = f'{risk_name}_Q{quarantine_days}_{test_frequency}_{test_name}_{rep}',
                        general_community_infection_rate = 6.8e-5 if risk_name == 'Lowrisk' else 6.8e-4,
                        zone_a_community_infection_rate = 3.4e-6,
                        test_sensitivity = {'NOTEST': 0, 'PCR90': 0.9, 'PCR95': 0.95, 'AG85': 0.85}[test_name],
                        test_specificity = {'NOTEST': 0, 'PCR90': 0.99,'PCR95': 0.99, 'AG85': 0.985}[test_name],
                        zone_a_test_time = get_test_time(test_frequency, start=7, stop=quarantine_days + 46),
                        zone_am_test_time = get_test_time(test_frequency, stop=quarantine_days + 46),
                        zone_b_test_time = get_test_time('' if test_frequency else 'M', stop=quarantine_days + 46),
                        seroprevalence = 0.137,
                    ))
```

The major advantages, I think, are that

1. All elements are clearly defined in context, even those "constants" that are needed by the substeps.
2. the contexts can be used throughout my project as "cases" and I do not have to recreate them during simulation and during data analysis.

**Comment by BoPeng** [comment]
done.
