### ISSUE TITLE
group_by='none' to remove groups?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1408]
```python
single]
input: for_each=dict(i=range(2))
output: f'single_{i}.bam'

_output.touch()

[double]
input: for_each=dict(i=range(3))
output: f'single_{i}.bam'

_output.touch()

[combined]
input: output_from('single', group_by='all'), output_from('double', group_by='all'), group_by=1

print(_input)
```

`output_from('single', group_by='all')` flattens the groups into one, join with the ones from `double`, before `group_by=1` again.

I tried to use `group_by=None` but failed because `group_by=None` is the default parameter that will honor the original groups from the `single` step. I am wondering if we should provide some parameter to `ungroup`  a `sos_target`.

**Comment by gaow** [comment]
＞output_from('single', group_by='all') flattens the groups into one, join with the ones from double, before group_by=1 again.

What's the issue with this behavior? it seems to achieve what's designed, right?

**Comment by BoPeng** [comment]
I was referring a discussion on gitter where my first response to this problem was the use of `group_by=None` to remove grouping, and I was a bit surprised to find that it did not work.

Indeed `group_by='all'` solves this particular problem but I realized that we currently do not have a method to "remove" groups. From a memory optimization point of view, `group='all'` still have a single group with every targets, which uses memory and needs to be passed around between processes...

Of course adding another option can just add more confusion.

**Comment by gaow** [comment]
> Of course adding another option can just add more confusion.

In this case though, it seems you already expect the behavior of group_by = None to remove grouping. So maybe we can indeed implement that and make the default be `group_by = 'auto'` or `default` to retain the original? Users will never need to actually use this `auto` or `default` or whatever so we don't even have to document it.

**Comment by BoPeng** [comment]
You are right, `group_by=None` is certainly more intuitive than `group_by="none"`. I will do this when I get some more time to think through this. (Currently overwhelmed with a COVID paper, will have more time for your DSC tickets afterwards).

**Comment by BoPeng** [comment]
done.
