### ISSUE TITLE
get_output non-zero return code for command that seems legit

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1413]
Here is an example:

```python
from sos.utils import get_output
cmd = ''' get_seeded_random() { seed="$1" ; openssl enc -aes-256-ctr -pass pass:"$seed" -nosalt </dev/zero 2>/dev/null ; } ; echo -e '1\\n2\\n3\\n4\n' > test.txt ; shuf -n 2 test.txt --random-source=<(get_seeded_random 9) | sed 's/^/"/;s/$/"/' '''
get_output(cmd)
```

There will be an error message saying return code is non-zero. However it works fine with Popen:

```python
from subprocess import Popen
child = Popen(cmd, shell=True, executable='/bin/bash').communicate()
```

If I try to get its returncode:

```
child = Popen(cmd, shell=True, executable='/bin/bash')
child.communicate()
child.returncode
```

the return code is zero. I am wondering what's special about `get_output` that complains about this command?

**Comment by BoPeng** [comment]
`get_output` uses `check_output`

(https://github.com/vatlab/sos/blob/fd0b01c896c35d16a55898d78c7d428b3738d9c7/src/sos/utils.py#L760

and the only difference seems to be the use of `executable`?

**Comment by gaow** [comment]
Yes indeed. `check_output` works with `executable='/bin/bash'`. 

Should we assume bash syntax for `get_output` by default and provide an option to make it otherwise? I guess that'd make sense because pipelines thus written should be more robust against the default shell program of the computer it run executes on?

**Comment by BoPeng** [comment]
I will provide `**kwargs` to `get_output` and allow the passing of extra parameters. I think the problem was that you were using some `bash`-specific syntax that the default shell does not.

**Comment by BoPeng** [comment]
Option added. Cannot test here since both commands pass with output `''` here (mac).
