### ISSUE TITLE
Move local .sos to ~/.sos/path

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1419]
We have `.sos` with a bunch of stuff. They are placed there mostly because we had a pack/unpack feature that was supposed to contain files and their signatures.

With the at least temporary removal of the pack/unpack feature, I think it is better to move `.sos` to `~/.sos/encoded_path` to stop the creation of `.sos` directory all over the places.

**Comment by gaow** [comment]
@BoPeng may I suggest that the global directory be named as `~/.sos/basename(path_of_sos_script)_encoded_path`? That can help us delete traces of obsolete projects. I get complaints from users from time to time that `~/.sos` folder gets too big and my only suggestion to them is to `rm -rf ~/.sos`. It would be nice if we can do something to help with it. An improved path name is a good start.

**Comment by BoPeng** [comment]
how big was too big? The files over there are generally small but can accumulate.

We can
1. development something like `sos clean` to remove all project related files.
2. develop some auto-cleanup strategy that removes files that are, say, more than 30 days old.
3. Of course needs to know the cause of "too big", some big files or too many files....

**Comment by gaow** [comment]
Here is the message i got from the user:

```
 .sos directory takes 23G, so my home directory run out of storage limit. In .sos , tasks takes 11G, transcript.txt  takes 7.4G. 
```

so definitely it is small files accumulated over time beacuse transcript.txt is huge. Option 1 sounds very reasonable.

**Comment by BoPeng** [comment]
ok,

* `.sos/tasks` can be big because it contains all task information, including logs (input/output), results, and signatures, and old tasks are supposed to be removed automatically (I believe 30 days).
* `.transcript` can be big because it records all commands executed. Perhaps it makes sense to clear `.transcript` for any new `sos` run?

**Comment by gaow** [comment]
> Perhaps it makes sense to clear .transcript for any new sos run?

Definitely that will help. 

I think 30 days removal for `tasks` is good enough. Then what's left is step and workflow signatures. We may want to keep them until users want to remove them. I can still imagine that a "clean" feature can help -- that cleans up tasks and also step and workflow signatures for a project.

**Comment by BoPeng** [comment]
I am removing transcript file if it is more than 30 days old.
