### ISSUE TITLE
Checking the status of remote workflows.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1420]
Remote workflow is getting easier with #1407 and #1418 

Currently `sos run -r` simply execute the workflow on the remote host, or submit it to remote cluster system. There is no way to check the status of the workflow or get the error message.

It is tempting to pipe the output from the workflow to the local host, and allow the use of `sos status` to check the status of the remote workflow. Not sure how exactly we should do that.

**Comment by BoPeng** [comment]
So what we need to have are:

1. Add an option, perhaps `-m` for `monitor`, to start a monitoring thread, similar to the task monitoring process.
2. Encourage users to specify workflow `err` and `out` files in the right place so that `sos status -v4` can pick up.
3. Add workflow monitoring to command `sos status`.
4. Add support for `sos kill`, `sos purge` etc
5. Automatically add option `-m` when `sos run -r host` to `sos run ` on remote host.

**Comment by bioworkflows** [comment]
all done. (It is supposed to be Christmas time. :-( )
