### ISSUE TITLE
Docker temporary script missing

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1427]
I think this is a regression bug -- to reproduce:

```
[1]
bash: container='debian:stable-slim'
  asdf
```

the output:

```
ERROR: 1 (id=bd067693a77def1b) returns an error.
ERROR: [1]: [0]: Failed to locate specified command (exitcode=127). The script has been saved to /home/gw/.sos/bfd3b87644acbff4/.sos/docker_run_88818.sh. To reproduce the error please run:
docker run --rm --security-opt label:disable -v /home/gw/tmp/19-Jan-2021:/home/gw/tmp/19-Jan-2021 -v /home/gw/.sos/bfd3b87644acbff4/.sos/docker_run_88818.sh:/var/lib/sos/docker_run_88818.sh    -t  -w=/home/gw/tmp/19-Jan-2021 -u 1000:1000    debian:stable-slim /bin/bash /var/lib/sos/docker_run_88818.sh
```

The problem is that the file `/home/gw/.sos/bfd3b87644acbff4/.sos/docker_run_88818.sh` does not exist:

```
$ ls /home/gw/.sos/bfd3b87644acbff4/.sos/docker_run_88818.sh
ls: cannot access '/home/gw/.sos/bfd3b87644acbff4/.sos/docker_run_88818.sh': Not a directory
```

so I get an ugly error when I attempt to reproduce the error as prompted. I dont think it was the case for earlier versions. 

Also , should we save the script under `.sos` and not `~/.sos`?

**Comment by BoPeng** [comment]
Oh, local .sos has been removed. I will have a look soon.

**Comment by BoPeng** [comment]
Fixed.

This only happens when the command failed, and why the test suite did not detect it.
