### ISSUE TITLE
SoS no longer reports location of temp scripts when code goes wrong

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1432]
Here is a minimal example:

```
[1]
R:  stderr=False
  wrong_code
```

the error message is:

```
$ sos run test.sos 
INFO: Running 1: 
ERROR: 1 (id=8f28d9b9ddc3daa3) returns an error.
ERROR: [1]: [0]: 
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
script_9016547112804817921 in <module>
----> R('wrong_code\n', stderr=False)
      

FileNotFoundError: 2
```

This is very confusing for those who wants to debug the script.

**Comment by BoPeng** [comment]
Perhaps an artifact related to the removal of `./.sos`. Will have a look later.

**Comment by gaow** [comment]
Thanks @BoPeng. A related issue is can we also move `transcript.txt` to project specific cache under `~/.sos` so each project can have their own `transcript.txt`? Currently this is the only file under `~/.sos`. All other files are in subfolders

**Comment by BoPeng** [comment]
Currently there is a per-project subfolder but the name is scrambled so it is difficult to see which is which....

**Comment by BoPeng** [comment]
A patch is submitted but I do not know what is the best way to find the `transcript.txt` file.

One way is to turn this hidden transcript feature as an explicit option and require users to specify the output transcript file. It can even be done as something like `export SOS_TRANSCRIPT=FILE`.

**Comment by gaow** [comment]
The patch works well, thanks! I think `transcript.txt` is only relevant when there are some errors in the pipeline? In that case users will already get a line like:

```
Failed to execute Rscript /home/gw/.sos/d336ae6054b445f8/annotate_0_b5beede3.R
```

and they can track the folder name here? Maybe the question boils down to what do you see is the use of `transcript.txt`? Currently it is under `~/.sos` for all projects which is worse than under a project specific folder with scrambled name.

**Comment by gaow** [comment]
@BoPeng shall we make a new release to reflect recent changes including the docker temp script and this one? Or you would like to also fix the `transcript.txt` and release? Then i can tell people to run `pip install` to update and not trying to install from github. Thanks!

**Comment by BoPeng** [comment]
`transcript.txt` is already under the scrambled directory. I reverted the changes to #1424 (the server branch) because the patch was not ready. I can release the next minor version if you are happy with the location of `transcript.txt`.

**Comment by gaow** [comment]
Thank you it works well! Yes it would be great if you could release this bug fix version, unless we are only a few days before the server branch is ready (in which case we can live with current release for a few days).

**Comment by BoPeng** [comment]
I will do that after travis passes.

The server branch will not be ready any time soon because I have found it very tricky to start short-lived daemon on the server since there is no easy way to tell which port is available on the server. A very dumb solution would be fall back to the old `ssh` way if the server cannot be started but then I will have to implement the same things twice.

#1424 is only a problem for the use of `remote()` files so might not be very urgent anyway.

**Comment by BoPeng** [comment]
Version 0.22.5 released.
