### ISSUE TITLE
Fix CI pylint

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1439]
pylint fails due to some weird error, and we should fix it.

**Comment by he1l0world** [comment]
I guess I found a similar issue mentioned in [Here](https://github.com/actions/starter-workflows/issues/636), the command "s -R|grep .py$|xargs" will only list all files not the path, so that's why it will give a bunch of error about missing module name.

Can I make a PR with the new command?

**Comment by BoPeng** [comment]
I have alredy started working on this on the `test` branch, which changed the command to `pylint src/sos`. There are still a bunch of pylint error though.

I think you can create a PR against the test branch.

**Comment by he1l0world** [comment]
Sure, sounds good.

**Comment by BoPeng** [comment]
Because `pylint` gives many many warnings, I added a file `.github/linters/.python-lint` to disable many of the warnings that I deemed non-essential. This pylint configuration file is used by [`super-linter`](https://github.com/github/super-linter), a linter that I use for other projects, but I am not sure if `pylint.yml` uses this file.

I suspect that `.pylint.yml` uses something like `.pylintrc` on the project home directory.

**Comment by he1l0world** [comment]
Ok, I can look it up and add the configuration file to the command.

**Comment by he1l0world** [comment]
I think you are right that the pylint use .pylintrc file as configuration file

**Comment by BoPeng** [comment]
This is completed.
