### ISSUE TITLE
Default container option to not use containers

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1445]
I often find myself in this situation where I would like to run a workflow on a test data locally on my computer using software installed, but then move to the cluster with singularity. My default workflow looks like:

```
parameter: container = 'gaow/something' # for docker, or alternatively use singularity via  --container /path/to/something.sif
...

R: container = container, ...
 ...
```

I wonder if we can come up with an interface such that eg with `--container NULL` or something like that, we dont use container at all? It boils down to interpreting `R: container="NULL", ...` as just `R: ...`. Or, can we achieve this using our existing features?

**Comment by BoPeng** [comment]
nextflow does something like this, with `process.container=whatever` etc in their runtime definition. It looks like they have cleaner separation of running environments from "process" than ours, although I frown upon ideas of "workflow specific" settings in `~/.sos/config.yml`. Perhaps we can do something similar in `./config.yml`.

**Comment by gaow** [comment]
> Perhaps we can do something similar in ./config.yml.

So this is to configure `task:` ? That sounds a good idea.

**Comment by BoPeng** [comment]
The easiest thing that perhaps already works is

```
[step1]
sh:  container=CONFIG.get(task1_container, None)
```
which is more troublesome than  nextflow but perhaps more explicit is better. The problem for us to adopt a nextflow approach is that there is no single action in task so it is not easy to say do something like

```
step1:
    container:  'whatever'
```
since the step could in theory have

```
[step1]
sh:
   script1
python:
   script2
```
I mean, the concept of "process" is unclear in sos.

**Comment by gaow** [comment]
Can we leave a default option in the workflow but allow for config file to overwrite them? eg, by default we dont specify any container at all. But if our config file says that a step needs a container then we can use that container? 

> I mean, the concept of "process" is unclear in sos.

what if we allow for

```
step1:
    container:  ['whatever1', 'w2', 'w3']
```

and let the steps match them by the order specified to the actions in the step, and throw an error if they dont match? Of course we can have just one of them by default for use for all actions in the step, so it should be either 1 or N where N is the number of actions in that step.

**Comment by BoPeng** [comment]
That can be very confusing. 

I would instead propose something like

```
sh: cname='align'
   script
```

```
align:
    whatever: parameter
    whatever: parameter
```

Basically `cname` gives a 'configuration name` for the action. When SoS find that an action has a name, it will checkes the configuration file and add whatever parameters defined over there to the action.

It is unclear how to handle conflicting parameters, namely if configuration file or in-script parameter will have priority.

**Comment by gaow** [comment]
Well then we will have to always use a configuration file to accompany a workflow; and we have to make one for every computing environment we run a workflow, even for a simple test on a local computer where we just want to run without container. 

I wonder if we can have a better, minimal default behavior that doesnt need any config file. The downside is obviously for config file to overwrite it, we need to specify it at step level.

**Comment by BoPeng** [comment]
> Well then we will have to always use a configuration file to accompany a workflow

Why is that? `cname` will be ignored if it does not exist in `CONFIG`. Basically what `cname` does is adding `**CONFIG.get(cname, {})` to `kwargs` of the action.

**Comment by BoPeng** [comment]
The problem with a default `cname` is that it has to be something like `step_1` or `step_1.sh` and it is more likely to break when the workflow changes. A user-specified name can be used for multiple steps using the same action (which can be good and bad, but should mostly be good).

**Comment by gaow** [comment]
> Why is that? cname will be ignored if it does not exist in CONFIG.

Okay that is reasonable. Can we use `configuration = ` instead of `cname` (which sounds like CNAME in DNS record)

**Comment by BoPeng** [comment]
> Okay that is reasonable. Can we use configuration = instead of cname (which sounds like CNAME in DNS record)

Or `config_name`?

**Comment by BoPeng** [comment]
The implementation is almost trivial so I have just added it to the `config_name` branch. 

Here is how to use it:

1. Have a configuration file:

```yaml
action_templates:
    cat: |
        echo '>>> showing content of {filename}:'
        cat {filename}
action_params:
    test_action:
        template_name: cat
```
Note the use of `action_params`.

2. have a script
```python
run:  config_name='test_action'
            echo 'whatever' > template_output.txt
```

Then

```
% sos run test -c myconfig.yml -v1
>>> showing content of /var/folders/97/_n92l0hj4y38vrn1xyn7cz4c0000gq/T/tmpdvgnnua1.sh:
echo 'whatever' > template_output.txt
```

Without `-c` the script will run the script to create the `template_output.txt` file.

**Comment by BoPeng** [comment]
I think we can just say `name=`, and explain that `action_params` will list parameters of actions with specified `name`.

**Comment by BoPeng** [comment]
Through this mechanism maybe we can deprecate `template_name`, and introduce

```yaml
action_templates:
    name:
       tesmplate
```

**Comment by gaow** [comment]
@BoPeng I'm revisiting this feature. I can understand what it does, but I cannot see how it can easily control my workflow runs whether or not to use a container for all the steps in a workflow. That is, how exactly do I switch between:

```
R: container="repo/image"
```
vs.

```
R: container=None
```

so the latter means we dont use a container ( I was hoping the latter actually works so I can set default container to `None`...)

**Comment by BoPeng** [comment]
The source code is

```
if "container" in kwargs and kwargs["container"]:
```
so it appears that `container=None` would be ignored.

**Comment by BoPeng** [comment]
> I think this is a good idea and should be generalized to task as well?

The problem is that we have a lot of anonymous use cases. For example, in sos notebook we do not have step name (or one anonymous step name for many cells), in a sos step we can have multiple actions

```
sh:
sh:
python:
R:
```
so it is difficult to refer to one particular action from the configuraiton file. Task is easier since there is only one task if we can find the right step name.

This is why I suggested "ID"ed configuration so that you can use some ID to refer to entry of the configuration file

```
task: **CONFIG['whatever']
```
If you hate this, we can do something like

```
task: config_name='whatever'
```

**Comment by gaow** [comment]
`task: **CONFIG['whatever']` looks good and very clear to me as a Python user because I'll expand that in my head as a bunch of keyword arguments, compared to `config_name='whatever'` where `config_name` is a keyword argument that will override other keyword arguments when specified (which is a bit confusing).

**Comment by BoPeng** [comment]
> task: **CONFIG['whatever'] looks good

The only problem is that you will have to use

```
task: **CONFIG.get('whatever', {})
```
to make it work properly, which is a bit verbose (unless we do some magic to `CONFIG`, but "magic" has its own costs.

**Comment by BoPeng** [comment]
Things will get more complicated for subkeys, so I suppose someting like

```
task: get_config('runtime/whatever')
```
can become handy.
