### ISSUE TITLE
Further improvements to Jupyter sos kernel

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#146]
Right now jupyter
1. lists input and output files in a table with link
2. displays images in output files (for jpeg etc)
3. preview pdf files in iframe
4. display csv files using `pandas` (Question: should we require pandas and numpy? Right now no table is displayed if pandas is not available).
5. display the first 5 lines of all text files that are not handled by other preview method.

Further improvements can include
1. Imporve codemirror syntax highlighting (a javascript expert is needed)
2. allow users to set width and height of preview (pdf) iframe. Currently it is fixed to 600x400.
3. Include pandas css to make the table look prettier.
4. print basic information about gtf, bam and vcf files. In particular, I would like to see if the chromosome names start with `chr` which has been a major problem for compatibility of these files.

More ideas will follow.

These will make jupyter a bit closer to RStudio in usability, with the advantage of using multiple languages. The main disadvantage of jupyter is the intergration of code and results, which is good for notebook, but bad for version control stuff. RStudio's separation of .Rmd and exported code seems to be a better design.

**Comment by BoPeng** [comment]
There is an interesting [blog](https://decisionstats.com/2015/10/20/how-jupyter-ipython-threaten-the-dominance-of-rstudio-for-data-science-developers/) on Python, R and data science... perhaps SoS can find a role there with being able to integrate different kernels into one notebook.

**Comment by gaow** [comment]
> The main disadvantage of jupyter is the intergration of code and results, which is good for notebook, but bad for version control stuff

That was my main contention against notebook, but if SoS <->jupyter works then that'll no longer be an issue :)

**Comment by BoPeng** [comment]
The conversion process needs to be improved because the `#with R` stuff needs to be translated to `R:`. If we can make the conversion lossless (discard the output, but keep the markdown), we can think sos as Rmd, notebooks as Rmd generated HTMLs but are live.

The bottom line is that the notebook format is useful to its purpose (bundle code and result for archive and presentation), and is very good for interactive use because I can immediately preview the results. The `#with R` stuff makes SoS notebook real 'script of scripts' notebook with scripts in different languages evaluated by their own kernels. Jupyter users might like it if it works flawlessly.

**Comment by BoPeng** [comment]
The preview feature is there, and is the biggest reason for me to use the notebook format. For now I will add meaningful previews for more and more file types, but later on there might be a need for to control preview, something like

```
%preview: none
%preview: pdf=as_jpg, gxt=my_prev_func
```

**Comment by BoPeng** [comment]
I just submitted a [ticket](https://github.com/jupyter/notebook/issues/1883) to jupyter for changing notebook and/or cell colors according to active/used kernels.
