### ISSUE TITLE
Additional flags for containers

### ISSUE THREAD

**Issue by tfabiha** [vatlab/sos#1500]
Hi Bo,

I'd like to run scripts in singularity with the --nv flag, similar to the command `singularity run --nv {filename}.sif`, but haven't been able to find any information about including flags for containers in the SoS docs. 

I was wondering if there already is a way to include flags?

Thank you in advance!

**Comment by BoPeng** [comment]
You are right, currently the singularity mode only supports the `bind` option, not `nv`. There are also a number of other options that could be supported.

It also does not support `singularity run`, only `singularity exec`.

Let me see if I can come out with a quick fix.

**Comment by tfabiha** [comment]
I'll be able to run with `singularity exec`. Thank you so much for such a quick response!

**Comment by BoPeng** [comment]
I have updated test and doc, and released sos 0.23.2.
