### ISSUE TITLE
kernel dead after launching jupyter or jupyterlab on macbook pro M1

### ISSUE THREAD

**Issue by bayeslearner** [vatlab/sos#1504]
Doesn't run.

**Comment by BoPeng** [comment]
This is related to Python 3.10 (should import `Sized` from `collections.abc`). I am submitting a patch.

**Comment by BoPeng** [comment]
This has been fixed quite a while ago (https://github.com/vatlab/sos-notebook/pull/337). Could you please upgrade to the latest version of sos-notebook?
