### ISSUE TITLE
remote computer wall time format HH:MM

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1509]
@BoPeng The issue is that the wall time format accepted by a cluster system we use is `hh:mm`. However sos uses the `hh:mm:ss` format. Currently, we have to hard code the wall time to make it work. How would you suggest we programmatically reformat the walltime values to stripping off the seconds part in the yml file?

**Comment by mw201608** [comment]
Hi BoPeng. It works. Thanks for the advice!

**Comment by BoPeng** [comment]
Great. I tried to test but we lack some method to render the job script without submitting it...
