### ISSUE TITLE
SoS is broken on Python 3.12?

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1542]
On Python 3.10 and SoS 0.25.0 this workflow:

```
[1]
parameter: dat = path
input: dat
print(_input)
```

it works well. 

```
sos run test.sos --dat test.sos
INFO: Running 1:
test.sos
INFO: 1 is completed.
INFO: Workflow default (ID=wadc76383948ec2d8) is executed successfully with 1 completed step.
```

But on Python 3.12, it fails:

```
# sos run test.sos --dat test.sos
INFO: Running 1: 
ERROR: [1]: [1]: Failed to process input statement dat
: file_target object has no attribute traced
```

I have another workflow that shows a different error:

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.pixi/envs/sos/lib/python3.12/site-packages/sos/targets.py", line 128, in __getattr__
    return self._dict[name]
           ^^^^^^^^^^
  File "/root/.pixi/envs/sos/lib/python3.12/site-packages/sos/targets.py", line 132, in __getattr__
    raise AttributeError(f"{self.__class__.__name__} object has no attribute {name}") from e
AttributeError: file_target object has no attribute _dict
```

after we upgrade from Python 3.10 to 3.12 it seems we are crippled ..

**Comment by BoPeng** [comment]
I can reproduce the problem with a Python 3.12 environment, but cannot figure out what went wrong immediately.

I have [updated the test suite to add python 3.12](https://github.com/vatlab/sos/commit/3bfd2de99ca4d5628202ae821b896f724e67cf03) to catch all such problems.

**Comment by BoPeng** [comment]
ok, find the source of the problem. What we did was sending a compiled global statement in task file to be executed on remote host. However, the docker side uses python 3.10, and the test side uses 3.9, and a change in the `ast` package has changed the format of the `ast` object....

So the problem happens if local and remote sos has different versions of python, which we can fix, or ignore.

**Comment by gaow** [comment]
Ahh .... I think it is enough to check and report error or warning for that case, leaving it for users to fix. That should be fair enough.

**Comment by BoPeng** [comment]
sos 0.25.1 is released for this fix.

**Comment by gaow** [comment]
great thanks @BoPeng , i take that conda release is automatic and will be there in a few hours? Sorry i cannot remember if it is automatic or you have to click on some extra buttons. I'll merge the PR once I see it pass on conda-forge GitHub.

**Comment by BoPeng** [comment]
automatic, merged.
