### ISSUE TITLE
Preview (-v) option of command sos.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#158]
The most useful feature of jupyter notebook is in my opinion the ability to preview results. I can see if a file has been downloaded correctly and what the file look like, and see if a figure has been created correctly. It can prevent a lot of errors, for example, if your gff file has `chr1` as chromosome name and your bam file has `1` as chromosome name.

I suppose we can migrate the feature to command line use, with `-v` to preview the results. `-v` would be `True` by default in interactive mode, and `False` in batch mode. It can also accept options on how to preview each type of files.

**Comment by BoPeng** [comment]
`-v` (verbosity) is not available, neither does `-p` (prepare).

**Comment by BoPeng** [comment]
Also, instead of writing most of the stuff to terminal and fire up mac preview stuff for pdf and jpg, I believe it is better for us to open a browser to display things such as report, preview, even debug message, without having to reload the page. These pages serves as monitor of sos scripts and I believe this can be done in javascript although I do not know anything about that language (yet).

**Comment by gaow** [comment]
Oh haha your new comment made me erasing a long text I just wrote here. Exactly I was suggesting taking a different approach, by adding something like `--html` switch to `run` that displays more information in a more readable fashion including summaries/preview of input/output. Is that what you have in mind? Instead of having to write some javascripts I wonder if there are existing templates that we can just use. We can do a quick search.

**Comment by BoPeng** [comment]
In the end we will most likely have some thing like a web console that reports the status of workflow and local and remote task, and these can easily be tabs/windows in that interface. I suppose we can start something simpler and I will be happy to have a browser that display different local output streams of sos.

**Comment by gaow** [comment]
I personally do not think reloading page is such a big deal and it makes our life a lot easier to use static HTML converted from markdown. 

> have a browser that display different local output streams of sos.

By "listening" to multiple channels on the same web-page? That might be overly crowded. On multiple tabs, maybe, and that justifies more on auto-reloading. But I find it is very rare that I try to work on to many different local SoS instances (usually means different projects) at the same time to press F5 for them manually.

**Comment by BoPeng** [comment]
Say, we can have channels `preview', `report`, `transcript` and `log`, we can control if we would like to have them using option `-c` or not control them at all (as long as we do not listen). If we open a browser and listen to a specific port (e.g. `http://localhost:1111`), we can have a page displaying all these information or separate ports for different contents. Then, just like [jupyter sidecar](https://github.com/nteract/sidecar), we can have live information displayed during the execution / debugging of workflow...

**Comment by gaow** [comment]
Oh Ok I now see different channels means different information from the same project and we can opt to listen part of it. That makes a lot more sense and justifies the use of channels rather than static pages.

**Comment by BoPeng** [comment]
Yes, the current idea is that when sos runs, it fires up a webserver and serves one or more ports ... something like  the example in [python webserver help page](https://docs.python.org/2/library/simplehttpserver.html). How users interact with sos through that web interface is another matter... 

This is of course an overkill for small workflows but can be immensely useful for large workflows and/or for interactive use / debugging.

**Comment by BoPeng** [comment]
I have a feeling that we can make use of websocket https://websockets.readthedocs.io/en/stable/intro.html for this kind of thing.

**Comment by BoPeng** [comment]
It is worth noting that spyder uses sockets for their object inspector and other widgets. Basically, the ipython sesesion has a few servers and other widgets ask information from these session. I suppose this should be the direction for us, especially when there is existing code to mimic.

**Comment by BoPeng** [comment]
Relevant code is at https://github.com/spyder-ide/spyder/blob/master/spyderlib/widgets/externalshell/introspection.py
