### ISSUE TITLE
Proper codemirror highlighter for SoS

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#162]
The codemirror definition of `SoS` is defined in `sos/jupyter/sos_codemirrot.js` and copied to jupyter sos kernel directory. The definition is very rough in that many sos directives and magics are not displayed correctly. We should collect the problems and try to correct them by tweaking this highlighter.

**Comment by BoPeng** [comment]
The `sos_codemirror.js` file is based on the Python syntax highlighter in https://github.com/codemirror/CodeMirror/tree/master/mode/python . We should follow the codemirror website and create a HTML file to test the syntax highlighter.

**Comment by BoPeng** [comment]
Improvements?

1. differentiate between single and double quotes because double quotes would be interpolated.
2. ??

**Comment by jma7** [comment]
Would you please help me to check if the highlights are correct?
http://bopeng.github.io/SOS/tutorial_html/A_Complete_Example.html

**Comment by BoPeng** [comment]
Yes, the only problem now is `${}`. Ideally we should emphasize `${}` within double quoted strings and script style. But this would be really difficult given any python expression is allowed between `{}`. I think we should at least remove the red box around it or change to another style because red box indicates error.

**Comment by jma7** [comment]
I just removed the red border. Do you want to show ```$``` in another color?

**Comment by BoPeng** [comment]
No unless you can highlight `$` only in double quoted strings and script in script mode.
