### ISSUE TITLE
RQ as external task queue

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#198]
See branch rq, to test it, go to `test/script`,

step 1: start a redis server

```
% redis-server
```

step 2: start a rq worker

```
% rq worker
```

step 3: start a monitor

```
% rq-dashboard
```

and open a browser to the address specified by rq-dashboard

step 4: run the script

```
% sos run test_rq.sos
```

This is all very preliminary. In theory, we should be able to create multiple queues (workers), submit jobs to the works with load balance, and have redis server, worker etc on different computing nodes.

**Comment by gaow** [comment]
I get it work -- got the idea! Still playing ...

**Comment by BoPeng** [comment]
Ideally, we should

1. Start one redis-server somewhere, with information (host:port) saved in the configuration file. The server can be started by SoS automatically if it is local. Otherwise a dedicated command is needed to start the server. `redis-server` might be good enough but we can use something like `sos start redis-server` if more steps and configurations are involved.

2. Start one or more rd-workers locally or remotely. My understanding is that the rd-workers only need to talk to the redis-server. It would be best if they can be started and stopped independent of sos instances. For example, we can start and stop workers according to workload and available resource, and they should automatically balance workload between them. Again, we can use `rd-worker` or `sos start worker` to start a worker.

3. SOS should just send the tasks to redis server and do not know how they are handled. Right now we have to wait for the completion of all tasks, but we do not have to wait with a DAG.

If these more or less work, we should make the system more robust on the handling of dead worker and/or SoS process. For example, what should happen if a job is sent but the sos process is killed, and what should happen is a job fails.

**Comment by BoPeng** [comment]
With the master branch, the last command should be

```
% sos run test_rq.sos -e rq
```
