### ISSUE TITLE
Session info?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#21]
There is a need to save the version of program or packages of R ...

**Comment by bpeng2000** [comment]
```
$ R -q -e 'sessionInfo()'
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> 
```

might help.

**Comment by BoPeng** [comment]
This does not look like part of SoS because there is no general session information. Users should do this by themselves.

**Comment by BoPeng** [comment]
With the stabilization of Jupyter format, I think it is time to discuss a `%sessioninfo` magic, which basically,

1. List all kernels used for the notebook (Jupyter version, SoS version plus version of python, R kernels etc).
2. For each kernel, execute a variant of `sessioninfo` function, that should be defined by the kernel (perhaps recommended but not enforced). R already has this function, it should not be too difficult to write a Python function for this.

**Comment by BoPeng** [comment]
This should be done before the talk because it has an emphasis on reproducibility.

**Comment by gaow** [comment]
Also it would be very useful to be able to figure out whether or not the notebook is under git version control and report a version ID. I currently run this manually for my notebooks:

```
echo Revision `git rev-list --count HEAD` '('`git rev-parse HEAD`')'
```

Will give, for example, "Revision 48"

**Comment by BoPeng** [comment]
Ok, this is implemented and documented [here](http://vatlab.github.io/SOS/doc/documentation/Notebook_Interface.html#%sessioninfo-1416). Let me know if you have any comment.

**Comment by gaow** [comment]
It is perhaps my undoing but I did update (then removed and reinstalled) SoS and `killall` all my jupyter notebooks. But still I get:

```
ERROR:root:Line magic function `%sessioninfo` not found.
In [ ]:
```

Am I missing something?

**Comment by gaow** [comment]
Oops sorry I was running it in a Python notebook not SoS ... please ignore my previous post.
