### ISSUE TITLE
RQ/Cluster interface

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#234]
Command

```
sos start server [-e rq|mrq|celery]
sos stop server ID
```
1. start a redis server
2. write .sos/server.yaml

```
sos start worker [-e rq|mrq|celery]
sos stop worker ID
```
1. check `.sos/server.yaml` for redis server
2. wait if redis server is not started (e.g. still in PBS queue)
3. try to connect to redis server and check if it is alive
4. start working once redis server is alive

```
sos start monitor
```
1. check .sos/server.yaml for redis server
2. start a browser and point to rq monitor interface

```
sos run myscript [-e rq|mrq|celery]
```
1. check .sos/server.yaml for redis server
2. connect to redis server
3. submit tasks to redis server

Of course we do not have to support multiple backend but the interface should be general enough if we need to switch.

**Comment by BoPeng** [comment]
http://stackoverflow.com/questions/166506/finding-local-ip-addresses-using-pythons-stdlib has suggestions on how the redis-server knows its IP address.

**Comment by gaow** [comment]
I see this feature of perhaps more general interest. I wonder instead of making it SoS commands, shall we create a separate app (a wrapper separate from SoS code) so that more people can potentially contribute, comment and maintain? I feel the idea itself deserves a separate implementation. We can also use it with other projects (VATLab maybe?). It can be a command tool that works with submitting Python codes where redis queue is used to dispatch tasks rather than the multiprocessing module.

**Comment by BoPeng** [comment]
This is exactly what mrq does, right? They have a command `mrq-run`. I do not mind putting it outside of sos but it has to be easy to use.

**Comment by gaow** [comment]
Indeed! I think it is also under consideration that we use `mrq` as the backbone. 

Our application is more specific for a cluster environment and perhaps involving more steps. But if we can get it work with 2 HPC system (yours and mine) we should be able to come up with something easy to use and interesting to the general public. So we need a good name for the repo ...

**Comment by BoPeng** [comment]
But the separate utility is very similar to `mrq-run` and I do not see the value of doing so. We can extend the discuss on #234 .

**Comment by BoPeng** [comment]
Another advantage of starting worker etc from within sos is that we can control the python interpreter used and make sure sos can talk to workers. For example rq worker started from a Python 2 based environment would not be able to talk to sos.
