### ISSUE TITLE
Resource options for task

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#240]
Just for the record, we will sooner or later have some options to `task` so that we know how to send tasks to rq workers. If we submit workers to the cluster with limited resource, the jobs should be sent with knowledge of the capacity of the worker.

These options should include number of CPU, amount of RAM, and walltime.

**Comment by BoPeng** [comment]
`walltime` has been added to be used by rq backend.

**Comment by BoPeng** [comment]
However, to avoid adding too many parameters, it makes sense to use a single parameter (e.g. `resource={'walltime': '2:0:0', 'mem': 16G}`, although I admit that this format is a lot longer.

**Comment by gaow** [comment]
I too think this simple form is more agreeable. Or, a compromise would be to use dedicated parameters for a few commonly used argument, i.e., just `mem`, `nodes`, `threads`, `walltime`, and the rest parameters go into a single dictionary.

**Comment by BoPeng** [comment]
We are facing similar situation with `env={'PATH': '/path'}` or `PATH=`, but I think this is a less used option so it should be fine with `env` (similar to `subprocess.Popen(env)`.

**Comment by BoPeng** [comment]
Implemented `walltime`, `mem`, `nodes`, and `ppn`, which are common PBS parameters, although sos jobs are currently 1 node only so `nodes` is not needed. There seems to be option for the number of gpu.
