### ISSUE TITLE
Report used resource.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#256]
Resource used by workflow is now reported immediately after a step is completed and is scattered around under `.sos`. Now that we have an unique ID for each run, we should be able to create a master index to collect such information and report resource used, possibly using a plot. This is helpful to, for example, determine resource used and update the workflow with proper `walltime` option so that it can run better on cluster.

**Comment by BoPeng** [comment]
The proper way should be writing CPU and Memory usage to workflow runtime file, although we will need to pass step_id to actions so that such information can be recorded properly and allows proper re-construction of execution details.

Note that a workflow would have the same ID if it is rerun, so the second run would have extremely short runtime for skipped steps. It probably makes sense to keep all previous runtime information.

**Comment by BoPeng** [comment]
The runtime file now has CPU information. A command is needed to view them though.

**Comment by BoPeng** [comment]
I suppose a summary plot would be needed to display how a workflow has been executed, which should have a time line, and a DAG graph. The runtime information is already there and we should probably output the DAG to this file as well.

One way to achieve this is to put step dependency information in the master file, because DAG can change and the actually execution sequence shows exactly how each step is executed.

**Comment by gaow** [comment]
wading though opened tickets ... I think we should not spend too much time on a summary plot. The `dot` command can generate such plot from the dag file but often for workflow with many parallel jobs it looks extremely ugly. Perhaps we do not want to wrestle with it. Rather, I think parsing the runtime file and making a summary table of CPU information is good enough. Interface-wise it could go to `Output options`, using `-i` for information (we are running low on options)?

**Comment by BoPeng** [comment]
OK, the status file and .sig file has all these information. Perhaps a summer student could write a script to summarize them.

**Comment by BoPeng** [comment]
Summary for tasks are good enough for now.
