### ISSUE TITLE
Starting RQ worker from within SoS

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#260]
I'm trying to start redis worker from within the script (as an attempt to streamline the process as discussed before). Currently it is a mess to display thousands of output names. Hopefully we can derive this class and manage the output info along with other possible tweaks. 

This is how I start the worker:

``` python
def rq_worker(host_url):
     import redis
     from rq import Worker, Queue, Connection
     listen = ['high', 'default', 'low']
     redis_url = 'redis://' + host_url
     conn = redis.from_url(redis_url)
     with Connection(conn):
          worker = Worker(map(Queue, listen))
          worker.work()
```

I guess we can also shutdown the worker at the end. However this only works as a standalone program, i.e., if I do:

``` python
if __name__ == '__main__':
  rq_worker(host_url)
  do_something()
```

It will start the work and stay there, not proceeding to `do_something()`. Do you think it is good idea to try starting rq worker from inside SoS and therefore control it better?

**Comment by BoPeng** [comment]
What do you mean by 'inside SoS? The worker should be started as a separate process and start a infinite loop for working so I am not sure what  `do_something` would be doing.

**Comment by gaow** [comment]
Currently the workflow is:

1. start redis server with `host_url` via command line
2. start worker connecting to the redis server at `host_url` via command line
3. run SoS
4. shutdown worker from step 2.

I'm thinking that we merge 2, 3, 4 such that SoS will automatically start works to connect to given `host_url`, then run the computations (`do_something()` in my example) and shutdown workers. That way we only keep the server running and we'll remember to shut down the server, not worrying about all the worker processes we started.

**Comment by BoPeng** [comment]
The problem is that we do not know the IP address of the redis-server if it is submitted via PBS. This is why we proposed that we start redis-sever from within SoS and let the redis-server write down its IP address.

**Comment by gaow** [comment]
Yes I should say that we can start redis server then obtain `host_url` ... updated the comment above. The point still sticks that it would be easier if SoS can start / stop worker for each process. I think we can manually maintain the server because it is crucial to have running before workers start. We can then auto start works to connect to it.

**Comment by BoPeng** [comment]
"for each process"? What do you mean? The idea was to share workers among sos processes.

**Comment by gaow** [comment]
Sorry I should say for each SoS script, or SoS instance, we can possibly start within SoS a number of works at different nodes all connecting to the server; that way we keep track of what have been started; and we shut them down automatically after the instance has done its job.

**Comment by BoPeng** [comment]
SoS does not need to know or track how many workers have been started. It only needs to talk to the redis server. Start within SoS a number of workers at different nodes is also not practical because the workers would be started by PBS.

So in #234 I proposed that

1. we start a redis-server manually (PBS or not). The redis-server writes down its IP address in a configuration file.
2. we start multiple workers manually (PBS or not). The worker checks the configuration file for IP address of redis server and connect to it. The worker will die if it cannot connect to a redis server.
3. we start multiple sos instances. SoS checks the configration file and send jobs to the same redis-server.
4. we manually shutdown redis-server after all jobs are done. The workers will die after they cannot reach the redis server. They might also be starved to death.

**Comment by gaow** [comment]
I guess now the biggest problem is still PBS ... I was thinking by manually starting the server via PBS then we'll know that SoS will surely be able to talk to the server. If we start workers from within SoS then even if only part of those workers were successfully initialized they are still surely able to connect to server. But I agree that doing this via PBS inside SoS is still hard.

On the other hand, if users do not use SoS, they still have to submit N jobs to use N nodes. In contrast we submit N + 2 jobs with N workers, an additional server, and the SoS job (on the same machine as the server). So even though we did not save people's efforts in submitting we are not letting them submitting many additional jobs either. So I guess it is reasonable.

**Comment by BoPeng** [comment]
The redis server and sos "submitters" are supposed to be less resource intensive. They can reside on different nodes although they are likely to be on the same node on my system because they request less resource.

**Comment by BoPeng** [comment]
No longer applicable with the current remote execution framework. The RQ server must be setup externally.
