### ISSUE TITLE
Youtube videos

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#276]
We will make very short videos for specific topics about SoS. Each one should focus on very specific topic of sos, e.g. one option. This ticket will be used to plan the content of each video.

@BoPeng will record the videos but please feel free to contribute ideas. Basically, we need to have detailed outlines of the videos (what to talk about etc) before we start recording.

**Comment by BoPeng** [comment]
## Video 1: Why SoS Notebook matters
Subtitle: What is multi-language working environment and why does it matter.

1. We are used to working environments for single languages, such as R-Studio for R, Spyder for Python. There are multiple language IDEs (e.g. Eclipse) but each language is separate.

2. Because of the language barriers:
  * There are numerous ways to call another language from one language. E.g. `system` for shell commands, `rpy`, Python matlab engine etc
  * There are numerous attempts to `migrate` good libraries from one language to another (e.g. `ggplot` clone of R in Python)
  * These bridges or clones are immature, difficult to use, but most importantly, not native.

3. SoS Notebook as a multi-language working environment:
  * All languages are local
  * Solves the problem of single environment (for editing, debugging etc)
  * Solves the problem of inter-language data exchange (so not a collection of unrelated scripts)

**Comment by BoPeng** [comment]
### Installation of SoS and SoS Notebook (for Mac)

1. Anaconda Python 3
2. `pip install sos`
3. Use of `sos` command 
4. `jupter notebook`
5. Installation of `ir` kernel, and `bash` kernel

**Comment by BoPeng** [comment]
### Basic usage of SoS Notebook

1. Start jupyter server `jupyter notebook`
2. Start a web browser and choose SoS kernel
3. Select language
4. Execute cell
5. Line by line execution
6. SoS Magics

**Comment by BoPeng** [comment]
### Preview

**Comment by BoPeng** [comment]
I just created a very short video, just to test the screen-capture software and the new (professional level :-) microphone that I got today. Not sure how to get a video of me and embed in such a video (e.g. a picture in picture in the lower right corner), but this is a good start.

https://youtu.be/Mttff05R_KU

**Comment by gaow** [comment]
Great start! The new microphone is good. Not sure if having embedded video is helpful, but having subtitles might help for people who does not want ot wear headset (like me). Youtube has the feature and tutorials to add captain via speech recognition, maybe worth a go?

**Comment by BoPeng** [comment]
I can already see subcaption when I watch the video on my cellphone. No idea what is going on.

**Comment by gaow** [comment]
Ahh I see, I disabled it by default. This is the unedited version so there are quite a few mistakes, and the display is not as nice as captains embedded by dedicated software.

**Comment by BoPeng** [comment]
Yeah, I know. Auto-CC recognized most of my words correctly at first when I spoke a bit slowly and clearly, but messed up quite a bit later... I suppose this is unavoidable with my Chinese accent, which might or might not improve after I get better with this youtube stuff.

Using powerpoint has the problem that people have to rely on my interpretation to understand what is going on. I can imagine that most of the videos would be live demonstration, in which I will open Jupyter/Vi etc, enter SoS scripts, run, and vocal interpretation would be less important.

**Comment by BoPeng** [comment]
Now I see a real use of the live server. I mean, instead of starting a Jupyter server each time, I can just go to the SoS website, click a button and connect to the server. Perhaps you can try again to set it up?

The problem is that it would be difficult to change videos once they are recorded so we will have to keep the (or a) server running after we post the videos.

**Comment by BoPeng** [comment]
### String interpolation

1. One of the biggest differences between SoS and Python (or extra syntax)
2. The use of `${}`
3. Point 1: Applicable to `" "`, not `' '`
4. Point 2: The usual Python `format` syntax (`:`)
5. Point 3: The script format is `""" """` that subject to interpolation.
6. Point 4: Converters
  * Manipulation of paths
  * Handling of arrays and dictionaries (which is quite different from Python 3.6 format string syntax)

**Comment by BoPeng** [comment]
### Script format

1. What you usually see  in a SoS script
2. is actually a normal function call written in a different format
  * with script as `""" """` style of the first parameter
  * with others as keyword parameters of the function
3. You can use `R(''' ''')` to avoid interpolation, to use inside `if/else` etc
4. Indentation is optional but recommended, and why (because script only ends with new section header)
5. The script can append/prepend content from files specified with parameter `input`
6. Alternative sigil?, this is too advanced.

**Comment by BoPeng** [comment]
### `%render` magic

**Comment by BoPeng** [comment]
### `%run` magic

**Comment by BoPeng** [comment]
### `%sosrun` magic

1. How workflows are defined within a Jupyter notebook
2. How to execute the workflow within Jupyter (the `%sosrun` magic)
3. How to execute the workflow from command line (the `sos run myscript.ipynb` command)
4. How to export workflow to `.sos` file

**Comment by BoPeng** [comment]
### SoS variables `output` and `_output`

**Comment by HenryLeongStat** [comment]
Making tutorial based on video is really a good idea since beginner tends to prefer videos than long documentation.

According to all the videos I have watched on Youtube, the subtitles which are generated automatically are not very accurate even the lecturer is a native speaker. Besides embedding the subtitles, maybe we can write some notes in the description?

Btw, the microphone is really great! 👍

**Comment by BoPeng** [comment]
OK, not a PR-type guy so everything is new to me. Now if you go to https://www.youtube.com/watch?v=Sm0fJRm-cdg&feature=youtu.be , you should be available to subscribe to a new channel ScriptOfScripts... I created a new gmail account for this youtube channel, I think I can invite you guys to this channel to help edit the videos (e.g. add subcaption) but not sure how to do that yet...

Also there is a twitter account ScriptOfScripts now that is empty, but you can follow.

**Comment by gaow** [comment]
Wait, why is the channel called "ScriptOfScript" (missing an `s`)? The name reads a bit awkward, though. Is `vatlab` taken on youtube?

**Comment by BoPeng** [comment]
Oh, that is a typo. `vatlab@gmail.com` is taken so I registered `scriptofscripts@gmailcom`. I have renamed the channel to `SoS` because there is no plan to youtube other parts of vatlab, at least for now.

**Comment by BoPeng** [comment]
Added slides for installation: https://github.com/vatlab/sos-docs/blob/master/src/videos/installation.pptx , with a title page

![image](https://user-images.githubusercontent.com/9889312/31412511-05801908-addb-11e7-9573-53e9dfeae55b.png)

**Comment by gaow** [comment]
I saw the new video on notebook -- this is great!

What to record next? Seen from this thread I see the upcoming ones are on SoS syntax etc. I wonder before that, we should have an overview of SoS workflow using very simple examples, eg, those along the lines of Figure 1 of SoS paper, instead of diving into details. And the next can be multi-style workflow video I assume, and with those 2 videos the users will get a very good big picture view of what's going on?

**Comment by BoPeng** [comment]
SoS Notebook is easier to present so I went with this one first. The video is much longer than I expected but I do not have the energy to re-record or edit it. I will try to control future videos, especially for those single-feature videos (e.g. one explains `input` and `_input`, one explains script format) to be within 5 minutes.

An overview of SoS should be the next one but it is more difficult. I plan to find some alternative commands than the quick tutorials, but follow the steps in the quick tutorial to demonstrate the format, the header, variables, header options etc. I am planning on one or at most two videos per week so this has to be done next week.

**Comment by BoPeng** [comment]
### Overview of SoS Workflow Engine (done)

https://youtu.be/dDlqn26ulu8

**Comment by BoPeng** [comment]
### Using SoS inside of SoS Notebook (done)

Notebook workflow, `%sos` and `%sorun`

https://youtu.be/TxcPwyCVa8Y

**Comment by BoPeng** [comment]
I think we have completed all the "primary" overview videos and the rest would be very technical videos on specific features. 

Till next week though.

**Comment by BoPeng** [comment]
I have found it unnecessary to plan and summarize the videos here.
