### ISSUE TITLE
Design of homepage

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#302]
This deserves a separate ticket.

There should be `INSTALLATION` or `GETTING STARTED` . There should be a github logo somewhere, and no `TEAM` and `CONTACT` (for now).

Not sure if we should use the tab layout (e.g. [beaker](http://beakernotebook.com/getting-started)) or the current one page for all design. I have a feeling that we should have dedicated pages (tabs) for installation instructions, and list of documentation. This leans towards the tab design.

There should also be a `Run SoS` button to lead to our public jupyter server.

**Comment by gaow** [comment]
Do you want to try something simple yet elegant? For example just bootstrap:

https://bootswatch.com/cosmo

`cosmo` is a good theme to me. But you can see others. I like such simplicity with a modern test.

**Comment by BoPeng** [comment]
@jma7 might have the most website related knowledge among us, at least in term of javascript. "simple yet elegant" does fit my design goal for the website but I do not know what it takes to use cosmo (or something else) because all these modern websites seem to be javascript/bootstrap etc based ...

Anyway, we are not giving up the jekell stuff because we essentially only have one page (maybe tabbed) so it should be easy to test a few... Perhaps you can customize a cosmo site and see how it works?

**Comment by gaow** [comment]
So instead of jekyll we can use R markdown. It is pretty straightforward:

http://rmarkdown.rstudio.com/rmarkdown_websites.html

And the outcome is:

[rmarkdown.zip](https://github.com/BoPeng/SOS/files/641046/rmarkdown.zip)

What do you think? Perhaps @jma7 can play with this? We just write RMD files (which is like MD files) for those home pages, and use a YML template to specify the style, and run from R markdown.

**Comment by BoPeng** [comment]
Come on, rmarkdown, cannot R stay at its own regime, something called statistical computation? The website is a bit "too simple" to my taste, though (unless there is some good template).

**Comment by gaow** [comment]
R ecology is rather interesting. Rstudio certainly made a difference by
being the only single engineering team in R world. Albeit simple and
restricted there's no qualified competitions and thus less of a chaos
compared to outside world. The R plannet citizens really appreciate their
work.

**Comment by jma7** [comment]
I could try some other themes and design for sure. I think just use bootstrap and js will give us more flexibility.

**Comment by BoPeng** [comment]
I noticed that the homepage has switched to tabs, could you let us know how to edit individual pages? Are they in md, html, or js? We should also replace the tell me more button with a "Try me now" button.

**Comment by BoPeng** [comment]
Just realize that "Tell me more" and "Try me now" cannot be put together. We should change "Try me now" to "Run SoS", "Try SoS Now", or "Run SoS Now". And two buttons need to separate a bit more.

**Comment by BoPeng** [comment]
"Run SoS" is shorter than "Tell me more" so the buttons have different size. We should either fix button size or use "Try SoS Now" to make the second button larger.

**Comment by BoPeng** [comment]
I have found our current tab design inconvenient in that I need to scroll down for any action I would like to take. This becomes especially troublesome when I would like to for example, switch from documentation to tutorials. If possible, please move tabs to the top of the screen so that they can be more accessible, and make the banner image shorter. https://emby.media/index.html is a good example for these.

**Comment by jma7** [comment]
How about separate tutorials and documents into two tabs?

**Comment by BoPeng** [comment]
Then there is no appropriate place for examples. My concern is that although the homepage looks nice, it does not have any actionable link without a scroll-down action. I have tried but unfortunately did not figure out how to shorten the banner image and see how well the bottom tabs work in that case.

**Comment by jma7** [comment]
OK, either way will work.

**Comment by BoPeng** [comment]
Thanks. It has been a bit frustrating to stare at a big trunk of css/js and do not know how to do "simple" things such as shorten the banner image, change tabs to all cap with another font, stop capitalization of section head, change paragraph text size (e.g. documentation page)...

**Comment by jma7** [comment]
You could add the edit you want in the testtab.css, this is the last style file added to the javascript file which will overwrite all the previous ones.

**Comment by BoPeng** [comment]
Some changes are applied, e.g. `.nav-tabs li a {font-size:22px;   text-transform: uppercase; }`, some do not (e.g. remove other uppercase transformation), some are not defined here (e.g. the uppercase definition for `h1` is in `agency.min.css` and cannot be overwritten from here).

**Comment by jma7** [comment]
There are additional js in_Kernel.ipynb, Auxiliary_Steps.ipynb and Understanding_Targets.ipynb too. @BoPeng

**Comment by BoPeng** [comment]
We can keep them as long as they do not interfere with anything.
