### ISSUE TITLE
Problems with nested `task` option

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#339]
A MWE:
```
[test_1]
n = ['{}.out'.format(x) for x in range(4)]
input: for_each = ['n']
output: _n
task: concurrent = True
run:
  touch ${_output}

[default]
task: workdir = '/tmp'
sos_run('test')
```
The outcome is:

```
ERROR: Failed to execute workflow default
[default_0] ExecuteError:
	Failed to execute workflow test
[test_1] RuntimeError:
	Output target 0.out does not exist after the completion of step test_1
[test] RuntimeError:
	1 failed step: test_1
[default] RuntimeError:
	1 failed step: default_0
```
However if I remove the `task` derivative from the first step it will work. It looks like with the `task` in the first step it ignores the `workdir` definition under `task` in the 2nd step.

**Comment by BoPeng** [comment]
The problem here is that `${output}` is created under `/tmp` so it does not exist when it is tested in step `default`. The behavior of sos is questionable here because there should be no `${output}` in section `default` and nothing to test there.
