### ISSUE TITLE
Terminal height issue

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#340]
I run into this issue also a couple of days ago but I thought there is an easy fix I could do and I was too buried in work at hand so I did not open a ticket -- I was wrong because now I cannot reproduce it ... The message is:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.8.4.1-py3.5.egg/sos/utils.py", line 1011, in run
    with self.term.location(0, self.term.height - self.get_index() - 1):
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

The reason I was able to use SoS without fixing it is interesting: it only shows when I have a problem elsewhere with my script, and when that other problem is fixed I no longer see it. This is also why I cannot reproduce it. But looking at the message is there an obvious problem? If we cannot see an obvious fix then we can close it for now and I'll reopen when I get a reproducible example.

**Comment by BoPeng** [comment]
The error message says `self.term.height` is `None`, which means the `blessings` module failed to get terminal height for your terminal, but since this happens in a thread, it probably caused by data sharing problem when some error happens. The easiest fix is to 

```
(self.term.height - self.get_index() - 1) if self.term.height else ???
```
where ??? is something for last line (0 or -1?), which you can hopefully find from blessings doc.

**Comment by gaow** [comment]
Yes I thought the same. I looked at the code then and found multiple lines of such involving `blessing`'s `term.height`. I was just not sure what ??? should be. The doc is not helpful, but the code is, to some extend:

https://github.com/erikrose/blessings/blob/master/blessings/__init__.py#L219

So it relies on `struct` then fall back to `env`. I wonder what happen if we use `shutil` instead:

http://stackoverflow.com/questions/566746/how-to-get-console-window-width-in-python/14422538#14422538

Again perhaps it is easier when I can find a minimal reproducible example for this.

**Comment by BoPeng** [comment]
In case you do not know, adding #340 to commit message can link the patch to the ticket.
