### ISSUE TITLE
R kernel can't start in sos notebook. 

### ISSUE THREAD

**Issue by jma7** [vatlab/SOS#344]
I was just trying to follow the tutorials. I installed the ir package in R, and started a SOS note book, when I try ```%use R```, it seems it can't find R kernel? However, ir is in the kernel list and I can start a R note book. I just run setup.py in virtualenv. 

![screen shot 2017-01-02 at 10 53 26 am](https://cloud.githubusercontent.com/assets/22623882/21593179/f307d2b8-d0d9-11e6-865e-285189f529d4.png)

**Comment by BoPeng** [comment]
How about `%use ir`?

**Comment by BoPeng** [comment]
It looks to me that `setup.py` might have installed R to another interpreter. You can debug if the `R` language is properly installed by open your python console and 

```
import pkg_resources
group = 'sos_languages'
for entrypoint in pkg_resources.iter_entry_points(group=group):
     print(entrypoint.name)
```

and check if `R` is printed.

**Comment by jma7** [comment]
R is printed by above script, and ```%use ir``` works fine.

**Comment by BoPeng** [comment]
This is strange. You could add a `self.warn(repr(self._supported_languages))` to line 276 of `sos/jupyter/kernel.py` and see if R is loaded. As you can see from line 447, `%usr R` actually loads `ir` after it identifies `ir` from the language plugin.

**Comment by jma7** [comment]
It's working now.
