### ISSUE TITLE
Problem with nested workflow

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#346]
I'm porting some old codes to the latest version and I find myself in trouble with nested workflow. For example:

```
[work_1: shared = {'data': 'output'}]
input: "1.txt", "2.txt", group_by = 'single', pattern = '{name}.{ext}'
output: expand_pattern('{_name}.out')
task: concurrent = True
run:
  touch ${_output}

[another_work_1]
input: "1.txt", "2.txt", group_by = 'single', pattern = '{name}.{ext}', paired_with = ['data']
output: expand_pattern('{_name}.out2')
task: concurrent = True
run:
  touch ${_data} ${_output}

[default]
sos_run("work_1+another_work_1")
```

Will result in 
```
ERROR: Failed to execute workflow default
[default_0] RuntimeError:
	Failed to process statement 'sos_run("work_1+another_work_1")\n': Workflow work_1 is undefined. Available workflows are: default, work, another_work
[default] RuntimeError:
	1 failed step: default_0
```

It looks like I can no longer mix-match steps with index. Is this intentional and what would be the proper syntax to achieve this with the current SoS?

**Comment by BoPeng** [comment]
Could you try `work:1`? The new syntax is `workflow:range` so `work_1` is not accepted as a sub-workflow.

**Comment by gaow** [comment]
Oh I was under the impression that this only holds when workflow is specified via command line. Yes it works. I should add a line to the doc -- speaking of which, is the theme changed back to the default purposely?

**Comment by BoPeng** [comment]
It is documented in http://vatlab.github.io/SOS/doc/documentation/Workflow_Specification.html#Sub--and-combined-workflows-15

Which theme? You meant naming of subworkflow?

**Comment by gaow** [comment]
I see. No I mean we used `jt` to change the website HTML theme to look more "polished" but currently it seems to revert back to the Jupyter default. 

![2017-01-03-11-20-40_scrot](https://cloud.githubusercontent.com/assets/917985/21616392/ea28abcc-d1a6-11e6-9ce0-ead570fd33e2.png)

**Comment by BoPeng** [comment]
Ohmm, I did not notice it. I added command `sos convert file.ipynb file.html` so I changed the `jupyter nbconvert` in `release` to `sos convert`, the `--template` option might have stopped working...
