### ISSUE TITLE
Moving jupyter theme css to separate file

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#347]
Right now each converted HTML file has a big blob of css code which I believe is from the jupyter theme. Because each of us might have different local style, we should store the css file under `docs/css/jupyter.css` and import it from the template file (`docs/src/documentation/toc_doc.tpl` and equivalent file under tutorial`). To achieve this,

1. figure out what .css is embedded (`~/.jupyter/custom/custom.css`?)
2. move it to `docs/css/jupyter.css` and add to git
3. figure out how to convert `ipynb` to `html` without using local customized css (at least reset theme locally before converting).
4. add `jupyter.css` to template
5. re-generate HTML files without embedded css.

We can then modify `jupyter.css` if needed.

**Comment by BoPeng** [comment]
I reset my local jupyter theme so some documents now have inconsistent style. Storing `custom.css` under `docs` instead of for each user locally should be the way to go.

**Comment by gaow** [comment]
Agreed ...  I have no other plans on weekend so I should be able to close this ticket by then.

**Comment by gaow** [comment]
This patch 9b6adad8aed188a470487fb9fd31af3af36af4b6 is a bit ugly but is what I think the best solution I can currently find. Since jupyter does not have a barely minimal HTML output product here we first generate the full HTML and use perl to remove about 13K lines of css style blocks. These blocks are instead saved to `jt.css` that will be included in `toc_xxx.tpl`. Would it work?

**Comment by gaow** [comment]
I'm yet to try to embed fonts to the CSS files. Currently the fonts are not good unless users have them in the computer. Should we also ship these fonts on our website, or we can use Google font API? Let me try to implement a version with Google font API and get back on this.

**Comment by gaow** [comment]
I decide to add fonts directly to `docs/fonts` because those files can be easily downloaded and are not large. However the code font `PT Mono` now looks a bit different from that via `jupyter-theme`. Perhaps I have downloaded the wrong font? Will try to look into `jupyter-theme` fonts and see.

**Comment by gaow** [comment]
I located font files installed to Jupyter and added them there and they look the same ...

**Comment by BoPeng** [comment]
A huge improvement on the removal of 13k lines from **each** html file. I am also happy that I can finally fine-tune the css, like removing the flashing orange scrollbar.

**Comment by BoPeng** [comment]
Note that a problem with jupyter theme is that it overrides sos kernel-specific style.
