### ISSUE TITLE
Use all global runtime signatures.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#350]
Right now we are separating file signatures to global (`~/.sos/.runtime`) and local (`.sos/.runtime`) runtime directories. This was designed for cases when we would like to pack projects and their runtime information. However, with the dedicated pack subcommand, sos would be able to get signatures anywhere so there is no need to keep local `.sos/.runtime`. It therefore makes sense to put all runtime information to the global runtime directory.

**Comment by gaow** [comment]
But is there a book-keeping concern? I'm worried for an actively used research computer / HPC account there will be too many runtime signatures accumulated over time. I often have the tendency to `rm -rf .sos` from time to time to clean things up. With global signature it would be hard to keep it neat.

**Comment by BoPeng** [comment]
You are right but without local `.sos` you do not have `.sos` here and there and there is less a need to clean up.

**Comment by BoPeng** [comment]
We could add some utility functions to clean up signatures related to certain workflow (e.g. `sos clean myscript`) but I am not quite sure if it is needed.

**Comment by gaow** [comment]
I think even if the global `.sos` has all the run time signature I could still clean my laundry by removing the local `.sos` combined with `-s force`. I'm just concerned there will be millions even billions of file signatures over time in the global `.sos` and will that be problematic in any way?

**Comment by BoPeng** [comment]
The signatures are stored in a very inefficient manner, both in terms of small files and access speed, with the biggest reason being the parallel execution of workflows and steps. I have long been thinking of using redis server for this purpose but file-based signatures are much easier to work with and perhaps more reliable (at least in the sense of persistency). I have not really touched the signature storage system because we first need to make sure sos works as expected.

We could also use a local sqlite database. The problem is that we have so many runtime information and potentially many processes accessing the same sqlite database. Although a lock can be used, it can be slow to acquire lock, open database, write item, close database, and release lock. Redis seems to be a better choice.

Using all global signature at least moves towards that direction.

**Comment by BoPeng** [comment]
Redis server would work like this:

1. Redis server starts if no redis server is available.
2. The server writes its information in `~/.sos/redis.conf` so that remote workers know how to connect to it.
3. All processes send and receive runtime information from the redis server.

The problems with this approaches include
1. Persistency, not sure how fault-tolerant a redis server is, but we should not lose any information when the server is killed.
2. Fault-tolerant: what would happen when the redis server is done while the worker still tries to send information?

**Comment by BoPeng** [comment]
So in the end maybe a local database daemon would be a better choice.

**Comment by gaow** [comment]
> Using all global signature at least moves towards that direction.

This is a sound argument. 

Running a redis server makes it a bit complicated to configure for regular users and maintenance (fault tolarance) can be a challenge if the users are to be responsible for it. I agree now that we can first use global signature to move towards that direction then look for better solutions from there.

**Comment by BoPeng** [comment]
Note that we have not tried [mrq](https://github.com/pricingassistant/mrq) because we have not really tested our tasks managers. If `rq` does not work as well as we would expect, we can try `mrq`, then if we have to use MongoDB for `mrq`, we might as well use MongoDB for signatures.

I personally feel less comfortable with redis' all-in-memory approach and would be more willing to work with MongoDB if it is easier to install and hide from users.

**Comment by BoPeng** [comment]
We could use both systems. If users have mongodb installed, they can use some command like

```
sos config --set sig_db localhost:port
```

to use mongodb version of signatures.

**Comment by BoPeng** [comment]
Most runtime signatures are moved, but workflow execution log and some other stuff remain in `.sos`. They will be moved based on a case by case basis.

**Comment by BoPeng** [comment]
Note the new `sos remove --signature/-s` command that removes all signatures related to current project.
