### ISSUE TITLE
Separate Documentation and Tutorial tags

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#359]
Currently we have both Documentation and Tutorials under the same tag `Documentation`. I think it would be easier to read if we separate them.

**Comment by BoPeng** [comment]
The problem is then where to place examples , at least before it can grow into a separate section.

**Comment by gaow** [comment]
A separate section down the line would be great -- if we can have one RNA-seq pipeline, a eQTL pipeline and a GWAS pipeline from our own work / publications.

**Comment by BoPeng** [comment]
That page at least now is not very long. I would propose that we keep it as it is until it gets longer.
