### ISSUE TITLE
toc panel scrollbar/height issue.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#360]
My my browser, the shorter docs are ok, but for long docs such as http://vatlab.github.io/SOS/doc/documentation/Function_Reference.html when a scrollbar is needed, the toc does not make full use of the height (as show below). Maybe there is some easy css fix to this.

![image](https://cloud.githubusercontent.com/assets/9889312/21777726/ae543030-d665-11e6-918c-2f55e18dde7f.png)

**Comment by BoPeng** [comment]
![image](https://cloud.githubusercontent.com/assets/9889312/21777997/147c16b0-d667-11e6-846b-26c859d6b6a5.png)

The panel would work as expected if I disable the `height` property of `element.style`, not sure where this was set though.

**Comment by jma7** [comment]
fixed.
