### ISSUE TITLE
R kernel issues

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#365]
I've been having these issues for R kernel since last update. See the screenshot here: 
![2017-01-12-08-41-43_scrot](https://cloud.githubusercontent.com/assets/917985/21893974/16ecf0b6-d8a3-11e6-918e-8c8f7cd12e97.png)

As you can see there are several problems:

1. `%use R` never works, which has been reported before and I've been using `%use ir`.
2. Even `%use ir` would not work unless you execute it **twice** in the same cell. See Cell 6. 
3. Now after running it twice I can successfully run R code as in Cell 9. However moving on to Cell 10 the data is no longer there. Unless I run all in the same cell see Cell 11 I will be able to execute. 
4. I do not see the newly added coloring, etc, for different kernels. 

Not sure if the same symptom is observed on your end, though.

**Comment by BoPeng** [comment]
Sorry, the patch send different messages to the front-end to work with Jun's front-end work (adding language selection drop down boxes). Jun should be able to finish his patch today.

**Comment by BoPeng** [comment]
It should be more or less working now. Will do more testing after the big frontend change.

**Comment by BoPeng** [comment]
The front-end work is done. Please test and let me know if you notice any problem. Briefly speaking,

1. cell dropdown displays kernel used.
2. existing cell will be re-evaluated with the previous kernel
3. changing kernel through cell dropdown changes start the cell with specified kernel (but %use in the cell can still switch out)
4. global toolbar dropdown lists default kernel (kernel for new cell and cells that have not been evaluated).
5. change of default kernel will be reflected there (e.g.`%use`)
6. change in dropdown lists changes sos default kernel (as if a `%use` is used), also kernel for any new cells.

Hopefully this is intuitive enough so that users do not have to memorize all these.

**Comment by gaow** [comment]
Great! Now the `%use ir` works at the first load. However other behavior still puzzles me:

1. If I load `%use ir` multiple times there will be error messages. See Cell 2 below
2. Cell 3 and Cell 6 still fails -- this contradicts what you'd expect in item 2 of your list above.
3. There is nothing added to my `Cell` dropdown menu or global toolbar so I cannot judge the rest of the expected behavior you've listed. 

![2017-01-13-08-44-09_scrot](https://cloud.githubusercontent.com/assets/917985/21933814/8b2bd266-d96c-11e6-8836-b73e8f59c9bb.png)

**Comment by BoPeng** [comment]
Why do not you show any dropdown list? Could you reset your theme?

**Comment by gaow** [comment]
I've no idea ... I use the default theme. I just reset it via `jt -r` but it does not make any difference. Let me clean up my SoS installation and install again and will comment here if that helps.

**Comment by BoPeng** [comment]
Force reload (ctrl-reload) or clear cache?

**Comment by BoPeng** [comment]
![image](https://cloud.githubusercontent.com/assets/9889312/21934223/3ace68b8-d96e-11e6-9089-266565064bf0.png)

**Comment by BoPeng** [comment]
You should see menu dropdown and per-cell dropdown, and color change with successful kernel switch.

**Comment by gaow** [comment]
No -- I reinstalled the package and did ctrl-reload. Same old. However at one point I did see those dropdown menus and all other behavior were as expected! It was immediately after I reinstall and did ctrl-reload. Only my dropdown menu says `ir` not `R`. Then I lost it -- cannot reproduce it whatsoever. I guess it is really hard to test it on your end since you do not have these issues. I also tried to open the notebook in the incognito mode on google chrome. Not successful. 

I guess I'll try later today this on another computer and see if it fixes things.

**Comment by BoPeng** [comment]
We saw something similar, clear cache might work. Or change to safari if you are using chrome.

**Comment by gaow** [comment]
Hmm ... I tried Firefox, not working. I have to try Safari later today as I do not have a mac with me right now.

**Comment by BoPeng** [comment]
I see, we might be burnt by a browser js compatibility issue.

**Comment by BoPeng** [comment]
Are you on linux or windows?

**Comment by gaow** [comment]
I'm on Linux.
