### ISSUE TITLE
A scratch panel for SoS jupyter frontend

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#380]
The nbextension [scratchpad](https://github.com/minrk/nbextension-scratchpad) is very useful in that it allows us to test commands, check variables, etc without saving things to the notebook. Unfortunately, the scratchpad does not work well with SoS frontend because its panel take the right half of the window and covers the kernel-selection buttons.

I have submitted [a request](https://github.com/minrk/nbextension-scratchpad/issues/11) to make the scratchpad panel float so that we can move the panel to the left. We can also consider adding a scratchpad to SoS, with

1. A toolbar button (instead of floating like the current scratchpad extension) to open/close scratch pad, in a way similar to toc2.
2. The scratchpad can be float, but would by default dock at the left similar to toc2. 
3. Execution of statements in scratchpad would not increase `execution_count`.

Implementation wise we can borrow ideas from [scratchpad](https://github.com/minrk/nbextension-scratchpad) (execution of cells) and [toc2](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/toc2) (UI).

I do think this can be a good addition to our SoS frontend but let us wait and see if @minrk can make the scratchpad float.

**Comment by BoPeng** [comment]
We should try to improve scratchpad, and think of further improvements in the context of #381.

**Comment by jma7** [comment]
I think it is a useful feature. Have you tried scratchpad on local sos notebook? It seems I can't get the script in the scratchpad running.

**Comment by BoPeng** [comment]
I tried, it worked. I am playing with scratchpad.css. I could get the scratchpad to the left, but cannot get the notebook shift to the right. Perhaps you can come over to my office?

**Comment by BoPeng** [comment]
Please do not use word scratchpad for the left panel because we are going to use the panel for multiple purposes ( #381), use a more general word `panel` instead.

**Comment by BoPeng** [comment]
The author of scratchpad suggested

>  I think jquery-ui is the easiest way to make an HTML element float-able.
>   cf https://jqueryui.com/draggable/

**Comment by jma7** [comment]
Yes, that is what used in toc2.

**Comment by jma7** [comment]
Try to click on the cube icon in the toolbar to observe the scratchpad. I still have problem in getting code executed in the code cell in scratchpad. I suspect it may need some "%softwith" patch as what you have done in the main script?

**Comment by BoPeng** [comment]
The cube does not work on safari and chrome from mac. I suspected that I need to change setup.py to install .js files.

Why do you still keep codemirror stuff in kernel.js?

**Comment by jma7** [comment]
I am using chrome on mac which works fine.

**Comment by BoPeng** [comment]
I can see `js` does not have to be copied to the kernelspec directory because it is loaded from sos (looks like magic to me). But I cannot make the button work.

**Comment by BoPeng** [comment]
Perhaps you forgot to push some css file?

**Comment by jma7** [comment]
You are not in the office...css file is in the js. How about you try to checkout b9963421b1364a36bf88c442d202343b13f453be? The files are not separated in that commit. Maybe some path issues.

**Comment by BoPeng** [comment]
I tried, not path problem, because I can trace into the toggle function from browser.

Perhaps because you have other nbextensions installed/turned on?

**Comment by BoPeng** [comment]
I have  a local scratchpad extension that might have been messed up by me, and your button can change it. Could you rename the item and function to avoid it?

**Comment by BoPeng** [comment]
I can see that you have

```
var Scratchpad = function (nb) {
    var scratchpad = this;
    this.notebook = nb;
    this.kernel = nb.kernel;
    this.km = nb.keyboard_manager;

    // create elements
    this.element = $("<div id='nbextension-scratchpad'>");
```

so the real scratchpad is affected. I suppose you can name it as something like `id=sos-panel`.

**Comment by BoPeng** [comment]
I see

![image](https://cloud.githubusercontent.com/assets/9889312/22387573/dcdf2636-e4a1-11e6-9f9e-3848d47887cb.png)

so the scratchpad has height 0. Do you see the same scratchpad style on your browser?

**Comment by jma7** [comment]
I changed all the scratchpad to scratchtab.

**Comment by jma7** [comment]
The initial height is 0, click on the cube makes it appear.

**Comment by BoPeng** [comment]
The height field would refresh with the click of button, and then to 0 again,

**Comment by BoPeng** [comment]
Did you push you scratchtab change?

**Comment by BoPeng** [comment]
I now see the new name, but still the same behavior. Perhaps you can try to clear your cache or use a different browser?

**Comment by jma7** [comment]
Looks fine on safari and Firefox.

**Comment by BoPeng** [comment]
It can be my chrome, because I can see the scratchtab on windows edge. ...

**Comment by BoPeng** [comment]
Yeap, uninstall chrome, remove Library, reinstall fixed the problem. I will see how to make it work with the kernel.

**Comment by BoPeng** [comment]
Ctrl + (enlarge) will send the scratchtab away. So this thing is not yet toc-like float. (Not a big deal for now).

**Comment by jma7** [comment]
Yes, that hot key is not defined for scratch pad yet. You can try ctrl+b to toggle.

**Comment by BoPeng** [comment]
Chrome just falls back to the old non-working behavior... strange. :-(

**Comment by BoPeng** [comment]
I need to zoom in to a certain large font to have the scratchtab displayed... You can zoom out and test.

**Comment by BoPeng** [comment]
Or it should be the exact zoom level when the sratchtab is first displayed...

**Comment by jma7** [comment]
OK, I see that too.

**Comment by BoPeng** [comment]
Good. I must be on a particular resolution with my old chrome. You do not have to fix it now if you do not see a quick fix.

**Comment by jma7** [comment]
changing from checking height==0 to height<1 solve the problem, don't know why...

**Comment by BoPeng** [comment]
The scratchtab will always be displayed, but zooming would mess up the layout. We can switch to toc2 style floating panel later, but is it possible to adjust its width with mouse?

**Comment by jma7** [comment]
I think it should be able to behave like toc2. We can just replace all those contents in toc2 with the code cell.

**Comment by BoPeng** [comment]
Toc2 is certainly better, but later.

I am trying to make the execution in the loop of sos.

**Comment by BoPeng** [comment]
It is working now. I am opening new tickets for small improvements.
