### ISSUE TITLE
Matlab support.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#394]
We have a decent matlab user-base here and it seems to be the next easiest one to implement. We can add basic support and implement more advanced data structure later.

**Comment by gaow** [comment]
I agree with making matlab priority! I'm doing a project that needs matlab codes. Currently we use an R package for matlab file I/O though. I guess we'll not take that path here considering we have rejected using rpy2 for R / Python communication at one time.

**Comment by BoPeng** [comment]
I have matlab installed but it has been ages since I last used matlab. If you are USING matlab, you should take the lead on its sos support. It should be much easier than R.

**Comment by gaow** [comment]
I do not use matlab to program. It is a piece of code for a clustering algorithm others have in matlab that I think is too much work to re-write. We use R's `R.matlab::writeMat` to perpare input for the matlab code, run it on the university cluster (that has matlab) and use `R.matlab::readMat` to load output to R. That was the easiest way I found for data communication after a quick search. I'm pointing to that package but perhaps we do not want to adopt an R package for this goal.

**Comment by BoPeng** [comment]
Of course no. All communications are between sos (Python) and LAN and lan1 to lan2 is lan1 to sos to lan2 . There is a mature Python matlab module and no reason to involve R.

**Comment by BoPeng** [comment]
matlab already have mature support for python, it should be easy to convert python object to matlab using a null function in matlab (https://www.mathworks.com/help/matlab/matlab_external/call-matlab-functions-from-python.html). However,

1. Pandas `DataFrame` is not natively supported so we will have to export to file and then import.
2. Passing matlab variables to Python is not very easy, I assume we can handle simple types manually and other types in `.mat` file (https://stackoverflow.com/questions/38197449/matlab-data-file-to-pandas-dataframe).

**Comment by BoPeng** [comment]
There is a matlab [table](https://www.mathworks.com/help/matlab/ref/table.html) type that naturally correspond to Pandas `DataFrame`. Because dataframes can be large, perhaps saving table to `.csv` file and load from anther end is a good idea, but perhaps `scipy.io` supports table as well.

**Comment by HenryLeongStat** [comment]
Is it matlab [table](https://www.mathworks.com/help/matlab/ref/table.html) type is the same as Pandas **DataFrame**? I just checked about [table](https://www.mathworks.com/help/matlab/ref/table.html), one specificity of  [table](https://www.mathworks.com/help/matlab/ref/table.html) is that in different columns, there can be different number of elements. (e.g. column 1: [1], column 2:[1,1]) I am not sure whether Pandas **DataFrame** has the same specificity.

**Comment by HenryLeongStat** [comment]
Sorry for all the mess... Didn't know using `fixed` as the end of the title would close the issue automatically... Please check [0e223ea](https://github.com/vatlab/SOS/commit/0e223ea9df3019727ab010aa732b9ed2eac72598) and [0c2f7a6](https://github.com/vatlab/SOS/commit/0c2f7a635a6f22656e60dfe9092928f4654bc5b7) for all the changes...

**Comment by HenryLeongStat** [comment]
passed the test! 
<img width="716" alt="screen shot 2017-07-25 at 3 59 17 pm" src="https://user-images.githubusercontent.com/26916551/28593540-3e074244-7152-11e7-87d2-e1f54b672633.png">

**Comment by BoPeng** [comment]
Could you try octave now? You can change to `%use Octave` if it works.
Otherwise the test suite will fail.
