### ISSUE TITLE
asyncio for sos tasks.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#399]
Not quite sure how to make use of asyncio in sos but it appears very useful to replace our multiprocessing + queue scheduling.... Need to learn more to see how we can make use of asyncio for sos.

**Comment by gaow** [comment]
It is not clear to me what advantage it has over multiprocessing module, after reading the doc page. Specifically:

> This module provides infrastructure for writing single-threaded concurrent code using coroutines, multiplexing I/O access over sockets and other resources, running network clients and servers, and other related primitives.

"Single-threaded concurrent code" means multiple concurrent instances each using single thread?

Not sure if the "running network clients and servers" part is relevant ...

**Comment by BoPeng** [comment]
First, it is the hottest stuff in the python world, so even if we are not using it with sos, we should learn it.

Second, sos on windows is not working because we use subprocesses a lot and windows is really bad at python multi-processing (basically each process is new, need to start a python interpreter, load sos and all its environments from scratch). I **hope** asyncio can save us there.

Third, the execution of DAG is currently implemented by a simple process-status array. It works but might not stand the abuse of large workflows and we might run into IO problems if we are not doing async IO.

Fourth, vat will be built on a web request model with a lot of requests between vat and vat-dp (data provider) and asyncio will almost certainly be used there.

**Comment by BoPeng** [comment]
`oncurrent.future` has been used for task submission.
