### ISSUE TITLE
explicit dependency?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#403]
Something like,

```
[some_step]

[step]
depends: sos_step('some_step')
```

In this way we can force the execution of `some_step` even if that step does not produce any visible file or target.

**Comment by gaow** [comment]
+1 to the idea. This is a very nice generalization of make style. I'm running into a problem that would benefit a lot from this feature.

**Comment by gaow** [comment]
But the `some_step` is not always executed, right? I expect that it will be skipped when it does have an output and its output is up to date. For example:
```
[some_step]
output: files
[step]
depends: sos_step('some_step')
```
then if `files` are up to date it should be skipped? What if multiple downstream steps requires it at the same time:

```
[some_step]
output: files
[step_1]
depends: sos_step('some_step')
input: None

[step_2]
depends: sos_step('some_step')
input: None
```

Will it create a race condition?

**Comment by BoPeng** [comment]
No. The step will be inserted to DAG once.

**Comment by BoPeng** [comment]
Implementation wise this is a bit tricky because the `existence` of the `sos_step(name)`  has to be successful execution of the step, which has to be retrieved from log file or DAG, neither is accessible from the target.

**Comment by gaow** [comment]
I'm thinking if we make it kind of an alias to checking for a step specific variable ... you see we do have `sos_variable()`. What if when we call `sos_step(name)` we in fact translate it to some variable target using some (internal) variable from that step and call `sos_variable()`?

**Comment by BoPeng** [comment]
So basically you are saying that the execution of a step would leave some trace in `sos_dict` (namely a variable)... this is indeed a good idea although this will add yet another env variable.

Note that we currently only check auxiliary steps (with `provides` and `shared`), but `sos_step(a_previous_step)` makes sense because `5` might depend on `sos_step(2)`. Then we need to expand the definition of auxiliary steps and say all steps can be depend upon.

```
1 - 2
    |
4 - 5  - 6
```

**Comment by gaow** [comment]
Yes your diagram is essentially the situation I got myself in! Hopefully we can afford an additional env variable in order to utilize an existing mechanism.

**Comment by BoPeng** [comment]
The problem is that there is no universal `sos_dict` in a multi-processing environment where steps inherit (sort of) dict from their upstream steps ...

Of course, everything is doable and the final patch might be short... just need to figure out the least intrusive way to get it done.

**Comment by gaow** [comment]
I'm thinking of whether this would also be a problem:

```
[a_step]
parameter: param = None

[another_step]
depends: sos_step(a_step)

[default_1]
sos_run('another_step', param = 1)

[default_2]
sos_run('another_step', param = 2)
```

Then calling `default_2` will SoS thinks that `step` has already been invoked due to `default_1` thus skipping it, providing `default_2` a bad input?

**Comment by BoPeng** [comment]
No, at least in your nested workflow case `sos_run` would trigger an independent DAG so `a_step` would be called twice.

I suggest that you write a test with intended behavior to make sure the feature works as expected.

**Comment by BoPeng** [comment]
A relatively troublesome problem is that we currently only include numbered steps and auxiliary steps from a script in a workflow, but this arbitrary `sos_step` requires us to include arbitrary steps in the workflow. Also, we exclude some names from steps (e.g. `mouse_1` would be removed from `[human_1, mouse_1]` for a human pipeline, but `sos_step('mouse_1')` should be possible as it is visible to users in the script.

So in the end we have to include everything, including included scripts to the workflow.... We cannot evern pre-screen steps with names in `sos_step(name)` because `name` could be a variable or expression.

**Comment by BoPeng** [comment]
If we limit selection to existing workflow steps, we are excluding simple cases such as

```
[something]

[1]
depends: sos_step('something')
```

**Comment by BoPeng** [comment]
@gaow can start testing.

**Comment by gaow** [comment]
Great! will surely do it soon later today. But before that, I'd like to know which one is more efficient to connect pipeline: using target on file or target on step?

**Comment by BoPeng** [comment]
Finding step is certainly more efficient than finding output, HOWEVER, the steps are triggered differently because there is no target to match, so NO default output.

**Comment by gaow** [comment]
Ok ready to test but the documentation is not there. I see it in the ipynb file though. Is it still being worked on or you forgot to update website?

**Comment by BoPeng** [comment]
I guess l forgot to update website. The documentation should indicate no
default input and output though.

**Comment by gaow** [comment]
This example, converted from examples used in other issues, fails for now:

```
parameter: fileset1 = ['{}.txt'.format(i) for i in range(2)]
parameter: fileset2 = ['{}.txt'.format(i) for i in range(2,4)]
parameter: fileset3 = ['{}.txt'.format(i) for i in range(4,6)]
parameter: fileset4 = ['{}.txt'.format(i) for i in range(6,10)]
parameter: fileset5 = ['{}.txt'.format(i) for i in range(10,14)]

[main]
parameter: output_files = []
input: for_each=['output_files']
output: output_files[_index]
task: concurrent = True
run:
  touch ${_output}

[joe_a]
output: fileset1
sos_run('main', output_files = fileset1)

[john_a]
depends: sos_step("joe_a")
output: fileset2
sos_run('main', output_files = fileset2)

[john_b]
depends: sos_step("joe_a")
output: fileset3
sos_run('main', output_files = fileset3)

[mark_a]
depends: sos_step("joe_a"), sos_step("john_a")
output: fileset4
sos_run('main', output_files = fileset4)

[mark_b]
depends: sos_step("joe_a"), sos_step("john_b")
output: fileset5
sos_run('main', output_files = fileset5)

[default]
depends: sos_step("mark_a"), sos_step("mark_b")
```

**Comment by BoPeng** [comment]
Try again.

**Comment by gaow** [comment]
It works for my workflow! This is great. I have a question: when two required steps have output overlap does SoS prevent them from stepping on each other?

**Comment by BoPeng** [comment]
Yes before, but not now. The steps would have different sig id if input, output and variables are not identical. This is to accommodate the cases when the complete `output` is specified for steps with input loop.

**Comment by gaow** [comment]
Close this for now ... will reopen if there is an issue.

**Comment by BoPeng** [comment]
Did you try the complex example you created?

**Comment by gaow** [comment]
Yes it worked for my workflow (when I said +1 on the 2nd comment of this ticket). It was, however a workflow for a pet project ... I'd use this features more often whenever needed and report back issues.

**Comment by BoPeng** [comment]
ok. We should somewhere document all the ways a step would be called.

1. regular, default input as previous output.
2. auxiliary, default output as triggering target.
3. depends, no default input or output.

In the end, a **well-defined** step would have
1. no default input
2. no default output
3. provides so that it can be used in both ways
4. parameter statements to make sure what external information need to be available
5. with to_host, from_host etc in case it will be executed on another host
6. runtime estimate (walltime etc) in case it will be submitted to queue
