### ISSUE TITLE
Cluster job submission and monitoring features.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#406]
Given that it is relatively troublesome to set up and use rq/celery task queues (dedicated redis server and workers are needed), we should design a new "cluster" queue to facilitate the use of traditional clusters with PBS/Torch/SunGrid systems. The following is a short description of the features that will need to be fully developed and implemented.

1. **`task` statement**: the task directive will be responsible for sending jobs to task queues and clusters. It is chosen because we have a mechanism already to send necessary environmental information to the tasks and make them self-contained jobs. 

2.  **job parameters** such as memory, node, walltime etc should be acceptable by `task` statement. (issue #240). These parameters will be backend independent because all queue systems need them.

3. **how to transfer files** this is related to #257 . Basically if the cluster and desktop are on different filesystems, we will need a way to automatically transfer input files to cluster and transfer output files back. Interface wise we can
    
    * define global file transfer commands in *config.yml*. e.g.
        `sos config --set to_cluster 'rsync -av {} mycluster:/path/project/`
        `sos config --set from_cluster 'rsync -av mycluster:/path/project/{} {}`

    * automatic file transfer. SoS will transfer all input files automatically to the cluster before execution, and transfer all output files back after execution. 

    * explicit file transfer: users can specify files and directories to be transferred. This can possibly be achieved by parameter `shared` of `task`.

    * Note that snakemake uses [remote files](https://snakemake.readthedocs.io/en/latest/snakefiles/remote_files.html) although it requires users to run snakemake commands on the cluster (which is discouraged if run on head node).

4. **how to submit jobs** Not sure how to do this, but the easiest method seems to be defining a command to remotely submit a jobs (e.g. `ssh mycluster:...`). The key part is that we should get a handle of "job" (job id) for query purpose.

4. **how to monitor jobs** Not sure how to do this but we could potentially query the status with job id using commands. Note that there can be separate web or command line monitoring interface for clusters.

5. **how to wait for the completion of jobs in batch mode** The step will simply wait for the completion of the job (signature written).

6. **how to wait for the completion of jobs in Jupyter notebook**. The front-end can collect the jobs that are running and display widgets to indicate status of the jobs.

7. **prevention of duplicated jobs**. Each job will have a remote signature and a lock so duplicated jobs will be prevented (the same job id would be returned).

8. **A sos daemon**? It might worth the trouble to run a sos daemon to accept, submit and monitor jobs.

9. **cluster-specific specification**. We should use `sos config` to define cluster specific parameters. public-key ssh access would be required to avoid storing passwords.

10. **queue configuration** We should make use of existing parameter `--queue` to specify queues to use. Once we have PBS working (`-q pbs`), it should be trivial to support additional systems such as `torch`, `moab` etc.

We should first investigate other technologies such as [ganglia](http://ganglia.info/), snakemake,  [drmaa-python](http://drmaa-python.github.io/), and [pbs-drmaa](http://apps.man.poznan.pl/trac/pbs-drmaa).

Here is an interesting read on [bioinformatics workflow using Galaxy + Makeflow](http://ccl.cse.nd.edu/research/papers/scaling-escience-2015.pdf)

**Comment by BoPeng** [comment]
[snakemake](https://snakemake.bitbucket.io/snakemake-tutorial.html) uses command line (qsub) and DRMAA, it might be sufficient for us to use their method.

**Comment by BoPeng** [comment]
The jupyter interface would be something like [the following](https://github.com/conda-forge/staged-recipes/pull/2334). Basically all jobs related to the current cell are listed, with status and details listed.

![image](https://cloud.githubusercontent.com/assets/9889312/22711631/7eb8dd28-ed47-11e6-877e-d21e1f119b28.png)

**Comment by gaow** [comment]
I agree it was a bit involved to setup rq on a traditional cluster. I have 2 Linux desktops that connects to each other and share a storage space. It was quite nice setup that gives me 16 CPU threads until the University IT asked me to shut it down. My early experience with snakemake qsub was not very smooth and I ended up exporting commands from snakemake and submit them manually. 

Can we look for something similar to rq yet without a server? For example:

http://dispy.sourceforge.net/
http://asyncoro.sourceforge.net/

I think this is a problem the community should have a solution for that we can take advantage from.

**Comment by BoPeng** [comment]
snakemake take a [very simple approach](https://bitbucket.org/snakemake/snakemake/src/096f56aaf6ced2614ee29207b56abe22eab05518/snakemake/executors.py?at=master&fileviewer=file-view-default#executors.py-483) that does not need any third-party library. Without first-hand experience, it seems that it requires users to login to the head node to run snakemake. Snakemake will wrap steps into bash scripts, submit jobs, and wait indefinitely for the completion of the jobs (there is a "progress" mechanism to monitor the jobs). This is not idea at least to us because we do not allow hanging jobs on the head nodes.

A non-invasive snakemake-like approach would be adding data synchronization functions/options (e.g. `remote(files, carrier=CONFIG['carrier_cmd'])`) and use ssh commands (e.g. `ssh cluster qsub < local_script`) to submit and monitor jobs. It is relatively straightforward (but not easy) to implement but I am not sure how well it would work.

**Comment by BoPeng** [comment]
[asyncoro](http://asyncoro.sourceforge.net/) also needs a [server](http://asyncoro.sourceforge.net/discoro.html) (similar to rq worker). Its location transparency looks very interesting but it might not be the one we need (external programs cannot access these files).

**Comment by BoPeng** [comment]
#414 has been implemented and merged to the master. **This feature should be considered as experimental and a first step towards proper remote execution of tasks.**

**Comment by gaow** [comment]
This is also an interesting read:

https://github.com/osbd/osbd-2016/blob/master/proceedings/S04209_3263.pdf

**Comment by BoPeng** [comment]
I am working towards "farming" my jobs to a remote linux server with docker support. Basically SoS handles data and task transfer and docker handles applications. Something like:

```
task:   on_host='linux_server', 
        to_host=[input, hg19_genes_gtf, hg19_Bowtie1_index],
        from_host="${output_dir}/tophat_main"

R1 = sorted([x for x in to_host(input) if '_R1_' in x])
R2 = sorted([x for x in to_host(input) if '_R2_' in x])
stop_if(len(R1) != len(R2), "Unequal number of R1 and R2 files from input ${fastq_files}")

run:    docker_image='genomicpariscentre/tophat2'

	tophat2  \
		--bowtie1 \
		--read-realign-edit-dist 1 \
		--segment-length 24 \
		-o '${output_dir}/tophat_main' \
		-p 7 \
		--GTF '${hg19_genes_gtf}' \
		--rg-id 0 \
		--rg-sample '${sample_name}' \
		--library-type fr-firststrand \
		--no-coverage-search \
		--keep-fasta-order  \
		--fusion-search --fusion-anchor-length 13 \
		--fusion-ignore-chromosomes chrM,M '${hg19_Bowtie1_index}/genome'
		'${R1!a,}' '${R2!a,}'
```

If this can be done, I would at least be free of problems I had with #414, I am bitten by #424 though.

**Comment by BoPeng** [comment]
The CJ is very similar for our task ( a fancier name) but seems to be more scalable.... We should definitely cite this paper for our definition of task.

**Comment by BoPeng** [comment]
The idea of CJ is great but I do not understand how it captures input and output files. I mean, a meaning bioinformatics task would have large input files and output files that would have to be removed after the execution so it is difficult to really make CJ reproducible.

We could however make task more friendly by making it easier to view the content, we might need some better interface than `sos status task -v3` . It is also interesting to provide web interface and notification features to tasks. I mean, if an email address is provided, the sos task wrapper could send an email notification for the change of status.

**Comment by BoPeng** [comment]
I suppose another big difference is that cj is designed for cluster, and sos execute can be run locally, or by any task systems on non-cluster environments.
