### ISSUE TITLE
Unavailable lock problem

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#408]
I am running into a problem which is a bit hard to prepare a MWE for. The message is:

```
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.3.1-py3.5.egg/sos/target.py", line 446, in __setstate__
    raise UnavailableLock((self.output_files, self.proc_info))
sos.target.UnavailableLock: Failed to obtain a lock for output [sim1_3.rds]
```

This problem is readily replicable. I removed `.sos` and `~/.sos` yet problem persists. I wonder under what situation that line of error message can be triggered. I have it on my desktop where I have write permission and enough space. Not sure how we can best debug this case without a MWE ... 

Currently I use `-j1` instead of `-j8` and the program seems to run fine.

**Comment by BoPeng** [comment]
Code is [here](https://github.com/vatlab/SOS/blob/master/sos/target.py#L445), basically we create a lock file for each signature. I remember we have had issue with too many opened file with locks not released aggressively around the same code? Will reducing loop size help?

**Comment by gaow** [comment]
I'm not sure. It does seem to fix the issue now that I run it on a smaller scale. Let me close the issue for now until I can find a MWE and reopen it.

**Comment by gaow** [comment]
Ok now I can reproduce the issue in this peculiar way: 

```
$ rm -rf ~/.sos .sos # Maybe for your case you want to rename them
$ sos run test.sos

Process ForkPoolWorker-1:1:
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/opt/miniconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/miniconda3/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/opt/miniconda3/lib/python3.5/multiprocessing/queues.py", line 345, in get
    return ForkingPickler.loads(res)
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.3.1-py3.5.egg/sos/target.py", line 446, in __setstate__
    raise UnavailableLock((self.output_files, self.proc_info))
sos.target.UnavailableLock: Failed to obtain a lock for output [a2.out, a1.out]

```
The test code is simple:

```
[1]
d = [1, 2]
input:  for_each = ['d']
output: ['a2.out', 'a1.out']
task: workdir = './', concurrent = True
run:
  sleep 2
  touch ${_output}
```

I wonder if it could be reproduced on your end.

**Comment by BoPeng** [comment]
The problem with the script is that it runs two concurrent jobs to generate the same set of output, so one of the tasks fails to get a lock for the output. The problem should go away when you define `output` for each job.

I would give proper error message if this scenario is confirmed.

**Comment by gaow** [comment]
I see .. yes I confirm that was the problem.

**Comment by BoPeng** [comment]
Close ticket. Note that this is designed to avoid multiple processes writing to the same output files.
