### ISSUE TITLE
An option to hide stdout / stderr from actions

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#413]
Sometimes we run into software packages (particularly in R) where the authors prints a lot runtime info on the screen without using a verbosity control to moderate it. It is straightforward to redirect the output in `run` / `sh` action but not with `R` or `python`. It can be very annoying particularly for some numerical algorithm that dumps large amount of information on the screen at each iteration. It also makes execution extremely slow. Does it sound reasonable that we add a switch to `sos run` to redirect stderr/stdout to /dev/null?

**Comment by BoPeng** [comment]
Tie this to `-v`?

**Comment by gaow** [comment]
Most natural is to tie it with `-v1` and I'm cool with it.

**Comment by gaow** [comment]
I'm getting rather annoyed with an R package in my pipeline that flushes my screen with lines of junks. Shall we make this work with `-v1`? I can try to change them, along the lines of:

```python
p = subprocess.Popen(cmd, shell=True, stderr=subprocess.PIPE if env.verbosity > 1 
         else subprocess.DEVNULL , stdout=subprocess.PIPE if env.verbosity > 1 
         else subprocess.DEVNULL)
```
I'm thinking should we only do it for `action.py` to control user scripts, or do it for all subprocess calls?

**Comment by BoPeng** [comment]
I do not see any side effect so please commit.... we can always revert if we find better methods.
