### ISSUE TITLE
Unify task execution

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#421]
Right now tasks are executed in different ways,

1. Local jobs are executed by `multiprocessing` `subprocess`
2. Multiple jobs are executed by `multiprocessing` `pool` (async)
3. rq jobs are executed through rq job submission
4. celery jobs are executed through celery job submission
5. remote jobs are executed through saved task files.

With the introduction of new `sos execute task` command, I would propose that we execute all tasks using the `sos execute` command. That is to say, the subprocesses will not fork the parental process, and will all read from a job description file. This has the benefits of

1. Simplified code.
2. Easier testing because we know a job would run if it runs in one of the environments.
3. Easier to use a job pool (#400)
4. Easier cross platform because this might work better under windows (#374)

**Comment by gaow** [comment]
A related comment: I think currently parallel computation is only possible for `task: concurrent = True`. This makes me wonder what the DAG is there for. For example, 

```
[1]
run:
stress -c 2 -t 60

[2]
run:
stress -c 2 -t 60
```

When running this script, because [1] and [2] are independent and no other jobs are involved, I'd expect with `-j8` the 2 jobs should run in parallel given the DAG logic. However it is not the case. I always consider it a limitation with SoS but it feels a bit daunting to make it otherwise. Maybe now that we are re-structuring the execution code it is a good chance to re-evaluate the behavior before others raise a concern.

**Comment by BoPeng** [comment]
SoS considers step `2` to be dependent of `1` if no input is specified. You can add `input: None` to achieve independent execution. This is by design to allow plain no input/output scripts to be executed sequentially.

**Comment by gaow** [comment]
Sorry indeed ... I should have created a better MWE. This is related to job pool for nested workflow (I'm a big fun of nested workflow):

```
[test_1, test_2, test_3, test_4]
input: None
run:
stress -c 1 -t 60

[1]
sos_run('test:1+test:2')
[2]
sos_run('test:3+test:4')
```

Now I expect 4 instances works in parallel, but it apparently runs `[1]` and `[2]` sequentially.

**Comment by BoPeng** [comment]
This is the same, `input: None` is needed for `[2]` as well.

**Comment by BoPeng** [comment]
Anyway, the road map is to first unify task executions, then use execution pool to reorganize `MP_Executor`.

**Comment by gaow** [comment]
I see. It's funny I've used nested workflow with input but I did not keep track on CPU usage in the context of that project; and for the situation I cared I did not use input! I should add `input: None` to that context and test it out -- doing it. Looking forward to the change!

**Comment by BoPeng** [comment]
The `input` design is a bit confusing so I have long thought of making it mandatary. Right now I think we can **strongly recommend** specifying `input` even if it is `None`.

**Comment by BoPeng** [comment]
Completed.
