### ISSUE TITLE
Better identifier of temp scripts in `.sos`

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#423]
Currently the exported temp scripts have file name `stepname_N1_N2`. However I've run into situations with multiple nested workflow, in the flavor of but much more complex than:  

```
[1]
sos_run('A:1+B:1')
[2]
sos_run('A:1+B:2')
...
```
what happen is that the file name `stepname_N1_N2` will get overwritten. It can be very annoying when errors occurred yet the pipeline did not stop immediately, and once it stopped it points to an updated version of `stepname_N1_N2` asking the user to run / debug, but in fact there is nothing wrong with that version of script. Can we use a better ID for these scripts that we can ensure that they are unique during the entire execution?

**Comment by BoPeng** [comment]
In light of the new remote execution feature where tasks from different machines could be sent to the same server, all jobs will have UUID names.

**Comment by gaow** [comment]
This is great! Just curious: what is the UUID? Is this the same as job signature, or some portable version of it? I wonder if one can access it from within a step like `step_name` -- maybe `uuid[_index]`? This may be unrelated to the ticket but I want to track for some jobs under given parameters very specific information such as running time, resource usage, etc, that is not part of my output. A temp file with UUID based file name would be very useful. I can then parse these tmp files and get what I want.

**Comment by BoPeng** [comment]
This is not hard but needs some work. Basically because actions has to know from its environment which step it is executed from so I have to pass step id in addition to step name to `env`, and I need to make sure all places where actions are executed have access to this id.

**Comment by BoPeng** [comment]
Do you need static unique ID (e.g. ID derived from content of the step), or runtime ID (e.g. ID derived from content and context), or purely unique ID (e.g. ID independent of steps)?

**Comment by gaow** [comment]
As long as it is unique, not to be overwritten by any other processes, I'd be cool. Whichever choice good for the design is good. Of course it would be nice to keep the name as short as possible because users might often need to debug and long file names would look ugly. Otherwise it does not seem very relevant  which type of naming convention it uses.

**Comment by BoPeng** [comment]
It is about potential to be overwritten. E.g. md5 of step would be overwritten if the same step is executed by different workflow (with different variable), context ID is better but can be difficult to get, unique ID would be long and random.

**Comment by gaow** [comment]
I see ... then I'd go for completely unique ID because I've had experience that my problematic got overwritten in a nested workflow and made the error message on the screen very much useless.

**Comment by BoPeng** [comment]
I simply add a random string to the temporary script. Not even tested. You can close the ticket if it works.

**Comment by gaow** [comment]
That sound like one way to go! I'll test and see if I have more suggestions to the issue.
