### ISSUE TITLE
Expose step md5/uuid to user script.

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#425]
This is related to my 2nd comment on this ticket #423. In R there is this `sessionInfo()` function. I wonder if we can have a similar built-in function to store various things unique to a step (including UUID) and to be able to call it in step script. I think the information must have been there but just not exposed to users, so may be it is not hard to enable it?

**Comment by BoPeng** [comment]
Not sure what you need exactly.

**Comment by gaow** [comment]
I think it should return *all* the step variables that uses cannot see otherwise, ie, `step_name`, `_index`, etc, plus the UUID, when implemented.  Anything internal to SoS yet is characteristic of the step may be useful. Also maybe text of scripts actually executed, after string interpolation. Running time, memory and CPU peak usage may be tricky because the are not available until after the run. I see it a useful debug feature and provides a way to make customized log only for steps of interest.

**Comment by BoPeng** [comment]
These information are in the `exe_info` files (global), and can be traced from the workflow `.sig` files (local to project).

**Comment by gaow** [comment]
Exactly! But these variables are currently stored in files. It is not possible to use them in the step. For example I want to know the UUID of the step so that I can create temp file with the UUID, rather than having to use different temp file mechanism for different languages. We have access to `step_name` but I find other session info, at least this UUID, can be useful.

**Comment by BoPeng** [comment]
I am a bit reluctant to do so right now because there has been too many such variables and `env.sos_dict`, which has made them difficult to maintain. I will see what I can do to organize them more cleanly, for example, some mechanism to add it somewhere and it will propagate everywhere so that I do not have to add them here and there.

**Comment by gaow** [comment]
Agreed. We should wait until the code is improved.

**Comment by BoPeng** [comment]
One step towards this goal is #421 (Unify execution). The idea is to make all external execution code a simple `sos execute task_file` call so the variables are wrapped to `task_file` once for all in `sos/sos_step`. Currently I need to make sure all needed variables are copied in `sos/rq/sos_step`, `sos/celery/sos_step` and two places in `sos/sos_step`.

**Comment by BoPeng** [comment]
Still need this?

**Comment by gaow** [comment]
Yes, it would still be great to have, for reasons in my previous threads.

**Comment by BoPeng** [comment]
Something like `workflow_id`, `step_id`, and `master_workflow_id` (in case this is a nested workflow)? All these would be md5 signatures from the content of step or workflows.

**Comment by gaow** [comment]
Yes, something like that. Although I have to admit my need for it is lessened now that our error message report keeps improving. Therefore the only practical use for it, for the time being, is to help configuring lazy outpout filenames that are guaranteed to be unique.

**Comment by BoPeng** [comment]
Yes, a practical use is to create your own report `{workflow_id}.log`. I do not know how to name IDs for workflow and master workflow though because the latter seems to be more practical and should have a shorter name.

**Comment by gaow** [comment]
Nested workflow can have arbitrary hierarchy, right? So in that case what if we do not distinguish and all use `workflow_id`? Then if this variable is used inside the nested workflow it means the sub-workflow; when used outside in flow with `sos_run` it is effectively the `master_workflow`?

**Comment by BoPeng** [comment]
You are right. The problem is that users might want to use an unique workflow ID through out the execution, and the master workflow ID (the outermost workflow) can serve that purpose.

**Comment by gaow** [comment]
I think I understand what you said and I think it is very reasonable.

**Comment by BoPeng** [comment]
I could use `master_id`, `workflow_id` and `step_id`, with `master_id` being the ID of the master workflow.

**Comment by gaow** [comment]
Okey for some reason, none of these ID matches the script filename generated: the script name is `test_0_0_541d7b59.R`. I have in the SoS script:

```
## UUID: ${step_id} ${master_id} ${workflow_id}
```

and inside `test_0_0_541d7b59.R` they still do not match:

```
 UUID: b2ac6c733bbefa77 2da0ac1d0d80e73d b967314c36d18404
```

In other words, I cannot tie the bad output log file with the script in question as prompted on the command line. What is the convention of the script name and how can i reconstruct it?

**Comment by BoPeng** [comment]
The ID in the filename was simply a random ID so that they do not override each other. We cannot make it `step_id` because currently `step_id`, unlike signature, does not take into account of environments so all input groups have the same `step_id`.

**Comment by BoPeng** [comment]
According to your scenario described in #423, `step_id` is equivalent to `step_name` (`test_0`) and the random string to differentiate runs is needed.

**Comment by gaow** [comment]
Okey, that's fine. Thanks for the clarification. I assume it is fine as long as users can trace back the environment and the corresponding problematic code from these unique generated scripts.
