### ISSUE TITLE
Problem with OrderedDict() signature

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#426]
Here is the MWE:

```
[test_1]
input: None
output: '1.txt'
from collections import OrderedDict
MyDict = OrderedDict([(1,2),(3,4)])
open(output[0], 'w').write(str(1))
```

Running it twice triggers a warning message:

```
WARNING: Variable MyDict  with value OrderedDict([(1, 2), (3, 4)]) cannot be restored from signature
```

If I use `list` or `dict` for the variable `MyDict` there is no problem.

**Comment by BoPeng** [comment]
Yes. I was trying to save plain text representation of variables so that they could be readable in the signature. `OrderedDict` could not be restored because of its not defined in the restoration module.

The solution is to use pickle to save and restore, which makes the signature file less readable.

**Comment by BoPeng** [comment]
A patch is submitted but is significantly slower (pickle, base64 encode/decode). Actually `sos run` is rather slow and I am not sure how much we can improve its efficiency later.

**Comment by gaow** [comment]
Would it help to use json, or `msgpack`?

http://www.benfrederickson.com/dont-pickle-your-data/

**Comment by BoPeng** [comment]
Well, would jason restore `OrderedDict` type??

**Comment by gaow** [comment]
Let me try `msgpack` with OrdereDict, numpy, etc and get back to you.

**Comment by gaow** [comment]
`msgpack` (and so is `json`) works for ordered dict but not numpy or pandas:
```
from collections import OrderedDict
import msgpack
import numpy as np
import pandas as pd

ordered_dict  = OrderedDict(((1,2),(3,4)))
#matrix = np.matrix([[1,2],[3,4]])
matrix = ''
#df = pd.DataFrame({'A':[1,2,3], 'B':[4,5,6]})
df = ''

data = {'1': ordered_dict, '2': matrix, '3': df}
print(data)
output = 'file.mpk'
open(output, 'wb').write(msgpack.packb(data))
data = msgpack.unpackb(open(output, 'rb').read(), encoding = 'utf-8')
```

**Comment by gaow** [comment]
I do have experienced drastic slow down in my script with large number of steps. I seem to remember we had some option to skip saving signature for certain variables -- was that the case? Also I think we should use `msgpack` instead and give warnings when users want to save signature for larger objects. I think data such as numpy matrix and pandas data frame should be stored in files anyways because they can be arbitrarily large. Saving them automatically is not a good idea.

**Comment by gaow** [comment]
> I do have experienced drastic slow down in my script with large number of steps.

Sorry I should take this back. It turns out my CPU was otherwise engaged for a dead job outside SoS ... so I'm yet to see what the real impact of this patch to large number of steps. I'll re-open the ticket if I can confirm and compare exactly how much slower.

**Comment by BoPeng** [comment]
Note that I previously take the approach to only save signature for basic types (int, str, dict, set, etc), but `OrderedDict` was saved because it is derived from `dict`. We could potentially just ignore more complex types because it does not make sense to save large data in signatures.
