### ISSUE TITLE
Ignore more complex types of variables in signature

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#428]
This ticket stems from #426. We should save only basic variable types in signature, and instead of pickle we use json / msgpack for the signature files format.

**Comment by BoPeng** [comment]
But there is no need to use json if we stick to basic types, save with `repr` and load with `eval` should be enough. This is exactly what was done, and was broken only because `OrderedDict` passed `isinstance(dict)` test but could not be `eval`ed.

**Comment by BoPeng** [comment]
Not also that signature file serves another important purpose, namely returnning results when the step is skipped. That is to say, to make sure a sos step runs correctly in the case of signature-caused skipping, we have to save the context variables regardless of their sizes.

**Comment by gaow** [comment]
I'd consider OrderedDict a basic type, not np.matrix or pd.dataframe, though. For these complex types of variable, can we save their MD5 instead?

**Comment by BoPeng** [comment]
That said, it is fair enough to require steps to return (`shared` or through other means) only basic types.... I would say let us keep this ticket open, stick to the current implementation, and add restrictions if it proves to be inefficient.

**Comment by gaow** [comment]
I believe initially my motivation was to keep signature files small enough. I'm closing this ticket for now since current implementation serves us well for almost 3 years now.
