### ISSUE TITLE
Different username between local / remote servers

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#429]
I have not tried this but on the tutorial "Remote_Execution" I cannot find instruction on scenario when local and remote machines have different user names. I do not have a way to test it out (yet) as all my account names are identical, but I believe there will often be exceptions. Can this be dealt with?

**Comment by BoPeng** [comment]
Setting host address to `username@host` should work.

**Comment by gaow** [comment]
Right ... will add a line in the  tutorial
