### ISSUE TITLE
A global option like `%use_remote`

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#430]
I'm not sure if this request makes sense but in my case I can either run a script locally or remotely as the two computers I have are identical. One can of course comment out the specs in `task` when local execution is desired, but it can be a pain if there are many of them. Would a global switch help? Or some other switches that can finer control if remote execution is to be activated for given tasks. We can discuss if this request is reasonable then the interface.

**Comment by gaow** [comment]
A related one is that if I purposely or accidentally make `host` identical to the current machine then hopefully this can be automatically figured out and we avoid copying a file to itself. But this may already have been implemented in `rsync` by default? The question is relevant to this ticket because I might execute a script from either of  the 2 identical machines.

**Comment by BoPeng** [comment]
For the first question, you can do

```
parameter: host=None

[10]:
task:  on_host=host
```

Then by default everything is wrong locally and you can use `sos run script --host remote` to run it remotely.

**Comment by BoPeng** [comment]
Question 2 related to #420, namely what would happen if specified host is actually localhost. I believe the most straightforward way is to try not be clever. `rsync` will be run but hopefully it will exit directly. The added benefit of being dumb is that we can use this feature to test the remote feature (e.g. `on_host='localhost', path_map='locationA:locationB'`).
