### ISSUE TITLE
Use `host` with configuration file error

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#431]
Not sure if it is relevant to using a configuration file but I run into this as I try to run part of a pipeline remotely:

```
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/remote.py", line 57, in _get_path_map
    if self.alias in env.sos_dict['CONFIG']['hosts'] and \
KeyError: 'hosts'
```

**Comment by BoPeng** [comment]
Thanks. Forgot to check if `hosts` is defined in `CONFIG` in this case.
