### ISSUE TITLE
Interface for job submission on clusters

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#437]
With the completion of #414 (remote execution of tasks), and planned wait feature ( #436) of the sos core, we will need to find a good way to submit jobs on clusters.

I would propose that we make use of the `CONFIG['hosts'][host]` feature to define behavior for each cluster. Something like:

```
hosts:
   cluster:
        address:    address of head node
        path_map:  how to map files
        shared:        shared filesystem, not likely to have one
        send_cmd:  how to send files to cluster, default value should work
        receive_cmd: how to receive files from cluster, default value should work
        execution_cmd:  THIS WOULD NEED SOME THOUGHT
        wait:                False
        status_cmd:      Status checking command
```

Basically, 

1. option `wait` tells SoS that the job would be in waiting status after `sos execute task` returns, which triggers command `sos execute task --no-wait`.
2. option `execution_cmd`. Instead of `ssh head_node sos execute task`, it would be something like `ssh head_node qsub sos execute task`
3. option `status_cmd` would be a command to check status, something like `ssh head_node sos execute task --check-status`

There are two missing pieces here:

1. SoS does not know how to pass resource options to PBS. Something like

  ```
  job_template:  "#PBS -wall ${_runtime["wall"]}
  ```

  might do.

2. SoS does not know how to check the status of the job. Supposedly the `qsub` command would return some ID number but there is no general way to perform `--check-status`.

This all looks troublesome, but at the end of the day (month, year?), we should be able to do

```
[10]
task: on_host='cluster', to_host, from_host

```

and submit tasks to the cluster in Jupyter notebook, or from command line using

```
sos run script --no-wait
```

to submit all the jobs without waiting for their completion, or

```
sos run script --no-wait
```

again to check the status (sos would try to submit jobs but found that they are still running), and perform latter steps if some jobs are completed, and

```
sos run script
```

to wait for the completion of jobs and continue the workflow after the jobs are completed. Interruption of this command should not affect the execution of remote jobs.

**Comment by gaow** [comment]
I'm a bit confused here: do we want to use `sos run` or `sos execute` eventually? How do we move from `run` to `execute`?

**Comment by gaow** [comment]
For snakemake, it uses a dedicated configuration file that controls each job:

```
{
    "__default__":
    {
        "-q":"short.q",
        "-pe":"smp 1",
        "-l":"membycore=4G"
    },
    "job1":
    {
        "-q":"short.q",
        "-pe":"smp 8",
        "-l":"membycore=4G"
    },
    "job2":
    {
        "-q":"short.q",
        "-pe":"smp 8",
        "-l":"membycore=4G"
    }
}
```
Because it is make style, I believe there is no `--no-wait`. It would submit queue based on dependencies. Snakemake was appealing to many people I know for the cluster feature. I think we are the exceptions that each of us have two very powerful machines for daily work. But most people around me use a laptop to work from home / coffee shop / library and does all the work on cluster; this is partially why I had hard time convincing them to try out SoS as is.

**Comment by gaow** [comment]
It may also be helpful to look again at snakemake cluster submission interface:

https://snakemake.readthedocs.io/en/stable/tutorial/additional_features.html#cluster-execution

This doc mentions `qsub -sync yes` -- I did not know it exists until I read it.

**Comment by BoPeng** [comment]
I read it. The biggest problem is that our cluster does not allow standing jobs, so the snakemake model does not work. This might not be a problem if all jobs would be submitted, but for sos, many jobs are outside of tasks and have to be executed on the head node.

**Comment by gaow** [comment]
> This might not be a problem if all jobs would be submitted, but for sos, many jobs are outside of tasks and have to be executed on the head node.

What would the SoS model look like, then -- have the jobs outside tasks be executed on a local computer, and the actual tasks go directly to computational nodes?

**Comment by BoPeng** [comment]
Yes. SoS recognizes that workflows typically have a large amount of "connection" code or "light analysis" that do not need to be executed as tasks, so it makes clear that **only tasks are external** and everything else should be executed by SoS. Other workflow systems seem to treat everything as tasks and provide very limit amount of glue code (correct me if I am wrong here), and I frankly do not know how snakemake handles small jobs --- clusters are not designed for them.

The consequence is that we typically run workflows locally, even interactively in Jupyter, and the workflow would submit large jobs to remote hosts and queues. The workflow could wait or exit after the jobs are submitted. (#448). We could run a sos workflow on the head node if the workflow has all tasks, but generally speaking sos workflows are not suitable for headnode execution.

**Comment by gaow** [comment]
Right, the idea that remote host (whether it be another desktop server or a cluster) only handles external tasks is a powerful idea that stands out compared to snakemake. We have already the remote host feature for a desktop server (which you implemented over a weekend half a month ago!). Interface-wise I like snakemake's configuration structure that you can customize each specific job. That gives more flexibility without making the main script any longer.

**Comment by BoPeng** [comment]
Could you elaborate how snakemake configure each job? To me these are task options.

**Comment by gaow** [comment]
Exactly these are just task options. I am saying we should also allow for task specific configuration. I admit and agree snakemake model of sending everything to cluster is not smart and we should do better. It is being a while since I use snakemake cluster but I believe their job completion is indicated by leaving behind a signature. Later jobs keep an eye on this signature and submit accordingly.

**Comment by BoPeng** [comment]
We have `walltime` etc but have not used them yet for anything... Ideally the `hosts` configuration should take care of all global cluster-specific configurations, and `task` options should take care of task-specific options, and `CONFIG` could be used to provide some flexibility.

**Comment by BoPeng** [comment]
Let us keep looking but it appears that command-line pulling is still the only way to go.

I suppose we can have for each cluster (configuration) an agent that

1. Starts as a sub process of sos but would stay alive after sos exits (if there are pending jobs).
2. Manages a set of tasks under ~/.sos/tasks/server_alias
3. Manages job submission (creation of proper shell script that wraps around sos execute task) to limit the number of running (and/or submitted) jobs.
4. Manages periodical query of job status at defined (and configurable) interval (e.g. Every minute)
5. Kills remote jobs if needed

So in the configuration file we can have for each cluster

1. `path_map` etc that defines how to transfer files and execute commands (`_host_agent`)
2. `max_jobs`: max number of jobs, which is unrelated to command line option `-j`.
3. `submit_cmd`: command to submit a job
4. `query_cmd`: command to query status of a job
5. `kill_cmd`: command to kill a job. Note that we could also use the pulse thread to kill job.
6/ `query_interval`: frequency of querying job status.

**Comment by BoPeng** [comment]
This has been implemented.
