### ISSUE TITLE
Hide toc2 when side panel shows

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#440]
Currently toc2 and side panel does not work well with each other. This is very unfortunate because the side panel copies code from toc2 are compete each other for screen place. I would suggest that we hide toc2 when side panel is displayed.

Not urgent but should be done sooner or later because both are important for the workplace.

**Comment by BoPeng** [comment]
In the same sprint, scratchpad would actually break sos because it steals our keyboard shortcuts. It would be necessary for us to disable scratchpad when we start. We might not be able to do this if scratchpad starts after sos though.

**Comment by BoPeng** [comment]
```diff
diff --git a/sos/jupyter/kernel.js b/sos/jupyter/kernel.js
index 2c7461e..10c0f30 100644
--- a/sos/jupyter/kernel.js
+++ b/sos/jupyter/kernel.js
@@ -428,7 +428,9 @@ define([
             .append(
                 $("<div/>").attr("id", "panel").addClass('panel')
             )
-
+               // the nbextension scratchpad would compete with side panel for shortcuts
+               if ($('#nbextension-scratchpad')[0] !== undefined)
+                       $('#nbextension-scratchpad').remove()
         $("body").append(panel_wrapper);

         $([Jupyter.events]).on("resize-header.Page", function() {
```

does not work. It seems that scratchpad could be loaded later than sos side panel.

Perhaps we can insert a warning message somewhere when scratch pad is detected?

**Comment by BoPeng** [comment]
toc2 sometimes remains... not sure why. Note that scratchpad would totally mess up the panel (because it hijacks shortcuts) but toc2 is tolerable although it can be confusing. I suppose the best method would be letting sos panel work with toc2 panel if toc2 exists (I understand this can be very tricky).

**Comment by BoPeng** [comment]
See the patch, still does not work well. Let me try to define the behavior:

1. When sos panel expands:
    * hide toc2 <- avoid both open (problem 4.1)
    * expand sos, adjust notebook
2. When sos panel closes
    * hide toc2 <- so that notebook widens, avoid notebook going under toc2.
    * hide sos 
3. When toc2 expands
    * If sos is open, it covers sos, notebook unchanged <- but problem will arise if toc2 closes
   * if sos is closed, notebook change width
4. When toc2 closes
   * If sos is open... notebook goes behind sos  <- need fix. So basically we cannot let toc2 and sos open at the same time (case 3.1).
   * If sos is closed ... notebook widens

So in the end the behavior, expand and close toc2 will be troublesome when sos is open. I do not see a proper solution here.

**Comment by jma7** [comment]
If toc2 open, click on cube button, hide toc2, open sos panel.
if toc2 open, click on toc2 button, hide toc2.
if sos panel open, click on toc2 button, hide sos panel, open toc2.
if sos panel open, click on cube button, hide sos panel. 

So there is no situation as one cover another which causes confusing.

**Comment by BoPeng** [comment]
I was referring to the case when sos panel is open, and you click toc2 twice, the notebook would go behind sos panel. This is unavoidable unless you can hijack the toc2 button behavior to close sos panel when toc2 button is clicked.

**Comment by BoPeng** [comment]
Basically I do not see 

"if sos panel open, click on toc2 button, hide sos panel, open toc2."

in this case, sos panel is covering toc2 during my test.

**Comment by jma7** [comment]
Are you referring to the older commit? Right now, on my desktop, if sos panel open, you click toc2 button twice, the first click will hide sos panel and show the toc2 panel, the second click will hide the toc2 panel and widen the notebook.

**Comment by BoPeng** [comment]
This is for the new commit, but I will try using a different browser to avoid cache problem.

**Comment by BoPeng** [comment]
This works now. I suspect it is again some sort of browser cache problem.

**Comment by gaow** [comment]
wow at the long last!!

BTW nice new github avatar -- thumb up to the artist :)

**Comment by BoPeng** [comment]
I liked the avatar as well, though I have to ask her if that is a turtle or dragon.
