### ISSUE TITLE
Unify rq/celery, remote execution, and PBS feature, and separation of file system features.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#441]
In light of the fact that we should also have `path_map`, `to_host` and `from_host` options if the rq/celery workers and server (redis) are not on the same file system (#438), we should consider unifying all these execution options and treat them as some variants of `hosts`.

Logically speaking:

1. Options `to_host`, `from_host` and `preserved_vars` prepare the step for the execution on hosts with different file systems. They are not triggered if the step is executed locally. These are remote-execution options that are independent of how tasks would be executed on the remote host.

2. Options `walltime` etc (#240) prepare the step for the execution in task queues where estimated resources would be needed. Each variant of the task queue (e.g. PBS, rq) should figure out a way to make use of these runtime options. Again, these are task descriptions and are independent of who will execute the task.

3. The `--queue` option should be an abstraction of job queues when sos submit the tasks. In the `queue` definition, sos needs to know if the workers are on a different file system (configuration `shared`), and how to copy files if that is the case (`path_map` etc). SoS also needs to know how to interact with the queue system (e.g. how to pass runtime option `walltime`). Another key aspect of the `host` is whether or not it is a queue system. SoS would return and check for the status of the job later for a queue system (PBS, rq, and celery), and wait for the completion of the job if it is not (remote execution).

4. Whereas the `queue` option is an global option to send all tasks to certain queues, the `on_host` runtime option should be treated as a per-task specification that provides us an opportunity to send tasks to different queues/servers. It is at least useful for interactive use when we send individual tasks to different servers.

The key question would then how to generalize a good definition of `queue` so that we can work with all these different execution methods. 

1. Remote execution without queue: This is already done and the current `execute_cmd` option seems to be working all right. SoS waits for the completion of the job in this case.

2. `rq`: The rq definition should have `redis` server, `port`, etc. The SoS rq extension would know how to send the job to rq server.

3. `celery`: similar to rq. The configuration file should have definitions for `celery` server. The SoS celery extension would know how to send the job to celery server.

4. `PBS`: ... this is topic of #437.

My understanding now is that we should abstract the `queue` or `host` execution in the SoS core, and implement different types of hosts as SoS extensions.

**Comment by gaow** [comment]
So I'm trying to comprehend the logic here: for each specific host type we list all the actions it involves, then the intersect of these actions will be what we'll abstracted to the `core` executions? For actions unique to each type do we want to create a general interface that easily fits them all, or we provide fixed specific interface as "templates" for host specific options?

**Comment by BoPeng** [comment]
The basic idea is that `--queue queue` or `on_host='host'` would point to a configuration of `queue` or `host` that defines some common behaviors. Our job is to define these behaviors and implement them for particular types of `host`. The core would just grasp the `type` information and interact to them with a common interface. Something like:

```
remote-host:
    type: remote-server
   wait: True
   path-map:
   ...
```

```
rq1:
    type: redis-queue
    host:  redist-server-ip
    port: redist-server-port
    path-map:  if worker in the different file system
```

Then, we have classes defined for each type and registered as `entry points`. In the core, we

1. get the configuration of host.
2. get the type of host.
3. retrieve from entry point the class of host
4. create an object of that type of host and pass it the configuration
5. use this object to submit job and wait for result.

In this way, the system is very flexible in the defining of new queuing systems and for users

1. They can define a number of 'hosts' of different types, which can be local host, remote host, redis, or cluster.
2. As long as they define the steps correctly with all the runtime informations, they can smoothly switch between these servers/services with only a change of `--queue` (globally) or `on_host` (each step).

**Comment by BoPeng** [comment]
This has been implemented.
