### ISSUE TITLE
Auxiliary step problem 

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#444]
I hope it is just my undoing but I cannot seem to make this example the backward `make` style:

```
[test_1: provides = ['{}.txt'.format(x) for x in range(20)]]
n = [1]
s = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
tm = [0, 1]
input:  for_each = ['n', 's', 'tm']
output: ['{}.txt'.format(x) for x in range(20)]
task: workdir = './', concurrent = True
run:
  touch ${_output}

[test_2]
input: dynamic(['{}.txt'.format(x) for x in range(20)]), group_by = 1, pattern = "{name}.{ext}"
output: expand_pattern("{_name}.out") 
task: workdir = './', concurrent = True
run:
  touch ${_output}
```

Running the script I get lock conflicts. It seems the processes are trying to secure lock for all 20 output together, thus the conflict. I wonder what is the correct behavior or syntax in this case. Thanks!

**Comment by BoPeng** [comment]
I think the problem here is not with auxiliary step, but again with the same output for different input loop.

**Comment by gaow** [comment]
I agree ... an alternative syntax solves the problem for this MWE:
```
output_file = ['{}.txt'.format(x) for x in range(20)]
output: output_file[_index]
```
But I remember my case involved something more complicated and this trick did not fix it. I should have confirmed and posted a better example. Will find it over the weekend and I'll close the ticket if it turns out to be a false alarm from my memory.

**Comment by BoPeng** [comment]
I am wondering if we should declare an error if multiple input loops sharing the same `_output`. You see, even if we can somehow correct this problem for local multiprocessing (e.g. using single process in this case), users will suffer from performance loss, and there can be problems when we submit jobs to remote hosts etc, and troubleshooting can become really complicated then. 

More generally speaking, we should perhaps keep track of output files of all steps and raise an error if any step (or step loop) tries to step on others' toe. We can cook up some examples, say, another step modifying result of a previous step, but such practice should be banned because this will totally mess up sos signature.

**Comment by gaow** [comment]
The example I gave before was processes stepping each other within loops of the same step.  I believe my problematic version of example is more similar to this below, where there is inter-step conflicts:

```
[test_1: provides = ['{}.txt'.format(x) for x in range(20)]]
n = [1]
s = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
tm = [0, 1]
input:  for_each = ['n', 's', 'tm']
output_file = ['{}.txt'.format(x) for x in range(20)]
output: output_file[_index]task: workdir = './', concurrent = True
run:
  touch ${_output}

[test_2]
input: dynamic(['{}.txt'.format(x) for x in range(20)]), group_by = 1, pattern = "{name}.{ext}"
output: expand_pattern("{_name}.out") 
task: workdir = './', concurrent = True
run:
  touch ${_output}


[another_test_1]
input: dynamic(['{}.txt'.format(x) for x in range(20)]), group_by = 1, pattern = "{name}.{ext}"
output: expand_pattern("{_name}.out2") 
task: workdir = './', concurrent = True
run:
  touch ${_output}

[default_1]
input: None
sos_run('test')

[default_2]
input: None
sos_run('test:1+another_test:1')
```

Running `default` I'd expect SoS's DAG figures out that part of `default_1` and `default_2` steps on each other, but it is totally acceptable so `test:1` will be executed first, alone, followed by `test:2` and `another_test:1`, in parallel, because those steps have different output. I wonder if SoS could figure it out and make arrangements with DAG. A more extreme example would be calling the same thing twice:

```
[default_1]
input: None
sos_run('test')

[default_2]
input: None
sos_run('test')
```

Then I'd expect this is legitimate because SoS will figure out and handle.

**Comment by BoPeng** [comment]
```
$ sos run test
INFO: Executing default_2:
INFO: default_2 input:    []
INFO: Executing default_1:
INFO: default_1 input:    []
INFO: Executing workflow test:1+another_test:1 with input []
INFO: Executing workflow test with input []
INFO: Executing test_1:
INFO: test_1 input:    []
INFO: Executing test_1:
INFO: test_1 input:    []
INFO: Executing task test_1_0_4ce72e8b3a097c19c4c7c6c8e8aecddd
INFO: Executing task test_1_1_4ce72e8b3a097c19c4c7c6c8e8aecddd
INFO: Executing task test_1_2_4ce72e8b3a097c19c4c7c6c8e8aecddd
INFO: Executing task test_1_3_4ce72e8b3a097c19c4c7c6c8e8aecddd
INFO: Executing task test_1_4_4ce72e8b3a097c19c4c7c6c8e8aecddd
INFO: Executing task test_1_5_4ce72e8b3a097c19c4c7c6c8e8aecddd
INFO: Executing task test_1_6_4ce72e8b3a097c19c4c7c6c8e8aecddd
INFO: Executing task test_1_7_4ce72e8b3a097c19c4c7c6c8e8aecddd
INFO: Waiting on another process for step test_1
INFO: Executing task test_1_8_4ce72e8b3a097c19c4c7c6c8e8aecddd
INFO: Executing task test_1_9_4ce72e8b3a097c19c4c7c6c8e8aecddd
INFO: Executing task test_1_10_4ce72e8b3a097c19c4c7c6c8e8aecddd
INFO: Executing task test_1_11_4ce72e8b3a097c19c4c7c6c8e8aecddd
INFO: Executing task test_1_12_4ce72e8b3a097c19c4c7c6c8e8aecddd
INFO: Executing task test_1_13_4ce72e8b3a097c19c4c7c6c8e8aecddd
INFO: Executing task test_1_14_4ce72e8b3a097c19c4c7c6c8e8aecddd
INFO: Executing task test_1_15_4ce72e8b3a097c19c4c7c6c8e8aecddd
INFO: Executing task test_1_16_4ce72e8b3a097c19c4c7c6c8e8aecddd
INFO: Executing task test_1_17_4ce72e8b3a097c19c4c7c6c8e8aecddd
INFO: Executing task test_1_18_4ce72e8b3a097c19c4c7c6c8e8aecddd
INFO: Executing task test_1_19_4ce72e8b3a097c19c4c7c6c8e8aecddd
INFO: test_1 output:   ['0.txt', ...] (20 items)
INFO: Executing another_test_1:
INFO: another_test_1 input:    ['0.txt', ...] (20 items)
INFO: Executing test_1:
INFO: test_1 input:    []
INFO: Executing task another_test_1_0_c91a9c1877f4e39aa92052a3fc3aad6e
INFO: Executing task another_test_1_1_c91a9c1877f4e39aa92052a3fc3aad6e
INFO: Step test_1 (index=0) is ignored due to saved signature
INFO: Executing task another_test_1_2_c91a9c1877f4e39aa92052a3fc3aad6e
INFO: Executing task another_test_1_3_c91a9c1877f4e39aa92052a3fc3aad6e
INFO: Step test_1 (index=1) is ignored due to saved signature
INFO: Step test_1 (index=2) is ignored due to saved signature
INFO: Step test_1 (index=3) is ignored due to saved signature
INFO: Step test_1 (index=4) is ignored due to saved signature
INFO: Step test_1 (index=5) is ignored due to saved signature
INFO: Step test_1 (index=6) is ignored due to saved signature
INFO: Step test_1 (index=7) is ignored due to saved signature
INFO: Step test_1 (index=8) is ignored due to saved signature
INFO: Executing task another_test_1_4_c91a9c1877f4e39aa92052a3fc3aad6e
INFO: Executing task another_test_1_5_c91a9c1877f4e39aa92052a3fc3aad6e
INFO: Step test_1 (index=9) is ignored due to saved signature
INFO: Executing task another_test_1_6_c91a9c1877f4e39aa92052a3fc3aad6e
INFO: Executing task another_test_1_7_c91a9c1877f4e39aa92052a3fc3aad6e
INFO: Step test_1 (index=10) is ignored due to saved signature
INFO: Step test_1 (index=11) is ignored due to saved signature
INFO: Step test_1 (index=12) is ignored due to saved signature
INFO: Step test_1 (index=13) is ignored due to saved signature
INFO: Step test_1 (index=14) is ignored due to saved signature
INFO: Step test_1 (index=15) is ignored due to saved signature
INFO: Step test_1 (index=16) is ignored due to saved signature
INFO: Step test_1 (index=17) is ignored due to saved signature
INFO: Step test_1 (index=18) is ignored due to saved signature
INFO: Step test_1 (index=19) is ignored due to saved signature
INFO: Executing task another_test_1_8_c91a9c1877f4e39aa92052a3fc3aad6e
INFO: test_1 output:   ['0.txt', ...] (20 items)
INFO: Executing task another_test_1_9_c91a9c1877f4e39aa92052a3fc3aad6e
INFO: Executing task another_test_1_10_c91a9c1877f4e39aa92052a3fc3aad6e
INFO: Executing task another_test_1_11_c91a9c1877f4e39aa92052a3fc3aad6e
INFO: Executing task another_test_1_12_c91a9c1877f4e39aa92052a3fc3aad6e
INFO: Executing task another_test_1_13_c91a9c1877f4e39aa92052a3fc3aad6e
INFO: Executing task another_test_1_14_c91a9c1877f4e39aa92052a3fc3aad6e
INFO: Executing task another_test_1_15_c91a9c1877f4e39aa92052a3fc3aad6e
INFO: Executing task another_test_1_16_c91a9c1877f4e39aa92052a3fc3aad6e
INFO: Executing task another_test_1_17_c91a9c1877f4e39aa92052a3fc3aad6e
INFO: Executing task another_test_1_18_c91a9c1877f4e39aa92052a3fc3aad6e
INFO: Executing task another_test_1_19_c91a9c1877f4e39aa92052a3fc3aad6e
INFO: Executing test_2:
INFO: test_2 input:    ['0.txt', ...] (20 items)
INFO: Executing task test_2_0_a2cb1a457f3c1716d30f01b25ef24e53
INFO: Executing task test_2_1_a2cb1a457f3c1716d30f01b25ef24e53
INFO: Executing task test_2_2_a2cb1a457f3c1716d30f01b25ef24e53
INFO: Executing task test_2_3_a2cb1a457f3c1716d30f01b25ef24e53
INFO: Executing task test_2_4_a2cb1a457f3c1716d30f01b25ef24e53
INFO: Executing task test_2_5_a2cb1a457f3c1716d30f01b25ef24e53
INFO: Executing task test_2_6_a2cb1a457f3c1716d30f01b25ef24e53
INFO: Executing task test_2_7_a2cb1a457f3c1716d30f01b25ef24e53
INFO: Executing task test_2_8_a2cb1a457f3c1716d30f01b25ef24e53
INFO: Executing task test_2_9_a2cb1a457f3c1716d30f01b25ef24e53
INFO: Executing task test_2_10_a2cb1a457f3c1716d30f01b25ef24e53
INFO: Executing task test_2_11_a2cb1a457f3c1716d30f01b25ef24e53
INFO: another_test_1 output:   ['0.out2', ...] (20 items)
INFO: Executing task test_2_12_a2cb1a457f3c1716d30f01b25ef24e53
INFO: Executing task test_2_13_a2cb1a457f3c1716d30f01b25ef24e53
INFO: Executing task test_2_14_a2cb1a457f3c1716d30f01b25ef24e53
INFO: Executing task test_2_15_a2cb1a457f3c1716d30f01b25ef24e53
INFO: Executing task test_2_16_a2cb1a457f3c1716d30f01b25ef24e53
INFO: Executing task test_2_17_a2cb1a457f3c1716d30f01b25ef24e53
INFO: Executing task test_2_18_a2cb1a457f3c1716d30f01b25ef24e53
INFO: Executing task test_2_19_a2cb1a457f3c1716d30f01b25ef24e53
INFO: Workflow test:1+another_test:1 (ID=25d78d7f75ffffea) is executed successfully.
INFO: default_2 output:   []
INFO: test_2 output:   ['0.out', ...] (20 items)
INFO: Workflow test (ID=227a4e7aedab363c) is executed successfully.
INFO: default_1 output:   []
INFO: Workflow default (ID=853e8f82cf7d2817) is executed successfully.
```

**Comment by gaow** [comment]
Hmm I'll have to confirm this in some none trivial example that takes longer to generate an output, because I do recall I have had such issue even with `output_file[_index]`. I was asking if **by design** this correct behavior is expected. It would be great if it does!

**Comment by BoPeng** [comment]
Your script is strange because `test_1` is executed not because it is needed, but because it is the first step in the workflow. We should perhaps disallow such use.

**Comment by gaow** [comment]
Sorry I did not get this comment: `test_1` is indeed needed, but you are saying that you can tell from the log that it is executed anyways because it is the first step? So what I should in fact put in `sos_run` are just `test:2` and `another_test:1` and they will figure out that `test:1` is needed automatically -- this would be the Makefile logic / style. I'm now mixing it up but SoS was no smart enough to tell this, right?

**Comment by BoPeng** [comment]
I was saying that step was run not because of provide keyword so you can try to rename it to make it called through the make file mechanism.

**Comment by gaow** [comment]
Without `sos_step()` as target #403  I'm trying out make style for the job, but I'm running into issues, also related to race condition. One can immediately tell where it goes wrong by looking into the dag file it generated:

```
[test_1: provides=['{}.txt'.format(i) for i in range(10)]]
output: ['{}.txt'.format(i) for i in range(10)]
run:
  touch ${output}

[test_2: provides=['{}.txt'.format(i) for i in range(10, 20)]]
depends: ['{}.txt'.format(i) for i in range(10)]
output: ['{}.txt'.format(i) for i in range(10, 20)]
run:
  touch ${output}

[default]
depends: ['{}.txt'.format(i) for i in range(10, 20)]
```

Is there anything obviously wrong with this script? I just did not expect this behavior when there are multiple target files.

**Comment by BoPeng** [comment]
This is a bug. The addition of step should happen only once. It has been fixed.

**Comment by gaow** [comment]
I'm not sure if the bug fix has introduced a new one or it is some syntax error, but this example hangs without generating a dag:

```
parameter: fileset1 = ['{}.txt'.format(i) for i in range(5)]
parameter: fileset2 = ['{}.txt'.format(i) for i in range(5,10)]
parameter: fileset3 = ['{}.txt'.format(i) for i in range(10,15)]

[test_1: provides=fileset1]
output: fileset1
run:
  touch ${output}

[test_2: provides=fileset2]
depends: fileset2 
output: fileset3
run:
  touch ${output}


[test_3: provides=fileset3]
depends: fileset1, fileset2 
output: fileset3
run:
  touch ${output}



[default]
depends: fileset3 
```

**Comment by gaow** [comment]
Sorry it turns out to be a typo on my 2nd step ... but it would be a good wrong test case.

**Comment by gaow** [comment]
Finally I've detected another problematic case. The dag generated is messy. But I suspect it is by design to fail because each `sos_run` is a standalone dag? If so, how can I achieve below script without essentially having to define this `main` function everywhere?

```
parameter: fileset1 = ['{}.txt'.format(i) for i in range(5)]
parameter: fileset2 = ['{}.txt'.format(i) for i in range(5,10)]
parameter: fileset3 = ['{}.txt'.format(i) for i in range(10,15)]

[main]
parameter: output_files = []
output: output_files
run:
  touch ${output}

[test_1: provides=fileset1]
parameter: output_files = fileset1
sos_run('main')

[test_2: provides=fileset2]
depends: fileset1
parameter: output_files = fileset1
sos_run('main')

[test_3: provides=fileset3]
depends: fileset1, fileset2 
parameter: output_files = fileset3
sos_run('main')

[default]
depends: fileset3 
```

**Comment by BoPeng** [comment]
I need to explain the technical difficulty here.

```
[provides='{}.txt']
```

automatically generates

```
[provides='{}.txt']
output: 'a.txt'
```

if the step is matched to `a.txt`. 

```
[provides=['a.txt', 'b.txt', 'c.txt']]
```
is currently also turns to 

```
[provides=['a.txt', 'b.txt', 'c.txt']]
output: 'a.txt'
```
when the step is matched to `a.txt`.

It is not perfectly clear if 

```
[provides=['a.txt', 'b.txt', 'c.txt']]
```

would generate one of `a.txt`, or all of `a.txt`, `b.txt` and `c.txt`...

**Comment by gaow** [comment]
I see. So this issue is challenging the bases on which the Auxiliary step mechanism is built ...

**Comment by BoPeng** [comment]
We only need to define rigorously what would happen. That is to say,

```
[provides=[name1, name2,name3]]
```
could be expanded to

* case 1:
    ```
    [provides=[name1, name2,name3]]
    output=[expand_pattern(name1), expand_pattern(name2), expand_pattern(name3)]
    ```

* case 2:
    ```
    [provides=[name1, name2,name3]]
    output=expand_pattern(matched_name)
    ```

The problem here is that whereas it is easy for user to specify `output` in case 1 (if we do not choose case 1), it is difficult for user to specify `output1 in case 2 because it is not clear which pattern would be matched.

We can enforce the rule that only one name can be matched, and do something like:

* case 3:
    ```
    [provides=[(name1, name2,name3)]]
    output=[expand_pattern(name1, name2, name3)]
    ```

so when `name2` is matched, the whole group is matched....

**Comment by BoPeng** [comment]
How does make/snakemake handle this?

**Comment by BoPeng** [comment]
Also, your script has two problems (that might or might be relevant to this bug):

```
[test_2: provides=fileset2]
depends: fileset1
parameter: output_files = fileset1
sos_run('main')
```

You are using a regular step as auxiliary step, but this step would not run if it is executed as a regular step (no `output`). Also, as an adjustment to how `parameter` is handled in nested workflow, parameters have to be explicitly passed to `sos_run`, for example as `sos_run('main', output_files=output_files)`.

**Comment by gaow** [comment]
Thanks for the pointers! I've fixed the `sos_run` call. Still the output are in race conditions. 

> You are using a regular step as auxiliary step

By "using a regular step" you mean the use of step name `test_2`? It would become a pure auxiliary step if I remove `_2`?

I was looking into snakemake but I have not figured out the chunk of codes that is dealing with this ...

**Comment by BoPeng** [comment]
Can you creat a snake make examole?

**Comment by gaow** [comment]
Yes let me give it a go.

**Comment by gaow** [comment]
Sorry was a bit rusty on snakemake -- here it is:

```
fileset1 = ['{}.txt'.format(i) for i in range(5)]
fileset2 = ['{}.txt'.format(i) for i in range(5,10)]
fileset3 = ['{}.txt'.format(i) for i in range(10,15)]

rule default:
  input: fileset3

rule test_1:
  output: fileset1
  shell: "touch {output}"

rule test_2:
  input: fileset1
  output: fileset2
  shell: "touch {output}"

rule test_3:
  input: fileset1, fileset2
  output: fileset3
  shell: "touch {output}"
```

Save it to `Snakefile` and type `snakemake` to run.

**Comment by BoPeng** [comment]
I do not see how snakemake handles partial match. Say you ask only one of the files.

**Comment by gaow** [comment]
```
fileset1 = ['{}.txt'.format(i) for i in range(5)]
fileset2 = ['{}.txt'.format(i) for i in range(5,10)]
fileset3 = ['{}.txt'.format(i) for i in range(10,15)]

rule default:
  input: expand("{file_id}.txt", file_id = [10,11])

rule test_1:
  output: fileset1
  shell: "touch {output}"

rule test_2:
  input: fileset1
  output: fileset2
  shell: "touch {output}"

rule test_3:
  input: fileset1, fileset2
  output: fileset3
  shell: "touch {output}"
```

It does generate all output files.

**Comment by BoPeng** [comment]
Then is there a way to generate partial output? I mean from partial match? Perhaps pattern or multiple rules would be needed?

**Comment by gaow** [comment]
Do you mean something like this in snakemake? I'm trying to compose it but it does not work for now:

```
n1 = [1,2]
n2 = [3,4]
n3 = [5,6]

rule default:
  input: expand("{a}.{b}.{c}.txt", a = 1, b = 3, c = 5)

rule test_1:
  output: "{n1}.txt" 
  shell: "touch {output}"

rule test_2:
  input: "{n1}.txt"
  output: "{n1}.{n2}.txt"
  shell: "touch {output}"

rule test_3:
  input: "{n1}.txt", "{n1}.{n2}.txt"
  output: "{n1}.{n2}.{n3}.txt"
  shell: "touch {output}"
```

**Comment by BoPeng** [comment]
Basically I am trying to see if a step can be triggered by several rules, and produce output in response to how it is triggered. Say a step can generate 10 files and generate 1 file if that is the one that triggers the step.

**Comment by BoPeng** [comment]
What we are seeing now is all 10 files are generated. Not saying one way is better than the other, but want to kNow how to do both in snakemake

**Comment by gaow** [comment]
This is what I'm trying to do here. By using 

```
  input: expand("{a}.{b}.{c}.txt", a = 1, b = 3, c = 5)
```

I hope to only trigger half of the files be generated. However that snakefile does not run ... I fail to see an obvious syntax or logic error on my end.

**Comment by BoPeng** [comment]
At least on sos side one can always override with an output statement.

**Comment by BoPeng** [comment]
Your script runs with the `sos_run('main', output_files = output_files )` change.

**Comment by gaow** [comment]
Was it because of the latest patch? I have fixed sos_run calls earlier today to no vail, but now it indeed works. The output dag looks good (with a single file). I'm reading the patch now ...

**Comment by BoPeng** [comment]
Yes, the patch tries to insert `output` statement according to `provides`. It is not complete in the sense that we have not had rigorous rules on how to handle all cases ... I will define one (and document it) if generating all targets is the preferred behavior.

Another problem is that `analyze_step` is static (cannot not evaluate expressions without correct environment) so it can fail in complex cases (e.g. user-specified `output`).  So instead of trying to return all targets during analysis, it makes sense to return only matched output, and expand the DAG if more copies of the output is needed. Such gradual expansion (even contraction) of DAG is probably more reliable but natural but would be slower in some cases (because of smaller DAG).

**Comment by BoPeng** [comment]
What I meant was instead of :

`target A B C is required` ==> `step A` is triggered to produce `A`, `B`, `C`

or 

`target A B C is required` ==> `step A` is triggered to produce `A`, `step A` is triggered to produce `B`, `step A` is triggered to produce `C`
 
because either could be correct, we do

`target A B C is required` ==> `step A` is triggered to produce `A` 

Then `step A` is triggered to produce `B` if `step A` does not produce `B`.

**Comment by BoPeng** [comment]
Or in a more advanced way, 

`target A B C is required` ==> `step A` is triggered to produce `A` (or `B` or `C`) [special flag to execute only one `step A`] ==> check if `step A` is needed to produce `B` or `C` after its completion.

**Comment by gaow** [comment]
I'm not sure if the issue has been fixed. Here is one more test:

```
parameter: fileset1 = ['{}.txt'.format(i) for i in range(2)]
parameter: fileset2 = ['{}.txt'.format(i) for i in range(2,4)]
parameter: fileset3 = ['{}.txt'.format(i) for i in range(4,6)]
parameter: fileset4 = ['{}.txt'.format(i) for i in range(6,10)]
parameter: fileset5 = ['{}.txt'.format(i) for i in range(10,14)]

[main]
parameter: output_files = []
input: for_each=['output_files']
output: output_files[_index]
task: concurrent = True
run:
  touch ${_output}

[joe_a: provides=fileset1]
sos_run('main', output_files = fileset1)

[john_a: provides=fileset2]
depends: fileset1
sos_run('main', output_files = fileset2)

[john_b: provides=fileset3]
depends: fileset1
sos_run('main', output_files = fileset3)

[mark_a: provides=fileset4]
depends: fileset1, fileset2
sos_run('main', output_files = fileset2)

[mark_b: provides=fileset5]
depends: fileset1, fileset3
sos_run('main', output_files = fileset3)

[default]
depends: fileset4, fileset5
```

Note that in `main` I asked for concurrent executions via `_index` (which helped before). The error is still a race:

```
...
INFO: Executing task main_0_1_52be57a217ac7b52e23c4b8c231020b3
ERROR: Caught Failed to obtain a lock for output [4.txt]. It is likely that these files are protected by another SoS process or concurrant task that is generating the same set of files.
INFO: main_0 output:   ['2.txt', '3.txt']
...
```

If I do not use `concurrent` it works well.

**Comment by gaow** [comment]
And also when I execute it repeatedly at some run it gives me a strange message in addition to the error above:

```
ERROR: Caught Ran out of input
```

**Comment by BoPeng** [comment]
I have been thinking about this multi-target issue this morning and it appears to me that trying to be clever on what the default output be can be VERY challenging.

Could you check http://vatlab.github.io/SOS/doc/documentation/Auxiliary_Steps.html and see if the additional output statement would work well for you?

Implementation wise this will make things a lot easier and less error prone. You code under the new rule would be very inefficient without additional `output` statement but I can at least make it executed without error.

**Comment by gaow** [comment]
Thank you -- I am trying to follow it. I added output to steps where I call `sos_run`, eg:

```
[mark_b: provides=fileset5]
depends: fileset1, fileset3
output: fileset5
sos_run('main', output_files = fileset5)
```

Is this what the page is suggesting? I still get the same error with the current `master`.

**Comment by BoPeng** [comment]
Yes. That is what the documentation is suggesting. The master branch has not bee updated to switch to that behavior.

**Comment by BoPeng** [comment]
I am just trying to make sure the behavior is well-defined for all cases and makes sense to you.

**Comment by gaow** [comment]
I see. Yes it does make sense to me but my view can be biased because I know the context ... Maybe give some recommendation on the wiki about being explicit about output?

**Comment by BoPeng** [comment]
Be explicit can be as awkward as defining `output: __default_output__`.

Anyway, I have changed the behavior to the simple one. Your script should work with additional `output` statement but I will see if I can make the no-output version work as smoothly as it can be (perhaps with a warning).

**Comment by BoPeng** [comment]
Note that my main concern of `providing all` is how to handle mixed patterns. I mean, it is easy to match

```
provides=['file1', 'file2']
```

and
```
provides='{pattern}.txt'
```
but
```
provides=['{pattern}.txt', '{pattern}.csv']
```
is not well-defined, because when `file.txt` matches, there might be no `file.csv`.

**Comment by gaow** [comment]
Indeed this other case is difficult. The last script example I posted still does not work, though.

**Comment by gaow** [comment]
There is no rush to get it work -- I understand experiments are ongoing.

**Comment by BoPeng** [comment]
The problem is with workflow being executed twice:

workflow without `task`
```
$ sos remove -s; sos run test -d test
INFO: 39 runtime signatures removed
INFO: Adding step mark_b with output 11.txt
INFO: Adding step mark_a with output 8.txt
INFO: Adding step john_a with output 2.txt
INFO: Adding step joe_a with output 0.txt
INFO: Adding step john_b with output 5.txt
INFO: Executing joe_a:
INFO: Executing workflow main with input unspecified
INFO: Executing main_0:
INFO: main_0 output:   ['0.txt', '1.txt']
INFO: Workflow main (ID=d8a193fbec43ced2) is executed successfully.
INFO: joe_a output:   ['0.txt', '1.txt']
INFO: Executing john_b:
INFO: Executing john_a:
INFO: Executing workflow main with input unspecified
INFO: Executing workflow main with input unspecified
INFO: Executing main_0:
INFO: Executing main_0:
INFO: main_0 output:   ['4.txt', '5.txt']
INFO: main_0 output:   ['2.txt', '3.txt']
INFO: Workflow main (ID=0b0562923dd3259e) is executed successfully.
INFO: john_b output:   ['4.txt', '5.txt']
INFO: Workflow main (ID=4e9273071592a770) is executed successfully.
INFO: john_a output:   ['2.txt', '3.txt']
INFO: Executing mark_a:
INFO: Executing mark_b:
INFO: Executing workflow main with input unspecified
INFO: Executing workflow main with input unspecified
INFO: Executing main_0:
INFO: Executing main_0:
INFO: main_0 output:   ['6.txt', '7.txt', '8.txt', '9.txt']
INFO: Workflow main (ID=5d069c0421e9b183) is executed successfully.
INFO: main_0 output:   ['10.txt', '11.txt', '12.txt', '13.txt']
INFO: mark_a output:   ['6.txt', '7.txt', '8.txt', '9.txt']
INFO: Workflow main (ID=106b9766aa941d49) is executed successfully.
INFO: mark_b output:   ['10.txt', '11.txt', '12.txt', '13.txt']
INFO: Executing default_0:
INFO: default_0 input:    []
INFO: default_0 output:   []
INFO: Workflow default (ID=393d336b9dd2c56e) is executed successfully.
```

**Comment by BoPeng** [comment]
OK, it turns out to be a problem that I was working on, namely task signature with different output files. It should have been fixed.
