### ISSUE TITLE
Output `group_by` option

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#445]
Currently we have input options  `group_by` and `paired_with`. But now I have a workflow that generates multiple output from a single input. I wonder how this can be implemented. For example, I have a step that takes 2 input files and produce 3 output files per run:

```
[1]
input: something, group_by = 2
output: something_else, ??group_by = 3??
task: concurrent = True
R:
 produce_output(${_input[0]}, ${_input[1]}, ${_output[0]}, ${_output[1]}, ${_output[2]})
```

How can this be implemented in the current SoS framework? 

BTW I find the `reference manual` of SoS wiki very helpful but there is no `search` feature. Do you think it is good to have that? Maybe I should open a separate ticket for it.

**Comment by BoPeng** [comment]
Yes, Please submit a ticket for search. I do not know how this can be done though. Perhaps very easy.

**Comment by BoPeng** [comment]
The idea was basically derive `_output` from `_input`. If they are not that related, I suppose you have to do something like

```
output_files = ...

output: output_files[_index*3:_index*3 + 3]
```

**Comment by gaow** [comment]
I see, thanks for the tip! I'll try it out and have it documented [here](http://vatlab.github.io/SOS/doc/documentation/SoS_Step.html#Step-output-13) (shall we document it, or provide a better interface?). Will use a separate ticket for search. As for this ticket you can decide whether we provide interface to achieve deriving from input, or we just document this and close the ticket.

**Comment by BoPeng** [comment]
Our input output stuff is already complicated with all the index, underscore variables, patterns, auxiliary ... and I would refrain from adding more features.

**Comment by BoPeng** [comment]
The output `group_by` option is actually not a bad idea, but users would have to make sure that the input and output have the same number of groups.

**Comment by BoPeng** [comment]
`output` statements are currently executed for each `input` so this this can be tricky if users specify something variable in `output`. Anyway, the implementation is rather simple, just add `group_by` to [`sos_syntax`](https://github.com/vatlab/SOS/blob/master/sos/sos_syntax.py#L27), and add its support in [`process_output_args`](https://github.com/vatlab/SOS/blob/master/sos/sos_step.py#L531) by calling [`handle_group_by`](https://github.com/vatlab/SOS/blob/master/sos/sos_step.py#L314). The tricky part is that we will only use the `_index` piece for `_output` and ignore all others.
