### ISSUE TITLE
Have a `search` toolbox for the wiki website

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#446]
A general text search on all HTML pages is perhaps best. In fact github `search this repository` is somewhat helpful though messy. But I wonder why plink2 adopts another mechanism: 

https://www.cog-genomics.org/plink2

It has a `index` search that only shows indexed terms. At least we can do that. The behavior is interesting if you try to type anything in it.

**Comment by BoPeng** [comment]
@jma7 please have a look and evaluate how difficult it is to do this. I suppose the search box can be added to the TOC and searching would lead to a result page... sounds complicated but there are perhaps a bunch of existing wheels.

**Comment by jma7** [comment]
This might be useful, I tried a little bit before. 
http://www.tipue.com/

**Comment by gaow** [comment]
Some HUGO sites seem to use this one:

https://lunrjs.com/

It looks quite simple with the `Demo` it has, though I'm not in a good position to judge the details (not very familiar with javascript). 

BTW @BoPeng how up-to-date is the documentation currently for particularly the juypter front-end and the remote features? I'd like to re-learn SoS on these topics, just want to make sure I'm re-learning the latest stuff.

**Comment by BoPeng** [comment]
The document is complete and up to date but not well organized for newbies --- but you are not a newbie.

Documentation can be long and technical but we will need to reorganize tutorials. I suggest that we

1. List topics to demonstrate as tree
2. Create short tutorials that focus on one feature each time

**Comment by gaow** [comment]
Another idea is to add annotations as hyper-links to output of `sos convert *.sos *.html` such that each keyword in the converted HTML will have a hyper-link to point to relevant documentation pages. That way users can learn SoS syntax easily by compiling the examples we provide. However a search box is perhaps much easier to implement.

**Comment by BoPeng** [comment]
Right now our documentations are not separated so it is difficult to point keywords to individual sections in these pages. We could potentially have individual pages for each keyword etc with formal definition and examples but a good search engine that lists relevant information for a keyword in multiple pages seems to be easier to everyone.

**Comment by BoPeng** [comment]
Given that we are hosting static pages on github.io, I think static search, namely tipue is the way to go. Basically, we use [beaty](http://www.tipue.com/beaty/) to create indexes and use [tipue](http://www.tipue.com/search/) to search and display them. We will need to manually index our pages but it should not be too difficult with our `release` script.

We will need to decide where to put the search box though. The documentation index (toc) can have one, but it would be nice to have one on the main page as well.

**Comment by BoPeng** [comment]
If we put a search box in nav, we will need to put the whole nav bar to the top, something like https://stackoverflow.com/

**Comment by BoPeng** [comment]
The search button works, although the search result page could be improved. We should perhaps also add the button to the documentation pages (e.g. in toc panel).
