### ISSUE TITLE
Option to kill running jobs.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#449]
`sos execute task_id --kill`

The status file has the process id of the running process. For local subprocess-like jobs, we could try to kill the process and all its subprocesses. However, the jobs could be submitted to docker, or be executed (by PBS) on a remote worker, so there is no clear way how to kill them.

**Comment by BoPeng** [comment]
Interface wise, this could be something like

```
sos run workflow --kill
```

to kill all related workflow, or

```
sos kill job_id
```

to kill specific job. The problem with the latter is that the job could be executed remotely so we should have this information somewhere.

**Comment by BoPeng** [comment]
We already have a daemon monitoring thread that touches a status file during the execution of tasks. This `pulse` thread let sos know that the task is running and will terminate as soon as the main task is terminated. We should perhaps implement a mechanism to let the pulse thread kill the main job when it receives an instruction to stop the task.

The advantage of this method is that we do not need to worry about how the task is started (e.g. through PBS on a worker). We just need to touch a status file, let the pulse thread know something is wrong, and it will kill the process.

One exception I can think of is docker when the pulse thread might not be able to stop the docker instance. This is related to #460 and we might be able to achieve this by using another pulse thread.

More usefully, we might be able to "pass the pulse thread to action" while the action is executing, and return the pulse thread to the master process when an action is done....

**Comment by BoPeng** [comment]
I suppose it is pretty easy to perform suicide. Basically, the pulse thread would update `${task}.status`,  and when it notices a `${task}.stop` file (or something like that), it would use `getpid()` and `psutil.kill` to kill itself.  The only problem seems to be with docker when the task is executed by the docker daemon. Perhaps the docker daemon should also have a pulse thread.

**Comment by gaow** [comment]
It may be a very dumb question, but isn't it possible to link `ctrl-c` with killing everything?

**Comment by BoPeng** [comment]
No. The jobs are external, they can be in the background, within docker, remotely on a worker machine, so there is generally no way to send `Ctrl-C` to them.

**Comment by gaow** [comment]
But in these cases don't we still have the main SoS process controlling the external task status? If that's the case then we use `try ... except` to capture keyboard interruption on the main process, and send a `killalll` message to every external task involved. It's like running `--kill` but we tie to the `ctrl-c` interruption on the main process.

**Comment by BoPeng** [comment]
No. It does not work like this. Like my comments in #448, SoS does not wait for the completion of jobs (so no `try/except` and these jobs are not directly controlled by SoS. Actually, by default sos would exit after the jobs are submitted, and running sos again would resume from completed tasks.

**Comment by BoPeng** [comment]
Currently `sos kill` uses pulse thread to kill a task but this does not work well if the job is submitted to the task queue (e.g. PBS) and not yet started, because the job could still start after we kill it. We should actually start the task engine to kill the job.
