### ISSUE TITLE
Track files / dirs with lite or no MD5

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#455]
Separated from #450. We may want to design some sort of `dag` target or `dir` target to track a bunch of files or directory without md5 of the exact content. For example, 

```
files(["{x}.txt" for x in range(10000)"])
```

would be considered as a single target. The exists of `files` could be existence of all files, but `md5` would be simply md5 of filenames (or cheap information about file size). Similarly, 

```
files('a_dir')
```
would just check all the files. 

This can be useful in Make style workflow when we create execution graph. Are there any other situations this target may be useful? Perhapsit can also be used with `output:` to skip fine signature check?

**Comment by BoPeng** [comment]
This is a `target`, so it has its own `exists`, `md5` functions, and can be depends upon and serve as input.

As of applications, 

1. save on md5 time
2. group items together to avoid listing all files under directories etc.
3. `output` can indeed be a large number of files (e.g. a directory), using this target allows us to, for example, copy all files back from remote_server.

Name of the target could be

* `group` to group files and directories together.
* `manifest` to indicate this is a manifest of files, not their contents
* ??

**Comment by gaow** [comment]
How about `bundle`?  It is indeed a "collection" but `collection` is a python module.

**Comment by BoPeng** [comment]
Sounds reasonable. It will be put behind `sos_step` though.
