### ISSUE TITLE
Advanced `for_each` rule for input parameters

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#462]
Currently the `for_each` rule will enumerate all possible combinations of input parameters. But there are cases we need additional constraints. For example certain routines should only be performed when N > P, etc. Have an additional constraint would be extremely helpful and implementation-wise I assume it is easy:

```python
x = [0,1,2]
y = [0,1,2]
z = [2,1,3]
rule = "_x!=_y and _y<_z and _z>2"
result = [(_x, _y, _z) for _x in x for _y in y for _z in z if eval(rule)]
# [(0, 1, 3), (0, 2, 3), (1, 0, 3), (1, 2, 3), (2, 0, 3), (2, 1, 3)]
```

But we need a good interface for it, and need to quit if `result` is empty or the rule has an error. 

I'm thinking how about when `for_each` is a tuple of length 2, it takes the parameters and the rule; and when it is a list it takes the parameters? eg:

```
for_each = (['x', 'y'], ('_x < _y'))
```

and 

```
for_each = ['x','y']
```
the original behavior. It's a bit ugly but we do not need a new parameter. Otherwise we can have and additional option `for_each_rule = '_x<_y'`. Would it be possible?

**Comment by BoPeng** [comment]
`stop_if(_x>=_y)`?

**Comment by gaow** [comment]
But it will mess up with my input. I only provide enough input excluding those situations to start with. stop_if would skip one of my input

**Comment by BoPeng** [comment]
Could you present an example on how to use your syntax? Perhaps `skip=lambda` would also work?

**Comment by gaow** [comment]
Yes, `skip` sounds a good syntax! For example:

```
[default_1]
parameter: n = [100, 200, 300]
paramter: p = [50, 100, 200]
input: 1.txt, 2.txt, 3.txt, group_by = 1, for_each = ['n', 'p'], skip = if _n < _p
run: 
  echo ${_input} data apply parameters ${_n} ${_p}
```

This example is trivial but there are complicated ones in practice. The catch is that there are more parameter combinations than input files so `skip_if` will not work.

**Comment by BoPeng** [comment]
`group_by` and `for_each` stacks (similar to nested loop) so I do not understand why `stop_if(_n < _p)` does not work.

**Comment by gaow** [comment]
Exactly: you see how `_index` is messed up. I should have made a better example:

```
[1]
parameter: n = [100, 200, 300]
parameter: p = [50, 100, 200]
parameter: outfile = ['1.txt', '2.txt', '3.txt', '4.txt', '5.txt', '6.txt']
input: 'a.txt', 'b.txt', group_by=1, for_each=['n', 'p']
output: outfile[_index]
stop_if (_n > _p)
print("${_output} ${_n} ${_p}")
```

I envision it will run into an index error because the max output index is just 6. However running this code I get another perhaps SoS bug: 

```
ERROR: 'provides'
```
Anyways, how can i skip parameters beforehand without messing the index?

**Comment by BoPeng** [comment]
I got index error within jupyter.

Anyway, `skip` was replaced by `stop_if` because the parameter is processed altogether (not one by one), so a lambda function has to be passed (e.g. `skip=lambda _n,_p: _n > _p`). 

I am however reluctant to make the input syntax more complex for a corner case that can be easily implemented using existing methods. For example, you could do

```
[1]
parameter: n = [100, 200, 300]
parameter: p = [50, 100, 200]
np = [(_n,_p) for _n,_p in zip(n,p) if _n > _p]
parameter: outfile = ['1.txt', '2.txt', '3.txt', '4.txt', '5.txt', '6.txt']
input: 'a.txt', 'b.txt', group_by=1, for_each='np'
output: outfile[_index]

print("${_output} ${_np[0]} ${_np[1]}")
```

```
1.txt 100 50
2.txt 100 50
3.txt 200 100
4.txt 200 100
5.txt 300 200
6.txt 300 200
```

**Comment by gaow** [comment]
Yes that'd work for this example. But my real case is complicated because the `task` part that involves the parameter is generated by fixed code that should not be touched -- sometimes I need these constraints sometimes not. I think implementation is easy, it is just a good interface for it.

So you are suggesting with the old `skip` with lambda function I can avoid messing up the index? I'm also thinking if there is a way to have generated `output` differently that takes into consideration of those? But I'm going to complete #445 down the line which sounds like it depends on  `_index` ...

**Comment by BoPeng** [comment]
`_index` belongs to implementation details and you should not try to use it. The `skip` parameter is ugly and difficult to use and I would not restore it either.

Changing `for_each` is not a good idea because at least `skip` was able to skip based on both filenames and `for_each` variables and your proposal would not.

In the end, I still do not see what cannot be implemented under the existing framework. If

```
for_each = {'np': [(_n,_p) for _n,_p in zip(n,p) if _n > _p]}
```
does not work, how about

```
for_each = {'_n,_p': [(_n,_p) for _n,_p in zip(n,p) if _n > _p]}
```
(not implemented).

**Comment by gaow** [comment]
```
for_each = {'_n,_p': [(_n,_p) for _n,_p in zip(n,p) if _n > _p]}
```
will give me exactly what I need so it would be great to have it!

Or, have a reserved keyword "condition" that goes at the last element of `for_each` -- not sure if the parser can accommodate that easily:

```
for_each = ['n', 'p', condition = 'lambda: _n, _p: ...']
```
But I like your interface better, if it works. It's like an enhanced version of `for_each` and is consistent in flavor to eg. `shared` that takes both lists and dicts.

**Comment by BoPeng** [comment]
You could already do

```
for_each = {'_n': [_n for _n,_p in zip(n,p) if _n > _p],
    '_p': [_n for _n,_p in zip(n,p) if _n > _p]}
```

**Comment by gaow** [comment]
I see ... so I'd have to loop it for every parameter? For my case it should be:

```
for_each = {'_n,_p': [(_n,_p) for _n in n for _p in p if _n > _p]}
```

so having a tuple-like syntax would avoid looping multiple times.

**Comment by BoPeng** [comment]
Please finish something like the following,

```diff
diff --git a/sos/sos_step.py b/sos/sos_step.py
index 2f4e41a..82b9b53 100755
--- a/sos/sos_step.py
+++ b/sos/sos_step.py
@@ -408,8 +408,19 @@ class Base_Step_Executor:
                 fe_iter_names = []
                 fe_values = []
                 for k, v in fe_all.items():
-                    fe_iter_names.append(k)
-                    fe_values.append(v)
+                    if ',' in k:
+                        names = [x.strip() for x in k]
+                        values = [[] for name in names]
+                        for _i,_v in enumerate(v):
+                            if len(_v) != len(names):
+                                raise ValueError('...')
+                            values[_i].append(_v)
+                        #
+                        fe_iter_names.extend(names)
+                        fe_values.extend(values)
+                    else:
+                        fe_iter_names.append(k)
+                        fe_values.append(v)
             else:
                 if ',' in fe_all:
                     fe_var_names = [x.strip() for x in fe_all.split(',')]
```

add a test, and document this feature.

**Comment by BoPeng** [comment]
I usually use `itertools.product` etc to avoid nested list comprehension.

**Comment by gaow** [comment]
> I usually use itertools.product etc to avoid nested list comprehension.

Thanks for the tip -- will do. I cannot apply that patch for some reason (corrupt at line 26) so I'll patch manually, add a test and document.

**Comment by BoPeng** [comment]
The code might have bug anyway.... you should rewrite it.. it is not hard.

**Comment by BoPeng** [comment]
The loop is actually totally wrong. :-)

**Comment by gaow** [comment]
Is the logic run? The code looks fine by appearance up to the raise part. I'm trying to understand the rest.

**Comment by gaow** [comment]
```
fe_values.extend(zip(*values))
```
? from my eyeballing of codes. Now trying to actually run and observe ...

**Comment by gaow** [comment]
For some reason I cannot get this work!! As I said instead of index error I run into:

```
[GW] sos run test.sos -v 4
DEBUG: Workflow default created with 1 sections: default_1
DEBUG: Args outfile[_index]
 cannot be determined: name 'outfile' is not defined
DEBUG: Args outfile[_index]
 cannot be determined: name 'outfile' is not defined
INFO: Resolving 2 objects from 1 nodes
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/__main__.py", line 297, in cmd_run
    executor.run(args.__targets__)
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/__main__.py", line 297, in cmd_run
    executor.run(args.__targets__)
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/sos_executor.py", line 698, in run
    dag = self.initialize_dag(targets=targets)
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/sos_executor.py", line 478, in initialize_dag
    self.resolve_dangling_targets(dag, targets)
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/sos_executor.py", line 290, in resolve_dangling_targets
    env.logger.debug('{}: {}'.format(x.step_name(), x.options['provides']))
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/sos_eval.py", line 550, in __getitem__
    raise KeyError(key)
KeyError: 'provides'
ERROR: 'provides'
```
so does my Jupyter. Other SoS scripts are fine. Still looking.

**Comment by BoPeng** [comment]
`fe_values` should match `fe_iter_names`. Basically  if`v` is `[(a,b), (c,d), (e,f)]`, `values` should be `[[a, c, e], [b, d, f]]` and be extended to `fe_values`. My use of `_i` was wrong.

**Comment by gaow** [comment]
Yes that's what I figured I should do `zip(*)` to transpose it in the end. Glad I got it with eyeballing but I cannot get SoS work on this one ... see above.

**Comment by BoPeng** [comment]
Could you send me your `test.sos`.

**Comment by gaow** [comment]
Here: [test.sos.txt](https://github.com/vatlab/SOS/files/800160/test.sos.txt)

**Comment by BoPeng** [comment]
Works after `touch a.txt`, something wrong with the step look up code.

**Comment by gaow** [comment]
Oh yes, sorry I always have 1.txt 2.txt etc in place but you had a.txt ... I tried to fix with a lot `sos remove` commands but did not check the input!

**Comment by BoPeng** [comment]
This has been fixed. Basically currently all steps are auxiliary steps (that provides `sos_step` target) but some code still assumes that auxiliary steps have a `provides` option.

**Comment by gaow** [comment]
Great! Also the patch seems to work. I'm doing test / docs now.

**Comment by BoPeng** [comment]
#445 is also yours if you still want that feature. Frankly that option is a bit awkward given that `output` would be evaluated repeatedly for each input loop ...

**Comment by gaow** [comment]
Yes I'd need that feature I'm afraid, but until the week after next (I know it is weird to say this but that's the plan ...). I'll paste the patch and behavior etc on that ticket and we can decide if we want it.
