### ISSUE TITLE
Ordered DAG

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#464]
I'm not sure if my observation is completely accurate but I notice the output DAG is ordered differently every re-run. The side effect (or rather a phenomenal) is that every rerun it might either be slow at first (running new task first) and fast towards the end (skipping previously completed tasks), or fast at first then becomes slower (which is the expected behavior). Is it possible to fix the order of output DAG so that each rerun will surely skip all previous completed tasks first?

**Comment by BoPeng** [comment]
Currently the execution path is selected by random and there is no way to know if a path has been executed before it is executed.

**Comment by gaow** [comment]
I see. Thanks for the clarification!
