### ISSUE TITLE
Action level signature

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#468]
Right now sos records signatures at step and task levels. When we work on a step with long running scripts, it might be helpful to have action level signature so that long-running scripts can be more easily mixed with other actions. in my case, adding another `run` action after a `run` action running `STAR` causes the whole `STAR` command to be re-executed.

**Comment by gaow** [comment]
+1 on this. I too have the problem from time to time.

**Comment by BoPeng** [comment]
We already allow actions to accept parameters `input` and `output`, as optional parameters for some subtle purposes. Perhaps we can build signatures for actions with `input` and `output`.
