### ISSUE TITLE
Evaluation in panel makes notebook goes under side panel

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#471]
Ctrl-Enter is ok, Shift-Enter is ok, but Ctrl-Shift-Enter (`execute_in_panel`) would resize notebook and make it go under panel. Had a quick look at the code and did not know what triggers the resize.

**Comment by BoPeng** [comment]
This appears to happen after toc2 is loaded

**Comment by jma7** [comment]
I didn't observe the behavior you described. Ctrl-Shift-Enter will copy the command in notebook to side panel and execute there. I didn't see the resize of notebook or side panel.

**Comment by BoPeng** [comment]
It was on my home mac chrome, I cannot observe it now either on windows/chrome.

**Comment by BoPeng** [comment]
Cannot seem to reproduce.... I suppose this is again a cache issue?
