### ISSUE TITLE
Definition of dryrun mode

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#474]
Dryrun mode is very difficult to define because of the dynamic nature of sos. It currently,

1. does not report error is no input file is available, but the behavior is undefined if the input is provided by another step.

2. does not execute most actions (action return `None`).

3. does not verify output file

4. does not check or save signature

I am wondering if we should get rid of 1, because a DAG cannot be built correctly without 1. Then 3 would have to be a `touch` function to generate intended output (so satisfy the input of next step).

**Comment by gaow** [comment]
I have no problem to remove it. I now inspect syntax error via `sos convert` :)

**Comment by BoPeng** [comment]
I think dryrun can be useful if it works like this

1. Works identical to `run` mode in terms of multi-processing, input file etc.
2. actions mostly work the same, scripts would print interpolated scripts. This is helpful for debugging in some cases.
3. the steps `touches` output so that dryrun will leave a complete set of empty output.
4. no signature etc.

Because we do not take return value of scripts (except for failure), the workflow would most likely still work.... and the interpolated script and complete set of output files can give users a hint of what would happen after execution.

**Comment by gaow** [comment]
Well I previously use it only for syntax check. In fact a regular run will also check syntax. My point is do we want to consider how useful it is (or how often one uses it, which to me is not all that often) before improving it? Of course if the improvement is straightforward then it is nice to have it. I was just weighing if it worth the work.

**Comment by BoPeng** [comment]
Currently `dryrun` is not useful at all and I am trying to see how to make it useful. In the proposed method, we could

1. write a step, run `sos dryrun stepname` to check if string interpolation works as expected.
2. run `sos dryrun workflow` to get all the task files, then run `sos status task -q queue` to see if the script has the correct path on the remote host.

Of course sos dryrun would fail for regular non-task statements, and dryrun is not a good idea if you put heavy analysis in sos trunk (non-action, non-task).
