### ISSUE TITLE
remote files target?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#475]
Say I have a large number of large raw files stored on a institutional server that are accessible from the cluster. If I would like to process them remotely using sos, I would write a workflow that handles them directly on the cluster...

The problem is that these files do not exist locally so our workflow would choke with 'non-existent' input file etc. 

Perhaps some sort of

```
input: remote('/path/to/file', host=alias)
```
would help? Say,

1. to get signature, sos would login to remote server and calculate it.
2. to process the file locally, sos would copy the file.
3. to process the file on the host, sos would not copy the file.
4. to process the file on another server, sos would copy from host to that server.

Doable but sounds a bit complicated.

**Comment by jirikuncar** [comment]
Would you consider to support different resource types (see e.g. [Target](http://luigi.readthedocs.io/en/stable/api/luigi.target.html) class from Luigi package)?

**Comment by BoPeng** [comment]
Thank you for pointing us to the Luigi Target class. Yes, we have remote target in mind but I have not figured out a good interface for it. Also, our "remote" features currently focus on [remote execution of tasks](http://vatlab.github.io/SOS/doc/documentation/External_task.html) so there seems to be less a need for remote targets if the tasks are executed locally (on the remote host).

**Comment by jirikuncar** [comment]
The issue might be with tasks executed on different machines (see the discussion on using remote kernels). It would be nice to connect the outputs and inputs from different locations with some easy API.

**Comment by BoPeng** [comment]
Could you describe a use case where such a feature can be useful? Currently sos tasks are designed to be independent with each other and with systems they are running on, which allow them to be executed by different task queues. I also do not see an application of connecting remote kernels.

**Comment by jirikuncar** [comment]
@BoPeng the use case is an interactive development of a workflow in Jupyter notebook so certain tasks can be offloaded to remote machines.

**Comment by BoPeng** [comment]
Our answer to "offload certain tasks to remote machines" is [remote execution of tasks](http://vatlab.github.io/SOS/doc/documentation/External_task.html), which I think should satisfy your need.

**Comment by jirikuncar** [comment]
@BoPeng it's nice, but it's not what our users were asking for. They are developing their code directly in Jupyter notebook and they would like to be able to execute a cell remotely and use the result locally. That is why I have been implementing the integration of remote kernels.

**Comment by BoPeng** [comment]
The remote task system is designed to be interactive. The tasks can be submitted in Jupyter, in a cell, to any cluster and super computer, and you can monitor the status of tasks easily, the files are also automatically synced between local and remote hosts, and a nice thing about this approach is that the Jupyter notebook is not blocked when the tasks are executed remotely.

But the remote kernel method does have the advantages of being truly interactive in the sense that you get "results" as variables (while `tasks` can only return files), and the kernel can be in any language (while the tasks are sos wrapper of other scripts).

**Comment by BoPeng** [comment]
I am hesitating between

1. `remote(files)` without host information with the only side effect that files are not tracked locally.
2. `remote(files, host)` to let sos know files are on `host` (and do something if the task is executed on another host, which can be really tricky because host names can differ).

also, not sure if 

1. `files` should be in local names and be translated for different remote host
2. `files` should be in remote names without translation, or
3. `remote(files, host)` should be in `host` specific names and need to be translated if the tasks are submitted to another host.

**Comment by BoPeng** [comment]
A `remote` target type has been implemented and is documented [here](http://vatlab.github.io/SOS/doc/documentation/External_task.html#remote-target-1815). Hopefully it is easy to understand and use.

**Comment by BoPeng** [comment]
@jirikuncar I am closing this ticket because a general `remote` target type (a wrapper to other targets) has been implemented. Please create separate tickets for targets of other types.

Note that sos creates signatures for each target so it is difficult to create targets such as a single "directory" because it is difficult to track the content of the directory.

**Comment by gaow** [comment]
A remote toast of champagne on #503 ! :)

I just want to make sure that when `-q` is not specified then `remote(file)` would be degenerated to just `file`, right? Also would it make sense to have some global switch that makes every file remote? I admit a good interface is difficult but how about a default config option that we can set via `sos config`? Then with this option, every `input/output` will be translated to `remote()` and execute.

**Comment by BoPeng** [comment]
When `-q` is not specified, `task` will still be generated and be executed locally, and in this case `remote(file)` is simply `file`. However, using `remote` target in a step without `task` is currently undefined, meaning it most likely will not work.

Global `remote` sounds like an interesting idea....
