### ISSUE TITLE
Rstudio notebook

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#478]
also has multi-language support etc. http://rmarkdown.rstudio.com/authoring_knitr_engines.html 

So is SoS really good at anything?

1. jupyter, compete with RStudio, losing battle?
2. workflow, facing a huge crowd of workflow systems
3. Simple sos format that unites 1 and 2 would be the selling point?

**Comment by gaow** [comment]
I do not think Rstudio is comparable to Jupyter and their respective user groups are distinct. My understanding is that Rstudio is for statisticians yet Jupyter for data scientists. Workflow system is more for bioinformaticists who typically focus more on running things on large data-set yet constantly having difficulties interacting with the data nicely. Usually I see people running all the pipelines, and use separate R instances to examine output of each. Not only SoS is a great workflow system, it also bridges data science and bioinformatics. Such simplification and unification (your point 3) is crucial to correct and reproducible research, which will make science better!
