### ISSUE TITLE
Random identical tasks.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#481]
In many cases, especially for simulation studies, there is a need to run identical tasks repeatedly. I would recommend that each instance is associated with a RNG seed so that they can be separated and executed as separate tasks. I am however wondering if we should have internal support for truly random executions (e.g. generate a random number for task id).

**Comment by gaow** [comment]
In my simulations I always pass `seed` as a parameter and set my RNG. I think a reasonable way a task ID is generated is to calculate MD5 of the str version of all the parameters and the contents of the task script. This will ensure the randomness. Of course this is only feasible after string interpolation. If this is how SoS is currently designed then it'd be good to use this MD5 rather than random numbers.

**Comment by gaow** [comment]
My point is that people should be advised against not setting `seed` (a very bad habit and direct violation of reproducible research). Using these MD5 there will be task ID conflict that will ideally throw an error and ask users to check their implementation ... maybe I'm being too stringent here but I really think one should always set a `seed`.

**Comment by BoPeng** [comment]
This is reasonable, but there are subtle differences in things like

```
input: for_each={'rep': range(1000)}
task:
run:
    seed=get_a_seed()
    start simulation(seed)
```

and 


```
input: for_each={'seed': random.get_some_number(1000)}
task:
run:
    start simulation(${seed})
```

The first task is identical to sos' eyes.

**Comment by gaow** [comment]
Let me try if I get it: you are saying in different steps there are tasks that would appear identical, even if they are initialized with seemingly different ways of seeding -- and is often too subtle to debug? I agree. But I'm not sure how often people would have identical scripts in 2 separate steps. Having identical scripts in multiple steps is also always a bad habit to me.

Another reason I think random task ID is perhaps not good is that I can imaging sos submits tasks to clusters and certain tasks will fail repeatedly. Then users will remember that task ID and resubmit until it works. Now ff the same SoS is executed a second time (for whatever reason) all task ID will change as they are generated randomly. This may cause a bit of a confusion on the user's end.

**Comment by gaow** [comment]
Oh for your subtle case, would it be an issue when 

```
[human_1, mouse_1]
input: for_each={'seed': random.get_some_number(1000)}
task:
run:
    start simulation(${seed})
```
is executed in the context of parallel human and mouse pipeline executions?

**Comment by BoPeng** [comment]
Yes. The problem with the first example is that the task itself generates (perhaps saves) random seeds but the script itself appears to be identical to sos so an identical task ID would be generated so that only one task would be executed.

For the `human` and `mouse` case, yes, the task would be the same for human and mouse for each identical seed.

Task tries to be self-contained with ID hashed from its content, and I am trying to see if there is a need for users to generate truly random task IDs.
