### ISSUE TITLE
-w option and daemonized tasks.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#482]
I just submitted a patch to enable daemonized tasks and the default `--no-wait` behavior. It has a strong impact on the use of tasks so everyone should be aware of the change. It might also have introduced some weird behavior and bugs.

The changes are
1. daemonize tasks so that they are executed independent of sos. This should have been done long time ago, but there has been some technical difficulties (conflict between `multiprocessing` and `os.fork`).
2. when `sos` is waiting for the execution of tasks and there is no runnable node, sos would quit without waiting for the completion of tasks.
3. Option `-w` can be added to change the behavior to `wait`.

Remaining issues:
1. running in `wait` mode (option `-w`) + `Ctrl-C` would kill the tasks. This should be fixed if this is the case.
2. It is unclear how to handle `stdout` and `stderr` for tasks. It makes sense to direct them all to `task.out` and `task.err`, instead of to terminal.
3. This is not supported on windows so we might have to figure out something else if we ever want to support task engine properly on windows.

**Comment by gaow** [comment]
I've not tested the behavior myself (not yet at the stage to run heavy computation for the revision ... ) but I can understand `--no-wait` means `sos run` will just submit everything and quit. With `wait`, does `sos run` hang on the terminal checking the job status automatically from time to time?

**Comment by BoPeng** [comment]
Yes. With `-w`, the task engine would repeatedly check the status of all jobs, local or remote, using effectively `sos status -q` with engine-specific `check_status_interval` (e.g. 30s), and continue the workflow after a job is completed.

By default, sos will exit with a list of pending tasks, which allows jupyter notebook users to submit the job and continue to work on something else (not implemented yet #480).
