### ISSUE TITLE
Stop after submitting one task

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#484]
Usually if one job fails all jobs would fail for the same reason, and if one job runs all jobs would run. We can use the`-n` (dryrun mode) option to print instead of run scripts, but it would be nice to

1. dryrun only one task because it is likely that one task is enough to see if the script is correct.
2. run only one task to check if it actually runs correct before submitting the rest of the tasks to the cluster

We could quit or prompt the user if he would like to continue to dryrun or run the rest of the job. Note that because of the multi-process nature of execution, it could be difficult for users to see the prompt to continue.

Not sure what this option could be named though. Perhaps `-p` (pause)?

**Comment by BoPeng** [comment]
At least "running only one task" could be achieved by

```
sos run script -n
sos execute task_id
```

because the dryrun mode would generate all tasks.

**Comment by gaow** [comment]
How about we do it from configuration -- can we have a line to specify how many tasks to submit, and default `-1` means all of them?

**Comment by BoPeng** [comment]
But we current does not have a way to control queue parameters, unless we do something like

```
sos run script -q pbs maxjobs=20
```

**Comment by gaow** [comment]
I'm thinking we can always `sos config` to reset this for 1 or more tasks, so there is no need for a terminal argument?

**Comment by BoPeng** [comment]
Yes, but my manual procedure would work too, namely

1. run `sos run script -q pbs -n`, wait until the first task is submitted and is "running" to display the script, Ctrl-C.
2. check the printed script and see if it is correct (if paths are correctly translated).
3. copy the task id to clipboard
3. run `sos execute task_id -q pbs` to submit the job and see if it starts execution, wait another few minutes and see if it continues.
4. run `sos run script -q pbs` to submit all jobs. The already submitted jobs will be running and will not be resubmitted to queue.
5. If things go wrong, check the details of the task with command `sos status task_id -q pbs -v4`

This is not very complicated if you know what each step is doing.

**Comment by BoPeng** [comment]
How about

```
-n 1
```

for running one job? Basically this means dryrun and at most 1 task. We can consider this as some sort of level or stage of dryrun, we could even promote this to something like

```
-n r1
```

to say, yes, this is dryrun, but let us try one task for real.

Both look to me like some sort of hack/abusive use of options.

**Comment by gaow** [comment]
I agree we should provide shortcut to this (not a sequence of commands) because it'd be a commonly used feature. It's just a bit awkward to squeeze it here with `-n`. Also this option is only relevant when running external tasks on remote computers ... so I still feel using configuration file is most natural.

**Comment by BoPeng** [comment]
I am using

```
host:
    host1:
         queue_type: process
    host1_pbs:
          queue_type: pbs
```

to define two queues for the same host. The first one is for small tasks running on the head node (e.g. `rsync`), and the second one is for real large tasks. Submitting large jobs to the first one (and crash the head node) will get me grounded but this works for me nicely now.

So what you are proposing can be done in two ways,

1. define `host1_test`, `host1_1` or something with a `max_running_hosts` set to 1, then define `host1` as the regular full service queue.
2. allow the config definition to use some sort of command line argument like `-q host1 jobs=1`.

I tend to think 1 is easier for both users and us developers.

**Comment by gaow** [comment]
Yes I also think 1 is good because it is intuitive and self-contained.

**Comment by BoPeng** [comment]
OK, then we should just document and promote this one-server-multi-config approach.
