### ISSUE TITLE
nteract notebook

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#487]
I don't have anything specific in mind when I post this -- just think it is interesting even Jupyter gets competitions:  

http://moderndata.plot.ly/nteract-revolutionizing-notebook-experience/

**Comment by BoPeng** [comment]
Jupyter has been slow at catching up things, mostly because of its high popularity which makes it extremely difficult to adopt any intrusive change. New tools such nteract could in stead have a fresh design and apply new technologies.

One example of this is inline interpolation (RStudio's `r expr` stuff), which has been discussed for 4 years without a proper solution.

**Comment by gaow** [comment]
I couldn't resist the temptation of trying this out with SoS notebook. The within-cell language switch dropdown and the nice sidebar of output are both gone ... but it looks great!

**Comment by BoPeng** [comment]
Try it and let me know what we can learn from it.

**Comment by BoPeng** [comment]
BTW, I was planning to create some videos (gifs) to demonstrates the features of sos, like what nteract has but did not get around to do it. Do you know any good tool for it? I have a windows screen-shot tool that might be able to do it.

**Comment by gaow** [comment]
Somehow it is buggy on my end ...  there is only SoS and R kernels available. For the `R` kernel whatever code I type and run it stuck at the `[*]` busy sign without producing an output. But the SoS kernel seems to work nicely. Apart from a nicer interface, I do not find these two tools are much different except:

* one can drag a cell and insert it elsewhere
* nteract supports uploading to gist

It seem to have some potential as well as rough edges.

**Comment by gaow** [comment]
> BTW, I was planning to create some videos (gifs) to demonstrates the features of sos, like what nteract has but did not get around to do it. Do you know any good tool for it? I have a windows screen-shot tool that might be able to do it.

For mac there is build-in screen recorder, and suppose it generates MOV files we can always convert it to MP4 then use the linux command `convert` to make it gif. I'm just not sure (before I google) if we can fine tune how many frames per second on the gif.

**Comment by BoPeng** [comment]
I do not get it, you meant nteract uses our SoS kernel?

**Comment by BoPeng** [comment]
Yes, the goal is to have something small to be put on the frontpage. Like movable screenshots.

**Comment by gaow** [comment]
Yes. In fact it can open any ipynb notebook so I just opened one with SoS kernel. Apparently all the hacks we've done to jupyter javascript codes are gone, but it otherwise seems to work fine.

**Comment by BoPeng** [comment]
But it would not recognize our cell data for different engines right? I mean, R language, Python language etc.

**Comment by gaow** [comment]
Making a video and converting to gif is a lot simpler than having to constantly take screen shots. I still suggest that we make videos via screen recorder, and maybe convert them all into pictures (via `ffmpeg`), keep perhaps every N of them (via `SoS`), resize them to smaller (via `convert`) and make them a gif again (via `convert`). That way you do not have constantly take screen shots and you can always re-edit from that video

http://askubuntu.com/questions/610903/how-can-i-create-a-video-file-from-a-set-of-jpg-images

**Comment by gaow** [comment]
> But it would not recognize our cell data for different engines right? I mean, R language, Python language etc.


No this is gone, unfortunately. It does have a dropdown menu already at the end of every cell and one of them says "convert to markdown". Also the side panel of results preview is gone too.

**Comment by BoPeng** [comment]
I see, and all the magics....
