### ISSUE TITLE
Option for PBS JOB name

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#489]
Not sure how to do this but right now all jobs in PBS task queue are task ids, which are quite uninformative. It might be helpful to add something like step name to the name.

**Comment by gaow** [comment]
I agree ... and even for local jobs it would help if `sos status` can show somewhat informative task ID's. Is it related to #486 ?

**Comment by BoPeng** [comment]
$486 is different. 

The problem is that the same task could be run by different steps or workflow so adding any such information to task name would break its independence.

**Comment by BoPeng** [comment]
It is possible for us to provide an option `group_name` or `tags` to tasks so that we can keep such information in the task file, or in task file name. There are a few possibilities

1. Code group names in task name  e.g. `80aa97f8ab432.myworkflow.align.task`
2. Embed group names in task file
3. use a separate file for group names e.g. `80aa97f8ab432.tags`

The tags would by default contains for example a workflow id and a step id so that

```
sos status 
```
would limit to workflows executed in the current project directory (unless a parameter `-a` asks to list all tasks).

```
sos status -t align
```
would list all tasks with tag `align`.

**Comment by BoPeng** [comment]
We can use the name only for PBS job so that we know what the job is for. The task would still have unique hashed names.
