### ISSUE TITLE
Summary of supported task queues and servers.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#491]
| Server | OS | Queue Type | sos queue | Ticket/Config | Comment |
| --- | --- | --- | --- | --- | --- |
| nautilus | RHEL6 | PBS/Torch | pbs | | First cluster system to test |
| bcbm-bpeng |  MacOS | | process | | Mac workstation |
| linux-server | RHEL6.5 | | process | | with docker |

**Comment by gaow** [comment]
Moved to https://github.com/vatlab/SOS/wiki/Summary-of-supported-task-queues-and-servers for continued, shared editing.

**Comment by BoPeng** [comment]
OK, please list details of your system configuration (especially the "differences") as much as possible. I believe that in the end we will list typical configurations in to the documentation.

**Comment by gaow** [comment]
Updated the list. My 2nd server requires logging in to a headnode first, then to a computational node from there -- I believe it is a typical setup of a "loose" cluster. I rarely use that one (except for very long running jobs) because it is inconvenience but hopefully with SoS config it will be more straightforward. Does my description of the setup makes sense and can it be handled with SoS as is?

**Comment by BoPeng** [comment]
So there is no direct access to workers and there is no queue system from the head node? At least the head node and workers share file system, right? Can you start command directly from head node?

Perhaps we can honor `submit_cmd` for `process` type?

1. set up public key access for head and workers.
2. from desktop, use `process` as queue type
3. set up `submit_cmd` as something like `ssh worker ${cmd}`
4. We could even honor `template_file` and use `submit_cmd` as `ssh worker bash ${job_file}`.

My point is that we have `submit_cmd`, `template_file` etc for `pbs`. We might be able to work with this cluster by honoring this mechanism with `process`.

You could open a ticket for this setup (without specific server details).

**Comment by gaow** [comment]
No there is no queue. We cannot start commands on the login node.  There is even no shared file system between login and computation nodes but those computation nodes do share a file system. It is also very similar to a system we had at the Baylor lab. I will open a ticket for it after I test out my first cluster in that table.

**Comment by BoPeng** [comment]
I do not get it. You should be able to start a command as long as you can `ssh worker command` from head node.

So it looks to me like a `Chained_TaskEngine` or `PassThrough_TaskEngine`, basically 

1. You set up a sos task queue from the head node to a point that you can do your work remotely on worker if you are on head node.
2. You set up a task queue on your workstation and remotely control the task queue on the head node. Something like:

```
sos run script -q headnode
```

send task to headnode. This would trigger the following command
```
sos execute task -q worker
```

which sends the task to worker. Because our `sos execute` command can already work with or without `-q` option, the actual implementation should not be very difficult.

**Comment by gaow** [comment]
Oh yes of course `ssh worker command` would work. I was saying we cannot run, say sos, on the login (we are not supposed to). I see you logic. It is just not immediately clear to me how the tasks are to be monitored from the desktop.

**Comment by BoPeng** [comment]
Monitor is problematic because the current implementation does not check server type on remote host, but everything is possible.
