### ISSUE TITLE
Converting variables that point to actual files?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#492]
We are having trouble determining what to convert during the conversion from local to remote task. For example

```
ID = 'myID'
support_file = '/path/to/support/file'

task:
run:
    command ${ID} --from ${support_file}
```

would be converted to 

```
ID = '/remote/path/to/myID'
support_file = '/remote/path/to/support/file'

run:
    command ${ID} --from ${support_file}
```
and we have to use

```
ID = '/remote/path/to/myID'
support_file = '/remote/path/to/support/file'

task: ppreserved_vars=['ID']
run:
    command ${ID} --from ${support_file}
```
to keep `ID` from being converted as a path.

Is it possible for us to only convert variables that points to local files? This sounds reasonable but there is an annoying possibility that there happens to be a file with name `myID` that causes `ID` to be converted so the behavior would differ depending on environment. So I assume the explicit `preserved_vars` option is still the way to go.

**Comment by gaow** [comment]
It does sound like we have to introduce an option for this one way or another. `preserved_vars` sounds reasonable choice.

**Comment by BoPeng** [comment]
I have submitted a patch that gives out a warning for suspicious conversions, namely for a string that is not a file and is being converted as a file. Hopefully this can help catch these ID conversion errors.
