### ISSUE TITLE
Question on behavior of the new task branch

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#494]
I'm just starting to use the new task branch for real jobs and I get messages below that I'd like to clarify:

```

INFO: a260f012fd2fe8cff7d14c968812ba39 started
INFO: 93fb6a8afc55e0e3885dc2398c218f16 started
INFO: f3ae37d21b7c9eefd4bf7dec4086076d started
INFO: 013d37c0116174ef9c878f17460dbc90 started
INFO: ba7e2b22d7860ac0de7b77612c552aae started

ERROR: 20 pending 10 running
ERROR: 20 pending 0 running


INFO: 90483282666a6ce9aca3c864e687ae2f started
INFO: b9bce1933c16321e35fa503f9294d1e5 started
INFO: 609aa9f11a1e1a901671e0ecdc3701b7 started
INFO: 0ded6a12cca6154e214b61821e8eeff5 started
INFO: 21f9bd35c9e8bef7b1f78fcaa685d993 started
INFO: feeb83ad09f3a389b452c1f9852636e6 started
INFO: c9410b329fd6799f43708b9164fa5ea6 started
INFO: cb5c85208f4ec7d213aac65cd5df5d31 started
INFO: 0dc9420f452c5789fe024363fa177e61 started
ERROR: 1 pending 9 running
```

1. It seems the error messages are just nuisance ... because my program was able to finish just fine. Then why are these messages?
2. I'm running on `-v1` mode for less terminal output (perhaps this is why I can see these ERROR). Yet I still get these INFO lines. The `-v1` mode does turn off the `INFO: .... queued` lines, so why are these `started` lines displayed?

**Comment by BoPeng** [comment]
The task branch has been merged to trunk.

**Comment by gaow** [comment]
Yes sure -- I'm saying that this is the first time I used the master branch after the merger. I stayed with the old SoS to ensure my old batch of analysis will not rerun due to various changes. I'm now switching to the new master and these are the problems I'm seeing.

**Comment by BoPeng** [comment]
OK, just submitted a patch to enable `sos status -q` to list all queues and `sos status -q -v4` to show all the details. Working on this now.

**Comment by BoPeng** [comment]
For the second question, it means `-v` is not passed to tasks. This could be related to your job file if you are using it. Otherwise this should be a bug with local task engine.

**Comment by gaow** [comment]
Yes I'm still running everything local for now. The 2nd problem is easy to reproduce:

```
[test_1]
task:
run:
 touch /tmp/1.txt

[test_2]
task:
run:
 touch /tmp/2.txt

[test_3]
task:
run:
 touch /tmp/3.txt

[default_1]
sos_run('test:1+test:2')

[default_2]
sos_run('test:1+test:3')
```

and the outcome:

```
[GW] sos run test.sos -v 1
default:   0%|                                                                               | 0/2 [00:00<?, ?it/s]
test:1+test:2:   0%|                                                                         | 0/2 [00:00<?, ?it/s]INFO: b217053cddeadd69c1d300cf3b927032 started
test:1+test:2:  50%|██████▌                                | 1/2 [00:02<00:02,  2.21s/it]INFO: f0b191766e61e32ee4928ab7d7b2e1ad started
test:1+test:3:  50%|████████████████▌                                | 1/2 [00:00<00:00,  3.32it/s]INFO: 8fd463279814d07aadc685e15ab3d6b5 started
```
