### ISSUE TITLE
R_library() for github subdir packages

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#515]
There are cases when R library on github are kept in subdirectories of a repo rather than the root of the repo (e.g. [here](https://github.com/jobovy/extreme-deconvolution/tree/master/r)). Need to adapt `R_library()` for this case. I'd suggest we use a simple syntax:

```
R_library('jobovy/exteme-deconvolution/r')
```
and parse this with SoS to call the `subdir` argument of `devtools::install_github`.

**Comment by BoPeng** [comment]
I was wondering what is `exteme`.

**Comment by gaow** [comment]
Oh, `extreme-deconvolution` is the name of a repo where its R package locates in a subfolder `r`, unlike other standard R packages on github where the entire repo is the R package. It's just an example (that I encounter in my project) of such a case.

**Comment by gaow** [comment]
@BoPeng I should add this ... but would that be good before or after you move codes around? #882 I guess may be right after it so that I can also use that opportunity to test for issues.

**Comment by BoPeng** [comment]
I am moving it right now and should be done in the next few minutes.

**Comment by gaow** [comment]
Oh am so sorry ... I just pushed it to `sos_r` thinking I can rush it in ... if you are already moving then never mind. I'll fix it later.

**Comment by BoPeng** [comment]
Done. It should include your new commit.
