### ISSUE TITLE
Syntax highlight in Jupyter

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#524]
Is syntax highlight in Jupyter still working? I think I have it until very recently and now everything is in black:

![2017-03-20-14-31-58_scrot](https://cloud.githubusercontent.com/assets/917985/24117967/247cb9da-0d7a-11e7-9dcb-120349537ab8.png)

**Comment by BoPeng** [comment]
I can confirm this and will investigate later (after two deadlines this week). #521 is another regression bug, perhaps I accidentally broke something.

**Comment by BoPeng** [comment]
It seems that new notebook would have syntax highlighting, but reloaded and opened notebooks do not.

**Comment by BoPeng** [comment]
Jun: it seems that

1. create a new notebook would go through the `onload` and enable syntax highlighting.
2. reload the page and syntax highlighting is gone.

So we should revisit the codemirror part of the code, which might be broken by our frontend work.

**Comment by BoPeng** [comment]
Not sure what is going on but I cannot reproduce this bug any more.

**Comment by BoPeng** [comment]
@gaow Please close the ticket if the patch works.

**Comment by gaow** [comment]
Yes the syntax highlighting is back!
