### ISSUE TITLE
Auxiliary step in nested workflow does not generate target

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#526]
Here is a MWE:

```
[test1]
output: '1.txt', '2.txt'
run:
 touch ${output}

[test2]
input:  group_by = 'single'
depends: "${_input!n}.loglik.txt"

[loglik: provides = '{result}.loglik.txt']
input: "${result}.txt"
run:
  touch ${input!n}.loglik.txt

[default]
sos_run("test1 + test2")
```
Running this script I do not get `*.loglik.txt` as expected. However if I name `test*` as `default_*`  and run directly (not as nested workflow) then it works well. Am I doing something wrong, or is this a bug?

**Comment by BoPeng** [comment]
I can confirm this bug, which seems to be caused by the passing of context during the execution of nested workflow. Not sure if I can find a quick fix though.

**Comment by BoPeng** [comment]
Could you try again? You might not see `*loglik.txt` because they are removed with signature.

**Comment by gaow** [comment]
Well, it still does not work as expecte don my case ... I have to see if I can make a MWE out of my example. I will try to find a time slot today to strip my case into something simple enough to post here.

**Comment by BoPeng** [comment]
OK, I have added more output for `depends` statement. If you see  something like

```
INFO: _depends: ['1.loglik.txt']
```

this means the dependent file and/or its signature is available. Otherwise you should see something like

```
INFO: Target unavailable: 1.loglik.txt
INFO: Resolving 1 objects from 2 nodes
INFO: Adding step loglik with output ['1.loglik.txt']
```

**Comment by BoPeng** [comment]
Please test again and let me know if the bug still exists.

**Comment by gaow** [comment]
Sure. I'm going to close it if it does not existing anymore. I'm going to test perhaps tomorrow, though, after I help a colleague to meet her deadline ...

**Comment by gaow** [comment]
This particular issue is gone but there was something else about changing codes not triggering changes. I'm still looking but will post when there is MWE.
