### ISSUE TITLE
`task` no longer honors `-j`

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#531]
Not sure if others can reproduce it but `task` does not seem to honor `-j` on my end; it simply submit all jobs in the script.

**Comment by BoPeng** [comment]
Tasks honor `max_running_jobs` of the task queue.

**Comment by gaow** [comment]
I see. Looks I have to catch up with the documentation. So we have 2 layers of controls now:  `-j` is for DAG per task and `max_running_jobs` for task?

**Comment by BoPeng** [comment]
`-j` for maximum number of running steps (if there are multiple branches of the DAG. `max_running_jobs` is defined in `hosts.yml` which are different from queue to queue.

I was thinking of `-J` option to override `max_running_jobs` for testing/dryrun purposes.

**Comment by gaow** [comment]
I agree we currently have a great system that can fine tune resource assignment for complicated computational environment. But I feel that a complex system should not make a simple user case also complicated. For example on a single desktop with `-j` a user new to the might not even know there exists `hosts.yml` to set things up. A simple default behavior may be helpful in this case.

**Comment by BoPeng** [comment]
Default

1. Do we use `BackgroundProcess_TaskEngine`? The engine will now run in foreground in `-w` mode but the tasks are still executed externally, and most importantly controlled by the default 10 `max_running_jobs` rule. 

2. Do we use default `no-wait` mode? I do not mind changing the default but Jupyter obviously needs `no-wait` and I do not know what option to use for `no-wait`.

3. No `localhost` definition is a valid request.

**Comment by BoPeng** [comment]
So `-J` is needed when there is no definition for `localhost`?

**Comment by gaow** [comment]
Just to be frank about what I like to see -- by default (on `localhost`) it makes more sense not to execute jobs externally, and even have `-w` the default. Maybe switch `-w` with `-e` for "external" task such that with `-e` SoS will submit job as external and quit. Where the jobs are submitted to of course depend on queue setting, etc, which is more advanced.

As long as we have a default `-j` we should be good. Not sure what `-J` is ...?

**Comment by gaow** [comment]
To clarify on 2: 

> I do not know what option to use for no-wait.

You mean command line option? I was saying `-e` to try to kill 2 birds with one stone: it also takes care of your point No. 1 by making it clear that by default jobs are not executed externally

**Comment by BoPeng** [comment]
`-J` is number of running tasks, which in the case of `localhost` should be number of tasks. That said, tasks themselves can spawn multiple processes so `-J` means job/task, not process. Right now we have `max_running_jobs` set to 10 for background task engine so `-J` would be needed to override the default if localhost is undefined.

**Comment by BoPeng** [comment]
So `-e` (external) implies `--no-wait`? This is different because `-q queue` implies external.

**Comment by gaow** [comment]
Sorry perhaps we have to clarify what `external` means. My understanding of external is when `subprocess.Popen` is called. It seems currently it is called all the time so there is no distinction of internal vs external by my definition. So By not having `localhost` as a queue is it true that we'll then not call `subprocess.Popen` and have everything run inside SoS, as the case in previous releases? 

If `-q` will imply external now, then perhaps reluctantly should we reassign `-s` for `submit` and use `-m` for mode of signature?

**Comment by BoPeng** [comment]
The previous behavior is inconsistent in that jobs executed internally sometimes cannot be executed externally (the `import time` example I gave in another thread). Using the same `.task` mechanism allows me to handle them in the same way, with added benefits such as

1. Local execution can be different in that when I am local on the headnode of a cluster, running tasks locally means submiting to PBS queue.
2. I can create tasks locally but execute them on a remote host outside of sos (`sos execute -q`).

So whereas it is certainly more complicated and slower (creating of `.task` files and monitor status of tasks) to execute tasks locally but externally, I feel that a uniform approach allows more flexibility and can bring us further.

**Comment by gaow** [comment]
I see. That make sense. So basically now there is no way to execute SoS steps internally in parallel?

**Comment by BoPeng** [comment]
No but not using `DaemonizedProcess` has allowed you to kill all associated tasks, a default 2s check-status-interval should be acceptable... and users would not notice the creation of task files if no wait is the default.

**Comment by BoPeng** [comment]
I suppose we can make `no-wait` a queue option. That is to say, we can make `wait` an default option so the local task queue will by default wait. Then for remote `PBS_TaskEngine` we can set `wait: False` so that we do not wait for tasks for that particular queue.

In this way we get around of the default `-w` problem and saves an option.

**Comment by gaow** [comment]
This sounds good too!

**Comment by BoPeng** [comment]
Seems to be overly complicated with `-J` overridding `max_running_jobs` and `-w` and `-W` overriding `wait_for_completion`.

```diff
+        parser.add_argument('-j', type=int, metavar='STEPS',
+        default=4, dest='__max_jobs__',
+        help='''Maximum number of worker processes for the execution of the
+            workflow if the workflow can be executed in parallel (namely
+            having multiple starting points or execution branches).''')
+    parser.add_argument('-J', type=int, metavars='TASKS',
+        help='''Maximum number of externally running tasks. This option
+            overrides option "max_running_jobs" of a task queue (option -q)
+            so that you can, for example, submit one job at a time (with
+            -J 1) to test the task queue.''')

     parser.add_argument('-w', dest='__wait__', action='store_true',
-        help='''Whether or not wait for the completion of external jobs. By
-            default, a sos step will return immediately after submitting a task,
-            and the master process would exit after all tasks have been submitted
-            and there is no more step to execute. Specifying option "-w" will make
-            SoS wait for the completion of all tasks. -w is the default mode
-            in dryrun mode.''')
+        help='''Wait for the completion of external tasks regardless of the
+            setting of individual task queue.''')
+    parser.add_argument('-W', dest='__no_wait__', action='store_true',
+        help='''Do not wait for the completion of external tasks and quit SoS
+            if all tasks are being executed by external task queues. This option
+            overrides the default wait setting of task queues.''')
```

```diff
+   "source": [
+    "### `wait_for_completion`"
+   ]
+  },
+  {
+   "cell_type": "markdown",
+   "metadata": {
+    "output_cache": "[]"
+   },
+   "source": [
+    "Whether or not SoS should wait for the completion of tasks (`true/false`). By default SoS will wait for the completion of tasks submitted in a queue and complete the workflow in one run. Alternatively, SoS would quit after all tasks have been submitted to a queue with `wait_for_completion` set to `false`. The workflow can be resumed after tasks have been completed.\n",
+    "\n",
+    "This option is set to `True` by default and can be overridden by command line option `-w` (wait) or `-W` (no wait)."
+   ]
+  },
```

**Comment by BoPeng** [comment]
ok, now sos is supposed to work this way. Writing tests for these features would be troublesome though.

**Comment by gaow** [comment]
It does seem to have solved a lot issues I ran into recently! Trying it for production. Hopefully all goes well.

**Comment by BoPeng** [comment]
Unlikely to "all goes well", but at least at a better place to submit bugs. I will close this ticket for individual bug reports.
