### ISSUE TITLE
`ctrl-c` keyboard interruption cannot completely kill

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#532]
With `-w` option when I use `ctrl-c` to kill jobs the current started jobs seem to be killed but other jobs are still being submitted. I ended up having to write a while loop to keep killing until it is cleared. Do we have to use a separated `sos kill` command even when `-w` is on?

**Comment by BoPeng** [comment]
First, `-w` should be the default with local jobs, let us make sure these pieces work as expected one by one.

**Comment by BoPeng** [comment]
With my sleep example,

```
[10]
input: for_each={'i': range(10)}
task:
run:
	echo I am ${i}
	sleep ${2+i}
```

```
sos run test -s force
sos run test -s force -W
sos run test  -s force + Ctrl-C
```
work as expected.

```
sos run test -s force -J2
```
does not yet work.

**Comment by gaow** [comment]
Yes -- sorry I should have said that I did use `-J`

**Comment by BoPeng** [comment]
Try again.

**Comment by gaow** [comment]
No. I use `-J` but still `ctrl-c` wouldn't work. I looked at the patch -- it reads like merely a fix to a typo ...?

**Comment by BoPeng** [comment]
Your script can be more complex. Does my example work?

**Comment by gaow** [comment]
Yes your example does. I'll have to make a MWE for my case and post here ...

**Comment by BoPeng** [comment]
Still waiting for MWE

**Comment by gaow** [comment]
It works now for the project I was having issue with. Close it for now until I find it otherwise later.
