### ISSUE TITLE
adjust panel problem.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#540]
To reproduce:

1. Open a sos notebook with side panel
2. Adjust the side panel to, say, 1/2 of the screen
3. evaluate a cell with Ctrl-Shift-Enter
4. The notebook is narrowed. This seems to be a width calculation bug with widened side panel.

**Comment by BoPeng** [comment]
The symptom is sometimes notebook shrink then expand.

**Comment by jma7** [comment]
Is this fixed? I can't reproduce the problem.

**Comment by BoPeng** [comment]
Probably, I fixed something and have not yet been able to reproduce it.
