### ISSUE TITLE
sos remove command behavior

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#543]
Not sure if what other users think about it, but I'm getting negative feedback from my colleague who finds the remove feature confusing. It seems more intuitive to remove by default everything when one uses the system `rm` command. If one wants to keep the signature of certain steps then a version of `sos remove` can be used to make sure the signature is sufficient. I thought we had a reason not having adopted this design before but i cannot remember it. It was indeed inconvenient to keep track of all these at times, and I still often find myself doing `rm -r .sos` when things get messed up (fortunately a lot of my work does not need rerun once I harvest the results). Shall we rethink of the design of remove to see if we can make it more intuitive?

**Comment by BoPeng** [comment]
Well, I am certainly ok to any proposal...

**Comment by gaow** [comment]
I'm not sure how difficult it is to implement but here is a proposal:

1. `rm -rf FILE_OR_DIR`  should trigger rerun, as if we have executed `sos remove FILE_OR_DIR -t` and `sos remove FILE_OR_DIR -u`. It is very intuitive because users can simply delete unwanted files and rerun. This is perhaps the most common scenario when we are not happy with what we get and want to redo it.
2. Change the behavior of `sos remove FILE_OR_DIR -t` so that it only removes files without touching the signature (i guess it should modify signature in such a way it does not trigger reruns). This is useful for removing large intermediate files. 
3. Keep `sos remove FILE_OR_DIR -u` as is. This is only useful for house keeping.
4. Make it possible for `sos remove FILE_OR_DIR -s` to clean up file signatures regardless of if files exist. For example one has used `sos remove ... -t` to remove a file without triggering rerun, yet later decide to indeed trigger rerun. Then `-s` can be used remove the signature .

**Comment by BoPeng** [comment]
Clearly `rm -rf` would not touch our signatures, are you saying `sos rm FILE_OR_DIR` by default removes all files and their signatures? Note that the current design makes sure that you can externally `rm -rf FILE_OR_DIR` large files without triggering rerun.

**Comment by BoPeng** [comment]
Or do you want to keep signatures locally so that you can `rm -rf .sos` without affecting other projects? The main consideration for global signature is the possibility to switch to a database/process/daemon like signature system but I do not see that happening with remote tasks etc. In that case, keeping global signatures is not optimal because the number of small files will increase indefinitely due to signatures from completed projects.

**Comment by BoPeng** [comment]
#485 should be considered together.

**Comment by gaow** [comment]
Is it possible that we use local signature instead of global signature for now, and change the behavior when we switch to daemon-like system later? I often find myself removing the entire `~/.sos` and `.sos` just because I know for fact I've run very many experiments that I will never need them. Knowing their huge signature sits on disk is disturbing ... not sure how you cope with it :)

**Comment by BoPeng** [comment]
The signatures have been moved to local .Sos, except for files outside of project directory.
