### ISSUE TITLE
Allow the execution of workflow defined in notebooks

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#553]
Since now we have a clear definition of what constitutes a "workflow" inside a Jupyter notebook (sos cells starts with section header), it is possible to treat `.ipynb` as `.sos` files and execute it in place of where a `.sos` file is required. For example,

```
sos run myscript
```

could look for a `myscript.ipynb` file, strip workflow from it, and execute it.

**Comment by BoPeng** [comment]
This represent a major change on how sos scripts can be written. We should add a short tutorial on this.

**Comment by gaow** [comment]
I'm being horrible keeping myself up to date but I'm trying!

**Comment by BoPeng** [comment]
This will change the way we develop workflows. Basically, we can

1. run the analysis without worrying about workflow definition in Jupyter notebook. Execute lines and cells  interactively to perform the analysis or test steps.
2. convert cells to steps by adding section headers. 
3. execute complete workflow within Jupyter using `%sosrun`, or save workflow to `.sos` file. The latter is no longer needed because `sos run` can directly work with `.ipynb` file.

**Comment by gaow** [comment]
> This will change the way we develop workflows. Basically, we can

This is very appealing. I've mostly trying things out with Jupyter and copy-paste them to text. It good to know it's time to change it.
