### ISSUE TITLE
Live sos jupyter server died

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#563]
After trying to start a task and I have not been able to connect it again.

**Comment by BoPeng** [comment]
I have to manually reboot the server, which seems to be working again. But there is no hint as of why the server stopped responding.

**Comment by jma7** [comment]
It seems the server is dead again. Can't see SoS after clicking New.

**Comment by BoPeng** [comment]
Works for me right now. Did you use the rocket button at the top right corner of the homepage?

**Comment by gaow** [comment]
The future-proof (at least meant to be) link is 

https://vatlab.github.io/sos/live

I can see `SoS` after clicking `New`

**Comment by BoPeng** [comment]
@gaow Could you update the server to 0.18.2? The notebook end has many updates, especially the background mode (`&` after `%run` and `%sosrun`), and this seems to be the version that can stay for a bit longer.

**Comment by gaow** [comment]
Sure, done.

We can possibly write a `crontab` to automatically check for new pip versions (say, daily), and update. But I guess manual updates are safer. It is a one-liner to update it anyways without even having to login to the machine.

**Comment by BoPeng** [comment]
As long as the cron job does not pull master, it should be safe to install from pip. But in theory updating the server will interrupt the service even user sessions so the script should at least check if there is indeed an upgrade.

**Comment by gaow** [comment]
Does any of the materials needs to be changed (or add more material) to reflect current development of sos-notebook?

>  so the script should at least check if there is indeed an upgrade.

Certainly. I just need to figure out the best way to detect package version change on pypi without having to have them installed on the server (the server does not even have `pip` though I can install it. But would be good to avoid installting SoS related packages)

**Comment by BoPeng** [comment]
Then it might not worth the trouble. It is quick to update anyway.

**Comment by jma7** [comment]
Thanks, so the problem is my out dated browser.
