### ISSUE TITLE
sos status --html or sos console

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#564]
Current `sos status --html` is used by Jupyter `%taskinfo` to display task information. It would be nice to expand this option to display information directly in browser, especially for multiple tasks. This however goes to the task console business and we should perhaps design a dedicated interface for it.

That will be a lot of JS and we should wrap it as a dedicated project similar to what rq and celery are doing.

**Comment by gaow** [comment]
Yes although it might deserve a `later` tag as `sos status --html` is good enough for a decent summary.

**Comment by BoPeng** [comment]
Note that one can open a notebook and use

```
%taskinfo task_id -q queue
```

to manually display html output in Jupyter notebook. Because the JS code is executed separately by the frontend, the output of `--html` option is not enough to display the status in a browser, unless if we add another option (e.g. `--in-browser`, or `--full`) to add the JS script to a complete HTML output. 

The problem with this seemly easy new option is that it only handles one task so it does not work well in the majority of the usages when `sos status` is used to check status of multiple jobs, and if we are going to use a browser, something like `sos status --console` would be a much more complete solution.

**Comment by BoPeng** [comment]
`%tasks` is good enough for now.
