### ISSUE TITLE
`ctrl-c` kills all projects on the same machine

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#567]
When I run the same script with different parameters (essentially different pipelines) on my computer in the same folder, it works without any issue until I realize I made a mistake in one setting so I used `ctrl-c` to kill it. But it ended up killing both jobs. I guess it is a bug rather than a feature ... ?

**Comment by BoPeng** [comment]
Not sure what is going on. You meant that

1. You start a job in wait mode
2. You in another terminal start another job under the same directory
3. Ctrl-C another sos instance
4. Both sos instances were killed?

**Comment by gaow** [comment]
Yes, I'm still on default wait mode.

**Comment by BoPeng** [comment]
Are you running the same task from two scripts? I run

```

[10]
task:
import time
time.sleep(20)
```

```
[10]
task:
import time
time.sleep(30)
```

and kill one of them, the other is still running

```
763011dc7673cfd05420bf984ffd9abe	       00:00:24 ago	aborted
8439c4b31a08a55b5571233ccb7fddd3	       00:00:22 ago	running
```

**Comment by gaow** [comment]
No because the parameter is different. Here is the MWE:

```
parameter: k = 40
[1]
task:
python:
import time
time.sleep(${k})
```

Here is the outcome (I killed the top task but the bottom task also got killed)

![2017-04-22-09-59-22_scrot](https://cloud.githubusercontent.com/assets/917985/25305517/65eb5318-2742-11e7-87fe-d6991a018f98.png)

**Comment by BoPeng** [comment]
Interesting, the two processes obviously share something ...

**Comment by BoPeng** [comment]
The cleanup process wrongfully killed other processes ... it should have been fixed.

**Comment by gaow** [comment]
It works. Interesting you've end up deleting all those codes to fix a problem!

**Comment by BoPeng** [comment]
That is because we now have a more rigorous step/workflow worker and task management system that distinguish and manage in-house and daemonized processes so those clean up code should not be needed any more. Hopefully these zoombie processes will not come back.
