### ISSUE TITLE
Disable floating side panel?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#577]
I rarely use floating side panel and found the feature annoying. Is it ok to disable it?

**Comment by gaow** [comment]
I do not use it either, but i thought it's because I do not have a big enough screen :)

**Comment by BoPeng** [comment]
I think floating panel is useful for viewing large table/picture when you have a small screen because the panel in floating mode shares workplace with the notebook. On my 27in screen, I can drag the panel to use half of the screen so floating is not useful.

Anyway, the problem with floating is that it is too easy to switch from side to float (e.g. happens when I select text). Perhaps I can keep the float mode but make it more difficult to trigger.
