### ISSUE TITLE
Not enough error message from tasks.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#579]
The please check script message can be irritating... because we need real error messages.

**Comment by gaow** [comment]
We can display the real error message (stderr collected by Popen), but we should still point users to the script to check, because people can debug directly with those scripts. I find it quite helpful.

**Comment by BoPeng** [comment]
This patch forces all tasks to write stdout and stderr to task stdout and stderr files so that we can always get the error message from the task interface.
