### ISSUE TITLE
Keyword conflict `name`

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#580]
Here is the MWE that will fail:

```
parameter: name = 'test'
  
[test]
parameter: name = None
task:
run:
  echo ${name}

[default]
sos_run('test', name = name)
```

However if I replace `name` with `name2` it will work. I believe it is a recently introduced bug for task names that somehow completes with the potential user parameter settings.

**Comment by gaow** [comment]
A related issue is that all my `pattern = "{name}.{ext}"` stuff seem to have broken ...

**Comment by BoPeng** [comment]
Yes. `name` was recognized as a keyword and not put into task environment. SoS needs to be more clever on such things. I am having a look.

**Comment by BoPeng** [comment]
I committed a fix because it does not break any test, but the long-term solution is to improve syntax-analysis engine so not to confuse variable with keywords.

Close for now.
