### ISSUE TITLE
Auxiliary step / nested step not properly running in Jupyter

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#581]
I'm not sure about the cause of the issue but I can describe what it is. I have two files `lib.sos`:

```
[draw]
input: group_by = 'single'
depends: "${_input!n}.loglik.png"

[loglik_plot: provides = '{result}.loglik.png']
input: "${result}.txt"
task:
R:
 png("${input!n}.loglik.png")
 plot(runif(10))
 dev.off()
```

and `main.sos`

```
%include lib

[analyze]
output: 'result1.txt', 'result2.txt'
run:
  touch ${output}

[default]
sos_run('analyze+lib.draw')
```

There is no problem when I run from the command line:

```
sos run main.sos
```

However if I use Jupyter:

![2017-05-03-17-49-42_scrot](https://cloud.githubusercontent.com/assets/917985/25684788/e96ac89c-3028-11e7-8028-f782d37f77e9.png)

What am I missing here?

**Comment by BoPeng** [comment]
`%include` and `%if` stuff are not officially supported now. One of the problems is that currently all magics are ignored when workflows are constructed, so if you do 

```
%preview --workflow
```

you will see that `%include` is not part of the workflow.

**Comment by gaow** [comment]
I see. it is a bit frustrating though considering I use `%include` quite a lot. So I'll have to revert to command interface. I guess there will be plans to support them? :)

**Comment by BoPeng** [comment]
`%include` is something that I have not really explored so I inclined to exclude (at least no document) it before it matures. I suppose I can support it for now.

**Comment by gaow** [comment]
That'd be great. I find `%include` a great way to balance between interactive work and hardcore codes. I usually have a minimal main.sos file that basically are `sos_run` of workflows from many other scripts. When I migrate from command line to Jupyter I find it appealing to let the notebook display as little as possible so that readers can focus on my results. `%include` is a great way to achieve it.

**Comment by BoPeng** [comment]
I suppose you do not need to `%include` jupyter notebooks, which is supposed to work with the current convention.

**Comment by gaow** [comment]
You are right, I only `%include` SoS files.

**Comment by BoPeng** [comment]
Please close the ticket if the fixes work for you. Note that the feature is still not documented although I have a bit more confidence since you have used it more.

**Comment by gaow** [comment]
Yes it works now! I'll reopen the ticket if I later find it otherwise. Thanks a lot!
