### ISSUE TITLE
Interface for sos remove command.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#590]
#543 

There are four possible actions:

1. remove both file and signatures, trigger rerun
    * Thorough clean of files and signatures.
2. remove files but not signatures, trigger rerun
    * Can largely be achieved with `rm -rf`
3. keep files but remove signatures, trigger rerun
    * Clean `.sos`? There is no real need for this.
4. replace files with their signatures, does not trigger rerun
    * Remove large intermediate files.

### Proposal One

Only one command

```
sos remove FILE_OR_DIR
```

will replace files with their signatures.

Rational:
* Most easy to remember.
* Normal file-only removal can be done by `rm -f`
* Removal of signatures are not really needed.
* Removal of visible `.sig` files can trigger rerun

Cons:
* Can be counter-intuitive. 

### Proposal two

1. By default replace files by their signatures. This will NOT trigger rerun.
    `sos remove FILE_OR_DIR`
 
2. Remove signatures but not files (clean signatures only), this will trigger rerun.
    `sos remove FILE_OR_DIR -s`

3. Remove signatures and files (clean up everything), this will trigger rerun.
    `sos remove  FILE_OR_DIR -S`   (or `-a` for `all`)

### Proposal three

1. By default remove files and signatures. This will trigger rerun. Note that this is more consistent with what users expect, but again, `rm -f` has similar effect.
    `sos remove FILE_OR_DIR`
 
2. Remove signatures but not files (clean signatures only), for cleanup, will trigger rerun.
    `sos remove FILE_OR_DIR -s`

3. Replace files with their signatures, will not trigger rerun.
    `sos remove  FILE_OR_DIR -i`   (`-i` for `impersonate`, or `--replace`, or `-S`)

So default performs clean removal, `-i` is a special removal.

### Options

Limiting parameters to 
* Limit to tracked files (`-t`, `--tracked`)
    `sos remove  --tracked`
* Limit to untracked files (`-u`, `--untracked`)
    `sos remove  --untracked`
* Limit to files older or newer than age (`--age`)
    `sos remove --age +5d`
* Limit to files smaller or larger than size
   ```sos remove FILES --size +5G```

**Comment by BoPeng** [comment]
It makes sense to use a separate command for tasks, such as sos purge

**Comment by gaow** [comment]
I think using separate command for tasks is easier, if we let `sos -h` show help messages by groups. I really also like the remove task feature! 

For `sos remove`, if we do let `rm -f` trigger rerun we can shorten the behavior list:

1. Remove files and signatures
```
rm -rf FILE_OR_DIR
find ... -exec rm
```

2. Remove tracked files older or newer than age, or smaller or larger than, yet keep signature. 
```
sos remove FILES --size 5G / --age
```

3. Remove untracked files (-u, --untracked) (no signature)
```
sos remove FILE_OR_DIR --untracked
```

4. Remove tracked files yet keep signature
```
sos remove FILE_OR_DIR
```

5. Remove only signatures of tracked files (default to .)
```
sos remove FILE_OR_DIR -s
```

I think we may mostly use 1-3. 4 might be useful if we want to distribute pipeline yet hiding some confidential material. 5 would be very much a housekeeping feature, which I to me is less straightforward than `rm -rf .sos` if we do use local signature for project specific files #543

**Comment by BoPeng** [comment]
1. `rm -rf` to remove file and signature is not possible since signatures are not saved with files.
2. remove tracked files etc yet keep signature can be done outside of sos (although not the tracked part)

Proposals have been updated.

**Comment by gaow** [comment]
Right, I should have said "trigger rerun" instead of "removing signature". I think proposal 2 sounds great. However `-S` is essentially `rm -f` plus `-s` therefore that may not be necessary. Having a command to remove signature is less of a need now that we have signatures in local .sos. However I do run sos to operate on files outside current directory a lot, because my sos scripts are in my github repo folder while all data are outside it. So it may still be useful to have `-s`. 

I still find `rm -rf` most intuitive to trigger rerun :) Does it help to make it a bit more intuitive if we replace `remove` with `clean`?

**Comment by BoPeng** [comment]
`rm -rf` does trigger rerun with the new design. It differs from `sos remove -S` in that `sos remove` also removes signature, and provides options to select files on size although users can do that with `rm` + `find`.

Regarding `clean`,
```
sos clean FILE
```
to reduce its size does not sound very intuitive, although

```
sos clean FILE -s
```
and
```
sos clean FILE -S
```
are ok. If we are to use `clean`, we should perhaps make another option the default (perhaps `-S`), and make the replace action a special one.

**Comment by BoPeng** [comment]
Perhaps something like

```
sos zap FILE
```

is better than `clean` or `remove`. Users would be wondering what `zap` would do and learn its magic.

**Comment by gaow** [comment]
I think it sounds good to make `clean` by default the `-S` behavior. 

`zap` sounds very comic :) Perhaps `trim` or `clip` are somewhat more formal. But `clean` would be the most intuitive. In fact people would write `clean` in their makefile.

**Comment by BoPeng** [comment]
Well, zap (mosquitoes) sounds to me like magically make them disappear perhaps with some residue of ashes, which is exactly what that command is doing. :)

**Comment by BoPeng** [comment]
Documented [here]( http://vatlab.github.io/SOS/doc/documentation/User_Interface.html#subcommand-remove-16), needs testing.
