### ISSUE TITLE
Where to look for error information when submitted job fails and no `err` file generated?

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#596]
I'm running a very simple test, using `host.yml` configured as:

https://github.com/vatlab/SOS/wiki/Summary-of-supported-task-queues-and-servers#slurm

The master process on my computer keeps waiting but I know for fact it has failed when I use `sacct` to check for status on the cluster. 

```
       JobID    JobName  Partition    Account  AllocCPUS      State ExitCode 
------------ ---------- ---------- ---------- ---------- ---------- --------
27174409.ba+      batch           gaow        20     FAILED      1:0 
```

Since no `err` file was generated I do not know where to look. It is entirely possible that my configuration has an error (in which case it would be great if you could point it to me!!). But in general how do I debug this one? 

My test script is simply:

```
[default]
output: 'done.txt'
task:
run:
  sleep 5
  echo completed > ${output}
```
and I run via sos command line. Thanks!

**Comment by gaow** [comment]
One apparent observation is the JobName is not properly set. But I cannot see how I did it wrong in my YML, just by looking at the docs.

**Comment by BoPeng** [comment]
SoS assumes standard output and error be located at `~/.sos/tasks/task_id.err` (on remote server) etc so your `-o` setting should be `${home_dir}/.sos/tasks/${task}.out`.  You also seems to put `walltime` in config, not as task options, not sure how it plays out.

I would first check `~/.sos/tasks/task_id.sh` to see if the job submission script is correct (option `submit_cmd_output`). Then the sos output should be given `job_id` in output if the job is correctly submitted. Otherwise sos cannot query job status (but that is not important because sos checks its own status).

I would also try to manually submit task and see if the command is correct (sos should have command in debug message).

**Comment by BoPeng** [comment]
Also, what is the status of task from command line or Jupyter? If it is running or the icon is rotating, it means tasks is running (with live pulse thread). Also, `sos status -v4` should try to get pbs status using the query command you provide.

**Comment by gaow** [comment]
Oh no I wrote a long debug list doing everything you suggested. Then I somehow shut the browser and lost it all!!!

Long story short, everything works and all debug procedure you suggested did not find any issues. But I'm glad I see how it is done now. Manual submission works. I then tried again from my desktop using `-v4`, and it works ... 

The only issue remaining is the mystery of `job_name`. According to the documentation if I do:

```
name: "${step_name}_${_index}"
...
job_template: |
...
      #SBATCH --job-name=${job_name}_${task}
```
I should get `default_0_taskid`. However I got `taskid_taskid` instead. Looks like the default job_name is taskid, which is cool to me. I just want to know how to overwrite it. I think it might be a bug?

**Comment by BoPeng** [comment]
`name` is a `task` option, what happens for

```
      #SBATCH --job-name=${job_name}_${task}
```
is that `task: name='${step_name}_${_index}'` determines `job_name` so your `name` is ignored.

So in the end you should first check `sos status -q queue` to check the status of the task, see if it matches PBS status, then see if the Jupyter icon correctly reflects the status.

**Comment by gaow** [comment]
I see. So with the exception of `name`, all other task options such as `walltime` can have a default value in the configuration file -- just like snakemake. 

I'm still using commandline more than Jupyter to submit jobs, because there was still rough edges. Are you comfortable with Jupyter interface as of now? The last time I tried was a few weeks ago so things might have changed a lot.

**Comment by BoPeng** [comment]
I use the Jupyter interface daily now and would consider it usable for sure.

**Comment by gaow** [comment]
Should I close the issue? I was able to follow the steps in documentation completely on this page:

http://vatlab.github.io/SOS/doc/documentation/External_task.html

Except that I tried to be creative by setting some "defaults" in the configuration. All worked except for `name`. But `job_name` does have a nice default to `task_id`. I'm thinking if we should document the usage (or make a comment) of setting default within host configuration file. It will make SoS scripts less wordy in many cases.

**Comment by gaow** [comment]
In fact can we make `task: name = ..` by default to be `${step_name}_${_index}`? As said on the wiki it is only used to set job name. It makes sense to have this default rather than the `task_id` default. It reads a lot better on the cluster.

**Comment by BoPeng** [comment]
Perhaps we should make `step_name` etc available also to the template so that users can use other variables in addition to `job_name` (default to `task` and value of option `name`).

Also, there is by design no `mem` and `walltime` although you seem to get round and did it. Perhaps we should do something about this.

**Comment by BoPeng** [comment]
Did you figure out why sos still returned running (or some other state) when the job has failed?

**Comment by gaow** [comment]
> Also, there is by design no mem and walltime although you seem to get round and did it. Perhaps we should do something about this.

Ok that'd kill my creativity ... I just hope there is a way to set defaults on all these quantities in host.yml yet still have the flexibility to modify it with `task: ...`. As you can perhaps tell from my configuration, I have access to a single remote linux machine and I will use the same resource request for most of my runs. Have to set these defaults inside SoS script sounds a lot of trouble and not good for reproducibility when shared with others who does not have access to that computer.

**Comment by gaow** [comment]
> Did you figure out why sos still returned running (or some other state) when the job has failed?

No, because I could not reproduce it now. But I'm sure it will come back ... I'll open a new window and use `sos status` to check explicitly when that happens.

**Comment by BoPeng** [comment]
I think a reasonable thing to do without referring to your configuration is to 

```
walltime = '6:00:00'
job_template = |
    #PBS walltime=${walltime}
```
so the template is exposed to a dictionary with `walltime`, which becomes the default value if users do not specify `walltime`. Then the value would be overridden with the task option `walltime.

**Comment by BoPeng** [comment]
Yes. You can always check the status of a job on a separate terminal, even remotely from another machine (with `hosts.yml`).

**Comment by BoPeng** [comment]
You can close the ticket and create separate ticket for specific issue later.

**Comment by gaow** [comment]
Sorry I'm now a bit confused. What you suggested here https://github.com/vatlab/SOS/issues/596#issuecomment-300339072 is exactly what I did. It worked for everything else except for `name` which I suggest we change the default from `task_id` to `${step_name}_${_index}`. 

Then you suggested here https://github.com/vatlab/SOS/issues/596#issuecomment-300337348 that we "do something to it". That sounds like you want to disable them because by design they should be `task`, not in config. I was asking not to "do something to it" but rather enhance it so that `name` has a better default.

**Comment by BoPeng** [comment]
Sorry for the confusion. SoS provides default `jobname` (`task` ID) so users do not have to specify option `name`. On other options such as `walltime`, sos does not provide any default and if a template file requires it and there is no corresponding task option, sos would fail. It makes sense to define default `walltime` for some hosts. A simple `walltime` definition in `hosts.yml` might do but this is not something that we have tested or documented.

**Comment by gaow** [comment]
I see. I'm not sure if my user case is good enough as a test. How about changing default job_name to step_name + index? Because otherwise `${task}` will produce exactly the same information as default `job_name`. This redundancy is awkward.

**Comment by BoPeng** [comment]
ok. The code is [here](https://github.com/vatlab/SOS/blob/master/sos/PBS/sos_task.py#L85), you can make the change and test if it works for you.

**Comment by BoPeng** [comment]
And [this](https://github.com/vatlab/SOS/blob/master/sos/PBS/sos_task.py#L100) looks like a bug because if users put `walltime` in config file, it would override `walltime` etc from task options. Could you confirm this? If so, I think we should remove that line to before 80, basically allowing task options to override config values.

**Comment by gaow** [comment]
I've changed the codes and tested. Does it look fine 0f4343eae127e0a7d77a489b893d1edb63e90611 ? It work as expected though there is a separate issue that i'll open another ticket.

**Comment by BoPeng** [comment]
Yes. It looks fine. I will document the change.
