### ISSUE TITLE
Thoughts on paths configuration in hosts.yml

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#597]
Right now we require all hosts having the same set of paths to construct `path_map`. There are two possible improvements:

1. Create `path_map` only for matched `paths` and ignore others. That is to say, if a local machine only with `home` if mapped to another machine with `home` and `projects`, the `path_map` would be local to remote `home`. The reverse can trigger an error because files under `projects` cannot be mapped.

2. Disallow paths outside of `paths` to make `paths` and `export` item which makes sense because SoS supposedly does not know how to map paths outside defined `paths` definition to remote host. The current behavior works like a default root to root map that would be used when other maps fail.

**Comment by gaow** [comment]
I understand and fully agree on 1. But I do not understand 2. Perhaps needs rephrase ... ?

**Comment by BoPeng** [comment]
For two, basically if  the hosts file has
```
paths:
    home: /home/user
```

and the script has

```
input: '/homes/user/proj/a.txt'
depends: '/resource/hg19'
```

we know how to translate `/homes/user/proj/a.txt` but we do not know how to translate `/resource/hg19`. The current behavior is that `/resource/hg19` is not translated and pass directly to remote host, which might or might not have `/resoruce/hg19`. The error would be detected only when the translated script is executed.

In 2 I was proposing that we raise an error for `/resource/hg19`, indicating that sos does not know how to translate the path. This would detect the problem earlier, but we also run into the possibility that users know what they are doing and it is ok to keep the path.

**Comment by BoPeng** [comment]
I suppose as usually, it would make sense to raise warnings on non-translatable paths.

**Comment by gaow** [comment]
I see. I agree a warning is the most we can do. For quick-dirty implementation we'll ignore warnings anyways. When we are bothered by warnings it means we see it repeatedly so it's no longer quick-dirty, and users should invest a minute to formalize it.
