### ISSUE TITLE
`walltime` parsing doesn't work for slurm

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#598]
My SoS looks like:

```
[default]
output: "test.done"
task: walltime="02:00:00"
run:
...
```

and my PBS job is generated:

```
#!/bin/bash
#SBATCH --time=7200
...
```
So `walltime` is translated to seconds. However my system does not like it:

```
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)
DEBUG: Check output of ssh -q gaow@midway.rcc.uchicago.edu -p 22 "bash --login -c 'sbatch ~/.sos/tasks/09e506a693f315967ecda61e9018f344.sh'"  failed: Command 'ssh -q gaow@midway.rcc.uchicago.edu -p 22 "bash --login -c 'sbatch ~/.sos/tasks/09e506a693f315967ecda61e9018f344.sh'" ' returned non-zero exit status 1
INFO: 09e506a693f315967ecda61e9018f344 submitted to mstephens with job id None
```

If I change it to `HH:MM:SS` it will work. So we perhaps should check for walltime format yet does not try to translate? Also the last line of the INFO says:

```
INFO: 09e506a693f315967ecda61e9018f344 submitted to mstephens with job id None
```
But DEBUG would suggest an error. Maybe want to improve the error message here ..

**Comment by BoPeng** [comment]
This is documented [here](http://vatlab.github.io/SOS/doc/documentation/External_task.html#Option-walltime-181) but I should perhaps update the example. Basically sos accepts `walltime` in both seconds (integer) and `HH:MM:SS` (string) and convert it to seconds for consistency. Then for each task queue, it should be converted to an queue-specific format, something like

```
walltime=${walltime/3600:02d}:${walltime%3600/60:02d}:${walltime%60:02d}
```
I hesitated

1. if we should provide a function to make it easy to convert to the most widely used format. 
2. if we should use `HH:MM:SS` as default.

The reason for integer `walltime` is for

```
#PBS queue=${'short' if walltime < 3600 else 'medium'}
```
but I suppose users can also do

```
#PBS queue=#{'short' if int(walltime.split(':')[0]) < 6 else 'medium'}
```
if we chose to use `HH:MM:SS` as internal format.

**Comment by BoPeng** [comment]
```
INFO: 09e506a693f315967ecda61e9018f344 submitted to mstephens with job id None
```
means something wrong with the `submit_cmd_output` setting because sos could not extract job ID from it...

**Comment by gaow** [comment]
`submit_cmd_output` works well when job submission is successful, which is not the case in my example. The INFO line was not aware thus still give None for an answer.

**Comment by BoPeng** [comment]
I see, the error handling code is [here](https://github.com/vatlab/SOS/blob/master/sos/PBS/sos_task.py#L147), not sure how to improve it with your case.

**Comment by gaow** [comment]
I see. `HH:MM:SS` is supported in all systems, right? Now with `config` dictionary updated later, the `${walltime/3600:02d}:${walltime%3600/60:02d}:${walltime%60:02d}` syntax wouldn't work unless we set default walltime to seconds. 

In the documentation it says "SoS automatically converts this option to an integer and formats it appropriately for different task engines.". It did not ring a bell until now ... 

Knowing the solution to it I can work it out either way. Now I can see the appeal to have it in integer if long/short queue matters. In our cluster there is no long/short queue distinction.

**Comment by BoPeng** [comment]
The default walltime should be set in integers for this reason. 

I now tend to think we should use the `HH:MM:SS` internally because it is the widely accepted format. Let me make the change. Users can always convert `HH:MM:SS` to integer if needed, which is actually easier than converting seconds to `HH:MM:SS`.

**Comment by gaow** [comment]
Sure! I'm totally cool with HH:MM:SS as default. Converting to seconds is an easy one-linear.

This is what happens with the INFO line:

```
>>> from sos.pattern import extract_pattern
>>> tpl = "Submitted batch job {job_id}"
>>> output = "Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)">>> res = extract_pattern(tpl, [output])
>>> res
{'job_id': [None]}
```

In fact regardless of output, `res` will always have `None` unless the correct pattern is matched. But I see it a separate bug. The fundamental issue is that there is no way to tell in this section of code if the output message generates None ID due to bad `submt_cmd_output` or due to failed submission. We should be able to check return code for failed submission elsewhere and handle it there, right?

**Comment by BoPeng** [comment]
This might have something to do with `ssh` because the command is executed through `ssh`. If `ssh` raises an exception [the code](https://github.com/vatlab/SOS/blob/master/sos/hosts.py#L482) should catch it.

If it is not easy to fix ssh, we should just give a proper error message for any `None` output.

**Comment by gaow** [comment]
I guess there is a return status we can use? `Popen` does have it. From the error message, clearly return status is 1.

**Comment by BoPeng** [comment]
No. `subprocess.check_output` will raise an exception when the return value if not 0. So either your `sbatch` command did not return non-zero, or `ssh host sbatch` did not return non-zero when `sbatch` returned non-zero. The exact command is [logged](https://github.com/vatlab/SOS/blob/master/sos/hosts.py#L493) so you can run it from command line and check `$?`.

**Comment by gaow** [comment]
Ok the error message I previously posted was too long and the code block hide the key message ... That's why we were not on the same page. Pasting it plain text here so it can be seen:

'''
DEBUG: Check output of ssh -q gaow@midway.rcc.uchicago.edu -p 22 "bash --login -c 'sbatch ~/.sos/tasks/09e506a693f315967ecda61e9018f344.sh'"  failed: Command 'ssh -q gaow@midway.rcc.uchicago.edu -p 22 "bash --login -c 'sbatch ~/.sos/tasks/09e506a693f315967ecda61e9018f344.sh'" ' returned non-zero exit status 1
'''

So it does "say" it returns none zero but somehow `check_output` doesnt capture?

**Comment by BoPeng** [comment]
OK, [this line](https://github.com/vatlab/SOS/blob/master/sos/hosts.py#L494) is problematic. I do not quite remember the reason, but it seemed that I tried to be more tolerant to the failure of remote commands. Please change this line to `raise` and we will see what happens.

**Comment by BoPeng** [comment]
It might affect the logic of some other places (e.g. sos might expect an empty string if `sos status` fails) but let us handle downstream exception properly if that happens.

**Comment by gaow** [comment]
Maybe being more tolerant is a good idea in general, but for submit operation we want to be strict?
 How about we add a parameter to the function so that we can control for the level of stringency? Otherwise you'll still have to try-catch and return empty string in a number of other places ...

**Comment by BoPeng** [comment]
Being tolerant downstream can be good but this is a general remote call function so it is better to pass the exception on. If you make the change, also change [here](https://github.com/vatlab/SOS/blob/master/sos/hosts.py#L181) for local `check_output`.

**Comment by gaow** [comment]
Sure. I'll try it tomorrow as I've already shut down my Linux desktop ...

**Comment by gaow** [comment]
Sorry just getting to it but it seems you've added raise already ... will test with a failiure case and see.
