### ISSUE TITLE
Multiple global sections?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#603]
There is current a restriction on there can be only one global section and I do not see a compulsive reason why this should be case. I mean, we can simply join multiple global sections.

In practice, this allows us to define a global section whenever we see a need to define a new global function, and do not have to define everything in the only global section in the script.

**Comment by gaow** [comment]
+1 to this. I'm already a bit tired dumping back and forth from/to the top of the doc to make changes!
