### ISSUE TITLE
String interpolation not fully functional for step options

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#604]
Here is the HWE:

```
[1]
input: '/tmp/1.txt', pattern="{name}.{ext}"
output: expand_pattern('{name!b}')
run:
  echo ${output}
```

Then it would say:

```
INFO: input:    ['/tmp/1.txt']
...
INFO: output:   ['{name!b}']
```
So the `!` wouldnt work here. Alternative implemetation is trivial on my end. I just want to make sure this behavior is intended.

**Comment by BoPeng** [comment]
`{}` is for pattern matching, you should use `"${name!b}"` is you would like to use string interpolation.

**Comment by gaow** [comment]
... my bad. Sorry :)
