### ISSUE TITLE
Location of side panel buttons.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#607]
They are currently to the right of input prompt, not a very good place but I do not have any better idea. We may move them to another location, or remove them completely if they are not proven to be useful.

**Comment by jirikuncar** [comment]
@BoPeng I am using the kernel select boxes. I agree that sometimes they interfere with the input, however I find them useful for quick kernel switching.

**Comment by BoPeng** [comment]
The select box was too wide (40%?) so it interfered with code input even when the text has not reached the box. I have changed the box to `40pt` recently which should alleviate the problem. I am not sure if sos should provide an option to move the language selection box outside of the input area because I have found that actual code (especially the first line) rarely reach the selection box, and users should switch to markdown to remove the box before inputting markdown text.

**Comment by BoPeng** [comment]
Also note that this ticket refers to the [new buttons on the side panel](http://vatlab.github.io/SOS/img/JupyterNotebook.png), which provides shortcuts to magics such as `%toc` and `%tasks`, and a way to re-execute previously executed statements in code cell.

**Comment by BoPeng** [comment]
I would propose that

1. We remove the existing buttons.
2. We add a "dropdown" button to the end of the input cell.
3. The dropdown is separated into two parts,
    * `%toc`
    * `%preview --workflow`
    * `%tasks`
    *  -------- (separator)
    * history of commands

There is one more step to access the shortcuts but we already have a keyboard shortcut for `%toc`, and I am not sure if `%preview --workflow` and `%tasks` are frequently used, especially when `%tasks` is usually followed by options `-q` (query) and `-s` (status), and it is awkward to display tasks in the side panel. Perhaps we can add a `%help` or `%soshelp` magic to display help messages in side panel.

**Comment by BoPeng** [comment]
[The updated interface](http://vatlab.github.io/SOS/doc/media/JupyterNotebook.png) is a lot less intrusive.
