### ISSUE TITLE
String interpolation from within dictionaries

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#609]
I have a dictionary say `CONF` that looks like:

```
{'factors': 1: "a.rds", ...}
```

And I want to be able to use it in my pipeline like:

```
parameter: F = [1,2,3...]
input: group_by = 'single', for_each = ['F']
R:
readRDS(${CONF['factors'][_F]!r})
```

Currently SoS parser would deem it syntax error. How can I use dictionary-like parameter here?

**Comment by BoPeng** [comment]
What errors do you get?
```
CONF = {'factors': {1: "a.rds"}}
_F = 1

print("${CONF['factors']}")
print("${CONF['factors'][_F]}")
print("${CONF['factors'][_F]!r}")
```

**Comment by gaow** [comment]
Oops my bad. I used `CONF` but I should use of `CONFIG` as it is dictionary of `-c` ... I always make `CONF` vs `CONFIG` mistake and did not recognize it because I was looking for `invalid syntax` .... (which technically is!)

```
ERROR: 08fb4220462416bb7539d29f8f3e50e0 failed with InterpolationError error invalid syntax (<string>, line 1):
CONF['factors'][_F]!r}"), control = control)
```
