### ISSUE TITLE
Support multiple instances (including remote instance) of the same kernel

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#614]
[These kernels](https://github.com/jirikuncar/sos-remote-ikernel/blob/master/sos_remote_ikernel.py) wrap around the [sos_R](https://github.com/vatlab/SOS/blob/master/sos/R/kernel.py#L237) and sos_Python kernel to redefine background colors. I suppose it should be pretty easy to make these configurable, something like

```
sos config --global --set language.R.background_color #FDEDEC
```
to set a key in `~/.sos/config.yml`, and the `ir` kernel checks its value before using the default.... The color cannot be used for sos convert though.

**Comment by jirikuncar** [comment]
It's not only about language, but also about a kernel, since one can have multiple kernels for one language. I was hoping to have something like a "color pallet" for a language if a specific color was not assigned for a given kernel.

**Comment by BoPeng** [comment]
So it would be something like the following? Of course we can have default `color` and `name` for new kernels.

```
%use R --new --name R2 --color #FFAACC
```
I have not figure out how [remote_ikernel](https://pypi.python.org/pypi/remote_ikernel) works though?

**Comment by jirikuncar** [comment]
@BoPeng the configuration of remote ikernel is not complicated but it requires some prior knowledge of your system [1]. For simplicity one can create a new local kernel with different python version (or with SageMath). Then the complication comes. If SoS would instead of wrapping kernels with serializers, provided generic language wrappers, which could be change on per-kernel-basis, we would safe ourselves some extra work do in sos-remote-ikernel.

```
%use  # magic
<name_of_jupyter_kernel>  # as defined in jupyter kernelspec list
--serializer sos.serializer.Python3  # default serializer should be chosen based on language from kernel.json
--color #FFAACC  # language default + scale based on number of kernels with same language
```

--
[1] https://gist.github.com/jirikuncar/e4958e2c386e070d53b23985e28a4a49

**Comment by BoPeng** [comment]
Could you clarify how should sos start or connect to an existing remote kernel? I think there can be two new features:

1. connect to an existing remote kernel. Something like
   ```
    %use R_remote --port some_port --serlializer sos.R.sos_R
   ```
   to wrap an existing remote kernel with language interface  `sos.R.sos_R`.

2. Start a new instance of a local kernel
    ```
    %user R_local  --serlializer sos.R.sos_R --kernel ir
    ```

I am not sure how `remote_ipython` falls into these. Actually, it is possible for the `%use` magic to ssh to a remote server to start a kernel if properly configured.

**Comment by jirikuncar** [comment]
ad 1. One needs/should to create/configure the kernel first (see [example](https://gist.github.com/jirikuncar/e4958e2c386e070d53b23985e28a4a49#remote-ikernel)).

```
%use R_slurm --serializer sos.R.sos_R
```
should be enough (of course with possible `--color pink`).

ad 2. with correct config there is no difference between local and remote kernel if no local files are  used. `%use` should not create new configuration, but simply spawn a new instance of existing kernel configuration.

**Comment by BoPeng** [comment]
@jirikuncar 

OK, here is the proposed interface

```
usage: %use [-h] [-k KERNEL] [-l LANGUAGE] [-c COLOR]
            [-i [IN_VARS [IN_VARS ...]]] [-o [OUT_VARS [OUT_VARS ...]]]
            [name]

Switch to a specified subkernel.

positional arguments:
  name                  Displayed name of kernel to start (if no kernel with
                        name is specified) or switch to (if a kernel with this
                        name is already started). The name is usually a kernel
                        name (e.g. %use ir) or a language name (e.g. %use R)
                        in which case the language name will be used. One or
                        more parameters --language or --kernel will need to be
                        specified if a new name is used to start a separate
                        instance of a kernel.

optional arguments:
  -h, --help            show this help message and exit
  -k KERNEL, --kernel KERNEL
                        kernel name as displayed in the output of jupyter
                        kernelspec list. Default to the default kernel of
                        selected language (e.g. ir for language R.
  -l LANGUAGE, --language LANGUAGE
                        Language extension that enables magics such as %get
                        and %put for the kernel, which should be in the name
                        of a registered language (e.g. R), or a specific
                        language module in the format of package.module:class.
                        SoS maitains a list of languages and kernels so this
                        option is only needed for starting a new instance of a
                        kernel.
  -c COLOR, --color COLOR
                        Background color of the new kernel, which overrides
                        the default color of the language.
  -i [IN_VARS [IN_VARS ...]], --in [IN_VARS [IN_VARS ...]]
                        Input variables (variables to get from SoS kernel)
  -o [OUT_VARS [OUT_VARS ...]], --out [OUT_VARS [OUT_VARS ...]]
                        Output variables (variables to put back to SoS kernel
                        before switching back to the SoS kernel
```

Usage:

| command | effect |
|---|---|
| `%use R`| start `R` with kernel `ir`|
| `%use ir` |start `R` with kernel `ir`|
| `%use R --color red` | new color|
| `%use R --kernel ir_remote` | fail, need to use a different name |
| `%use R2`|  fail, unrecognized name|
| `%use R2 --kernel ir_remote`| starts a new remote kernel without language support|
| `%use R2 --kernel ir_remote --language R` |starts a new remote kernel with langauge R|
| `%use R2 --kernel ir_remote --language package.module:another_R`| starts a new kernel with another language interface|
| `%use R2 --language package.module:another_R`| starts a new kernel with another langauge interface using local kernel R|

The actual implementation needs a lot of internal changes and I am not sure how soon it can be done.

**Comment by BoPeng** [comment]
@jirikuncar I have implemented this feature and documented it [here](http://vatlab.github.io/SOS/doc/documentation/Notebook_Interface.html#%use-141). It appears to be working all right but I have not really tested it with remote_ikernel... please feel free to let me know if you notice any problem.

If sos works well with remote_ikernel, could you please write a short tutorial on how to setup ikernel and sos to work with remote kernel? We have a tutorial section on the documentation page that needs many such tutorials. Thanks!

**Comment by jirikuncar** [comment]
@BoPeng thank you. I have tested it and it works for me. 

--
But now, I see the position of select box really annoying. There was some other issue about it which is closed now.

**Comment by jirikuncar** [comment]
@BoPeng I have a problem with kernels being launched multiple times.
![image](https://cloud.githubusercontent.com/assets/189798/26395648/00730fa6-4071-11e7-9d56-7ec8e85c39fa.png)

It's also a bit annoying that one always needs to define a language argument when using `%use` magic otherwise the `%get` and `%put` doesn't work.

**Comment by jirikuncar** [comment]
After restarting kernel and re-running the cells, I have got:
```
Traceback (most recent call last):
  File "/Users/jirka/.virtualenvs/sos/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/jirka/.virtualenvs/sos/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/Users/jirka/.virtualenvs/sos/lib/python3.6/site-packages/sos-0.9.7.4-py3.6.egg/sos/jupyter/kernel.py", line 1770, in do_execute
    user_expressions=user_expressions, allow_stdin=allow_stdin)
  File "/Users/jirka/.virtualenvs/sos/lib/python3.6/site-packages/sos-0.9.7.4-py3.6.egg/sos/jupyter/kernel.py", line 1924, in _do_execute
    if self.find_kernel(args.cell_kernel)[0] != self.find_kernel(self.kernel)[0]:
  File "/Users/jirka/.virtualenvs/sos/lib/python3.6/site-packages/sos-0.9.7.4-py3.6.egg/sos/jupyter/kernel.py", line 603, in find_kernel
    raise ValueError('No pre-defined subkernel named {} is found. Please define it with one or both of parameters --kernel and --language'.format(name))
ValueError: No pre-defined subkernel named new_Python is found. Please define it with one or both of parameters --kernel and --language
```

**Comment by jirikuncar** [comment]
The color of the same kernel with default name is being affected when new instance of same kernel with different name is created:

![image](https://cloud.githubusercontent.com/assets/189798/26396984/1aa75c5c-4075-11e7-8b28-60fd90ce3488.png)

**Comment by BoPeng** [comment]
The problems were caused by moving the dropdown box out of cell toolbar (so that we could use cell toolbar normally #634 ) and managing them by ourselves. I have fixed some of them last night.

**Comment by BoPeng** [comment]
> It's also a bit annoying that one always needs to define a language argument when using %use magic otherwise the %get and %put doesn't work.

SoS needs to know what language the remote kernel is to perform `%get` and `%put`. Not sure how the kernel is started, but supposedly if a known kernel is specified without language (e.g. `python2`, `python3` using command `%use newP3 -k python3`), the default language for that kernel is used. This is not possible for remote kernels because all we can see are kernel name and spec path.

**Comment by BoPeng** [comment]
Previously the kernel would always have the most updated kernel list, but now a newly restarted kernel would need a kernel list from the frontend... this should have been fixed.

**Comment by BoPeng** [comment]
I believe all the reported problems have been fixed. Please confirm.

**Comment by jirikuncar** [comment]
@BoPeng I can confirm that the problem has been solved for me. Thanks!
