### ISSUE TITLE
Still attempting to sync from remote with `-W` 

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#617]
I'm running jobs on remote server involving large files so I do not want any of it to get sync-ed with my computer. `-W` seems the option for it. However I'm getting the following: 

```
INFO: Executing PFA_summary_2: 
INFO: input:    [~/Documents/PFA/Monocle/GSE525....R1.loglik, ...] (60 items)
INFO: 581a539d111b2074244f5b1768fe4a96 already completed
ERROR: Failed to copy /scratch/midway2/gaow/PFA/Monocle/GSE52529_fpkm_matrix.voom.K4.F0.gz from midway2: Failed to copy /scratch/midway2/gaow/PFA/Monocle/GSE52529_fpkm_matrix.voom.K4.F0.gz from midway2
```

What happened was that I manually removed `GSE52529_fpkm_matrix.voom.K4.F0.gz` via `rm -f` on the remote because the result is incomplete. I then run sos again from my computer with `-W`. I expect there will be a rerun on the remote's end. However instead I see  `581a539d111b2074244f5b1768fe4a96 already completed` and an attempt to copy data back. What am I missing here?

**Comment by BoPeng** [comment]
Is the `.gz` file defined in `output` or `from_host`? Not quite sure what is going on but if the `.gz` file is part of the `output` definition, the status of the task should be `result-mismatch` and would rerun.

**Comment by gaow** [comment]
Those files are defined in `output` (I always try to avoid `from_host/to_host` but it is a matter of style). I've deleted those files on the remote and I do expect a rerun. It looks the absence of those files did trigger something as sos at least attempted to run task `581a539d111b2074244f5b1768fe4a96`, as opposed to use saved signature. However it concludes the task has completed, and still tries to `copy` file to local machine. This is not very consistent with what `-W` option is there for.

**Comment by BoPeng** [comment]
So this can be a signature detection issue. I will try to remove a remote output file and test.

`-W` is for `no-wait` and has nothing to do with this. You are looking for `sos execute task_id -s force -q queue` if you want to rerun this particular task.

**Comment by BoPeng** [comment]
`to_host`, `from_host` is not only about style as they can be used to copy entire directories without tracking them.

**Comment by gaow** [comment]
Ok I think we are talking about 2 issues here:

1. Removing remote output didn't trigger rerun: for my particular case I get `<task_id> already completed`
2. With `-W` there should be no attempt to sync data back to my computer but the error message seems to indicate there is a `copy` action going on

Am I understanding the issue correctly?

By "style" I mean I often have a "resource prep" workflow that ensures local and remote in sync for untracted resource data before I even start executing the pipeline. Perhaps my pipelines are not complicated enough to have to use `from/to_host`. I find sometimes there is a lot going on under `task` so I try to make sure there is minimal configurations there.

**Comment by BoPeng** [comment]
No `-W` is for sos to quit without waiting for the completion of tasks. You cannot put the file in `output` if you do not want it to be copied.

I understand the need for pure-remote execution and was thinking of remote targets ( #475 ) but have not got around to it yet.

**Comment by BoPeng** [comment]
I suppose you can send me output of `sos execute task_id -s force -q queue -v4`.

**Comment by gaow** [comment]
I see. Then it becomes a feature request to run pure-remote execution, because there is no way I can fit all those data back to my machine :)

BTW documentation is a bit misleading here:

http://vatlab.github.io/SOS/doc/documentation/External_task.html#-w-and--W

debug message to follow.

**Comment by gaow** [comment]
Run without `-s force`, basically saying the same thing:

```
sos execute 581a539d111b2074244f5b1768fe4a96 -q midway2 -v4
DEBUG: Executing command ssh -q gaow@midway.rcc.uchicago.edu -p 22 "bash --login -c 'sos status  -v 2  --start-time '" 
INFO: 581a539d111b2074244f5b1768fe4a96 already completed
DEBUG: Put results for ['581a539d111b2074244f5b1768fe4a96']
DEBUG: scp -P 22 -p -q gaow@midway.rcc.uchicago.edu:.sos/tasks/581a539d111b2074244f5b1768fe4a96.* /Users/gaow/.sos/tasks
DEBUG: mkdir -p /Users/gaow/Documents/PFA/Monocle; rsync -av -e 'ssh -p 22' gaow@midway.rcc.uchicago.edu:/scratch/midway2/gaow/PFA/Monocle/GSE52529_fpkm_matrix.voom.K4.F0.gz "/Users/gaow/Documents/PFA/Monocle"
  File "/anaconda/lib/python3.6/site-packages/sos-0.9.7-py3.6.egg/sos/__main__.py", line 1862, in main
    args.func(args, workflow_args)
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/sos-0.9.7-py3.6.egg/sos/hosts.py", line 364, in _receive_from_host
    raise RuntimeError('Failed to copy {} from {}'.format(source, self.alias))
RuntimeError: Failed to copy /scratch/midway2/gaow/PFA/Monocle/GSE52529_fpkm_matrix.voom.K4.F0.gz from midway2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/sos-0.9.7-py3.6.egg/sos/__main__.py", line 1862, in main
    args.func(args, workflow_args)
  File "/anaconda/lib/python3.6/site-packages/sos-0.9.7-py3.6.egg/sos/__main__.py", line 673, in cmd_execute
    res = host.retrieve_results(args.tasks)
  File "/anaconda/lib/python3.6/site-packages/sos-0.9.7-py3.6.egg/sos/hosts.py", line 733, in retrieve_results
    return {task: self._host_agent.receive_result(task) for task in tasks}
  File "/anaconda/lib/python3.6/site-packages/sos-0.9.7-py3.6.egg/sos/hosts.py", line 733, in <dictcomp>
    return {task: self._host_agent.receive_result(task) for task in tasks}
  File "/anaconda/lib/python3.6/site-packages/sos-0.9.7-py3.6.egg/sos/hosts.py", line 557, in receive_result
    self._receive_from_host(job_dict['_output'])
RuntimeError: Failed to copy /scratch/midway2/gaow/PFA/Monocle/GSE52529_fpkm_matrix.voom.K4.F0.gz from midway2: Failed to copy /scratch/midway2/gaow/PFA/Monocle/GSE52529_fpkm_matrix.voom.K4.F0.gz from midway2
ERROR: Failed to copy /scratch/midway2/gaow/PFA/Monocle/GSE52529_fpkm_matrix.voom.K4.F0.gz from midway2: Failed to copy /scratch/midway2/gaow/PFA/Monocle/GSE52529_fpkm_matrix.voom.K4.F0.gz from midway2 
```

**Comment by gaow** [comment]
Running with `-s force` there is a bug:

```
sos execute 581a539d111b2074244f5b1768fe4a96 -q midway2 -v4 -s force
DEBUG: Executing command ssh -q gaow@midway.rcc.uchicago.edu -p 22 "bash --login -c 'sos status  -v 2  --start-time '"
  File "/anaconda/lib/python3.6/site-packages/sos-0.9.7-py3.6.egg/sos/__main__.py", line 1862, in main
    args.func(args, workflow_args)
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/sos-0.9.7-py3.6.egg/sos/__main__.py", line 1862, in main
    args.func(args, workflow_args)
  File "/anaconda/lib/python3.6/site-packages/sos-0.9.7-py3.6.egg/sos/__main__.py", line 658, in cmd_execute
    host.submit_task(task)
  File "/anaconda/lib/python3.6/site-packages/sos-0.9.7-py3.6.egg/sos/hosts.py", line 726, in submit_task
    return self._task_engine.submit_task(task_id)
  File "/anaconda/lib/python3.6/site-packages/sos-0.9.7-py3.6.egg/sos/sos_task.py", line 999, in submit_task

   elif task_id in env.config['resumed_tasks']:
KeyError: 'resumed_tasks'
ERROR: 'resumed_tasks
```

**Comment by BoPeng** [comment]
Try again, `resumed_tasks` was unavailable for `sos execute`.

**Comment by gaow** [comment]
Now it works with `-s force` and submitted succesfully. In the end it gives an ineresteing message:

```
DEBUG: Executing command ssh -q gaow@midway.rcc.uchicago.edu -p 22 "bash --login -c 'squeue --job 27463986'" 
TRACE: STATUS 581a539d111b2074244f5b1768fe4a96    submitted

DEBUG: result-mismatch: 5 completed: 66 aborted: 56 submitted: 1
```

Although I do not understand what `aborted` is -- jobs in `wait` mode that got cutoff? Then I immediately typed `sos resume` this is what I get:

```
sos resume
INFO: Workflow ID:        2694dd928f30595f
INFO: Command:            sos run ./rnaseq-pipeline.sos vanilla -c /Users/gaow/Documents/dr-tree/src/pipeline/conf/monocle.conf -q midway2 -j 10 -J 60 --maxiter 20 --n_replicates 30 --K 4 5 
INFO: Working dir:        /Users/gaow/Documents/dr-tree/src/pipeline
WARNING: {} does not have any pending task. The workflow might have been interrupted.
INFO: Cannot resume workflow 2694dd928f30595f because all tasks are still running
```

But I cannot relate this number with the job i just submitted.

**Comment by BoPeng** [comment]
The counts are for all tasks on host. You have the job submitted and not resumable.

**Comment by BoPeng** [comment]
Cannot reproduce the problem after removing remote result file... Note that there can be local and remote signatures and sos will not check remote signature if the local signature matches.

**Comment by gaow** [comment]
I was suspecting the same but I too `rm -r` the local version of it ... I will get rid of the `.sos`, run `-s build` and see if I still run into it in the future. I've started not resorting to `rm -rf .sos` since a couple of weeks ago, so far so good! Hope this time is the only exception I need to make ... Thank you for checking it on your end!

**Comment by BoPeng** [comment]
Note the new [`remote` target](http://vatlab.github.io/SOS/doc/documentation/External_task.html#remote-target-1815) for keeping files on remote server.
