### ISSUE TITLE
Better control of content of HTML report converted from sos notebook

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#619]
I believe that the biggest problem for using Jupyter to report analysis is the inclusion of input cells in the resulting .html file. There has been already solutions (e.g. [hide input Jupyter extension](http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/hide_input/readme.html) but it is difficult to use by normal users.

I think sos should provide this as a standard feature, and provide a template for users to hide source code. Something like:

```
sos convert myanalysis.ipynb myanalysis.html
```
would use a default sos provided template that 

1. by default hide all input cells
2. provides a button to show source code.

**Comment by BoPeng** [comment]
OK, 

```
sos convert analysis.ipynb analysis.html
```

will use `sos/jupyter/sos.tpl` as the default template, which provides a button to show source code (the default is hide).

It is working but is not pretty, so further improvement would be needed.

**Comment by BoPeng** [comment]
I have found a need also to hide some of the results. I suppose it can be a cell meta data that introduced by sos using a magic or a shortcut. Then it should be relatively easy for `sos.tpl` to hide output according to cell metadata.

If we implement it as a magic, it can be

```
# hide both input and output
%hide
%hide -i      #hide only input in html output
%hide -o    #hide only output
```

Then, the show/hide button can have three states (or we can have two buttons)

1. Hide all input and specified output
2. Show everything except for specified input and output
2. Show everything

**Comment by BoPeng** [comment]
Or, if we only want to show selected output (which seems to be a more common case), we can use magic

```
%report 
```
to show the output of cell with this magic in converted HTML file.

**Comment by BoPeng** [comment]
Interface wise, I plan to 

1. Add a separate cell toolbar toggle box [show output [x]]
2. Users would need to "view -> cell tool bar -> Output in HTML"
3. Selection of box would enable output in HTML output.

**Comment by BoPeng** [comment]
Not sure if we should borrow some code or feature from the [hide code extension](https://github.com/kirbs-/hide_code).

**Comment by jirikuncar** [comment]
Can you just add dependency on the `hide_code` extension?

**Comment by BoPeng** [comment]
These are two different features:

1. hide input and/or output of the Jupyter notebook, which is what the hide code extension is for although it does not hide output. I do not really care about this feature although it seems to be useful for the `%render` magic ( #633 ).
2. hide input and/or output of exported HTML report, which can be the same or a different feature but hidding output is more important than hiding input.

It is generally a bad idea to send ipynb files as report because they are difficult to open even with Jupyter installed, so I tend to export ipynb file as HTML file after the analysis. With the current implementation, the default output files from `sos convert analysis.ipynb analysis.html` have a button `hide/show input` to hide all input cells, but I would like to refine this behavior so that the HTML file only contain output that I would like to represent. Note that the HTML file will have all input/output, but by default only displays markdown cells and selected output.

**Comment by BoPeng** [comment]
OK, [hide code extension](https://github.com/kirbs-/hide_code) is a nice package although we cannot make use of it as it is

1. we have made the cell tool bar too narrow to display the three checkboxes cleanly so we should try to restore the cell toolbar style when language selection is not used.
2. I really like the option to display hidden code when needed (with a button).
3. The hide all input option seems to be set to False by default.

**Comment by BoPeng** [comment]
Listing `hide-code` as dependency causes problems

```
(nbconvert 5.1.1 (/Users/bpeng1/anaconda/lib/python3.6/site-packages), Requirement.parse('nbconvert<5.0'), {'hide-code'})
```

So I suppose this has to be installed separately, and I am getting 404 errors for all pages such as

```
http://localhost:8888/notebooks/Untitled.ipynb/export/latexpdf
```

**Comment by BoPeng** [comment]
Confirmed [here](https://github.com/kirbs-/hide_code), "nbconvert 5.x does not work with hide_code.

**Comment by BoPeng** [comment]
Here is what has been implemented:

1. A `Ctrl-Shift-O` shortcut to toggle `show_output` metadata of codecell. The background of output of cells will be changed to indicated output that will be displayed by default in the HTML file.
2. By default (`sos convert analysis.ipynb analysis.html`) will only display markdown cells and output with `show_output` tag. 
3. A button `show more` (and `show less` after pressed) will display hidden input cells and output, which is basically all the information of the notebook.

This works ok for my work style but please comment if it you would like a different default behavior.

**Comment by BoPeng** [comment]
Changed the style to (note the bar to the end of output area)

![image](https://cloud.githubusercontent.com/assets/9889312/26423804/a91f905c-4094-11e7-9980-188f2c5c57f4.png)

and like it better. Otherwise the workplace has been too colorful.
