### ISSUE TITLE
Behavior of remote targets on local host.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#622]
Just to clarify ( #475 ), `remote` targets currently work like this:

1. A `remote` target always `exist()` (returns `true`) locally.
2. A `remote` target, like other non-file targets, are not translated during task preparation.
3. `remote(target)` are replaced with `target` at the beginning of `execute_task`.

It is then clear that `remote` targets only works properly inside tasks. It is not possible to do something like 

```
input: remote('*.txt'), group_by=1
```
although

```
input: remote('file.txt'), remote('file2.txt'), group_by=1
```
works.

You also cannot do

```
output: remote('a.txt'):
sh:
    touch ${output}  
```
since `remote('a.txt')` is not a proper filename, although

```
output: remote('a.txt'):
task:
sh:
    touch ${output}  
```
works all right.

I am not sure if there is any case we should handle `remote` target locally.

**Comment by gaow** [comment]
I'm cool with not handling `remote` target locally but I do think it is useful to have a global remote if we are Ok with not mixing local and remote like this. 

Perhaps it is less of a concern when one has a computer with a lot of disk space to sync data back and with stable cabled internet connection, but I'm working with someone whose only device is a macbook which has small disk space and wifi inside the office building is always not good. Such situation was the main motivation for a global remote.

**Comment by BoPeng** [comment]
The global remote feature is actually not difficult to implement but I do not know how well it plays with other  parts of SoS. For example, the `remote` design requires **all file operations to be handled in tasks** which might or might not be a huge problem.

I suppose I can implement it and let you guys play with it and see how it turns out ...

**Comment by gaow** [comment]
Yes I fully realize this. We are mostly running heavy lifting jobs which always involves `task` so indeed this is not a huge problem. I do see that `-r` can create problem when using SoS as a scripting language by itself, but at the same time `-r` is very consistent in behavior to submitting jobs on HPC, only more friendly (no need to login to the HPC). Users would very likely appreciate this similarity and convenience SoS provides in this context, and should take for granted that remote files always sits on the remote -- being able to sync is more like a bonus here given one has good local storage and internet connections.

**Comment by BoPeng** [comment]
Something like this:

```
[10]
input: 'sos/target.py'
output: 'target.pyc'
task:
sh:
    cp ${input} ${output}
```
start with
```
% sos run test -r -q mac_pro
INFO: Executing default_10:
INFO: input:    [remote("sos/target.py")]
INFO: aced87c09d516f129e8c6a7212640860 queued
INFO: aced87c09d516f129e8c6a7212640860 send [remote("sos/target.py")]
INFO: On mac_pro: _input = [remote("sos/target.py")]
INFO: On mac_pro: _output = [remote("target.pyc")]
INFO: On mac_pro: input = [remote("sos/target.py")]
INFO: On mac_pro: output = [remote("target.pyc")]
INFO: On mac_pro: input = [remote("sos/target.py")]
INFO: On mac_pro: output = [remote("target.pyc")]
INFO: aced87c09d516f129e8c6a7212640860 started
INFO: aced87c09d516f129e8c6a7212640860 completed
INFO: aced87c09d516f129e8c6a7212640860.out:
INFO: aced87c09d516f129e8c6a7212640860.err:
INFO: aced87c09d516f129e8c6a7212640860 received [remote("target.pyc")]
INFO: output:   [remote("target.pyc")]
INFO: Workflow default (ID=f6d6313b157ea7a5) is executed successfully.
```
with copy `sos/target.py` to `target.pyc` on the remote machine `mac_pro`.

**Comment by BoPeng** [comment]
As I have said, the implementation is easy although I might have missed some corner cases, and we will see how to handle more complex workflows.

For example, the idea of `task` is to submit large tasks to task queues but you are essentially running everything in tasks, which can be really troublesome if the task queue is full. In practice, you might have to define two hosts, one for PBS/Slurm and one for head node, and run the smaller jobs directly on headnode as follows:

```
[10]
input: 'sos/target.py'
output: 'target.pyc'
task: queue='head-node'
sh:
    cp ${input} ${output}
```
Then the `-r -q slurm` option will submit these jobs to headnode and larger tasks to slurm. This is not particularly difficult to understand or implement though.

**Comment by gaow** [comment]
I see, it makes a lot sense and is also consistent with our current framework, so we can recommend it as some "suggested practice". This feature looks great!

**Comment by BoPeng** [comment]
Also remember that we only check the status of remote tasks every `status_check_interval` seconds so in practice this is more or less the minimum amount of time a task will execute (actually when we know a task is completed). I do not see a way to improve this because we only have one-way communication so the server cannot notify the desktop once a task is completed.

**Comment by BoPeng** [comment]
Documented [here](http://vatlab.github.io/SOS/doc/documentation/External_task.html#Local-and-Remote-Targets-19)
