### ISSUE TITLE
A local target type?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#624]
In the case of a global remote mode (`-r`), there can be a need for a `local` object, which basically means I want this particular result to be transferred locally, or I would like to transfer this local resource to the remote server.

**Comment by gaow** [comment]
Catching it up here ... so please let me know if I'm wrong (no need to reply otherwise):  with `-r` all is remote and without `-r` all is `local()` ; `remote()` and `local()` will overwrite `-r` or no `-r` behavior.

**Comment by BoPeng** [comment]
Yes, plus the `remote` and `local` section options. All described [here](http://vatlab.github.io/SOS/doc/documentation/External_task.html#Local-and-remote-Targets-19).
