### ISSUE TITLE
%sossave broken?

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#627]
This is my cell:

```
%sossave -f -x main.sos
parameter: x = 5
```

But the saved result is just:

```
$ cat main.sos 
#!/usr/bin/env sos-runner
#fileformat=SOS1.0
```

Looks like `master` is broken?

**Comment by BoPeng** [comment]
This is not a "workflow" cell because it does not start with `[]`.

**Comment by gaow** [comment]
I tried 

```
%sossave -f -x main.sos
[global]
parameter: x = 5
```
which still doesnt work. Is this what you mean by `workflow cell`? My actual codes starts with `%include ...` though, not `[]`.

**Comment by BoPeng** [comment]
[Fixed](https://github.com/vatlab/SOS/commit/6f2297288e5c1c871645895043a9c81e4541b7aa). It is broken due to the new multi-kernel feature (#614) and there is currently no easy way to test such features.

**Comment by gaow** [comment]
So we test them in the field :) Thanks a lot!

**Comment by BoPeng** [comment]
Add a bit of test for `sos convert ipynb --to sos` and `sos run ipynb`. Still cannot test interactive magic especially because we intercept the normal cell execution code.
