### ISSUE TITLE
Separate setuptools command for installing SoS kernel

### ISSUE THREAD

**Issue by jirikuncar** [vatlab/SoS#629]
Provide a separate setuptools command for installing SoS kernel in development mode where files are linked instead of copied over.

**Comment by BoPeng** [comment]
What is the motivation for this? I thought of separating sos kernel as a separate packages (namely `sos-kernel` and `sos` batch command) but find a single package easier to maintain.

**Comment by jirikuncar** [comment]
The testing and debugging would be more pleasant. I completely agree in separating the module to separate packages.

- core
- cli
- ipython kernel
- jupyter extensions
- ...

**Comment by BoPeng** [comment]
Separating sos would be time consuming and is certainly not a priority now. I will keep this ticket open and work on it later.

**Comment by BoPeng** [comment]
SoS is getting larger. Keeping everything in one package has become more and more problematic. However, to keep the installation process simple, I think we should keep the `pip install sos` installation command so that we can have packages

* `sos-base` the sos workflow system
* `sos-notebook` the jupyter notebook (sos kernel) with Python2/Python3 subkernels.
* `sos-R`
* `sos-matlab`
* `sos-SAS`
* `sos-Julia`
* `sos-Bash`
* `sos-PBS`
* `sos-RQ`

And in the end we could have

* `sos` to install all sub-packages.

**Comment by BoPeng** [comment]
Ohmm, both dashes and underscores are discouraged ... what names should we use?

**Comment by gaow** [comment]
>  both dashes and underscores are discouraged

By pip? Then dot, I guess ?

**Comment by BoPeng** [comment]
`dot` is even worse...  [this post](https://stackoverflow.com/questions/2852283/python-naming-a-module-that-has-a-two-word-name) suggests `soscore`, `sosnotebook`, but I think I will follow Jupyter convention and use `sos-core` as displayed package name and `sos_core` as importable package name. Example of this is

```
$ pip list | grep jupyter
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
jupyter (1.0.0)
jupyter-client (5.0.1)
jupyter-console (5.1.0)
jupyter-contrib-core (0.3.3)
jupyter-contrib-nbextensions (0.3.1)
jupyter-core (4.3.0)
jupyter-highlight-selected-word (0.0.11)
jupyter-latex-envs (1.3.8.4)
jupyter-nbextensions-configurator (0.2.7)
[bpeng1@bcbm-bpeng:~/sos (master)]$ python -c 'import jupyter_client'
```

**Comment by BoPeng** [comment]
```
$ pip list | grep sos
sos (0.9.9.3)
sos-all (0.9.9.1)
sos-bash (0.9.9.2)
sos-bioinfo (0.9.9.2)
sos-essentials (0.9.9.2)
sos-javascript (0.9.9.2)
sos-julia (0.9.9.1)
sos-matlab (0.9.9.2)
sos-notebook (0.9.9.3)
sos-pbs (0.9.9.1)
sos-python (0.9.9.1)
sos-r (0.9.9.2)
sos-rq (0.9.9.1)
sos-sas (0.9.9.2)
```
