### ISSUE TITLE
Automatic preview of assignment in other languages.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#630]
In SoS, when we execute some statement in the side panel, for example,

```
a = 1
```

The statement would automatically translated to

```
%preview a
a = 1
```
to preview the result of assignment. I am wondering if we should enable this for other languages.

We should perhaps  know some information about the language to do this, for example, in R, we should recognize

```
a <- 1
```

**Comment by jirikuncar** [comment]
WDYT about `%preview NAME /--all / --assignments / --expressions`?

**Comment by BoPeng** [comment]
`%preview` can preview `name` or `expression`, so manually input

```
%preview a
a <- rnorm(5)
```
works ok for R kernel.

The idea is to automatically preview `a` when `a <- rnorm(5)` is evaluated in the side panel using shortcut `Ctrl-Shift-Enter`. Then we should somehow know the syntax of assignment in the underlying language.
