### ISSUE TITLE
Remote target file name derivation

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#632]
Here is a MWE:

```
[default]
input: "start.txt"
output: "${input[0]!n}.done"
task:
run:
  sleep 5
  echo completed > ${output}
```

and I run with `-r` I get this error from the string interpolation routine:

```
INFO: Executing default_0: 
INFO: input:    [remote("start.txt")]
ERROR: Failed to execute workflow default
[default_0] RuntimeError:
	Failed to process step output: "${input[0]!n}.done" (expected str, bytes or os.PathLike object, not remote)
[default] RuntimeError:
	1 failed step: default_0
```

**Comment by BoPeng** [comment]
So because the target is only meaningful on remote server, string interpolation should be delayed?

```
input: remote('start.txt')
output: remote('${input[0]!n}.done')
```

**Comment by gaow** [comment]
What do you mean by delayed? I just want to point out there might be cases where we want string interpolation happen instantly, for a trivial example:

```
parameter: script = '...'
parameter: data = open("${script}!r").readlines() 
```
Not sure if it is relevant to the fix you have in mind that delays interpolation but I'm saying this is expected to be allowed.

**Comment by BoPeng** [comment]
By delayed I meant that 

```
input: remote('start.txt')
output: remote('${input[0]!n}.done')
```

should not be handled locally, or `${input[0]!n}` should not do anything if `input[0]` is of `remote` type. Because these variables only make sense when they are expanded inside `task`.

**Comment by gaow** [comment]
i see. that's what I too understand. I just want to make sure that string interpolations in parameters (as my example above) will work regardless of it be local or remote.

**Comment by gaow** [comment]
Well, it is exactly what I fear delayed interpolation will beak my pipeline. Here is a more careful MWE:

```
[1]
input: "1.txt"
output: "${input!n}.h5"
task:
run:
  echo 1 > ${input}
  echo 2 >> ${input}
  echo 3 >> ${input}
  touch ${output}

[2]
parameter: tissues = get_output("cat ${input[0]!n}.txt | awk '{print $1}'").strip().split('\n')
input: for_each = ['tissues']
output: "${_tissues}_PEER_covariates.txt", "${_tissues}_PEER_alpha.txt", "${_tissues}_PEER_residuals.txt"
task:
run:
 touch ${output}
```

It works fine locally, but not with `-r`. You can immediately tell the interpolation is problematic. I think it is perhaps easiest to use regex to remove `remote` and do interpolation not delayed ?
```
[GW] sos run test1.sos -s force -q midway2 -r
INFO: Executing default_1: 
INFO: input:    [remote("1.txt")]

INFO: d36b662d56de2a312e5d247872e0d92d queued
INFO: d36b662d56de2a312e5d247872e0d92d send [remote("1.txt")]
INFO: On midway2: _input = [remote("1.txt")]
INFO: On midway2: _output = [remote("input!n.h5")]
INFO: On midway2: input = [remote("1.txt")]
INFO: On midway2: output = [remote("input!n.h5")]
INFO: On midway2: output = [remote("input!n.h5")]
INFO: On midway2: input = [remote("1.txt")]
```

**Comment by BoPeng** [comment]
Ohmm, this is more complicated than I thought, especially when `'${input}'` and  `"${input}"`  are the same to `remote` (both string) but are different in SoS (one is interpolatable one is not).

**Comment by BoPeng** [comment]
OK, I have assumed that `remote(string)` is all interpolatable...

But this does not solves your problem because 

```
[2]
parameter: tissues = get_output("cat ${input[0]!n}.txt | awk '{print $1}'").strip().split('\n')
input: for_each = ['tissues']
```
is exactly the case that I have warned you. The problem is that `input` is a remote target so **it can only be used in tasks**. Even if you know `input=[remote('a.txt')]` so that we can possibly know `${input[0]!n}`, what about absolute path (`${input[0]!a}`) or expand user (`${input[0]!u}`) that depend on remote file system?

**Comment by gaow** [comment]
I should mention that `${input}` in parameter is only made for this MWE. In my actual code I use `${input!nn}.meta.txt` which exists on my local computer. I guess users have to understand these limitations and expect `file not found` error when using them improperly.  I'll try to see if it works later. Thanks a lot!

**Comment by BoPeng** [comment]
It still makes some sense to convert remote targets if possible because we are getting `remote(filename)` which is conceptually still a `path`.

**Comment by BoPeng** [comment]
A related case might be

```
[step: remote]
input: "*.fastq", group_by=1
output: "${_input:n}.html"

```
where we will have to expand `remote('*.fastq')` to `remote('f1.fastq')` and `remote('f2.fastq')` to properly `group_by` the input.

**Comment by BoPeng** [comment]
```
%run -q nautilus

input: remote('~/RNASeq/R376-8-P8/raw_data/R376-8-P8_S3_L001_R1_001.fastq.gz')
output: "${_input!dd}/QC/${_input!nb}_fastqc.html"

task: walltime='30m', mem='4G'
sh:
    fastqc ${_input} --outdir ${_input!dd}/QC
```

does not yet work.

**Comment by BoPeng** [comment]
I have the new `R` converter can help address this issue. The details is demonstrated in [this example](http://vatlab.github.io/SOS/doc/examples/Remote_Target.html).
