### ISSUE TITLE
Using an alternative kernel or language for pre-defined subkernel

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#641]
Currently
```
%use R -l myR
```
is disallowed because `R` is pre-defined by SoS to work with local `ir` kernel and language `R`. 

However, for example, if we

1. Create a notebook with local `ir`
2. Move to another machine and would like to connect to the original `ir` kernel (on the remote machine)  because it has the modules we need and/or exact versions of modules if we would like to reproduce the analysis.

We can do

```
%use R-remote -k R-remote
```
then we would have to change the `R` kernel to `R-remote` for all cells.

It would be easier to allow

```
%use R -k R-remote
```

@jirikuncar : is this scenario reasonable?

**Comment by jirikuncar** [comment]
I would be extremely careful with overriding existing (especially remote) kernels unless we can explicitly halt them. Otherwise I can imagine somebody trying to do what you have explained above.
