### ISSUE TITLE
Replace magic %restart with %use --restart 

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#646]
This is a rarely used magic and could be merged to `%use` as an option `--restart`.

**Comment by jirikuncar** [comment]
@BoPeng can we also include an option to explicitly stop a kernel?

**Comment by BoPeng** [comment]
What command do you have in mind?

```
%use --restart
```
makes sense because we are switching to a kernel, and restart if necessary.

```
%use --halt
```
does not sound right so we have to add another magic such as

```
%shutdown R
```
