### ISSUE TITLE
Absolute path resolve and remove symbolic links

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#650]
I'm running into an interesting problem with symbolic links in my file paths. I have an R function written in C++ with a parameter being a file path. For example `logfile = "~/Documents/XXX/YYY"` where `~/Documents` is in fact a symbolic link to another hard drive I have (not mounted to `~/Documents` directly for a reason). Then the C++ program does not leave any logfile behind. If I change the path to the actual link it then works. 

I'm wondering if we can let SoS string interpolation take care of it. ie, a shorthand for `os.path.realpath()`?

**Comment by BoPeng** [comment]
Does `abspath` (`!a`) work?

**Comment by gaow** [comment]
No, unfortunately. It's very C++ specific. 

I'm thinking should we just make `!a` be `os.path.realpath(os.path.abspath(os.path.expanduser))`?

**Comment by BoPeng** [comment]
Can you think of any case that users would need `abspath`, not `realpath(abspath)`? I was thinking a separate convertor (`!l`?) but using existing `!a` seems to be easier. I guess we can use `!a` until we see a case where two cases need to be separated.

Please make the change in `sos_eval.py` and `SoS_Syntax.ipynb`.

**Comment by gaow** [comment]
I cannot think of any side effects for now ... 

Let me make those changes and close the ticket. I'll not compile the HTML though for fear of messing things up. So next release on your end should change the documentation :)

**Comment by BoPeng** [comment]
Your patch actually broke a test...

When a task sends symbolic link (option `to_host`), it would send the link itself and the link content to remote host, and the send command uses `!a` to convert the link to absolute path before sending it, and with your patch, the content would be sent twice and the remote script would not run without the link.

**Comment by BoPeng** [comment]
I added `!l` (for expand link), but we might have `!A` or `!R` for 

```
realpath(abspath(expanduser()))
```
as a way to get real absolute path.

**Comment by gaow** [comment]
I see ... so we'll either have to use something other than `!a`, or do not use `!a` in the underlying code for path communication between local and remote. Perhaps the first solution is better. `!u` for `unlink`? or `!l` for `resolve link`?

**Comment by BoPeng** [comment]
`u` is used for `expanduser` so I used `l`. Having `realpath(abspath(expanduser()))` is cool but there can be cases for `realpath` without `abspath`.

**Comment by BoPeng** [comment]
The funny part about this bug is that I really did not expect any problem with the change, at least not so soon.

**Comment by gaow** [comment]
Indeed, even with existing unit test! I did not even expect this to be a bug in the first place -- thanks to my new hardware. `!l` is good enough I think. One can always combine these operators so we should be good as long as there is a solution in this case.
