### ISSUE TITLE
Convert to PDF even word

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#657]
I prefer HTML output because of the display panel to hide/unhide content, and the inclusion of interactive tables and figures, but I was pointed out that PDF even word reports are frequently requested...

For PDF, the default method is to convert from`ipynb` to `tex` and to `pdf`, we could see if we can add support for sos template.

Word is more difficult and there seems to be a [ticket](https://github.com/jupyter/nbconvert/issues/121) for it. I suppose we could use pandoc for this.

**Comment by gaow** [comment]
It's cool by me that we wait until officially supported. PDF request is justifiable and seems easily done. I feel user case of Word should be rare enough not to worry too much about.

**Comment by BoPeng** [comment]
I got the request for word from the audience because some PIs request reports in WORD format so that they could pass the reports around for opinions (with changes marked) and then incorporate the results directly in the manuscript.

**Comment by gaow** [comment]
Ah ... this would be the only scenario this request makes sense (and in fact very much valued... )

**Comment by BoPeng** [comment]
So basically the ability for others to comment on the report, which is not possible for HTML and difficult for PDF.

But anything is possible if we put enough effort on it. I would have the request open with perhaps a low priority. Right now SAS seems to be very important because it is very frequently used in the biostat side of the floor.

**Comment by BoPeng** [comment]
Out of scope.

**Comment by gaow** [comment]
There is a plugin to download Jupyter notebook as Word though, using pandoc -- I guess it's just exporting to markdown then convert to Word. 

https://github.com/m-rossi/jupyter-docx-bundler
