### ISSUE TITLE
Do not translate variables by default.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#682]
I have found it inconvenient to have to put variables such as `ID`, `sample_sheet` etc to `preserved_vars`. In addition, if I would like to write a script specifically for the remote server, I would have to put all variables used in `preserved_vars`.

I think it makes more sense to translate only local targets in `input`, `output`, `depends`, `to_host`, and `from_host`, and leave the rest of the variables untouched by default, because these should have covered most cases when files should be synchronized.

A new option could be named `translate`, or something along the line.

**Comment by gaow** [comment]
I use `remote()` a lot to avoid "unnecessary" file synchronizing. I think it can make things a lot simpler if we only translate some of those targets by default. Is the new option designed to explicitly translate those preserved defaults? Then we'll remove `preserved_vars`?

**Comment by BoPeng** [comment]
Yes, but this is not related to `remote` as it handles other variables that are not in `input`, `output`, `depends`, and `to_host` and `from_host`.

 The problem with `preserved_vars` is that we have `input` etc for `+`, and preserved_vars for `-`, and care should be taken for anything else. With an all-`+` design, we know `input`, `output` etc are `+`, and variables in an option (e.g. `map_vars`) will also be `+`, and anything else will not be translated, which is a lot simpler.

The problem is more pronounced when we are trying to write a script that works purely on remote host, because then we should be careful that all variables should be either written w.r.t local file system, or be put into `preserved_vars`. With the new option, we know things in `input` etc (perhaps `remote`) are files that would be translated/synchronized, and the script itself will not be touched by default.

**Comment by gaow** [comment]
I agree the proposed change will make things simpler. I've tried to avoid complications by setting via symbolic links all the major directories on remote to be the same structure as my local file system. Better `translate` behavior from within SoS is a lot more helpful!

**Comment by BoPeng** [comment]
OK, I will make the change and replace `preserved_vars` with `map_vars`.
