### ISSUE TITLE
Remote execution of workflows / auxiliary steps.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#684]
It is even conceptually unclear what sos should do for the execution of workflows remotely. The problem is that if we call the workflow with `sos_run`, it would trigger other steps, which might or might not use remote targets. Also, it is unclear how to trigger auxiliary step from a remote step ...

The bottom line is that our current remote execution model is limited to single tasks, not workflows.

**Comment by BoPeng** [comment]
Remote execution of workflow can be as simple as

1. Copy the script to remote host
2. Execute the command on remote host.

So

```
sos run script -r host
```
is equivalent to

```
scp script host:; ssh host sos run script
```

Not quite sure how this compares our existing `-r` option.

**Comment by BoPeng** [comment]
Not sure about step `remote` option but let me know if the command line `-r host` sounds useful to you (and your friend).

**Comment by gaow** [comment]
I do find this new behavior more intuitive than before. But what's the fate of `remote` option?

**Comment by BoPeng** [comment]
You meant the old global command line `-r` option? The mechanism is still there but I have removed the interface. We could resurrect if it appears to be useful later on but right now, it seems that the `remote` step option is enough.

The main usage of the new `-r` to me is to execute small workflows that are not suitable as tasks on remote hosts. The added benefit is that it is conceptually much easier to understand than the old option, the cost is that users would have to `sos pull` if they would like to get the result back.

**Comment by gaow** [comment]
I see. The new remote option is more practical to some of my scripts that uses a dedicated remote machine. I'll yet have to test when both the new `-r` and `-q` are used -- this should correspond to the case when one submits job to a remote headnode and let it distribute jobs to the rest of the cluster, right?

**Comment by BoPeng** [comment]
Yes, the combination of `-r` and `-q` can be pretty powerful although the remote host need to be configured to submit tasks (with `hosts.yml` and correct `localhost` etc).

**Comment by BoPeng** [comment]
Note that I am not particularly happy with the section option `remote` because it can be confusing why the following fails

```
[10: remote]
input: 'somefile'
sh:
  wc -l ${input}
```
Intuitively speaking users might expect the entire step to be executed on a remote host. I do not know what we can do here though.

**Comment by gaow** [comment]
But with the new `-r` it will work on remote host, right? What if we make this a `task` option -- will it be more or less confusing?

**Comment by BoPeng** [comment]
It would be more confusing because the files would be local or remote with the addition of a task, even worse if we have both regular actions and tasks statements.

The new `-r` is practical for submitting steps to remote host on a Jupyter notebook with `%run -r` (see [this example](http://vatlab.github.io/SOS/doc/documentation/Remote_Execution.html#Remote-execution-of-workflows-112)), but not for submitting steps to remote host.

I am not saying we should support submitting selected steps of a local workflow to remote host, which is not very practical (e.g. how to "connect" steps), I just thought that a step option `remote` can be misleading.

I suppose if the `remote` function is more clever, namely if it can handle

```
input: remote('file1', 'file2', var)
```
so that users do not have to wrap `remote` to individual item, perhaps we can remove the `remote` section option.

**Comment by BoPeng** [comment]
I meant,

```
[step: remote]
input: input files
sh:
    whatever
```
gives an impression of remote step or remote action (`sh`).

```
[step]
input: remote(input files)
sh:
    whatever
```
makes it clear that `sh` is still local, but the input file is remote.

**Comment by gaow** [comment]
I agree extending `remote()` would be a good way to avoid these confusions. I think using tasks specific queue to control where to submit tasks is good enough. Mostly I'd just use the new `-r`  to submit everything :)

**Comment by BoPeng** [comment]
Ok, I will see how to extend `remote()`.

**Comment by BoPeng** [comment]
Done. I have also removed `local()` and `local` section option because they are no longer needed without global `remote` option.
