### ISSUE TITLE
Compatibility with JupyterHub

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#688]
The multi-kernel nature of SoS makes installing sos and all the kernels a daunting job for the inexperienced. It is therefore very useful to have a [JupyterHub](https://github.com/jupyterhub/jupyterhub) set up with all the kernels and SoS, so that everyone can log in to the same location and perform analysis.

In theory sos should work with JupyterHub but we should test it.

**Comment by vibbits** [comment]
Hi, after having installed jupyterhub (via pip) on our CentOS server and launching a SoS notebook for the very first time we get an access error denied error:
e.g.
[global]
parameter: cwd = path('/home/albot/kitematic')
[Errno 13] Permission denied: '/tmp/sos_lock_bin'

My colleagues narrowed the issue down to https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/workflow_executor.py#L334

After removing the lock manually it works fine.

**Comment by BoPeng** [comment]
This is a known issue due to the use of global lock in a multi-user environment (someone else created this lock) and I will make sure all such locks are removed. This particular lock has been removed (https://github.com/vatlab/sos-notebook/commit/dca2a2b1fa039deca7fcd813cadb9068e803c1e7) because we now requires Python 3.6+ for which `exist_ok` exists for function `os.makedirs`.
