### ISSUE TITLE
Preview of multi-page pdf

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#693]
For some reason `pheatmap` package produces pdf figures with a blank first page, leading to a blank preview page for the file. We should perhaps use `iframe` as default pdf viewer because that viewer can handle multiple pages.

**Comment by BoPeng** [comment]
iframe is now by default, but we can use option `-s png` to force the use of imagemagick to convert pdf to png for preview.

The problem with pdf is that the height of the iframe is too small, which usually makes it difficult to preview the whole figure. We should probably try some magic to change the height of the iframe to height of figure.

**Comment by gaow** [comment]
Not sure how easy to debug this, but I'm just starting to use this new features and got:

```
%preview figures/20160615/dsc9.pdf
> figures/20160615/dsc9.pdf (14.7 KiB):
MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  apt-get install libmagickwand-dev
```
even though I've run the `apt-get` command. `--style png` does not work in this context. Is it a false warning? Or is there a specific command you were checking? I do have `imagemagick` installed.

**Comment by BoPeng** [comment]
DId you install wand python module? I guess you can test this on command line using

```
python -c 'import wand'
```

**Comment by gaow** [comment]
Yes I have `wand`.

**Comment by BoPeng** [comment]
`%preview` without `-s png` will use `iframe`, are you using the latest trunk?

**Comment by gaow** [comment]
I was on the latest trunk. I used --style png though. Just stepped outside. Will test some more after I return.

**Comment by BoPeng** [comment]
The code is pretty simple (in src/sos/jupyter/preview.py) so it seems that something wrong with your imagemagick/wand installation. Let me know what you can find.

**Comment by gaow** [comment]
Sorry forgot to add that it is a mystery on my end -- that `from wand.image import Image` shows those error, though not `import wand` .. and the imported module is usable anyways. I've not yet got a chance to figure out how to get rid of that error, but it's not problem with SoS.

**Comment by BoPeng** [comment]
I saw this before. You will have to install/reinstall ImageMagick.
