### ISSUE TITLE
Two step remote host job submission

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#700]
I'm trying out some more remote computations -- we have an old yet still powerful remote system that requires an additional step of login before submitting jobs. It basically involves:

```
ssh machine1.uchicago.edu 
```
then
```
ssh spudhead
```
which is the grid engine submit node. Is the current SoS job submission mechanism good to handle the additional layer of complication?

**Comment by BoPeng** [comment]
Do you have to be physically on spudhead to submit jobs? Otherwise `sos -r machine1 -q spudhead` should be able to submit jobs onto `spudhead`.

**Comment by gaow** [comment]
Sorry I should mention that the problem is on `machine1` there is no software installed, or storage shared with `spudhead`. It is just a portal. So the conventional `-r -q` technique may not work ...

**Comment by BoPeng** [comment]
Yes, that can be difficult. Can you log in to `spudhead` in one step with something like

```
ssh machine1.uchicago.edu 'ssh spudhead bash --login sos -h'
```

**Comment by gaow** [comment]
No I cannot ... and I just realized my `authorized_keys` setting does not work, and each time I'll have to type in the password. 

If there is no good solution I'll just execute sos on `spudhead` directly hoping there is no objection from others when I do it for this machine ... In that case I should configure the `spudhead` and only use `-q` to submit PBS jobs, right?

**Comment by BoPeng** [comment]
`authorized_keys` not working usually caused by permission of `.ssh` and `/home/user`...

Yes, if you are on `spudhead`, then you just use `-q` to submit to a local task queue (set `localhost` to `spudhead` with `PBS` settings).
