### ISSUE TITLE
Multiple kernels for a language.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#704]
It is possible for a language to have multiple kernels, for example matlab has [`matlab_kernel`](https://github.com/Calysto/matlab_kernel) and [`imatlab`](https://github.com/imatlab/imatlab), and JavaScript has [`jupyter-nodejs`](https://github.com/notablemind/jupyter-nodejs) and [`ijavascript`](https://github.com/n-riesco/ijavascript). It is likely that a sos language extension could work with all of them so it makes sense to support multiple kernels in a single language extension.

Note that

```
%use iMatlab -k imatlab -l Matlab
```
could already be used to use `Matlab` language with `imatlab` kernel.

**Comment by gaow** [comment]
But do all kernels have unified structure for data objects? ie, our data converting routine should work (once we have them work for a pair of languages) regardless of kernel used? 

Also for matlab there is also the `octcave_kernel`. We should support that too, if not too different from matlab kernel

**Comment by BoPeng** [comment]
That is something we should test and the language module will have to be started with a kernel name so that it can handle kernel-specific issues.

`octave` uses the same datatypes from `matlab` so we should be able to support it. Although it is better to add an entry in `setup.py` to list it as a different language (while pointing to the same language module).
