### ISSUE TITLE
Exchange of complex numbers between Python and R

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#707]
is not currently handled.

**Comment by HenryLeongStat** [comment]
Done.

**Comment by HenryLeongStat** [comment]
Done.

**Comment by BoPeng** [comment]
Then check test/R/test_R_kernel.py and add a complex number. Run thus script with python test…  to test it.

**Comment by BoPeng** [comment]
Finally, check the [documentation](http://vatlab.github.io/SOS/doc/documentation/Notebook_Interface.html#R-135) and see if documentation is needed. In this case, you will need to modify `docs/src/documentation/Notebook_Interface.ipynb` to add a line like `complex --> complex` in the conversion table.

Basically, tests and documentations are required to complete a change.

**Comment by HenryLeongStat** [comment]
Understood! I will handle it.

**Comment by HenryLeongStat** [comment]
Done. See [#723](https://github.com/vatlab/SOS/issues/723) for details.
