### ISSUE TITLE
Next language to support

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#712]
We currently support eight languages (Bash, R, Python2, Python3, JavaScript, SAS, Matlab, Octave) that I suppose would be enough for > 90% people in bioinformatics / biostatistics and related fields. I have no plan to add another language before SoS 1.0 but anyone can suggest new languages/kernels to support before or after 1.0.

Candidates can include
* [ruby/iRuby]( https://github.com/SciRuby/iruby)
* [perl/iperl](https://github.com/EntropyOrg/p5-Devel-IPerl)
* [Julia/iJulia](https://github.com/JuliaLang/IJulia.jl)
* [sciLab/scilab_kernel](http://www.scilab.org/)
* ...

[TypeScript/iTypeScript](https://github.com/nearbydelta/itypescript) could be a low-hanging fruit because it is very similar to JavaScript.

**Comment by HenryLeongStat** [comment]
Just did some search and found that there is a `ruby` kernel for `Jupyter` [here](https://github.com/SciRuby/iruby). Maybe we can add `ruby` later.

**Comment by BoPeng** [comment]
There is a jupyter kernel for whatever language you know or do not know out there. :-) 

The next language would be Julia (#756), want to try? It would be very similar to the R code, and you can start from basic types like `int`. Julia is a very good language for scientific computation and very popular among big data/ data science guys, which can certainly be useful for you later.

**Comment by HenryLeongStat** [comment]
Sure! :D 
Let me try learning it. I think it isn't too difficult to pick up. Maybe this time I can take care of both the test and the kernel (hopefully)! 💪

**Comment by gaow** [comment]
@HenryLeongStat this is great!!

**Comment by BoPeng** [comment]
Julia is similar to Python and should not be too difficult to learn, especially when you only need to learn basic datatypes. It would be cool to put Julia on your CV....

**Comment by gaow** [comment]
Yes Julia is very trendy. Not sure about Rice stats but it is gaining popularity among grad students here in Chicago @HenryLeongStat

**Comment by HenryLeongStat** [comment]
I know some post doc in Economics department use `Julia`, but never heard about it in stats department... 
Anyway, I am just interested in the differences of programming languages recently. I read about some articles about the comparison between `Python` and `ruby` these days. But for now, let me try to pick `Julia` up 😃 .
