### ISSUE TITLE
Transfer Matlab-table to Python

### ISSUE THREAD

**Issue by HenryLeongStat** [vatlab/SOS#713]

**Comment by BoPeng** [comment]
Is it matlab table type is the same as Pandas DataFrame?

To answer your question, sos aims to provide "similar" data types across languages so there is no need for a one to one type correspondence. For example, in R,  `3` is actually the same type of `c(3, 1)` but we translate the former to `3` (int) and latter to `[3, 1]`.

So when we transfer `table` to `Python`, we can check if all columns have the same length, and convert to a Pandas dataframe or a dictionary (with column name as key and value as value).

**Comment by BoPeng** [comment]
Ohmm, variables in tables should have the same number of rows so it is very similar to DataFrame.

**Comment by HenryLeongStat** [comment]
Yes, it seems they are very similar. I will try to use Pandas DataFrame instead of scipy.io to see if it is better.

**Comment by HenryLeongStat** [comment]
Table written as .csv would be a far better solution for Python to read as pandas dataframe. Since the column's names can be kept.

**Comment by BoPeng** [comment]
Fine with me...
