### ISSUE TITLE
Result mismatch problem with inconsistent use of `_index` and `_output`

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#714]
Currently I cannot provide an MWE for this one, but when I rerun my workflow with `-s force` SoS keeps aborting the runs with `result-mismatch` error message:

```
INFO: 8f61d0e6b6be7a86d14124ca0950a8a7 re-execute completed
INFO: 8f61d0e6b6be7a86d14124ca0950a8a7 queued
INFO: 228040a86fa69b8875132ccb5cbcce09 restart from status result-mismatch
INFO: 228040a86fa69b8875132ccb5cbcce09 queued
INFO: 228040a86fa69b8875132ccb5cbcce09 started
INFO: 8f61d0e6b6be7a86d14124ca0950a8a7 started
INFO: 228040a86fa69b8875132ccb5cbcce09 completed
INFO: 8f61d0e6b6be7a86d14124ca0950a8a7 completed
WARNING: 228040a86fa69b8875132ccb5cbcce09 result-mismatch
ERROR: 1 job completed, 1 job result mismatch
```

Intuitively, I think for `-s force` since I'm specifically asking it to rerun everything regardless of whatever exists, should I really expect any `result mismatch`? When I run with `-v4` I see lines like this:

```
DEBUG: result-mismatch: 617 completed: 906 aborted: 131 failed: 198 pending: 4 running: 2
```
which could be a bit confusing because in my workflow there should be only a couple of tasks. (I understand these lines may refer to runs from other workflows). 

BTW it may also worth mentioning that if I rerun when I first fail with `-s force` then the problem goes away. However another task in the workflow may start complaining the same. If I run many times, then the problem will get "fixed" one at a time for each run and eventually I'm able to execute the entire workflow without an issue. Not sure if these descriptions are enough to pin the problem.

**Comment by BoPeng** [comment]
Using `-v3` should at least show which file does not exist or does not match signature... basically, for the tasks that fail with `result-mismatch`, you can do `sos status ID -v4` to check its `_output` var and see if any file does not exist. From your description, it appears to me that several tasks might be writing to the same output file.

**Comment by gaow** [comment]
Hmm ... using `sos status` check I find this:

```
_index                1
_input                ['Overview.ipynb']
_output               ['docs/data.html', 'docs/index.html']
_runtime              {'cur_dir': '/home/gaow/GIT/github/random-nbs', 'home_dir': '/home/gaow'}
depends               None
input                 ['data/_index.ipynb', 'Overview.ipynb']
output                ['docs/data.html', 'docs/index.html']
step_name             'update-hp_0'
```

which is a bit suspicious. It should in fact be 

```
_input                ['Overview.ipynb']
_output               ['docs/index.html']
```
so the `_output` part has 2 files instead of one. But the end produce seems Ok! 

This is in fact some `release` script I took from here:

https://github.com/vatlab/SOS/blob/master/development/release#L72

though in my version I made them `task`. Why would you implement it that way -- that looks a bit counter intuitive to me now that I look at it. ...

**Comment by BoPeng** [comment]
I do not know how your `output:` is specified... this is `_index=1`, but your `output=_output` ... so you `_output` must not be defined from `_input`. Is this related to your output group by stuff ( #445)?

**Comment by gaow** [comment]
They should be separate issues but yes it would have been much easier if I did complete #445 ... 

> I do not know how your output: is specified... 

But I think you actually wrote it not me, I'm just taking it from your example:

https://github.com/vatlab/SOS/blob/master/development/release#L72

If I were to write it I'd have to use `pattern` and `expand_pattern`. I think it is your recommendation but apparently it gets messed up here.

**Comment by BoPeng** [comment]
This does not sound right, that line would only produce one file in  `_output` since it used `_input[0]` which is a single file.

**Comment by gaow** [comment]
Ok so it boils down to 

```
[1]
parameter: files= ["1.txt", "2.txt"]
input: files, group_by = 1
output: 'docs/' + _input[0]
task:
run:
  cp ${_input} ${_output}
```

Interestingly if I check the first task status I get:
```
_index                0
_input                ['1.txt']
_output               ['docs/1.txt']

input                 ['1.txt', '2.txt']
output                ['docs/1.txt']
```
which has correct `_input` `_output` but not `output`. However it does not fail, unlike my real example which is messed up the other way around. But how I specified the workflow is the same as this MWE.

**Comment by gaow** [comment]
I should add that for the example above when `_index=1` it looks fine:

```
_index                1
_input                ['2.txt']
_output               ['docs/2.txt']
...
input                 ['1.txt', '2.txt']
output                ['docs/1.txt', 'docs/2.txt']
```

**Comment by BoPeng** [comment]
`output` is cumulated from `_output`. At `_index=0`, there is no way to know what `_output` is when `_index=1`, so `output` equals `_output` temporarily.

**Comment by gaow** [comment]
I see. Since this is expected behavior it should not be the culprit ... let me dig some more into what might be wrong with my script. Would be much simpler if I implement #445 (soon as I would need it!).

**Comment by gaow** [comment]
Oops sorry my bad, I was running and reporting from a different workflow ... the workflow in question in fact looks like this and I'm able to partly reproduce the issue with a MWE now:

```
[1]
parameter: files= ["1.txt", "2.txt"]
input: files, group_by = 1
output: ['docs/' + x for x in files]
task:
run:
  cp ${_input} ${output[_index]}
```
Running this script there is no issue. Re-running it or run with `-s force`, no problem.

However if I add an additional line to the `run` part like this:

```
run:
  cp ${_input} ${output[_index]}
  echo 1 >> ${output[_index]}
```
and re-run it, then with or without `-s force` I will get an error message:

```
INFO: Executing default_1: 
INFO: input:    ['1.txt', '2.txt']
INFO: 1c341fe831dacc881cdd0278c9a396be restart from status result-mismatch
INFO: 1c341fe831dacc881cdd0278c9a396be queued
INFO: f94680328d6bbcce7b3413793835e21c restart from status result-mismatch
INFO: f94680328d6bbcce7b3413793835e21c queued
INFO: f94680328d6bbcce7b3413793835e21c started
INFO: 1c341fe831dacc881cdd0278c9a396be started
INFO: f94680328d6bbcce7b3413793835e21c completed
INFO: 1c341fe831dacc881cdd0278c9a396be completed
WARNING: f94680328d6bbcce7b3413793835e21c result-mismatch
ERROR: 1 job completed, 1 job result mismatch
```

If I implement the same actions with `output: "docs/+ _input[0]` then when I change the `run` part there is no problem.  The `sos status` does show a bad `_output` even though I did not use it in practice. Is that the cause of the problem?

**Comment by BoPeng** [comment]
OK, Now I see the problem. With your way of using `output`, `_output` is defined to be `output` in both cases so the task `_output` can only exist when both tasks are completed....

**Comment by gaow** [comment]
Indeed. Is this a feature or bug? I can of course change my implementation but using `_index` is quite handy here.

**Comment by BoPeng** [comment]
`_output` has to be properly defined to make tasks work with correct `_input` and `_output`. Given this example, I think we should yield an error if multiple tasks have the same `_output`. I even tent to remove `_index` altogether...

**Comment by gaow** [comment]
>  I even tent to remove _index altogether...

Is `_index` the only potential cause of issues like this? What's your user case for `_index`? I think I do use it quite often. Maybe with #445 in place we can eventually get rid of it? 

The use of `_input[0]` is interesting but is not always as convenient when output pattern is not derived from input. (which was my case)

**Comment by BoPeng** [comment]
I just submitted a patch (not tested at all) that checks if tasks step on each other's feet. Could you test it?

**Comment by BoPeng** [comment]
Yes, #445 would produce proper `${_output}` and should help avoid this problem.

I personally very rarely use `_index`.

**Comment by gaow** [comment]
Your patch does work and give me an ugly error :) Let me try if I can easily get #445 work based on your instructions in that ticket.

**Comment by BoPeng** [comment]
I am working on #445.

**Comment by gaow** [comment]
Oh Ok I was about to send you the patch I have for #445 which does not yet work ... but that's as far as I can get from your hints on that ticket :)

**Comment by BoPeng** [comment]
Just submitted a patch, let me know if it works. I am adding a test for it right now.

**Comment by gaow** [comment]
You can use this test:

```
[1]
parameter: files= ["1.txt", "2.txt"]
input: files, group_by = 1
output: ['docs/' + x for x in files], group_by = 1
task:
run:
  cp ${_input} ${_output}
```

It does not work now. Or am I doing it wrong?

**Comment by BoPeng** [comment]
Should work now.

**Comment by gaow** [comment]
Great it works! I'm changing the title of issue to `_index` related and we can close it after the use of `_index` is disabled officially.

**Comment by BoPeng** [comment]
`_index` is currently passed as a signature variable of tasks so it will take some patience to remove it.

**Comment by gaow** [comment]
Though rarely, it seems we might want to use `_index` at least to get things work before inventing a new feature (eg `output: group_by` and `group_with`). Maybe we can leave `_index` in without documenting it? If so then we are good to close this ticket.

**Comment by BoPeng** [comment]
I agree. `_index` is also used to generate task names which is more straightforward than other names.
