### ISSUE TITLE
Better error handling with `fail_if`

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#716]
Here is a MWE:

```
parameter: K1 = 1
parameter: K2 = 1
stop_if(K1, msg = 'stop here at global')

[1]
stop_if(K2, msg = 'stop here local')
```

Here is the outcome:

```
$ sos run test.sos --K1 1
ERROR: stop here at global
$ sos run test.sos --K1 0 --K2 1
INFO: Executing default_1: 
INFO: input:    []
WARNING: stop here local
INFO: output:   []
INFO: Workflow default (ID=9299f73c394453e4) is executed successfully.
```
It looks like when outside a workflow step `stop_if` can properly stop the workflow with an `ERROR` prompt. Otherwise it is just a `WARNING`, and although it does stop, the finally message would say `executed successfully`. Shouldnt the behavior consistent?

**Comment by BoPeng** [comment]
`stop_if` is designed to skip an input group and is not meant to stop the execution of the workflow, which is performed by  `fail_if`.

`stop_if` in global will stop all steps because global statement will be executed by all steps..., so it is hard to say if the workflow is executed successfully.

**Comment by gaow** [comment]
Ok I see ... my problem with `fail_if` is its ugly output information. This is what happens if I change it to `fail_if`

```
INFO: Executing default_1: 
INFO: input:    []
ERROR: Failed to execute workflow default
[default_1] RuntimeError:
	Failed to process statement "fail_if(K2, msg = 'stop here local')\n" (RuntimeError): stop here local
[default] RuntimeError:
	1 failed step: default_1
```
I guess it would be good enough if we can improve the formatting here.

**Comment by BoPeng** [comment]
I agree. Error handling of sos is not optimal now.
