### ISSUE TITLE
File signature issue: changes to input does not trigger rerun

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#719]
Here is MWE:

```
[1]
parameter: files = ['1.txt']
input: files, group_by = 1
output: [x.replace('txt', 'out') for x in files], group_by = 1
task:
run:
  cp ${_input} ${_output}
```

If I run it for the first time:

```
$ echo "version 1" > 1.txt
$ sos run test.sos
```
then `1.out` should have content `version 1`. But if I change the input file and run:
```
$ echo "version 2" > 1.txt
$ sos run test.sos
INFO: Executing default_1: 
INFO: input:    ['1.txt']
INFO: 477253501b417cca28671b014776ad3a already completed
INFO: output:   ['1.out']
INFO: Workflow default (ID=5746c6767a76e01f) is executed successfully.
```
You see it got skipped wrongfully; nothin is changed in output `1.out`.

In fact at this point even if I remove input file `1.txt` it still runs successfully ...

**Comment by BoPeng** [comment]
Ohmm, tasks somehow only checks `_output`, not `_input` and `_depends` for task status. This has been fixed.
