### ISSUE TITLE
Define `-v1` output for tasks

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#721]
For external tasks, what bothers me is when I run (in simulation workflows) there is a huge number of this type of line generated:

```
INFO: bd37bb9ac1c8cbc1f4e89212a2a0d50f queued
```

which, unlike `start`/`completed` prompts that only show up as the workflow progresses. I tried to use `-v1` but that silences everything (no progress bar). These `queued` lines dont look very useful. I'm wondering if we can replace those `queued` lines with a line of summary showing the number of jobs queued, eg. "N jobs queued"?

**Comment by gaow** [comment]
Or, how about simply moving `INFO: ... queued` to `-v3`?

**Comment by BoPeng** [comment]
How about other status lines, like completed? Another alternative is to use jupyter where you only see changing icons.

**Comment by gaow** [comment]
I think we can keep both `started` and `completed`. At least unlike `queued`  they do not flush the screen all at once with thousands of lines. 

> Another alternative is to use jupyter where you only see changing icons.

It does not really work nicely either when there is thousands of jobs submitted ...

**Comment by BoPeng** [comment]
Removed `queued` message, it was mostly added for debugging anyway.

**Comment by gaow** [comment]
Great it reads better now!

**Comment by gaow** [comment]
BTW what happened to progress bar for tasks? Currently with `-v1` there is no output information on the script. Is it possible or easy to bring it back for tracking tasks when `-w`  is specified -- unless we do not know the total number of tasks to be execute at the time progress bar should be initialized?

**Comment by BoPeng** [comment]
I think progress bars are only for steps, not for tasks within a step, right?

**Comment by gaow** [comment]
Yes. Currently for external tasks the `-v1` option has undefined behavior but I'm thinking if we know the total number of tasks it may be straightforward to define a progress bar for `-v1`
