### ISSUE TITLE
Octave appears at the kernel list instead of Matlab sometimes...

### ISSUE THREAD

**Issue by HenryLeongStat** [vatlab/SOS#722]
Sometimes, I see `Octave` at the kernel list instead of Matlab at jupyter... 

<img width="836" alt="screen shot 2017-07-24 at 9 52 49 pm" src="https://user-images.githubusercontent.com/26916551/28553658-afd79a7e-70ba-11e7-936f-f4d4aa4035f1.png">

**Comment by BoPeng** [comment]
This might be related to #704. Is `octave` shown in `jupyter kernelspec list`?

**Comment by HenryLeongStat** [comment]
No, `octave` isn't shown in `jupyter kernelspec list`. 
<img width="649" alt="screen shot 2017-07-24 at 10 04 16 pm" src="https://user-images.githubusercontent.com/26916551/28553963-3185851c-70bc-11e7-9d33-15bf04351a0a.png">

**Comment by BoPeng** [comment]
I have re-opened #704

**Comment by BoPeng** [comment]
Let me know if you still see this.

**Comment by HenryLeongStat** [comment]
Still see it... 
<img width="830" alt="screen shot 2017-07-24 at 11 59 28 pm" src="https://user-images.githubusercontent.com/26916551/28556466-32b0a2cc-70cc-11e7-8f8c-81660b30a33e.png">

**Comment by BoPeng** [comment]
After `git pull` and `python setup.py install`?

**Comment by HenryLeongStat** [comment]
Forgot to `git pull` just now... I will keep tracking it!

**Comment by BoPeng** [comment]
seems to be fixed.
