### ISSUE TITLE
codemirror fold code to save screenspace

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#725]
One of the problems of jupyter notebook is that cells can be large, making navigation a bit difficult. It can be helpful to fold long source code like [here](https://codemirror.net/demo/folding.html).

**Comment by gaow** [comment]
This should be extremely helpful -- can it also work for the resulting HTML from `sos convert`?

**Comment by BoPeng** [comment]
This is certainly possible but I am not familiar with codemirror stuff. On Jupyter code mirror is already there so I could possibly do this by changing the options of cell codemirros.

**Comment by BoPeng** [comment]
The following is supposed to work but it does not. Need to spend more time on it.

```difff
diff --git a/src/sos/jupyter/kernel.js b/src/sos/jupyter/kernel.js
index 195bcb2e..dff4d8bb 100644
--- a/src/sos/jupyter/kernel.js
+++ b/src/sos/jupyter/kernel.js
@@ -24,7 +24,10 @@ define([
     "jquery",
     "base/js/utils",
     "codemirror/lib/codemirror",
-    "codemirror/addon/selection/active-line"
+    "codemirror/addon/selection/active-line",
+    "codemirror/addon/fold/foldcode",
+    "codemirror/addon/fold/foldgutter",
+    "codemirror/addon/fold/indent-fold"
 ], function($) {

     "use strict";
@@ -734,6 +737,11 @@ define([
                var i;
         for (i = cells.length - 1; i >= 0; --i) {
             cells[i].code_mirror.setOption("styleActiveLine", cells[i].selected);
+            cells[i].code_mirror.setOption("foldGutter", true);
+            cells[i].code_mirror.setOption("tabSize", 4);
+                       cells[i].code_mirror.setOption("lineNumbers", true);
+                       cells[i].code_mirror.setOption("linewrapping", true);
+                       cells[i].code_mirror.setOption("gutters", ["CodeMirror-linenumbers", "CodeMirror-foldgutter"]);
                }
         return true;
     }
@@ -1629,6 +1637,27 @@ define([
 .lev6 {margin-left: 10px}
 .lev7 {margin-left: 10px}
 .lev8 {margin-left: 10px}
+
+.CodeMirror-foldmarker {
+  color: blue;
+  text-shadow: #b9f 1px 1px 2px, #b9f -1px -1px 2px, #b9f 1px -1px 2px, #b9f -1px 1px 2px;
+  font-family: arial;
+  line-height: .3;
+  cursor: pointer;
+}
+.CodeMirror-foldgutter {
+  width: .7em;
+}
+.CodeMirror-foldgutter-open,
+.CodeMirror-foldgutter-folded {
+  cursor: pointer;
+}
+.CodeMirror-foldgutter-open:after {
+  content: "\25BE";
+}
+.CodeMirror-foldgutter-folded:after {
+  content: "\25B8";
+}
 `;
             document.body.appendChild(css);
         };
```

**Comment by gaow** [comment]
I'm cool with manual folding: we can fold some large cells only when they bother us. Typically in one notebook there should not be too many such cells. I just tried it out -- it does not seem to impact the output HTML though. That would be quite useful to have, for sharing with other people. For example there is an option in Rmarkdown output HTML that hides all scripts so that the readers can focus on the results. Would be great if we can have output folded even by default.

**Comment by BoPeng** [comment]
I am not particularly happy with the blank box before text in most small cells. I think I will make the folding column narrower and remove the right border so make it more natural.

sos provides its own way to hide input, see [this example](http://vatlab.github.io/SOS/doc/examples/Preview_and_Report_Generation.html) for details.

**Comment by BoPeng** [comment]
Changed from
![image](https://user-images.githubusercontent.com/9889312/28834666-84a0355c-76a8-11e7-91da-34b37068d3cd.png)
to
![image](https://user-images.githubusercontent.com/9889312/28834794-f45caf74-76a8-11e7-889f-437232ff1bb7.png)

**Comment by BoPeng** [comment]
Ohmm, we should perhaps use the [existing mechanism](http://jupyter-notebook.readthedocs.io/en/latest/frontend_config.html) and let users configure code mirror. This will actually work better because Jupyter will use it for new cells (right now when we do `Shift-Enter`, the newly created cell does not have the folding column until we click on that cell).

**Comment by BoPeng** [comment]
I could get the options set for cells with 
```
  "CodeCell": {
  "cm_config": {
        "gutters": ["CodeMirror-foldgutter"],
        "foldGutter": true
    }
  }
```
added to `~/.jupyter/nbconfig/notebook.json` but I cannot yet get the folding option works. Seems to be a problem with loading the indent-fold module.

**Comment by BoPeng** [comment]
Finally, this folding stuff is not in the way for small cells.... I am happy with this behavior and will close the ticket.
