### ISSUE TITLE
Matlab passed the manual test but Octave didn't...

### ISSUE THREAD

**Issue by HenryLeongStat** [vatlab/SOS#726]
It seems they are different for the process of saving the data as `.mat` to the temporary file... Trying to figure out the problem.....

`Matlab`:
<img width="727" alt="screen shot 2017-07-25 at 11 13 40 pm" src="https://user-images.githubusercontent.com/26916551/28604252-ef8542be-718e-11e7-824c-49127e228d3b.png">

`Octave`:
<img width="721" alt="screen shot 2017-07-25 at 11 14 36 pm" src="https://user-images.githubusercontent.com/26916551/28604279-1713a4e2-718f-11e7-8f5d-b3e0dc392c20.png">

**Comment by HenryLeongStat** [comment]
The locations of temporary file are different between two languages. However, base on `sos_py_repr.m`, it isn't likely to be the problem...

<img width="734" alt="screen shot 2017-07-26 at 12 04 26 am" src="https://user-images.githubusercontent.com/26916551/28605229-04f04f48-7196-11e7-8f34-f12507266ec0.png">

**Comment by BoPeng** [comment]
You will have to separate the cell and figure out which statement, and which variable is causing the problem. If we cannot find a compatible way, we might have to have separate `.m` files for Matlab and Octave.

**Comment by HenryLeongStat** [comment]
Understood! I'm working on it.

**Comment by HenryLeongStat** [comment]
Finally figured out the problem! For example, if we want to transfer a matrix from `Octave` to `SoS`, using `save(fullfile(tempdir, 'mat2py.mat'), 'obj');`, which works in `Matlab`, would also works in `Octave`, but the `.mat` file created by `Octave` isn't readable. Instead, we should use `save -6 mat2py.mat` in `Octave`. However, this function doesn't contain the location parameter, so we simply need to change the working directory (use cd(tempdir)) before save the `.mat` file. 
Also, it seems `isstr' is going to be removed from `Octave`, and we will use `ischar` to replace it.

All in all, as Dr. Peng said, we have to separate .m files for Matlab and Octave.

**Comment by gaow** [comment]
I was under the impression the two are compatible in basic formats ... if it is too much trouble (more than variable name changes) to support Octave perhaps we can mark it for later until there is a need? I was just talking to stats and machine learning colleagues here. What I learned was that octave is only used by some professors teaching undergrad courses. Serious researchers always use matlab. Even grad student researchers would pay for private license out of pocket than using octaves instead, if they do want to install matlab on their personal computers.

**Comment by HenryLeongStat** [comment]
Update: the problem should be solved now, Dr. Peng found the common function between `Octave` and `Matlab`.

**Comment by HenryLeongStat** [comment]
Both `Matlab` and `Octave` passed the manual test now! 
<img width="852" alt="screen shot 2017-07-26 at 2 57 19 pm" src="https://user-images.githubusercontent.com/26916551/28640875-c0c2d99e-7212-11e7-8abf-b6283979787c.png">

**Comment by BoPeng** [comment]
I was playing the number game here to increase the number of supported languages, which we now have 8 for 6 distinct languages. I know nothing about [TypeScript](https://www.typescriptlang.org/) but we could make TypeScript work because apparently it is based on JavaScript and could almost certainly use the JavaScript language module for it.

**Comment by BoPeng** [comment]
Another value for Octave is that we cannot test matlab because of license issue but we can test octave on TravisCI.

**Comment by gaow** [comment]
@BoPeng good call!
