### ISSUE TITLE
test imatlab

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#730]
[imatlab](https://github.com/imatlab/imatlab) is derived from `matlab_kernel`. If it works, we should update installation instruction and list it as one of the supported kernels.

**Comment by HenryLeongStat** [comment]
For `imatlab`, when we use magic `%put` for `num_arr_var` to `SoS`, the following error message appears, and it seems is the problem of `imatlab`'s kernel itself:
<img width="864" alt="screen shot 2017-07-28 at 4 08 04 pm" src="https://user-images.githubusercontent.com/26916551/28736376-2e6d015c-73af-11e7-8d3c-a397fb44eb9e.png">
