### ISSUE TITLE
`download` action bug

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#732]
Here is a MWE:

```
[download: provides="master.zip"]
download: decompress = True
 https://github.com/pditommaso/awesome-pipeline/archive/master.zip
```
and the output of execution:
```
$ sos run test.sos -t master.zip
INFO: Resolving 1 objects from 0 nodes
INFO: Target master.zip already exists
INFO: Executing download: 
master.zip: 
ERROR: [download ['master.zip']]: Failed to process statement download(r"""https://github.co...s = True)\n (RuntimeError): Not all files have been downloaded

```

There are two problems: 

1. `master.zip` does not exist yet the INFO lines says it does
2. There is an error message raised, even when the download / decompress process actually was successful. 

BTW in this case the provided target is in fact a folder ... so if I manually remove the decompressed folder after download, and I run this script again it will not extract anything, thus creating problems. How can I avoid that? (other than extracting it later in other steps)

**Comment by BoPeng** [comment]
Failed to test decompress zip files with directories. Should have been fixed.

**Comment by gaow** [comment]
Yes!
