### ISSUE TITLE
Execution graph of Make style in nested workflow with `sos_run`

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#733]
I find it useful to have some "template" step that does not have any input / output files specified when they are defined;  but will take later those values from elsewhere and execute. That way a "template" can be used by many other steps without having to repeat itself. Currently the only way seems to be using `sos_run` and I have a toy example here that attempts to achieve this:

```
[template1]
parameter: output_files = list
output: output_files, group_by = 1
task:
bash:
  sleep 1
  touch ${_output}

[template2]
parameter: input_files = list
parameter: output_files = list
input: input_files, group_by = 1
output: output_files, group_by = 1
task:
bash:
  sleep 1
  echo ${_input} > ${_output}

[main1: provides = "1.txt"]
output: "1.txt"
sos_run("template1", output_files = ["1.txt"])

[main2: provides = "2.txt"]
depends: "1.txt" 
output: "2.txt"
sos_run("template2", input_files = ["1.txt"], output_files = ["2.txt"])

[main3: provides = "3.txt"]
output: "3.txt"
sos_run("template1", output_files = ["3.txt"])

[main4: provides = "4.txt"]
depends: "3.txt" 
output: "4.txt"
sos_run("template2", input_files = ["3.txt"], output_files = ["4.txt"])

[default]
depends : "2.txt", "4.txt"
```

The script works but the execution reads process is a bit weird. Seems the same file are generated multiple times. With `-s force` it will throw an error ... I cannot figure out why it went wrong. To me it does not seem to generate a proper DAG. If I do not use the nested workflow idea and write it like:

```
[main1: provides = ["1.txt"]]
parameter: output_files = ["1.txt" ]
output: output_files, group_by = 1
task:
bash:
  sleep 1
  touch ${_output}

[main2: provides = ["2.txt"]]
parameter: input_files = ["1.txt"]
parameter: output_files = ["2.txt"]
depends: input_files 
input: input_files, group_by = 1
output: output_files, group_by = 1
task:
bash:
  sleep 1
  echo ${_input} > ${_output}

[main3: provides = ["3.txt"]]
parameter: output_files = ["3.txt" ]
output: output_files, group_by = 1
task:
bash:
  sleep 1
  touch ${_output}

[main4: provides = ["4.txt"]]
parameter: input_files = ["3.txt"]
parameter: output_files = ["4.txt"]
depends: input_files 
input: input_files, group_by = 1
output: output_files, group_by = 1
task:
bash:
  sleep 1
  echo ${_input} > ${_output}

[default]
depends : ["2.txt", "4.txt"]
```
the DAG looks different but still not correct. 

I'm wondering 1) what's wrong with my scripts, and 2) regardless of my mistakes made, how can I use the idea of "template" in Make style yet still properly trigger the correct execution graph, as if I repeatedly write the same "template" multiple times as the 2nd script above?

**Comment by gaow** [comment]
Sorry there was a typo in my script in the previous thread that I just fixed. But my question still stands, that how to properly make "template" steps that looks like my script 1 syntax-wise, but I can get a behavior of script 2 (which has repeated codes in itself)?

**Comment by BoPeng** [comment]
Without checking your code, is not `provides='{file}.bai'` designed for such purposes?

**Comment by BoPeng** [comment]
I mean, essentially speaking, to instantiate (activate whatever) a template, there should be someway to locate and fill them with parameters, and this is what `provides` is designed for.

**Comment by gaow** [comment]
Indeed, my script here can trivially be written with `provides = {pattern}`. I should have made it clear that the provided file here in fact can be of arbitrary pattern. So instead of wildcard sigil I'll provide the full file name explicitly, as if passing parameter to a function. I know that sounds like it is best achieved via forward style, however forward style does not build a DAG and parallel as much as possible. This is why I'm looking to do it with Make style.

**Comment by gaow** [comment]
I think i should make my case better with a different example: say, for instance, what I want to change is not a target, but just a parameter. The only way to do it now is via nested workflow:

```
[template]
parameter: beta = float
task:
...

[default]
sos_run('template', beta = 2)
```

But this is much simpler than a `nested` workflow. It is more of something like:

```
[template]
parameter: beta = float
task:
...

[default: derived_from = "template"]
parameter: beta = float
```
And under the hood SoS just copy all text from `template`, update it with whatever new in `[default]` and execute it. No nested workflow is necessry. Using `sos_run` seems to messed up the DAG. For example in my previous thread, the first DAG looks like:

```
strict digraph "" {
template1_0;
}
```
but it should in fact look like my 2nd DAG:

```
strict digraph "" {
default_0;
"main2 ['2.txt']";
"main4 ['4.txt']";
"main1 ['1.txt']";
"main3 ['3.txt']";
"main2 ['2.txt']" -> default_0;
"main4 ['4.txt']" -> default_0;
"main1 ['1.txt']" -> "main2 ['2.txt']";
"main3 ['3.txt']" -> "main4 ['4.txt']";
}
```

**Comment by BoPeng** [comment]
Still not convinced .. :-)

**Comment by BoPeng** [comment]
Parallelization of forward-style workflow depends on how many root left in the DAG, because multiple steps could be started as soon as their dependencies have been met/executed. This is the same as makefile style. The major difference is that in make style it is easy to think of branches grown from root (final target) that can be executed in parallel, and in forward-style you have to manually specify `branches` (namely `input: None`) to let them execute in parallel.
