### ISSUE TITLE
Behavior of `paired_with` when used in conjunction with `group_by` 

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#734]
I'm trying to write a mixed-style SoS but got stuck at what boils down to this MWE:

```
input_files = ['{}.txt'.format(x) for x in range(5,9)]
data = [('1.txt', '2.txt'), ('3.txt', '4.txt')]

[1]
output: input_files
run:
 touch ${output}

[2]
input: input_files, group_by = 2, paired_with = "data"
print("${_input}")
print("${_data}")
```

I expect this script to work because it feels natural that when used with `group_by` the `paired_with` option should apply to input groups. However it does not work. In this case I can potentially "flat" `data` and get it work, but there may be cases when each group of `data` has different number of elements than each group of `input`. Should we change the behavior of `paired_with` for this case?

**Comment by BoPeng** [comment]
Because we can `group_by` in many different ways, `paired_with` always pair to raw input file list, and the **paired variables stick to and group with the input files.**

**Comment by BoPeng** [comment]
That is to say, we apply `paired_with` before `group_by`. Your method requires `paired_with` to match input groups after `group_by` and will be more difficult to use because you will need to manually group your variables that matches `group_by`.

**Comment by gaow** [comment]
In my case the variables are already grouped. Without doing so, then how can we handle the case where we have input `[a,b,c,d]`, grouped by 2, to be paired with something like `[(e,f,g), (h,i,j)]`? This seems impossible using current implementation.

**Comment by BoPeng** [comment]
By design, `paired_with` annotates input files so the paired-with variable will have the same dimension as `_input`.  For example, if you have `input=[a, b, c, d]`, `paired_with=K` where `K=[A,B,C,D]`, and group_by='combination', then for `_input=[a, c]` we always know `_K=[A,C]`.

Your case sounds like an example for `_index`.

**Comment by gaow** [comment]
Right, I understand the design but am proposing changes to it to handle the case I have here, without having to use `_index` (because we are soon to banish it?). If you see there is more problem than benefits to change it then I'll not insist. 

Could you let me know then what's the recommended syntax for [this line](https://github.com/vatlab/SOS/blob/master/docs/src/examples/LP_Mixed.sos#L74) without changing the behavior?

**Comment by BoPeng** [comment]
Use `pattern` to extract `id` and define `datafile` with it?

**Comment by BoPeng** [comment]
We could separate `paired_with` to `pair_input_with` and `pair_group_with`.

**Comment by gaow** [comment]
> We could separate paired_with to pair_input_with and pair_group_with

this certainly sounds the best way out! I'm wrestling with `pattern` but find it difficult and ugly ...

**Comment by BoPeng** [comment]
Well, you liked and pushed `pattern` a lot before...

**Comment by BoPeng** [comment]
Shorter names than `pair_input_with` and `pair_group_with`? How about `paired_with` and `group_with`? At least we do not need to rename `paired_with`.

**Comment by gaow** [comment]
Great -- that also ensures backwards compatibility.

**Comment by BoPeng** [comment]
Technical question, should `group_with` be applied before or after `for_each`?

**Comment by gaow** [comment]
I think should be before `for_each` because the behavior should be the same as groups of input.

**Comment by gaow** [comment]
@BoPeng Seems to be working nicely! At least my updated examples work. So you may close this ticket if tests on your end also look good.
