### ISSUE TITLE
Implement a `no_wait` feature for actions and nested workflows

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#735]
SoS nested workflow executes sequentially. It makes it hard to parallel scenarios like: 

```
sos_run('A+B+C')
sos_run('A+D+C')
```
where B and D can in principle execute at the same time as long as A completes. Currently the only way to make it happen is to write the script in `Make` style. Here we propose:

```
sos_run('A+B+C', no_wait = True)
sos_run('A+D+C', no_wait = True)
```
and for actions 

```
run: no_wait = True
...

python: no_wait = True
```

For nested workflow this will result in consolidating these sequences to the master DAG before execution. For actions this will result in no_wait actions to be sent to background for execution while the executor takes in the next action in line.

**Comment by BoPeng** [comment]
This is not possible given our existing way of implementation... `sos_run` is even disabled for steps with `concurrent=True` (#901).
