### ISSUE TITLE
Infinite loop with explicit dependency

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#736]
Here is MWE:

```
[provider]
input: None
output: '1.out'
task:
run:
 touch 1.out

[main-A]
depends: sos_step('provider')
input: None
output: '2.out'
task:
run:
 touch 2.out

[main-B]
depends: sos_step('provider')
input: None
output: '3.out'
task:
run:
 touch 3.out

[1]
sos_run('main-A+main-B')
```

This script loops infinitely ... output for `main-B` is never generated.

**Comment by BoPeng** [comment]
This bug looks scary but boils down to a small bug that prevents step dependencies to be correctly generated when `depends` is specified before `input`.

**Comment by gaow** [comment]
Haha thanks to our difference in coding style -- I do write `depends` before `input` for all my scripts. It works for the MWE and for my code!

**Comment by gaow** [comment]
Again got into this infinite loop issue with script below:

```
[print]
print("Hi")

[default]
depends: ['1.txt'] 

[A_1]
sos_run('print')

[B_1]
depends: sos_step("A_1")
sos_run('print')

[C_1: provides = ["1.txt","2.txt"]]
depends: sos_step("A_1"), sos_step("B_1")
run:
touch 1.txt 2.txt
```

May still be a simple fix to get such "nested" depend to work? 

BTW github is acting up now:

https://status.github.com/graphs/past_day

**Comment by BoPeng** [comment]
This is related to how auxiliary steps are referred .... should have been fixed.

**Comment by gaow** [comment]
Great -- indeed!

**Comment by BoPeng** [comment]
Just for the record,  auxiliary steps were designed to have no index (because they are single steps) so sos only calls them by name even if an index is provided. This is why `sos_step('A_1')` were not matched successfully because `A_1` is named `A` internally.
