### ISSUE TITLE
Change of parameter does not trigger rerun

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#739]
For this example:

```
parameter: n = 2

[init]
output: 'x.out'
task:
run:
 echo ${n} > x.out
print('init')

[run: provides = 'x.out']
sos_run('init')

[1]
depends: "x.out"

```

changing `--n` cannot trigger script rerun ...

**Comment by BoPeng** [comment]
The problem here is that nothing has changed to the eye of step `run`...so it can be a bad idea to use global variable here. The step would rerun with the following change

```
parameter: n = 2

[init]
parameter: m=int
output: 'x.out'
task:
run:
 echo ${m} > x.out
print('init')

[run: provides = 'x.out']
sos_run('init', m=n)

[1]
depends: "x.out"
```

although I am not saying this is the way to go.

**Comment by gaow** [comment]
I see ... my user case is more complicated than this (I was using the notion of `template` without having to pass through `sos_run` all parameters). My case was more like:

```
[template]
parameter: n = 2
parameter: x = 3
...
```
where there are a lot of parameters and I'd only manually change them from here. I take that to the eye of `sos_run('template')` still nothing has changed even when I change the parameter setting in the step.

**Comment by BoPeng** [comment]
So considering the fact that `sos_run` expands the "scope" of signatures beyond the current step, the only sensible way to make this work is to actually execute the `sos_step` and let the nested workflows verify their signatures. To do this, we will have to ignore signatures of all steps with `sos_run`.

**Comment by gaow** [comment]
>   actually execute the sos_step and let the nested workflows verify their signatures

Sounds like also solution to https://github.com/vatlab/SOS/issues/733 ? I think a few things that we've been talking has to do with what is the proper behavior of nested workflow ...

**Comment by BoPeng** [comment]
Submitted a patch to disable signature for steps with action `sos_run`. Please test it.

**Comment by gaow** [comment]
It works for the MWE, but seems to still have some issues with one of my script. I'm investigating that. Will report or close ticket when I find out what's going on there ... Thanks!

**Comment by gaow** [comment]
I now see changing my parameter will result in re-run though I"m not sure yet if it is correct number of jobs gets re-executed: correct means if I count the number of jobs restarted it should match the number of all the downstream after the step modified. 

Is there a way to preview / count that easily? I was trying to use `-n` but it does not make any difference. I'm closing this issue now. Please let me know if it warrants to open another issue to request some status report on which jobs will be rerun in `-n` mode.

**Comment by BoPeng** [comment]
I think you can use `sos status` to check number of running jobs easily.
