### ISSUE TITLE
Weird output status

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#740]
I'm running into an error in one of my scripts that I'm trying to re-write & test but I cannot make a MWE out of it to show the failure. Basically when I first run the script everything is fine, but when I run again with `-s force` it quits on error that complains about `signature mismatch`. Using `sos status ... -v 4 ` I find weird `output` recorded, that the `output` list is shorter than it's supposed to be. 

Here this MWE cannot reproduce the failure but can reproduce the weird `output`:

```
num = 10
n = [x for x in range(num)]
parameter: file_set1 = ["1_{}.out".format(x) for x in range(num)]
parameter: file_set2 = ["2_{}.out".format(x) for x in range(num)]

[init1]
parameter: input_files = list
parameter: output_files = list
input: for_each = ['n']
output: output_files, group_by =  1
task:
run:
 echo ${_n} > ${_output}
print('init1')

[init2]
parameter: input_files = list
parameter: output_files = list
input: dynamic(input_files), group_by = 1
output: output_files, group_by =  1
task:
run:
 echo ${_input} > ${_output}
print('init2')

[run_A]
output: file_set1
sos_run('init1', input_files = [], output_files = file_set1)

[run_B: provides = file_set2]
depends: sos_step("run_A")
output: file_set2
sos_run('init2', input_files = file_set1, output_files = file_set2)

[1]
depends: file_set2
```

If I run it for the first time, and check status of the last task, I see this:

```
...
input                 ['1_0.out',
 '1_1.out',
 '1_2.out',
 '1_3.out',
 '1_4.out',
 '1_5.out',
 '1_6.out',
 '1_7.out',
 '1_8.out',
 '1_9.out']
output                ['2_0.out',
 '2_1.out',
 '2_2.out',
 '2_3.out',
 '2_4.out',
 '2_5.out',
 '2_6.out',
 '2_7.out',
 '2_8.out',
 '2_9.out']
...
```
which is expected. But after I rerun with `-s force` and checking the last task I see:

```
input                 ['1_0.out',
 '1_1.out',
 '1_2.out',
 '1_3.out',
 '1_4.out',
 '1_5.out',
 '1_6.out',
 '1_7.out',
 '1_8.out',
 '1_9.out']
output                ['2_0.out', '2_1.out']

```
which only shows 2 files though the script completed without an issue. I'm not sure if it is the cause to my `signature mismatch` problem but it is a weird observation.

**Comment by BoPeng** [comment]
This is unrelated because what matters is `_input` and `_output` (which in this case should be single files). `output`, as I have explained before, is accumulated from `_output` so it can have any number of files depending on which task you peeked.

**Comment by gaow** [comment]
Ok what bothers me is the **inconsistency** between runs with/without `-s force`. Yes I do remember the case when `output` is accumulated but that was consistent ...

If this is not the problem, what could be the cause of `signature mismatch` error -- what should I do to debug? `-v 4` does not show anything more useful. I'm under the impression that `-s force` should redo whatever has previously been done, so having `signature mismatch` in this context makes me confused.

**Comment by BoPeng** [comment]
Who is generating `signature mismatch`? A step or a task?

**Comment by gaow** [comment]
A task. I am using tasks for all my heavy-duty work now. 

```
TRACE: Start submitting b80b727723ba6251ebb7f1b7cecdec1b (status: pending)
WARNING: 17f14c30a8c884c11d58eeeb2b90050b signature-mismatch
WARNING: a36ee48be7a449eb3481d53ca668c46e signature-mismatch
WARNING: 9faca6feed2441ac79b19ee5fb7f9030 signature-mismatch
WARNING: 9b370d1b419a5ad8f8fbbcdd32510771 signature-mismatch
WARNING: 11e62845b8cbb560596b4bda1ba8e23d signature-mismatch
WARNING: f9927756d7ee816ee939da51ab179df1 signature-mismatch
INFO: 17f14c30a8c884c11d58eeeb2b90050b.out:

INFO: 17f14c30a8c884c11d58eeeb2b90050b.err:
2017-07-31 21:59:25,181: DEBUG: Failed to load target docker_build: The 'docker' distribution was not found and is required by the application
2017-07-31 21:59:25,491: INFO: 17f14c30a8c884c11d58eeeb2b90050b ``started``
2017-07-31 21:59:25,516: DEBUG: Script for step core_estimate_0 is saved to /home/gaow/tmp/sim_dat/.sos/core_estimate_0_0_6c5ffa64.R
2017-07-31 21:59:26,044: INFO: 17f14c30a8c884c11d58eeeb2b90050b ``completed``
...
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.9-py3.6.egg/sos/sos_executor.py", line 902, in run
    raise RuntimeError(', '.join(['{} job{} {}'.format(y, 's' if y > 1 else '', x) for x,y in status if y > 0]))
RuntimeError: 14 jobs completed, 6 jobs result mismatch
ERROR: 14 jobs completed, 6 jobs result mismatch

```

Also maybe we want to remove the line 

```
2017-07-31 21:59:25,181: DEBUG: Failed to load target docker_build: The 'docker' distribution was not found and is required by the application
```
from `err`.

**Comment by BoPeng** [comment]
This sounds like the task could not find the output that is supposed to be generated.... we should perhaps add debug message for what target causes this warning.

**Comment by gaow** [comment]
> This sounds like the task could not find the output that is supposed to be generated...

It was indeed the case. I see you added some debug info for it though I figured out my issue before you test it. I'm closing this ticket for now.
