### ISSUE TITLE
SoS Notebook kernel issues: proper error / exception handling

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#744]
I'm going over example `Preview_and_Report_Generation.ipynb`. I have 2 questions / issues:

1. I've noticed that when I open the notebook there are a number of kernels from the drop down manual. But my computer does not have all of them. For example `SAS`. Trying to turn them on and load data leads to confusions, because there is no error message as if it is a success. However when I turn it off and load it again, those kernels goes away. Is there an easy way to load only kernels the system has? Of course if a cell indeed uses `SAS` then it should throw an error.

2. What's the difference between `ir` and `R` kernels? I recently reconfigured my R. My notebook always shows `ir` when I create a new SoS notebook. However I'd run into this error below with magic `%get`:

![2017-08-03-21-20-05_scrot](https://user-images.githubusercontent.com/917985/28951926-81872fe6-7893-11e7-8b7a-2ec2d3b091eb.png)

But interestingly even without showing `R`, if an SoS notebook comes with `R` kernel name then it will indeed work on my computer, even is able to `%get` data! So what's the deal with `ir`?

**Comment by BoPeng** [comment]
For the first issue, the problem is that when a computer has the SAS kernel, it will be made available to the frontend and be saved in the ipynb file. There is no change to remove them before the file is closed. I suppose what we need to do is to remove unused kernels when a notebook is opened.

The `ir` kernel is displayed when a `ir` kernel exists but no language module can be used, which can be the case when `r-feather` or python `feather-format` is not available. In this case no `%get` etc can be used. Your case seems to point to another possibility, namely a `ir` kernel was saved in `ipynb` file and is used later when the notebook is opened on a system with correct R installation. Changing the kernel from `ir` to `R` is supposed to fix the probe.

**Comment by gaow** [comment]
I see ... great pointer! After manually install `feather-format` on my recently configured `conda`, I see `R` instead of `ir` in my new notebooks. But `feather-format` is supposedly installed with SoS because it is in `setup.py`! 

Also I do not have `r-feather` so after fixing it on Python end I get:

![2017-08-03-21-48-10_scrot](https://user-images.githubusercontent.com/917985/28952529-5ff6e8b8-7897-11e7-85dc-93ffce4c993a.png)

Would be good to improve various messages here. I'm changing the ticket title and keep it open.

**Comment by BoPeng** [comment]
Ok, it turns out the kernel list was correctly populated but the unused kernels are displayed first and are not removed by the correct list. This has been fixed.

**Comment by BoPeng** [comment]
For the second problem, we cannot display an error message with all kernels with incorrect language module because the kernel might not be used by the notebook. A proper error message would be shown if users run `%use R`.

**Comment by gaow** [comment]
> A proper error message would be shown if users run %use R.

Not the case for me:

![2017-08-03-21-48-56_scrot](https://user-images.githubusercontent.com/917985/28953085-6cd62b94-789b-11e7-9271-4d3b02ca8e0f.png)

**Comment by BoPeng** [comment]
Did you restart jupyter server after fixing feather? From the code

```
            # let us check if there is something wrong with the pre-defined language
            for entrypoint in pkg_resources.iter_entry_points(group='sos_languages'):
                if entrypoint.name == name:
                    # there must be something wrong, let us trigger the exception here
                    entrypoint.load()
            # if nothing is triggerred, kernel is not defined, return a general message
            raise ValueError('No pre-defined subkernel named {} is found. Please define it with one or both of parameters --kernel and --language'.format(name))
```
the entrypoint should raise an error before reaching `No pre-defined...`. If you see the samething after restarting the server, please add "self.warn(entrypoint.name)" to see if the entrypoint is correctly iterated.

**Comment by gaow** [comment]
Well, after fixing `feather` it simply worked -- `ir` is replaced by `R`. It would be helpful if it shows some prompt to let me install `feather-format` in the first place. But again isn't that automatically installed by the setup file? I take that it somehow failed because a direct pipe install for feather-format did not work for me. I had to try a few things to get it finally installed.

**Comment by BoPeng** [comment]
`feather-format` is **not** automatically installed because it is added to the `extras_require` section.  You would have to do something like `pip install sos[R]` to install it. I do not know how to trigger that from `python setup.py install`.

**Comment by gaow** [comment]
I see. This is good to know. Then we should not blame users when they do not have `feather-format` installed :) An improved error message might help here.

**Comment by BoPeng** [comment]
OK, here you go. Note that the error message will be displayed in the console so it is very likely that users will not notice it. We cannot show the message in notebook because a notebook might not be ready and even if it is ready, users might be annoyed by a message from a kernel he is not interested in.
