### ISSUE TITLE
Improve error message for external tasks

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#748]
I find the error prompt here is not ideal:

```
ERROR: 1a3273c5b127f0cb34aa5e2ac62f9d58 failed with RuntimeError error Failed to execute script (ret=1).
Please use command
	Rscript \
	  --default-packages=datasets,methods,utils,stats,grDevices,graphics \
	  /home/gaow/tmp/test/.sos/core_fl_0_16_e3e26db7.R
under "/home/gaow/tmp/test" to test it.
```

For this example the computation is quite heavy. It takes up to an hour to reproduce the error. When executed as non-task the error message would dump on the screen, which is ugly but can give people some hints. 

However here apparently one can see the error message via `sos status 1a3273c5b127f0cb34aa5e2ac62f9d58 -v 4`. That opens the err file which has more information including the prompt above. That can save people from re-running. I'm wondering if it is possible to distinguish between task/non-task case and ask users to use `sos status` to check the job, instead of suggesting a rerun.

**Comment by BoPeng** [comment]
This should be easy. Just add its own error handling in the task handling case at [here](https://github.com/vatlab/SOS/blob/master/src/sos/actions.py#L276).

**Comment by gaow** [comment]
Ok, now the `task` error prompt is informative and running the `sos status` command it suggests leads to this output:

```
2017-08-08 22:29:07,479: INFO: 74c8c74a2a2fdd9db9c753dcc1f17015 ``started``
Error in 1:NA : NA/NaN argument
Execution halted
2017-08-08 22:29:08,687: ERROR: 74c8c74a2a2fdd9db9c753dcc1f17015 ``failed``: Use "sos status 74c8c74a2a2fdd9db9c753dcc1f17015 -v4" for details.
Task 74c8c74a2a2fdd9db9c753dcc1f17015 exits with code 1
74c8c74a2a2fdd9db9c753dcc1f17015.out:
=====================================
```

Which is very helpful as it displays error from R. However now the last line is also changed to 

```
2017-08-08 22:29:08,687: ERROR: 74c8c74a2a2fdd9db9c753dcc1f17015 ``failed``: Use "sos status 74c8c74a2a2fdd9db9c753dcc1f17015 -v4" for details.
```

which is not as informative compared to something like

```
ERROR: 1a3273c5b127f0cb34aa5e2ac62f9d58 failed with RuntimeError error Failed to execute script (ret=1).
Please use command
	Rscript \
	  --default-packages=datasets,methods,utils,stats,grDevices,graphics \
	  /home/gaow/tmp/test/.sos/core_fl_0_16_e3e26db7.R
under "/home/gaow/tmp/test" to test it.
```

Can we have some "hybrid" behavior here?

**Comment by BoPeng** [comment]
That is a separate issue from task output. The "Please use command" part takes several lines so I tried to compact it a bit. I also tend to change "under xxx" to "cd xxx; Rscript ..." because it makes it easier just to copy the command. You can revert [the code](https://github.com/vatlab/SOS/commit/b41531249673caf6ceb65c737dd5785ad1c723ea) if you like.

**Comment by gaow** [comment]
Oh no, I'm cool either way (though may think of some format improvements without expanding the output too much). I was just copying an old example from above. What am saying is:

## Old behavior

1. Show `failed to run <command> <script>` and quit

## Current behavior
1. Show `sos status ID -v4` to  direct users for more details, and quit
2. User follow the instruction, and display
   a. Exact error prompt
   b. again the instruction to run `sos status`

My point is that current behavior 1 is good. Also 2a is very informative because I can immediately see what's the problem. However if I cannot eyeball the bug, or want to use some example script to reproduce it, then I hope to have old behavior 1 as the next step to replace the current 2b.

**Comment by BoPeng** [comment]
2b is there because task hijacks logging error message to `.err` file. Anyway, the code is straightforward to change and you can adjust it to your liking. I do not have a strong opinion to it, although if you would like to restore the old message, having something like `cd xxx; Rscript xxx` would be easier for me to rerun things.
