### ISSUE TITLE
Too many opened files for extern task

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#749]
I ran into this error when I submitted a lot of trivial jobs:

```
ERROR: [Errno 24] Too many open files
```

all my jobs are R jobs and there's no opened files. I suspect it is signature files. I've set `ulimit` to unlimited yet it doesnt work. But maybe  we should have some mechanisms to prevent it from happening in the first place.

**Comment by BoPeng** [comment]
Yes, each job has an open lock file....

**Comment by gaow** [comment]
I see ... this is only problematic when those tasks are very quick. I was not sure of this behavior earlier, because I did have limited `-J 30` so I'd expect only 30 open lock files!

**Comment by BoPeng** [comment]
Do you have an example, using

```
[1]
input: for_each={'i': range(2000)}
task:
sh:
    echo "I am ${i}"
    sleep 1
```

I got something like:

```
$ sos run test
INFO: Executing default_1:
INFO: input:    []
INFO: f706782109d56999c07de911843a1f09 started
INFO: cd66ce88e39195eda6397ff4877c54ca started
INFO: 8f40db1adbb68f27646ebae3fcac323e started
INFO: 9cf26f0a56d3a5dda6082ee586d1d1dc started
INFO: cd66ce88e39195eda6397ff4877c54ca completed
INFO: f706782109d56999c07de911843a1f09 completed
INFO: 8f40db1adbb68f27646ebae3fcac323e completed
INFO: 9cf26f0a56d3a5dda6082ee586d1d1dc completed
INFO: ec21c0fa86884fd178313e7bc2a42446 started
INFO: b580a77bb43d45ff005a4ea3e3b63776 started
INFO: ba05299d8ebf1029edce479c349cde52 started
INFO: ab4230df74137bd31bcc1a97f0c9d5b4 started
INFO: ec21c0fa86884fd178313e7bc2a42446 completed
INFO: b580a77bb43d45ff005a4ea3e3b63776 completed
INFO: ab4230df74137bd31bcc1a97f0c9d5b4 completed
INFO: ba05299d8ebf1029edce479c349cde52 completed
``` 

due to default `max_num_jobs=4` and I do not see any problem with opened file.

**Comment by gaow** [comment]
I'm also trying to reproduce it on MWE ... so far no luck. Maybe it is also computer specific? It is a Make style script Im using:

```
[A]
input: for_each={'i': range(200)}
output: ['/tmp/a{}'.format(x) for x in range(200)] , group_by=1
task:
sh:
    echo > "I am ${i}" > ${_output}


[B]
input: for_each={'i': range(200)}
output: ['/tmp/b{}'.format(x) for x in range(200)] , group_by=1
task:
sh:
    echo > "I am ${i}" > ${_output}

[C]
input: for_each={'i': range(200)}
output: ['/tmp/c{}'.format(x) for x in range(200)] , group_by=1
task:
sh:
    echo > "I am ${i}" > ${_output}


[D]
input: for_each={'i': range(200)}
output: ['/tmp/d{}'.format(x) for x in range(200)] , group_by=1
task:
sh:
    echo > "I am ${i}" > ${_output}


[E]
input: for_each={'i': range(200)}
output: ['/tmp/e{}'.format(x) for x in range(200)] , group_by=1
task:
sh:
    echo > "I am ${i}" > ${_output}


[F]
input: for_each={'i': range(200)}
output: ['/tmp/f{}'.format(x) for x in range(200)] , group_by=1
task:
sh:
    echo > "I am ${i}" > ${_output}

[default]
depends:[sos_step(x) for x in ['A', 'B', 'C', 'D', 'E', 'F']]
```

But interestingly if I set `ulimit -n 300` temporarily, then instead of reproducing that problem I get:

```
ERROR: [A []]: Unable to release an unacquired lock
[B []]: Unable to release an unacquired lock
[E []]: Unable to release an unacquired lock
[C []]: Unable to release an unacquired lock
[D []]: Unable to release an unacquired lock
[F []]: Unable to release an unacquired lock
```

I am not sure if the orginal problem can be reproduced, based on my google search of the error message. But as you said, -J option should limit the number of files opened at the same time -- unless this is not the case, that if a job finishes too soon another file will be opened to record new signature, even before the signature file for the current job is still being opened?

**Comment by BoPeng** [comment]
I cannot reproduce the problem with your case, but let us keep this ticket open and see if we can reproduce it somehow.
