### ISSUE TITLE
External task error: ERROR: 'dummy_node' object has no attribute '_pending_workflow'

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#750]
I cannot provide MWE for this one easily ... but it looks like some bug that can be identified and fixed by looking at the code.

**Comment by BoPeng** [comment]
Line number of the error?

**Comment by gaow** [comment]
Sorry I was too hasty to record that ... will surely run into it again and report from -v 3  then

**Comment by gaow** [comment]
Finally get this:

```
[0m
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/__main__.py", line 350, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
Traceback (most recent call last):
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/__main__.py", line 350, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/sos_executor.py", line 1044, in run
    raise e
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/sos_executor.py", line 835, in run
    if proc[2]._status.endswith('_pending') and proc[2]._pending_workflow == runnable._pending_workflow:
AttributeError: 'dummy_node' object has no attribute '_pending_workflow'
```

It does not happen every time.

**Comment by BoPeng** [comment]
I am not quite comfortable at fixing bugs without knowing the exact reason, but here it goes...

**Comment by gaow** [comment]
I agree. I can do anything to try pinning down the exact reason?

**Comment by BoPeng** [comment]
This is triggered by failure in nested workflow so the worst could be zombie worker, we will see.

**Comment by gaow** [comment]
Yes I use nested workflow a lot, mostly simply as `templates` #733 eg:

```
[template_function]
...

[main_1]
parameters: ...
sos_run('template_function', parameters ...)

[main_2]
parameters: ...
sos_run('template_function', parameters ...)
```

It seems using nested workflow in this case is a real waste ... I do think it warrants being considered as a special case that simply copies the "template" and run as a non-nested workflow .. unless there is a better style for this that I do not know?

**Comment by gaow** [comment]
Here is what I observe with task flows for my application above:

[track_tasks.txt](https://github.com/vatlab/SOS/files/1202881/track_tasks.txt)

It looks like the first step can be avoided if it it not treated as nested workflow here. Also my script is a large one ... which has performance issues that I'll submit a separate ticket for.
