### ISSUE TITLE
Master process stuck with large number of tasks

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#751]
With the fix of #750 my workflow moves on until it got stuck -- it shows on screen `Executing [step name] ...` but no actual task is executed. It stuck for about 30 minutes, with multiple instances of SoS, then finally converges to one SoS process using 35% CPU. I ended up having to kill it after a while. Here I'm running a workflow simple in logic but involves lots of file combinations thus a lot of nested workflows. Maybe too many tasks sent to master can cause a jam (because it works when I reduce the number of simulation replicates)? See the tail 500 lines from DEBUG:

[log.txt](https://github.com/vatlab/SOS/files/1202887/log.txt)

Is there a way to avoid jam for large applications such as this? Job dependencies should be handled already at this stage. To me it is just task distributions.

**Comment by BoPeng** [comment]
Difficult to debug without an example, let me see what I can do with only a log file.

**Comment by gaow** [comment]
Sure! I can send over an example but it involves heavy computations that takes days to run. If it is hard to figure it out from log I can try to create a MWE (though not sure if it can be reproduced). I suspect 2 things:

1. It stuck because it was comparing existing task signatures all at once? I've been running the same pipeline multiple times fixing corner cases along the line (real annoying to deal with bad engineering for corner case handling from other people's black-box algorithms!). I was able to complete it at smaller scale. Maybe it is also because of the amount of accumulating number of signatures? 
 
2. It is related to my lastest thread at #750, that nested workflow caused the issue. 

Not sure if this is helpful, but the reason #750 does not happen every time I run is because my command is mostly disrupted by errors from my actual task, due to corner cases. As I fix them up I'm starting to see #750 oftener, yet still not every time. That's why it takes some effort to capture it with -v 4

**Comment by gaow** [comment]
I think what might naturally help is to set a threshold that limits the number of tasks submitted to the master process to be distributed per batch. Such threshold should be determined by `-J`. Not sure how easy it can be achieved. Do you still need a MWE to test it out?

**Comment by BoPeng** [comment]
Been b

**Comment by gaow** [comment]
Yes I agree. Will leave it open for later.
