### ISSUE TITLE
Attempt to load `saspy` when `sas` kernel is not involved

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#753]
I was trying to run `sos convert --execute` on a notebook in pure SoS but I got this:

```
[IPKernelApp] ERROR | Failed to load language SAS: The 'saspy' distribution was not found and is required by the application
```

**Comment by BoPeng** [comment]
This is the error message you asked.... for checking if R is properly installed. So it perhaps should be delayed to, say, when a notebook with sas or R is opened.

**Comment by BoPeng** [comment]
A proper fix needs substantial re-organization of the language handling code and will have to be delayed.

**Comment by BoPeng** [comment]
OK, used a not-that-proper but much simpler fix.
