### ISSUE TITLE
Support for R named vector to Python.

### ISSUE THREAD

**Issue by HenryLeongStat** [vatlab/SOS#754]
A problem comes up when I modified the `test` for `R`. For now, a `R` `named vector` would become a `list`, which is without index in `sos`. So it becomes a problem for `R` `named vector` -> `sos` `?` 
Should we convert the `R` `named vector` -> `sos` `pandas.Series`? Or `R` `named vector` -> `sos` `dict`?  
For `R` `named list n>0`, it would be converted to `dict` in `sos`.

**Comment by BoPeng** [comment]
I would convert

R named vector to pandas `Series`
R unnaed vector to numpy `array` or `list`

Dict is not an option because it does not preserve order.
