### ISSUE TITLE
An option to quit everything when one single error is detected

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#755]
I'm not sure if this can be achieved easily, but it would be helpful to have an option that tells SoS script to quite whenever an error is detected. I guess the current behavior is to wait until all other parallel process are complete before reporting errors? So in non-task mode I can see errors reported from my script, like:
 
```
Warning in 2:K :
  numerical expression has 2 elements: only the first used
Error in 2:K : NA/NaN argument
```

But SoS will keep running, not reporting the error at this stage. I guess it is saving it for later.

**Comment by BoPeng** [comment]
Yes, the current wait behavior is by design, because it seems blunt to kill other steps/tasks when one branch of the DAG fails.

**Comment by gaow** [comment]
> it seems blunt to kill other steps/tasks 

I agree totally. The user case here is for people who are eager to find out what's going on and fix things up, without have to anxiously hold it until the very end :)

**Comment by BoPeng** [comment]
So will the error be properly displayed with Ctrl-C? If so, you can break the workflow by Ctrl-C after noticing something odd.

**Comment by gaow** [comment]
Unfortunately it does not show any messages, unless I wait until the end. 

> error be properly displayed with Ctrl-C?

That would be a good behavior!

**Comment by BoPeng** [comment]
Example:

```
[1]
sh:
  echo "I am 1"
  sleep 2
  ech 'wrong'


[2]
input: None
sh:
  echo "I am 2"
  sleep 10

```

**Comment by gaow** [comment]
Well, looks like it works for your example but not for Make style:

```
[A]
R:
  k = 1:NA

[B]
sh:
  sleep 10 

[default]
depends: sos_step('A'), sos_step('B')
``` 

Expected:

```
INFO: Resolving 2 objects from 1 nodes
INFO: Executing A: 
INFO: Executing B: 
INFO: B (index=0) is ignored due to saved signature
INFO: output:   []
Error in 1:NA : NA/NaN argument
Execution halted
ERROR: [A []]: Failed to process statement 'R(r"""k = 1:NA\n\n""")\n' (RuntimeError): Failed to execute script (ret=1).
Please use command
	Rscript \
	  --default-packages=datasets,methods,utils,stats,grDevices,graphics \
	  /home/gaow/TempDir/.sos/A_0_61338163.R
under "/home/gaow/TempDir" to test it.
[default]: 1 pending step: default_0
```

Observed
```
INFO: Resolving 2 objects from 1 nodes
INFO: Executing A: 
INFO: Executing B: 
Error in 1:NA : NA/NaN argument
Execution halted
^CProcess SoS_Worker-1:
Traceback (most recent call last):
  File "/home/gaow/Public/miniconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/sos_executor.py", line 144, in run
    work = self.pipe.recv()
  File "/home/gaow/Public/miniconda3/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/gaow/Public/miniconda3/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/gaow/Public/miniconda3/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
KeyboardInterrupt
```
behavior when running as task is fine.

BTW it seems to take quite some overhead to execute this MWE (or maybe because my computer is fully loaded now?)

**Comment by BoPeng** [comment]
New improved after `KeyboardInterrupt` behavior:

```
INFO: Executing default_1:
INFO: input:    []
I am 1
INFO: Executing default_2:
INFO: input:    []
I am 2
/var/folders/ys/gnzk0qbx5wbdgm531v82xxljv5yqy8/T/tmp8a0vy1b3.sh: line 3: ech: command not found
^CERROR: [default_1]: Failed to process statement 'sh(r"""echo "I am 1"\nsleep 2\nech \'wrong\'\n\n\n""")\n' (RuntimeError): Failed to execute commmand /bin/sh /Users/bpeng1/sos/.sos/default_1_0_e26c7343.sh (ret=127, workdir=/Users/bpeng1/sos)
```

**Comment by BoPeng** [comment]
The make-style example has also been improved. Note that I have changed the long "please execute ..." error message to a single line to make output more compact.

**Comment by gaow** [comment]
Great, it works!
