### ISSUE TITLE
Support for Julia

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#756]
Julia is likely the next language to be supported, because

1. It is well supported by Jupyter, and is one of the "standard" kernels of Jupyter
2. It is part of the Jupyter notebook docker image on which `sos-notebook` docker image is based
3. It is trendy for data scientists
4. iJulia is immensely popular among Julia users so supporting Julia could attract them to SoS

Note that
* [introduction to Julia types](https://en.wikibooks.org/wiki/Introducing_Julia/Types)
* [Julia reads feather format](https://github.com/JuliaStats/Feather.jl) so it is easy to transfer Python dataframe to Julia.

**Comment by HenryLeongStat** [comment]
Note: At `julia`, if we want to name an `array`, an additional package [NamedArrays](https://github.com/davidavdav/NamedArrays.jl) is needed. Just simply run `using NamedArrays` in `julia`.
I simply add it with `using Feather` at the `statement in julia kernel`. I think `Pkg.add("DataFrames")` might also be needed. If it is the case, I will add it at the `sos` homepage. I'm still figuring it out...

**Comment by BoPeng** [comment]
Yes, it is ok to require some packages to make data conversion more authentic (we did this for Octave anyway).

**Comment by HenryLeongStat** [comment]
Just check the documentation of `julia` and find that it allows using Unicode as part of the name of function. Would that be a problem? (i.e. some editors cannot handle Unicode maybe?)

**Comment by BoPeng** [comment]
Yes, try to stay with unicode in program. Something like `__sos_FUNC` would be unique enough.

**Comment by BoPeng** [comment]
I have seen commercial software uses something like `d6bc3599dcabb1b0ad14a5` for such purposes.

**Comment by HenryLeongStat** [comment]
😨 OK... Let me think about a solution for this...

**Comment by BoPeng** [comment]
If you are really into this, you can use session id and something like

```
import uuid
SID = uuid.uuid4().hex

statement = '''func{0} = ..
'''.format(SID)
```
so that function names are truly unique even for each instance of the kernel. 😄 

It all depends on how far you would like to go to avoid such corner cases.

**Comment by HenryLeongStat** [comment]
It is interesting that using session id as a solution. 😆 
Anyway, I think that can be done once everything is ready (all the kernels are set). Since it might be difficult to read the codes after changing the name into session id. 😨

**Comment by BoPeng** [comment]
Readability wise it is not too bad because you are using name `SID` to create strings, not the actual random number, but I agree that it does not worth the trouble.

**Comment by HenryLeongStat** [comment]
As `list` in `julia` is just like `list` in `python`, so the current kernel can deal with it. 
I'm working on `Julia DataFrames` and will check the documentation of `julia` again to see whether there are other common data types. 
After that, I will work on the test and try to finish all the works (kernel and test) should be finished by next week! 💪

**Comment by BoPeng** [comment]
Are Julia tests working yet? Any plan to add Julia to [multi-language documentation](https://vatlab.github.io/SoS/doc/documentation/Supported_Languages.html)?

**Comment by HenryLeongStat** [comment]
Manual test should be working just now! 😄  I think I can finish the test kernel by tonight. 
For the [documentation](https://vatlab.github.io/SoS/doc/documentation/Supported_Languages.html), I will do it after the test kernel. It just takes half an hour or less to finish.

**Comment by BoPeng** [comment]
Great. I will release 0.9.9 after this part is done.

**Comment by BoPeng** [comment]
Benchmark with `tic()` and `toc()` before and after `init_statements` shows that loading the four packages uses 6 seconds while the rest of the code 0.12s. Unfortunately, it appears that `using` cannot be used inside a function so we have to load the packages when Julia kernel is started.

**Comment by HenryLeongStat** [comment]
That's quite a long time... 
I'm working on the test kernel, let me commit that here.

**Comment by BoPeng** [comment]
Ohmm, I guess I committed before you?

**Comment by HenryLeongStat** [comment]
Haha, that's fine!

**Comment by BoPeng** [comment]
But you could have saved me some time if you committed your revision earlier....

**Comment by HenryLeongStat** [comment]
Oops... I thought I should commit after the test kernel works without any problem... Sorry... 😭

**Comment by BoPeng** [comment]
The manuscript has been submitted so there is a small chance that some Julia expert is reviewing sos. I verified that Julia data conversion largely works so I added a section to the [documentation](https://vatlab.github.io/SoS/doc/documentation/Supported_Languages.html) and released 0.9.8.10. I will make another release after Julia is properly tested and documented.

**Comment by HenryLeongStat** [comment]
It is working at the manual test.
<img width="797" alt="screen shot 2017-08-26 at 12 49 22 am" src="https://user-images.githubusercontent.com/26916551/29739006-ca7fb012-89f8-11e7-9bbb-798852762ca9.png">
<img width="806" alt="screen shot 2017-08-26 at 12 51 22 am" src="https://user-images.githubusercontent.com/26916551/29739007-d0ef696a-89f8-11e7-8687-cf4a3eb4d2ab.png">

But doesn't work well at the `test kernel`... Don't understand some of the error msgs...

**Comment by BoPeng** [comment]
Yes I also noticed that so please just manually check the tests. You can fix documentation and the missing row labels of data frame while I check the test mechanism.

**Comment by HenryLeongStat** [comment]
OK! Let me fix the dataframe now!

**Comment by BoPeng** [comment]
Now? At 1am? You can do it tomorrow.

**Comment by HenryLeongStat** [comment]
Before the electricity runs out... 😭

**Comment by BoPeng** [comment]
All tests pass on my end, so we are more or less done. Please update the documentation with datatype translation tables.

**Comment by HenryLeongStat** [comment]
Done. In my opinions, the compatibility between `Julia` and `Python` is pretty high! Most of the datatypes are the same.

**Comment by HenryLeongStat** [comment]
Julia tests [fail on travis](https://travis-ci.org/vatlab/SoS/jobs/271318275#L3602) because IJulia and Feather fail to install. Need to find a Linux VM and test (My guess is that we might need to install something like julia-dev package).
