### ISSUE TITLE
Jupyter notebook set global workdir

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#760]
Is it possible to set default workdir directly from Jupyter notebook that all steps will use?

**Comment by BoPeng** [comment]
`%cd` before other kernels are started. Otherwise you will have to use language specific `chdir()` to change directory.

**Comment by gaow** [comment]
I see. This is actually good idea. May I ask how to achieve the same in command version? Is it some magic `CONFIG` setting I'm not aware of? :)

**Comment by BoPeng** [comment]
No. Command version has to use `task` level or `action` level `workdir`.
