### ISSUE TITLE
Batch / recursive download

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#761]
I'm trying to download some files structured like this:

ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByStudy/sra/SRP/SRP033/SRP033351

What is the best way to use SoS for it? Is it possible to add some recursive download features to `download`?

**Comment by BoPeng** [comment]
Recursive download is very tricky. Is there something to get the list of files under the directory (to feed to `download`)?

**Comment by gaow** [comment]
I'm not sure. With external tools there must be a way. Or there should be some python implementation:

https://stackoverflow.com/questions/11023530/python-to-list-http-files-and-directories

I guess the question is if we should have such support because it can be dangerous and tricky ...

**Comment by BoPeng** [comment]
Yes, dangerous and tricky, exactly what I was afraid of. Perhaps we should not do that. I suppose users could do something like
```
["http:/url/${file}" for file in HTML_BLOCK.split()]
```
to use some text copy/pasted from the webpage. This way the script at least shows what files are downloaded. Otherwise I could image some script works now, then someday downloads the entire website due to restructure of remote website.

**Comment by gaow** [comment]
Labeled `wontfix` and close, unless there are better ideas ...

**Comment by BoPeng** [comment]
BTW, you can always use

```
sh:
   wget URL -l 1 -r...
```

**Comment by gaow** [comment]
Sure, but this cannot properly `provide` files to other processes (vs. using some codes to get the file lists and both `download` and `provide` them)

**Comment by BoPeng** [comment]
sratools, as far as I remember, has command to download sra files. Also, you could potentially do

```
sh:
   wget
files = os.listdir()
```
