### ISSUE TITLE
Documentation on extra packages 

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#763]
Several issues here #744 #753 #762 are in fact related to improper installation of dependency packages. I wonder if we should include an option in `setup.py` to install all these extra packages, and also document these dependencies?

**Comment by BoPeng** [comment]
We have a long list of extra/optional packages

```
    extras_require = {
        ':sys_platform=="win32"': ['colorama'],
        'image':    ['wand'],
        'md':       ['markdown'],
        'R':        ['feather-format', 'pandas', 'numpy'],
        'rq':       ['rq'],
        'bam':      ['pysam'],
        'dot':      ['graphviz'],
        # docker-py is not working on windows 10 (as of Jan 2017)
        'docker':   ['docker'],
        'sas':      ['saspy'],
        #'spyder':   ['spyder'],
```
 I suppose we can make some of them required. The problem with docker is that it does not work under windows the last time I checked.

**Comment by BoPeng** [comment]
No longer applicable with new structure of packages.
