### ISSUE TITLE
Shortcut for `%preview --limit` to show all rows

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#766]
Currently --limit is default to 200 rows. I tried to use `--limit -1` to show all rows (vtools convention) but it shows all but the last row. `--limit -2` will show all but the last 2 rows, etc. Is there a shorthand to show all rows? Shall we make behavior of negative `--limit` well defined?

**Comment by BoPeng** [comment]
The parameter is basically sent to `DataFrame.head` and the behavior of negative index is undefined. I have adjusted the behavior of `--limit` with negative index to show all records.
