### ISSUE TITLE
Figure in report example is not displayed.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#767]
Figure in [this example](https://vatlab.github.io/SoS/doc/examples/Preview_and_Report_Generation.html) is there, but not displayed. Looks like some JS loading problem.

**Comment by BoPeng** [comment]
It is strange that the figure in the HTML file would be correctly displayed if I load local file 
 sos/docs/doc/examples/Preview_and_Report_Generation_report.html directly, but the online version does not work https://vatlab.github.io/SoS/doc/examples/Preview_and_Report_Generation_report.html.

**Comment by gaow** [comment]
I am outside but a quick check is whether http or https is used? Google
chrome does not like http

**Comment by BoPeng** [comment]
It is https.

**Comment by gaow** [comment]
Still having issues? It does seem to be http protocol issue that `sos-report` template needs to fix. Go to this page:

https://vatlab.github.io/sos-docs/doc/examples/Preview_and_Report_Generation.html

Then in Google chrome open the developer tools and see this error from the console:

![2018-04-29-23-07-32_scrot](https://user-images.githubusercontent.com/917985/39414896-4ba68f82-4c02-11e8-94ad-e99edc999788.png)
