### ISSUE TITLE
Adjust background colors of languages.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#770]
The new Julia background color is too similar to R, and should be changed. To make the colors more obvious to users, I have used the default colors as background colors for each language in [the features page](https://vatlab.github.io/SoS/#features). We should perhaps also change the color for Matlab/Octave (the navy color for the octave logo looks better).

Please update the language definition and the features page when changing colors.

**Comment by BoPeng** [comment]
Perhaps we can use the yellow color (similar to the "interactive UI" tag on this page for a language.

**Comment by HenryLeongStat** [comment]
OK! I will do it right now.

**Comment by BoPeng** [comment]
Perhaps we should try to match our colors with the logos, something like

* the green of the JS logo for green
* The yellow of the python logos for python
* navy blue for matlab and octave because it shows in both logos
* (perhaps) current light green for python for Julia?
* (perhaps) blue for SAS? perhaps too dark.

**Comment by HenryLeongStat** [comment]
Yes, I agree! That would look better.

**Comment by BoPeng** [comment]
![image](https://user-images.githubusercontent.com/9889312/29381580-5394158a-828f-11e7-8de0-4b88ed588c6d.png)
has many different shade of blues. We can use a light one for SAS.

**Comment by BoPeng** [comment]
For JS green, http://www.color-hex.com/color/77b635 has lighter color such as #c8e1ae

**Comment by BoPeng** [comment]
The SAS blue http://www.color-hex.com/color/3b7cc0 has a low shade one that is similar to what bash is using now (#c4d7ec)... 

Anyway, use `%use R --color COLOR` to test and I will leave the decisions to you.

**Comment by HenryLeongStat** [comment]
How about the followings?
<img width="455" alt="screen shot 2017-08-16 at 2 45 45 pm" src="https://user-images.githubusercontent.com/26916551/29382267-a364b6e4-8291-11e7-958f-421a1b590ee8.png">

They look quite pleasant in `jupyter notebook`! And each of the color represents the logo of each kernel except `Bash`.

<img width="377" alt="screen shot 2017-08-16 at 2 48 23 pm" src="https://user-images.githubusercontent.com/26916551/29382380-020780d2-8292-11e7-87c6-f89aac78c6ef.png">

**Comment by BoPeng** [comment]
Lighter shade for matlab to differ more from SAS?

**Comment by HenryLeongStat** [comment]
Seems better!

<img width="451" alt="screen shot 2017-08-16 at 2 55 02 pm" src="https://user-images.githubusercontent.com/26916551/29382663-ebe312ac-8292-11e7-96a2-49d7107ffc1e.png">

**Comment by BoPeng** [comment]
Good. Please make the necessary changes.
