### ISSUE TITLE
Option to clear output of job status from notebook cells

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#771]
Currently after submitting a large number of jobs my notebook will have thousands of lines of job status output. I would heat to keep them in my notebook or push them over to github, after I'm done with them (ie after all of the jobs succeed).  In Jupyter it is possible to clear all output, but not output for given cells. For now I have to clear all output inside a notebook in order to get rid of those lines before push to github. Is it possible to use an option to remove at least those job management output for  SoS Notebook?

**Comment by BoPeng** [comment]
The job IDs are very useful to check details of jobs after they are completed, but I agree that it can take a lot of space even with the current short form (4 letters, right?).

I can remove most IDs and show `id1, id2, ... idN`, or `id1, id2, id3, ...` where `...` can be clicked to expand all. Not sure if the latter one is necessary.

**Comment by BoPeng** [comment]
BTW, why did not you use `trunk_size`?

**Comment by BoPeng** [comment]
![image](https://user-images.githubusercontent.com/9889312/29415525-f68d7eae-8328-11e7-8dae-28846e9c45a9.png)

**Comment by gaow** [comment]
This looks great!

> BTW, why did not you use trunk_size?

Because this is still being tested and I want to see all types of corner cases all at once. Otherwise a chunk will fail due to one corner case in a task, then I fix, and submit, and will still fail due to another corner case ...

**Comment by BoPeng** [comment]
ok, please submit another ticket for this. We can potentially "single out" failed tasks from trunks...

**Comment by gaow** [comment]
This does not happen because my tasks are never "complete". all output files are generated and the main computational program has quitted. Nothing is going on on my computer yet the monitor still keeps updating itself (only the elapsed time string). Notice the left are blank square boxes (indicating idle or in queue?)

![2017-08-27-16-18-13_scrot](https://user-images.githubusercontent.com/917985/29754040-5bdc2afe-8b43-11e7-87c9-da07e05a83cc.png)

But for some other lighter tasks it will show "complete" when they do complete.

**Comment by gaow** [comment]
Update: it seems if I do see the rotating circle of dots during execution then in the end the "complete" status will be properly displayed. But sometimes all I see is blank squares like above without status change whatsoever. Not sure why it is happening. Still exploring ...

**Comment by BoPeng** [comment]
Update: please try the new [`%clear` magic](https://vatlab.github.io/sos-docs/doc/documentation/SoS_Magics.html#%clear-102), which is designed to clear output of selected or all cells of a notebook.
