### ISSUE TITLE
Single out failed task from trunks of tasks

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#772]
This is related to #771 . With `trunk` option it is harder to manage single tasks particularly those failed ones. For starters we may want to single out failed tasks from its trunk.

**Comment by BoPeng** [comment]
Test case
```
input: for_each={'i': range(5)}
task: trunk_size=5

import sys
print(i)
if i == 3:
  raise ValueError(i)
```
The fourth task would fail without option `trunk_size` and we need to make sure that the single task has proper error message, and the grouped tasks also have the correct message.

**Comment by BoPeng** [comment]
I think this is the best I can do for now.

**Comment by gaow** [comment]
:+1: :+1:  with this, do you think the auto-trunk stuff can be brought back into consideration?

**Comment by BoPeng** [comment]
Auto trunk was proposed to speed up job submission. What is the point of having it if job submission is now a non issue?

**Comment by gaow** [comment]
> Auto trunk was proposed to speed up job submission. What is the point of having it if job submission is now a non issue?

Okey I was not being clear about this. So there is always an issue of submitting too much jobs to cluster. That is why we want to do any trunking in the first place. But basically `-J` is kind of an indicator on the resources available. For example `-J 40` may mean that my cluster allows submitting 40 jobs at a time. Otherwise it will be on hold or declined. It seems to make more sense then to consolidate all the N tasks into just 40 batches so that we only submit 40 times, not submitting N times while ensuring only 40 active. So in principle I feel we do not need manual trunking because there is enough info to automatically trunk it. But please ignore it if I'm wrong, or trunk is still not good at showing up error messages in spite of the patch, or it is too difficult to do in practice.

**Comment by BoPeng** [comment]
At least in my case the RNASeq pipeline vary a lot on execution time (from a few hours to a few days) so running them one by one avoids possible combination of long running jobs. My feeling is that auto trunk is usable for cases with specified minimal job duration so that sos can automatically group small jobs ( with small specified wall time) to avoid submission of tiny jobs to cluster.

**Comment by gaow** [comment]
I see, that's great point! we currently do not have minimal job duration estimate, right? It sounds like a low priority thing to me though. Do you want me (or yourself) to open an issue for later?

**Comment by BoPeng** [comment]
That should be a parameter for each cluster. For example, if you set min_job_walltime for a cluster to 1hr and you have jobs with task: walltime=5m, sos would group 20 jobs together before sending them to cluster.
