### ISSUE TITLE
Convert to SoS notebook to/from Rmarkdown

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#775]
Is there a feature planned for these? I'm talking to someone at another lab who has many notebooks with Python kernel. I realized there is no provided function to convert them to SoS kernel though it might be possible to just change the `metadata` of the notebook to SoS. Also what if the notebook uses R kernel?

Similarly it might be a good idea to support converting Rmarkdown to SoS ... a full support is hard, but at least from plain markdown to SoS should be easy (I personally use a package called `notedown` )

**Comment by BoPeng** [comment]
Great idea.

For notebooks in other kernels, using `kernel -> Change Kernel -> SoS` should work. This will change the kernel from another kernel to SoS, with all cells having no pre-specified kernel. Then you can change the global kernel to the appropriate one (say, to `R`) to match the language of the cells, which can be ignored for Python notebook.

RMarkdown is quite different and can be difficult to convert. I am not sure what format `RStudio Notebook` uses, but it should be possible to convert.

The bottomline is that we should provide plugins to perform the conversion. `.ipynb` to `.ipynb` should be easy, and `Rmarkdown` to `.ipynb` should be on the list.

**Comment by gaow** [comment]
> kernel -> Change Kernel -> SoS

Thanks for the tip! I'll show them this for now -- at least it should be fully compatible with Python notebooks.

>  I am not sure what format RStudio Notebook uses, but it should be possible to convert.

I think the major difficulty converting `Rmarkdown` is its dynamic part, ie the `knitr`. I think there is no point to do the conversion without touching this point (i'm thinking render it to plan markdown with R and convert to SoS Notebook but this would make us look silly)

**Comment by BoPeng** [comment]
Perhaps it is not that difficult, although a perfect conversion is not possible. I mean, we can scan each paragraph, and convert pure markdown to markdown cell. For the  triple quote `{r}` paragraphs, we can convert to a R cell (ignore all the options). And then we are only left with the embedded expressions, which could be left untouched or be put to a `%render` cell with code wrap in `cat` (might not work, but basically this is how sos handles inline expression).

**Comment by gaow** [comment]
I think it works great! I checked `git diff` outcome with manual conversion and see no difference. My old R notebooks also got converted quite nicely. 

BTW there is a typo in this command interface -- the word "script":

```
    sos-md              Convert SOS scriot to a markdown format with scripts
                        quoted in markdown syntax.
```

I'm reporting yet not going to fix it in case of merge conflict if you are still changing it.

**Comment by BoPeng** [comment]
Please fix it. I am not editing that part. Also `sos-md` is useless as far as I can see.

**Comment by BoPeng** [comment]
OK, here is some very crude converter from `rmd` to `ipynb`. At least it converts [this one](https://gist.githubusercontent.com/jeromyanglim/2716336/raw/574783e141a99bd315c49647a3b308bd7de64cf3/example-r-markdown.rmd) reasonably well into a sos notebook.

**Comment by gaow** [comment]
Great! This should work for a plain Rmarkdown, and with `sos convert --execute` it should run the examples. But indeed it is crude because the `knitr` related stuff is hard to adopt. I'm not familiar with that system but I think that's what distinguishes Rmarkdown from markdown.

**Comment by gaow** [comment]
I find it a bit difficult to work on some converted R notebooks because I have no intension to use other languages there, but each time a new cell is created it uses SoS kernel by default. Having to click & change is a bit annoying. I'm wondering if it make more sense to use kernel for the previous cell as the default kernel for a new cell, and if it is easy / any side effects to change the current SoS Notebook to this behavior.

**Comment by BoPeng** [comment]
If you convert by change kernel, you can set global language to R and then R will be used for all cells when you execute. If you use `sos convert`, the cells will have R as kernel.

**Comment by gaow** [comment]
Yes I was talking about outcome of `sos convert`. I should not say I'm not going to use other languages in that notebook because then otherwise it is pointless to convert to SoS Notebook. I should say most default cells are R. `%use R` is Ok, but having SoS creating new cells of the same type as previous cell sounds more intuitive.

**Comment by BoPeng** [comment]
I do not get it. After conversion, existing cells are in R, right? Then, if you want to have new cells in R, just change the global default to R.

**Comment by BoPeng** [comment]
Note that global default is always `SoS` for now. If you want this information to be saved/loaded, it is certainly doable (another ticket?). Then it makes sense to set the default to `R` if `sos convert` a R notebook.

**Comment by BoPeng** [comment]
It is more or less working. Please open a new ticket for specific problems.
