### ISSUE TITLE
%preview error with complicated dictionary keys

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#776]
See error screenshot:

![screenshot from 2017-08-19 17-37-13](https://user-images.githubusercontent.com/917985/29490542-22d0761e-8505-11e7-9213-6ebf81c192e0.png)

**Comment by BoPeng** [comment]
This is because of the space between `this` and `tiggers`. You can try to use  a single quote around the expression.

**Comment by gaow** [comment]
Right, that indeed works. Not sure how this can be nicely dealt with: looking for paired `"` or `'`? What if `'''` or `"""` ...?

**Comment by BoPeng** [comment]
Magics uses shell syntax (options etc) so do not work well with spaces. We cannot be even intelligent to try to guess the syntax because `%preview` can work with expression from any kernel.
