### ISSUE TITLE
%include bugs

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#779]
There are several issues in the current `master` related to `%include`. See screenshot here:

![2017-08-19-19-26-21_scrot](https://user-images.githubusercontent.com/917985/29491021-6d13bd4e-8514-11e7-8c76-ae93cc3cf057.png)

1. `%include` no longer works. This is weird because I'm sure I've used it before -- as of yesterday!
2. `%from A include B, C` does not work. I believe this is a long standing problem. I had to use `%from A include *`. I ran into this yesterday but did not open a ticket to report it because I was in the middle of getting some work done. 
3. Minor: typo in the error prompt `statemetns`

**Comment by BoPeng** [comment]
What is the content of `Untitled.sos`?

**Comment by gaow** [comment]
It has one cell:

```
[test]
print(9)

[another_test]
print(6)
```

**Comment by gaow** [comment]
Seems what initially reported is fixed. But there is still some problems here. To reproduce, create an empty notebook called `test.ipynb` and run in a main notebook this cell:

```
%run -s force -v 3
%from Untitled include *

[default]
output: '1.txt'
run:
    echo 'Running it'
    sleep 3
    touch '1.txt'
```

(I was importing from `test.ipynb` an empty notebook but really does not matter for the sake of reproducing the bug; same deal when import from another non-trivial notebook). 

The error message I get is:

```
DEBUG: Workflow default created with 2 sections: default_0, default_0
  File "/home/min/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/jupyter/sos_executor.py", line 372, in runfile
    'workflow_args': workflow_args
Traceback (most recent call last):
  File "/home/min/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/jupyter/sos_executor.py", line 372, in runfile
    'workflow_args': workflow_args
  File "/home/min/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/jupyter/sos_executor.py", line 57, in __init__
    sig.write('# included: {}\n'.format(','.join(self.workflow.content.included)))
TypeError: sequence item 0: expected str instance, tuple found
sequence item 0: expected str instance, tuple found
```
 Yet removing `-s force` it will work.
