### ISSUE TITLE
Non-tasks in notebook does not skip existing outcome

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#780]
Maybe I'm doing something wrong here, but repeatedly running non-tasks in notebook does not seem to skip previously completed jobs. For example the cell below has been executed 8 times yet it reruns every time.

![screenshot from 2017-08-20 08-08-09](https://user-images.githubusercontent.com/917985/29495171-e8190890-857e-11e7-9a0c-cc46a056d3ce.png)

BTW I'm trying to explore ways to better organize / execute my projects using what SoS can offer, particularly the interactive interface. But I might be abusing or misuse it ... I'd very much appreciate suggestions or alternatives that helps forming a version of best SoS practice.

**Comment by BoPeng** [comment]
The default sig mode for notebook is ignore, because the notebook was not designed to run large jobs when it was first implemented. Perhaps it is time to change.

**Comment by gaow** [comment]
I see. Sorry I did have tried `-s ignore` before I open this ticket, which I meant to type `-s default` but somehow made that mistake ... It's then a discussion of "consistency" and "best practice". Large jobs may note mean heavy jobs. I do use non-task mode to run heavy yet single core jobs, particularly in notebooks because the interaction is easiler compared to `task`.

**Comment by BoPeng** [comment]
The reasons for the `ignore` signature mode was that notebooks are for interactive use, thus not for heavy long running jobs that requires waiting. It can also be surprising if the same commands act differently. Moreover, unlike batch mode with only one script, notebook users tend to modify here and there and re-run things, and it can be challenging to keep track of signatures (some variables cannot be used in signature).

Long-running jobs in notebook are supposed to be executed as tasks, which are not blocking and has a much nicer interface.

**Comment by gaow** [comment]
I see. The 'long waiting' argument makes a lot of sense. I agree we do not change the behavior here.

The problem running as `task` is that I can no longer keep some "log info" of jobs I run inside the notebook. Tasks is great for running many jobs, but not very friendly to simple case. For example, all I want is to run some `plink` pipeline for QC, yet have my notebook show all those stderr from plink so that I can keep track of number of samples / variants at each step, and save the info for future review. Do you think such user case warrants some special handling? I understand `sos status` will work but it requires additional tracking, typing and give more information than I'd want :) (sorry for being picky here, just brainstorming not complaining!)

**Comment by BoPeng** [comment]
That is why I tried to keep the task IDs in the notebook (reduced to 3 due to a recent change) so that you can just click on the ID and see the stderr.

Note that the last argument does not count anymore because `%run` is executed now with a new dict. The long-running argument does not really count either because we cannot control what users do so if they do run long-running jobs, it is their decision and signatures can help.

**Comment by gaow** [comment]
> That is why I tried to keep the task IDs in the notebook (reduced to 3 due to a recent change) so that you can just click on the ID and see the stderr.

It does but it goes to the side panel along with other info, and it is temporary. In order to bookkeep these info in the main notebook one has to do what I said, and still do not have isolated `err`. The point is not to "see" the status but to "keep" the outcome `err` as part of the result for future reference, when there is one single important task executed. 

Again, not a big deal, just food for thought. I can always pipe my stderr to a file and `%preview` it after, if I do want to keep it.
