### ISSUE TITLE
Support for singularity

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#786]
SoS makes it easy to submit tasks to HPC but it still requires the HPC to have the software installed. The idea (actually current implementation) of sos running docker container is practical for workstations but not for HPC because of security concerns. [Singularity](http://singularity.lbl.gov/) is a container solution for HPC as demonstrated by [its paper](http://journals.plos.org/plosone/article/file?type=printable&id=10.1371/journal.pone.0177459) and had been adopted by universities.

Without checking the actual capacity of singularity, on the surface it looks like we could wrap our tasks as singularity apps and execute them on HPC and free users the need to install software there. This should definitely be something we should try, which can make sos an even better platform for cross-platform computation.

**Comment by gaow** [comment]
Going over old posts -- just to add that converting from docker to singularity, or running docker images from singularity, is [established](https://singularity.lbl.gov/docs-docker), but I guess it takes time and work to figure out the command options that works best. Will see if there is a need from one of us.
