### ISSUE TITLE
Writing matrix to by using feather in Julia

### ISSUE THREAD

**Issue by HenryLeongStat** [vatlab/SoS#787]
The problem here is that: When we want to transfer a `matrix`  from `Julia` to `Python`, we need to convert the `matrix` to `dataframe` first, and then save it by using `feather`.

However, when it saves a `dataframe`, we can see that the first row is `1   │ 4294967297 │ 4294967297`, which should not be the case. 

<img width="555" alt="screen shot 2017-08-25 at 6 30 21 pm" src="https://user-images.githubusercontent.com/26916551/29736055-7dd80262-89c3-11e7-8716-3857abf8b2e7.png">

I'm not sure if it is the bug of the package or the problem or myself...
Maybe we should think another way to do it? However, it will also happen for `dataframe` in `Julia`.

**Comment by BoPeng** [comment]
I will take care of it. Are you safely at home? The rain is getting bigger.

**Comment by HenryLeongStat** [comment]
I am! Thanks Professor! 😄  Went back home at 2:00 pm from office today. And I bought a lot of food and water as well. Be safe too Professor!!! 💪

**Comment by HenryLeongStat** [comment]
It somehow works fine here...? 😕 

<img width="550" alt="screen shot 2017-08-26 at 12 02 45 am" src="https://user-images.githubusercontent.com/26916551/29738750-f41d7136-89f1-11e7-8865-45ab598f5b97.png">

**Comment by BoPeng** [comment]
Yes, I added parameter `nullable=false`, not sure if it helped.
