### ISSUE TITLE
Show INFO message when syncing files between remote / local

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#790]
When syncing large files between remote / local, the `task` icon in SoS Notebook does not spinning, nor does it show anything. It was not an issue until just now I wrongfully sync-ed very large files without noticing and depleted one of my disk. It was a bit annoying. 

Since syncing can sometimes be a harmful behavior, it would be great to add more INFO prompt to the notebook while `rsync` is doing its job.

**Comment by BoPeng** [comment]
This stage is called "pending" and is executed as a preparation step for submission. It does not have its own dedicated icon because the job might be waiting after the files are synched. I will see what I can do here though.

**Comment by BoPeng** [comment]
One way to solve this problem is to replace the timer with a status line (maybe limit to 50 character) and update what is doing from time to time.

**Comment by BoPeng** [comment]
There are already [info](https://github.com/vatlab/SoS/blob/master/src/sos/hosts.py#L522) messages, although they were displayed after the files are synced.

**Comment by gaow** [comment]
Yes exactly. But by that time mess was already made :(

**Comment by BoPeng** [comment]
Good enough?

**Comment by gaow** [comment]
Looks like so! I do not (yet again) have a large file to test sync for now, but it seems exactly what i'd expect. Close it for now until there is an issue in field test soon.
