### ISSUE TITLE
SoS report template does not show code with `report_output` tag

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#792]
The notebook below seems to imply that both codes and output should be visible by default once `report_output` tag is set, but in fact only output is shown in the HTML without code, when I tag a cell with `report_output`. Is the notebook out dated? How can I also show codes? 

https://github.com/vatlab/SoS/blob/master/docs/src/examples/Preview_and_Report_Generation.ipynb

**Comment by gaow** [comment]
As an example, here is my notebook:

![2017-08-28-16-39-20_scrot](https://user-images.githubusercontent.com/917985/29794892-943ea6d4-8c0f-11e7-85b4-c0b59558250e.png)

and here is the exported HTML

![2017-08-28-16-39-46_scrot](https://user-images.githubusercontent.com/917985/29794903-9cee5b80-8c0f-11e7-9573-e4888bd7b78f.png)

**Comment by BoPeng** [comment]
The **output** is displayed. Source code is by default not displayed in all cases because a "report" IMHO should contain only results.

**Comment by gaow** [comment]
I see, I got it confused with this page:

https://vatlab.github.io/SoS/doc/examples/Preview_and_Report_Generation_report.html

> because a "report" IMHO should contain only results.

IMHO: there might be cases when codes are also part of a report: for example you want collaborators to review implementation of certain computational algorithm, or check if some command arguments you pick makes sense. Of course at the same time you want to hide most of the other codes that you are comfortable with (though readers may find them overwhelmingly uncomfortable if shown )

**Comment by BoPeng** [comment]
My reports are all to PIs and they are not interested in code at all. It is pretty easy to add a `report_cell` tag though. All you need to do is to change `sos_report.tpl` to handle it (and also update the doc).

**Comment by BoPeng** [comment]
A `report_cell` tag has been added.
