### ISSUE TITLE
Cannot trigger %sosrun rerun even when output is deleted

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#793]
Symptom: 

![2017-08-29-14-54-35_scrot](https://user-images.githubusercontent.com/917985/29841231-4a7f5afa-8cca-11e7-9902-8cd807ce10bc.png)

You see even itself complains about target not found yet it refuses to generate it. In my data analysis actually it just skips the step; not even an error message was given.

**Comment by BoPeng** [comment]
Works here

![image](https://user-images.githubusercontent.com/9889312/29853897-2b89e384-8d08-11e7-9c0c-d50640e6771c.png)

Looks like some signature problem. Did you use `%set` to use another signature mode?

**Comment by gaow** [comment]
No it is default mode, an MWE on a fresh notebook ... This is weird. 

I think I'm having a lot signature related issue with Notebook interface but I did not have time to prepare MWE properly as I'm quite buried in data. Running `sos run notebook.ipynb` always worked for me. I'll dig some more and report when I have more time.
