### ISSUE TITLE
Action `run` for non-zero return code

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#794]
I am using a program written in C++ whose source codes says:

```cpp
int main(...) {
...
return 1;
}
```
This breaks `run:` because it will report error all the time. Is there a way to turn off the return code check optionally?

**Comment by BoPeng** [comment]
[`allow_error`=True](https://vatlab.github.io/SoS/doc/documentation/Targets_and_Actions.html#allow_error-128)?

**Comment by BoPeng** [comment]
In case of shell script, you could also do `cmd || true`.

**Comment by gaow** [comment]
> allow_error=True?

It will solve the problem only when there actually is no other error. Otherwise it will mask all errors. Yet the problem here is very specific: the return code check needs to be changed.

> cmd || true

Same problem here?

But I admit a good interface is hard to come by and only applies to very particular case like this one. So I'd not have any objection if this is a wont fix. 

Currently I wrap it with a Python `os.system()` call. I feel it is safer than to just skip all errors ( not 100% sure about this claim ... ).

**Comment by BoPeng** [comment]
Also note that `run` and `sh` or `bash` are different in that `run` stops at error while `sh` does not so that you can check return value using `$?` in `sh`, but not `run`.
