### ISSUE TITLE
Release unacquired lock error when there are many output

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#796]
I'm not yet able to find a MWE for this one yet, but when I run the step command with 95 output it works. With over 2,000 output there seems to be an issue:

```  
File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/__main__.py", line 350, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
Traceback (most recent call last):
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/__main__.py", line 350, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/sos_executor.py", line 1085, in run
    raise exec_error
sos.sos_executor.ExecuteError: [preprocessing_1]: Unable to release an unacquired lock
[preprocessing]: 3 pending steps: preprocessing_2, preprocessing_3, preprocessing_4
ERROR: [preprocessing_1]: Unable to release an unacquired lock
[preprocessing]: 3 pending steps: preprocessing_2, preprocessing_3, preprocessing_4
```

This is an external task. My input file is a single file, and output file is over 2,000 due to `for_each`.  Here is debug info related to locks:

```
DEBUG: Set _ids = 'C32907'
DEBUG: _input: ['/home/gaow/Documents/CP/input/20170901/BOS.bed']
TRACE: Lock acquired for output files [/home/gaow/Documents/CP/output/20170901/round1/BOS.C32907.bed]
```

It fails even before any jobs start.

There are over 2,000 `for_each`, so maybe it's an issue? If I remove `task:` then my workflow runs well sequentially. I can keep working on a MWE but just reporting it here in case there are quick and obvious fixes.

**Comment by BoPeng** [comment]
There will be more verbose warning message but not an error.... which could help identify the source of the problem.

**Comment by gaow** [comment]
Okey indeed now it turns into a warning message of the same nature and attempts to move forward

```
TRACE: Lock released for output files ...
TRACE: Lock released for output files ...
TRACE: Lock released for output files ...
... (there are numerous lines of such) ....

WARNING: Unable to release lock for output files [/home/gaow/Documents/CP/output/20170901/round1/BOS.C32907.bed]: Unable to release an unacquired lock
```

But then there is the new error message **immediately follows the warning** complaining about too many opened files:

```
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/__main__.py", line 350, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
Traceback (most recent call last):
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/__main__.py", line 350, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/sos_executor.py", line 1085, in run
    raise exec_error
sos.sos_executor.ExecuteError: [preprocessing_1]: Failed to process step output: expand_pattern("${outdir}/${input!bn}.{_ids}.bed") ([Errno 24] Too many open files: '/home/gaow/.sos/.runtime/7279dddd31952c2203ebb9aa01df708b.exe_info_')
[preprocessing]: 3 pending steps: preprocessing_2, preprocessing_3, preprocessing_4
ERROR: [preprocessing_1]: Failed to process step output: expand_pattern("${outdir}/${input!bn}.{_ids}.bed") ([Errno 24] Too many open files: '/home/gaow/.sos/.runtime/7279dddd31952c2203ebb9aa01df708b.exe_info_')
[preprocessing]: 3 pending steps: preprocessing_2, preprocessing_3, preprocessing_4
```

Is that the source? I think at some point we've discussed this 2nd issue. #749 . But I'm dealing with having 2000 files here which should not be a big issue I think ...

**Comment by BoPeng** [comment]
Yeah, that at least means the error happened when there were many opened files. Let me have a look.

**Comment by BoPeng** [comment]
Could you try again?

**Comment by gaow** [comment]
Oops:

```
ERROR: unindent does not match any outer indentation level (sos_step.py, line 1133)
```

Let me take a look at this if you are not getting back to it soon.

**Comment by gaow** [comment]
```diff
diff --git a/src/sos/sos_step.py b/src/sos/sos_step.py
index 14e52e03..1323b607 100755
--- a/src/sos/sos_step.py
+++ b/src/sos/sos_step.py
@@ -1127,9 +1127,9 @@ class Base_Step_Executor:
                 if signatures[idx] is not None:
                     signatures[idx].release()
                 if not self.step.task:
-                        if 'sos_run' not in env.sos_dict['__signature_vars__']:
-                            signatures[idx].write()
-                        signatures[idx] = None
+                    if 'sos_run' not in env.sos_dict['__signature_vars__']:
+                        signatures[idx].write()
+                    signatures[idx] = None
                     continue
 
                 # check if the task is active
```
?

**Comment by gaow** [comment]
BTW your last fix seems to be working for my code (assuming my patch above is good). But I'll test more and report back -- if I do not see an issue in a few days maybe I'll close it.

**Comment by BoPeng** [comment]
Thanks, Please fix my patch.

**Comment by gaow** [comment]
Ok this patch is doing some serious damage here:

![2017-09-03-23-29-46_scrot](https://user-images.githubusercontent.com/917985/30011771-d40f9b20-90ff-11e7-95bb-9577c050aaf9.png)

should be easy to fix -- just add a None check wrapper. But it would be great if you could take a look in case you spot any other obvious errors.

**Comment by gaow** [comment]
I suspect this is the proper fix, and my previous indentation logic is wrong?

```diff
diff --git a/src/sos/sos_step.py b/src/sos/sos_step.py
index 1323b607..dcf4d5c8 100755
--- a/src/sos/sos_step.py
+++ b/src/sos/sos_step.py
@@ -1126,11 +1126,11 @@ class Base_Step_Executor:
                 # we should be able to release the signature because external task has its own signatures
                 if signatures[idx] is not None:
                     signatures[idx].release()
-                if not self.step.task:
-                    if 'sos_run' not in env.sos_dict['__signature_vars__']:
-                        signatures[idx].write()
-                    signatures[idx] = None
-                    continue
+                    if not self.step.task:
+                        if 'sos_run' not in env.sos_dict['__signature_vars__']:
+                            signatures[idx].write()
+                        signatures[idx] = None
+                        continue
 
                 # check if the task is active
```

Indentation is perhaps the only think I hate about Python :)

**Comment by BoPeng** [comment]
Fixed. The indentation was correct because a `None` check was accidentally removed. Sorry about the mistake.

**Comment by gaow** [comment]
Great, this is exactly my local patch so no problem I was able to use SoS Notebook all the time tonight.

**Comment by gaow** [comment]
I should say that it is usable, but somehow compared to what it is before, each step takes a lot more time to prepare ...

**Comment by BoPeng** [comment]
Are you sure this is caused by the patch? The patch releases the locks before the tasks are created, in contrast to the old version where the locks are released after the tasks are completed (thus the error). So at least the overall execution time should be the same.

**Comment by gaow** [comment]
Well, I just do not remember having that experience earlier. Now for me I feel like my tasks "choke" -- for lite jobs it takes longer to prepare then than to execute. I'm talking about ~40 jobs. I'll need to do more careful benchmarking before making that claim between old/new version though, so no I'm not sure for now ...

**Comment by gaow** [comment]
I think the slowness might come from the fact that I've got too many `task` in the global sos folder? Because it is getting worse now and even a job involving a single input file takes long time to prepare. I'm still working on something but after production is over I can purge (back up) global sos and try again, to see if that is indeed the cause.

**Comment by BoPeng** [comment]
Currently SoS uses files for tasks and signatures and it does create a lot of small files. If we are not expecting too much concurrent sos instances, using sqlite for signatures should be better. I stayed away from that idea because we have changed our design of signatures a few times. Now that we are approaching version 1.0, perhaps it is time to revisit this issue.

**Comment by gaow** [comment]
Yes it would be great to revisit this. But with `sqlite`? I think our shared past experience was not very smooth with sqlite. It is also kind of a vulnerable system. Are there alternatives?

(this objection might be a bit personal because a few month ago my mendeley database (in sqlite) corrupted and I lost all my notes to PDF files I read -- it was a big mental suffering!!)

**Comment by gaow** [comment]
To show you want I'm experiencing running this MWE:

```
[1]
input: "1.txt"
output: "/home/gaow/Documents/tests/unrelated.min5.L1QC.pdf"
task:
run:
touch ${output}

```
This is how long it takes, for this one file check:
```
INFO: Workflow default (ID=ebf081409880e29f) is executed successfully.

real	0m21.495s
user	0m22.060s
sys	0m5.576s
```

**Comment by BoPeng** [comment]
Output of `ls -lR ~/.sos | wc -l` and `ls -lR .sos | wc -l`?

**Comment by gaow** [comment]
```
[GW] ls -lR ~/.sos | wc -l
266334
[GW] ls -lR .sos | wc -l
61371
```

**Comment by BoPeng** [comment]
The first one is definitely causing the problem. Because that directory has mostly task related files, sqlite for signatures would not help. You could try to purge all completed and failed tasks.

**Comment by gaow** [comment]
Yes I will do it , after my jobs are done here. I think we once talked about automatically cleaning this up -- because users can get very confused otherwise. 

I should add that the `~/.sos` file contains only work of my past 2 weeks. I remembered having deleted the entire folder once quite recently.

I'm a bit hesitated cleaning up completed tasks at this point of my project because that will trigger rerun next time I make minor changes.  However a lot of completed tasks are actually obsolete. That was my initial suggestion to move them to local folder so that I can do it per project by first cleaning it up, then `-s build`. But you did point out reasons we cannot move it to local `.sos`. 

So I'm a bit stuck here. I guess i'll leave with it, until I really have enough of it, then I'll purge completed tasks. Or we can come up with a better solution :)

**Comment by BoPeng** [comment]
We now semi-automatically purge tasks older than 1 month (with each `sos status` call which could be triggered by task engine automatically).

**Comment by BoPeng** [comment]
BTW, not sure how much it can help but you can manually remove all `.out`, `.err`, even `.sh` files which do not interfere with rerun.
