### ISSUE TITLE
[local] section

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#802]
Not sure if this is a good idea but I found myself doing this

```
---
%sosrun BIG
[global]
[BIG]
sos_run('small')
---
%run small
[???]
statement
[small]
---
```

The idea is that I have cells for small tasks, basically steps that I would like to experiment or run interactively, then I would like to run many such steps in `BIG` which has a bunch of `sos_run` calls. The problem here is that `statement` in `small` is supposed to be local, only used for `%run`, and I do not want to put it in `[global]` which would be merged to the global section. However, if I do not use `[global]` and put the statement directly there, the whole cell would be excluded from the notebook workflow because only cells with `[]` would be counted as part of the workflow.

Solution 1:
Define `[local]` section that would be excluded from the global workflow.

Solution 2:
Allow the use of 
```
statement
[step]
...
```
and use another method to decide if `step` should be part of the notebook workflow.

**Comment by BoPeng** [comment]
I think a cleaner solution would be re-defining **notebook workflow as the sum of all sections defined in the notebook**. That is to say, if we have

```
---
statement

[step]
---
```
then statement would be ignored and `step` would be included. In this way `statement` would naturally becomes local.

**Comment by gaow** [comment]
This scope issue is also bothering me. I usually find myself having to define one same variable twice: one under `[global]` to let workflows use them, one as a local statement for interactive analysis. If we are discussing scope related issue then perhaps this user case can also be improved here.

I'm not sure if it is good idea to always make `statement` local. If I understand it right, then it is clearly different from SoS script format where one can just write up statement like that and get them executed.

**Comment by BoPeng** [comment]
Basically what I was proposing was that

```
---
%run
statement

[step]
---

would be treated as a normal workflow with a `[global]` section without header. In the mean time, the notebook workflow would consist of all sections so `[step]` would be included. This is different from the current behavior in which `[step]` is excluded because the whole cell does not start with a section header. The new behavior is actually easier to understand because notebook workflow simply contain all sections.

**Comment by BoPeng** [comment]
A side effect, however, is that we can no longer hide sections in a notebook. Previously we can have examples like

```
---
%run
statement
[example]
---
%run
statement
[example]
```
and none of the `[example]` would appear in the notebook workflow. With the proposed rule, there would be a conflict between the two `example` sections.

**Comment by gaow** [comment]
I see. I misread you. Yes I agree this is more intuitive. I actually have not run into your user case (perhaps just a matter of style)

> A side effect, however, is that we can no longer hide sections in a notebook.

When I need to do it, I convert the cell to markdown temporarily. 

Should I use another ticket to discuss not able to use variables defined in `[global]` in statements outside steps? I think it is also a scope issue that we may want to reevaluate?

**Comment by BoPeng** [comment]
Yes. Let us start another ticket for that.
