### ISSUE TITLE
Restrict `report` only to current cell

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#806]
Since we are on scope discussions tonight let me bring this up too. Currently:

```
----------code cell----------
[step_1]
report: output=...
<markdown codes>

---------markdown cell--------
<markdown codes>
----------------------------------
```

then the 2nd cell's contents will go into the report section. This is bad because that cell is meant to be some narrative only visiable to myself, and a way to organize notebook contents. Should we restrict report only to current cell?

**Comment by BoPeng** [comment]
This in theory should not happen because the code cell does not have access to the content of the next cell.

**Comment by BoPeng** [comment]
<img width="453" alt="screen shot 2017-09-13 at 11 56 26 am" src="https://user-images.githubusercontent.com/9889312/30390096-9e48b47c-987a-11e7-87b0-abc94efba68d.png">

**Comment by gaow** [comment]
Sorry I should have said that it's not a problem when we execute from within SoS. But will be an issue when running from command line:

![2017-09-15-10-47-13_scrot](https://user-images.githubusercontent.com/917985/30491554-44d7d8ca-9a03-11e7-87ca-b39c78bad649.png)


and run it:

```
$ sos run Untitled.ipynb 
INFO: Executing default_1: 
INFO: input:    []
INFO: output:   []
INFO: Workflow default (ID=6bb9b5e18a1843bd) is executed successfully.
$ cat a.md

# this is
# a test

#! ## Now I write something here

```

**Comment by BoPeng** [comment]
I see, it should have been fixed now.

**Comment by gaow** [comment]
Indeed, thanks for the quick fix!
