### ISSUE TITLE
non-SoS config.yml under the same directory

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#809]
This is perhaps a corner case but it did happen to me: I have a file called `config.yml` for something totally unrelated to SoS. I have it in a directory where I also run SoS from, without realizing it. Until I decide to set some configuration via `sos` command. Needless to say my config.yml got edited ... I had to manual undo it, and rename it to avoid conflict with SoS. It is trivial for me but I just worry if we messed up other people's non-SoS `config.yml` they may be quite upset :)

**Comment by BoPeng** [comment]
Proposal?

**Comment by gaow** [comment]
No idea, other than restricting `config.yml` to `~/.sos` and have uses specify the file to load otherwise. Can be a bit inconvenient, but ... is this a scenario that fits "better safe than sorry"?

**Comment by BoPeng** [comment]
Can we simply remove local config an+ rely on the back config and FC?

**Comment by gaow** [comment]
Yes that's my proposal too
