### ISSUE TITLE
Too many task files slows down SoS 

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#810]
This is separated from #796. There is slowness not only in job preparation but also at the end of every for loop in tasks -- my task queue will always halt for about 10 seconds before submitting the next batch of jobs, ie, the overhead of submitting 1000 jobs is 500 seconds. Today I finally can no longer live with the slowness so I removed my `~/.sos/tasks`. Out of curiosity I `tar zcf` before I delete it. It took quite a while to archive it, and generated for me a 1.9G `tar.gz` file. That might be a 10GB sqlite database if that's what we will end up doing, and growing ... that sounds disturbing.

This may be an important issue for heavy duty work. I'm really curious how other software deal with this problem.

**Comment by BoPeng** [comment]
I am not sure how to solve this problem because it appears to be file system dependent, and I am not entirely sure what sos was doing during the delay. There is a possibility that sos was running `sos status`, which will check the modification dates of all `.task` files and `.status` files etc using multiple processes to determine the status of tasks. It is possible to separate the files into subdirectories (e.g. by file type or date) but that will complicate the code without much benefit.

**Comment by gaow** [comment]
Sorry I should follow this up -- I did purge everything but there still seems to be a delay in action execution. I'll provide some more examples over the weekend to back it up and hopefully you could reproduce on your end, and we'll know if it is platform issue (if you do not experience it)

**Comment by gaow** [comment]
Ok this is related to #751 so I'm going to close that one and we focus on the MWE here:

[MWE_50KJobs.ipynb.zip](https://github.com/vatlab/SoS/files/1381122/MWE_50KJobs.ipynb.zip)

This example schedules for 50K tasks. I finally realized the reason that I was not able to provide MWE earlier was probably because my task script is not "long" enough. If I do 50K "echo ${_output} > ${_output}" then it will be done quickly. But this MWE just stuck there for 2 hours before I killed it. Hopefully finally we can fix the issue!

**Comment by BoPeng** [comment]
The first thing I notice is that sos execute tasks in this order

1. generate all tasks 
2. create all task files, combine them in groups if `trunk_size` is specified.
3. sending all of them to execute, and wait for all of them to be completed
4. The master process accepts all tasks and start sending them to workers

Obviously, if there are many tasks, each step can take a while and the tasks should better be run async...

**Comment by gaow** [comment]
I do not think it even has passed step 2 after two hours. It is interesting to note that if the script is short then it is very quick to generate all the tasks.

**Comment by BoPeng** [comment]
Basically `sos_step` was not written with these many tasks in mind. To improve the performance, we will have to have dedicated threads to manage tasks so that creation, writing, and execution of tasks can be done in parallel.

**Comment by gaow** [comment]
And also optimize the procedures somehow? ie. dont run syntax check for all the 50K tasks -- i suspect that's what takes time? For 2hrs wait, I doubt it will be very helpful to even split it to 8 parallel processes.

(I think 50K tasks is not a big number in genomics if we think about number of Genes / SNPs)

**Comment by BoPeng** [comment]
One by one, let me first streamline the generation and execution of tasks, basically sending tasks to workers right after they are created.

**Comment by BoPeng** [comment]
Your tasks should start faster now....

**Comment by gaow** [comment]
Yes, I now see 2 dedicated process preparing for those jobs, but it still takes about 2min. Because you said "basically sending tasks to workers right after they are created.", this makes me wonder whether or not every "batch" of jobs sent will have to wait for 2min? 

I cannot verify it for now because I'm now getting this error:

```
ERROR: [test_0]: NameError at line 1 of 
>>> R(r"""print(999)
    
    """)
name 'R' is not defined
```

from a very simple script:

```
[test]
R:
  print(999)
```

Does it happen on your end?

**Comment by BoPeng** [comment]
`pip install sos-r`?

**Comment by gaow** [comment]
I see, I suspected that. So each time we change the code we'll have to run setup.py followed by pip? Or maybe write an SoS script to install from all repos?

**Comment by BoPeng** [comment]
You mean R worked before but failed after git pull and setup.py?

**Comment by gaow** [comment]
For the MWE in this example, if I replace all R codes with two lines of script, it prepares jobs extremely fast. I guess string interpolation is a bottleneck. For my case I can use #816 to optimize it a bit, but a more upstream optimization would be great.

**Comment by BoPeng** [comment]
So previously you needed to wait 2hr for the first job to be run, right? How log do you need to wait now, and how long do you need to wait if you use short scripts?

**Comment by gaow** [comment]
Previously my jobs did not run after 2hrs. Currently I wait for 2min before it starts to run. If I use short script the wait time is negligible.

And if I run it again, it takes about 10 sec to prepare instead of 2min. Then after every "batch" of tasks it submits and run, it takes about 3 sec to prepare for the next batch. I guess that's not too bad.

**Comment by BoPeng** [comment]
2 min seems to be long. I will check.

**Comment by BoPeng** [comment]
Using your MWE, my first job starts a few seconds after the `input:[]` line.

```
$ rm -rf ~/.sos; rm -rf .sos; time sos run test
INFO: Executing default_0:
INFO: input:    []
INFO: f92f03b77544ef091a0034aea4c753b7 started
INFO: c32b79561adfb80a63fd1ee5ba629020 started
INFO: 4b52db4aeee12680b017ea4c68295f71 started
INFO: c15c2523ca0c9bed3956c7f62f2be7bc started
^CKeyboardInterrupt
ERROR: c32b79561adfb80a63fd1ee5ba629020 interrupted
ERROR: 4b52db4aeee12680b017ea4c68295f71 interrupted
ERROR: f92f03b77544ef091a0034aea4c753b7 interrupted
ERROR: c15c2523ca0c9bed3956c7f62f2be7bc interrupted
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
WARNING: Check output of sos status f92f03b77544ef091a0034aea4c753b7 c32b79561adfb80a63fd1ee5ba629020 c15c2523ca0c9bed3956c7f62f2be7bc 4b52db4aeee12680b017ea4c68295f71 -v 1     failed: Command 'sos status f92f03b77544ef091a0034aea4c753b7 c32b79561adfb80a63fd1ee5ba629020 c15c2523ca0c9bed3956c7f62f2be7bc 4b52db4aeee12680b017ea4c68295f71 -v 1    ' returned non-zero exit status 1.

real	0m7.273s
user	0m15.571s
sys	0m7.798s
```

**Comment by gaow** [comment]
As I mentioned, on my end the first time I run was 2min, but the 2nd time was 10s. Does it sound like possible, or it is some artifact I have here?

Anyways, I'm cool with it as it now only takes a few sec to prepare the jobs. I'm just wondering if there are some apparent optimization possible. For example, syntax check only for one out of many `for_each` -- although I appreciate its danger.

**Comment by BoPeng** [comment]
I removed `.sos` so I am not sure what was causing the first-time delay. This patch broke unit tests because of its interaction with sos kill etc and I have to fix that...

You also mentioned something like 10s after each task completes, do you still see it?

**Comment by gaow** [comment]
> You also mentioned something like 10s after each task completes, do you still see it?

No, not 10s, but rather 2s delay. I still see it. It's not a bit deal if the computation is heavy enough.

**Comment by BoPeng** [comment]
OK. I guess the issue can be considered fixed for now.
