### ISSUE TITLE
SoS homepage is not mobile friendly.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#815]
When I view the homepage on my mobile phone, there are two problems:

1. header image is too tall.
2. The pages are displayed within the screen but can be scrolled left or right.

**Comment by BoPeng** [comment]
These have been fixed with the use of bootstrap cells for tables.

**Comment by gaow** [comment]
The "Documentation" navigation tab on the homepage seems to be broken.

**Comment by gaow** [comment]
Sorry -- nevermind my previous message. It's apparently due to the slow wifi signal I have on this corner of the campus ...

**Comment by BoPeng** [comment]
We should remove TOC bar for documentation in mobile mode.

**Comment by BoPeng** [comment]
Good. The docs are readable on smartphones now.
