### ISSUE TITLE
Strange string in online help message

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#817]
Not sure what is going on with the `rreeppoorrtt` as in 

![screen shot 2017-09-27 at 9 31 18 pm](https://user-images.githubusercontent.com/9889312/30946720-52dfabc4-a3cb-11e7-973c-0a9d9ba29425.png)

**Comment by gaow** [comment]
How did u trigger that? I never realized one can read help message this way!

**Comment by BoPeng** [comment]
Shift-tab.

**Comment by BoPeng** [comment]
You can also use this to inspect variables, although only for sos variables because no cell/kernel information is provided.

**Comment by BoPeng** [comment]
The returned text from `pydoc` has `\x08`, which should be something to emphasize the function name

![image](https://user-images.githubusercontent.com/9889312/30947579-251bdbcc-a3d0-11e7-96e7-5afdb233775c.png)
