### ISSUE TITLE
Improve search function of sos website.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#818]
The search function (at the top right corner of [SoS homepage](https://vatlab.github.io/SoS/))  is currently implemented by [tipue](http://www.tipue.com/search/) in static mode. More specifically,

1. Script [index_site.py](https://github.com/vatlab/SoS/blob/master/docs/js/index_site.py) is run manually (with release) to index headers of all pages to create [tipuesearch_content.js](https://github.com/vatlab/SoS/blob/master/docs/tipuesearch/tipuesearch_content.js). This process used [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/) to parse our pages. We grab only headers because we do not want to create huge `tipuesearch_content.js` that takes a lot of time and ram to load, and because it is better to target the most important items (headers) of the website.

2. When the search function is called, it opens [Search.html](https://github.com/vatlab/SoS/blob/master/docs/search.html) and calls 
[tipuesearch](https://github.com/vatlab/SoS/blob/master/docs/tipuesearch/tipuesearch.js#L12) to generate result page.

We need to improve the appearance and functions of the search box. In particular, because our headers (e.g. [this one](https://vatlab.github.io/SoS/doc/documentation/SoS_Step.html#Option-filetype-122) has link anchors and can be jumped upon directly, we would like to display the results better in the search page and be able to jump directly to headers from the search page.

Tasks:

1. The search box and github icons are of different height and do not align well. We will need to adjust the height of the search box to match github icons in [testtab.css](https://github.com/vatlab/SoS/blob/master/docs/css/testtab.css#L201).

2. Improve [index_site.py](https://github.com/vatlab/SoS/blob/master/docs/js/index_site.py) is run manually (or automatically with [`release`](https://github.com/vatlab/SoS/blob/master/development/release) script when the html files are updated ) to generate better "text" to store the anchors. For example, instead of saving `Option filetype` for the aforementioned URL, we save `Option filetype #Option-filetype-122`. This can be achieved by better handling in the BeautifulSoup parsing.

3. Improve [tipuesearch](https://github.com/vatlab/SoS/blob/master/docs/tipuesearch/tipuesearch.js#L12) to better display the output. Basically, this function will find the item and display its context. We will need to change that part to display URLs from the anchors. That is to say, for matched text `filetype` with line `Option filetype #Option-filetype-122`, we display `<a href="https://vatlab.github.io/SoS/doc/documentation/SoS_Step.html#Option-filetype-122">Option filetype</a>`.

4. A search box has been added to each doc page but its destination is the default `search.html`. It would be better to send results to a search page with side panel so everything will be within the doc style.

Current screenshot:
![image](https://user-images.githubusercontent.com/9889312/31046245-1c5b49f4-a5bb-11e7-954b-76cfde3290ef.png)

Need to have the anchored link(s) directly under the title.

**Comment by gaow** [comment]
This is a great step forward! Should we also change the notebook template file so that every page can have a search function?

**Comment by BoPeng** [comment]
I wrote this ticket in such a detail to allow my high-schooler boy to try to tackle some of them. I have added the template request but that one might be too difficult for him. We will see.

**Comment by gaow** [comment]
I wish I had this project when I was in high school! The manuscript should acknowledge @willischool for his contributions :)

**Comment by BoPeng** [comment]
Note that the entire website has been moved to the `sos-docs` repository.

**Comment by gaow** [comment]
But we'll still be using the https://vatlab.github.io/SoS URL right? Via URL redirect as we've done before?

**Comment by BoPeng** [comment]
Yes, and I pruned the repo to reduce the size of `sos` from 70M to 10M.

But for some reason `/sos/` and `/SOS/` works, `/SoS/` shows some partial page. There is now no `docs` folder under the `SoS` repo so I am wondering what is going on now. I am waiting a bit because things change fast and there might be cache and github response problem.

**Comment by BoPeng** [comment]
I suppose we need to add `docs/index.html` to `SoS` with a redirect?

**Comment by gaow** [comment]
I think we should disable `gh-pages` altogether in SoS repo, then use this repo to redirect:

https://github.com/vatlab/vatlab.github.io

(what we now see might be gh-pages relic that we should not need to worry once we disable gh-pags for that repo)

**Comment by BoPeng** [comment]
I have just done that, waiting for github to respond.

**Comment by BoPeng** [comment]
OK, Now I get a 404. Need to create a `SoS` folder similar to `sos` and `SOS`?

**Comment by gaow** [comment]
Yes that'd be the way to go!

**Comment by BoPeng** [comment]
Still 404, waiting.

I was wondering if we should move everything to `vatlab.github.io/SoS/` so that we do not have to maintain two repos, but since I am moving vtools website from `sf.net` to `github.io`, I suppose it is a bad idea to host two websites in one repo.

**Comment by gaow** [comment]
I think the current setup gives us more flexibility, and a nice overview of lab projects :)

**Comment by BoPeng** [comment]
Still 404, I think we should enable gh-pages for SoS and add `index.html` under `docs`.

**Comment by BoPeng** [comment]
redirect from `SoS/docs/index.html` works.

**Comment by gaow** [comment]
Well, actually 31min ago (when I left my last comment) I was able to access it via the `vatlab.github.io/SoS` redirect. So perhaps it was your browser cache. ...

**Comment by BoPeng** [comment]
I do not trust you ... and there is no point to try again.

**Comment by BoPeng** [comment]
With a few pull requests, we are getting

![image](https://user-images.githubusercontent.com/9889312/31322362-f03ccb48-ac5b-11e7-9425-4325d86f6259.png)

Better, but the search box is still larger than the github icon...

**Comment by BoPeng** [comment]
The search icon was fixed when I added the rocket (launch) button, see https://github.com/vatlab/sos-docs/commit/837f3100e64e1e658982c980ceb90a729c855053 for details.

**Comment by BoPeng** [comment]
The URL for the links are wrong (use `/SoS/doc`, and should be `/sos-docs/doc`).

**Comment by BoPeng** [comment]
@Qwertyuiop21672 To avoid trouble in parsing the text again in JS, it is easier to create multiple entries in the search list in Python. I mean, instead of creating

```
{"title": "title", "text": "header1 #header1\n header2 #header2", "tags": "", "url": "some.html"},
```
to present search result as 
```
<a href="some.html#header1">header1</a>
```,

you can create search content

```
{"title": "title", "text": "header1", "tags": "", "url": "some.html#header1"},
{"title": "title", "text": "header2", "tags": "", "url": "some.html#header2"},
```
so that tipue search would create almost acceptable output that needs only slight modification.

**Comment by BoPeng** [comment]
![image](https://user-images.githubusercontent.com/9889312/31953662-2596c9c0-b8a9-11e7-908a-ea46f06fc079.png)

This is already way better than our previous search function. The next step would be organizing the results better. I would propose that

1. We show the main title of the search result. Right now we only keep section header so the user does not know which document the results belong.
2. Group headers from the same document together.
3. Remove the link and text from the output because they do not provide userful information.

So, in the end, if we search for word `option`, we should get something like

```
Document 1
   option 1
   option 2
Document 2
  option 1
```

**Comment by BoPeng** [comment]
Done. Kudos to @Qwertyuiop21672
