### ISSUE TITLE
Tagging tasks

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#819]
Related to #486, I think it is helpful to **tag** tasks with keywords, something like

1. When a task is created, it is automatically tagged with workflow name, step name, index etc.
2. Tag does not affect the creation of IDs so tasks with the same content still refer to the same task (ID).
3. Tags are displayed with `sos status` etc
4. Tags can be used to submit, kill, resume tasks in batch.

Proposed interface:

1. `task: tags='horn'`: adding specified tag(s) to the tag list.
2. `sos status`: display tags
3. `sos status -t horn`: display all tasks with tag `horn`
4. `sos kill -t default_2`: kill all tasks submitted by step `default_2`

**Comment by gaow** [comment]
+1 for this feature!

**Comment by BoPeng** [comment]
Implementation wise, it is tricky to handle identical tasks generated by different steps/workflows. They should have the same IDs but the tags should somehow be merged. We can argue that this is a corner case that we can ignore for now.

**Comment by BoPeng** [comment]
For performance considerations, we cannot afford to read each file to get the tags. It therefore only makes sense to use file system extended attributes to store tags. Here are the facts

1. Python 3.3 + supports [extended file attributes](https://python.readthedocs.io/en/latest/library/os.html) but only for Linux.
2. [`xattr`](https://github.com/xattr/xattr) supports both linux and mac.
3. windows supports such attributes, but it is very complicated and there is no Python library for it (as far as I know).
4. These attributes tend to get lost but `rsync` has limited support for it so there is a good chance that we can make it work within and between mac and linux.

It is unlikely that this feature will work very well in a cross-platform fashion but we might be able to get it working reasonably well locally (linux and mac)...

**Comment by BoPeng** [comment]
Given the complexity of extended attributes across platforms, it seems easier to use customized header for `task` files. Hopefully reading 1k from task file when tags are needed is not that slow.

**Comment by BoPeng** [comment]
There is also the question whether tags should be simple lists or dictionaries. Generally speaking, tags are named keys but simple lists could be easier to use.
