### ISSUE TITLE
Remote task copy error

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#822]
This uses the same MWE as #820 . Only this time I added `-r` because it is too much data to sync:

```
sos run ~/Dropbox/1.sos -q midway2 -r midway2

```
And I get these error (this is `-v2` output but `-v4` is not any more informative):
```
INFO: Executing default_1: 
INFO: input:    []
ERROR: Failed to query status of tasks []: Command 'ssh -q gaow@midway.rcc.uchicago.edu -p 22 "bash --login -c '[ -d /home/gaow/GIT/github/gtex-eqtls ] || mkdir -p /home/gaow/GIT/github/gtex-eqtls; cd /home/gaow/GIT/github/gtex-eqtls && sos status  -v 2  --start-time '" ' returned non-zero exit status 255.
INFO: On midway2: _output = ['/home/gaow/GIT/github/gtex-eqtls/1_A.txt', ...] (16 items)
ERROR: Failed to copy job /home/gaow/.sos/tasks/midway2/M16_36934469c90d2d7f4fa78b1620fa3e15.task to midway2 using command ssh -q gaow@midway.rcc.uchicago.edu -p 22 "[ -d ~/.sos/tasks ] || mkdir -p ~/.sos/tasks" && scp -q -P 22 /home/gaow/.sos/tasks/midway2/M16_36934469c90d2d7f4fa78b1620fa3e15.task gaow@midway.rcc.uchicago.edu:.sos/tasks/: Command 'ssh -q gaow@midway.rcc.uchicago.edu -p 22 "[ -d ~/.sos/tasks ] || mkdir -p ~/.sos/tasks" && scp -q -P 22 /home/gaow/.sos/tasks/midway2/M16_36934469c90d2d7f4fa78b1620fa3e15.task gaow@midway.rcc.uchicago.edu:.sos/tasks/' returned non-zero exit status 255.
ERROR: Failed to retrieve result of job M16_36934469c90d2d7f4fa78b1620fa3e15 from midway2 with cmd
scp -P 22 -p -q gaow@midway.rcc.uchicago.edu:.sos/tasks/M16_36934469c90d2d7f4fa78b1620fa3e15.* /home/gaow/.sos/tasks
ERROR: Command 'ssh -q gaow@midway.rcc.uchicago.edu -p 22 "bash --login -c '[ -d /home/gaow/GIT/github/gtex-eqtls ] || mkdir -p /home/gaow/GIT/github/gtex-eqtls; cd /home/gaow/GIT/github/gtex-eqtls && sos run /home/gaow/Dropbox/1.sos -q midway2'" ' returned non-zero exit status 1.
```

It complains about 255 return status, but when I check, for example, the first command it complains, in `bash`, it works. Also I called it in Python via `subprocess.call` and the return code is zero. 

Am I missing something here? What else can I check?

**Comment by gaow** [comment]
Ok I think I've figured out the problem -- I should have configured the remote machine's default queue to using the PBS system, and remove `-q` switch ... otherwise it will result in a circular job submission scenario. I'm going to add a note in the documentation and close the issue with that commit.

**Comment by BoPeng** [comment]
Thanks. I was very busy with the big split.

**Comment by gaow** [comment]
>  I was very busy with the big split.

That is very important! This issue was my undoing anyways: I recently purged my `~/.sos` folder on the remote but failed to reconfigure its localhost properly. I added a note in the doc already (notebook un-compiled for now), and close this issue.
