### ISSUE TITLE
%toc magic in main notebook

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#826]
We have the `%toc` magic in the side panel but it could be useful to execute the `%toc` magic in the main notebook, which would create a toc in the main notebook, even in the exported HTML file.

**Comment by BoPeng** [comment]
This is more difficult than I expected. Basically, just displaying the toc in the main notebook is not difficult, but to include the TOC in the exported HTML file, the TOC needs to be returned as a regular output so that they can be part of the cell output.

**Comment by j-andrews7** [comment]
Are there any plans for this? It would be quite useful. Consider this another vote for such a feature.

**Comment by BoPeng** [comment]
`%toc` is good enough when editing a notebook so I think inserting a TOC in the notebook is primarily used to add a TOC to the exported HTML report (through `%sossave` magic). However, automatic generation of a TOC is a common practice for many HTML templates (e.g. [Rstudio report](https://rmarkdown.rstudio.com/html_document_format.html)) so there is less a need to insert it at the notebook level. I am therefore thinking that adding TOCs to our templates (e.g. [sos-report template](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/sos-report.tpl)) is more flexible (because we can have many templates in different styles) and therefore a better choice.

That said, I am not a HTML/JS expert and it is challenging for me to write customized Jupyter templates to produce reports as nice as what RStudio/Knitr is generating. Perhaps I should dissect a knitr report and borrow its TOC code even CSS. :smile:

**Comment by BoPeng** [comment]
sos ntoebook now offers template `sos-full-toc`, `sos-report-toc`, `sos-cm-toc`, which automatically adds a toc to the generated HTML file. See https://github.com/vatlab/sos-notebook/issues/89 for details and usage and https://vatlab.github.io/sos-docs/doc/examples/RNASeqDE.html for an example.

**Comment by BoPeng** [comment]
I have found it still usable to have a static toc generated by `%toc`.

**Comment by BoPeng** [comment]
Implemented with an additional option `--id`, with documentation [here](https://vatlab.github.io/sos-docs/doc/documentation/SoS_Magics.html#magic_toc).
