### ISSUE TITLE
Delayed cluster job submission

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#829]
I wonder if it is good to have some task options that, after preparing for jobs, only submit N of them at a time to the remote system until they are completed, then submit new jobs. Long story short I need to analyze some data by submitting 200 jobs (cannot make this smaller due to various constraints). But the cluster system will only run 40 jobs per user at a time. When I submit, either 160 gets queued there for days which is not very nice, or I can perhaps submit 40 at a time manually. It would be nice if SoS can manage this for me, though, so that I can submit all jobs at once yet without having them all queued on the PBS system.

**Comment by BoPeng** [comment]
Did you define max running jobs to be 40 for the cluster?

**Comment by gaow** [comment]
Ahh Okey of course that's the option for it. I never have related `-J` to number of tasks in the PBS queue but it is obviously the case!
