### ISSUE TITLE
Installing all SoS modules from github repo

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#830]
This is separated from #810 . After code refactoring, it seems every time I `git pull` the core repo and install the latest code, my other modules are lost. I'll have to run `pip` to get them back. Is this the case? Any shortcuts to propose?

**Comment by BoPeng** [comment]
Can you confirm this? On my machine

1. `python -c 'from sos.runtime import bash`
2. `git pull`
3. `python setup.py install`
4. `python -c 'from sos.runtime import bash`

works fine.

**Comment by gaow** [comment]
It is fine too on my end. I had not installed `sos-r` separately. Is it included in `sos-essentials` (the one that I'm sure I've installed)!

**Comment by BoPeng** [comment]
Should be, https://github.com/vatlab/sos-essentials/blob/master/setup.py#L88

**Comment by BoPeng** [comment]
So next time on a new machine you can try to install `sos-essentials` and check `pip list | grep sos` and see if these packages are installed correctly.

**Comment by gaow** [comment]
Ok will do that. It's likely my installation has failed on my home computer that I did not notice. In fact you've probably noticed `pip` will generate a few seemingly scary yet benign errors so I stopped worrying (i even put  a note on the documentation -- Note for Conda users on  https://vatlab.github.io/sos-docs/#runningsos). But this seems to be a case it in fact failed.

Close the issue for now because it is likely an accidental `pip` fail.

**Comment by BoPeng** [comment]
There is a separate issue though.

The `R` action is used by `sos`, and `R` language is used by `sos-notebook`. Although the latter can be difficult to setup, the former does not need any dependency and in fact be installed and used without `sos-notebook`. Actually, on a server setup, people might want to install all actions but not the language modules.

So it seems natural to move all actions and targets from language modules to `sos` and leave `sos-r` etc as pure language modules for `sos-notebook`, but on the other hand I tend to like the separation of components by language.

**Comment by gaow** [comment]
Now again I get:

```
ERROR: [ms_1]: Failed to process step depends: Py_Module('sklearn'), Py_Module('plinkio') (name 'Py_Module' is not defined)
```
which was fixed by `pip install sos-python`. So something is indeed going on with my computational environment.

**Comment by gaow** [comment]
Ok my `bash` also failed. Here is what I did:

```
$ python -c 'from sos.runtime import bash'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'bash'

$ cd ~/GIT/software/SoS; git pull
Already up-to-date.

$ python setup.py install
$ python -c 'from sos.runtime import bash'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'bash'

$ pip install sos-bash
$ python -c 'from sos.runtime import bash; print("done!")'
done!
```

**Comment by BoPeng** [comment]
The packages are "related" by `install_requires` and `entry_points`, and I have not heard of anything that causes the removal of `sos-bash` with the installation/update of `sos`. I will try to reproduce it (e.g. running `from sos.runtime import bash` before and after updating sos).

**Comment by BoPeng** [comment]
I can now reliably reproduce this on my machine. Not sure how this was set up but

1. No `sh`

 ```
[bpeng1@bcbm-bpeng:~/sos-bash (master)]$ python -c 'from sos.runtime import sh'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'sh'
```

2. Install `sh`,

```
[bpeng1@bcbm-bpeng:~/sos-bash (master)]$ python setup.py install
running install
running bdist_egg
running egg_info
writing src/sos_bash.egg-info/PKG-INFO
```

3. works

```
[bpeng1@bcbm-bpeng:~/sos-bash (master)]$ python -c 'from sos.runtime import sh'
[bpeng1@bcbm-bpeng:~/sos-bash (master)]$
```

4. re-install `sos`

```
[bpeng1@bcbm-bpeng:~/sos (master *)]$ python setup.py install
```

5. `sh` is gone

```
[bpeng1@bcbm-bpeng:~/sos-bash (master)]$ python -c 'from sos.runtime import sh'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'sh'
[bpeng1@bcbm-bpeng:~/sos-bash (master)]$
```

Need to figure out where `sh` is stored and how to retrieved, and how the installation of `sos` removes the `sh` entry point.

**Comment by BoPeng** [comment]
This is interesting:

```
Failed to load target bash: (sos 0.9.9.7 (/Users/bpeng1/anaconda/lib/python3.6/site-packages/sos-0.9.9.7-py3.6.egg), Requirement.parse('sos>=0.9.9.8'), {'sos-notebook'})
```

In `sos-bash`, we have

```
    install_requires=[
          'sos',
          'sos-notebook',
          'bash-kernel',
      ],
```

which does not say anything about version of sos but it is somehow linked to the pip version 0.9.9.8. When local sos is installed, which lags behind pip version 0.9.9.8:

```
[bpeng1@bcbm-bpeng:~/sos (master *)]$ sos --version
sos 0.9.9.7 for Python 3.6.1
```

so it stops `bash` from being loaded.

So the solution seems to always keep git version ahead of pip version...

**Comment by BoPeng** [comment]
I will close this ticket unless the problem arises again.
