### ISSUE TITLE
Monitor of task failed

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#834]
I've got errors in my jobs that I cannot reproduce with MWE:

```
f52d9658a018085e6a00abc693e7b701.err:
=====================================
2017-10-23 23:56:11,290: INFO: f52d9658a018085e6a00abc693e7b701 ``started``
2017-10-24 00:07:12,680: DEBUG: Monitor of f52d9658a018085e6a00abc693e7b701 failed with message psutil.NoSuchProcess process no longer exists (pid=11451)

f52d9658a018085e6a00abc693e7b701.out:
=====================================
```

Basically each of these task calls a variant of [this script](https://github.com/knmkr/lift-over-vcf) which runs one `liftover` for every variant; each `liftover` will result in a PID. I run this for all chroms in parallel. After a few minutes the jobs started, they all failed like this:

```
WARNING: Result for f52d9658a018085e6a00abc693e7b701 is not received
ERROR: 23 jobs aborted
```
But in fact the actual python process of `vcf-liftover` still seems to be running and the result files are still constantly updated. I'll wait until it finishes to check the outcome. Maybe the task PID can change for python scripts involving `subprocess.Popen`?

**Comment by BoPeng** [comment]
Yes. It appears that the original process that started the task has been killed but the subprocesses that performing the actual task are still alive. The monitor script traces all subprocesses from the root process and thus the error.

So although it is possible to monitor the task without the main process, the key here is to grab its subprocess before it dies, and that can or cannot be done depending on how the subprocess was spawned.

**Comment by gaow** [comment]
Update: I left the processes running. Even though those jobs are said "aborted" a few hours ago, I can now see these on the screen:

```
INFO: f52d9658a018085e6a00abc693e7b701 completed
INFO: fce629998142b46182c03042dc0e4538 completed
```
which seems proper; and apparently SoS still tries to monitor them, rather than abort.

**Comment by BoPeng** [comment]
With that message, the monitor thread would consider the process to be died and stop monitoring (you can check the `.status` file to confirm this). SoS does not kill the already-died task and let it run. It would show task as canceled but after the task has been completed (with a result file), it would claim the task to be completed.

**Comment by BoPeng** [comment]
As I have said, it is possible to trace all subprocesses in https://github.com/vatlab/SoS/blob/master/src/sos/monitor.py#L54 . Basically, you can try to put all `child` in `self.pid` and get the subprocesses of them all while ignoring dead ones. You can implement this when you see such problem again and let me know if we should do that.

**Comment by gaow** [comment]
Hmm this is what `sos status` currently say:

```

EXECUTION STATS:
================
status               completed
task                 f52d9658a018085e6a00abc693e7b701
nproc                7
start                2017-10-23 23:56:11
end                  2017-10-24 00:06:12
duration             00:10:01
cpu_peak             2.4
cpu_avg              1.5
mem_peak             115.9Mb
mem_avg              95.9Mb
f52d9658a018085e6a00abc693e7b701.err:
=====================================
2017-10-23 23:56:11,290: INFO: f52d9658a018085e6a00abc693e7b701 ``started``
2017-10-24 00:07:12,680: DEBUG: Monitor of f52d9658a018085e6a00abc693e7b701 failed with message psutil.NoSuchProcess process no longer exists (pid=11451)
2017-10-24 04:46:15,693: INFO: f52d9658a018085e6a00abc693e7b701 ``completed``

f52d9658a018085e6a00abc693e7b701.out:
=====================================
```

which adds one line of `completed` to the previous status.

> Yes. It appears that the original process that started the task has been killed 

I wonder why this happens in the first place (that the task is already-died), particularly if there is something wrong with the `bash` process that runs the task, because that seems scary -- wondering if the computational results can be trusted.

> the key here is to grab its subprocess before it dies

Again, why would it die when it is supposed not to?

> Basically, you can try to put all child in self.pid and get the subprocesses of them all while ignoring dead ones. You can implement this when you see such problem again and let me know if we should do that.

I'm not sure if I understand the logic but the problem is readily reproducible with my example here so I can let it finish first (still needs >30hrs) and try what you suggest.

**Comment by gaow** [comment]
I believe I'm going to test this issue very soon in the current stage of my project -- by the end of the month for sure. But not tonight. Shall we leave it open for another week to allow for test?

**Comment by BoPeng** [comment]
ok.

**Comment by gaow** [comment]
I believe it is good enough now. Possibly also due to better error traceback https://github.com/vatlab/sos-notebook/issues/31
