### ISSUE TITLE
Allow execution of nested workflow from another file

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#837]
Given that we can use another script as a module or file

```
python: input='another.py'
python:
    import another
```

or execute the workflow with `sos run` command

```
!sos run another.sos
!sos run another.ipynb
```

I am wondering what is the value of `%include`.

**Comment by gaow** [comment]
I think this is related to a previous discussion of best practice. `%include` makes some SoS script utilities, and helps with modularizing the workflow, if desired. Otherwise we cannot use steps defined in another script, right?

**Comment by BoPeng** [comment]
So the value currently is to include "steps" from another notebook/script as part of the existing workflow. 

What if we make this an option for nested workflow (`sos_run`)? Something like

```
sos_run('workflow', source='another.ipynb')
```

**Comment by gaow** [comment]
That's good -- I think that's even more clear!

**Comment by BoPeng** [comment]
OK, I will make this an option and you can check if all your need for `%include` and `%from ... include` could be met by it.

**Comment by BoPeng** [comment]
Note that we had this `source` option for `sos_run` before, and we even had something rather complicated  (```sos_run('a + b', source={'a': 'fileA.sos', 'b': 'fileB.sos'}```), but we removed this option in favor of `%include` because the latter allows, for example, the inclusion of a large number of auxiliary steps that might or might not be used in the existing workflow.

**Comment by BoPeng** [comment]
The re-introduced `source` parameter to `sos_run` accepts a single filename. Let me know if this is good enough.

**Comment by gaow** [comment]
I haven't checked yet but just want to make sure this feature has been updated on the wiki (no need to point me the link because I can find it when you confirm that the wiki is up to date). I'll surely get to it later and close the ticket after succesfully converting my relevant scripts.

**Comment by BoPeng** [comment]
Yes. The document is now updated, and thanks for my boy, you can use the improved search function to search for it (still needs to be improved, but much more usable already).

**Comment by BoPeng** [comment]
I have summarized ways to use external script/module/workflow/commands [here](https://vatlab.github.io/sos-docs/doc/documentation/SoS_Syntax.html#Modularize-SoS-Workflow-16). I will remove `%include`, `%from`, `%if`, `%else` etc form SoS format if current mechanisms are enough.
