### ISSUE TITLE
Input parameter of actions.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#839]
The input parameter of actions actually serves two purposes now:

1. for script running actions, the content of the input will be prepended to the script.
2. if both `input` and `output` exist, sos will try to create a task level signature to skip the action.

I did not realize this problem when we added feature 1. It is a bad idea to let one parameter server two purposes.... for example, if a user wants to create step signature with some arbitrary `input`, then the script will be broken.

**Comment by gaow** [comment]
> if both input and output exist, sos will try to create a task level signature to skip the action.

I do not quite follow what's the practical use for this. Actually I was not aware there is such a feature. Would you elaborate the user case?

**Comment by BoPeng** [comment]
Accidentally edited your comment on a cellphone app...

**Comment by BoPeng** [comment]
The parameter actually have a third use. That is to check the existence of `input` and `output` files before and after the execution. The actions themselves do not have to use `input` and `output` in any way.

**Comment by BoPeng** [comment]
Since the signature feature is the least known feature, I suppose we can move it to something else, perhaps a parameter called `tracked`.

**Comment by gaow** [comment]
Yes it bites me now : 

```
[1]
output: '1.yml'
task:
res = 1
report: output = "${output}"
  res
```

this workflow is  broken:

```
ERROR: c0c64086c09c19aece3dd92efacb3fb4 failed: Invalid output ['1.yml'].
```

So indeed we have to rename it now ...

**Comment by BoPeng** [comment]
Try again. I have moved the feature to parameter `tracked`. The first commit broke something, it should be ok now.

**Comment by gaow** [comment]
I tried it about 15min ago. It worked for my old pipeline!

**Comment by BoPeng** [comment]
Great. I will close the ticket after update the documentation.

**Comment by BoPeng** [comment]
Done. I do like the new `tracked` parameter better than `input` and `output` because signature-tracking was a side-effect or something seemed irrelevant.
