### ISSUE TITLE
Global section evaluated multiple times

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#840]
Running this MWE with `-J 4`

```
[global]
genes = [1,2,3,4]
print(genes)

[1]
input: None, for_each = 'genes'
output: "${_genes}.txt"
run:
  touch ${_output}
```

I get:

```
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]
INFO: Executing default_1: 
INFO: input:    []
touch 1.txt
touch 2.txt
touch 3.txt
touch 4.txt
INFO: output:   ['1.txt', '2.txt', '3.txt', '4.txt']
INFO: Workflow default (ID=f2e71d543f0e49da) is executed successfully.
```

Apparently the `global` section is evaluated 5 times (why 5 times?). This is not very clean. Also what I actually do in my project involves some non-trivial computation in `global` section so evaluation it multiple times slows things down quite a bit, too.

**Comment by gaow** [comment]
Also I see it's evaluated at the beginning of the 2nd step. eg, my script looks like:

```
[global]
...
print('{} genes to analyze for {}'.format(len(genes), tissue))

[default_1]
...
[default_2]
```

When I run with `-J 40` I get:

```
1 genes to analyze for Thyroid
1 genes to analyze for Thyroid
1 genes to analyze for Thyroid
1 genes to analyze for Thyroid
1 genes to analyze for Thyroid
1 genes to analyze for Thyroid
1 genes to analyze for Thyroid
1 genes to analyze for Thyroid
INFO: Executing default_1: utils
INFO: input:    []
INFO: output:   ['/home/gaow/Documents/GTExV8/.utils.R']
1 genes to analyze for Thyroid
INFO: Executing default_2: 
INFO: input:    []
INFO: db16a2022c77a52e9471ff5004136ce3 started
```

You see one line gets printed in between the 2 steps.

**Comment by BoPeng** [comment]
The global section is designed to contain "definitions" that will be used by each step, and is executed at the beginning of each step in the current implementation. Although it is possible to define a `sos_dict` that contains the global definitions (after executing global section once) and be used by each step, the dictionary might not be pickleable and thus cannot be passed to each worker.

So basically the global section should only contain definitions, not any computation.

**Comment by gaow** [comment]
I see. But what if I do need to compute some global level quantities, would it work if I just write them outside `global` section ( I seem to remember that it will not work for SoS Notebook without `global`) ?

**Comment by gaow** [comment]
Or I should use a separate step for it, and expose it to other steps via `shared`?

**Comment by BoPeng** [comment]
Yes. That would be the recommended method.
