### ISSUE TITLE
Add PBS job id to sos tasks

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#843]
After jobs are submitted, we can add the PBS task id to task tags, which makes it easier to track tasks and jobs.

**Comment by BoPeng** [comment]
The problem here is that the `task` files are usually on remote host. What we do right now is

1. transfer `.task` file to remote host
2. create `.sh` file and send to remote host
3. submit the job and obtain `job_id`

If we are to add `job_id` to task, we will have to modify the task file locally and re-send `.task` file to remote host, which can be done but does not look like a good idea.

**Comment by BoPeng** [comment]
An alternative is to by default add `name` to `tags` so that we can tell from job id from the task id. In the current implementation, it is difficult to link pbs jobs and sos tasks.

**Comment by gaow** [comment]
Sorry I did not weigh in on this one. Typically the way I use remote PBS system is to do `-r` directly without file transfer (because of too many / too large output files) -- that might have made things easier. For the time being, I was not actively tracking job ID's because it does not seem to be a need. But I can imaging many cases when it will matter.

**Comment by BoPeng** [comment]
Basically I need a way to link task id, pbs job id or name, and sample id. If task fails, I need to know which sample fails, and sometimes which job fails. Currently `name` can be set to `ID` (if there is such info) to link sample id to job name, but there is no easy way to link task id to pbs job. So we can

1. Rename `name` so that task id is always the same as job name. (#842)
2. Add value of `name` to `tags` automatically to link sample ID to tasks.

I tend to remove `name` because
1. one less parameter, users do not need to worry about adding `ID` to `name` and/or `tags`.
2. task id is always the same as job name, which makes things a lot easier.

**Comment by gaow** [comment]
> I tend to remove name because

Remove `name` from task_id or from SoS `task` options? I still see the value of `name` though. I always find PBS job id is a bit hard to keep track of. But many systems will additionally list names in parallel with job ID, which is an appealing feature to me.

**Comment by BoPeng** [comment]
Remove name from task options so that PBS job will always use task ID. This is ok because tags allows multiple IDs such as workflow ID, step name, and sample ID so it is always better to use task tags.
