### ISSUE TITLE
Remove SoS' own string interpolation feature

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#844]
There has been several tickets on string interpolation, arguing if we should have such a feature given that python already has a bunch of string formatting features, namely`%`, `str.formt()`, and format string (`f" "`) in Python 3.6.

Reasons to remove string interpolation:
1. It makes SoS incompatible with Python. (**SoS is not compatible with Python anyway**)
2. Our implementation suffers from a closure bug that has been mentioned in [PEP498](https://www.python.org/dev/peps/pep-0498/), namely string interpolation can fail when it is used inside another namespace (e.g. inside a function). **Touching core function feature is always tricky...**
3. It slows down SoS quite a bit when it is used, for example, in a loop. **this could potentially be addressed with more optimization**

Reasons to keep string interpolation:
1. The SoS style conversion is useful in SoS (e.g. avoid `output[0]` if there is only one element). **We could define a new type for SoS path and define `__format__` function for it, but this only solves part of the problem.**
2. The added conversion operators are very handy for path manipulation. **but instead of conversion (`!`), we could use customized format spec**
3. Using `{ }` for string interpolation can be very troublesome for R scripts, which is one of the primary supported languages. **We could pre-process strings to keep our sigil option**
4. format string only supports Python 3.6 so we will have to move up to Python 3.6. **This is not a big problem as 3.6 should be quite popular when SoS becomes popular**.
5. we have used string interpolation quite a bit in SoS and it can be difficult to change,  **but we can define SOS format 2.0 without string interpolation**.

So there are few options:
1. Keep things as it is... not ideal, with problems, but it is working more or less ok.
2. Use existing string interpolation feature only for script format. This is easiest to do and we can just say script format is `action(interpolate(script))`. `interpolate` has to be used explicitly in other places if needed.
3. Completely remove string interpolation ...  in the next sos format. To compensate for the existing features, we will have to assume scripts as format strings, define a new type for paths, and define customized `__format__` function for them.

I tend to think the second option is the best because
1. it addresses all three reasons to get rid of string interpolation.
2. it largely keeps all the features we are familiar with...
3. the use of `interpolate` function is limited to one place, so we can easily change or remove it later on if needed.

**Comment by gaow** [comment]
I want to clarify for option 2:

1. It will only impact everything outside scripts (actions)?
2. the syntax for wild-card pattern `{_name}.{_ext}` will remain the same, right? 
3. what exactly would be the next recommended syntax, as there are still different flavors of interpolation? Do they handle filename conversions as conveniently? I see that's of great value that we should not compromise.

**Comment by BoPeng** [comment]
1. Yes. The `output: "${input!b}.html"` stuff will be gone. This would be the biggest change. 
2. Yes. The syntax for pattern will remain. The syntax for other particular use of string interpolation will probably also remain (e.g. the `args` parameter).
3. I do not know yet because for option 3, we will have to create a special class for paths and use the customized `__format__` option for similar effect, which accept `:`,  but not `!`, so we might have something like `${input:b}`.
4. I agree with you, so we might just say we have a special way (`script` format with string interpolation) to include scripts in a SoS script, and keep everything else untouched. That is basically my proposal.

**Comment by BoPeng** [comment]
We could make conversion easier by renaming `interpolate` to something like `_i` so that we can convert 

```
output: '${input!b}.html'
```
to
```
output: _i('${input!b}.html')
```

We could bump up sos format string but it would be a lot of hassle to keep backward compatibility in this big language change.

**Comment by gaow** [comment]
At the face value it looks like `_i()` is a step backward -- it's more complicated. I think it would be great of we can do this:

```
cwd = '~/Documents'
data = 'file.txt'
[1]
input: "${cwd:a}/${data}"
output: ...
R:
  read.table(${input!r})
```

Basically the only change on the user's end is to replace `!` outside scripts to `:`. It's more like a hybrid fo 2 & 3 of your proposal. Is it easy to do?

**Comment by gaow** [comment]
Personally I'm Ok with bumping version to 1.x and drop backward compatibility, if changes are minimal like that. Fixing existing scripts would be easy enough in that case.

**Comment by BoPeng** [comment]
Not easy because `cwd` need to be a special class to be able to use customized `__format__` rule. That is to say, we can treat `input` etc as perhaps `SoS_Path`, but have to explicitly convert `cwd` to `SoS_Path(cwd)` to take advantage of the `:a` format.

**Comment by BoPeng** [comment]
Or, we can keep `input` etc as string and use `f" "` string for script format.

```
python:
    with open("{input[0]}") as file:
          file.write('I am {os.path.basename(input[0])}')
```
is the same as
```
python(F'''
    with open("{input[0]}") as file:
          file.write('I am {os.path.basename(input[0])}')
''')
```

which is longer but perhaps acceptable because it at least does not require users to learn another set of string interpolation rules.

On top of that, if we really want to help users, perhaps we can keep `sigil` option, and allow

```
R: sigil='${ }'
```
so that users can include R scripts without doubling `{}`.

**Comment by BoPeng** [comment]
The bottom line is that having two string interpolation systems after 3.6 is widely used can be really confusing.

**Comment by gaow** [comment]
Sorry I do not understand. Can we just extend the `__format__` rule to work like that, for all `str`? 

Even if we do have to explicitly say `cwd` is a path, I still find it easier to have the similar file path conversion flavors that we have implemented before. As a python user myself, I'd rather learn another set of string interpolations rules (that we currently have) than having to type out `os.path.basename` etc. 

I'm not sure if it is very confusing because the only difference would ideally be `:` vs `!`, and we want to use `!` in scripts anyways because I think all scripts in SoS are equal -- we do not favor Python over other scripts. Then for Python users they'll understand our motive to have `:` vs `!`. For regular users, the difference inside / outside scripts should be acceptable to them.

**Comment by BoPeng** [comment]
I did not think the possibility of extending `str` itself...

**Comment by BoPeng** [comment]
Not allowed. This is where Ruby shines.
![image](https://user-images.githubusercontent.com/9889312/32337924-4a5f38ae-bfc1-11e7-9b0d-94068d225f77.png)

**Comment by gaow** [comment]
Okey ... then I'm kind of in favor of 

```
cwd = path('~/Documents')
output: '${cwd:a}'
```
and keep interpolation inside strings intact. I'm thinking more for people who never uses Python. Then our existing interpolation system would be way easier to understand and use for them, than having to learn at least part of Python.

**Comment by BoPeng** [comment]
If you are using the Python `__format__` style, the syntax should be

```
cmd = path('~/Documents')
output: f'{cwd:a}
```
Then this comes my third proposal, basically migrating our string interpolation system to Python 3.6 format string.

It would not be terribly difficult for users to understand this because `:a` would fail if the object is not `path`.

Problems with this would be
1. `"{dir}"` for pattern matching (no `f` before it), `f"{dir}"` for format string.
2. `{{ }}` for R scripts, which I really hate. We could use `R: sigil='${ }'` etc to alleviate this.
3. Variable types, which should be more or less ok if all `input` and `output` etc are `path`, and users can use `path('~/Documents')` in rare cases.

**Comment by BoPeng** [comment]
[performance of f-string](https://cito.github.io/blog/f-strings/)

**Comment by gaow** [comment]
I can see the advantage of migrating to Python 3.6 style: for complicated pattern and for performance. I'm just trying to figure out ways to make sure the syntax is not any more complicated for simple scenarios. 

I'd too hate `{{ }}` in R. But not sure I understand your `R : sigil = ${ }` proposal -- that, under the hood, will use the old-style interpolation, or are you going to translate it first to Python 3.6 (with `{{ }}`) then let Python handle it? If it is the 2nd case, then perhaps making `${ }` default sigil in parallel with Python 3.6 build-in interpolation convention would be a good idea -- if I understand the problem right.

**Comment by BoPeng** [comment]
For `R: sigil='${ }'`, the SoS parser would 

1. replace all `{ }` with `{{ }}`.
2. replace `${ }` with `{ }`
3. add `f` to the resulting string.

Basically,

```
R: sigil='${ }'
    if (TRUE) {
        read.csv('${input[0]}')
    }
```
would be parsed to
```
R(f'''
    if (TRUE) {{
        read.csv('{input[0]}')
    }}
```

**Comment by gaow** [comment]
I see, then I understand it correctly. It would be good if we can have sigil `${ }` by default. Then after enhancing Python 3.6 `__format__` to handle paths (and input / output will be path class by default), for old scripts we can completely replace `!` with `:` and make them work. Plus, we can now do much more, with/without using the `${ }` sigil, as long as it is legit Python 3.6 style.

**Comment by BoPeng** [comment]
OK, so the consensus is to

1. Bump version requirement to 3.6.
2. Remove our own string interpolation system.
3. Change script style to python format string, with option `sigil`.
4. Make `input` etc a special class to be able to use our old string conversion features.

I would suggest against using `sigil='${}'` as default because it can confuse people and it is not terribly difficult to add this option to existing script.

**Comment by gaow** [comment]
To add to your list:

5. We need to create a manual rule to specify path class, eg `genotype = path('file.vcf.gz')`
6. We migrate all our old path `!` conventions to enhance Python 3.6 syntax

> I would suggest against using sigil='${}' as default because it can confuse people

I'm not saying using it as default; I'm saying we can automatically allow for it, as long as it can exists in parallel with the native Python 3.6 syntax -- no need to even make a big deal of it so people will not get confused. But if additionally parsing for `${ }` has performance concerns I'm happy to not do it. 

> You know, I felt uncomfortable a year ago when I learned the new f-string syntax in python 3.6

Yes I do remember the conversation. Hopefully performance of SoS, after this change, will be greatly enhanced in parsing long scripts / statements.

**Comment by BoPeng** [comment]
It feels good that I can finally use f-string after bumping version requirement to 3.6... #800 can also be in the radar because of the version change.

**Comment by BoPeng** [comment]
OK, changes in the sos core is mostly done, at least all tests pass, so you can start testing the new syntax. Basically, you will need to 

1. Upgrade to Python 3.6
2. Use format string instead of SoS string, namely changing

```
output: "${input!b}.html"
```
to
```
output: f"{input:b}.html"
```
3. Use `{ }` instead of `${ }` in scripts, or use option `sigil='${ }'`.
4. Use `{}` instead of `${ }` in `.hosts.yml` files
4. Section option `sigil` is removed.

I tried to made the change as small as possible so the internal structure such as DAGs are untouched. There should be room for further performance improvement but that is not the priority now. Update on other sos modules should be relatively easy, but there is huge amount of work ahead to update all the documentations and examples, so the lesson is that we should have made the decision last year.

**Comment by gaow** [comment]
This is great! It looks like the changes are indeed minimal and I can always quickly patch my R codes with `sigil` option.

>  There should be room for further performance improvement 

Curious about what are these?

> Update on other sos modules should be relatively easy

So for now, the SoS workflow can be used without a problem, and I should expect broken codes for SoS notebook?

> but there is huge amount of work ahead to update all the documentations and examples

Particularly videos ...

**Comment by BoPeng** [comment]
For the performance part, SoS still parses statements and execute them one by one, which is no longer necessary. There are also some internal code that could be done better but my current focus is to make the tests work. I will work on them after I have revised all sos modules and documentations.

**Comment by gaow** [comment]
Still, can we make `run`, `bash`, `sh` and `R` actions, or any actions potentially having to use `{{ }}`, to accepting `${ }` by default in parallel with `{{ }}` -- is there a big overheard? I realized I have enough `awk` scripts that seems pretty annoying to add `sigil` to all of the related actions. Also, many of my `get_output()` that involves `awk` would not be usable, right?

**Comment by BoPeng** [comment]
It is possible to define default sigil for each different action, but I do not know if it is a good idea.

**Comment by BoPeng** [comment]
The problem is that sigil substitution happens at parsing time without knowing the actions, so the change can be difficult.

**Comment by BoPeng** [comment]
Also , having sigil listed explicitly helps readability.

**Comment by BoPeng** [comment]
[Documentation of SoS syntax](https://vatlab.github.io/sos-docs/doc/documentation/SoS_Syntax.html) is now updated. I see no reason to go back so I will merge the branch to trunk and close the ticket now. Do not update to trunk if you have jobs running.

**Comment by gaow** [comment]
Great! Not sure if I can try it tonight because I'm a bit behind schedule on writing up these analysis, but I'm really looking forward to migration. Do you notice obvious performance gain on some of your long scripts?

**Comment by BoPeng** [comment]
No, because my scripts always have longer jobs and sos' performance does not really matter compared to the time to execute the tasks. Only you have millions of small tasks, which should make a difference. Also, to me performance is only one of the considerations and making sos easier to learn, read and write is still more important.

**Comment by gaow** [comment]
I still have not tried, but is it going to mess up with the following Python codes:

```
# Dictionary init
MAF = {x:y for ...}

# Conventional string interpolation
string = '{0}'.format(x)
```

Basically, is it true that when there is `{ }` in any codes, the "default" sigil will have to become `{{ }}`? That'd be inconvenient if it is the case.

**Comment by BoPeng** [comment]
Yes, this sucks. So basically,

1. SoS Notebook will use `%get`, no interpolation.
2. SoS will use interpolation, not magic.

So if you are in SoS with its own kernel, you can write whatever code without worrying about interpolation. If you are going to use sos action, you have to use double braces or `sigil` option.

**Comment by BoPeng** [comment]
All sos packages are now updated and released (`0.9.10.x`) so it is safe to switch now, although more problems might be discovered when I go through and re-run the docs.

**Comment by gaow** [comment]
I see. This is why I though having default `sigil` for actions might be a good idea (because to me, `${}` is more readable than `{{ }}`), although I would not mind specifying it for all actions I previously have.

Also I just edited my comment above to be a bit more specific, and let me give an example here. I'm not sure `sigil = ${ } ` will  resolve the case when:

```
[1]
x = 'test'
python: sigil = '${ } '
  x = 'another_test'
  y  = 'f{x}'
  print(y)
```

would there be an issue? I realized the release has been updated. Since I still have not finished work at hand, I'll hold the update until later today. Just trying to envisage issues for now.

**Comment by BoPeng** [comment]
Yes, your example would work. Basically, setting `sigil='${ }'` disables `{ }` interpolation. You can even set `sigil=None` if you just want to include the script in verbatim.

**Comment by BoPeng** [comment]
Note that your sigil spec is wrong (ending space), so the complete code should be

```
%run
[1]
x = 'test'
python: sigil = '${ }'
  x = 'another_test'
  y  = 'f{x}'
  print(y)
```
with output
```
f{x}
```

**Comment by gaow** [comment]
> Basically, setting sigil='${ }' disables { } interpolation. 

I see. I was under the impression that the 2 types can co-exist. I guess I'll have to stick with adding `sigil` to all my codes and try to replace the pattern `${*!*}` with `${*:*}`, so that I can at least batch convert my old scripts to the new convention more easily. 

Also I made a typo: `f'{x}'` not `'f{x}'`. But i'd expect the output of `y` be `another_test`, and `z` be `test`, after you explained this.

**Comment by BoPeng** [comment]
Yes, `f'{x}'` would work as you expect.

There could be something like 

```
%set sigil='${ }'
```
but I would try to avoid such global settings because it makes it difficult to copy part of a sos script to another.

**Comment by gaow** [comment]
Okey, but I think a (random) mixture of `{ }` and `{{ }}` hurts readability because readers would not be technically motivated to see this "feature" welcoming.

**Comment by BoPeng** [comment]
I assume everyone would prefer `sigil` option to `{{ }}` because it is really tedious and error-prone to manually double the braces.

**Comment by BoPeng** [comment]
The sad part is that `{ }` is not a good choice for either Python or R, which was one of the biggest reasons I hesitated for so long to switch to f-string.

**Comment by gaow** [comment]
Then I'd imaging that many people would use `%set sigil='${ }'` almost like a "default". But it's a relatively straightforward parsing procedure for whatever sigil before falling back on f-string (compared to interpolating sigils). So the switch itself is by all means a big improvement. 

Also other than performance issues I do not see why we don't make `${}` default for actions. This is because we already have the `{ }` syntax, which, when used in `input/output` etc is actually pattern matching. It would be more confusing to mix `{ }` for pattern and for string interpolation in different context, than to have `${ }` vs `{ }` and `f'{ }'` in / out actions.

**Comment by BoPeng** [comment]
Pattern matching is only used in `provides` and related functions, and it is not that confusing between

```
provides='{filename}.html'
```
and
```
input=f'{filename}.csv'
```
because the former is a plain string literal, and the latter is a format string.

What I am trying to avoid is to  interpolate the same variables in different formats as follows:

```
output .= f'{input}.html'
python:
    open('${input}')
```
and I would prefer either

```
output .= f'{input}.html'
python:
    open('{input}')
```
or
```
output .= f'{input}.html'
python: sigil='${ }'
    open('${input}')
```

**Comment by gaow** [comment]
> Pattern matching is only used in provides and related functions ..

Wait, then we are not discussing the same thing. I have this in mind:
```
genotype = 'test.vcf'
name = 'sample_id'
input: pattern = '{name}.{ext}'
output: expand_pattern(f'{name}.{genotype:n}.{ext}')
python:
   print('{name}')
```

which should still work due to perhaps higher priority to parse `expand_pattern`. But it will be confusing in the action because it is not clear which `name` gets printed.

**Comment by BoPeng** [comment]
No, you usage of `expand_pattern` is wrong. You can use `f`-string to get a pattern, you should use something like

```
expand_pattern(f'{{name}}.{genotype:n}.{{ext}}')
```
to get something like
```
'{name}.whatever.{ext}'
```
to be fed to `expand_pattern`.

**Comment by BoPeng** [comment]
```
python: sigil = '${ }'
```
and
```
%set sigil = '${ }'
```
are different because the former is local and the latter is global and tend to more confusing.

Another option is to set default `sigil` to `None` so scripts are always included in verbatim unless we explicitly allow string interpolation. This tends to cause less error when users include scripts.

**Comment by BoPeng** [comment]
The logic here is to keep the "first" step easy so that users do not get any error message when they use sos for book keeping. They, for the more advanced step, e.g. with string interpolation, they can choose a sigil that works with the included script.

**Comment by gaow** [comment]
Sure, that I understand :) I was just being wishful thinking by saying "which should still work due to perhaps higher priority to parse `expand_pattern. `" -- because previously you said pattern syntax will not be impacted when I asked, yet I just realized we were talking about different details.

**Comment by BoPeng** [comment]
Also, the `sigil` option could be changed to something like `expand='{ }'` to make it easier to understand.

**Comment by gaow** [comment]
I think I first learned the word `sigil` with a kid's book or something ... so I take maybe even kids know this word? Or maybe `ph` for place holder -- `expand` is a bit long to type.

**Comment by BoPeng** [comment]
`sigil` in kids book should not be the `sigil` in CS, and I just confirmed with my boy and he saw it but does not know the exact meaning of this word. I would prefer `expand` over `ph` because of readability.

So you agree with setting `sigil=None` to default?

**Comment by gaow** [comment]
> So you agree with setting sigil=None to default?

Certainly. It is both conceptually and practically much more clear.

>  I would prefer expand over ph because of readability.

I've no objection to it.

**Comment by BoPeng** [comment]
`interpolate` is the right word but it is a bit long. `format` could be used but `expand` sounds a bit better... you can suggest some better word. Also, if `expand='{ }'` is a bit long to type, we can allow `expand=True`, although the default should still be `{ }`. Note that we cannot define `VAR='${ }'` and `expand=VAR` because translating to f-string must happen at parsing time when `VAR` is not interpreted.

**Comment by BoPeng** [comment]
According to [wiki](https://en.wikipedia.org/wiki/String_interpolation), the verb can be interpolate, substitute or expand, so we have another choice of `sub`, but `expand` still reads better.

**Comment by BoPeng** [comment]
ok, I am adding a huge amount of `expand=True` to the test, not sure if it is an improvement...

**Comment by gaow** [comment]
Unless a global sigil can be allowed -- which might still not help with the test, though, but might help with users who know what they are doing.

**Comment by BoPeng** [comment]
Everything has been updated.

I dislike global options... let us see how the f-strings work in practice and see if there is a need to change the syntax again. Anyway, as far as I can tell, this should be the last major change of SoS syntax and we can even think of a 1.0 release if everything works well.

**Comment by BoPeng** [comment]
A very intense weekend and Monday morning but I am glad that this is finally done. With all documentation and examples updated, we are now officially in the f-string age.
