### ISSUE TITLE
sos-notebook docker image asks for password

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#851]
I think @jma7 has resolved the problem for our live server but our docker image, as documented in the documentation, still asks for a password
```
docker run -d -p 8888:8888 -v $HOME:/home/jovyan/work  mdabioinfo/sos-notebook
```
we will need to document the password (how to get password, token etc), or change the Dockerfile to disable password.

**Comment by jma7** [comment]
It just need one additional step:
```
docker run --name SoS -d -p 8888:8888 -v $HOME:/home/jovyan/work  mdabioinfo/sos-notebook
```
Then, type 
```
docker logs SoS
```
in the command line.
Copy the url to the browser.

There is also an option to start the docker jupyter notebook without password, however it is not recommended. 
```
docker run --name SoS -d -p 8888:8888 -v $HOME:/home/jovyan/work  mdabioinfo/sos-notebook start-notebook.sh --NotebookApp.token=''
```

This is the link for reference:
https://github.com/jupyter/docker-stacks/tree/master/scipy-notebook

**Comment by BoPeng** [comment]
I have updated the [docker instructions](https://vatlab.github.io/sos-docs/#runningsos), thanks.
