### ISSUE TITLE
Easier way to convert str to sos_targets or file_target

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#853]
Before converting to f-string, SoS strings can be interpolated freely as paths. After the switch, we have to convert strings to file or directory names to use the `sos_targets` format rules. Right now we have to use `f"{sos_targets(name):u}"`, which is probably more troublesome than `f"{os.path.expanduser(name)}". 

We could use something like

```
[global]
st = sos_targets
ft = file_targets
```
to shorten the names but I am wondering if there are some better ideas.

**Comment by gaow** [comment]
How difficult is it to have something like 

```
ft = p'~/Documents'
```

or any simple conventions like it -- is it possible to capture and process them? `sos_targets` is indeed to long considering most input strings in SoS are paths!

In fact I'm wondering what's the side effect to treat all input strings as paths?

**Comment by BoPeng** [comment]
`file_target` is currently derived from `str` so it can be used when strings are needed, this makes it possible to widen the use of `file_target` in SoS scripts. HOWEVER, the deep rooted problem is still the inability to treat `str` automatically as path so things would fail on whatever `str` values that returned from Python.

Anything is possible but adding `p' '` would again require us to parse user expressions before sending to Python, which we have just avoided and should have boosted the performance of sos.

**Comment by BoPeng** [comment]
#852 is more or less easy to address, and then we might have to live with `sos_targets` and `file_target`, or its shorthands in one form or another.

**Comment by BoPeng** [comment]
How about renaming `file_target` to `path` and `sos_targets` to `paths`?

**Comment by gaow** [comment]
> How about renaming file_target to path and sos_targets to paths?

This is surely a lot better. 

> file_target is currently derived from str

and so is `sos_targets`? I was saying that we convert all input `str` to such targets ... but there might be unwanted side effects.

**Comment by BoPeng** [comment]
Then we need to have a close look at pathlib.Path.

**Comment by BoPeng** [comment]
Actually, when we did not have a dedicated `file_target` type, we were merely talking about convenient ways of formatting strings. If we expose such a type that handles filenames, we are in direct competition with `pathlib.Path`, and our design quickly shows its problems. For example, the exact reason why `Path` did not derive from `str` is that operations involves `str` and `Path` might return `str` and got stuck there, and this is exactly the problem we are having now.

So if we are to define `file_target`, we should better derive it from `BaseTarget` and `pathlib.Path`, instead of `BaseTarget` and `str`. The latter was chosen for convenience and backward compatibility, not for rigor.

**Comment by BoPeng** [comment]
The biggest advantage of deriving from ``path.suffix` and avoid using most of the ugly `os.path` stuff, and we can continue to use our `:` format for convenience. I understand that we are all so used to string-like path but perhaps this is a good chance for us to move away from `os.path` and get used to the `pathlib` way of handling path.

**Comment by gaow** [comment]
Sounds promising now that we are taking full advantage of Python libraries. But how does it impacts it syntax-wise? I hope it only makes it simpler, not more complicated.

**Comment by BoPeng** [comment]
There was a few cases when strings was solely needed to pass the tests so I derived `file_target` from string. I cannot recall the exact tests now. So what I can do is to stop deriving `file_target` from `str` and check the failed tests and see if we can address them with some acceptable `pathlib` syntax.

**Comment by BoPeng** [comment]
I am reading [this heated debate on whether or not path should be derived from str](https://www.reddit.com/r/Python/comments/4ck0v5/why_pathlibpath_doesnt_inherit_from_str_in_python/). My inclination is actually still on the `str` side (`path` / `path` yields `path`, `path`  + `str` yields `str`, which is very clean to me), but since `pathlib` has been adopted officially, I need to convince myself that  I am the one who lacks vision. :-)

**Comment by BoPeng** [comment]
We could keep the old syntax but the switch to `pathlib` would allow some new syntax, although the huge difference is that result of the old syntax would be string, and the new syntax could be `Path`.

| from | to | old syntax | new syntax|
|---|---|---|---|
| `path/file.tmp` | `file.tmp` | `f"{input:b}"` | `input[0].name` |
| `path/file.tmp` | `.tmp` | `f"{input:x}"` | `input[0].suffix` |
| `path/file.tmp` | `path/file` | `f"{input:n}"` | `input[0].stem` |
| `path/file.tmp`| `path/file.html`| `f"{input:n}.html" ` | `input[0].with_suffix('.html')`|
|`path/file.tmp`| `path/a.html`| `f"{input:d}/a.html"` | `input[0].with_name('a.html') `|
| join paths | | `f"{a}/{b}/{c}"` | `a / b / c `|
|  read content      | | | `input[0].read_text()` |
| write content | | | `input[0].write_text()` |

Note that we could "pass" unknown attribute to only element in `sos_targets` so `input[0].name` could be written as `input.name`.

**Comment by gaow** [comment]
> although the huge difference is that result of the old syntax would be string, and the new syntax could be Path.

Indeed, I'm trying to think of side effects (eg some codes that rely on `isinstance()`) and how that might impact users. But that'd be a corner case and users can always fall back to old syntax in that case. 

`input[0].name` is really awkward but without `[0]` is a lot better! How about `_input`?

**Comment by BoPeng** [comment]
`input[0].name` to `input.name` could be done by the pass-on mechanism, although this works only for `sos_target` with one element.

I think the difference is not that big. I mean, if you continue to use `string` everywhere, we can continue to use the format syntax, and the new syntax can be use occasionally for when it is convenience. One test that failed was when I try to add a `file_target` directly to string, that would not work any more but perhaps not a big deal.

**Comment by BoPeng** [comment]
Interesting `pathlib.Path` [does not like to be subclassed](https://bugs.python.org/issue24132)

**Comment by BoPeng** [comment]
Interesting, by overriding `__add__`, the new `file_target` allows `str = path + str` so all tests can pass without modification, yet we are getting a lot of magics from `pathlib.Path`. The type is sort of complicated and with lots of magics but we can comfort ourselves with the famous idiom "practicality is more important than purity*.

I will also make `path` and `paths` aliases to `file_target` and `sos_targets`...

**Comment by BoPeng** [comment]
OK, I separated `path` from `file_target` and `paths` from `sos_targets` to make them real classes because `path` can be directory and is different from `file_target`, and so on. Everything is documented [here](https://vatlab.github.io/sos-docs/doc/documentation/SoS_Syntax.html#SoS-Target-classes-13).
