### ISSUE TITLE
A blog for vatlab-related topics.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#856]
We can create a Jekyll static blog site and post logs over there. This would help us, for example, to show case examples, describe technical details for those are interested, and submit blog posts to hacker news etc.

There seems to be a [complete guide on how to do this](https://www.smashingmagazine.com/2014/08/build-blog-jekyll-github-pages/). The problem is that I am not at all a blogger so the blog might have very few posts.

**Comment by BoPeng** [comment]
And there is an interesting way to use issue tracker for comments: [here](http://hydroecology.net/using-github-to-host-blog-comments/)

**Comment by gaow** [comment]
I really prefer HUGO. Very easy to use and there are a lot of nice templates so you barely need to code. And it is markdown:

https://themes.gohugo.io/theme/hugo-kiera/
https://themes.gohugo.io

Here is a "vs" review : 

https://opensource.com/article/17/5/hugo-vs-jekyll

The conclusion, I quote:

>  If you already have a RubyGems environment set up and you need the extensibility of plugins, then Jekyll is the way to go. However, if you value a simple workflow and a straightforward means of customizing your site, then Hugo would be your top pick.

**Comment by gaow** [comment]
For comments, "disqus" plugin is avaiable for both systems I believe. Maybe also more blog-friendly than github issues as the interactions are more versatile

**Comment by BoPeng** [comment]
Well, we need to see how well `disqus` work with github.io. I personally prefer github issue tracker because this is where I am used to and I can use the tracker to remove and modify blog and comments easily.

**Comment by gaow** [comment]
> Well, we need to see how well disqus work with github.io.

`disqus` works for github.io just as it works for any other sites, because the database are stored in `disqus` website not github. 

>  I can use the tracker to remove and modify blog and comments easily.

This can be a big factor against disqus ... here is the hugo solution though (did not read very carefully):

http://donw.io/post/github-comments/

**Comment by BoPeng** [comment]
It has the same idea of using github issue tracker for comments, which I really like. I tend to use github tracker to write blog as well but that depends on if there is any existing template for it. Or we can use HUGO as blog engine and github tracker for comments. I believe that in that case we need to manually create a ticket for each blog post and link to the ticket from the post.

**Comment by gaow** [comment]
> I believe that in that case we need to manually create a ticket for each blog post and link to the ticket from the post.

I think it can be streamlined, via an api to automatically create it.  HUGO would be at least nicer looking than to create it entirely on github issues.

**Comment by BoPeng** [comment]
I do not mind creating a ticket for each blog post because I will not blog frequently anyway. Let me investigate how to set up a HUGO blog under vatlab (unless you know how to do it already). I think we can create a repo (perhaps called `blog`) under vatlab and use its trunk for HUGO and issue tracker for comments.

**Comment by gaow** [comment]
Yes I've setup HUGO website on github.io, but not issue tracker as comments. But believe me it is so straightforward that you'd perhaps rather want to do it yourself -- just fork a theme's repo, run `hugo` as is, then push to github.io! You can pick up a theme you like in general and fiddle with it.

**Comment by BoPeng** [comment]
I might go with a [KISS theme](https://themes.gohugo.io/theme/kiss/post/migrate-from-jekyll/) or [HUGO Premium](https://themes.gohugo.io/hugo-bootstrap-premium/) without side bar because they use similar fonts with SoS website.

**Comment by BoPeng** [comment]
https://vatlab.github.io/blog/ is up and running. Further discussion will happen in the blog repo.
