### ISSUE TITLE
Rename input to step_input?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#858]
It occurs to me that we should rename our `input` to `sos_input`, `output` to `sos_output`, and `depends` to `sos_depends`. `_input` etc can be kept unchanged.

The reason is simple, `input`, `output` are too common. `input` is a built-in function and `output` is a common name, so it is very likely they will be used by users, and cause surprises. At least for now,

```
input('a')
```
in a SoS kernel and `python3` kernel will behave differently,

This will be a big change and will force us to change many documentations and re-record multiple videos, not sure if there can be a walkaround for it.

**Comment by BoPeng** [comment]
A semi-walkaround and a way to simplify logic is to deprecate `input` etc and always advertise `_input`....

**Comment by gaow** [comment]
Is it possible to improve the parser so that `input:` is properly handled, and in different way as `input('a')`? `input` and `output` is much more readable than any other syntax.

**Comment by BoPeng** [comment]
It is not about parser, it is about the existence of the `input` variable in `sos_dict` which overwrites the system `input`. Basically, one cannot use `input` and `output` in SoS script, and in `SoS Notebook` because they are manipulated by SoS in the background.

`input` is indeed much more readable but in the end, `_input` should be used in the majority of the cases (same for `output` and `_output`) so renaming it can have added benefit of less confusion on the seemingly equivalence between `input` and `_input`.

**Comment by BoPeng** [comment]
BTW, I am not suggesting the use of

```
sos_input: 'a.txt'
```

This is still be
```
input: 'a.txt'
```

But the variables produced by the `input:` statement will be called `sos_input` and `_input`. 
sh: expand

**Comment by gaow** [comment]
I see. But will `{input}` become `{sos_input}` in scripts? That'd also be inconvenient.

**Comment by BoPeng** [comment]
Yes, but in the majority of such cases you only need to change `{input}` to `{_input}`.

**Comment by gaow** [comment]
Agreed about the "majority" claim, though I have had situation when the entire `{input}` and the particular iteration `{_input}` are both used. 

BTW, `snakemake` decides to use `input` as is: 

http://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#wildcards

**Comment by BoPeng** [comment]
Does snakemake have input group (`_input`)?

Our situation is completely different from snakemake in that SoS is derived from Python and users are free to write big trunks of Python code and SoS Notebook can behave just like a Python3 kernel, so having `input` and `output` in the way is a problem.

Another consideration is that we are aiming to be the "default" kernel for JupyterLab and even Jupyter so the SoS kernel should be as close to a regular Python3 kernel as possible. The better we "hide" the SoS part of SoS Notebook, the easier it could be adopted.

**Comment by BoPeng** [comment]
Of course `input` has its place so I am replacing but not removing it. I actually have made several mistakes when using something like

```
output: `{input:n}.bai`
```
which works ok for
```
input: 'a.txt'
```
but failed for
```
input: '*.txt', group_by=1
```
and the failure was not immediately clear to me because of the tiny difference between `input` and `_input`. Encouraging the use of `_input` and having a larger difference between `input` and `_input` should help avoid such problems.

**Comment by gaow** [comment]
My understanding is that for make-style there is no such concept as input group. `snakemake` also allows for putting in chunks of Python codes, at least in principle, though of course is already limited in many ways compared to SoS. 

But your latest post is more convincing. So something has to be done here. Currently the use of `_` is for input group. For example 

```
parameter: replicate = [1,2,3]
...
bash:
  echo ${_replicate}
  echo ${replicate}
```

distinction between those 2 commands is very clear. It feels like we will have fix a name conflict issue by abusing the `_` notation or change its concept. It is something to process at least for me ...

**Comment by BoPeng** [comment]
I do not think we are abusing the `_` notation because `_input` is the input of input groups, which is only  equivalent to `input` when there is only one group. I understand "normal" users might not use input group but then they might be confused with the two and use `input` everywhere until they run into the problem I showed. Enforcing the use of `_input` will help reduce such confusions and renaming `input` to `sos_input` happens to help the enforcement.

**Comment by gaow** [comment]
In that case, will we allow `_replicate` be `replicate` when there is only one input group? Will `_replicate` always be recommended over `replicate`? I said we "abuse" notation because to me at least in this case we are discriminating cases when `_` is used.

Also not sure if you want `sos_input` or `step_input`: I'm under the impression that we have things like `step_name` reserved. Maybe it is time to make such variable naming convention consistent?

**Comment by BoPeng** [comment]
Yes, `step_input` is a lot clearer than `sos_input`, let us use `step_input`.''

The case for `replicate` and `_replicate` is similar but because they are used intentionally with input groups (to to create input group), there is far less a chance to make mistakes like `input`.

**Comment by BoPeng** [comment]
Feels really guilty to introduce this kind of incompatible change. If we have some more man power, we should strive to keep backward compatibility.
