### ISSUE TITLE
`shared` does not work when the variable is used in section options

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#860]
I found this issue when modifying a workflow as discussed in #840. The MWE is:

```
[1: shared = ['myvar']]
myvar = 1

[2: skip = myvar]
print(myvar)
```
This workflow will produce error message:

```
ERROR: Failed to evaluate option skip with value myvar: name 'myvar' is not defined
```

My question is whether or not this is intended behavior, and how to implement what I want otherwise. Note that computation of `myvar` is none trivial in practice so I cannot make it a global parameter.

**Comment by BoPeng** [comment]
This is by design (at least as currently implemented) because parameter skip is handled at parsing time and does not accept variables.

**Comment by gaow** [comment]
Ok I understand. But does it mean the only way out is to make the heavy computations global and live with what I have complained in #840?

**Comment by BoPeng** [comment]
```
[1: shared = ['myvar']]
myvar = 1

[2]
stop_if(myvar)
print(myvar)
```
or
```
[def: shared = 'myvar']
myvar = 1

[2]
depends: sos_variable('myvar')
stop_if(myvar)
print(myvar)
```
works.

**Comment by gaow** [comment]
Okey, I noticed a potential issue after I solve the problem this way:

```
[init: shared = 'myvar']
myvar = glob.glob('*.*')

[default]
depends: sos_step('init')
print(myvar)
```

Note that in practice I had to use `sos_step('init')` not `sos_variable('myvar')` because there are many variables shared by this init step.

 It's all good the first time I run it. Then I deleted some files in the directory so `myvar` should be changed. However SoS does not know this. Therefore running it again: 

```
INFO: Executing init: 
INFO: input:   []
INFO: init (index=0) is ignored due to saved signature
INFO: output:   []
INFO: Executing default_0: 
INFO: input:   []
['1.txt', '2.sos', '2.txt', 'FMO2.ld.abs.png', '1.sos']
INFO: output:   []
INFO: Workflow default (ID=7742ec967072cc4b) is executed successfully.
```

it says `INFO: init (index=0) is ignored due to saved signature`, and loaded the saved `myvar` object instead, which is actually obsolete. Currently the only way out seems to use `depends: sos_variable('myvar')` instead of depending on the step. Is there a better way out?

**Comment by BoPeng** [comment]
The problem here is that the signature for step `init` consists of input, output, depends, and content of the step, and none of them have changed. Perhaps setting `depends: '*.*'` would help? At least in this way SoS would check if depends have changed.

**Comment by BoPeng** [comment]
Too complicated to allow arbitrary expression for `skip`, but the following error message

```
$ sos run test
ERROR: Failed to evaluate option skip with value myvar: Only constant values are allowed for section option skip
```
should help.
