### ISSUE TITLE
Dynamic input cannot properly handle underscore filenames

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#861]
Here is the MWE:
```
[1]
input: dynamic(['_1.txt', '_2.txt'])
print(_input)
```
and error message:

```
ERROR: Failed to regenerate or resolve _2.txt requested by .
```

I believe this is introduced due to the use of `libpath` because this workflow used to work for me. In my actual case the input were interpreted to `Undetermined('')` rather than `file_target()`, but I cannot reproduce that behavior with a MWE.

**Comment by BoPeng** [comment]
The MWE works for me if `_1.txt` and `_2.txt` exist. The error message appears if `_2.txt` does not exist so `dynamic('_2.txt')` cannot be resolved to a filename.

**Comment by gaow** [comment]
In fiddling with the example I found a related bug:

```
input: dynamic(paths(['_1.txt', '_2.txt', '1.txt']))
```

will result in:

```
ERROR: 'path' object has no attribute 'remove_sig'

```

**Comment by BoPeng** [comment]
Should be fixed.
