### ISSUE TITLE
Shorthand (or default) string interpolation for lists

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#862]
Now that SoS uses Python's f-string method, I find it a bit difficult to properly format variables the way it used to be. For example:

```
[1]
n = [x for x in range(2)]
input: [f'{x+1}.txt' for x in range(2)], group_by = 1, paired_with = 'n'
run: expand = '${ }'
  echo ${_n}
```

Will result in

```
[0]
[1]
````

So I will always have to use `${_n[0]}`. Also things like `${_n:,}`, `${_n:s}` do not work. And if I need the entire list I'll have to do `${' '.join(n)}`. All these are a bit difficult to use. Should we try to make variable string interpolation the way it was, because that'd be more intuitive?

**Comment by BoPeng** [comment]
Yes, this has been the biggest problem when converting to Python f-string. The more intuitive interpolation only happens to our types, namely `paths` and `sos_targets` and variables such as `_n` are left out.

We obviously cannot do anything to `n` but perhaps we can do something to SoS generated variables such as `_n`. We will need to introduce new types such as `sos_list` though.

**Comment by BoPeng** [comment]
Note that I have advertised the use of `paths(IDs)` to make list of strings easier to use in SoS.

**Comment by gaow** [comment]
> Note that I have advertised the use of paths(IDs)

Yes I do take advantage of that, but there I also have a complaint: `f'{targets}'` works flawlessly when `targets` is `paths` object, but `f'{_targets}'` is improperly formatted.

**Comment by gaow** [comment]
> We obviously cannot do anything to n but perhaps we can do something to SoS generated variables such as _n.

I agree we can leave `n` as is, but making `_n` an atomic element by default would be more intuitive.

**Comment by gaow** [comment]
Actually it would be a lot helpful (and maybe less confusing) if we add something like:

`{n:}` which translates to `' '.join(map(str,n))`. Also for `{n:,}` can we do `map(str,n)` before joining by comma?

**Comment by BoPeng** [comment]
That is not necessarily the case because `_n` is paired with `_input` and is a list matching each element in `_input`. The problem here is that `_input` can be used for `_input[0]` when there is only one `sos_target`  but `_n` cannot be used for `_n[0]` in the same case.

The technical problem here is that we know what to do for list of strings (`paths`) but `n` can be of arbitrary type and `_n` can be tricky to deal with in some case. For example, if `n` is a nested list, say,

```
n = [[1,2], [3,4]]
```
In the current implementation
```
_n = [[1,2]]
_n = [[1,2], [3,4]]
```
has known behavior, but if `_n` is
```
_n = sos_list ([[1,2]])
_n = sos_list([[1,2], [3,4]])
```
Then
```
_n[0]
```
can be
```
[1,2]
```
in the second case because `_n` has more than one element and `_n[0]` refers to the first element, and can be
```
1
```
in the first case because `_n` has only one element and `_n[0]` refers to the first element of the only element.

This was why I restricted the default to first element behavior only to `paths` (and then `sos_targets`).

**Comment by gaow** [comment]
Okey then I'm not sure if `sos_list` is needed. When we do need the non-atomic behavior, I assume users should know what they are doing and it is reasonable to ask them to work with indices. Otherwise as I proposed in the thread above, it would be helpful to device or improve the behavior of join so that we can always use that shorthand to convert a list into a string.

**Comment by BoPeng** [comment]
We are talking about two features here, one is the `:` format and the other is the fall-back to only element behavior. Both features need to be associated with a type to be used. In the most complicated case you can define type `A` for `:` format, type `B` for fall-back, and derive type `C` from both `A` and `B`, and `paths` and `sos_targets` from `C` so that you can cherry-pick feature to use.

**Comment by gaow** [comment]
I think the `:` format should be associated with any type, and we should decide the particular types that falls back to element-wise behavior. Currently it's just paths and targets which sounds reasonable to me. I'm not sure the complication added from introducing a new type `sos_list` is worth what it can do for us.

**Comment by BoPeng** [comment]
It is not possible to add our formatting style to any type because `__format__` is associated with each data type. We have to convert a native type to some sos type to redefine `__format__`.

**Comment by gaow** [comment]
Okey, then how about make `{n:}` or `{n:,}` behavior work for a list of strings or numbers? I'm talking about simple cases such as starting with a list of strings `some_files = ['a.txt', 'b.txt']` and do `run(f'rm -f {some_files}')` . Currently I have to `run(f'rm -f {paths(some_files)}')`. I imaging maybe `run(f'rm -f {some_files:}')` is better.

For more advanced types, maybe we want to first decide what would users need. The less alien types they need to worry about the better.

**Comment by BoPeng** [comment]
You will need to convert `some_files` to some sos type to be able to use sos formatting. It can be `paths` or some base class of `paths` but there is no way to do `{some_files:}` if `some_files` is a pure Python list.

**Comment by gaow** [comment]
I see. It seems introducing something like `sos_list` is required if we need such fall-back behavior.

**Comment by BoPeng** [comment]
`sos_list` is more awkward to type than `paths` but `paths` only works with strings. We can allow `paths` to take int (convert to string) so that `f'{paths(n)}'` can be used for  `f'{' '.join(map(int, n))}'` though.

**Comment by BoPeng** [comment]
Something like

```diff
diff --git a/src/sos/targets.py b/src/sos/targets.py
index 31b1bb9..5d58aa7 100644
--- a/src/sos/targets.py
+++ b/src/sos/targets.py
@@ -631,6 +631,8 @@ class paths(Sequence, os.PathLike):
         elif isinstance(arg, Iterable):
             for t in list(arg):
                 self.__append__(t)
+        elif arg is not None:
+            self.__paths.append(str(arg))

     def __getstate__(self):
         return self._paths
```
but I am not sure if this is the best way to go.

**Comment by gaow** [comment]
I think it is conceptually clear that those "customized" string interpolation behavior are for paths / file targets, and it can be considered a trick to convert other types into path/paths in order to take advantage of those customization. In that sense I'm cool with converting integer or list of numbers to path/paths.

**Comment by BoPeng** [comment]
Ok, we will then expand the trick to list of other types.

**Comment by BoPeng** [comment]
ok

```
>>> paths(1,2,3,[4,[5,6]])
[path('1'), path('2'), path('3'), path('4'), path('5'), path('6')]
```

**Comment by gaow** [comment]
I do not think this issue has been resolved:

```
[1]
parameter: K = paths(['a'])
input: '1.txt', paired_with='K'
run: expand = '${ }'
  echo ${_K}
```

will result in 

```
echo [path('a')]
```

If I replace `K = paths(['a'])` to just `K = ['a']` then the outcome is:

```
echo ['a']
``` 

**However, if I use `group_by = 'K'` instead of `paired_with = 'K'` then there will be no problem and I get `echo a`**.

**Comment by BoPeng** [comment]
This looks like intended behavior because `paired_with` pairs a list with files in a list `_input`. Because `_K` is a regular list instead of magic types such as `sos_targets`, you have to use `_K[0]`...

**Comment by gaow** [comment]
I understanding I'll have to use `_K[0]` as we've discussed in earlier threads. But I was under the impression that when `K` is converted to `paths` or `file_targets` I can get away without `[0]`. It seems my understanding is wrong. Anyways, using `[0]` is just a bit awkward though one can live with it.

**Comment by BoPeng** [comment]
The problem was that `K` can be of any type so it cannot be converted to `paths` or `file_targets`.

**Comment by gaow** [comment]
I think this is precisely what we are discussing here: we allow `paths` etc to have the power to convert any type to the old behavior (pre-f-string epoch) of an SoS variable. To cite what you've mentioned:

> We can allow paths to take int (convert to string) so that f'{paths(n)}' can be used for f'{' '.join(map(int, n))}' though.

In that case we can have a neat syntax for simple applications while allowing for more advanced uses (with any types, via `[i]`)

**Comment by BoPeng** [comment]
I meant explicit use of `paths` for conversion. Variables generated by `paired_with` are currently list of items of various types.

**Comment by gaow** [comment]
In my example above, I did try to use `paths()` for `K`. But I guess the fact that this happens prior to `paired_with` has made that operation effectively useless.

**Comment by BoPeng** [comment]
Yes, that is true.

There is one possibility though. That is to say, if `K` is sequence of `str`, `path`, `file_target`, we can make `_k` `paths` and `sos_targets` to avoid `[0]`. I was not comfortable of doing this because of the inconsistency (e.g. different usage of `_K` when `K` is list of `int` or `str`), but perhaps it is acceptable if we consider `paths` as SoS' native representation for`list` of `str`.

**Comment by BoPeng** [comment]
OK, the patch makes the type `_K` the same type of `K`, so `_K` will be a `paths` if `_K` is a `paths`. Your example should work now.

**Comment by gaow** [comment]
Great! havent got a chance to test it yet but will close it for now and reopen if necessary.
