### ISSUE TITLE
Improve `paths` function

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#863]
For example:

```
>>> paths(['a.txt', 'b.txt', 'c.txt'])
[path('a.txt'), path('b.txt'), path('c.txt')]
>>> paths('a.txt', ['b.txt', 'c.txt'])
[path('a.txt'), path('b.txt'), path('c.txt')]
```
both works but not 

```
>>> paths(['a.txt', ['b.txt', 'c.txt']])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.10.17-py3.6.egg/sos/targets.py", line 636, in __init__
    raise RuntimeError(f'Unrecognized targets {t} of type {t.__class__.__name__}')
RuntimeError: Unrecognized targets ['b.txt', 'c.txt'] of type list
```

I can flatten the list before throwing it in, but I think `paths` should be smart enough to do it automatically :)

**Comment by BoPeng** [comment]
Yeah, going arbitrary depth needs a bit of work but should be done...

**Comment by gaow** [comment]
Great!

BTW I'm going to update `jnbinder`. It would be helpful if we can make a `0.9.10.17` release on this github repo because `jnbinder` version check downloads from SoS repo release directly.
