### ISSUE TITLE
tmp folder permission deny

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#866]
This has not happened to me before but I'm just testing out #865  on the cluster today when this happens:

```
[MW] ./release.sos 
ERROR: [Errno 13] Permission denied: '/tmp/sos_config_'
```

Does this make sense?

**Comment by BoPeng** [comment]
This file is a inter-process lock that prevents multiple sos instances from access config files simultaneously. Access denied is strange possible if another user on the same system created this file, I guess.

**Comment by gaow** [comment]
I see ... I guess there are other SoS user on the same cluster that created this issue for me! I actually can see who that user is. Then we are all locked out of the cluster because of him :)

**Comment by BoPeng** [comment]
This should not happen ..., let me see what I can do.

**Comment by gaow** [comment]
Moving it to `~/.sos` seems most natural? I wonder if there are other related code that will fail due to the same nature

**Comment by BoPeng** [comment]
```
 fasteners.InterProcessLock(os.path.join(tempfile.gettempdir(), 'sos_config_')):
```
usually returns something like

```
/var/folders/ys/gnzk0qbx5wbdgm531v82xxljv5yqy8/T/sos_config_
```
not sure why it lands at `/tmp` on the cluster. I agree `~/.sos` makes more sense.

**Comment by gaow** [comment]
The downside is the potential to generate lots of junk and SoS will have to clean them up after use.

**Comment by BoPeng** [comment]
I will use fixed lock files for config files and check other lock files later.

**Comment by gaow** [comment]
Okey I think this issue alone is worth at least a `pip` release. But can we hold until later tonight? I want to test and ensure #865 is truly resolved.

**Comment by BoPeng** [comment]
Agree

**Comment by BoPeng** [comment]
How about #834?
