### ISSUE TITLE
Improved error info for step processes

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#867]
This is a complementary issue to #834 : I recently got user feedback complaining that debugging in step process is difficult, when writing python scripts directly into SoS steps. For example:

```
[global]
def bad_print():
    print(f'{[1,2,3](9)}')

[1]
print("hi from SoS")
bad_print()
```

The error message is:

```
ERROR: [default_1]: TypeError at line 2 of 
    print("hi from SoS")
>>> bad_print()
'list' object is not callable
```

The problem is that the user has no idea which line of `bad_print()` complains. `-v4` gives:

```
    exec(script, _dict)
  File "<string>", line 2, in <module>
  File "<string>", line 2, in bad_print
TypeError: 'list' object is not callable
```

In this MWE it is trivial to realize that indeed the 2nd line of `[global]` is problematic. But when `global` gets complicated and without any line numbers in SoS Notebook it is difficult to determine where the problem is. The `<string>` can be different from the physical text in SoS script. This MWE might not be very convincing but I hope I've conveyed the idea. I'll try come up with better examples if something more convincing is needed. The error that the user actually has run into was impossible to pin-point that he ended up copying the entire thing to a pure python notebook to debug.

**Comment by BoPeng** [comment]
Perhaps this is because of incorrect pointing of `>>>`? Also, why cannot the user execute the offending script line by line in SoS?

**Comment by BoPeng** [comment]
I see, this is from command line, not in sos notebook.

**Comment by BoPeng** [comment]
For

```
def bad_print():
    print(f'{[1,2,3](9)}')

print("hi from SoS")
bad_print()

```

The result of `python test.py` is

```
hi from SoS
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    bad_print()
  File "test.py", line 2, in bad_print
    print(f'{[1,2,3](9)}')
TypeError: 'list' object is not callable
```
so the problem is that SoS pointed to the wrong line.

**Comment by BoPeng** [comment]
The output of `sos run test.sos` for
 
```
[1]
def bad_print():
    print(f'{[1,2,3](9)}')

print("hi from SoS")
bad_print()
```
is
```
ERROR: [default_1]: TypeError at line 2 of
    def bad_print():
>>>     print(f'{[1,2,3](9)}')

    print("hi from SoS")
    bad_print()
'list' object is not callable
```

The problem was actually the separated execution of 

```
def bad_print():
    print(f'{[1,2,3](9)}')
```
and
```
print("hi from SoS")
bad_print()
```
so the error message can only point to `bad_print()`.

**Comment by BoPeng** [comment]
Tracing further back can be done in a Python 3 kernel, interesting

![image](https://user-images.githubusercontent.com/9889312/35196596-04dd1374-fe9a-11e7-8e8c-bc1bdb4e7d34.png)

**Comment by gaow** [comment]
> so the error message can only point to bad_print().

Yes this is precisely where the problem is. It doesnt trace it all the way back.

Also, not having line number in SoS Notebook is a bit inconvenient when trying to debug such. But that can wait.

**Comment by BoPeng** [comment]
Not as pretty as Python3 but close.

![image](https://user-images.githubusercontent.com/9889312/35197908-6e9bc37a-feac-11e7-9e99-9bec63120306.png)

**Comment by BoPeng** [comment]
Please let your user/friend know the improvement so that we are losing a user. :-)

**Comment by gaow** [comment]
I take you mean "we are NOT losing a user" -- this is great!

**Comment by BoPeng** [comment]
Yeah, every user is important, especially at this stage. We could format the error message better (with syntax highlighting stuff, not all in red) but this is good enough for now.

**Comment by gaow** [comment]
I tried it myself. I like the behavior. The red text might be slightly disturbing but good enough for now or even in the long run. The arrow has made the problematic line very easy to spot.

**Comment by BoPeng** [comment]
The ipython guy has a [dedicated module](https://github.com/ipython/ipython/blob/5b2b7dd07a268baceeeedfe919de0a59e5bc922b/IPython/core/ultratb.py) to format the message so it might be trivial to format the message as nice as the Python 3 kernel. But I agree that the current behavior is way better than before and is good enough for now.

**Comment by gaow** [comment]
Speakign of syntax highlights this is a minor issue with a trivial fix so I'll not open a separate ticket in the other repo for it. In SoS Notebook at least on my end I take that the `!` for `${_input!n}` is highlighted because of the string interpolation pattern. Currently we have `${_input:n}` but the `:` is no longer hightlighted. Should we make a highlight of this instead?

**Comment by BoPeng** [comment]
Python 3 current does not highlight expressions inside f-string so we are not doing that either. If you are talking about scripts in script style, they can be in any language so basic syntax highlighting should be enough.
