### ISSUE TITLE
`file_target` cannot be properly interpolated to string

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#868]
This is related to #862 

```
[1]
output: '1.txt'
python: expand = '${ }'
	print(${_output!r})
```
Error:
```
INFO: Executing default_1: 
INFO: input:   []
Traceback (most recent call last):
  File "/tmp/tmp6bkasykq.py", line 2, in <module>
    print([file_target('1.txt')])
NameError: name 'file_target' is not defined
```

**Comment by BoPeng** [comment]
This is because the `repr(_output)` is `file_target('1.txt')`, not `1.txt`, and the Python script does not understand this type. What you need is therefore `${_output:r}` because the `file_target` is formatted as string `1.txt` for the formatters.
