### ISSUE TITLE
Moving actions and targets from language modules to sos.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#882]
Right now, if we would like to execute sos workflow on a remote host, we will need to install `sos`, `sos-notebook`, and language modules for actions such as `python`. `sos-notebook` is needed because local sos could execute `sos preview -q` to get preview of remote files and the previewers are implemented in `sos-notebook`. Two recent releases have addressed this problem so that `sos-notebook` is no longer needed for remote preview.

However, `sos-notebook` is still needed because it is required by language modules, which provide not only the actions and targets (e.g. `bash`, `R_Library`), but also languages modules (e.g. support for `bash_kernel`). In theory, remote execution will need the actions and targets, but not language modules, but they are currently bundled together.

So the situation now is that we will have to install all sos modules on remote servers. It is not a big deal but incorrect installation (e.g. missing `sos-bash`) would disallow the execution of tasks on the remote host. My proposal is to move all actions and targets to the SoS module (sos workflow engine) so that installing `sos` will install all workflow related functions.

This solution is not clean in the sense that we will have to modify `sos` for the addition of actions for new languages, but I do not know a better way.

**Comment by gaow** [comment]
How about making a separate `sos-languages` module that consolidates all actions and targets?

BTW from the names of other software we might get some hints on packaging:

```
r-base
r-base-core
r-recommended
...
*-extra (latex)
*-essentials
*-meta
*-all
```

**Comment by BoPeng** [comment]
Would it be confusing to have both `sos-langauges` and `sos-r`, `sos-python` etc? In theory, if we move actions and targets out of `sos-r`, it should be renamed to `sos-notebook-r` (which I do not like).

**Comment by gaow** [comment]
> it should be renamed to sos-notebook-r (which I do not like).

I think it is not bad idea because it reads very clear. It also makes sense to add kernels to notebooks separately (vs `sos-r` etc users will be a bit confused why something called "script of scripts" wants to keep languages separate). I was also trying to come up with some more name suggestions, not `languages`; that was why I was trying to list some words that other packages used. But for our case they all seem to be overly generic.

**Comment by BoPeng** [comment]
We have released packages such as `sos-r` for a while and it can be confusing to rename the packages and leave `sos-r` etc on pip along with `sos-notebook`.

I think I will just move everything to `sos` so that `sos` is the self-contained sos workflow engine with all the actions and targets, and everything else belong to SoS Notebooks.

**Comment by gaow** [comment]
Great (and thanks for including my patch #515 )! I noticed `sos-r` repo is still unchanged. Are we going to also release updated `sos-*`? Should we now re-define what `sos-essentials` is?

**Comment by gaow** [comment]
Also are you sure you do not want to use all lower case letters in script file names?

**Comment by BoPeng** [comment]
What do you mean by 'script file name'?

**Comment by BoPeng** [comment]
`sos/actions_R.py`?

**Comment by gaow** [comment]
> sos/actions_R.py?

Yes! or `sos/actions_r.py`?

**Comment by BoPeng** [comment]
It does not bother me. Is there any guideline for this? PEP8?

**Comment by gaow** [comment]
> It does not bother me. Is there any guideline for this? PEP8?

Yes. I edited my last post.

**Comment by BoPeng** [comment]
ok.

**Comment by gaow** [comment]
The `master` is now broken, eg.:

```
[1]
depends: R_library('ashr@stephenslab/ashr')
R:
 print(99)
```

will not work.

**Comment by BoPeng** [comment]
`R_library` can be imported, the error message seems to be related to network problem

```
Downloading GitHub repo ashr@stephenslab/ashr@master
from URL https://api.github.com/repos/ashr@stephenslab/ashr/zipball/master
Installation failed: Not Found (404)

WARNING: R Library ashr is not available and cannot be installed.
ERROR: No step to generate target R_library("ashr@stephenslab/ashr") requested by default_1
```

**Comment by gaow** [comment]
Okey apparently your `R_library` was imported from an old version, possibly still from `sos_r`.  The problem is, I guess due to a4bd029, even this does not work for me:

```
[1]
R:
 print(99)
```

```
ERROR: [default_1]: 
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
script_6670084858033468369 in <module>
----> R(r"""print(99)
      """)

NameError: name 'R' is not defined

```

**Comment by BoPeng** [comment]
You will need to remove `dist` and `build` directories and re-install if you see `actions_R.py` in your site directory.

**Comment by BoPeng** [comment]
I see. On my mac, the changes are not pushed. 

```
[bpeng1@BCBMC07MX084DY3:~/sos (master +)]$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	renamed:    src/sos/actions_Bash.py -> src/sos/actions_bash.py
	renamed:    src/sos/actions_JavaScript.py -> src/sos/actions_javascript.py
	renamed:    src/sos/actions_Julia.py -> src/sos/actions_julia.py
	renamed:    src/sos/actions_MATLAB.py -> src/sos/actions_matlab.py
	renamed:    src/sos/actions_Python.py -> src/sos/actions_python.py
	renamed:    src/sos/actions_R.py -> src/sos/actions_r.py
	renamed:    src/sos/targets_Python.py -> src/sos/targets_python.py
	renamed:    src/sos/targets_R.py -> src/sos/targets_r.py
	renamed:    test/test_Bash_actions.py -> test/test_bash_actions.py
	renamed:    test/test_Julia_action.py -> test/test_julia_action.py
	renamed:    test/test_Matlab_action.py -> test/test_matlab_action.py
	renamed:    test/test_Octave_action.py -> test/test_octave_action.py
	renamed:    test/test_Python2_actions.py -> test/test_python2_actions.py
	renamed:    test/test_Python3_actions.py -> test/test_python3_actions.py
	renamed:    test/test_Python3_target.py -> test/test_python3_target.py
	renamed:    test/test_R_actions.py -> test/test_r_actions.py

[bpeng1@BCBMC07MX084DY3:~/sos (master +)]$ git push
Everything up-to-date
```

Are you on a linux box? Could you do it?

**Comment by BoPeng** [comment]
ok, try again...

**Comment by gaow** [comment]
Oh sorry I just saw this message. well, another mac shame :) but it works now!

**Comment by BoPeng** [comment]
Done. Hopefully this will be the last major shuffle of code.
