### ISSUE TITLE
Iterate over `file_target`

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#883]
I have updated [this example](https://github.com/vatlab/sos-docs/blob/master/src/examples/LP_Forward.sos) to keep up with recent syntax changes, and with [this line](https://github.com/vatlab/sos-docs/blob/master/src/examples/LP_Forward.sos#L15) I want to share all output. But judging from [this line](https://github.com/vatlab/sos-docs/blob/master/src/examples/LP_Forward.sos#L72) and also failure to execute the example, it seems the way I specify variable sharing is problematic. How can I share all output files from the first step under current syntax?

**Comment by BoPeng** [comment]
`shared = {'data_files': 'step_output'}`?

**Comment by gaow** [comment]
Yes ... I actually recalled this not long after I submit this ticket. After the update a new issue related to `paths` / `file_target` surfaces:

For this chunk:

```
input: dynamic("*.mse.csv")
import numpy as np
ridge_summary = np.mean(np.matrix([sum([x.strip().split() for x in open(f).readlines()], []) for f in _input if 'ridge' in f], dtype = float).T, axis = 1).tolist()
lasso_summary = np.mean(np.matrix([sum([x.strip().split() for x in open(f).readlines()], []) for f in _input if 'lasso' in f], dtype = float).T, axis = 1).tolist()
```

The error message is:

```
TypeError: argument of type 'file_target' is not iterable
```

So `for f in _input` is no longer valid statement. What should I use instead?

**Comment by BoPeng** [comment]
Your problem was with `'ridge' in f` because `f` is now `file_target`, not `str`.

**Comment by BoPeng** [comment]
We could redefine `__contains__` to enable `str in file_target`, but this can cause more confusion than convenience. Remember we have allowed `paths(['a.txt'])` to behave like `path('a.txt')`, so it is unclear what to expect for

```
'txt' in paths(['a.txt'])
```
because `txt` is not one of the paths (compare in whole) but is part of the first path (compare single item).
