### ISSUE TITLE
Executing input groups concurrently by default 

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#885]
Same logic for `concurrent=True` for tasks, it is even difficult to set up a case for `concurrent=False` for input groups, so it makes sense to set `concurrent=True` as default.

**Comment by gaow** [comment]
Wait, I think you've justified `concurrent =False ` by default by the user case that behavior on later input will depend on previous input. Is that a valid user case?

**Comment by BoPeng** [comment]
The example I gave in the doc is

```
sum = 0
input: for_each={'i': range(4)}
sum += i
print(f'sum is {sum} at index {_index}')
```

and the use of `concurrent=False` here is to pass `sum` to the next step, instead of having `sum=0` for each input group. I am not sure if this is a good user case but I can imagine that users might expect `concurrent=False` when they, for example, process some data line by line and expect the output in the same order.

This is indeed a weaker case compared to `task: concurrent=False`, and I just try to set a reasonable default that is safe, less surprise, and clean (e.g. do not have to write `concurrent=True` everywhere).

**Comment by gaow** [comment]
>  and I just try to set a reasonable default that is safe, less surprise, and clean 

In terms of "safe", maybe `concurrent = False`; in terms of cleaness then maybe `concurrent = True` because that'd perhaps be the most user case. I have a feeling you cannot have both :)

**Comment by BoPeng** [comment]
OK, then. Let us keep `concurrent=False` as default.
