### ISSUE TITLE
Revisiting global variable issues and ask for advice dealing with large amount of global data

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#889]
This ticket will revisit #840 and #860. In #840 I was complaining about global section got loaded multiple times; the solution is to make them `shared`. This led to #860 a situation where `shared` does not work, though there is a workaround and we closed that ticket. However for situations like this:

```
[global]
data = yaml.load(...)

[default]
depends: data['some_file']
```

the `shared` option will not work. So `data` has to be global variable. The problem is, what if `yaml.load` results in a constant but has huge amount of data and gets loaded at every actual workflow steps? This is a waste of resource, as already been a problem in my applications. I do not know a way to get around it ...

**Comment by BoPeng** [comment]
SoS executes steps in separate processes so there has to be some way to pass `data` from master to workers, and `pickle` is not necessarily faster than `yaml.load`.

**Comment by gaow** [comment]
I see. It looks like there is no truly "global" variable by design -- that each separate process will read data from disk, even if I put `data` in `sos_dict['CONFIG']` somehow?

**Comment by BoPeng** [comment]
`sos_dict` is pickled between processes, which are supposedly done via ram but could use disk (pipe etc) for large data. If you are concerned on performance, perhaps you can benchmark reading the same data from `pickle`, `marshal`, which can be faster than `yaml.load`.
