### ISSUE TITLE
`path_map` not displayed

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#890]
According to [this page](https://vatlab.github.io/sos-docs/doc/documentation/Remote_Execution.html#path_map-(derived)) I should see `paths_map` in `sos status -q`. But I do not see it.

```
$ sos status -q
Alias       Address                       Queue Type Description                  
-----       -------                       ---------- -----------                  
localhost   localhost                     process                                 
midway2     gaow@midway2.rcc.uchicago.edu pbs        UChicago RCC cluster Midway 2
stephenslab gaow@midway2.rcc.uchicago.edu pbs        UChicago RCC cluster Midway 2
```

I do have defined `paths` for all hosts:

```yaml
  midway2:
   paths:
      home: /home/gaow
  localhost:
    paths:
      home: /home/{user_name}
```

I am asking this, because my `task: to_host = [file1, dir1]` does not work. I'm try to to figure out why.

**Comment by BoPeng** [comment]
`-v3` is needed for

```
$ sos status -q  -v3
Queue:       bcb
Address:     bcbm-bpeng.mdanderson.edu
Queue Type:  process
Description:
Configuration:
  address:                 bcbm-bpeng.mdanderson.edu
  alias:                   bcb
  path_map:                ['/Users/bpeng1/ -> /Users/bpeng1/']

Queue:       laptop
Address:     localhost
Queue Type:  process
Description:
Configuration:
  address:                 localhost
  alias:                   laptop
  path_map:                []
  shared:                  ['/']
```

**Comment by gaow** [comment]
I see. Good to know this -- I added `-v3` to the doc notebook so that next time it will get compiled when u run updates. Should I push?

Then I'm wondering why my `to_host` has failed. My script looks like:

```
task: to_host = ["result_mash", "src/mash.conf.yml"], queue = 'localhost'
```

which is a folder and a file in my current workdir. And my command:

```
sos run test.sos -r midway2
```

Should they get `rsync`-ed? I do not think mine worked though the task was successful ...

**Comment by BoPeng** [comment]
Please push.

`localhost` would not `rsync` because the data are on the same file system. I think we have a ticket discussion what should sos do for syncing between hosts on the same host.

**Comment by BoPeng** [comment]
You cannot. `-r midway2` execute everything on `midway2`. If `midway2` has `hosts.yml`, it will have `midway2` as localhost and your desktop/laptop as one of the remote hosts, and file transfer should be done as `from_host`...

**Comment by gaow** [comment]
Okey I see that `sos run test.sos -q midway2` will work for sending my files over to `midway2`, if I remove `queue = 'localhost'`. However, I do want to run on `localhost` on `midway2` ... I guess a workaround is to define another queue on midway 2 that is a `process` type but has different name from `localhost`. Is there another way to do it?

**Comment by BoPeng** [comment]
Yes, I usually have a `cluster`/`pbs` queue and a `cluster-headnode`/`process` queue on cluster because I frequently need to send file to and prepare environments on headnode.

**Comment by gaow** [comment]
Okey I'm trying to do this. Basically you are saying I should have eg on local machine:

```
midway2-process:
   based_on: midway2
   queue_type: process
```

and on remote machine:
```
midway2-process:
   based_on: hosts.localhost
```

Is this your setup? I do think I have to put `midway2-process` in both local and remote machines.

Now with this setup I think I ran into a bug:

```
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.12.4-py3.6.egg/sos/hosts.py", line 856, in _get_host_agent
    raise RuntimeError(f'Failed to load task engine {self._task_engine_type}: {e}')
RuntimeError: Failed to load task engine process: No module named 'sos.sos_task'
```

**Comment by BoPeng** [comment]
`-r` option only uses address and port to send workflow over and execute and does not care about queue type so you can use `-r midway2` without problem. If you need to execute tasks on headnode of `midway2`, you will have to define `midway2-headnode` with a process type.

The definition of `midway2-process` depends on your `-q` option. You can use `-r midway2 -q localhost` to execute tasks on local host, which in this case is `midway2`.

The bug might be caused by outdated installation because I do not see `sos_task` from any of the source code.

**Comment by gaow** [comment]
Well, I was only trying to create a task that transfers files first, then run on `midway2-process`. So `-r midway2` is out of question. That's why, based on your ealier suggestions, I have to make that queue in both machines I think.

The bug is this line I think (and a fix):

```diff
 diff --git a/setup.py b/setup.py
index 1717d849..da8ed047 100644
--- a/setup.py
+++ b/setup.py
@@ -167,7 +167,7 @@ pandoc = sos.actions:pandoc
 docker_build = sos.docker.actions:docker_build

 [sos_taskengines]
-process = sos.sos_task:BackgroundProcess_TaskEngine
+process = sos.tasks:BackgroundProcess_TaskEngine
```

**Comment by BoPeng** [comment]
So we have tests for `pbs` but not for `process`? Strange.

**Comment by BoPeng** [comment]
I do not understand your comment on defining it on both hosts. If you are using `midway2-process` from localhost, you are sending tasks to `midway2-process` to be executed directly (not sending to PBS). The remote machine does not need to define anything.

**Comment by gaow** [comment]
Ahh I think I get what you meant -- apparently indeed there is no need to define anything on the remote machine if `-r` is not used!

**Comment by gaow** [comment]
Sorry please allow me to ask a question related to configuring a headnode as  `process` and a potential feature request that I might post after your confirmation. When I have something like:

```
midway-process:
  based_on: hosts.midway
  queue_type: process
```

Then I can no longer specify a `job_template`? If so, in this particular case with cluster headnodes, I'd like to have something like:

```
midway-process:
  based_on: hosts.midway
  queue_type: process
  job_template: |
      module load R/3.4.3
```

that first loads `R` to bash, as commonly done on clusters, then start some quick computations. I cannot write this to `.bashrc` because the software echo system is different from compute nodes and head node. Load as needed is the cleanest approach. Is this possible?

**Comment by BoPeng** [comment]
Right now the `process` task engine executes the command on the remote host directly. `job_template` can technically be supported although I did not see a use case for it (and you just gave one).

**Comment by gaow** [comment]
Great! If it is simple enough I'll not open a separate ticket for it? I'd like to discuss the keyword. Maybe `job_template` is not the best keyword for it? Because at least for backward compatibility:

```
midway-process:
  based_on: hosts.midway
  queue_type: process
```

will be broken because the old `job_template` for PBS will be derived and used. Should we use another name for it, such as something like `shell_profile`?

**Comment by BoPeng** [comment]
`job_template` is the right word for it because it is the template file submitted to `pbs` (for `pbs`) or `bash` (for `process`). If implemented, it should have something like

```
  job_template: |
      module load R/3.4.3
      sos execute {' '.join(tasks)} -v {verbosity} -s {sig_mode} {'--dryrun' if run_mode == 'dryrun' else ''}
```

**Comment by BoPeng** [comment]
The line would still be

```
      sos execute {task} -v {verbosity} -s {sig_mode} \
        {'--dryrun' if run_mode == 'dryrun' else ''}
```
but we have a problem here.

We now submit jobs in batches to task engine. Say if there are 4 `max_running_jobs` and 100 tasks, we will submit 25 tasks to each `process`. Current implementation does

```
sos execute task1 task2 ...
```
Now, with the `job_template` stuff, are we going to do

```
sos execute {' '.join(tasks)} ...
```
or multiple
```
sos execute {task}
```
The patch I just submitted uses the latter but stacks all jobs to a single file, something like
```
$ cat adaef96f81afbf48-5fc993c7cb44264f.sh
sos execute adaef96f81afbf48

sos execute 8641a250adbb84fd

sos execute e2e6870014f2ed04

sos execute 5fc993c7cb44264f
```
but this might not work if your `job_template` has something complicated.

**Comment by gaow** [comment]
What do you mean by multiple `sos execute {task}`? Ideally I want something like this to work because it is exactly the same as `PBS` queue:

```
      sos execute {task} -v {verbosity} -s {sig_mode}
```

Are you saying this is currently the case, and under the hood they got expanded and put into a single file? This sounds reasonable to me. 

I assume there is a "default" implicit template for `process` queue anyways -- previously we just cannot edit it. How does that look like?

**Comment by BoPeng** [comment]
The default one was something like 
```
sos execute {' '.join(tasks)} -v {verbosity} -s {sig_mode} \
        {'--dryrun' if run_mode == 'dryrun' else ''}
```
For process queue, I simply put multiple `.sh` files (each from `job_template`) into a single file to execute. For pbs queue, we cannot do that because job template contains PBS instructions, so in PBS the jobs are still submitted one by one.

**Comment by gaow** [comment]
I see. Then the current behavior is better!

**Comment by BoPeng** [comment]
The problem with stacking is that if you have something like

```
sos execute {task_id}
if not exist what ever, exit 1
```
Then subsequent jobs will not be executed if one job fails. 
```
sos execute task1 task2 ...
```
etc does not have this problem.

So it might be better to send `tasks` to `job_template` and let users decide what to do with multiple tasks.

**Comment by gaow** [comment]
Can we have both behavior? I'm mainly looking for compatiblilty with `PBS` `job_template`. That is, I hope to be able to use `base_on` to define a derived `process` queue without having to worry about `job_template` ...

**Comment by BoPeng** [comment]
Then let us keep this stacking behavior and add an option for multi-task template when needs arise.
