### ISSUE TITLE
Changes to `to_host` does not trigger rerun automatically

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#891]
It is not a big deal but is a bit annoying: I noticed that when changing `taks: to_host = []` adding other files I have to `-s force`, otherwise the added files will not be synced.

**Comment by BoPeng** [comment]
Is the signature at the task level or step level? I can imagine task level signature will be bypassed because it only records `input` and `output`. Step level signature should be invalidated with different statements, but perhaps sos skipped statements from the task.

**Comment by gaow** [comment]
I am sorry not sure if I get your question. I guess it is task level. Basically I change:

```
task: to_host = ['1.txt']
```
to 
```
task: to_host = ['2.txt']
```

nothing happens. It is not a big deal as I'm using this as a phony step anyways to copy data and I can always make it such that both script and options change. Or just use `-s`. It is just something I'd like to bring about in case it is considered a bug.

**Comment by gaow** [comment]
I made it work by setting `parameter: to_host = ...` then `task: to_host = to_host`
