### ISSUE TITLE
External tasks still trying to check `*.slot` file

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#892]
In running external tasks on remote computer I got this error message:

```
ERROR: [Errno 2] No such file or directory: '/home/gaow/.sos/manager_73dfd65f7cfc0d91.slot'
```

In fact when I manually check it, the file is there. So there must be some glitches (checked before generated?). But is it true that for external tasks `*.slot` file is still needed? My understanding is that it is only used for non-task engine, so why would external task runs check this file and report that error?

**Comment by BoPeng** [comment]
It should not. Let me check.

**Comment by gaow** [comment]
Oh I should add that my workflows are nested. Basically I have a bunch of `sos_run` that calls a few "core" steps with different parameters. Only those "core" steps are tasks based.

**Comment by BoPeng** [comment]
Do you see messages such as ` ... slot requrested ` with `-j3`?

**Comment by BoPeng** [comment]
I cannot figure out the reason from reading the code but I have tried to better lock the file...

**Comment by BoPeng** [comment]
Also, to check if the `slot` file is created by task, you can remove the `.slot` file, execute task with `sos execute task_id` and see. In theory, the `slot` files are only created during the execution of workflows or steps, not tasks.

**Comment by gaow** [comment]
I have tried to use `-v3`. I did not see that message. However, I do see `.slot` file generated. 

```
$ cat manager_73dfd65f7cfc0d91.slot
0
```
But as I said, I was running nested workflow. It can be reproduced by the example posted at #871, only changing the "core" to using `task` instead. Is that why I see `.slot` files?

**Comment by BoPeng** [comment]
I do not understand. The file should exist for the execution of workflow, but not tasks. If you remove the file and use `sos execute task_id`, the file should not be created. Note that `sos_run` cannot be used inside `task` due to restrictions of sos.

**Comment by gaow** [comment]
> If you remove the file and use sos execute task_id, the file should not be created.

I just tried it. Indeed no `slot` is created. 

> Note that sos_run cannot be used inside task due to restrictions of sos.

Yes I understand. I was just trying to rule out the possibility that `sos_run` outside task has created the `slot`. But your suggest test is a cleaner way to verify it. 

I guess I"ll close this ticket until I run into it next time ... hopefully your patch now protects slots better!
