### ISSUE TITLE
Control of max submitted jobs to host

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#898]
I got this error when submitting jobs with SoS to our cluster:

```
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)
```

I then checked: `showq` indicates I have submitted 482 jobs (!! most of them declined, of course) . But in my configuration file I did have:

```
    max_running_jobs: 30
```

also I have set `-J` to 30. Am I doing something wrong here? It is true that `-J` will override `max_running_jobs`, and SoS should at least recognize one of these settings?

**Comment by BoPeng** [comment]
Please update your submitting sos instance and check again. The problem was caused by the new batch submission method that was designed for faster execution on local host, but PBS does not stack jobs and submit them altogether. Therefore an option `batch_size` was introduced which is set to `1` for PBS.

**Comment by BoPeng** [comment]
Ok, I will test it more on my end and let you know.

**Comment by BoPeng** [comment]
Not the case here. I am using a task spooler with script

```
[10]
input: for_each={'i': range(100)}
task:
sh: expand=True
  echo {i}
  sleep 100

```
Command

```
$ sos run test -c ~/docker.yml  -q ts -J 10
```
shows that there are always 10 running jobs
```
$ sos status -c ~/docker.yml -q ts  -s running
859af4841863cade	0b867c3c3e496af1 default_10	   1 min 34 sec	running
62eeb2fc9fdf659a	0b867c3c3e496af1 default_10	   1 min 33 sec	running
30ca39d5c884f755	0b867c3c3e496af1 default_10	   1 min 33 sec	running
9b3d4b39b9919b9a	0b867c3c3e496af1 default_10	         33 sec	running
902daf1d12dbc73e	0b867c3c3e496af1 default_10	         30 sec	running
bcdecd6c35093b7b	0b867c3c3e496af1 default_10	         28 sec	running
939cb4c376d2e243	0b867c3c3e496af1 default_10	         28 sec	running
280bdae91652bb8b	0b867c3c3e496af1 default_10	          3 sec	running
abaf2f4c76a3ee3e	0b867c3c3e496af1 default_10	          1 sec	running
```

**Comment by BoPeng** [comment]
`-v4` will show a bunch of messages like
```
DEBUG: submit f66ce86db5d7e988: tsp -L f66ce86db5d7e988 sh ~/.sos/tasks/f66ce86db5d7e988.sh
```
and you should not see jobs submitted all at once to remote host.

**Comment by gaow** [comment]
I was in fact using `-r host`; also a more complex workflow. My account is currently fully queued. I'll try this simple one once it is freed up, then try to make a MWE of my case, if it is still problematic.

**Comment by BoPeng** [comment]
`-r` means submitting from remote host, then that instance of sos should be updated. I guess you already know it hough.

**Comment by gaow** [comment]
I am sorry, it must have been a glitch on my end -- at some point I used `pip install --upgrade --user` switch that installed a copy from `pip` to `~/.local` on my cluster. Then for non-pip versions that got updated and  installed into my `conda` they were overridden by what's found in `~/.local`. I think it now works as intended. Sorry for having to have you tested it ...
