### ISSUE TITLE
Use zeroMQ for multiprocessing

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#899]
The SoS executor is very complex now with a lot of message passing via pipes. Pipe objects are passed around so a process might have a pipe for its parent and a pipe for its worker, and so on. Whereas this has been working all right after hours of debugging, the code is messy.

It appears that zeroMQ has been used in such scenarios so if we are adding anything major to the executor, perhaps we can use zeroMQ for message passing, at least [has better performance than pipe](https://taotetek.net/2011/02/03/python-multiprocessing-zeromq-vs-queue/). Also, having a process dedicated to signature etc might also be a good idea. That it so say, we collect all signatures in a single file or database, start a process to read it all, and perform signature validation etc on request.

**Comment by gaow** [comment]
This sounds like a huge step forward! 

>  That it so say, we collect all signatures in a single file or database

Does it mean there will be something like a `redis` server that `zeroMQ` sends data to? If so, it might be non-trivial to set it up on, say, a remote computer -- for example my institute specifically bans running public redis server (the default setup). Just curious what type of database is there that you are considering ..

**Comment by BoPeng** [comment]
We have visited this topic a few times and the center problem is how to maintain the server (redis or not). I would rule out the possibility for requiring users to start a server manually, so we have either 

1. A single server solution: sos query a server, connect to an existing one or starts one if no server is available. The server is shared by multiple sos instances so it should not be killed with the death of an sos instance, but it should kill itself if no one talks to it for a while.

2. A multi-server solution: each sos instance starts a server with a different port. The problem with this approach is that multiple-servers need to talk if the server is supposed to keep track of signatures, task status etc. This can be difficult to do as each server could cache information to itself, otherwise sharing a database has its own problems (servers lock database to write etc).

The server does not have to be a redis server, because we do not have to use redis database to store the information. For example, we can use a simple dictionary to keep track of worker status and use the server to coordinate the execution of workers. We could migrate things like file signature to the server but there are practical problems. For example,

1. We might not want to start a server for task execution because tasks could be sent to different computing nodes so file system is the only way to read/write signatures. 
2. We might not be able to use the server for file locking as well because file lock is released when the process is killed but this is difficult to mimic in a server implementation.

I think what I will do is start a zeroMQ branch and implement a on-demand server process. We can then use the server to do more and more things.

**Comment by gaow** [comment]
It would be great to see / test a prototype of this. I still have difficulty wrapping my head around the idea of running no rq-like servers yet have all signatures in the same place. Anyways, I do want to check if `zeroMQ` has the potential to resolve #871 completely? Now very occasionally I still run into #871 and had to manually kill them all (though MUCH better than before!).

**Comment by BoPeng** [comment]
This is unrelated to #871 but having better process process might eventually solves #871. Because our priority right now is not internal optimization, I will leave this ticket for later, even after our 1.0 release.
