### ISSUE TITLE
Can't seem to get magic %get to work with Julia

### ISSUE THREAD

**Issue by YannCNovelli** [vatlab/SoS#904]
I have tried to uninstall and reinstall Julia, IJulia and Feather but I still get this message:

`Magic %get failed because the language module for julia-0.6 is not properly installed. Please install it according to language specific instructions on the Running SoS section of the SoS homepage and restart Jupyter server.`

How can I determine exactly what is wrong with the installation?

**Comment by BoPeng** [comment]
To check what is going on,

1. Check if you are using python 3.6
```
$ python --version
Python 3.6.2 :: Anaconda custom (64-bit)
```

2. Check if julia is in the output of `jupyter kernelspec list`

```
$ jupyter kernelspec list
Available kernels:
  ruby         /Users/bpeng1/.ipython/kernels/ruby
  bash         /Users/bpeng1/Library/Jupyter/kernels/bash
  ir           /Users/bpeng1/Library/Jupyter/kernels/ir
  julia-0.6    /Users/bpeng1/Library/Jupyter/kernels/julia-0.6
```

3. Check if you can use julia-0.6 kernel separately (`New` -> `Julia 0.6.1`).

4. Check if sos julia language module is installed

```
pip install sos-julia
```
The following command should not produce any error
```
python -c 'import sos_julia.kernel'
```

5. Create a SoS notebook, check if `Julia` (capital `J`) is listed as one of the languages. If you see `julia 0.6.1`, then the language module is not working.

6. Then you should be able to use `%use Julia` or select `Julia` from language dropdown box.

**Comment by YannCNovelli** [comment]
1, 2, and 3 all checked with the expected output.
4 resulted in the installation of sos-julia which was apparently missing. Subsequently importing the sos_julia kernel did not produce any error.
5 and 6 worked afterwards.
Strangely though, I got this warning in the Terminal window: `WARNING: Failed to locate subkernel julia-0.6 with kernerl "julia-0.6" and language "": Cannot change kernel or language of predefined subkernel julia-0.6`
Still, it's working now and I really appreciate your help. Thank you.

**Comment by BoPeng** [comment]
OK, so the problem was the missing `sos-julia` module. The warning message was caused by opening a notebook that used kernel `julia-0.6` without proper language definition (`sos-julia`) and could be safely ignored.
