### ISSUE TITLE
Use of `f-string` wildcard conflicts with Python's build-in function

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#905]
To reproduce it, under `sos-docs/src/examples`

```
$ ./LP_Mixed_ST.sos 
```

The interpolated R code from `set.seed(${id})`is:

```
set.seed(<built-in function id>)
```

It needs the current `master` for `sos-docs` repo, although updating it will make https://github.com/vatlab/sos-docs/issues/23 no longer reproducible ...

**Comment by BoPeng** [comment]
This example looks wrong to me because

```
[ridge_2, lasso_2 (evaluate)]
depends: sos_step('simulation')
``` 
triggers
```
[simulation: provides = ["data_{id}.train.csv", "data_{id}.test.csv"]]
# Simulate sparse data-sets
depends: R_library("MASS")
parameter: N = (40, 200) # training and testing samples
parameter: rstd = 3
output: f"data_{id}.train.csv", f"data_{id}.test.csv"
```
but `id` was not patten-matched or defined (so the `id()` Python function is used).

**Comment by BoPeng** [comment]
The problem here is that `sos` allows auxiliary steps to be called in this way (define `output`) and `f"data_{id}.test.csv"` happens to be valid without patten matching.

**Comment by gaow** [comment]
I think it is pattern matched at [this line](https://github.com/vatlab/sos-docs/blob/master/src/examples/LP_Mixed_ST.sos#L41). Also [this script](https://github.com/vatlab/sos-docs/blob/master/src/examples/LP_Mixed.sos) actually worked ... note that it also uses `id` as wildcard key.

**Comment by BoPeng** [comment]
But the `simulation` step is executed because of the `sos_step` stuff before the `input` line.

**Comment by gaow** [comment]
Ahh I see, this is when using `sos_step` as dependent variable, as opposed to using actual files ... this in fact was a new example I added. Would it be possible you could fix this example, after possibly using it as a test to the keyword conflict case, so that we have a good example for mixed style with step dependencies?

**Comment by BoPeng** [comment]
At least `depends: sos_step()` cannot depend on an auxiliary step that requires file matching. You could create an example that depends on a step that download a resource file (and you do not have to specify the actual file downloaded).

**Comment by gaow** [comment]
I see. I would perhaps make the provided files explicit for `simulate` in that example, rather than having to pattern-match. Or just remove that example, because if I make explict file provides then it defeats the purpose to make comparisons with `LP_Mixed.sos` and can be confusing to explain. This is a newly added example anyways. We had not expanded on it in any occasion yet.
