### ISSUE TITLE
Build missing targets with build sig mode.

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#906]
Or, I should say, for [this](#871) particular workflow. The example file is again attached here.

[hang_test.sos.txt](https://github.com/vatlab/SoS/files/1756754/hang_test.sos.txt)

To reproduce, first

```
sos run hang_test.sos
```

then

```
rm -f t_1.rds
sos run hang_test.sos -s build
```

It will complain about `output target t_1.rds does not exist ...`

**Comment by BoPeng** [comment]
`-s build` is used to create signatures from existing files so there is nothing wrong for it to complain that `t_1.rds` does not exist.

**Comment by gaow** [comment]
The problem is, that `-s build` will fail, rather than complain, for non-existing files. So for the user case when a workflow is partly completed and signatures are somehow lost (e.g. moved to a new path or new computer), I'd imaging this be useful:

```
sos run ... -s build
sos run ...
```

if `-s build` does not fail. Is it a reasonable scenario?

**Comment by gaow** [comment]
Sorry I should have made clear that example in my first post that it actually "failed" with error, not a warning ...

**Comment by BoPeng** [comment]
The `default` mode will use the signature if it exists, and build the signature if it does not, right? The difference is that the `build` mode will overwrite existing signatures while `default` mode will not.

At least in the original design, `build` is used to build signatures from files, not to create files.

**Comment by gaow** [comment]
> The difference is that the build mode will overwrite existing signatures while default mode will not.

I think you are talking about `force` vs `default`. 

The problem here is that missing files actually will trigger error messages with `-s build`. if I remove one file after running the workflow, as the example given in my first post, and do 

```
sos run ... -s default
```

it works -- the missing file triggers rerun and no error message. But 

```
sos run ... -s build
```

will **fail** with error message: `Output target t_1.rds does not exist after the completion of step ...`. I guess we can leave this ticket open when you get a chance to try that example and decide if the behavior is proper.

**Comment by BoPeng** [comment]
I tried that example and sos works as expected to produce an error for **failed to build signature because of missing file**, although the error message is unclear about the exact reason for the failure.

When we compare the modes

| mode | file | signature  | action |
|--|--|--|-|
|default| no file | no sig | run to generate file and signature|
| | no file | with sig | pass |
| | with file | with matching sig | pass|
| | with file | with mismatch sig |  rerun | 
| build | with file | either | build sig |
| | without file | either | error |
| force | either .| either | rerun to generate file and signature |
| ignore | either | either | rerun without saving signature |

**Comment by gaow** [comment]
Okey, I guess this brings to the user case when I have part of my results files, and I do not have any signature (lost my `.sos` folder one reason or the other). I want to recover my work while trusting the part of files I have already generated. In  GNU Make there is a `--touch` option that does something like rebuilding signature. Actually in most cases I fill `-s build` is the same as `--touch`, and it can cope with missing files. Just somehow in that example with `sos_step` depend it does not work as expected.

**Comment by BoPeng** [comment]
`--touch` marks existing files as up to date, which is similar to ours, but I doubt `touch` would execute the workflow to create files.

**Comment by gaow** [comment]
> but I doubt touch would execute the workflow to create files.

I agree. I was merely saying that the scenario and the command I proposed in [this thread](https://github.com/vatlab/SoS/issues/906#issuecomment-368394921) is reasonable behavior. When it throws errors, it actually did not accomplish what we'd expect, that it rebuilds signatures to the best it could.

**Comment by gaow** [comment]
Sorry I was just reading your table above again. You said:

```
default: no file, with sig -> pass
```

but shouldn't it be 

```
default: zapped file, with sig -> pass
default: no file, with sig -> rerun
```

? Because i rely on just `rm -rf` existing files / folders to trigger rerun ... 

and also to be clear, the proposal now for `build` is:

```
build: no file, either with/without sig -> rerun
```
that is, build will not fail. I would say if that's the behavior then it can be used to recover a tarball project that not only misses all the signature but also miss some if its files. #850

**Comment by BoPeng** [comment]
The original behavior of no file + full sig is pass.... let me check.

**Comment by BoPeng** [comment]
You are right, either the target or zapped file must exist.

**Comment by gaow** [comment]
> You are right, either the target or zapped file must exist.

Yes this is what we believed more intuitive (more consistent to Make behavior)

**Comment by BoPeng** [comment]
Please test again.

**Comment by gaow** [comment]
Great! It seems the patch works. Are we sure there are no side effect to set `skip_index` to `False` -- I mean you set it to `True` previously for a reason, right?

**Comment by BoPeng** [comment]
I cannot recall the reason and will see if this change bites me later.

**Comment by gaow** [comment]
Okey ... well, then i'll close the ticket until there is a problem.
