### ISSUE TITLE
Examples on live server

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#913]
We should put 

1. examples on the home page (three gif figures)
2. examples for the SoS manuscript 
3. examples for the videos 

on live server.

**Comment by BoPeng** [comment]
OK, I have added all examples for homepage and videos, @gaow only need to add the examples from manuscript.

**Comment by BoPeng** [comment]
Note that sf.net is down again so docker build might fail at the `octave --eval` step. If that is the case, comment out [this line](https://github.com/vatlab/SoS/blob/master/development/docker-notebook/Dockerfile#L39) for now.

**Comment by gaow** [comment]
Great! I've converted & uploaded  examples and modified docker file. [Here](https://github.com/vatlab/SoS/commit/12d72eb2c3fb320f7c04395424409e7f5696c194) are the changes. sf.net seems to be online now. The Docker file is being built -- fingers crossed!

**Comment by gaow** [comment]
@BoPeng I got access denied to that docker repo ... would you try on your end?

**Comment by BoPeng** [comment]
I had to disable octave forge and change the COPY command because the linux docker might be too old. It is working but you should perhaps rename the files to `WP2018_xxxx` to group files together. You should also test if the workflows are reproducible on the server.

**Comment by BoPeng** [comment]
WIth my changes, you should be able to just push the change, go to the live server and run update.sh.
