### ISSUE TITLE
if condition for actions.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#914]
We will have to use non-script format of actions if the actions are executed conditionally, something like:

```
if condition:
    sh(script)
```

I am wondering if we can provide something like

```
sh: skip=not condition
   script
```
so that we can use script format of actions even under conditions.

**Comment by gaow** [comment]
But we have `active` already. Is there a way to merge / enhance these options?

**Comment by BoPeng** [comment]
Good point. Active accepts internet, slice etc, and we can let it accept Boolean.

**Comment by BoPeng** [comment]
Done, my SoS script will look a bit better with this feature.
