### ISSUE TITLE
Automatic expanduser for path

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#915]
Our `path` type is derived from `pathlib.Path` with additional format operators, and like `Path`, we will have to use `expanduser()` to expand `~`:

```
>>> path(os.path.expanduser('~/.bashrc')).exists()
True
>>> path('~/.bashrc').exists()
False
>>> path('~/.bashrc').expanduser().exists()
True
```

Since `path` is a SoS type and SoS automatically expand `~`, I believe we should treat

```
path('~/.bashrc').exists()
```
as
```
path('~/.bashrc').expanduser().exists()
```
The problem is that we will have to redefine many functions such as `exists`, `is_dir`, `is_file`, ..., and it does not look right if we automatically change the string representation of input path

```
>>> str(path('~/.bashrc').expanduser())
'/Users/bpeng1/.bashrc'
>>> str(path('~/.bashrc'))
'~/.bashrc'
```

**Comment by BoPeng** [comment]
```
>>> file_target('~/.bashrc').exists()
True
>>> path('~/.bashrc').exists()
True
>>> paths('~/.bashrc').exists()
True
```

However, this makes the `paths()` tricky no longer safe to use in case the passed string starts with `~`,

**Comment by ericchansen** [comment]
How does this work now? Is there a way to automatically do this?
=

**Comment by ericchansen** [comment]
I'm sorry, I should be in the pathlib GitHub. Thanks @BoPeng.
