### ISSUE TITLE
Test for R_library fails

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#917]
```
=====================================
ERROR: testDependsRLibrary (__main__.TestTarget)
Testing depending on R_library
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_r_targets.py", line 70, in testDependsRLibrary
    Base_Executor(wf).run()
  File "/Users/bpeng1/anaconda3/lib/python3.6/site-packages/sos-0.9.12.10-py3.6.egg/sos/workflow_executor.py", line 836, in run
    dag = self.initialize_dag(targets=targets)
  File "/Users/bpeng1/anaconda3/lib/python3.6/site-packages/sos-0.9.12.10-py3.6.egg/sos/workflow_executor.py", line 764, in initialize_dag
    if self.resolve_dangling_targets(dag, targets) == 0:
  File "/Users/bpeng1/anaconda3/lib/python3.6/site-packages/sos-0.9.12.10-py3.6.egg/sos/workflow_executor.py", line 559, in resolve_dangling_targets
    f'No step to generate target {target}{dag.steps_depending_on(target, self.workflow)}')
RuntimeError: No step to generate target R_library("xtable") requested by default_0
```

Since `R_library` is available,

```
$ python -c 'from sos.runtime import R_library'
```

I suspect that testing for existence of library fails due to https://github.com/vatlab/SoS/commit/7e4484d8b8de91e5aa9fd6afc43a1a000e3e29e3

**Comment by gaow** [comment]
Hmm it works on my computer, though, when I just run `python test_r_targets.py`. The patch you mentioned only attempts to reinstall when there is version mis-match ... does it work if you only execute this script?

**Comment by BoPeng** [comment]
The test is about installing package `xtable`. Perhaps you have it already installed?

**Comment by BoPeng** [comment]
No, it first attempts to remove `xtable` with command `R CMD REMOVE xtable`.

**Comment by BoPeng** [comment]
OK, [this line](https://github.com/vatlab/SoS/blob/master/src/sos/targets_r.py#L78) would fail if the package does not exist and might have prevented the installation of missing packages.

**Comment by gaow** [comment]
Right ... would need a tryCatch. I wonder why it did not report error on my end.

**Comment by gaow** [comment]
Tried to fix -- does it work now?

**Comment by BoPeng** [comment]
```
UnboundLocalError: local variable 'package_loaded' referenced before assignment
```

**Comment by gaow** [comment]
Oh boy, I needed another `rm -rf ../site-packages/..`. How about now?

**Comment by BoPeng** [comment]
```
Error: unexpected symbol in "            if suppressMessages"
```

**Comment by BoPeng** [comment]
Works now.

**Comment by gaow** [comment]
Finally, purged all my SoS installation and properly tested -- I was first able to reproduce the error then fixed it. Isn't it annoying that one has to `rm -rf` from time to time? I think we've mentioned this in passing before, but not sure what we can do.

**Comment by gaow** [comment]
I suspect this is due to mixed use of `python setup.py install` and `pip install` and the fact that one does not overwrite the other and there is a load preference. But in most cases there is no issue until it bites.

**Comment by BoPeng** [comment]
Yes, something like [what this post mentioned](https://stackoverflow.com/questions/27964960/pip-why-sometimes-installed-as-egg-sometimes-installed-as-files)

**Comment by gaow** [comment]
Hmm are you going to adopt their advice?  eg this might solve the problem:

```
If you are the author of the package, you can use the flag zip_safe=False in setup.py.

setup(
    name = "HelloWorld",
    ...
    zip_safe = False,
)
```

**Comment by BoPeng** [comment]
I am not sure if this actually works.

**Comment by BoPeng** [comment]
I think whenever something like this happens, we need to check if there are two versions of the package, the egg one and the flat one, and need to check which one is the one we need, and how it was installed etc.

The reason why I do not want to adopt it right now is that the option can only be tested with a new release and we have 10+ packages.

**Comment by gaow** [comment]
> The reason why I do not want to adopt it right now is that the option can only be tested with a new release and we have 10+ packages.

I agree. But maybe the flat version is ultimately the way to go, because `pip` will install numerous egg versions that will lead to potential problems as well? I guess we can start testing with just the `sos` release? Writing codes to check sounds like unnecessary effort if we decide to only use one way to solve the problem.

**Comment by gaow** [comment]
Sorry it looks like `pip` does not install `egg`. `setup.py` does! So we should be good with the released versions? I just `pip` installed all other SoS compoments, this is what I get:

```
[GW] ls sos
sos-0.9.12.10-py3.6.egg/         sos_notebook/                    sos_python-0.9.12.0.dist-info/
sos_bash/                        sos_notebook-0.9.12.9.dist-info/ sos_r/
sos_bash-0.9.12.1.dist-info/     sos_pbs/                         sos_r-0.9.12.0.dist-info/
sos_matlab/                      sos_pbs-0.9.10.4.dist-info/      
sos_matlab-0.9.12.0.dist-info/   sos_python/  
```

So the only `egg` was from my `setup.py` install.

**Comment by BoPeng** [comment]
So the somewhat surprising solution would be using `pip` only, that is to say, using

```
pip install .
```
instead of
```
python setup.py install
```
?

**Comment by BoPeng** [comment]
Then we have no choice but to do something like

```
python setup.py install --single-version-externally-managed --root /
```

**Comment by gaow** [comment]
and make it a `Makefile` ...
