### ISSUE TITLE
Docker image does not honor `work_dir`?

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#921]
Not sure if this can be confirmed, but in my run of a docker image:

```
[1]
bash: docker_image = 'bschiffthaler/ngs', work_dir = '/tmp' 
  STAR --help > test.txt

```

The above workflow should supposedly execute under `work_dir`. But from `docker` command output prompt it is not the case. And indeed files are generated to where I run the workflow, not my specified `work_dir`. Here is the docker output:

```
INFO: Executing default_1: 
INFO: input:   []
INFO: docker run --rm --security-opt label:disable  -v /home:/home -v /tmp:/tmp -v /home/gaow/GIT/tmp2lx5bbnu/docker_run_34624.sh:/var/lib/sos/docker_run_34624.sh    -t -P -w=/home/gaow/GIT     bschiffthaler/ngs /bin/bash /var/lib/sos/docker_run_34624.sh
INFO: output:   []
INFO: Workflow default (ID=338ff3d235b25221) is executed successfully.
```

and a file `test.txt` is created under `~/GIT` not `/tmp`.

**Comment by BoPeng** [comment]
What is `cwd` and what is the “`docker` command output”? The `docker_image` option basically turns the `STAR` command to a `docker run SCRIPT` command. `work_dir` is honored but it is not entirely sure if `docker run` would cause some complications.

**Comment by gaow** [comment]
Okey I updated my example above to a MWE with the command output. It seems docker run has caused complicates -- maybe need to set docker workdir somehow?

**Comment by BoPeng** [comment]
Docker has its own option called working_dir. You can try to set this one instead of work_dir.

**Comment by gaow** [comment]
> Docker has its own option called working_dir. You can try to set this one instead of work_dir.

It does work! should we make `work_dir` override docker's `working_dir` though?

**Comment by BoPeng** [comment]
If docker ignored where it is started (our work_dir), we should indeed translate work_dir to working_dir.

**Comment by BoPeng** [comment]
Btw, is there an option to set working dir inside docker image? Or is there such a need at all?

**Comment by gaow** [comment]
> Btw, is there an option to set working dir inside docker image? Or is there such a need at all?

I'm not sure I get this question. In my MWE it is sufficient to use `work_dir` to override `working_dir` to get what I expect.. I'm not sure what it means to set working dir inside docker image ... (that perhaps means no need?)

**Comment by BoPeng** [comment]
let me know if the patch works.

**Comment by gaow** [comment]
No it did not work for my example above ...

**Comment by BoPeng** [comment]
Could you trace and check if the patch is triggered? As far as I can tell, work for should appear in kwargs there.

**Comment by gaow** [comment]
> Could you trace and check if the patch is triggered? As far as I can tell, work for should appear in kwargs there.

On it now. In the mean time, onwership of all `docker` generated files are `root.root`. Is it possible to write the files as the `user`?

**Comment by gaow** [comment]
Sorry my bad, I somehow made a typo last night on `work_dir`: should be `workdir` ... so there was actually no need for the last patch because this line has taken care of it:

```
            working_dir_opt = '-w={}'.format(shlex.quote(os.path.abspath(os.getcwd())))
```

I am sorry about the false alert. Will use a separate ticket to discuss ownership.
