### ISSUE TITLE
Do not `touch` time stamp of existing files when they are skipped

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#924]
Not sure if there will be bad side effects but I find it very useful to be able to tell if a workflow has been re-executed (or when was it last actually been executed) simply by looking at the time stamp on the output files. Unfortunately currently since we rely on signature, the time stamps of existing files are all updated. Is there a reason we have to touch those files? Leaving them untouched is perhaps better idea otherwise.

**Comment by BoPeng** [comment]
Did you look at creation or access date? The files will be accessed to check signature, but creation time should be kept untouched.

**Comment by gaow** [comment]
Good point. I should have used creation time which is untouched.
