### ISSUE TITLE
Limit maximum download jobs

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#927]
Same example as #926 but instead of worrying about disk space we worry here the download bandwidth balance. The workflow is again pasted here:

```
[1]
input: for_each = ['files_sra'], group_by = 1, concurrent = True
output: files_sra
download: 
  {url}/{_files_sra}

[2]
output: files_bam
run:
 sratools-dump ${_input} ${_output}
```

Apparently we cannot use very large `-j` for step 1 due to band-width limit. But if we use eg, `-j 1` then after download step 1, the `sratools` decryption step 2 will take long time, and the workflow will not download anything. This is a waste of resource. 

So ideally we want something like this:

```
1st file download -> 1st file decryption &  2nd file download -> 2nd file decryption & 3rd file download ...
```

How can we use SoS existing features to achieve this?

**Comment by BoPeng** [comment]
Interesting ....

**Comment by BoPeng** [comment]
This looks to me should be implemented as 

```
[rsa: provides='{}.rsa']
download: max_jobs=2
  {url}/{_output}

[bam: provides='{file}.bam']
depends: f'{file}.rsa'

run:
 sratools-dump ${_input} ${_output}

[default]
sos_run(targets=whatever_bam_files)
```
That is to say,

1. We do not download all then process all
2. Band limiting should be at the `download` level (for each website, I suppose), not at workflow level
3. Let SoS handle waiting for download or waiting for processing because you do not know beforehand which part takes more time.
4. Limiting `download` action this way is a bit difficult, but can be done.

**Comment by gaow** [comment]
Indeed. If bandwidth can be controlled at download action then I would totally write a make style workflow that parallels best. Our current maxjob is at workflow level. I can tell it is not straightforward to limit at step or action level thus not sure how to solve this. But it seems specifically limiting download action is reasonable by itself

**Comment by BoPeng** [comment]
There is currently a hidden parameter (needs `sos config --set sos_download_processes`) to set the number of processes per `download` action. It does not work across multiple download instances though.

**Comment by BoPeng** [comment]
```
download: max_jobs = 3
```
is supposed to work now, but obviously needs testing. In the worst case (with error and interruption), you will have to manually remove `~/.sos/*.slot` to reset slot counters.

**Comment by BoPeng** [comment]
Using 

```
files = '''\
CancerGeneCensus-20130711.DB.gz
CancerGeneCensus-20130711.ann
CancerGeneCensus-20170912.DB.gz
CancerGeneCensus-20170912.ann
CancerGeneCensus.ann
CosmicCodingMuts-v67_20131024.DB.gz
CosmicCodingMuts-v67_20131024.ann
CosmicCodingMuts-v82_20170801.DB.gz
CosmicCodingMuts-v82_20170801.ann
CosmicCodingMuts.ann
CosmicMutantExport-v67_241013.DB.gz
CosmicMutantExport-v67_241013.ann
CosmicMutantExport-v82_20170803.DB.gz
CosmicMutantExport-v82_20170803.ann
CosmicMutantExport.ann
CosmicNonCodingVariants-v67_241013.DB.gz
CosmicNonCodingVariants-v67_241013.ann
CosmicNonCodingVariants-v82_20170801.DB.gz
CosmicNonCodingVariants-v82_20170801.ann
CosmicNonCodingVariants.ann
DGV-hg19_20130723.DB.gz
DGV-hg19_20130723.ann
DGV-hg38_20160831.DB.gz
DGV-hg38_20160831.ann
DGV.ann
ESP-6500SI-V2-SSA137.DB.gz
ESP-6500SI-V2-SSA137.ann
ESP.ann
EntrezGene-20131028.DB.gz
EntrezGene-20131028.ann
EntrezGene-20170919.DB.gz
EntrezGene-20170919.ann
EntrezGene.ann
EntrezGene2RefSeq-20131028.DB.gz
EntrezGene2RefSeq-20131028.ann
EntrezGene2RefSeq-20170919.DB.gz
EntrezGene2RefSeq-20170919.ann
EntrezGene2RefSeq.ann
ExAC-hg19_r0.2.DB.gz
ExAC-hg19_r0.2.ann
HGNC-20131029.DB.gz
HGNC-20131029.ann
HGNC-20170920.DB.gz
HGNC-20170920.ann
HGNC.ann
Illumina_NRCE-20130307.DB.gz
Illumina_NRCE-20130307.ann
Illumina_NRCE.ann
LCR-hg19_20090320.DB.gz
LCR-hg19_20090320.ann
LCR.ann
ccdsGene-hg19_20130904.DB.gz
ccdsGene-hg19_20130904.ann
ccdsGene-hg38_20171008.DB.gz
ccdsGene-hg38_20171008.ann
ccdsGene.ann
ccdsGene_exon-hg19_20130904.DB.gz
ccdsGene_exon-hg19_20130904.ann
ccdsGene_exon-hg38_20171008.DB.gz
ccdsGene_exon-hg38_20171008.ann
ccdsGene_exon.ann
clinvar-20150804.DB.gz
clinvar-20150804.ann
clinvar-20150929.DB.gz
clinvar-20150929.ann
clinvar-20171002.DB.gz
clinvar-20171002.ann
cytoBand-hg19_20111216.DB.gz
cytoBand-hg19_20111216.ann
cytoBand-hg38_20140810.DB.gz
cytoBand-hg38_20140810.ann
cytoBand.ann
dbNSFP-hg18_hg19_2_4.DB.gz
dbNSFP-hg18_hg19_2_4.ann
dbNSFP-hg18_hg19_2_7.DB.gz
dbNSFP-hg18_hg19_2_7.ann
dbNSFP-hg18_hg19_2_9.DB.gz
dbNSFP-hg18_hg19_2_9.ann
dbNSFP-hg38_3_5a.DB.gz
dbNSFP-hg38_3_5a.ann
dbNSFP.ann
dbNSFP_gene-2_4.DB.gz
dbNSFP_gene-2_4.ann
dbNSFP_gene-2_7.DB.gz
dbNSFP_gene-2_7.ann
dbNSFP_gene-3_5a.DB.gz
dbNSFP_gene-3_5a.ann
dbNSFP_gene.ann
dbSNP-hg19_138.DB.gz
dbSNP-hg19_138.ann
dbSNP-hg19_141.DB.gz
dbSNP-hg19_141.ann
dbSNP-hg38_143.DB.gz
dbSNP-hg38_143.ann
dbSNP.ann
dbscSNV-hg19_20141120.DB.gz
dbscSNV-hg19_20141120.ann
genomicSuperDups-hg19_20130626.DB.gz
genomicSuperDups-hg19_20130626.ann
genomicSuperDups-hg38_20141018.DB.gz
genomicSuperDups-hg38_20141018.ann
genomicSuperDups.ann
gwasCatalog-hg19_20140112.DB.gz
gwasCatalog-hg19_20140112.ann
gwasCatalog-hg38_20171004.DB.gz
gwasCatalog-hg38_20171004.ann
gwasCatalog.ann
hapmap_ASW_freq-hg18_20100817.DB.gz
hapmap_ASW_freq-hg18_20100817.ann
hapmap_ASW_freq.ann
hapmap_CEU_freq-hg18_20100817.DB.gz
hapmap_CEU_freq-hg18_20100817.ann
hapmap_CEU_freq.ann
hapmap_CHB_freq-hg18_20100817.DB.gz
hapmap_CHB_freq-hg18_20100817.ann
hapmap_CHB_freq.ann
hapmap_CHD_freq-hg18_20100817.DB.gz
hapmap_CHD_freq-hg18_20100817.ann
hapmap_CHD_freq.ann
hapmap_GIH_freq-hg18_20100817.DB.gz
hapmap_GIH_freq-hg18_20100817.ann
hapmap_GIH_freq.ann
hapmap_JPT_freq-hg18_20100817.DB.gz
hapmap_JPT_freq-hg18_20100817.ann
hapmap_JPT_freq.ann
hapmap_LWK_freq-hg18_20100817.DB.gz
hapmap_LWK_freq-hg18_20100817.ann
hapmap_LWK_freq.ann
hapmap_MEX_freq-hg18_20100817.DB.gz
hapmap_MEX_freq-hg18_20100817.ann
hapmap_MEX_freq.ann
hapmap_MKK_freq-hg18_20100817.DB.gz
hapmap_MKK_freq-hg18_20100817.ann
hapmap_MKK_freq.ann
hapmap_TSI_freq-hg18_20100817.DB.gz
hapmap_TSI_freq-hg18_20100817.ann
hapmap_TSI_freq.ann
hapmap_YRI_freq-hg18_20100817.DB.gz
hapmap_YRI_freq-hg18_20100817.ann
hapmap_YRI_freq.ann
keggPathway-20110823.DB.gz
keggPathway-20110823.ann
keggPathway.ann
knownGene-hg19_20110909.DB.gz
knownGene-hg19_20110909.ann
knownGene-hg19_20121219.DB.gz
knownGene-hg19_20121219.ann
knownGene-hg19_20130904.DB.gz
knownGene-hg19_20130904.ann
knownGene-hg38_20160328.DB.gz
knownGene-hg38_20160328.ann
knownGene.ann
knownGene_exon-hg19_20110909.DB.gz
knownGene_exon-hg19_20110909.ann
knownGene_exon-hg19_20130904.DB.gz
knownGene_exon-hg19_20130904.ann
knownGene_exon-hg38_20160328.DB.gz
knownGene_exon-hg38_20160328.ann
knownGene_exon.ann
nohup.out
phastCons-hg19_20110909.DB.gz
phastCons-hg19_20110909.ann
phastCons-hg19_20130322.DB.gz
phastCons-hg19_20130322.ann
phastCons-hg38_20150913.DB.gz
phastCons-hg38_20150913.ann
phastCons.ann
phastConsElements-hg19_20130622.DB.gz
phastConsElements-hg19_20130622.ann
phastConsElements-hg38_20150913.DB.gz
phastConsElements-hg38_20150913.ann
phastConsElements.ann
refGene-hg19_20110909.DB.gz
refGene-hg19_20110909.ann
refGene-hg19_20130904.DB.gz
refGene-hg19_20130904.ann
refGene-hg38_20170201.DB.gz
refGene-hg38_20170201.ann
refGene-mm10_20141201.DB.gz
refGene-mm10_20141201.ann
refGene.ann
refGene_coding-hg19_20130904.DB.gz
refGene_coding-hg19_20130904.ann
refGene_coding.ann
refGene_exon-hg19_20110909.DB.gz
refGene_exon-hg19_20110909.ann
refGene_exon-hg19_20130904.DB.gz
refGene_exon-hg19_20130904.ann
refGene_exon-mm10_20141201.DB.gz
refGene_exon-mm10_20141201.ann
refGene_exon-mm10_20171008.DB.gz
refGene_exon-mm10_20171008.ann
refGene_exon.ann
rutgersMap-b134.DB.gz
rutgersMap-b134.ann
rutgersMap.ann
thousandGenomes-hg19_20130502.DB.gz
thousandGenomes-hg19_20130502.ann
thousandGenomes-hg19_v3_20101123.DB.gz
thousandGenomes-hg19_v3_20101123.ann
thousandGenomes-hg19_v5b_20130502.DB.gz
thousandGenomes-hg19_v5b_20130502.ann
thousandGenomes.ann'''.split()


[download: provides='{file}']
download: expand=True, max_jobs=10
  http://bioinformatics.mdanderson.org/Software/VariantTools/repository/annoDB/{file}

[default]
input: files, group_by=1
print(f'{_input} downloaded')

```

1. If `max_jobs=2`, there will be at most two downloads
2. If `max_jobs=10`, there will be at most four downloads
3. If `max_jobs=10`, with `-j10`, there will be at most 10 downloads.

The reason is that the make style creates at most `-j` steps and each step download one file.

**Comment by gaow** [comment]
What is the default behavior -- not using slot files at all? I'm just a bit wary (on behalf of users) about what you mentioned having to manually clean up slot files to reset, but obviously if default does not use slots then it is less worrisome (?).

**Comment by BoPeng** [comment]
The slot files are per site. The default will use slot files because whatever parameter used, there might be other sos workflows downloading from the same site. There are potential problems with

1. One workflow has `max_jobs=10`, another has `max_jobs=2`, the it is likely that all slots will be occupied by the former workflow, leaving the latter wait until the first one is done (because 2 or more jobs will be running).
2. There can be more and more such slot files. No clean up right now.
3. Not quite sure brutal murder of sos process will do to subsequent runs. In the worst case a heavily-downloading workflow is killed, leaving a full slot file, and no one can download from the site until the slot file is cleared. I could potentially do something to recognize such residue files.

**Comment by gaow** [comment]
It sounds like cleaning up is the most crucial. `SlotManager` is also used for `-j` option for nested workflows. Doesnt `-j` potentially suffer from some of the same issues here? Can the behavior be unified with some improved versions of `SlotManager` that makes counts / cleans up better?

**Comment by BoPeng** [comment]
I cannot yet think of a safe way to do this, considering that you can limit downloads from workflows running on different workers sharing the same file system, so even detection of running sos is not safe. A more or less safe way is to remove old (e.g. > 14 days) slot files from time to time.

**Comment by BoPeng** [comment]
But in the end, there would not be too many websites anyone would download data from, so I am more worried about dead but (partially) full slot files.

**Comment by BoPeng** [comment]
This should solve the problem, at least partially.

**Comment by gaow** [comment]
Cool! I'll see my colleague this evening to try out this one along with the new `.zap` feature on some none-trivial bulk downloads of 6T data, and report back issues if any.

**Comment by BoPeng** [comment]
The directory should contain user name.  I am on the road but you should be able to add it.

**Comment by BoPeng** [comment]
import getpass
username = getpass.getuser()

**Comment by BoPeng** [comment]
Done.

**Comment by gaow** [comment]
Okey I wrote some bad workflow code (my fault) but SoS got an error [on this line](https://github.com/vatlab/SoS/blob/master/src/sos/actions.py#L834), saying:

```
 File "/opt/miniconda3/lib/python3.6/site-packages/sos-0.9.12.11-py3.6.egg/sos/actions.py", line 830, in download
    sm = SlotManager(name=url_hash[0])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.6/site-packages/sos-0.9.12.11-py3.6.egg/sos/step_executor.py", line 1052, in execute
    self.last_res = SoS_exec(stmt, return_result=self.run_mode == 'interactive')
  File "/opt/miniconda3/lib/python3.6/site-packages/sos-0.9.12.11-py3.6.egg/sos/eval.py", line 88, in SoS_exec
    exec(compile(script, filename=stmtHash.hash(script), mode='exec'), _dict)
  File "script_281475398839268085", line 2, in <module>
  File "/opt/miniconda3/lib/python3.6/site-packages/sos-0.9.12.11-py3.6.egg/sos/actions.py", line 206, in action_wrapper
    res = func(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.6/site-packages/sos-0.9.12.11-py3.6.egg/sos/actions.py", line 834, in download
    sm.release(1)
UnboundLocalError: local variable 'sm' referenced before assignment

```

**Comment by gaow** [comment]
Sorry I should have posted an MWE -- just did it, see above. After I remove the wrong `output:`, download was successful, then running it twice and more I get this:

```
INFO: Executing default_0: 
INFO: input:   []
INFO: Target refGene-hg19_20110909.bam already exists
INFO: Target refGene-hg19_20130904.bam already exists
INFO: Target refGene-hg38_20170201.bam already exists
INFO: Target refGene-mm10_20141201.bam already exists
INFO: Target refGene_coding-hg19_20130904.bam already exists
INFO: Target refGene_exon-hg19_20110909.bam already exists
INFO: Target refGene_exon-hg19_20130904.bam already exists
INFO: Target refGene_exon-mm10_20141201.bam already exists
INFO: Target refGene_exon-mm10_20171008.bam already exists
ERROR: [eb6d8112-9d1c-4ff9-a494-8ec0b04bc5cd]: All targets already exists.
```

Nothing is wrong about it, but the last step says `ERROR` ... should it be `INFO` instead?

**Comment by BoPeng** [comment]
Yes, `download` gets an empty url list. The patch should have fixed it.

**Comment by BoPeng** [comment]
The `ERROR` is triggered because the way to exit the executor in this case. Let me see what I can do.

**Comment by gaow** [comment]
Okey we got this warning message:

```
WARNING: f02c988cad5d9293: Releasing 1 slots from 0 available ones. Please report this bug to SoS developers.
```

The download process did stuck at some point without finishing up all downloads. Looks like `SlotManager` issue?

**Comment by BoPeng** [comment]
If you clear `/tmp/username/sos_slots`, do you still see this problem?

**Comment by gaow** [comment]
Well, after removing the folder at least I think the download is still stuck. Should I try to kill it all and restart download?

**Comment by BoPeng** [comment]
Not sure what would be the behavior if the slot files are removed, perhaps you will have to stop everything. This can be made more robust but let us first try to figure out what went wrong.

**Comment by gaow** [comment]
Running it again the download resumes. Not sure when we'll hit the hang next, though.
