### ISSUE TITLE
Issues with external NTFS system on Linux

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#928]
I plugged in an external hard drive to my computer and run some SoS from there. It's a regular WD 2TB hard drive, original factory setting (NTFS system). Issues I had so far are:

1. Running SoS there twice it says `FileExistsError: [Errno 17] File exists: '/media/gaow/My Passport/.sos'` even though the code in SoS looks good ` os.makedirs(os.path.join(rdir, '.sos'), exist_ok=True)`
2. Docker cannot work. To reproduce:

```
[1]
run: docker_image='gaow/debian-ngs'
  samtools --help > 1.txt
```

I get 

```
INFO: docker run --rm --security-opt label:disable  -v /home:/home -v /tmp:/tmp -v '/media/gaow/My Passport/tmpmd5djho2/docker_run_31709.sh':/var/lib/sos/docker_run_31709.sh    -t -P -w='/media/gaow/My Passport' -u 1000    gaow/debian-ngs /bin/bash /var/lib/sos/docker_run_31709.sh
/var/lib/sos/docker_run_31709.sh: line 1: 1.txt: Permission denied
```

@BoPeng Not sure if it can be reproduce on your end with such external hard drive on a Mac computer?

**Comment by gaow** [comment]
For problem 2 maybe it is a [wontfix](https://unix.stackexchange.com/questions/292481/docker-problems-on-external-drive)

**Comment by BoPeng** [comment]
The first one is perhaps also file system related. The [source code](https://github.com/python/cpython/blob/3.6/Lib/os.py#L208) also shouts for not raising an error in this case.

**Comment by gaow** [comment]
The solution seems to be simply avoid using NTFS as workdir.
