### ISSUE TITLE
Behavior of `_input` / `_output` in Makestyle

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#929]
On ticket #927 I have this example:

```
files = paths('''
refGene-hg19_20110909.DB.gz
refGene-hg19_20130904.DB.gz
refGene-hg38_20170201.DB.gz
'''.strip().split('\n'))
url = 'http://bioinformatics.mdanderson.org/Software/VariantTools/repository/annoDB/'

[rsa: provides='{file}.DB.gz']
download: max_jobs = 2, expand = True
  {url}/{file}.DB.gz

[bam: provides='{file}.bam']
depends: f'{file}.DB.gz'
run: expand = True
 zcat {file}.DB.gz > {file}.bam

[default]
sos_run(targets=[f'{x:nn}.bam' for x in files])
```

Which uses wildcard `file` everywhere. Let's call it `test1.sos`. In my `test2.sos` below, I use `_input` / `_output` syntax:

```
files = paths('''
refGene-hg19_20110909.DB.gz
refGene-hg19_20130904.DB.gz
refGene-hg38_20170201.DB.gz
'''.strip().split('\n'))
url = 'http://bioinformatics.mdanderson.org/Software/VariantTools/repository/annoDB/'

[rsa: provides='{file}.DB.gz']
download: max_jobs = 2, expand = True
  {url}/{_output}

[bam: provides='{file}.bam']
depends: f'{file}.DB.gz'
run: expand = True
 zcat {_input} > {_output}

[default]
sos_run(targets=[f'{x:nn}.bam' for x in files])
```

`test1.sos` works great no matter what. `test2.sos` will faill with the following commands:

```
sos run test2.sos 
rm -f *.bam
rm -rf .sos/
sos run test2.sos 
```

with message:
```
INFO: Executing default_0: 
INFO: input:   []
INFO: Executing bam: 
INFO: input:   []
zcat  > refGene-hg19_20110909.bam
gzip: compressed data not read from a terminal. Use -f to force decompression.
For help, type: gzip -h
INFO: Executing bam: 
INFO: input:   []
zcat  > refGene-hg19_20130904.bam
gzip: compressed data not read from a terminal. Use -f to force decompression.
For help, type: gzip -h
INFO: Executing bam: 
INFO: input:   []
zcat  > refGene-hg38_20170201.bam
gzip: compressed data not read from a terminal. Use -f to force decompression.
For help, type: gzip -h
```

So apparently `_input` was lost there because it previously exists. Is it a feature or bug?

**Comment by gaow** [comment]
I want to add that `_input` here matters to me because my 2nd step is meant to be:

```
[bam: provides='{file}.bam']
depends: f'{file}.DB.gz'
run: expand = True
 zcat {_input} > {_output}

_input.zap()
```

with the `_input.zap()` in the end.

**Comment by BoPeng** [comment]
You did not specify `input:` in the `bam` step, were you supposed to `_depends`?

```
 zcat {_depends} > {_output}
```

**Comment by gaow** [comment]
Oh can I do that, when I have 

```
depends: f'{file}.DB.gz', Py_Module('docker')
```
?

and can I use `_depends.zap()`? I can give this a go. guess it is a bit confusing because `_input` indeed has worked when I run it first time.

**Comment by BoPeng** [comment]
`zap()` ignores non `file-target` so it should work. If you want to use `_input`, you can do

```
input: f'{file}.DB.gz'
depends: Py_Module('docker')
```

**Comment by gaow** [comment]
Sure, I realized I can explicitly ask for it. My trouble is just that we have some implicit `_output` allowed, yet we have to make `_input` explicit in Make style. Is my concern correct and reasonable?

**Comment by BoPeng** [comment]
In make style, `_output` is copied from `provides` if not specified. `_input` cannot be safely implied.

What you are asking is something like setting `_input` to `_depends` if `_input` is none, which I am not sure if it is a good idea.

**Comment by BoPeng** [comment]
This is actually related to #907, that is to say sos can warn users even refuse processing if `_input` etc are suspicious. .. In the same vein, the new syntax highlighting code marks `input` and `output` in expressions such as `{input}` in red since it is not supposed to be used.
