### ISSUE TITLE
Path for current directory returns empty

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#930]
For example:

```
>>> from sos.targets import path
>>> a = path('1.txt')
>>> f{a:d}
''
```

the output is `''` empty rather than `./`. It creates trouble when for example later I use `workdir = f{_output:d}`.

**Comment by BoPeng** [comment]
This does not mean we cannot change it though.

**Comment by BoPeng** [comment]
Note that you could have used

```
_output.parent
```

**Comment by BoPeng** [comment]
Changed to `.` considering that `path` is derived from `pathlib.Path`. I would have kept `d` and added `p`(arent) if `p` is not used for `posix` right now.
