### ISSUE TITLE
Question: further processing path expansion results

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#931]
For example I have this workflow:

```
oo = path('/tmp/1234567.txt')
[1]
run: expand  = True
  echo {oo:bn}
```
the output is `1234567`. But I only want to output `1234`. This is straightforward before we use file targets, but I'm not sure what is the best way to do it given now that `oo` is a `path`.  `{os.path.basename(oo)[:4]}` surely works but i'm wondering if there is a better way.

**Comment by BoPeng** [comment]
This cannot be done because we have no control over the output once the format function (`:bn`) is called.
