### ISSUE TITLE
Running docker on drives not mounted to `/home`

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#932]
By default, docker images on SoS gets automatically maped (on a linux machine) via `-v /home:/home -v /tmp:/tmp` which works for files under the current directory. Currently I have some data located under  `/median/$USER` that I try to use with docker images but got a complain that the paths does not exist. Can this issue be confirmed on your end? How can we map the path better in that case? I tried symbolic link, did not work. The only way to ensure it works is to have everything under `/home`

**Comment by BoPeng** [comment]
There is an option `volumes`, which is mentioned in [the reference](https://vatlab.github.io/sos-docs/doc/documentation/Targets_and_Actions.html#docker_image).

**Comment by gaow** [comment]
Thanks for the pointer! I did not read those in detail because there is always `extra_args` one can fall back on ... I'm more thinking about trying to determine if some input files are not under `/home`, and thus automatically create volume mapping for the proper paths. This will make the workflow more portable (eg. when an extern drive is mounted on `/mnt` on one computer and `/media` on another). Is it straightforward to implement?

BTW there is a broken link on that reference: " (if [properly configured](http://vatlab.github.io/SOS/doc/tutorials/SoS_Docker_Guide.html) under mac) "

**Comment by BoPeng** [comment]
I am not sure how to do that properly because directory names would be different inside and outside of docker, especially with externally mount directories. The script might also refer to path outside of docker, which can cause problems as well.

This is certainly doable but overly clever can bite us in some situations.

**Comment by gaow** [comment]
Okey, I can understand it. I'm cool to close the ticket if you deem it proper.
