### ISSUE TITLE
SoS running docker applications with entrypoints

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#933]
Here is a MWE:

```
[1]
run: docker_image = 'dceoy/gatk'
     java -Xmx4g -jar GenomeAnalysisTK.jar -h
```

I got the command line interpolated:

```
INFO: docker run --rm --security-opt label:disable  -v /home:/home -v /tmp:/tmp -v /home/gaow/Documents/GIT/github/pet-project/tmphnzuaurk/docker_run_14466.sh:/var/lib/sos/docker_run_14466.sh    -t -P -w=/home/gaow/Documents/GIT/github/misc -u 1000:1000    dceoy/gatk /bin/bash /var/lib/sos/docker_run_14466.sh
```

It fails on this error:

```
***********************************************************************

A USER ERROR has occurred: '/bin/bash' is not a valid command.


***********************************************************************
Set the system property GATK_STACKTRACE_ON_USER_EXCEPTION (--java-options '-DGATK_STACKTRACE_ON_USER_EXCEPTION=true') to print the stack trace.
```

So it looks like the `dceoy/gatk /bin/bash /var/lib/sos/docker_run_14466.sh` line is problematic. Has anyone ran into this before? I guess there should be a fix with docker switches but it is not apparent to me.

**Comment by BoPeng** [comment]
`run` uses `bash` to execute script by default. Perhaps you should use

```
run:
    #!/usr/bin/java -Xmx4g -jar
   GenomeAnalysisTK.jar -h
```
or simply
```
script:
   java -Xmx4g -jar  GenomeAnalysisTK.jar -h
```
to start?

**Comment by gaow** [comment]
Oh I never have used this `script` action. I'll give it a go when I get back to my desk. Does `script: interpreter = 'java -Xmx4g'` work?

**Comment by BoPeng** [comment]
The root question is how to execute a file with

```
 java -Xmx4g -jar  GenomeAnalysisTK.jar -h
```
In this case you will have to have an interpreter. If `/bin/bash` does not exist, you will have to use `sh:` or `#!/path/to/sh`. If you want to use `java` as interpreter, you will have to figure out the syntax to run `java whatever_option a_temp_file_with_the_script`.

**Comment by gaow** [comment]
Right, I'm still in the search for such a command that uses `java` directly. Various `script` interpreter did not work for that docker image.

**Comment by gaow** [comment]
The problem is that this Docker has a specific "entry point": https://hub.docker.com/r/dceoy/gatk/~/dockerfile/

In this case we are restricted to providing `java -jar gatk.jar` some scripts to run ...

**Comment by BoPeng** [comment]
So the docker image will be run as additional parameter passed to `java -jar gatk.jar`?

**Comment by BoPeng** [comment]
Note that outside of docker, there is a trick to use script as parameter, that it to say

```
run: args='{script}'
    real args
```
The mechanism is that if no `args` is specified, `args` will be set to `{filename}`. I can implement the same mechanism for docker if this is helpful.

**Comment by gaow** [comment]
Well, this docker image will be executed essentially like this: `java -jar gatk.jar  <sos task interpreter> <sos generated sh file>` which is problematic. I can simply create my own docker image to disallow entrypoint. I am not sure if your proposed solution is going to deal with it, from what you've described: a script is involved anyways, right?

**Comment by BoPeng** [comment]
Well, it is complicated. Outside of docker,

```
run:
  script
```
is `/bin/bash temp_script_name` which is the most comm case.

```
run: args='{script}'
  content
```
will run `/bin/bash content` which passes content to command line.

`script` does not have a default interpreter, so 
```
script:
   content
```
execute `temp_file_with_content` directly, and

```
script: args='{script}'
  content
```
will execute `content` directly.

Now, if I can make this work also for docker, you should be able to do

```
script: args='script', docker_image='blah'
    java ...
```

**Comment by BoPeng** [comment]
With the patch I just committed,

```
[0]
script: docker_image='ubuntu', args='{script}'
echo 'Echo'
```
will be translated to
```
INFO: docker run --rm   -v /Users:/Users -v /tmp:/tmp -v /Users/bpeng1/sos/tmp2b4en3xl/docker_run_67576.sh:/var/lib/sos/docker_run_67576.sh    -t -P -w=/Users/bpeng1/sos -u 1985961928:895809667    ubuntu  echo 'Echo'
```
Basically `echo 'Echo'` becomes the command. Will this work for you?

**Comment by gaow** [comment]
I see. Yes I agree this is going to work for me if it works for docker applications.

**Comment by gaow** [comment]
Great! Now this works:

```
[1]
script: args = '{script}', docker_image = 'dceoy/gatk'
     PrintReads -h
```

**Comment by BoPeng** [comment]
Does the following also work?
```
[1]
script: args = 'Print Reads -h', docker_image = 'dceoy/gatk'
```

**Comment by gaow** [comment]
Yes it does! though it is not that useful because the arguments are very long. 

BTW are we stable enough to make another release, or some other issues needs to be resolved before doing so? I'd like to share my script with someone. Would be nice to have him `pip` it.

**Comment by BoPeng** [comment]
OK, I have documented such advanced usages at [action doc](https://vatlab.github.io/sos-docs/doc/documentation/Targets_and_Actions.html#Core-Actions) and [option `docker_image`](https://vatlab.github.io/sos-docs/doc/documentation/Targets_and_Actions.html#docker_image-124), and released sos 0.9.13.0.

**Comment by gaow** [comment]
Okey it looks like we need another bug fix release because this ticket has broken something:

```
[1]
bash: docker_image = 'gaow/debian-ngs'
  STAR -h
```

gives 

```
INFO: docker run ...   gaow/debian-ngs ['/bin/bash', 'bash'] /var/lib/sos/docker_run_7138.sh
```

which, as you can tell, is doomed to fail. Using `run` we do not have the problem.

If we are to make a bug fix release it would be great to resolve #934 as well so users only need one upgrade ...

**Comment by gaow** [comment]
Great, it works now. 

Before we release, should we check `pyflake`? A couple of red flags are raised if you check it. Additionally tools like https://github.com/hhatto/autopep8 might also be helpful.

**Comment by BoPeng** [comment]
already released. Will deflake later.
