### ISSUE TITLE
Rscript start up issues

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#934]
Currently we run R action by `Rscript --defaultPackages=datasets,methods,utils,stats,grDevices,graphics`. This is to resolve problem with some systems that the startup environment does not load these packages with `Rscript`, even though the interactive R sessions do. However as complained by a colleague of mine, it turns out we are essentially customizing R start up environment by overriding the default, thus breaking the scripts for some R users.

So it seems to me that a compromise is to still use just `Rscript` to call the `R` action, but when we prepare R scripts we add to the beginning of it the following:

```
lapply(c('datasets','methods','utils','stats','grDevices','graphics'), require, character.only = TRUE)
```

That way we add in packages without overriding user's defaults. I'm just not sure what's the best place in SoS code to add in this line: as default `input=` option to `R` action prior to R scripts are generated? Or edit generated R scripts adding these in before execution?

**Comment by BoPeng** [comment]
I do not know any of these. You do have a good R group there.

The essential problem is that we would like to be able to execute "normal interactive script" in Rscript. Is this even a valid request? We asked that users should write "complete script" to be executed by interpreters, so it makes sense to ask them to add something after the `R:` line, or do something like:

```
R:  args='--defaultPackages=datasets,methods,utils,stats,grDevices,graphics {filename}'
  some script
```

**Comment by BoPeng** [comment]
Can we define `R_DEFAULT_PACKAGES`? We can add a variable `env` for actions.

**Comment by BoPeng** [comment]
The users can also debug the script interactively? I do not like the idea of modifying user-provided script.

**Comment by gaow** [comment]
Yes I was about to suggest it. I am on the same boat as you are. We should avoid changes to scripts

**Comment by BoPeng** [comment]
How about extending [option env of task](https://vatlab.github.io/sos-docs/doc/documentation/Remote_Execution.html#Option-env-1713)?

**Comment by gaow** [comment]
Sure. But how about non-task R actions?

**Comment by BoPeng** [comment]
This patch does these:

1. Add option `default_env` to all actions. This `default_env`, if specified, has to be a dictionary, and keys defined in this dictionary will only be added to `os.environ` if the key does not already exist.

2. Add option `env` to all actions. This `env`, if specified, has to be a dictionary, and will be used to update `os.environ` to override existing settings.

3. Add action definition option `default_args`, which will add some keyword arguments to user provided options if unspecified. Using this [here](https://github.com/vatlab/SoS/blob/master/src/sos/actions_r.py#L35) will has the following consequences.

1. The usual `R` action
```
R:
  script
```
is equivalent to
```
R: default_env={'R_DEFAULT_PACKAGES': 'datasets,methods,utils,stats,grDevices,graphics'} 
  script
```
which will add `R_DEFAULT_PACKGES` if it is not defined.

2. Users can use
```
R: env={'R_DEFAULT_PACKAGES': 'whatever'}
  script
```
to override environmental definitions.

Please test and let me know if this works as expected.

**Comment by gaow** [comment]
Great. It works as expected for me (Linux, stock `R`). I think we are good as long as it works on your end (Mac, conda `R`) I assume.

**Comment by BoPeng** [comment]
OK, just to confirm,

```
[bpeng1@rcsw0cl0133034:~/sos (master)]$ cat test.sos
R:
iris
[bpeng1@rcsw0cl0133034:~/sos (master)]$ sos run test
INFO: Executing default_0:
INFO: input:   []
    Sepal.Length Sepal.Width Petal.Length Petal.Width    Species
1            5.1         3.5          1.4         0.2     setosa
2            4.9         3.0          1.4         0.2     setosa
3            4.7         3.2          1.3         0.2     setosa
4            4.6         3.1          1.5         0.2     setosa
5            5.0         3.6          1.4         0.2     setosa
6            5.4         3.9          1.7         0.4     setosa
7            4.6         3.4          1.4         0.3     setosa
8            5.0         3.4          1.5         0.2     setosa
9            4.4         2.9          1.4         0.2     setosa
...
[bpeng1@rcsw0cl0133034:~/sos (master)]$ export R_DEFAULT_PACKAGES=NULL
[bpeng1@rcsw0cl0133034:~/sos (master)]$ sos run test
INFO: Executing default_0:
INFO: input:   []
Error: object 'iris' not found
Execution halted
ERROR: [default_0]:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
script_6209179844811813177 in <module>
      R(r"""iris
----> """)

RuntimeError: Failed to execute commmand "Rscript /var/folders/ys/gnzk0qbx5wbdgm531v82xxljv5yqy8/T/tmp3p4a_5j6.R" (ret=1, workdir=/Users/bpeng1/sos, script now in /Users/bpeng1/sos/.sos/default_0_0_5cfd11eb.R)
```

**Comment by gaow** [comment]
Okey `Rscript` command is biting me again. I have an R script that calls a system command which does not work when triggered with `Rscript file.R`, but works with `R --slave -f file.R`. 

Is `Rscript` or `R <args>` the proper way to run R code -- what is your take on this? There is not much info Google can tell me ...

**Comment by BoPeng** [comment]
I do not know what `--slave -f` does here but you can specify it with

```
R: args='--slave -f {filename}'
  script
```
if you need to run the script that way.

**Comment by gaow** [comment]
Oh I'm talking about command `R` vs `Rscript`, not just `args`. And I am aware that I can have workarounds with for example `script` action. I just want to discuss if indeed `Rscript` is the best default method to run R codes.

**Comment by gaow** [comment]
We can always ask users in trouble to use `script` anyways. so if we both do not yet know the answer, we can probably leave it as is for now, until we have better understanding about it later?

**Comment by BoPeng** [comment]
Sorry, I guess we will have to use 
```
run:
    #!R --slave -f
    script
```
or
```
script: intepreter='R', args='--slave -f {filename}'
   script
```

**Comment by gaow** [comment]
Yes for the time being I used `script:` action exactly as you pointed out. So let's just bear this in mind and see if we both run into another case of it in the future?

**Comment by BoPeng** [comment]
My understanding is that `Rscript` is for batch execution and `R` is for interactive use. We can simulate `Rscript` with `R CMD BATCH` etc but I do not see a reason for it.

I do not understand why you cannot use Rscript though.

**Comment by BoPeng** [comment]
There is nothing special about these options
```
  --slave               Make R run as quietly as possible
  -f FILE, --file=FILE  Take input from 'FILE'
```
so basically your are running R in interactive mode?

**Comment by gaow** [comment]
Okey here is the issue:

```
 diff <(Rscript -e "Sys.getenv()") <(R --slave -e "Sys.getenv()")
```

output:

```
33d32
< R_DEFAULT_PACKAGES      datasets,utils,grDevices,graphics,stats
45c44
< R_SESSION_TMPDIR        /tmp/RtmplZAfgQ
---
> R_SESSION_TMPDIR        /tmp/Rtmp7HDYkQ
```

so it is again default packages ... when I use `Rscript --default-packages=""` for my specific script, it all works. But as have been shown it will not work for others.

For your information, I was trying to run a R script that calls a python code to process some computing using `rpy2`. `Rscript` cannot get the `rpy2` related code running, saying:

```
  File "/opt/miniconda3/lib/python3.6/site-packages/rpy2-2.9.2-py3.6-linux-x86_64.egg/rpy2/robjects/robject.py", line 66, in RObjectMixin
    __show = rpy2.rinterface.baseenv.get("show")
LookupError: 'show' not found
```

But `R` works ...

**Comment by gaow** [comment]
I updated my comment above to keep to the essence of it. It is such a headache.

**Comment by BoPeng** [comment]
Do not know what to do, returning to my tax filing now.... :-(

**Comment by gaow** [comment]
Right, there is nothing wrong with SoS's implementation, it is just problematic that `Rscript` by itself does not reproduce.  As you said, it also feels wrong to me to make `R` run batch scripts. Let's leave it as is, and refer to this ticket to give users a solution when they run into the problem. I guess i'll have to leave my tax to at least after wrapping up my other task queue :(
