### ISSUE TITLE
Dockerized SoS workflow

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#935]
This might be a docker related question but it does not look trivial and maybe we can discuss here before we document it somewhere on our wiki site -- I wanted to make a docker image of my entire workflow to share with someone so that they do not have to install anything other than `docker` itself. Here is a MWE of what I'm attempting to do, and how i have failed:

```bash
$ docker run --rm --security-opt label:disable \
       -v $USER:/home/jovyan -v /tmp:/tmp -t -P \
       -w $PWD -u $UID:${GROUPS[0]} mdabioinfo/sos-notebook \
       sos run test.sos
...
PermissionError: [Errno 13] Permission denied: '/home/gw/.sos'
```

Notice that if I change the last line to `sos -h` or `sos -h > out.txt`  they both work. How to actually run and let this docker image generate something to the host? Here is my `test.sos` just in case : 

```
[1]
output: "2.txt" 
run:
  sos -h > 2.txt
```

**Comment by BoPeng** [comment]
Are you running as root or user in docker? If latter, you need to chown the user dir.

**Comment by gaow** [comment]
I run as user `-u`. The UID (from my computer) is likely not exist in the docker image. 

> If latter, you need to chown the user dir.

But in docker image running as user I would not have the permission, right? So are you suggesting that when creating the docker image we change `/home/jovyan` to let it writable by whatever user?

**Comment by BoPeng** [comment]
Why do you use `mdabioinfo/sos-notebook` instead of `mdabioinfo/sos`? The later is way smaller but should be enough for executing workflows.

**Comment by gaow** [comment]
> Why do you use mdabioinfo/sos-notebook instead of mdabioinfo/sos? 

Because I want him to be able to also open / edit the SoS notebook I wrote with syntax highlight. Generally people's response is "cool"!

**Comment by BoPeng** [comment]
But then you need to override the `entry_point` of the image, right? Your way of triggering it will append the arguments to the `tinit` entry point, I think.

**Comment by BoPeng** [comment]
Actually, `mdabioinfo/sos` can only do simple things such as 

```
docker run -it mdabioinfo/sos sos -h
```
Or very basic local workflow with command
```
docker run -w `pwd` -v `pwd`:`pwd` -it mdabioinfo/sos-notebook:latest sos run test
```
because the container does not have any common interpreter such as `R`.

When I saw the ticket, I thought you were writing a `Dockerfile` to include the interpreter and your workflow, so that people can execute the workflow with your image.

**Comment by gaow** [comment]
I have not gone that far yet. I got stuck at the first step creating `.sos` folder. 

Actually my entire workflow were dockerized -- every step uses a docker image. The SoS docker is just a tool to run the workflow. I assume that would work and that best modularize things, but again I have not gone that far yet ...

**Comment by BoPeng** [comment]
Have not tried but why do you map your home directory to `/home/jovyan`? That directory belongs to `jovyan` and you do not have permission, and you do not actually need that directory.

```
$ docker run --rm --security-opt label:disable \
       -v $USER:/home/jovyan -v /tmp:/tmp -t -P \
       -w $PWD -u $UID:${GROUPS[0]} mdabioinfo/sos-notebook \
       sos run test.sos
```
 You might try the method I use
```
-w `pwd` -v `pwd`:`pwd` 
```
which basically maps current directory into docker (which should not exist), and then set the current directory to this directory inside docker, which is then mapped to the outside directory, and you should have write permission to `pwd`.

**Comment by gaow** [comment]
> why do you map your home directory to /home/jovyan? 

I had to do that. Otherwise it will not work. `/home:/home` is not sufficient. 

> -v `pwd`:`pwd` 

Right, indeed this gets the basic test work. So in SoS should we make `pwd`:`pwd` part of the default volume map? I guess for every folder the workflow uses there has to be an explicit map?

**Comment by BoPeng** [comment]
> I had to do that.

I do not get it. The `/home/jovyan` is empty and I do not think the docker image needs it for anything (other than hosting examples).

>  in SoS should we make pwd:pwd part of the default volume map?

Good suggestion. We now map `/home`, `/Users` etc automatically so we can also map `pwd`. What is the consequence of mapping some directory that already exists in docker?

**Comment by gaow** [comment]
If I don't map /home/jovyan I get an error message permission denied for /home/jovyan. So looks like it requires mapping for the exact folder we will be working on. Thus I am not sure if mapping /home has helped at all. Mapping to existing folder means mounting disks to it. Based on my experience in Linux disk mounting I think it is no problem. We just cannot access contents in existing folder after mount.

**Comment by gaow** [comment]
Just a reminder for possibly the upcoming release: should we add `-v pwd:pwd`? I see no harm doing so.

**Comment by gaow** [comment]
Another observation is that running `jupyter notebook` from SoS notebook docker image does not work due to port issues. `-p` can be used to map ports, but I could not figure out a proper choice of ports that always works. I was hoping to get to the point that I can build a docker image to setup required resources for an entire project, including SoS environments. Then a collaborator / reviewer will not only be able to run my workflow using the docker image, but also able to use the docker image to open my `*.ipynb` workflow and make changes. Ideally they should not need to install sos-notebook in order to edit my work.
