### ISSUE TITLE
dot preview fails (largely) with dynamic workflow

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#939]
With the following example, because the first image is very small, later images are cropped to the small size, leading to a gif that shows only a small fraction of the DAG.

```
# preview multiple DAG
%preview -n target.dot -v4
!touch test.bam

%run -t test.vcf -d target.dot

# this step provides variable `var`
[index: provides='{filename}.bam.bai']
input: f"{filename}.bam"
run: expand=True
   echo "Generating {_output}"
   touch {_output}

[call: provides='{filename}.vcf']
input:   f"{filename}.bam"
depends: f"{_input}.bai"
run: expand=True
   echo "Calling variants from {_input} with {_depends} to {_output}"
   touch {_output}
```

It looks like we will need to use `PIL` to resize the imported images to the largest size to properly generate a gif.

Growing DAG:
```
strict digraph "8d66aa143009a990" {
"call ['test.vcf']";
}
strict digraph "8d66aa143009a990_1" {
"call ['test.vcf']" [color=green];
}
strict digraph "8d66aa143009a990_2" {
"call ['test.vcf']" [color=green];
}
strict digraph "8d66aa143009a990_3" {
"call ['test.vcf']" [color=green];
"index ['test.bam.bai']";
"index ['test.bam.bai']" -> "call ['test.vcf']";
}
strict digraph "8d66aa143009a990_4" {
"call ['test.vcf']" [color=green];
"index ['test.bam.bai']" [color=green];
"index ['test.bam.bai']" -> "call ['test.vcf']";
}
strict digraph "8d66aa143009a990_5" {
"call ['test.vcf']" [color=green];
"index ['test.bam.bai']" [color=blue];
"index ['test.bam.bai']" -> "call ['test.vcf']";
}
strict digraph "8d66aa143009a990_6" {
"call ['test.vcf']" [color=green];
"index ['test.bam.bai']" [color=blue];
"index ['test.bam.bai']" -> "call ['test.vcf']";
}
strict digraph "8d66aa143009a990_7" {
"call ['test.vcf']" [color=blue];
"index ['test.bam.bai']" [color=blue];
"index ['test.bam.bai']" -> "call ['test.vcf']";
}
```

**Comment by BoPeng** [comment]
But somehow this example works...

```
%sandbox

%preview -n mixed.dot
%run -d mixed.dot

[align_10]
depends: 'hg19.fa'
print(step_name)
[align_20]
print(step_name)
[call_10]
depends: 'dbsnp.vcf', 'hg19.fa'
print(step_name)
[call_20]
print(step_name)
[default]
sos_run('align+call')

[refseq: provides='hg19.fa']
run:
    # a real step would download a fasta file for hg19
    touch hg19.fa

[dbsnp: provides='dbsnp.vcf']
run:
    touch dbsnp.vcf
```

**Comment by HenryLeongStat** [comment]
>It looks like we will need to use PIL to resize the imported images to the largest size to properly generate a gif.

Do you mean the largest size of all the scenes of the `.gif`? (For example: the first one is 900x900, the second one is 600x600, then the gif should be max(900x900, 600x600).) 

I remember the images producing by tensorflow, they are very very big...

**Comment by BoPeng** [comment]
Yes, we need to get the max width and max height of all images, and resize all images to it (no need to scale, just resize).

**Comment by HenryLeongStat** [comment]
Let me check whether `imageio.mimsave()` can do something for that.

**Comment by HenryLeongStat** [comment]
Seems like [that](https://stackoverflow.com/questions/27271138/python-pil-pillow-pad-image-to-desired-size-eg-a4) is what we can do. 

1) Get each size of the `.png`, get the largest.
2) Make a layer with the same size of the largest `.png` in white or transparent.
3) **Replace** the original `.png` files except for the largest one.

**Comment by BoPeng** [comment]
I think as long as you make the first picture the largest one, all others will then be displayed correctly.

The question is that whethere or not you can mix `imageio` with `PIL`/`Pillow`. I suppose you will need to use `Pillow` to do this natively, something like (pseduo code)

```
images = [Image.open(x) for x in pngfiles]
maxx = max([x.width for x in images])
maxy = ...
if images[0].width < maxx or images[0].height < maxy:
    new_img = new image with maxx, maxy
    new_img.paste(images[0]... according to the example
    images[0] = new_img
save images to gif
```

**Comment by HenryLeongStat** [comment]
>I think as long as you make the first picture the largest one, all others will then be displayed correctly.

But how about the case of the original order of the plots? Like the first one is smaller than the second or the third one.

>The question is that whethere or not you can mix imageio with PIL/Pillow. I suppose you will need to use Pillow to do this natively, 

Worst case we can change from `imageio` to `PIL`/`Pillow`, just searched and found that `PIL`/`Pillow` can be used for saving `.gif` as well. 

>something like (pseduo code)

Good point here! In some cases, the x^th plot's width is larger than the y^th plot's, but the y^th plot's height is larger than the x^th plot's.

**Comment by HenryLeongStat** [comment]
>I think as long as you make the first picture the largest one, all others will then be displayed correctly.

Oh I understand what you say here, only change the first scene! Right!

**Comment by BoPeng** [comment]
Yes, in the end `imageio` is only a wrapper to PILLOW and other libraries, and you could always learn from [its source](https://github.com/imageio/imageio/blob/45c2f1a6ef9f496d341251c6cf860f0e4a01db3e/imageio/plugins/pillow.py). (I know you are not used to read source codes... :-)

**Comment by HenryLeongStat** [comment]
:sweat_smile: :sweat_smile: :sweat_smile: 

I will get used to it eventually!

**Comment by HenryLeongStat** [comment]
Spent 40 mins to figure out how to set the 'color of the border'. 
Based on the documentation:
```
    :param image: The image to expand.
    :param border: Border width, in pixels.
    :param fill: Pixel fill value (a color value).  Default is 0 (black).
    :return: An image.
```

I can't find what is the right value for white color or transparency...

**Comment by BoPeng** [comment]
You meant [this line of code](https://github.com/vatlab/SoS/blob/preview_dot_improve/src/sos/preview.py#L271)? That function is used to add borders to existing picture and is not what we need.

**Comment by BoPeng** [comment]
You found https://stackoverflow.com/questions/27271138/python-pil-pillow-pad-image-to-desired-size-eg-a4 post before, does the `paste` method work?

**Comment by HenryLeongStat** [comment]
`fill=0xFFFFFF` works!!

<img width="138" alt="screen shot 2018-04-11 at 5 25 10 pm" src="https://user-images.githubusercontent.com/26916551/38646383-5a606fe2-3dad-11e8-9cc3-b0f265df4729.png">

**Comment by BoPeng** [comment]
Great. Fix the remaining style problem I mentioned and you should be done. ㊗️

**Comment by HenryLeongStat** [comment]
Professor, which one takes smaller space? Two int or one list with two spaces?
