### ISSUE TITLE
Disable python setup.py install?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#940]
We have had a lot of trouble having versions of sos packages installed by `python setup.py install` and `pip install sos`. Basically, `pip` installs straight into `site-packages` with directories such as

```
sos/
sos-0.9.13.2.dist-info/
```

and `python setup.py install` would install

```
sos-0.9.13.3-py3.6.egg/
```

and which one will be called under which condition has been a mystery.

The good news is that `pip install .` supports installing from local source directory and installs to

```
sos/
sos-0.9.13.3-py3.6.egg-info/
```
so that subsequent `pip install sos` or `pip install .` will write to the same directory `sos`. That is to say, we should encourage `pip install .` and discourage `python setup.py install`.

The problem must have been noticed by the Python community and I just noticed that I cannot run `python setup.py install` for jupyter, whose [`setup.py`](https://github.com/jupyter/nbconvert/blob/master/setup.py)

has the following lines of code

```

from setuptools.command.bdist_egg import bdist_egg

class bdist_egg_disabled(bdist_egg):
    """Disabled version of bdist_egg
 
    Prevents setup.py install performing setuptools' default easy_install,
    which it should never ever do.
    """
    def run(self):
        sys.exit("Aborting implicit building of eggs. Use `pip install .` to install from source.")

cmdclass['bdist_egg'] = bdist_egg if 'bdist_egg' in sys.argv else bdist_egg_disabled

```
and running `python setup.py install` will trigger the error.

```
$ python setup.py install
running install
running bdist_egg
Aborting implicit building of eggs. Use `pip install .` to install from source.
```

I think we should follow this.

**Comment by BoPeng** [comment]
We can add this to other packages if it proves useful.

**Comment by gaow** [comment]
I think we have discussed `pip install .`. It by default does nothing when it deems the current installation is up to date. Something like `pip install -I .` will work but it forces upgrading all dependencies. The proper command is perhaps `pip install --upgrade --no-deps --force-reinstall .`?

**Comment by BoPeng** [comment]
[jupyterlab doc](https://github.com/jupyterlab/jupyterlab/blob/master/CONTRIBUTING.md) says `pip install -e .`, the help message for this option says

```
  -e, --editable <path/url>   Install a project in editable mode (i.e. setuptools "develop mode") from a local project
                              path or a VCS url.
```

Is this what we need?

**Comment by gaow** [comment]
> pip install -e .

If you check the outcome I think you still get some `egg` as a result -- is that the case on your system?

**Comment by BoPeng** [comment]
No. I only get `egg-info`, the real thing goes to `sos` without version, that is what we need.

**Comment by gaow** [comment]
Really? Did you remove existing `sos` folder before trying out `pip install -e .`? I get this : 

```
sos.egg-link                      sos_pbs/                          sos_r/
sos_notebook-0.9.12.11-py3.6.egg/ sos_pbs-0.9.10.4.dist-info/       sos_r-0.9.12.0.dist-info/
sos_notebook-0.9.12.12-py3.6.egg/ sos_python/                       
sos_notebook-0.9.13.1-py3.6.egg/  sos_python-0.9.12.0.dist-info/    
```

So everything is under `sos.egg-link`, no `sos` folder at all.

**Comment by BoPeng** [comment]
I see what is going on. `egg-link` points to in my case `/Users/bpeng1/sos/src`, which is the so-called in-place installation.

**Comment by gaow** [comment]
So is `pip install -U --upgrade-strategy only-if-needed .` the shortest command to achieve what we need?

**Comment by BoPeng** [comment]
I am checking
```
pip install -I .
```
which has help message
```
  -I, --ignore-installed      Ignore the installed packages (reinstalling instead).
```

**Comment by gaow** [comment]
It is perhaps good because it will upgrade all dependencies even if they are already met.

**Comment by BoPeng** [comment]
Yes, `-I` does pushes my local change to system `sos`.

**Comment by gaow** [comment]
Sorry, I meant to say "not good" because it upgrades also `psutils` etc if there are new version. Now the problem with that is if my dependencies are installed initially via `conda` then a `pip` upgrade of the same package will potentially cause problems. This is particularly relevant for `sos-notebook` which depends on many ipython related packages. That is why I had put in the long and ugly `--upgrade-strategy` switch.

**Comment by BoPeng** [comment]
Then
```
 pip install -I --no-deps .
```
which is faster anyway (18s vs 44s without `--no-deps` on my system).

**Comment by gaow** [comment]
Still no good, because we do want to upgrade some dependencies when there is a need -- this will be very much relevant to `sos-essentials`.

**Comment by BoPeng** [comment]
I suppose we will have to manually upgrade needed modules then... I have been doing this anyway.

**Comment by gaow** [comment]
Auto-upgrade is behavior more consistent with the original `setup.py`. I have therefore change the error prompt to [this](https://github.com/vatlab/SoS/blob/master/setup.py#L77) now. Works for me.

**Comment by BoPeng** [comment]
ok. It is a pity that python's packaging system is still so problematic after so many years. Just for your information, the new recommended virtualenv/pip environment is [popenv](https://github.com/pypa/pipenv), which seems to be better than virtualenv and virtualenvwrapper.

**Comment by BoPeng** [comment]
I am thinking of reverting this patch now because `pip install . -U` is much slower than `python setup.py install`. In the end,

* users are supposed to use `pip` to install the released versions of `sos`
* developers can use `python setup.py install` and manage dependencies manually

The problem only happens with mixed use of `pip` and `setup.py`, which is not difficult to avoid and fix if we know what is going on.

**Comment by gaow** [comment]
I do not think it is that bad in terms of slowness:

```
[GW] time python setup.py install &> /dev/null

real	0m0.513s
user	0m0.476s
sys	0m0.032s
[GW] time pip install -U --upgrade-strategy only-if-needed . &> /dev/null

real	0m0.995s
user	0m0.856s
sys	0m0.124s
```

So I think we should keep the patch -- better safe than sorry.

**Comment by BoPeng** [comment]
`pip` is slow here:

```
$  time pip install -U --upgrade-strategy only-if-needed .
real	0m29.385s
user	0m3.109s
sys	0m21.744s
```

My laziness made it even slower:
```
$ time pip install . U
real	0m47.917s
user	0m2.670s
sys	0m21.682s
```

but `python setup.py install` after reversing the patch is fast,

```
$ time python setup.py install
real	0m1.123s
user	0m0.679s
sys	0m0.403s
```
I do not know why `pip` is fast on your end.

**Comment by BoPeng** [comment]
I finally cannot tolerate the slow local `pip` run and googled a bit. Obviously this has been a long standing bug with pip: https://github.com/pypa/pip/issues/2195

Basically, during `pip install . -U`, `pip` copies the entire directory, including `.git` and our local `.sos` to a temporary directory before building. Since these two directories can have thousands of files (7000+ as I have just counted), local installation will be slow.
