### ISSUE TITLE
Documentation for installing ijavascript

### ISSUE THREAD

**Issue by HenryLeongStat** [vatlab/SoS#944]
Professor, I follow the documentation to install ijavascript. However, it keeps failing on my mac even though I ran it as root. 

I take a look with [git repo of ijavascript](https://github.com/n-riesco/ijavascript), it seems we should use different command to install it for different OS.

**Comment by BoPeng** [comment]
Please describe in detail the problems you have. But in general, we should avoid copying upstream installation instructions.

**Comment by BoPeng** [comment]
Henry, could you update our 'Running SOS" page and remove commands to install kernels? We should simply say, installing XXX following instructions from XXX, then ...

**Comment by HenryLeongStat** [comment]
>Please describe in detail the problems you have. But in general, we should avoid copying upstream installation instructions.

I followed the instruction in 'Running SOS" page for installing ijavascript. However, I failed to do that even though I try `sudo command` or changed to root to enter the command. When I checked the git repo of ijavascript, it showed that the process in our website is just for linux OS. And the one for mac (or Windows) is different. Not sure whether they updated it after the instructions of our website or before...

 >Henry, could you update our 'Running SOS" page and remove commands to install kernels? We should simply say, installing XXX following instructions from XXX, then ...

OK! Will do it now!
