### ISSUE TITLE
Docker commands cannot redirect stdout and stderr to files

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#945]
Here is a MWE:

```
[1]
run: docker_image="gaow/gatk3", stdout = False, stderr = False
   java -jar /opt/GenomeAnalysisTK.jar -T RealignerTargetCreator -h
```

The docker images is about 50mb to download. Then I expect to see nothing because i redirected the stdout and stderr. But I still see them. In practice I want to keep these info in log file. Currently it is not possible with docker.

**Comment by BoPeng** [comment]
Docker script is executed in a completely different manner and these options currently do not apply.

Let me see if `stdout=False` and `stderr=False` can be easily supported.

**Comment by BoPeng** [comment]
Please test.

**Comment by gaow** [comment]
Works great -- I was able to redirect the streams to files.
