### ISSUE TITLE
file_target vs path in "depends"

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#946]
I have this MWE that works:

```
[global]
src = file_target("main.R")

[scripts_download: provides = src]
run: expand=True
  touch {src}

[1]
depends: src
run:
  echo 1
```

However if I change `src` to `src = path('main.R')` it fails:

```
$ rm -f main.R
$ sos run test.sos
ERROR: Unknown target to match: main.R
```

Is this a feature or bug?

**Comment by BoPeng** [comment]
In theory, `provides` only accept a string (for patten matching), or a target (exact match), and `path` is neither or them. Let me see if I can at least produce a better error message.

**Comment by gaow** [comment]
> provides only accept a string (for patten matching), or a target (exact match)

This is good to know and reads clear to me. It can be in the error message I guess :)

**Comment by BoPeng** [comment]
But it is "natural" to `provides` something that `depends` accepts. I have just allowed the use of `path` etc in `provides` although this might introduce some more corner cases.
