### ISSUE TITLE
Docker image not properly shutdown by keyboard `ctrl-c`

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#949]
Here is the MWE:

```
[1]
run: docker_image='gaow/stress'
  stress --cpu 6 --timeout 3m
```
   
Here is a screenshot of what I'm getting:

![2018-04-23-12-00-14_scrot](https://user-images.githubusercontent.com/917985/39141636-f6c008a4-46ed-11e8-95e5-f932a6ccddf3.png)

You see I've terminated the run but there is still `stress` instances. I had to additionally `killall stress` to end them all.

**Comment by BoPeng** [comment]
Yes, `Ctrl-C` does not kill docker image because the way docker is designed. This is I believe a long standing problem with docker, not just SoS.

**Comment by gaow** [comment]
I see. Indeed in docker it does not even kill anything (at least on SoS it kills the workflow). [Some posts](http://www.johnzaccone.io/entrypoint-vs-cmd-back-to-basics/) suggest that there is a way to set up the container to respond to `Ctrl-C` but it did not work for me. 

I guess i'll close the issue for now until there are follow ups.
