### ISSUE TITLE
`dryrun` get caught in infinite loop

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#950]
I've noticed this issue for a while but did not find a motivation to fix it until today: I've got asked by someone to provide pure scripts from my workflow, so I did a `dryrun`. But I got caught in an infinite loop. To reproduce, 

```
a=file_target('1.txt')

[out: provides=a]
output: a
run: expand = True
  touch {a}

[1]
depends: a
print('hi')
```

then `sos dryrun test.sos`. 

Not sure if this behavior is easy to fix ...

**Comment by BoPeng** [comment]
Yes, this is because the workflow continues when the file was not generated after the "execution". We have to clean up these things one by one for dryrun mode.

**Comment by gaow** [comment]
Somehow this conversation reminds me of discussions in the other project on how well we support `vtools export` ... In spite of my efforts to dockerize everything, I still got asked repeatedly by my R collaborators the question "why are we using workflows". It seems one major inconvenience is the difficulty for a novice 3rd party user to change behavior of a relatively sophisticated workflow in an alien environment (Jupyter). So I ended up using `dryrun` to output scripts after interpolation to allow people to prototype, then incorporate the changes back. I guess a good `dryrun` behavior is particularly relevant for "re-prototyping" some production codes, a user case we did not think much of before.

**Comment by gaow** [comment]
Indeed. Can it dryrun / touch in some "sandbox", though?

**Comment by BoPeng** [comment]
We could maintain a global list of touched files but do not really create these files, or record a list of touched files to clean after dryrun. Either is bulletproof.

**Comment by gaow** [comment]
You meant to say "neither"? The first approach reads more appealing. It is like a "sandbox" of unusable targets :)

**Comment by BoPeng** [comment]
The problem with the first approach is that it solves cases with `depends: new_file` but not user-code such as `os.path.exists(new_file)`.

**Comment by BoPeng** [comment]
https://vatlab.github.io/sos-docs/doc/tutorials/Execution_of_Workflow.html#dryrun-mode-12 for the first time clearly document what dryrun mode does... The last part (external task) is still a bit uncertain because how to handle placeholder result files on remote host is till uncertain.

**Comment by BoPeng** [comment]
This particular bug has been resolved.
