### ISSUE TITLE
Script variable to SoS variable

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#952]
I understand this could be a long shot, but is there any chance that a variable in the script can be exported to the SoS global variable list (or local to a step unless shared)? :P

**Comment by BoPeng** [comment]
Do you mean Python variables or variables from any script? Generally speaking you will have to use disk, something like

```
[10: shared='var']
python:
   var = whatever
   pickle.save(filename, var)
var = pickle.load(filename)
```

**Comment by gaow** [comment]
Yes I understand. I'm talking R variable as well, though ... and any language for that matter, considering we already have perhaps the core functionalities implemented in SoS Notebook, data communication in SoS Workflow sounds like a natual extension.

**Comment by BoPeng** [comment]
That is a totally different mechanism that takes advantage of the fact that both kernels are "alive" so that they can exchange variables through memory. This is a totally different case.

**Comment by gaow** [comment]
Yes I understand that too, but can that "alive" part be dealt with by providing language specific utility functions, eg:

```
[10: shared='var']
R:
   var = whatever
   sos_export(var)
var = from_R(var)
```

and we use disk to mimic memory?

**Comment by BoPeng** [comment]
There are two problems here:

1. Our communication is language dependent, that is to say, the "same" information passed from `sos` to `matlab` can be presented quite differently from `sos` to `R`. We will have to either use a "general" format (such as JSON) to make our presentation language-neutral, or expand the interface to something like `sos_export(var, to='R')`.

2. The recipient language needs to have this `from_sos` function defined somewhere, so the script will most likely something like 
```
library('sos')
var=from_sos(filename)
```
That means we will have to write modules for each language we support.

If we do not want to support two sets of mechanisms, we can implement these modules and let the language modules use this mechanism as well. Other than performance losses, we will at least lose the feature of direct variable transfer between subkernels (not by way of sos).

**Comment by BoPeng** [comment]
But in general I agree that developing a **general** solution for variable exchange among languages can be an appealing feature and can expand the user-base of sos greatly. I mean, people can use `sos_import` and `sos_export` in their scripts without using sos, even if these functions are simple wrappers of native functions.

On the other hand, whereas in-memory data exchange in sos is transient and can be changed/improved freely without affecting user interface, these on-disk files are more likely to be used in a less transient manner, which will require much more complex implementation in general. Whereas this feature is well within the scope of "SoS", it would have to be planned and implemented very carefully, with perhaps support from a major grant.

**Comment by gaow** [comment]
Yes ... when I said "core features needed are implemented in SoS Notebook" I was referring to the data-type mapping between languages, not exactly how they are communicated. We certainly do not want to lose the advantage of in-memory data transfer at least for now. So indeed as you said, two mechanisms will have to be maintained here. We can revisit this when there is proper resources to do it. I'll keep this in mind!

**Comment by BoPeng** [comment]
I think the key difference between sos and other mechanisms such as JSON is the "neutrality". Where as data exchange using a common file format (e.g. JSON or extension of JSON) is much easier to implement, it can not be optimized for large datasets (e.g. huge dataframe) and can not accommodate language-specific datatypes (e.g. series vs named tuples). SoS sacrifices neutrality and requires the specification of "from" and "to" languages, but allows a de-centralized implementation of "type A of language B" to "type C of language D".  However, in practice, there are certainly many cases where users knows the from and to languages and would be willing to specify such information in exchange for lossless (meaning less, not no) data exchange. Implementation-wise, as soon as we define a common interface, the implementation can be separated into numerous small and independent functions that could be implemented gradually.

So I do think this is valid project that can be of interest to a large audience.

**Comment by gaow** [comment]
Yes! I share your view and I do feel a strong need of it. I may even manage to grab some attention from my surroundings that at least could justify some of my own efforts to it. Will follow it up with you via DM.

**Comment by BoPeng** [comment]
Could be tentatively named "SoS data exchanger". :smile:

**Comment by BoPeng** [comment]
And new logo word. SoS: bridging languages.

**Comment by gaow** [comment]
Moved to #953
