### ISSUE TITLE
The SoS Data Exchanger project

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#953]
Separate from #952 , this ticket keeps discussion on some thoughts on SoS Data Exchanger. The general idea is to use a neutral interface for all languages, with implementation details broken down to various functions that can be added incrementally in time. This is different design from using some intermediate common file formats, say JSON or HDF5, where there will be loss of information and performance issues.

**Comment by BoPeng** [comment]
Moved to vatlab/sos-dataexchanger#1
