### ISSUE TITLE
SoS error message improvements

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#954]
I've got feedback recently that the error messages we generate are not very easy to view (in fact they got daunted when seeing them and refused to read carefully ... ). There are 2 problems:

1. The trace-back information is long and distracting outside the context of [an interactive environment](https://github.com/vatlab/SoS/issues/867). 
2. Information from `docker` runs failed to point to where stderr files are kept.
3. Additionally for `task` the error info seems redundant and confusing. 

To elaborate, see MWE below for 1:

```
[sra (dump SRA to fastq): provides=['{data}_1.fastq', '{data}_2.fastq']]
output: f'{data}_1.fastq', f'{data}_2.fastq'
#task: workdir = '/tmp'
run: docker_image = 'gaow/debian-ngs', expand=True, stderr='/tmp/1.err', stdout='/tmp/1.out', workdir = '/tmp'
    fastq-dump -I --split-files {os.path.basename(data)}
```

and run:

```
sos run test.sos -t SRR001_1.fastq SRR002_1.fastq
```

Here is the output, red and daunting.

![2018-04-28-07-23-06_scrot](https://user-images.githubusercontent.com/917985/39396505-09d97d74-4ab5-11e8-9dca-a53b2d8d500e.png)

So for my point 1 above, I think here the `Traceback` info is completely unnecessary. We added it for #867. But is there a way to get rid of it here for runs from step actions? The `RuntimeError: Executing script in docker returns an error (exitcode=3 ..... ` is more than enough.

For my point 2 above, I can improve it and report back here. I'll come back to my point 3 above when these two are fixed first.

**Comment by gaow** [comment]
For 1, it makes sense to still have "Syntax Error" and those error that comes from non-action SoS codes. But can we raise a different type of error for actions, and skip their traceback (because they are not helpful) in the output?

**Comment by gaow** [comment]
Just submitted a patch to change the message to using green colors and report `stderr` file location if they exist:

![2018-04-28-07-44-06_scrot](https://user-images.githubusercontent.com/917985/39396664-ffed4a04-4ab7-11e8-8076-f203d5f32c40.png)

Still it would be nice to remove the unnecessary trackback info for the case of SoS actions.

**Comment by BoPeng** [comment]
I am more concerned about duplicate message. It appears that one is printed at step level, another one printed at the workflow level.

**Comment by BoPeng** [comment]
No. This is not the case. The message is printed twice because the step is called twice.

**Comment by BoPeng** [comment]
Why do you say the trace back is not important for sos actions?

**Comment by gaow** [comment]
Yes the step are called twice so there is no duplicate. 

> Why do you say the trace back is not important for sos actions?

I should say that `RuntimeError` (or more specifically in the case of `ret != 0`, this very specific type of error) in actions should not report trace. Because it is wordy and redundant -- all the info, and more, are also raised in the actual error message. For example currently:

```
ERROR: [sra ['SRR_1.fastq']]: 
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
script_-7594117775864177549 in <module>
      run(r"""fastq-dump -I --split-files {os.path.basename(data)}
----> """)

RuntimeError: Failed to execute commmand "/bin/bash -ev /tmp/tmpswhu8nto.sh" (ret=2, workdir=/home/gaow/tmp/28-Apr-2018, script now in /home/gaow/tmp/28-Apr-2018/.sos/sra_0_672e66db.sh, err=/tmp/test.err)
```

The trace info is not informative because it is not useful to debug or reproduce. Instead one should really focus on the mentioned temp script and the `err` file to find out what is going on. Because the error is not about workflow specification, it is about `fastq-dump` went wrong. Having the trace there is distracting. However it is otherwise useful, for example for any other error not in the `subprocess` call, eg, if I mess with the script I get trace info before the run:

```
ERROR: Failed to execute script: [Errno 21] Is a directory: '/tmp'
ERROR: [sra ['SRR_1.fastq']]: 
---------------------------------------------------------------------------
IsADirectoryError                         Traceback (most recent call last)
script_2345474589931989838 in <module>
      run(r"""fastq-dump -I --split-files {os.path.basename(data)}
----> """, stderr='/tmp')

IsADirectoryError: 21

```

that is, I specified `stderr='/tmp'` which is a folder, and it is my bad SoS code. Then it makes to raise trace error (though it is not super helpful in this case..). 

My point is, that we should have a clear distinction of action error -- which is typically outside of scope of SoS, and coding / syntax error -- which reports trace and ask users to fix. To me also I find trace usually means a bug in code, so displaying a trace error when in fact there is no error in the code per se is also distracting. That's also why I got the complaint that "I cannot understand the error message" even when we are perfectly clear that they should run some command or look at some log file to reproduce!

**Comment by BoPeng** [comment]
Try now.

**Comment by gaow** [comment]
Great! it is a lot better now, but I'm wondering for something like this:

```
ERROR: Failed to execute script: Command 'Rscript /tmp/tmp2emm8l1e.sh' returned non-zero exit status 1.
```

Maybe we don't show them, or show something more informative instead (eg step name)? Because this file in question is no longer available immediately after the step quits ...

**Comment by BoPeng** [comment]
You decide. I need to run some errands now. Note that that message at least shows interpreter and options, which is not always clear with script action and args stuff.

**Comment by gaow** [comment]
Thanks! I'll play with it a bit more. Happy weekend and see you later!

**Comment by gaow** [comment]
Okay the behavior looks good to me now. And you actually also has addressed to my concern 3 above even though I have not reported it! Hopefully new users will find their way easier now.

**Comment by gaow** [comment]
@BoPeng not sure about release cycle,s but is it possible to create a bug fix release with this feature and the fix of the hang behavior so that people can upgrade easily?

**Comment by BoPeng** [comment]
That is easy. Done. Also released sos notebook due to the fix of broken `%run` magic.

**Comment by gaow** [comment]
Great, thanks a lot!
