### ISSUE TITLE
Pickle module object error

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#955]
I ran into a weird problem today. Here is the MWE:

```
print('global_loaded')

[default]
parameter: option = [1, 2]
input: for_each = ['option'], concurrent = True
output:['1.txt', '2.txt'], group_by = 1
if os.path.isfile(f'{_output:n}.stderr'):
	open(f'{_output:n}.stderr', 'w').close()
if os.path.isfile(f'{_output:n}.stdout'):
	open(f'{_output:n}.stdout', 'w').close()
bash: expand = True, stderr = f"{_output:n}.stderr", stdout = f"{_output:n}.stdout"
  echo hello > {_output} 
```

When I run it:

```
$ sos run test.sos 
global_loaded
global_loaded
global_loaded
global_loaded
global_loaded
INFO: Executing default_0: 
INFO: input:   []
ERROR: [default_0]: can't pickle module objects
```
So 2 questions:

1. Why is global section loaded 5 times? Is that necessary?
2. The error in the end -- "can't pickle module objects"

**Comment by BoPeng** [comment]
Should have been fixed.

I now prefer `path` operations like
```
_output.with_suffix('.stderr').exists()
```

**Comment by gaow** [comment]
Great! Good call on the `with_suffix`, thanks a lot!

**Comment by gaow** [comment]
But I am curious what particular variable has caused the pickling issue? Also I think I've asked it before, but I'm still trying to wrap my head around why global section was evaluated exactly 5 times.

**Comment by BoPeng** [comment]
It is the `os`, which was identified as a potential signature variable. It was excluded in other places but somehow included in the signature for `subprocess.Pool` stuff caused by `concurrent=True`.

**Comment by BoPeng** [comment]
The evaluated `5` times stuff is because sos execute steps on different workers (subprocesses) and each of them would execute `global` to get the global variables. The building of DAG also evaluates it during the analysis of steps.

I cannot load it once and pass it around because the global section can import modules and modules cannot be pickled.
