### ISSUE TITLE
Server configuration to by pass "Are you sure you want to continue"?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#956]
From our JupyterHub installations, users can log to other servers with configurations stored in the `site_config.yml` or `~/.sos/hosts.yml` files. However, before connecting any other host, users would need to log in to the JupyterHub server, ssh to the host, and enter `yes`. 

```
$ ssh remotehost
The authenticity of host 'xxx' can't be established.
RSA key fingerprint is SHA256:xxxx.
RSA key fingerprint is MD5:xxx
Are you sure you want to continue connecting (yes/no)? yes 
```
Is there anyway to bypass this step?

**Comment by ChrisWakefield** [comment]
See: 
https://serverfault.com/questions/29262/how-to-manage-my-ssh-known-hosts-file?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
