### ISSUE TITLE
User .bashrc on JupyterHub server

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#957]
I noticed that every user has the following `$PATH` on the JupyterHub server

```
/usr/local/bin:/usr/local/share/anaconda3/bin:/sbin:/bin:/usr/sbin:/usr/bin
```

which most interpreters installed under `/usr/local/share/anaconda3/bin`. 

There are two problems:
1. There is no path to applications such as `samtools`.
2. There is no way for users to add their own `module load` or `PATH` to self-installed tools.

**Comment by gaow** [comment]
Which server are you talking about? The docker based one on our website? [This post](https://github.com/vatlab/SoS/issues/951#issuecomment-384139351) might be useful in mapping such paths and set permissions right

**Comment by BoPeng** [comment]
We have set up a JupyterHub server within the department so that all users can connect to it, start a Jupyter session and use sos (and other installed languages) there. It is experimental and this is one of the problems we have.

Perhaps I should create a separate (private) repo for related issues.
