### ISSUE TITLE
Kill sos tasks without having to specify queue

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#959]
I noticed that on the headnode of the institutes cluster quite a few instances like this:

```
 7559 ?        00:00:00 sos <defunct>
```

The problem is that I've not idea which job / queue it came from. The only way out seems to be `killall sos`. 

Is there a grace way to do this with `sos kill --all`? As I mentioned, the problem is I do not know which queue these processes come from and I just want to get rid of them all.

**Comment by BoPeng** [comment]
`sos kill --all` should kill task related processes (if it can) but there is no evidence that these processes are related to any task, right?

**Comment by gaow** [comment]
Okay if in principle `sos kill --all`, just like `purge`, can remove all tasks regardless of queue then I'm good with that. My trouble is that I do not think it worked until I dug into it and added `-q` ... but this may well be a headnode artifact, or because somehow something is still being submitted to the cluster from my office desktop. I just want to verify the behavior -- are you sure about it? I'll test some more and report back if that is not the case.

**Comment by gaow** [comment]
I was hoping to try it out this week on my data applications but seems we have more data issues that requires fixes outside SoS application. So sorry let's keep this ticket open for an extended period until hopefully later next week i can get to batch job submissions.

**Comment by gaow** [comment]
We shouldn't see `defunct` anyways if everything works well. I havent seen one of those in a while so maybe this issue has been resolved at this point.
