### ISSUE TITLE
Advanced return status check

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#960]
A colleague of mine challenged me with this situation:

```
[1]
output: 'test.txt'
bash:
  bash sleep.sh &
```

where `sleep.sh` has 

```
sleep 20
touch test.txt
```

Checking return code for `subprocess` is not enough in this case. But I suspect we already can handle this in principle: for our memory check code, do we recursively check for child processes eg [some memory check code](https://github.com/gaow/misc/tree/master/monitor) from stackoverflow. This is just food for thought, not suggesting any fixes to this deliberate sabotage.

**Comment by BoPeng** [comment]
Technically speaking the outer `bash` completed (without the intended output file). While we can check if all subprocesses have been killed in this case, I cannot help thinking if there are valid uses of firing background processes from scripts.

**Comment by gaow** [comment]
That is also very true. So a proper check is difficult though might still be doable. I'm cool to close this ticket any time you want.

**Comment by gaow** [comment]
My colleague has pointed to me that snakemake has these commands:

```
 --keep-going, -k      Go on with independent jobs if a job fails.
  --latency-wait SECONDS, --output-wait SECONDS, -w SECONDS
                        Wait given seconds if an output file of a job is not
                        present after the job finished. This helps if your
                        filesystem suffers from latency (default 5).
```

Not sure what happens under the hood -- adjust DAG in case of failure? It seems like a neat feature that at least keep things moving along.

**Comment by BoPeng** [comment]
I believe we do `--keep-going` by default. `--latency-wait` is designed for another matter that we have not experienced, not for the case you brought up.

**Comment by gaow** [comment]
> I believe we do --keep-going by default.

Ah now it is true statement after we fixed the hang bug over the weekend. I got too absorbed in the error messages of failures though and forgot about what really matters:) 

I was being lazy creating another ticket for the delayed error stuff but I thought that'd be something we can keep track of.

**Comment by BoPeng** [comment]
`--latency-wait` is very easy to implement because it only happens when the output file could not be found. However the snakemake dicussion list is the only place I heard the need of such a feature (some users reported that their cluster file system has this issue).

**Comment by gaow** [comment]
Yes that immediately reminds me of the genotype loader for `vtools associate` where we try 5 times on `sqlite.operational` error before throwing exceptions.
