### ISSUE TITLE
SoS went zombie on cluster

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#961]
The symptom is that the SoS process still appear to be running, but it stopped submitting jobs many hours ago yet did not quit. I keyboard killed it, and tried to kill all tasks on the headnode before starting afresh, I get this:

```
[MW] sos kill --all
ERROR: can't start new thread
[MW] sos kill --all -v4
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/site-packages/sos/__main__.py", line 2322, in main
    args.func(args, workflow_args)
Traceback (most recent call last):
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/site-packages/sos/__main__.py", line 2322, in main
    args.func(args, workflow_args)
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/site-packages/sos/__main__.py", line 1237, in cmd_kill
    kill_tasks([])
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/site-packages/sos/tasks.py", line 1099, in kill_tasks
    p = Pool(len(all_tasks))
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/multiprocessing/pool.py", line 789, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
RuntimeError: can't start new thread
ERROR: can't start new thread
```

If I check for the processes, I get
```
[MW] ps -A | grep sos
 7534 ?        01:18:18 sos
 7559 ?        00:00:00 sos <defunct>
```

Then I manually `kill 7534` and removed all `sos`, then I did `sos kill --all` again, still got that error. I can dig deeper, but I cannot think of how to get a MWE here. Does the error message mean something?

**Comment by BoPeng** [comment]
Never saw that error. So the sos process is supposed to continue submitting jobs? Is it because there were already max running jobs running so sos was waiting for the completion of tasks?

**Comment by gaow** [comment]
>  Is it because there were already max running jobs running

Not according to my `ps -A` result. There is just 2 `sos` running. I had specified `-J 40` so I should say 40, right?

> the sos process is supposed to continue submitting jobs?

I was not so sure if all jobs are complete. I just started a new run, and I see that it does seem every job was in fact ignored and it does seem all jobs are complete. But I still get a hanging screen that looks like this:

```
...
INFO: coef_err_0 (index=996) is ignored due to saved signature
INFO: pred_err_0 (index=999) is ignored due to saved signature
INFO: coef_err_0 (index=997) is ignored due to saved signature
INFO: coef_err_0 (index=998) is ignored due to saved signature
INFO: coef_err_0 (index=999) is ignored due to saved signature
INFO: output:   [file_target('finemap/pred_err/en_sim_1_en_1_pred_err_1.rds'), ...] (1000 items)
INFO: output:   [file_target('finemap/coef_err/en_sim_1_susie_1_coef_err_1.rds'), ...] (1000 items)

``` 

So it does not read like complete message, right? (usually at the end of execution it should say something like "workflow successfully executed"). And now the sos process from `ps` command is

```
[MW] ps -A | grep sos
15816 pts/19   00:00:43 sos
```

So the symptom is just SoS refuses to quit when it should. Does it look like a hang again? How can I tell that? I was under the impression that for remote tasks we do not use file locks.

**Comment by BoPeng** [comment]
Cannot really tell what is going on from these message. Let me check the code tomorrow.

**Comment by gaow** [comment]
Oh I'm sorry I was perhaps saying that too soon. Now after quite a while of hanging it started to submit jobs again, so apparently my jobs have not finished yet when I killed what I thought was a hang earlier. It might just be a jam on the headnode, for a couple of hours? So we are just down to one issue, the `sos kill --all` behavior. Not sure how to reproduce that reliably though.

**Comment by BoPeng** [comment]
It seems to be problem with killing pending tasks, in which case the pending tasks are not killed but sos cannot run it either.

```
[bpeng1@BCBMC07MX084DY3:~]$ sos status 5c63c4a244acf1bd
5c63c4a244acf1bd	04505b3affdd6b0b default_1	   1 min 46 sec	pending
[bpeng1@BCBMC07MX084DY3:~]$ sos kill 5c63c4a244acf1bd
5c63c4a244acf1bd	cancelled
[bpeng1@BCBMC07MX084DY3:~]$ sos status 5c63c4a244acf1bd
5c63c4a244acf1bd	04505b3affdd6b0b default_1	    2 min 5 sec	pending
```
and sos hangs.

**Comment by BoPeng** [comment]
sos should now work better with pending tasks killed from outside.

**Comment by gaow** [comment]
Great! will give that a go and report back. But maybe not in a while as my jobs were completed and i need time to process results. I'll close this for now and reopen when there is an issue.

**Comment by BoPeng** [comment]
Just note that there are two scenarios:

1. If a queue is specified, then sos can ask the queue to cancel all pending jobs.
2. Otherwise sos can only kill submitted jobs. The task engine will continue to send pending jobs until they are all canceled. This is the case, for example, for killing jobs on a remote host (cluster) with tasks sent from another machine.

**Comment by gaow** [comment]
Have to re-open this one, because 

1. `sos kill --all` still gives error message `ERROR: can't start new thread`.
2. when a queue is specified:

```
sos kill --all -q midway2 -c results3.queue.yml 
WARNING: Please specify task id, or one of options --all and --tags
```

Is there a better way to get rid of those `pending` tasks? I think it is choking the queue, and is confusing particularly when `ps -A | grep sos ` shows nothing.

**Comment by gaow** [comment]
The 2nd error actually took very long time to get. But by looking at the source code I could not understand why it happens. ...

**Comment by BoPeng** [comment]
I know what happens. The command passes the options to the task engine, which kills the tasks internally (e.g. `pbs kill` after clearing internal data), and fire a command that local to the remote host to kill commands externally. The mechanism to pass `--all` to remote host somehow failed.

**Comment by BoPeng** [comment]
Could you try again? `--all` is dangerous for remote hosts because it might contain tasks submitted from another host. I guess this is why I ignored `--all` with `--queue`. Anyway, the patch tried to fix this and please test.

I still cannot reproduce 1, but let us focus on 2 first.

**Comment by gaow** [comment]
Great! I'm running it. Takes long time and no message even with `-v4`. I was not sure what it is doing until you've confirmed it (some heavy-duty `pbs kill` going on). Would be nice to add some progress message? It is still processing as we speak.

**Comment by BoPeng** [comment]
This patch is wrong and has been reverted. Basically the underlying `sos kill` command has to be run at default verbosity level because `PBS` relies on the output of this command to run `pbs kill` etc.

Not sure why you do not see anything with `-v4` though because the task engine should output at least [this line](https://github.com/vatlab/sos-pbs/blob/master/src/sos_pbs/tasks.py#L273). Still checking.

**Comment by gaow** [comment]
Okay here is what happened after a long wait:

```
$ sos kill --all -q midway2 -c benchmark.queue.yml

ERROR: can't start new thread
WARNING: Check output of sos kill   -a failed: Command 'sos kill   -a' returned non-zero exit status 1.
ERROR: Failed to kill task []
```

I just pulled the patch above and I'm rerunning with `-v4`. I'll report back screen output.

**Comment by BoPeng** [comment]
No that patch was reverted... ( I numbered that patch as 691)

**Comment by gaow** [comment]
Now seem to be working -- got lots of these.

```
DEBUG: Running scancel 45664854
DEBUG: Running scancel 45634835
DEBUG: Running scancel 45669298
DEBUG: Running scancel 45653102
DEBUG: Running scancel 45639868
DEBUG: Running scancel 45662468
```

and it goes on and on (still running as we speak). But I do not understand this: there are no jobs in my queue at all. It feels like SoS task managing and PBS are not in sync somehow?

**Comment by BoPeng** [comment]
So the command to kill your job is `scancel ID`? `sos` just tried to kill all jobs with the job ID, regardless of its existing status, because sos status and pbs status can be out of sync.

**Comment by BoPeng** [comment]
This is why `--all --queue` was not recommended because a cluster can have many many jobs.

**Comment by gaow** [comment]
Oh okay but these jobs are all mine, right? They are all jobs I submitted from the past? I wanted to use `--all --queue` just for a clean up of jobs that possibly created a hang. I was initially trying to see what they are by `sos status -s pending`, but it took too long to show so I decided to run a clean-up after all.

**Comment by BoPeng** [comment]
`sos status` can be slow because sometimes `sos` needs to wait for the updates (non-updates) of pulse files to determine if a job is running, and if it has to check all jobs to find the pending ones...

I think at least the `scancel` thing can be skipped for jobs that are marked failed or complete. This could help a lot, I think.

**Comment by BoPeng** [comment]
OK. update `sos-pbs` and try again.

**Comment by gaow** [comment]
Great -- it took some time to check, but I finally got to the point that no `scancel` is called. However at the end of the command:

```
M2_00068dd41cf149d7	completed	M2_001115655c8717d0	completed	M2_001145efb2500134	completed	M2_0012bb0a1ba5b8b6	completed	M2_001979da09d61da4	completed	M2_001b01b19db6671d	completed	M2_001baa80cab273a5	completed	M2_001c31a5db4bb5d0	completed	M2_001ddce33688554b	completed	M2_001ef69ffac19a02	completed	M2_00250867a1c4919f	completed	M2_002776256d1eff9c	completed	M2_002b65b7d93dd6c2	completed	M2_002bc6fc91446dd6	completed	M2_00306b27c350c4db	completed	M2_0038032a78256d9e	completed	

```

Missing `\n`?

**Comment by BoPeng** [comment]
Fixed (forgot to cross-link). Sorry for the rush, I have been preparing a talk on sos on Wednesday.

**Comment by gaow** [comment]
No problem. Sorry to have bugged literally. Nothing urgent so please prioritize on the talk. I hope all goes well and we can talk more about it later!

**Comment by BoPeng** [comment]
It is ok. I depend on you to iron out winkles in areas that I rarely touch and you have done a great job there. For example, I have fewer larger jobs and I usually cancel/kill them from notebook by clicking the cancel button.
