### ISSUE TITLE
pulse file created in the future.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#962]
Got the following warning when executing a task on a remote host.

![image](https://user-images.githubusercontent.com/9889312/39611311-66d8386a-4f1c-11e8-8609-a84f57258295.png)

The warning is caused by [this line of code](https://github.com/vatlab/SoS/blob/master/src/sos/tasks.py#L731)

```
        start_stamp = os.stat(pulse_file).st_mtime
        elapsed = time.time() - start_stamp
        if elapsed < 0:
            env.logger.warning(
                f'{pulse_file} is created in the future. Your system time might be problematic')
```
According to [this post](https://unix.stackexchange.com/questions/111877/timestamp-of-newly-created-file-is-in-the-future), the files could be generated on the remote host that has different time than the local host. Not sure how this happens but 

1. Should we compare time between two servers and sync their times?
2. Can sos somehow addresses this warning?

**Comment by gaow** [comment]
I've seen this type of message with Make, something like "clock skew". I guess computing the difference in advance (in terms of linux epoch time) and apply this `delta` in that line of code should fix it?

**Comment by BoPeng** [comment]
So I am thinking if we should reduce the warning to debug for this case, and change the 'aborted' condition from 10 seconds to some longer interval, which means it will take sos longer time to confirm aborted tasks.

**Comment by BoPeng** [comment]
In theory we can define a "lag" in host definition but there is usually no fixed "lag". I guess it is enough to change warning to debug and hope nothing can go seriously wrong.
