### ISSUE TITLE
Change of log option stdout / stderr triggers rerun

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#963]
A MWE:

```
[1]
output: "1.txt"
run:  stdout = '1.out'
  echo hi > 1.txt
  echo finished
```

and run it twice:

```
$ sos run test.sos
INFO: Executing default_1: 
INFO: input:   []
echo hi > 1.txt
echo finished
INFO: output:   [file_target('1.txt')]
INFO: Workflow default (ID=280e8ea7fe33e40f) is executed successfully.

$ sos run test.sos 
INFO: Executing default_1: 
INFO: input:   []
INFO: default_1 (index=0) is ignored due to saved signature
INFO: output:   [file_target('1.txt')]
INFO: Workflow default (ID=280e8ea7fe33e40f) is executed successfully.
```

all look good. Then I change the script simply removing `stdout='1.out'`, and rerun:

```
$ sos run test.sos
INFO: Executing default_1: 
INFO: input:   []
echo hi > 1.txt
echo finished
INFO: output:   [file_target('1.txt')]
INFO: Workflow default (ID=2abd9038377506b3) is executed successfully.
```

then the existing files no longer get skipped. 

I'm not sure which of these variables goes to the step signature, but I'd argue that perhaps not `stdout` and `stderr` since they are like debug switches that we may want to have them on when trying things out, but silence them when we are done testing -- in that case we do not want a rerun due to such a nuisance change.

**Comment by BoPeng** [comment]
What triggers the re-run is the change of the content of the step, so we cannot do much unless we let sos dig into the code and explicitly detect and exclude these options.

**Comment by gaow** [comment]
Okay ... but why digging? are they stored in a dictionary that can be easily `del` or `pop` before evaluating for step contexts? Sorry I just want to clarify.

**Comment by BoPeng** [comment]
We [extract tokens](https://github.com/vatlab/SoS/blob/master/src/sos/parser.py#L394) from statements after `input:`. It is a bit difficult to detect and remove `stdout` and `stderr` etc because sos will need to parse `func(....., stdout=, stderr=)` while `func` does not have to be sos actions.

**Comment by gaow** [comment]
I see ... so any changes in that statement will trigger a rerun? It certainly makes sense for things like `args`, though not like `stdout`. That means we should avoid using absolute paths there as much as possible? and that makes `sos pack` difficult, too? I'm okay with the behavior if there is no easy fix. Just want to be sure it is not a bug.

**Comment by BoPeng** [comment]
There is a thin line here between clever and overly clever. The tokenizer would ignore spaces and comments and that is about it. For `stdout`, another scenario would be you want to see stdout from screen to debug the script, and then you like to keep the results to some files for later reference, and it can be frustrating that sos refuses to re-run.
