### ISSUE TITLE
Slowness building DAG with step dependencies

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#968]
I'm having trouble running a not very large benchmark generated by [this DSC configuration](https://github.com/stephenslab/dsc-reg/blob/master/benchmark.dsc). Here is the [benchmark.tar.gz](https://github.com/vatlab/SoS/files/1993366/benchmark.tar.gz). Notice that the `default` step has a large number of dependencies going on ... I guess large scale implicit style is always under tested, but this is how I see that a benchmark be built efficiently to achieve best parallel runs. So how can we optimize it here? and is there any suggestions of alternative implementations, based on looking at the SoS script, to improve the structure of a benchmark?

In fact this comes from a medium sized benchmark we've compiled. To elaborate the problem a bit more: it is kind of like the multi-style example in the SoS manuscript that we have 7 types of simulations, 10 methods to compare and each comparison generating 2 values to measure the differences. The script is written in outcome-oriented style based on step dependencies. You can imaging for each step we can allow for running multiple replicates (not the case here; that's why the comment "not very large"), but that will not add to the DAG complexity because it is using step dependencies. I suspect for this case it might be faster to use file target dependencies. But we cannot always expect it.

**Comment by gaow** [comment]
Now I implemented this version: [test_path_dep.sos.txt](https://github.com/vatlab/SoS/files/1993495/test_path_dep.sos.txt) that is outcome-oriented but based purely on `path` target. The DAG parsing seem to happen within seconds, but it gives weird error message about missing workflow steps, and the execution order is not right, so apparently the DAG was not properly created. I'm not sure if it is my bad script or an SoS bug. I'll try to come up with a MWE, if it is hard to tell from that actual code I ran.

**Comment by BoPeng** [comment]
Not sure what the problem is but you can keep the ticket open till I get some time to see it. Right now I am busy with `sos remote --test`.

**Comment by gaow** [comment]
No worries. I'm glad to see developments on the remote computing! In fact there are some sensitive data that I will have to process soon elsewhere outside my favorite cluster, so I'll be thrilled to try out the JupyterHub development!

This ticket has a very big example, and it actually carries mixed message: 1) a corner case with SoS that hangs the DAG step, and 2) discussion on the best way to use outcome-oriented style. I think for 1) I should create a MWE, and for 2) I should use a separate ticket and come with a smaller example. So I think it will save your time if close this one for now, and use 2 other separate tickets with better MWE to keep the discussions more efficient.
