### ISSUE TITLE
Improper step name causes DAG to hang with `sos_step` target

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#969]
This is a generated fake benchmark example, a cleaner version of #968 : 

[dag_hang.tar.gz](https://github.com/vatlab/SoS/files/1995111/dag_hang.tar.gz)

There are 2 files in it: `hang.sos` and `not_hang.sos`. To reproduce the hang:

```
sos run hang.sos
```

and SoS gets caught in infinite loop. But 

```
sos run not_hang.sos
```

works. The only difference between the two is step name: `test_01` in the hang one, and `test01` in the no hang one. 

As pointed out in #968, there is also a problem when changing the target to using file target. But maybe fixing this problem will lead to fix of that one, so let's focus on this one for now and I'll try reproducing the file target version bug after this one is addressed to.

**Comment by BoPeng** [comment]
The reason was the sos disect `b_test_01` to `b_test` and `1` and compare it with step `b_test_1`.
