### ISSUE TITLE
Current `master` broken?

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#981]
This ticket #979 posts the [benchmark](https://github.com/vatlab/SoS/files/2076295/benchmark.tar.gz) test, but it is broken in the current `master` of SoS:

```
$ sos run benchmark.sos 
ERROR: Defined output fail to produce expected output: first_investigation/abs_err/normal_1_mean_1_abs_err_1.rds generated, sos_step("a_abs_err") expected.
```

**Comment by BoPeng** [comment]
Yes, as I have mentioned in another thread. The entire internal structure has been revamped to use `sos_targets`. All tests passed but we do not have great test suite...

Will try to fix this soon.

**Comment by BoPeng** [comment]
Please confirm if it works.

**Comment by gaow** [comment]
It seems to be working now at least for that example, thanks! I"ll report more failures when I run into them.

**Comment by gaow** [comment]
I guess it is related to this issue?

```
INFO: Workflow default (ID=0ffbecfb502e5db8) is executed successfully with 8.025641025641026 completed steps, 9 completed substeps, 3.9743589743589745 ignored steps and 46 ignored substeps.
```

the number of steps are not integers now. Do you need a MWE or is it an obvious fix?

**Comment by BoPeng** [comment]
Well, it is because a small portion of the substeps are skipped so the overall "completed" is fractional. Obviously the presentation could be improved though.

**Comment by gaow** [comment]
Unfortunately, I think current master is still broken -- it no longer skips completed steps in my benchmark workflow template. Here is the MWE:

[14-Jun-2018.zip](https://github.com/vatlab/SoS/files/2104662/14-Jun-2018.zip)

To reproduce:

```
sos run benchmark.sos
sos run benchmark.sos
```

Supposedly the 2nd run should skip everything. But it does not. This seems to be related to step target dependency because other workflow styles seems okay.

**Comment by BoPeng** [comment]
Well, I can only say that the internals were changed for the better. :smile:

**Comment by BoPeng** [comment]
`sos_step` should not be in signatures, but they would not cause any harm either. The script still does not skip steps with the patch, and I see the change of `benchmark/median/normal_1_median_1.rds`

```
BCBMF5KWK0F8F69:Downloads bpeng1$ md5 benchmark/median/normal_1_median_1.rds
MD5 (benchmark/median/normal_1_median_1.rds) = 10d197f92541031ad26dfd840acbe14d
BCBMF5KWK0F8F69:Downloads bpeng1$ md5 benchmark/median/normal_1_median_1.rds
MD5 (benchmark/median/normal_1_median_1.rds) = 4420638a66b5f9b0faa7c7bde0fd21c2
```
between runs...

**Comment by gaow** [comment]
Hmm this must be what triggers the rerun. But sorry I do not get why it is the case because there is no randomness going on in the relevant part of the code ... and it used to work.

**Comment by BoPeng** [comment]
I am examining the context handling code. I think the file signature difference might be caused by R, just like python does not guarantee the order of dictionary keys when they are saved...

**Comment by gaow** [comment]
I see ... but on a second thought, if the input, parameters and scripts are the same then it should not matter, right? It is an interesting find though. 

R list are ordered. But not sure if there are other underlying issues. A simple test of `saveRDS` suggests the objects I saved were identical. Also rerunning the pipeline on my end, I get 

```
gaow@trico:~/tmp/14-Jun-2018$ md5sum benchmark/median/normal_1_median_1.rds 
f3b8b34b6539d91bf0a1eec3691ded3d  benchmark/median/normal_1_median_1.rds
gaow@trico:~/tmp/14-Jun-2018$ md5sum benchmark/median/normal_1_median_1.rds 
f3b8b34b6539d91bf0a1eec3691ded3d  benchmark/median/normal_1_median_1.rds
```

that is, signature is identical on my end ..?

**Comment by gaow** [comment]
@BoPeng seems the latest patch solves it. Is the fix complete? 

But RE the md5 I've got an interesting follow up. Please find the new benchmark test data below:

[15-Jun-2018.zip](https://github.com/vatlab/SoS/files/2107128/15-Jun-2018.zip)

There are 2 scripts, `benchmark-task.sos` and `benchmark-nontask.sos`. The difference is:

```diff
< task:
---
> 
70c70
< task:
---
> 
96c96
< task:
---
> 
124c124
< task:
---
>
```

and if I run the non-task version first followed by the task version:

```
sos run benchmark-nontask.sos
sos run benchmark-task.sos
```

then there are 2 issues:

1. the non-task version's outcome were not skipped. 
2. at the end of the task version there comes an error message prompt:

```
ERROR: File changed test/median/normal_1_median_1.rds 4d7c5323652bc90f 617f08f39d8621a2
```

I guess 2 is consistent to what you've found? But this must be wrong because if you run the same task or non-task version twice, everything looks okay.

**Comment by BoPeng** [comment]
That line is a debug message. When you run again using task, the steps are rerun and the files are re-regenerated ....

**Comment by gaow** [comment]
True, it is benign. But the fact that adding `task` and removing `task` will trigger rerun is puzzling. Sometimes I add `task` to send cluster jobs but I'd expect the ones completed before I add `task` should not be re-executed.

**Comment by BoPeng** [comment]
`$DSC_DEBUG$time$sys.self` is different between the runs.


```
> readRDS('old/test/mean/t_1_mean_1.rds')
$est_mean
[1] 2.42456

$DSC_DEBUG
$DSC_DEBUG$time
$DSC_DEBUG$time$user.self
[1] 0.001

$DSC_DEBUG$time$sys.self
[1] 0

$DSC_DEBUG$time$elapsed
[1] 0.001

$DSC_DEBUG$time$user.child
[1] 0

$DSC_DEBUG$time$sys.child
[1] 0

...
> readRDS('test/mean/t_1_mean_1.rds')
$est_mean
[1] 2.42456

$DSC_DEBUG
$DSC_DEBUG$time
$DSC_DEBUG$time$user.self
[1] 0.001

$DSC_DEBUG$time$sys.self
[1] 0.001

$DSC_DEBUG$time$elapsed
[1] 0.001

$DSC_DEBUG$time$user.child
[1] 0

$DSC_DEBUG$time$sys.child
[1] 0


```

**Comment by gaow** [comment]
Ah I see. it records the run time so it could be different ... Still, as I've commented before, the rerun should not be triggered in the first place because the input and scripts are not changed, right? I believe your previous patch has fixed it for rerunning non-task mode. But between task and non-task mode shouldn't it also skip existing runs?

**Comment by BoPeng** [comment]
That is a separate issue that I am checking. The code for non-task signature has been changed but not the task one, so two different signatures are generated.

**Comment by BoPeng** [comment]
oh, it happens because the step content is different with the addition of task keyword.

**Comment by gaow** [comment]
Oh, I guess this type of behavior has been observed before #963 . But for the `task` case maybe it is a bit easier to fix because we do not have to parse the tokens? But what if some options for `task:` are changed -- will issues similar to #963 happen?

**Comment by BoPeng** [comment]
OK, there was no guarantee for this (add task not trigger rerun) but now it is implemented and tested, and should stay as a feature.

**Comment by BoPeng** [comment]
This is different from #963 because change of action options should still trigger rerun.

**Comment by gaow** [comment]
Hmm I do not think it works, at least not from the log message I see:

```
$ rm -rf ~/.sos/
$ rm -rf .sos
$ sos run benchmark-nontask.sos 
INFO: output:   test/t/t_1.rds
INFO: output:   test/normal/normal_1.rds
INFO: Workflow t (ID=c7e4cbe969c6721f) is executed successfully with 1 completed step.
...
INFO: Workflow default (ID=9c2749f3bcfb1efd) is executed successfully with 13 completed steps.

$ sos run benchmark-task.sos 
INFO: e83331e04e5dd935 started
INFO: 7ab6557da4f8a551 started
INFO: 7ab6557da4f8a551 completed
INFO: e83331e04e5dd935 completed
...

INFO: Workflow default (ID=c23d0207eaaa9171) is executed successfully with 13 completed steps and 6 completed tasks.
```

Am I missing something here?

**Comment by BoPeng** [comment]
`task` added one extra space ... fixing.

**Comment by gaow** [comment]
Great, it seems to work now! This ticket discusses too many problems. I think the non-integer sub step message still has some issues that I can see for `jnbinder` script, but I'll come up with a separate example and suggestions later. Close this one for now.
