### ISSUE TITLE
Fail to install sos from local source

### ISSUE THREAD

**Issue by HenryLeongStat** [vatlab/SoS#982]
I run `pip download sos`, and downloaded a lot of packages in my local drive. And then I put those packages into a secure machine without internet. And then I run:

```
for file in sos/*; do
    pip install "$file" --user
done
```

It works fine for most of the packages except for 

`sos-0.9.14.9` (it needs sos-pbs)
`sos-rq-0.9.10.2` (it needs sos-0.9.14.9)
`sos_pbs-0.9.11.0` (it needs sos)
`sos_bioinfo-0.9.10.1` (it needs sos)

So they all somehow depend on each others, but I couldn't install any of them before installing some of them, and none of them are the "first one which should be installed".

@BoPeng Professor, do you have any idea?

**Comment by BoPeng** [comment]
What if you put them all in one line after `pip install`?

**Comment by HenryLeongStat** [comment]
It works!!!!!!!
