### ISSUE TITLE
Slot release bug report

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#986]
I'm running into this prompt:

```
  File "/tmp/tmp87os3f4e.py", line 22, in <listcomp>
    exclude = [i for i, item in enumerate(x) if (x[i], y[i]) in insig]
IndexError: index 100 is out of bounds for axis 0 with size 100
ERROR: Command 'python .sos/purity_4_28_0c345179.py' returned non-zero exit status 1.
ERROR: Command 'python .sos/purity_4_27_d499f3e4.py' returned non-zero exit status 1.
ERROR: Command 'python .sos/purity_4_39_2f724c08.py' returned non-zero exit status 1
.....
^CWARNING: 447e1fc66ec99c4b: Releasing 19 slots from 1 available ones. Please report this bug to SoS developers.
KeyboardInterrupt
```

The ERROR itself is mistake in my codes. The line in question is the purple line of WARNING at the end. It says "Releasing 19 slots from 1 available ones. Please report this bug to SoS developers.". How do we expect users to respond to it? Should they be worried? Perhaps we should ensure and reassure that in any case, all the hold slots are released when there is an error like this?

**Comment by BoPeng** [comment]
I will be interested to see how this happened if this can be reproduced.

**Comment by gaow** [comment]
Unfortunately i cannot reproduce it myself. Might be related to the timing of my `ctrl-c`?

**Comment by BoPeng** [comment]
The goal of that message was to collect cases where the slot manager misbehave. It should be replaced by something clearer or die silently if it is clear user mistake...
