### ISSUE TITLE
Float data in parameter with default int values

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#995]
Here is an MWE:

```
[1]
parameter: prior = 1
print(prior)
```

and 

```
[GW] sos run test.sos --prior 0.5
ERROR: [default_1]: 
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
script_5543089073314416318 in <module>
      if "sos_handle_parameter_" in globals():
---->     prior = sos_handle_parameter_('prior',  1
      )
      print(prior)

ArgumentError: argument --prior: invalid int value: '0.5'
```

Although I can type in `prior = 1.0` to fix the problem, I wonder if this is the best behavior of parameter types.

**Comment by gaow** [comment]
I agree the current behavior makes more sense. I guess my issues is on the error message behavior. Might be easier for users if we can make it less verbose -- even without print traceback would help, if it is easy enough to accomplish for ArgumentError?

type trait seems an overkill and brings us back to the old days of explicitly typed variables ...

**Comment by BoPeng** [comment]
The  `ArgumentError` was defined by sos. You can capture it at [here](https://github.com/vatlab/SoS/blob/master/src/sos/step_executor.py#L91), [here](https://github.com/vatlab/SoS/blob/master/src/sos/step_executor.py#L396), and [here](https://github.com/vatlab/SoS/blob/master/src/sos/step_executor.py#L1132) to reduce the amount of error message.
