### ISSUE TITLE
Testing for docker under windows.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#996]
Related to vatlab/sos-notebook#100

We did not enable docker for windows because appveyor's docker only supported windows VM, and all our images are linux-based. It seems that they have made progress on this and it is now possible to use linux VMs.

https://ci.appveyor.com/project/appveyor-tests/docker-ce/build/1.0.29

**Comment by vibbits** [comment]
yes, indeed, we managed to run a Linux docker via the command line. We will come back tomorrow on our findings - as far as I see you might have to do some cosmetics for the paths...
this is what comes out of sos 
```docker run --rm   -v C:\Data\software\OmicsIntegrationToolkit\InputFiles:C:\Data\software\OmicsIntegrationToolkit\InputFiles -v 'C:\Data\software\OmicsIntegrationToolkit\.sos\docker_run_14024.R':/var/lib/sos/docker_run_14024.R    -t -P -w=C:\Data\software\OmicsIntegrationToolkit\InputFiles     vibbioinfocore/rocker_conda_data_integration Rscript \var\lib\sos\docker_run_14024.R```

and this actually runs:
```docker run --rm   -v /C/Data/software/OmicsIntegrationToolkit/InputFiles:/C/Data/software/OmicsIntegrationToolkit/InputFiles -v /C/Data/software/OmicsIntegrationToolkit/.sos/docker_run_14024.R:/var/lib/sos/docker_run_14024.R    -t -P -w=/C/Data/software/OmicsIntegrationToolkit/InputFiles     vibbioinfocore/rocker_conda_data_integration Rscript /var/lib/sos/docker_run_14024.R```

**Comment by BoPeng** [comment]
The `/C/Data` command is used by the Ubuntu/Linux subsystem, not by native docker for windows, right? I am wondering if you the docker command should be `docker run --rm -v C:\Data ...` from a regular command window.

**Comment by BoPeng** [comment]
I tried to convert the paths to posix format, again blindly because I cannot test here.

**Comment by BoPeng** [comment]
@HenryLeongStat You are the only one who works with windows. Is your machine powerful enough for docker? Are you allowed to install docker on your windows machine?

**Comment by HenryLeongStat** [comment]
Yes, I think so! i7 intel CPU with 16G RAM for my windows Desktop in office. I can install anything since I am in the admin group. I will try the docker for windows!

**Comment by vibbits** [comment]
no, the command shown above (/C/data/...) is the one we could used in the command prompt (anaconda or standard Windows prompt). Most probably there are other options which work as well. We will give feedback on the posix format, too. For the Linux subsystem, it will be most probably (/mnt/C/data or similar).

**Comment by vibbits** [comment]
hi again - thanks for the changes - we discovered another small issue for the anaconda / docker for windows setup. 
the -P flag is no longer added but the slashes for the Rscript command is not Linux style.
```
Fatal error: cannot open file '\var\lib\sos\docker_run_13728.R': Invalid argument
```
the full command:
```
docker run --rm   -v /C//Data/software/OmicsIntegrationToolkit/InputFiles:/C//Data/software/OmicsIntegrationToolkit/InputFiles -v /C//Data/software/OmicsIntegrationToolkit/InputFiles/tmpfraui3t2/docker_run_13728.R:/var/lib/sos/docker_run_13728.R    -t  -w=/C//Data/software/OmicsIntegrationToolkit/InputFiles     vibbioinfocore/rocker_conda_data_integration Rscript \var\lib\sos\docker_run_13728.R
```

**Comment by BoPeng** [comment]
How about now?

**Comment by vibbits** [comment]
yes, the docker runs fine but the output does not seem to be put in the cell. i can see the output in 
``` 
docker logs id_container
```
so I am sure it has run

**Comment by vibbits** [comment]
oh, sorry, too early, the output is created at the end of the run. running the whole setup on Linux, it is immediately written to the cell. so I was mislead...

**Comment by BoPeng** [comment]
Great. The `docker run` command should be running by `pexpect` in sos notebook (thus output immediately) so there might be some caching problem between one of `docker -> linux -> windows -> sos -> notebook`. This is difficult to debug blindly so I will have a look when I get access to a windows machine.

**Comment by HenryLeongStat** [comment]
OK! Let me try!

**Comment by BoPeng** [comment]
There is no `create_signature` in the current trunk. What is your version of sos notebook?

**Comment by HenryLeongStat** [comment]
Was using 0.9.12.9, now I upgrade it to 0.9.15.9:

![capture1](https://user-images.githubusercontent.com/26916551/43107014-c31d8c7e-8ea0-11e8-942e-0b21e26158f8.PNG)

**Comment by BoPeng** [comment]
This is not right. `%frontend` is long gone. Please remove `sos_notebook` from `site-packages` and try again.

**Comment by HenryLeongStat** [comment]
Somehow the PATHs got messed up... Trying to reinstall anaconda3

**Comment by HenryLeongStat** [comment]
Got the error messages:
![capture2](https://user-images.githubusercontent.com/26916551/43110340-0a87a21a-8eb1-11e8-9980-f33a5b3a9aa3.PNG)

**Comment by BoPeng** [comment]
The next step is to play with the command line and see how to get it running. The idea is to map the script to a script inside docker (`-v /Users/.....rb:/var/lib....rb`) and execute it with `ruby /var/lib....rb`.

**Comment by vibbits** [comment]
hope that is is not depending on the anaconda version or docker versions - on my Windows 10 machine
Anaconda 1.8.7 and Docker 18.03.1-ce on Windows (version 1803 - 64-bit), it is possible to run the ruby script successfully.
```
docker run --rm -v /C/Users/Albot_2:/C/Users/Albot_2 -v /C/Users/Albot_2/tmp9t80o1yb/docker_run_13068.rb:/var/lib/sos/docker_run_13068.rb -t -w=/C/Users/Albot_2 ruby ruby /var/lib/sos/docker_run_13068.rb
```
gives
```
%run
ruby: docker_image='ruby'
    line1 = "Cats are smarter than dogs";
    line2 = "Dogs also like meat";

    if ( line1 =~ /Cats(.*)/ )
      puts "Line1 contains Cats"
    end
    if ( line2 =~ /Cats(.*)/ )
      puts "Line2 contains  Dogs"
    end

Line1 contains Cats
```

**Comment by HenryLeongStat** [comment]
Hi vibbits!
I am using windows 7, Docker 18.03.0-ce and Anaconda 5.0.1. Let me try to find out what causes the problem...

**Comment by BoPeng** [comment]
My experience:

1. Install docker for windows 18.06.0-ce-win72, has to reboot to enable it.
2. Install sos and sos notebook 0.9.16.0
3. From "anaconda" prompt, run `jupyter notebook`
4. Run the example, wait a long time and `docker pull` fails. We should give a hint or display the full output of docker pull command (#1005 )
5. Restart the kernel and repeat, `docker pull` works, being asked if I would like to share C drive, answer yes and entered password
6. The test cell succeeds.

In general docker is slow (perhaps the machine is slow), and I do notice the output appear all at once at the end.

**Comment by HenryLeongStat** [comment]
Still failed on my machine:
![capture11111111111](https://user-images.githubusercontent.com/26916551/43726597-307600de-9965-11e8-80dc-3645941afccf.PNG)

```
[I 16:38:00.035 NotebookApp] Saving file at /Untitled2.ipynb
error during connect: Get https://192.168.99.100:2376/v1.37/images/json?filters=%7B%22reference%22%3A%7B%22ruby%22%3Atrue%7D%7D: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Using default tag: latest
Warning: failed to get default registry endpoint from daemon (error during connect: Get https://192.168.99.100:2376/v1.37/info: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.). Using system default: https://index.docker.io/v1/
error during connect: Post https://192.168.99.100:2376/v1.37/images/create?fromImage=ruby&tag=latest: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
error during connect: Get https://192.168.99.100:2376/v1.37/images/json?filters=%7B%22reference%22%3A%7B%22ruby%22%3Atrue%7D%7D: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
[I 16:40:28.705 NotebookApp] Saving file at /Untitled2.ipynb
```

**Comment by BoPeng** [comment]
Did you start docker engine (run the docker program before running the cell)?

**Comment by HenryLeongStat** [comment]
Yes I did! It seems weird...

**Comment by BoPeng** [comment]
If command `docker images` fails on your computer, there must be something wrong with your docker installation.

**Comment by HenryLeongStat** [comment]
Rebooted my desktop and docker starts fine, but got the error as followings:

![capture123123123](https://user-images.githubusercontent.com/26916551/43787481-b77e9714-9a30-11e8-8f52-53f0b1cc85bc.PNG)

**Comment by BoPeng** [comment]
I think you can try to reproduce the problem from outside of SoS. Namely check if you can ssh into a ruby image, if you can mount some directories, and eventually on how to make the aforementioned command work.

**Comment by HenryLeongStat** [comment]
OK! Let me see...

**Comment by BoPeng** [comment]
The problem is that @HenryLeongStat is using Docker Toolbox under windows 7. In this system, a virtualbox mounts `c:/Users` as `/Users`, so the mounting path should be

```
-v /Users/user:/var/lib/whatever
```
instead of
```
-v /C/Users/user:/var/lib/whatever
```
that SoS assumes. Since in theory users can configure virtualbox shared directory with arbitrary pathname, there is very little we can do on the SoS side.

Solution?
1. Allow users to write this mapping into some sos configuration file.
2. Probe virtual box for the path mapping, which is possible with virtualbox command line.

**Comment by BoPeng** [comment]
Documentation updated with information on docker toolbox. Closing the ticket because it is way easier for users to change virtual box configuration instead of letting SoS to detect the docker version and configure command line.
