### ISSUE TITLE
Running SoS-notebook in Linux subsystem on Windows

### ISSUE THREAD

**Issue by chdeb** [vatlab/SoS#997]
Following this [blog](https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly) we were able to setup Docker for Linux subsystem 18.04 in Windows 10 (1803). Important changes are the deamon setting in Docker on Windows (port 2375) and the mounting in Linux subsystem 
```
sudo nano /etc/wsl.conf

# Now make it look like this and save the file when you're done:
[automount]
root = /
options = "metadata"
```

The installed sos version is 0.9.15.3, the sos-notebook version is 0.9.15.8.

If we try to start a docker within Jupyter notebook SoS cell we get the following error:
```
/usr/bin/docker: Error response from daemon: driver failed programming external connectivity on endpoint pensive_goodall (6d0f5f07ce08b5d69c5b8892015a527fe6af40484e9684aa1a590b740082fcab): 
Error starting userland proxy: mkdir /port/tcp:0.0.0.0:32777:tcp:172.17.0.2:8787: input/output error.
```
```
Docker daemon failed (exitcode=125). The script has been saved to /c/Users/chdeb/Git/OmicsIntegrationToolkit/.sos/docker_run_23.R. 
To reproduce the error please run:
docker run --rm --security-opt label:disable  -v /c/Users/chdeb/Git/OmicsIntegrationToolkit/InputFiles:/c/Users/chdeb/Git/OmicsIntegrationToolkit/InputFiles 
-v /c/Users/chdeb/Git/OmicsIntegrationToolkit/.sos/docker_run_23.R:/var/lib/sos/docker_run_23.R
    -t -P -w=/c/Users/chdeb/Git/OmicsIntegrationToolkit/InputFiles -u 1000:1000  
  vibbioinfocore/rocker_conda_data_integration Rscript /var/lib/sos/docker_run_23.R
```
We removed the -P flag and were able to run it successfully on the Linux subsystem. 
We would be able to remove the EXPOSE command in the Dockerfile so that the Jupyter notebook would run the docker.

**Comment by BoPeng** [comment]
I have no idea what this `Error response from daemon: driver failed programming external connectivity on endpoint` is. Further research is needed.

Option `-P` was set as default and can be overridden by option `--port`. I have changed the behavior to

* No `-P` or `-p` by default
* `--port xxx` would add `-p xxx`
* `--port` would add `-P`.

This is subject to change if it breaks docker support on linux.

**Comment by BoPeng** [comment]
Reported problem has been resolved, although running windows containers is still not supported. #1006.
